docs/platforms/flutter/upload-debug.mdx
Added missing configuration fields and documented updated behaviour for `sentry-dart-plugin`.
[Improve sentry-docs #227](https://github.com/getsentry/sentry-dart-plugin/issues/227)
=> docs(flutter): Update sentry dart plugin docs

docs/platforms/python/migration/raven-to-sentry-sdk.mdx, src/middleware.ts
Fix #10397 & #10385
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute …
=> fix redirects

platform-includes/user-feedback/sdk-api-example/javascript.mdx
See: https://github.com/getsentry/sentry/issues/73194
=> User Feedback: remove `extra` from sample

docs/platforms/javascript/guides/react/features/react-router.mdx
resolves https://github.com/getsentry/sentry-docs/issues/10478 …
=> fix: update react router tracing link

docs/platforms/python/integrations/spark/index.mdx
Fixing a typo and some capitalization.
Direct link to preview: https://sentry-docs-git-ivana-spark-integration-fixes.sentry.dev/platforms/python/integrations/spark/
=> fix(python): Fix typo, capitalization in Spark integration

docs/platforms/dart/features/index.mdx, docs/platforms/flutter/features/index.mdx
Flutter Features page has some missing information
Closes https://github.com/getsentry/sentry-dart/issues/2117 …
=> flutter: add missing features in the features page

docs/product/sentry-basics/integrate-backend/getting-started.mdx
=> Title case headings

src/components/lambdaLayerDetail.tsx
=> ref(aws): Sort aws lambda ARN region dropdown values

src/components/banner/index.tsx, src/middleware.ts
- [x ] Urgent deadline (GA date, etc.): banner needs to go up today …
=> update marketing banner and add redirect

docs/platforms/javascript/common/user-feedback/configuration/index.mdx
Relates to https://github.com/getsentry/sentry-javascript/issues/12599 …
=> doc(feedback): Add more snippets for User Feedback

docs/platforms/javascript/common/sourcemaps/troubleshooting_js/artifact-bundles.mdx, docs/platforms/javascript/common/sourcemaps/troubleshooting_js/index.mdx, docs/platforms/javascript/common/sourcemaps/troubleshooting_js/legacy-uploading-methods.mdx
Since v8 these sveltekit, remix, and nextjs support debug IDs.
=> Update platforms that can use debug IDs

vercel.json
CSP and NEL reports produce too much noise in the sentry-docs project (see related https://github.com/getsentry/sentry/issues/68260), so we're switching them to separate sentry projects. …
=> chore: fix CSP and NEL reports to separate sentry projects

src/components/onboarding/index.tsx
=> fix onboarding buttons z index (< search results)

docs/organization/data-storage-location/index.mdx
=> remove old banner about data storage location workshop

docs/platforms/javascript/common/tracing/instrumentation/opentelemetry.mdx
Forgot about something there, small adjustments to the otel docs.
=> fix: Fix custom otel docs with correct imports

docs/platforms/javascript/guides/aws-lambda/layer/index.mdx
Related: https://github.com/getsentry/sentry-javascript/issues/12465
=> docs(aws): Update v7 layer version and add instructions for the v7 version of the sdk

platform-includes/migration/javascript-v8/important-changes/javascript.react.mdx
Based on https://github.com/getsentry/sentry-javascript/blob/aafb4e7b7e855f41cddd51191f2da8d3ddadaa02/packages/react/package.json#L52 …
=> Update min react version in react migration docs.

src/components/search/index.tsx, src/components/search/search.module.scss
=> fix focus hijacking on mobile search input

docs/concepts/data-management/event-grouping/index.mdx, docs/concepts/key-terms/environments/index.mdx, docs/concepts/key-terms/tracing/trace-view.mdx, docs/organization/integrations/integration-platform/index.mdx, docs/organization/integrations/integration-platform/webhooks/issue-alerts.mdx, docs/organization/integrations/integration-platform/webhooks/metric-alerts.mdx, docs/product/alerts/create-alerts/routing-alerts.mdx, docs/product/crons/job-monitoring.mdx, docs/product/explore/metrics/metrics-explorer-page.mdx, docs/product/insights/assets.mdx, docs/product/insights/caches/index.mdx, docs/product/insights/queries.mdx, docs/product/insights/queue-monitoring/index.mdx, docs/product/insights/requests.mdx, docs/product/insights/web-vitals/index.mdx, docs/product/issues/suspect-commits/index.mdx, docs/product/performance/retention-priorities/index.mdx, docs/product/projects/index.mdx, docs/product/projects/project-details/index.mdx, docs/product/sentry-basics/integrate-frontend/configure-scms.mdx, docs/product/sentry-basics/integrate-frontend/create-new-project.mdx, docs/product/sentry-basics/integrate-frontend/generate-first-error.mdx, docs/product/sentry-basics/integrate-frontend/upload-source-maps.mdx, vercel.json
=> fix: Arcade embeds fullscreen permission

docs/platforms/javascript/common/best-practices/multiple-sentry-instances.mdx
We apparently forgot to update this for v8 etc.
=> fix: Fix multi instance code snippet

platform-includes/performance/traces-sampler-as-filter/javascript.mdx
Closes https://github.com/getsentry/sentry-docs/issues/10542
=> feat: Improve `tracesSampler` example

platform-includes/distributed-tracing/custom-instrumentation/javascript.mdx
See https://github.com/getsentry/sentry-javascript/issues/12334#issuecomment-2173351094, forgot to fix this here as well!
=> fix: Fix distributed tracing docs for v8

docs/platforms/python/integrations/starlette/index.mdx
=> Python/Starlette: Added new config option

docs/platforms/flutter/upload-debug.mdx
=> Update dart plugin version

docs/pricing/index.mdx
=> Remove extra definition of PAYG

docs/pricing/quotas/spike-protection.mdx
Add spans to the spike protection docs page.
=> fix: include spans in spike protection page

docs/platforms/python/configuration/options.mdx
Two settings where missing in the documentation. Added them . …
=> Python: Added some missing config options

src/middleware.ts
Add redirect for hidden pricing page to fix 404 #10554 …
=> add redirect for old pricing page

.github/workflows/algolia-index.yml
=> Ignore the whole /changelog before Algolia index build (2)

docs/product/alerts/notifications/index.mdx
this pr updates the date for when we send the weekly report.
=> chore(docs): Update day for weekly report

docs/platforms/python/configuration/options.mdx
Clarify user confusion [here](https://github.com/getsentry/sentry-python/issues/3209#issuecomment-2202444443) by noting that the Sentry server enforces an limit on HTTP body size sent with an event. …
=> Note server http body size limit

docs/platforms/javascript/common/configuration/tree-shaking.mdx
Some more clarification of where tree shaking applies.
=> fix(js): Add note about tree shaking relevance

platform-includes/performance/traces-sampler-as-sampler/javascript.mdx
This was partially done here: https://github.com/getsentry/sentry-docs/pull/10544 but one place was forgotten.
=> feat(js): Improve tracesSampler example

docs/platforms/javascript/common/index.mdx, platform-includes/capture-error/javascript.bun.mdx, platform-includes/getting-started-config/javascript.bun.mdx, platform-includes/getting-started-use/javascript.bun.mdx
Improve guide for bun + use the correct package name for a code snippet in "usage".
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact …
=> docs(bun): Improve bun documentation

src/middleware.ts
=> fix trycatch integration 404

docs/platforms/go/guides/gin/index.mdx
Import should have name else `sentry` reference is undefined
- [/] None: Not urgent, can wait up to 1 week+
=> docs: missing import name for sentry-go

docs/platforms/flutter/upload-debug.mdx
Add info that source contexts work on Flutter Web as well.
Relates to https://github.com/getsentry/sentry-dart-plugin/pull/247
=> docs(flutter): Update `Uploading Source Context` section

src/components/codeBlock/code-blocks.module.scss, src/components/configKey.tsx, src/components/docPage/type.scss, src/mdx.ts
- Fixes #10583
- Fixes #10468  …
=> fix: Resolve regex issues in code blocks

src/components/changelog/list.tsx
=> fix(changelog): Render correct dates in sidebar

docs/product/insights/web-vitals/index.mdx
Updates doc now that we support mobile browsers for web vitals.
=> feat(web-vitals): mobile browser support

docs/platforms/javascript/common/enriching-events/scopes/index.mdx
Fixes https://github.com/getsentry/sentry-javascript/issues/12808
=> fix: Clarify isolation/global/current scope usage

docs/platforms/elixir/enriching-events/context/index.mdx
- Fix for #3213 
- Fix references to context function name
- Remove deprecated additional info section
=> fix function names in elixir docs and remove deprecated additional info

app/changelog/page.tsx, prisma/seed/seed.mjs, src/components/changelog/list.tsx
=> Fix(changelog): Render mdx in changelog summary

package.json, yarn.lock
Reverts getsentry/sentry-docs#10623 because it breaks dev mode 😭
=> Revert "deps: Bump `@sentry/nextjs` to `8.16.0`"

docs/concepts/key-terms/environments/index.mdx, docs/organization/integrations/integration-platform/index.mdx, docs/organization/integrations/integration-platform/webhooks/issue-alerts.mdx, docs/organization/integrations/integration-platform/webhooks/metric-alerts.mdx, docs/organization/integrations/notification-incidents/discord/index.mdx, docs/product/alerts/create-alerts/routing-alerts.mdx, docs/product/insights/queries.mdx, docs/product/insights/web-vitals/index.mdx, docs/product/issues/suspect-commits/index.mdx, docs/product/sentry-basics/integrate-frontend/configure-scms.mdx, docs/product/sentry-basics/integrate-frontend/create-new-project.mdx, docs/product/sentry-basics/integrate-frontend/generate-first-error.mdx
Change wording from "gif" to "interactive demo" for arcades.
fixes #10559 …
=> change gif to interactive demo

docs/product/releases/setup/index.mdx
Links to release page for php SDK
=> Link to php release sdk

platform-includes/distributed-tracing/how-to-use/javascript.mdx
Based on discord feedback: https://discord.com/channels/621778831602221064/621778831602221072/1260913426633330780
ref https://github.com/getsentry/sentry-javascript/blob/38ec761a016ecd42fbf428f8b1799751bda10a49/packages/browser/src/tracing/browserTracingIntegration.ts#L314C65-L314C72 …
=> Fix meta tag name for baggage

docs/platforms/javascript/common/configuration/integrations/graphql.mdx
We had incorrect docs for graphql js integration, this fixes that …
=> Fix graphql integration docs

docs/platforms/javascript/common/configuration/integrations/localvariables.mdx
resolves https://github.com/getsentry/sentry-javascript/issues/12863 …
=> Add note about minification with js local variables

develop-docs/getting-started/index.mdx, src/components/header.tsx
=> fix: Set correct link for changelog

docs/product/insights/web-vitals/index.mdx, docs/product/insights/web-vitals/web-vitals-concepts.mdx
We've made some changes to streamline how performance score calculation works in the web vitals product. Updates these docs to more accurately reflect these changes.
=> feat(insights): Updates webvital docs to reflect new changes with performance score calculation

docs/product/performance/getting-started.mdx
resolves https://github.com/getsentry/sentry-docs/issues/10677
Also re-organizes JavaScript section to include more SDKs. …
=> fix: Fix sdk links in performance getting started page

docs/platforms/android/tracing/instrumentation/performance-metrics.mdx, docs/platforms/apple/common/tracing/instrumentation/performance-metrics.mdx, docs/platforms/dart/tracing/instrumentation/performance-metrics.mdx, docs/platforms/dotnet/common/tracing/instrumentation/performance-metrics.mdx, docs/platforms/flutter/tracing/instrumentation/performance-metrics.mdx, docs/platforms/java/common/tracing/instrumentation/performance-metrics.mdx, docs/platforms/javascript/common/tracing/instrumentation/performance-metrics.mdx, docs/platforms/powershell/tracing/instrumentation/performance-metrics.mdx, docs/platforms/python/tracing/instrumentation/performance-metrics.mdx, docs/platforms/react-native/tracing/instrumentation/performance-metrics.mdx, docs/platforms/ruby/common/tracing/instrumentation/performance-metrics.mdx, docs/product/performance/metrics.mdx, includes/custom-measurements-disclaimer.mdx
With the recent pivot in metrics, we do not want to encourage users to switch from custom measurements to custom metrics yet.
Closes https://github.com/getsentry/sentry/issues/73922
=> feat: Remove custom measurements disclaimer

.github/workflows/algolia-index.yml, package.json, scripts/make-vercel-json.mjs, skip-build.sh, src/components/search/index.tsx, src/isDeveloperDocs.ts, src/middleware.ts
please rename `DEVELOPER_DOCS=1` to `NEXT_PUBLIC_DEVELOPER_DOCS=1` before the merge
both on Github secrets and on Vercel
=> fix dev docs search results priority;

docs/platforms/python/integrations/langchain/index.mdx, docs/platforms/python/integrations/openai/index.mdx
* Added information about a new config option for AI integrations. Those where introduced in a bug fix that prevented a crash for a customer that will be released on 2024-07-15 …
=> [Python] Updated new config options for AI integrations

docs/platforms/python/configuration/options.mdx
We added [two new transport options](https://github.com/getsentry/sentry-python/commit/4fb51f2d03351197824d0641fb0fd26779458f1d) to the Python SDK in 2.10.0. Documenting them here.
Direct link to preview: https://sentry-docs-git-ivana-pythonnew-transport-options.sentry.dev/platforms/python/configuration/options/#transport-options
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 …
=> feat(python): Add new transport options

app/changelog/%5Fadmin/page.tsx
=> attempting to add guidelines for the changelog

skip-build.sh, src/components/header.tsx, src/components/mobileMenu/index.tsx, src/getChangelogLink.ts
Fixes the changelog link for dev docs on mobile
=> fix: Use correct changelog link on mobile

docs/product/insights/caches/index.mdx, docs/product/insights/queue-monitoring/index.mdx
Cache / Queue insights are now GA.
See: https://blog.sentry.io/backend-insights-with-caches-queues-requests-queries/
=> feat(insights): cache and queue insights are now GA

src/middleware.ts
Adds more redirects related to Issues settings.
Resolves [#10676](https://github.com/getsentry/sentry-docs/issues/10676)
=> chore(redirects): add more Issues related redirects

docs/platforms/android/configuration/options.mdx, platform-includes/enriching-events/attachment-max-size/android.mdx
Updates `Sentry.init` to `SentryAndroid.init` where applicable.
fixes https://github.com/getsentry/sentry-docs/issues/5679
=> fix(Android): changes to SentryAndroid.init for Android platform

docs/contributing/environment.mdx
Updates the instructions for running a dev server locally
=> docs: Update environment setup instructions

develop-docs/application/api/public.mdx, develop-docs/application/feature-flags/index.mdx, develop-docs/sdk/features.mdx, src/middleware.ts
=> fix: Update 404 links for develop-docs

app/platform-redirect/page.tsx, src/middleware.ts
=> fix: Handle product 404 links

docs/platforms/android/features/index.mdx, docs/platforms/dart/features/index.mdx, docs/platforms/flutter/features/index.mdx, docs/platforms/react-native/features/index.mdx
Adds ANR and App Hangs support to Flutter and React Native feature pages. Also refactors links to use <Link> and <PlatformLink> components and fixes some smaller errors/issues.
fixes https://github.com/getsentry/sentry-docs/issues/5771
=> feat(Mobile): adds ANR/App Hangs to RN+Flutter Features

develop-docs/application/dynamic-sampling/architecture.mdx, develop-docs/integrations/azuredevops.mdx, develop-docs/integrations/msteams/index.mdx, develop-docs/sdk/event-payloads/index.mdx, develop-docs/sdk/overview.mdx, develop-docs/sdk/performance/index.mdx
relates to https://github.com/getsentry/sentry-docs/issues/10747
=> fix some develop 404s

platform-includes/session-replay/setup/javascript.mdx
I found some typos on the capitalization of Session Replay in the docs.
=> Updating casing for Session Replay docs

docs/platforms/javascript/common/session-replay/issue-types.mdx, docs/product/issues/issue-details/replay-issues/hydration-error.mdx, docs/product/issues/issue-details/replay-issues/index.mdx
Got some review comments on https://github.com/getsentry/sentry-docs/pull/10686 after it was merged, addressing them here
=> docs(replay): Fix typos and more in Replay Hydration Error docs

develop-docs/application/dynamic-sampling/architecture.mdx
This PR updates dynamic sampling docs with new links and better explanations.
=> fix(dynamic-sampling): Update docs on the sampling algorithm

docs/platforms/javascript/common/best-practices/micro-frontends.mdx
https://docs.sentry.io/platforms/javascript/best-practices/micro-frontends/ …
=> Fix language for code example in Micro Frontends doc

.github/workflows/algolia-index.yml
Fixes algolia index creation in the case when content changes in both apps (user docs + developer docs)
=> fix: Update algolia index updates in gh actions

develop-docs/application/api/index.mdx, docs/api/pagination.mdx
Triggers re-creation of algolia indices
=> ci: Trigger index re-creation

docs/platforms/javascript/common/configuration/integrations/redis.mdx
closes https://github.com/getsentry/sentry-docs/issues/10700
=> feat(redis): Add redis and integration options

docs/product/alerts/create-alerts/issue-alert-config.mdx
Adds new `IS IN` filter condition
=> update docs to include is in

docs/platforms/react-native/session-replay/index.mdx
Fix RN SR snippet `integration:` -> `integrations:`
fixes https://github.com/getsentry/sentry-react-native/issues/3962
=> fix(RN): typo in RN snippet

.github/workflows/dependency-review.yml
Update Dependency Review actions.
=> ci: bump dependency review action

src/components/home.tsx
Added additional styling to account for medium screen sizes.
Addressing this issue:
=> Fixed direct links styling on medium screen sized

docs/platforms/react-native/session-replay/index.mdx
=> fix(replay): integrations pluralized

docs/platforms/javascript/common/configuration/integrations/index.mdx, platform-includes/configuration/integrations/lazy-loading-replay/javascript.angular.mdx, platform-includes/configuration/integrations/lazy-loading-replay/javascript.astro.mdx, platform-includes/configuration/integrations/lazy-loading-replay/javascript.electron.mdx, platform-includes/configuration/integrations/lazy-loading-replay/javascript.ember.mdx, platform-includes/configuration/integrations/lazy-loading-replay/javascript.gatsby.mdx, platform-includes/configuration/integrations/lazy-loading-replay/javascript.mdx, platform-includes/configuration/integrations/lazy-loading-replay/javascript.nextjs.mdx, platform-includes/configuration/integrations/lazy-loading-replay/javascript.react.mdx, platform-includes/configuration/integrations/lazy-loading-replay/javascript.remix.mdx, platform-includes/configuration/integrations/lazy-loading-replay/javascript.solid.mdx, platform-includes/configuration/integrations/lazy-loading-replay/javascript.svelte.mdx, platform-includes/configuration/integrations/lazy-loading-replay/javascript.sveltekit.mdx, platform-includes/configuration/integrations/lazy-loading-replay/javascript.vue.mdx, platform-includes/session-replay/setup/javascript.angular.mdx, platform-includes/session-replay/setup/javascript.astro.mdx, platform-includes/session-replay/setup/javascript.electron.mdx, platform-includes/session-replay/setup/javascript.ember.mdx, platform-includes/session-replay/setup/javascript.gatsby.mdx, platform-includes/session-replay/setup/javascript.mdx, platform-includes/session-replay/setup/javascript.nextjs.mdx, platform-includes/session-replay/setup/javascript.react.mdx, platform-includes/session-replay/setup/javascript.remix.mdx, platform-includes/session-replay/setup/javascript.svelte.mdx, platform-includes/session-replay/setup/javascript.sveltekit.mdx, platform-includes/session-replay/setup/javascript.vue.mdx
closes https://github.com/getsentry/sentry-docs/issues/10801
=> docs(js-integrations): Add snippet for dynamic loading

platform-includes/getting-started-use/javascript.nestjs.mdx
Should be merged after the new nestjs setup is released, but prepared this in the meantime for review.
Setup still WIP and will be introduced with [this PR](https://github.com/getsentry/sentry-javascript/pull/12920)
=> docs(nestjs): Update nestjs sdk docs with new setup

apps/changelog/package.json
We need to generate the prisma schema before building.
=> ci(changelog): Fix Vercel deployment

apps/changelog/src/app/(changelog)/layout.module.css, apps/changelog/src/app/(changelog)/layout.tsx, apps/changelog/src/app/globals.css, apps/changelog/tailwind.config.ts
=> ref(changelog): Clean up some styling

platform-includes/configuration/capture-console/javascript.mdx
Version 7 of the loader has to be hard-coded, as we do not have a variable for this. This is fine, as the version is not upgraded very often anymore.
fixes https://github.com/getsentry/sentry-javascript/issues/13042
=> fix(JS): Hardcode version 7 script source for loader

.github/CODEOWNERS, apps/changelog/vercel.json
https://www.notion.so/sentry/Sentry-Changelog-678db9c84d0a4b8c97b8ef2165e5ae47 …
=> feat(changelog): minimal CSP to start with

app/not-found.tsx
the report 404 button doesn't populate the correct path sometimes 
fixes #10728
=> fix 404 report host and pathname

platform-includes/metrics/configure/react-native.mdx
Adds new RN metrics config snippet to replace the default JS one which has an incorrect version note that does not apply to RN.
fixes https://github.com/getsentry/sentry-react-native/issues/3971
=> fix(RN): RN metrics configure snippet

src/components/header.tsx, src/components/mobileMenu/index.tsx, src/getChangelogLink.ts
Replaces dead links with hardcoded versions.
=> fix: Hardcode changelog links

docs/platforms/android/index.mdx, docs/platforms/apple/common/index.mdx, docs/platforms/dart/index.mdx, docs/platforms/dotnet/index.mdx, docs/platforms/flutter/index.mdx, docs/platforms/javascript/common/index.mdx, docs/platforms/javascript/guides/angular/angular1.mdx, docs/platforms/javascript/guides/aws-lambda/install/cjs-layer.mdx, docs/platforms/javascript/guides/aws-lambda/install/cjs-npm.mdx, docs/platforms/javascript/guides/aws-lambda/install/esm-npm.mdx, docs/platforms/javascript/guides/azure-functions/index.mdx, docs/platforms/javascript/guides/electron/index.mdx, docs/platforms/javascript/guides/gatsby/index.mdx, docs/platforms/javascript/guides/gcp-functions/index.mdx, docs/platforms/react-native/index.mdx, docs/platforms/ruby/common/index.mdx, platform-includes/getting-started-config/javascript.deno.mdx, platform-includes/getting-started-node/javascript.mdx
Reverts getsentry/sentry-docs#10815
=> Revert "add tracing and profiling explanation to check boxes"

platform-includes/configuration/capture-console/javascript.mdx, platform-includes/configuration/contextlines/javascript.mdx, platform-includes/configuration/debug/javascript.mdx, platform-includes/configuration/dedupe/javascript.mdx, platform-includes/configuration/extra-error-data/javascript.mdx, platform-includes/configuration/http-client/javascript.mdx, platform-includes/configuration/rewrite-frames/javascript.mdx, platform-includes/configuration/sessiontiming/javascript.mdx
follow-up for https://github.com/getsentry/sentry-docs/pull/10857
The checksums are taken from here: https://github.com/getsentry/sentry-release-registry/blob/master/packages/npm/%40sentry/browser/7.118.0.json
=> fix(JS): Hardcode v7 script for pluggable integrations

src/components/platformSelector/index.tsx, src/components/sidebar/platformSidebar.tsx
adds a chevron on platform links
=> feat: display chevron on platform link

docs/platforms/javascript/common/best-practices/sentry-testkit.mdx
Found a broken link in the Sentry Testkit page.
=> (javascript): fix testkit broken link

app/globals.css, src/components/docPage/type.scss
fixes [#10320](https://github.com/getsentry/sentry-docs/issues/10320)
=> fix selection color for users with high contrast screen setting

docs/platforms/apple/common/enriching-events/viewhierarchy/index.mdx
Added information about new `reportAccessibilityIdentifier` option.
=> feat(Apple): reportAccessibilityIdentifier option

src/components/configKey.tsx
fixes [#9857](https://github.com/getsentry/sentry-docs/issues/9857)
=> fix common options permalink aria label

docs/platforms/javascript/common/best-practices/shared-environments.mdx
Because of the hub and versioned carrier changes in v8, we should recommend people use it in the shared environments setup. …
=> feat: Update shared-environments js doc to recommend v8

docs/platforms/dotnet/guides/aspnet/index.mdx, docs/platforms/dotnet/guides/aspnetcore/index.mdx, docs/platforms/dotnet/guides/aws-lambda/index.mdx, docs/platforms/dotnet/guides/azure-functions-worker/index.mdx, docs/platforms/dotnet/guides/blazor-webassembly/index.mdx, docs/platforms/dotnet/guides/entityframework/index.mdx, docs/platforms/dotnet/guides/extensions-logging/index.mdx, docs/platforms/dotnet/guides/google-cloud-functions/index.mdx, docs/platforms/dotnet/guides/log4net/index.mdx, docs/platforms/dotnet/guides/maui/index.mdx, docs/platforms/dotnet/guides/nlog/index.mdx, docs/platforms/dotnet/guides/serilog/index.mdx, docs/platforms/dotnet/guides/uwp/index.mdx, docs/platforms/dotnet/guides/winforms/index.mdx, docs/platforms/dotnet/guides/winui/index.mdx, docs/platforms/dotnet/guides/wpf/index.mdx, docs/platforms/dotnet/index.mdx, platform-includes/getting-started-verify/dotnet.aspnetcore.mdx
Closes https://github.com/getsentry/sentry-dotnet/issues/2532
=> fix(.NET): Added `Verify`

docs/product/issues/issue-priority/index.mdx
Updating issue priority documentation to explain the feature differences between free/team plans and business plans. 
Fixes https://github.com/getsentry/sentry/issues/74979
=> chore(issue-priority): Update documentation for enhanced issue priority

develop-docs/application/api/public.mdx
Updating the sample code to reflect the new name of the param
=> nit(api): Update Publish API Instructions

docs/cli/configuration.mdx
Our CLI supports IDs as well as slugs, so updating the config docs of the CLI to reflect the change
=> chore(sentry-cli): Update Docs to Reflect Id Support in our CLI

docs/platforms/elixir/integrations/oban/index.mdx
Doc fixes inspired by https://github.com/getsentry/sentry-elixir/issues/757.
=> Improve Oban integration docs (Elixir)

docs/product/issues/issue-priority/index.mdx
Add log levels to the priority level definitions
=> Add log level info to priority definition

docs/concepts/key-terms/tracing/trace-view.mdx
I noticed there was inconsistency in the capitalism of Trace View. I confirmed with Sasha it should be capitalized, so I made those edits to be consistent here.
=> Capitalize Trace View

develop-docs/sdk/processes/index.mdx, develop-docs/sdk/processes/releases/index.mdx, develop-docs/sdk/processes/triaging/index.mdx, src/middleware.ts
=> Add docs about SDK processes

docs/platforms/apple/common/tracing/instrumentation/automatic-instrumentation.mdx
Remove experimental note for TTFD, which isn't experimental anymore. Change wording to mention when those features are available and not that they are new in 8.4.0, which was released over a year ago.
=> fix(apple): Small TTID/TTFD fixes

develop-docs/development/environment/index.mdx
Attempts to make the docs for starting the local ingestion pipeline idiot proof (benchmark: myself).
=> Update docs for starting Relay in dev env

docs/platforms/javascript/config.yml, docs/platforms/javascript/guides/angular/config.yml, docs/platforms/javascript/guides/astro/config.yml, docs/platforms/javascript/guides/aws-lambda/config.yml, docs/platforms/javascript/guides/azure-functions/config.yml, docs/platforms/javascript/guides/bun/config.yml, docs/platforms/javascript/guides/capacitor/config.yml, docs/platforms/javascript/guides/connect/config.yml, docs/platforms/javascript/guides/cordova/config.yml, docs/platforms/javascript/guides/deno/config.yml, docs/platforms/javascript/guides/electron/config.yml, docs/platforms/javascript/guides/ember/config.yml, docs/platforms/javascript/guides/express/config.yml, docs/platforms/javascript/guides/fastify/config.yml, docs/platforms/javascript/guides/gatsby/config.yml, docs/platforms/javascript/guides/gcp-functions/config.yml, docs/platforms/javascript/guides/hapi/config.yml, docs/platforms/javascript/guides/koa/config.yml, docs/platforms/javascript/guides/nestjs/config.yml, docs/platforms/javascript/guides/nextjs/config.yml, docs/platforms/javascript/guides/node/config.yml, docs/platforms/javascript/guides/react/config.yml, docs/platforms/javascript/guides/remix/config.yml, docs/platforms/javascript/guides/solid/config.yml, docs/platforms/javascript/guides/svelte/config.yml, docs/platforms/javascript/guides/sveltekit/config.yml, docs/platforms/javascript/guides/vue/config.yml, docs/platforms/javascript/guides/wasm/config.yml
ref https://github.com/getsentry/sentry-docs/issues/10938
Have more detailed categories for JavaScript SDKs so we can restructure the `supported` and `notSupported` sections throughout the docs. …
=> feat: Restructure categories for JavaScript SDKs

docs/product/issues/issue-details/breadcrumbs/index.mdx
Merged [my last PR](https://github.com/getsentry/sentry-docs/pull/10685) as it was, but forgot to add a small correction for a new filter option that was added per EA feedback.
=> fix(breadcrumbs): Small correction from recent change

docs/product/issues/issue-details/replay-issues/hydration-error.mdx
Only available in EA
Can be removed once we close:
* https://github.com/getsentry/sentry/issues/70199
=> Replay: Hydration Error is EA

src/components/codeBlock/code-blocks.module.scss
=> fix: Apply css diff styles only to first element

src/components/pageGrid.tsx, src/docTree.ts
=> reflect sidebar sorting  on PageGrid

redirects.js
=> fix api ratelimits redirect

docs/platforms/javascript/common/session-replay/issue-types.mdx
See: https://github.com/getsentry/sentry-docs/pull/11044#issuecomment-2278341483
Can be removed once we close:
* https://github.com/getsentry/sentry/issues/70199
=> Replay: JS platform replay issue EA

docs/product/issues/issue-details/index.mdx
This ensures a consistent usage of the term trace-related issues.
=> copy(issues): Wording update for trace-related issues

apps/changelog/sentry.client.config.ts
Flips the behaviour because @smeubank wants to see what happens.
=> feat(changelog): Apply tag for 3rd party errors

docs/platforms/javascript/common/troubleshooting/index.mdx
If a session replay is embedded into the envelope, decoding it to text will yield a `400 Bad Request` when tunnelling. So we need to pass the content as bytes into the body in order to work. …
=> docs: support session replay tunnelling for javascript

docs/platforms/python/integrations/index.mdx
=> [Python] Fix for the integrations list

src/components/codeBlock/code-blocks.module.scss
=> fix split code blocks for code blocks without specified language

docs/platforms/python/integrations/index.mdx
=> Startlite is not autoenabled

docs/platforms/javascript/common/tracing/instrumentation/automatic-instrumentation.mdx
Will merge when https://github.com/getsentry/sentry-javascript/pull/13255 goes through.
=> feat(js): update enableLongAnimationFrame default to true

docs/platforms/index.mdx
Clean up language and delete SDKs that are no longer being maintained.
=> Clean up platforms page

docs/product/alerts/uptime-monitoring/automatic-detection.mdx
Updates how automatic detection works to reflect our latest changes.
=> Update uptime's automatic detection description

develop-docs/application/feature-flags/flagpole.mdx
The flagpole docs are missing from the sidebar. I think the changes in #11105 didn't format the page header correctly.
=> Convert from markdown title to yaml title

docs/platforms/ruby/common/configuration/options.mdx, platform-includes/configuration/config-intro/ruby.mdx
This makes it look better and now finally has a sidebar.
=> chore(ruby): Update common options to match other platforms

docs/platforms/elixir/integrations/oban/index.mdx
=> Document new feature to Elixir's Oban integration

docs/platforms/javascript/common/opentelemetry/using-opentelemetry-apis.mdx
Add focus on exporting data in the OTEL TracerProvider section
=> docs: Update TracerProvider docs

platform-includes/sourcemaps/artifact-bundles/javascript.mdx
This pull request just removes two words that appear to have been accidentally repeated in the help document text. …
=> chore: Remove duplicate words

platform-includes/configuration/drain-example/javascript.node.mdx
https://github.com/getsentry/sentry-javascript/issues/13448
=> docs: Add note for sigterm event

docs/platforms/php/common/data-management/data-collected.mdx, docs/platforms/php/guides/laravel/data-management/data-collected.mdx, docs/platforms/php/guides/symfony/data-management/data-collected.mdx
Add data collected pages for the PHP SDKs based on the Python pages.
Fixes getsentry/sentry-php#1721
=> Add data collected pages for the PHP SDKs

docs/platforms/php/common/configuration/options.mdx
=> Add missing `trace_propagation_targets` option to PHP docs

docs/platforms/android/integrations/apollo/index.mdx, docs/platforms/android/integrations/apollo3/index.mdx, docs/platforms/java/common/tracing/instrumentation/apollo.mdx, docs/platforms/java/common/tracing/instrumentation/apollo3.mdx
Adds notes about incompatibility with Apollo4 in our Android+Java pages.
=> chor(apollo): Add note about incompatibility with Apollo4

app/robots.txt/route.ts, public/robots.txt
=> fix: Dynamic robots.txt

includes/profiling-mode-explanation.mdx
Add a include about continuous profiling SDK modes that we can include to different onboarding docs to explain about how the two profiling modes work together. …
=> feat: add profiling compatibility include

docs/platforms/javascript/common/configuration/options.mdx
Remove link to RN native init from Cordova/Capacitor. We don't currently have pages to link to for these platforms.
fixes part of https://github.com/getsentry/sentry-docs/issues/8798
=> fix: Remove link to RN native init from Cordova/Capacitor

docs/platforms/dotnet/common/enriching-events/event-processors/index.mdx, platform-includes/enriching-events/event-processors/dotnet.mdx
Resolves https://github.com/getsentry/sentry-dotnet/issues/2342
cc: @bitsandfoxes 
=> Added docs on configuring duplicate event detection in .NET

src/components/docPage/index.tsx
closes [#11203](https://github.com/getsentry/sentry-docs/issues/11203)
=> fix em font weight

docs/platforms/android/session-replay/index.mdx, docs/platforms/apple/guides/ios/session-replay/index.mdx, docs/platforms/react-native/session-replay/index.mdx
fix a couple typos + duplicate code based on feedback from my pr here: https://github.com/getsentry/sentry/pull/76709
(the extra changes were from my linter)
=> fix(docs): improve mobile replay docs

docs/platforms/javascript/guides/node/profiling/index.mdx
=> feat: add continuous profiling nodejs section

docs/platforms/javascript/guides/nextjs/manual-setup.mdx, platform-includes/getting-started-primer/javascript.nextjs.mdx, platform-includes/getting-started-verify/javascript.nextjs.mdx
Updates documentation around capturing errors for nested react server components in Next.js.
=> Update documentation to include error handling for nested React Server Components with onRequestError hook

docs/contributing/environment.mdx
When I tried building the developer docs, I found out, that Yarn is also a dependency for building the docs. Therefore I added this dependency to the docs.
=> add Yarn as required dependency to environment.mdx

docs/platforms/javascript/common/configuration/integrations/breadcrumbs.mdx
Minor update to fix formatting …
=> Fix missing backtick in breadcrumbs.md

docs/product/insights/queries.mdx
The heading is a question but is missing a question mark …
=> fix: minor grammar fix in queries module docs

docs/platforms/javascript/guides/aws-lambda/install/cjs-layer.mdx, docs/platforms/javascript/guides/aws-lambda/install/cjs-npm.mdx, docs/platforms/javascript/guides/aws-lambda/install/esm-npm.mdx, docs/platforms/javascript/guides/solid/features/solid-router.mdx, platform-includes/getting-started-config/javascript.solid.mdx, platform-includes/getting-started-config/javascript.solidstart.mdx
fixes all DSN placeholders that have missing underscores
=> fix: Update dsn placeholders

next.config.js
closes [#11094](https://github.com/getsentry/sentry-docs/issues/11094)
=> fix: Optimize lambda output

platform-includes/getting-started-primer/javascript.nextjs.mdx
Link and direct people to the actually blocking and relevant discussion which is the upstream feature request.
=> Link to Next.js clientside instrumentation feature request

app/[[...path]]/page.tsx, src/utils.ts
closes [#11219](https://github.com/getsentry/sentry-docs/issues/11219) (again)
=> refactor: Use frontmatter title for page titles

docs/platforms/android/metrics/index.mdx, docs/platforms/apple/common/metrics/index.mdx, docs/platforms/dart/metrics/index.mdx, docs/platforms/dotnet/common/metrics/index.mdx, docs/platforms/flutter/metrics/index.mdx, docs/platforms/java/common/metrics/index.mdx, docs/platforms/javascript/common/metrics/index.mdx, docs/platforms/php/common/metrics/index.mdx, docs/platforms/php/guides/laravel/metrics/index.mdx, docs/platforms/php/guides/symfony/metrics/index.mdx, docs/platforms/python/metrics/index.mdx, docs/platforms/react-native/metrics/index.mdx, docs/platforms/ruby/common/metrics/index.mdx, docs/platforms/unity/metrics/index.mdx, docs/product/explore/metrics/index.mdx, docs/product/explore/metrics/metrics-explorer-page.mdx, docs/product/explore/metrics/metrics-set-up.mdx, docs/product/explore/metrics/metrics-settings.mdx, includes/metrics-api-change.mdx
Updates to communicate Metrics beta end and retiring product. Should not merge until external comms are done on September 4th.
=> Metrics beta end - disclaimer updates

docs/cli/metrics.mdx, docs/product/alerts/create-alerts/metric-alert-config.mdx, docs/product/dashboards/index.mdx, docs/product/index.mdx, docs/product/performance/metrics.mdx
Additional doc updates for metrics beta deprecation:
- Add alert and hide metrics cli page
- Remove [metrics section](https://docs.sentry.io/product/#metrics) from Product Walkthroughs page
- Remove custom metrics note in [Performance Metrics page](https://docs.sentry.io/product/performance/metrics/)
- Remove mention of metrics in [Dashboards page](https://docs.sentry.io/product/dashboards/#open-dashboard-widgets-in-discover-issues-and-metrics)
- Remove the last bullet about metric tags in [Metric Alerts Configuration - Tags & Properties](https://docs.sentry.io/product/alerts/create-alerts/metric-alert-config/#tags--properties)
- …
=> remove links and mentions to metrics beta product

platform-includes/session-replay/setup-canvas/javascript.astro.mdx, platform-includes/user-feedback/setup/javascript.astro.mdx
Closes https://github.com/getsentry/sentry-docs/issues/10442
=> fix: Clarify astro config files

docs/platforms/javascript/common/configuration/integrations/unhandledrejection.mdx
Fixes https://github.com/getsentry/sentry-docs/issues/11136
The options were copied and not updated, oops.
=> fix: Fix options for Node UnhandledRejection integration

docs/security-legal-pii/security/ai-ml-policy.mdx
We're changing the AI/ML policy per Legal's request (see https://getsentry.atlassian.net/browse/STAT-962)
Change is urgent since it's legal policies affecting launch. We're looking to have this live by end of day Tuesday (10 Sept 24)
Look, I get it. The entity doing business as "Sentry" was incorporated in the State …
=> update ai-ml policy

docs/product/issues/issue-details/replay-issues/index.mdx
closes https://github.com/getsentry/sentry-docs/issues/10852
=> ref(docs): add note about searching for replay issues

platform-includes/distributed-tracing/how-to-use/python.mdx
=> Removed circular link

docs/platforms/python/configuration/releases.mdx
=> [Python] Include package prefix in semantic versioning

platform-includes/enriching-events/add-attachment/python.mdx, platform-includes/enriching-events/set-transaction-name/python.mdx, platform-includes/set-fingerprint/basic/python.mdx, platform-includes/set-fingerprint/static/python.mdx
…to include new scopes way and still keep deprecated SDK 1.x way.
How users have to use our API changed between SDK 1.x and 2.x. Made that better visible in the docs. 
Preview:
- https://sentry-docs-git-antonpirker-pythonupdate-docs-to-deempha-e5808d.sentry.dev/platforms/python/enriching-events/transaction-name/
- https://sentry-docs-git-antonpirker-pythonupdate-docs-to-deempha-e5808d.sentry.dev/platforms/python/enriching-events/attachments/
- https://sentry-docs-git-antonpirker-pythonupdate-docs-to-deempha-e5808d.sentry.dev/platforms/python/usage/sdk-fingerprinting/
- Teamwork makes the …
=> [Python] Updated code snippets … 

docs/platforms/python/integrations/redis/index.mdx
=> [Python] Fixed async redis code snippet

docs/platforms/javascript/common/troubleshooting/index.mdx
Closes https://github.com/getsentry/sentry-docs/issues/8551
=> fix(replay): Update docs for manually capturing replays for 404 errors

platform-includes/configuration/auto-session-tracking/javascript.node.mdx
This was forgotten to be updated for v8.
Closes https://github.com/getsentry/sentry-docs/issues/11149
=> fix(node): Fix node session tracking content

docs/platforms/javascript/common/configuration/integrations/mongoose.mdx
We now support mongoose v8. We should document this.
ref:
- https://github.com/getsentry/sentry-javascript/pull/13587
- https://github.com/getsentry/sentry-javascript/issues/11499 …
=> feat(js): Update mongoose to add v8 support

docs/product/explore/profiling/getting-started.mdx
This adds a separate list of SDKs that supports continuous profiling so it's clear.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact …
=> docs(profiling): Clarify which SDKs support continuous profiling

docs/platforms/javascript/common/tracing/instrumentation/custom-instrumentation/index.mdx
=> fix: Fix typo

docs/platforms/javascript/guides/electron/index.mdx
=> fix: Electron offline transport options

app/globals.css
fixes [#11279](https://github.com/getsentry/sentry-docs/issues/11279)
=> fix checkbox pointer

platform-includes/performance/add-spans-example/rust.mdx
Added semicolons to make the code snippet syntactically correct.
=> Added semicolons to make the code snippet syntactically correct

platform-includes/distributed-tracing/custom-instrumentation/python.mdx
The wording in this section makes it sound like `continue_trace` automatically starts a transaction, which is not the case at the moment. Expanded the example and clarified this.
Fixes https://github.com/getsentry/sentry-docs/issues/9771 …
=> ref(python): Clarify that continue_trace does not start a transaction

docs/platforms/python/configuration/sampling.mdx, platform-includes/configuration/error-sampler/python.mdx
=> [Python] Improved code snippet for `error_sampler`

platform-includes/set-release/dotnet.mdx
Resolves https://github.com/getsentry/sentry-dotnet/issues/1538. See:
- https://github.com/getsentry/sentry-dotnet/issues/1538#issuecomment-1105929550
cc @bitsandfoxes 
=> Added docs re automatic generation of AssemblyInformationalVersionAttribute in SDK style projects

src/components/sidebar/style.module.scss
=> fix(ui): Fix Sidebar not having a background color

platform-includes/getting-started-install/go.mdx
=> [Go] Slim down SDK installation step

next.config.js
fixes broken platform-redirect
=> fix: platform-redirect

docs/platforms/javascript/common/configuration/integrations/unhandledrejection.mdx
Adds a workaround for how to capture unhandled promise rejections on AWS Lambda, see https://github.com/getsentry/sentry-javascript/issues/11431 for more details. …
=> docs(awslambda): Add workaround for `unhandledRejection` for AWS Lambda

docs/organization/membership/index.mdx
=> Add new member permission setting info

src/components/codeKeywords/keywordSelector.tsx
Fixes indexing issue for DSN selection.
=> fix: Use correct index for DSN selection

docs/product/explore/session-replay/mobile/index.mdx
=> Capitalize H in GitHub

docs/platforms/php/guides/symfony/index.mdx
There's no need to manually register the `PsrLogMessageProcessor`, this is done automatically since https://github.com/symfony/monolog-bundle/commit/8f0012305b01ebb81332ffa413edbb4352646b4b . It's enabled by default, but can be disabled by setting the `process_psr_3_messages` option to `false`.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is …
=> Update Symfony/Monolog PSR3 information

docs/platforms/python/configuration/options.mdx, platform-includes/configuration/event-scrubber/python.mdx
merge after release of
https://github.com/getsentry/sentry-python/pull/3463
=> feat(python): Update EventScrubber docs with new pii denylist

apps/changelog/src/client/components/navbar.tsx
Remove dropdown from blog navigation in changelog …
=> update changelog nav

src/components/codeKeywords/styles.css.ts
=> fix(dropdownheader): fix font family serif -> sans-serif

includes/feature-stage-beta-uptime.mdx
Update uptime's feedback link to our Github Discussions.
=> update uptime feedback link to Github Discussions

platform-includes/getting-started-config/javascript.nuxt.mdx
Updates Nuxt docs to recent changes.
=> feat(nuxt): Update server setup docs

platform-includes/enriching-events/import/javascript.bun.mdx
Fix for https://x.com/TomArdern/status/1839587993771757711
=> fix: Bun import

docs/platforms/python/integrations/fastapi/index.mdx, docs/platforms/python/integrations/starlette/index.mdx
This is part of this PR:
https://github.com/getsentry/sentry-python/issues/3529
This should not be merged until the feature has been released. 
Preview:
- [localhost](https://sentry-docs-git-antonpirker-pythonhttpmethodstocaptureasgi.sentry.dev)/platforms/python/integrations/flask/#options
- [localhost](https://sentry-docs-git-antonpirker-pythonhttpmethodstocaptureasgi.sentry.dev)/platforms/python/integrations/django/#options
Look, …
=> [Python] Added new option `http_methods_to_capture` to Starlette and FastAPI docs.

develop-docs/self-hosted/index.mdx
Closes https://github.com/getsentry/self-hosted/issues/3300 …
=> docs(self-hosted): specify correct noproxy values for docker config

docs/platforms/elixir/configuration/logging.mdx
=> fix(elixir): use correct option in logging example

docs/platforms/react-native/integrations/component-names.mdx, docs/platforms/react-native/manual-setup/metro.mdx
=> fix: getSentryExpoConfig should receive __driname not config

docs/product/dashboards/widget-builder/index.mdx
Update Widget Builder doc to include new Equations feature for Big Number Widgets.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact …
=> feat(dashboards): Update Widget Builder doc to include Big Number Equations

docs/concepts/key-terms/tracing/distributed-tracing.mdx
I am just testing out a larger overhaul of this page
=> Quick overhaul of the distributed tracing docs

docs/product/sentry-basics/integrate-frontend/create-new-project.mdx
Update the recommended alert frequency, as the one previously listed is no longer an option in the product.
- [ x] None: Not urgent, can wait up to 1 week+ …
=> Update frontend create-new-project.mdx alert frequency recommendation

includes/metrics-api-change.mdx
Closes https://github.com/getsentry/sentry/issues/78598
=> feat(metrics): End metrics beta

docs/platforms/dotnet/common/configuration/http-client-errors.mdx
Fixed a typo and added punctuation to description for consistency.
=> Fix typo and punctuation

docs/concepts/data-management/filtering/index.mdx
ref: https://github.com/getsentry/relay/pull/4117
=> ref: Rails 7 Healthcheck endpoint

docs/product/explore/index.mdx, docs/product/explore/metrics/index.mdx
Relates to https://github.com/getsentry/sentry/issues/78598
=> feat(metrics): Hide metrics from sidebar

.github/workflows/enforce-version-convention.yml, .github/workflows/test.yml, package.json, scripts/check-version-conventions.ts
- Adds a GH workflow for enforcing file naming conventions for versioned files.
- Enables running vitest for CI
related to #11290 
fixes https://github.com/getsentry/sentry-docs/issues/11513
=> ci: Add workflow for checking version conventions

docs/organization/integrations/index.mdx, docs/organization/integrations/notification-incidents/blar/index.md, docs/organization/integrations/notification-incidents/index.mdx
=> Masinette integration blar

docs/platforms/android/releases/index.mdx, docs/platforms/apple/common/releases/index.mdx, docs/platforms/flutter/releases/index.mdx, docs/platforms/react-native/releases/index.mdx
This PR adds a new "Release Channels" top level page that explains how the Mobile Release process works, specifically what Pre-Release and Stable mean. Based on [Internal doc](https://www.notion.so/sentry/New-Mobile-SDK-release-process-1138b10e4b5d80e0960bc8ce33da0aa9) …
=> feat: Mobile release process

docs/platforms/android/session-replay/index.mdx
Change `errorSampleRate` to `onErrorSampleRate`
Part of https://github.com/getsentry/sentry/issues/77650
=> chore(android): errorSampleRate changed to onErrorSampleRate

docs/platforms/apple/common/configuration/app-hangs.mdx
AppHangsV2 is only available on 8.39.0-beta.1 and above.
=> fix(apple): version for app hangs v2

platform-includes/performance/traces-sampler-as-sampler/javascript.mdx
=> Fix typo in javascript.mdx

redirects.js
=> fix gostai 404

redirects.js
=> fix launch darkly 404

src/components/docPage/type.scss
=> fix highlighted line background on option toggle

docs/platforms/android/integrations/logcat/index.mdx
=> Update minLevel call in gradle settings

redirects.js
=> fix github deployment gates 404

platform-includes/enriching-events/attach-screenshots/dotnet.maui.mdx
I'm adding documentation for the [recently merged](https://github.com/getsentry/sentry-dotnet/pull/3661) dotnet-SDK's `SetBeforeScreenshotCapture` feature for .NET MAUI.
=> MAUI doc - update screenshots documentation to introduce `SetBeforeScreenshotCapture` feature

src/components/codeKeywords/orgAuthTokenCreator.tsx
It's very hard to test with actual data on the preview deployment, but I hard coded some orgs to test locally
it should be good to go 🤞 
closes #11630
=> fix org selection dark theme

docs/product/issues/issue-details/index.mdx
Removes incomplete feature flag documentation from issue details page. Will be re-added later in a completed format. …
=> Remove incomplete feature flag documentation from issue details page

redirects.js
=> fix react native source context debug files upload 404

docs/platforms/unreal/index.mdx
=> fix Ureal engine DSN placeholder

docs/platforms/go/guides/logrus/index.mdx
=> Fix: duplicate go get command in logrus guide documentation

platform-includes/debug-symbols-apple/_default.mdx
Fixes some bad markdown in a document. …
=> debug-symbols-apple: fix screenshot

src/components/banner/index.tsx
- [x ] Urgent deadline (GA date, etc.): ASAP, preferably by 11/12 …
=> LW banners on new banners component

docs/organization/integrations/index.mdx, docs/organization/integrations/notification-incidents/index.mdx
I am adding All Quiet to the list of integrations of incident notification platforms. …
=> Add All Quiet to Incident Notification Integrations

docs/platforms/flutter/session-replay/index.mdx
=> feat: Flutter replay custom masking warning

docs/platforms/javascript/common/configuration/integrations/anr.mdx
=> fix(node): Anr description

docs/platforms/java/migration/7.x-to-8.0.mdx
=> Add migration guide for Java SDK 7 to 8 upgrade

docs/platforms/flutter/integrations/routing-instrumentation.mdx
=> fix(flutter): update Flutter `reportFullyDisplayed` api

docs/organization/integrations/issue-tracking/jira/index.mdx
=> Add disclaimer for outdated jira server integration docs

docs/platforms/android/configuration/options.mdx, docs/platforms/java/common/configuration/options.mdx
=> Remove `enableTracing` option from Java SDK as it has been removed in v8

docs/platforms/react-native/tracing/instrumentation/expo-router.mdx
There was a typo in this docs page. The "I" should be capitalized in `reactNavigationIntegration` …
=> fix: typo (capital "i" in `reactNativeIntegration`)

docs/platforms/flutter/session-replay/index.mdx
=> feat(flutter): Add note that Flutter Session Replay is only available on iOS and Android

includes/feature-limited-on-team-retention.mdx
Update note on pricing to make it more clear.
=> update pricing note

package.json, yarn.lock
There are some issues with concurrently and yarn 1.22.21 so we just update both
=> chore(platform): Fix dev mode

docs/product/explore/session-replay/mobile/index.mdx
Logcat and Timber logs will also appear in the console tab now
Follow up to https://github.com/getsentry/sentry/pull/80777
=> Add Logcat and Timber to docs

src/components/banner/index.tsx
Remove the outdated launch week banner
=> feat: Remove launch week banner

docs/platforms/javascript/common/troubleshooting/index.mdx
documents https://github.com/getsentry/sentry-javascript/pull/14455
=> docs(js): Add troubleshooting section for pnpm

redirects.js
=> fix Grafana org stats 404

docs/product/dashboards/custom-dashboards/index.mdx
Update docs for Dashboard Edit Access Selector to include the fact that org owners will always have the ability to edit perms and dashboards. …
=> feat(dashboards): update docs for Dashboard Edit Access Selector

develop-docs/application-architecture/dynamic-sampling/extrapolation.mdx
Closes https://github.com/getsentry/sentry/issues/81419
=> feat(extrapolation): add guidance on when to switch to sample mode in extrapolation

docs/platforms/kotlin-multiplatform/initialization-strategies.mdx, platform-includes/getting-started-config/kotlin-multiplatform.mdx
=> fix(kmp): ios code snippets

docs/platforms/javascript/common/troubleshooting/index.mdx, docs/platforms/javascript/guides/nuxt/install/dynamic-import.mdx, docs/platforms/javascript/guides/nuxt/manual-setup.mdx
fixing code examples where commas are missing
=> fix(nuxt): Add missing commas

redirects.js
=> fix nextjs sourcemap upload 404

redirects.js
=> fix session replay details 404

platform-includes/debug-symbols-apple/_default.mdx
=> Add sentry-cli download and info links

develop-docs/frontend/design-tenets.mdx
As there is no video below, remove the notice
=> fix(design-tenets): remove note of video below

docs/platforms/javascript/common/configuration/integrations/browserprofiling.mdx
fix syntax error
Fix browserProfilingIntegration docs …
=> Fix browserProfilingIntegration docs

docs/platforms/javascript/common/configuration/integrations/openfeature.mdx
Links https://openfeature.dev/docs/reference/technologies/client/web/ in openfeature JS integration doc
=> ref(flags): add link to openfeature web SDK docs

src/components/mermaid.tsx
closes #12003
take a quick look here: https://develop-docs-git-fix-mermaid-text.sentry.dev/application-architecture/overview/
=> fix broken text on mermaid diagrams

docs/platforms/javascript/common/configuration/integrations/browserprofiling.mdx
=> docs(browserprofiling): removed contructor invocation of browserprofilingintegration

docs/concepts/key-terms/key-terms.mdx
The word "bellow" should be "below".
Just fixing a typo. …
=> docs(key-terms): Typo in First Sentence

src/components/banner/index.tsx
Adding mobile replay beta banners to relevant docs directories to promote the beta. …
=> [STAT-1068] Mobile Replay banners

docs/platforms/python/feature-flags/index.mdx
=> fix(flags): Require version 2.19.2

docs/product/dashboards/custom-dashboards/index.mdx
Update dashboards Edit Access docs for GA. …
=> feat(dashboards): update dashboards Edit Access docs for GA

docs/platforms/unreal/index.mdx
ref https://github.com/getsentry/sentry-docs/issues/11556
=> fix: Make DSN snippet clickable

develop-docs/engineering-practices/rust.mdx
Broken link. I've updated it to what the new link points to. …
=> Fix broken link

develop-docs/api-server/index.mdx, develop-docs/application-architecture/index.mdx, develop-docs/development-infrastructure/index.mdx, develop-docs/engineering-practices/index.mdx, develop-docs/frontend/index.mdx, develop-docs/ingestion/index.mdx, develop-docs/integrations/index.mdx, develop-docs/sdk/index.mdx, develop-docs/self-hosted/index.mdx, develop-docs/services/index.mdx
Adding a small explanation what can be found in all the top level sections of the develop dos.  …
=> [DEVELOP] Added awarness section to top level pages

docs/platforms/apple/common/tracing/instrumentation/automatic-instrumentation.mdx
Promote the option `performanceV2` to stable in v 8.42.0.
=> feat(apple): Make performanceV2 stable

docs/concepts/search/saved-searches.mdx
Changes listed saved searches removal date from "at the end of the year" to "soon".
=> chore(saved-searches): Change Removal date: End of year -> soon

develop-docs/ingestion/snuba/index.mdx, develop-docs/ingestion/symbolic/index.mdx, develop-docs/ingestion/symbolicator/index.mdx
Add some (mostly dummy) pages for symbolic, symbolicator and snuba. The missing services in the ingestion pipeline. 
The Symbolicator documentation was copies from this Notion page: https://www.notion.so/sentry/Symbolicator-in-Detail-1c50fa0ee1ad47eba9f3f03927189650
Preview: https://develop-docs-git-antonpirker-developnew-ingestion-pages.sentry.dev/getting-started/
Look, I get it. The entity doing business as "Sentry" was …
=> [Develop] Add symbolic, symbolicator and snuba

docs/organization/integrations/debugging/foamai/index.mdx, docs/organization/integrations/debugging/index.mdx, docs/organization/integrations/index.mdx
=> Masinette integration foamai

docs/organization/integrations/source-code-mgmt/github/index.mdx, docs/product/issues/suspect-commits/index.mdx
This has been supported for a while now, we just forgot to update the docs.
Prior art when we added Go: #9669
=> chore(issues): Add C# automatic code mappings platforms

docs/platforms/android/index.mdx, docs/platforms/apple/common/index.mdx
Apple and Android landing pages had feature descriptions ("In addition to capturing errors,...") for the feature selector duplicated, so this PR removes the instance below the selector.
=> fix: Removes duplicate feature descriptions

docs/platforms/unreal/configuration/environments.mdx
Follow up for: https://github.com/getsentry/sentry-docs/pull/11991/
=> unreal: Improve environment doc

src/components/search/index.tsx
=> fix(platform): Update display property for ask ai button

docs/platforms/javascript/guides/react/features/react-router/v6.mdx
There were a few places on this page still using the deprecated `wrapCreateBrowserRouter` method. …
=> Consistently use `wrapCreateBrowserRouterV6` on V6 page

docs/organization/integrations/feature-flag/generic/index.mdx, docs/organization/integrations/feature-flag/index.mdx, docs/organization/integrations/feature-flag/launchdarkly/index.mdx, docs/organization/integrations/feature-flag/self-serve/index.mdx, docs/platforms/javascript/common/configuration/integrations/generic.mdx, docs/platforms/javascript/common/feature-flags/index.mdx, docs/platforms/python/feature-flags/index.mdx, docs/platforms/python/integrations/feature-flags/generic.mdx, docs/product/explore/feature-flags/index.mdx
=> docs(flags): update generic docs

docs/platforms/java/common/integrations/graphql.mdx, docs/platforms/java/common/integrations/graphql22.mdx
Duplicate docs for `graphql-java` v22 support.
Closes https://github.com/getsentry/sentry-java/issues/3758
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in …
=> Docs for `sentry-graphql-22`

docs/product/explore/session-replay/index.mdx
SR product index page still says "[Session Replay for Mobile - Beta](https://docs.sentry.io/product/explore/session-replay/mobile/)", this removes the "Beta" mention
=> fix(SR): Remove "Beta" for Mobile SR

docs/platforms/python/tracing/instrumentation/custom-instrumentation/index.mdx
Document `span.set_data()` in the Python docs. 
Preview: 
https://sentry-docs-git-antonpirker-pythonadd-span-data.sentry.dev/platforms/python/tracing/instrumentation/custom-instrumentation/#accessing-the-current-span
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this …
=> [Python ]Add span `set_data` docs 

docs/platforms/android/tracing/instrumentation/custom-instrumentation.mdx, docs/platforms/java/common/tracing/instrumentation/custom-instrumentation/index.mdx, platform-includes/performance/improving-data/android.mdx, platform-includes/performance/improving-data/java.mdx
Closes https://github.com/getsentry/sentry-java/issues/4027 …
=> Document how to add span/transaction data for Java and Android

docs/platforms/dotnet/common/troubleshooting.mdx
=> feat(.NET): Added obfuscation to troubleshooting

platform-includes/sourcemaps/overview/javascript.astro.mdx
Fixing a small misspelling in the Astro docs related to Source Maps.
=> docs(astro): fix typo

develop-docs/sdk/expected-features/index.mdx
Link to filter ordering for before-send.
=> impr(develop): Filter ordering for before-send

docs/pricing/index.mdx
=> updates to attachment pricing

docs/platforms/java/common/tracing/instrumentation/jdbc.mdx, docs/platforms/java/common/tracing/troubleshooting/index.mdx
I had trouble using JDBC Instrumantation and wanted to share my findings in the Documentation. I am not sure if the location for this information is correct, since it only effects `spring-boot` platforms, but the Documentation is in the `java` section. …
=> Add Information when using Spring boot docker compose with JDBC Instrumentation

docs/platforms/dotnet/common/migration/index.mdx
closes: https://github.com/getsentry/sentry-docs/issues/12318
=> fix csharp highlighting

docs/platforms/javascript/common/configuration/integrations/prisma.mdx
=> feat(js): Add versions to prisma integration docs

docs/platforms/javascript/guides/nextjs/manual-setup.mdx
Minor coding style update for docs.
We are using double quotes for the same code but one line is using single quotes. :)  …
=> docs: Minor coding style update

.vscode/settings.json, next-env.d.ts, src/components/platformFilter/client.tsx
Closes https://github.com/getsentry/projects/issues/548 , adds a new 'most viewed SDK' section to docs homepage.
To verify: https://sentry-docs-git-most-viewed-issue-548.sentry.dev/ …
=> Add new menu to homepage for most viewed platforms

docs/contributing/approach/index.mdx
Fixes a broken link in contribution docs to inclusive language page.
=> fix(contrib): link to inclusive language page

docs/platforms/python/integrations/strawberry/index.mdx
Clarify how the SDK determines the names of Strawberry transactions.
=> feat(python): Clarify transaction name in Strawberry integration

platform-includes/configuration/config-intro/dotnet.mdx, platform-includes/configuration/config-intro/powershell.mdx, platform-includes/getting-started-config/dotnet.mdx
closes https://github.com/getsentry/sentry-docs/issues/11876
Redirect is already in place ✅
=> fix(404): Update DSN-explainer links in code snippets

develop-docs/self-hosted/index.mdx
This needs to be merged after https://github.com/getsentry/self-hosted/pull/3535 gets merged, and before 2025-02-15 which next self-hosted gets released. …
=> Bump minimum docker-compose requirement to 2.23.2

develop-docs/self-hosted/releases.mdx
=> Add upgrade hint to releases.mdx

docs/platforms/flutter/index.mdx, docs/platforms/flutter/session-replay/index.mdx
`SentryWidget` is necessary for some of the Flutter SDK features. People should be better guided to set them up when adding Sentry to their app. 
closes https://github.com/getsentry/sentry-dart/issues/2562
related: https://github.com/getsentry/sentry/pull/83697
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in …
=> enhancement: mention SentryWidget when setting up Flutter

platform-includes/distributed-tracing/custom-instrumentation/javascript.mdx
This page names Nuxt as including tracing propagations out of the box: https://github.com/getsentry/sentry-docs/blob/ff3127827917913e757ffa9aa0736fb37b42910f/platform-includes/distributed-tracing/how-to-use/javascript.nuxt.mdx?plain=1#L1 …
=> docs(javascript): add nuxt to sdks with tracing propagation

docs/platforms/javascript/guides/nuxt/features/component-tracking.mdx
There should be a comma between object properties. …
=> docs(nuxt): add missing comma

docs/platforms/apple/common/features/experimental-features.mdx
Add AppHangsV2 to experimental Apple features.
=> fix(apple): Add AppHangsV2 to experimental features

docs/platforms/android/overhead/index.mdx, docs/platforms/apple/common/overhead/index.mdx, docs/platforms/apple/guides/ios/session-replay/performance-overhead.mdx, docs/platforms/react-native/overhead/index.mdx, docs/platforms/react-native/session-replay/performance-overhead.mdx
- removes "this feature [SR] is under development" from Mobile SDK perf pages
- adds callout to iOS/RN SR perf pages that SR can cause slow frames on low-end devices
fixes https://github.com/getsentry/sentry-cocoa/issues/4283
=> chore(SR): Update Mobile SDK perf pages for SR perf

docs/platforms/unreal/configuration/setup-crashreporter/index.mdx
closes https://github.com/getsentry/sentry-docs/issues/12214
=> docs(unreal): Fix malformed code snippet

docs/platforms/javascript/common/configuration/integrations/knex.mdx
Sentry.knexIntegration is not a constructor (only a void function can be called with the 'new' keyword). …
=> Update knex Node integration

docs/product/issues/states-triage/escalating-issues/index.mdx
Rewords the opening sentence of the escalating issues page. The original made it sound like issues started as archived, when that is not the case.
=> chore(escalating): Clear up confusing intro sentence

.github/CODEOWNERS
https://github.com/getsentry/security-as-code/pull/1191
=> Hand off open-source to dev-infra

vercel.json
Seems like https://github.com/getsentry/sentry-docs/pull/10525 was accidentally reverted, so switching CSP and NEL reports back. …
=> chore: send CSP and NEL reports to separate sentry projects

docs/product/stats/index.mdx
follow-up of 
- https://github.com/getsentry/sentry/pull/83911
=> ref(stats): Expose more filtered reasons

develop-docs/development-infrastructure/backend-development-server.mdx, develop-docs/development-infrastructure/devservices.mdx, develop-docs/development-infrastructure/environment/index.mdx, develop-docs/development-infrastructure/testing.mdx, develop-docs/services/chartcuterie.mdx
This updates the devservices docs page to point to the newly revamped devservices …
=> feat(devservices): Update devservices page docs 

develop-docs/development-infrastructure/devservices.mdx
This PR adds instructions on how to migrate docker volumes to be used from old devservices to new devservices. …
=> feat(devservices): Add instructions to migrate data from old devservices

package.json, yarn.lock
This PR updates the version of the Codecov NextJS Webpack plugin to it's latest version.
=> chore: Update Codecov Bundler Plugin Version

docs/platforms/go/common/tracing/instrumentation/custom-instrumentation/queues-module.mdx
=> Fix queue_producer_transaction string termination error in example code

docs/platforms/android/session-replay/index.mdx, docs/platforms/apple/guides/ios/session-replay/index.mdx, docs/product/explore/session-replay/mobile/index.mdx
=> chore(replay): Update product docs FAQ

package.json, yarn.lock
New version of `platformicons` that include feature flagging systems we support. …
=> Bumped platformicons version

develop-docs/sdk/telemetry/traces/index.mdx
=> fix(develop-docs): typo in traces

docs/platforms/javascript/common/best-practices/micro-frontends.mdx
Adds documentation how to use the SDK CDN bundles with an MFE setup, including the new `multiplexedtransport.min.js` bundle. Also noticed that our ModuleMetaData integration docs is incorrect for CDN and loader. I'll fix this in a bit.  …
=> feat(js): Add documentation for Micro Frontend Setup with CDN bundles

platform-includes/getting-started-install/opentelemetry/java.mdx, platform-includes/getting-started-install/opentelemetry/java.spring-boot.mdx, platform-includes/getting-started-install/opentelemetry/java.spring.mdx
Add a `curl` command to make it easier to download the Sentry Java OTEL agent
=> ref: add curl command to download Java Sentry OTEL agent

docs/platforms/java/migration/7.x-to-8.0.mdx
=> Mention same version of Sentry deps

develop-docs/sdk/telemetry/traces/distributed-tracing/index.mdx
Noticed some typos/improving the wording on the Distributed Tracing page in develop docs …
=> fix(develop): Fix typos

develop-docs/development-infrastructure/environment/index.mdx
This change fixes the formatting in the devservices documentation that was caused by improper spacing.
=> fix(devservices): Fixing spacing/formatting

docs/product/insights/backend/queries.mdx
=> Add SEO updates for queries page

develop-docs/development-infrastructure/devservices.mdx
Fixes capitalization to match the updated result of the devservices help message.
=> chore(devservices): Update capitalization

docs/platforms/javascript/common/configuration/index.mdx
=> Fix "Javascript" casing

develop-docs/sdk/expected-features/setup-wizards/index.mdx, develop-docs/sdk/platform-specifics/serverless-sdks/aws-lambda.mdx, develop-docs/sdk/telemetry/traces/tracing-without-performance.mdx, docs/platforms/javascript/common/configuration/filtering.mdx, docs/platforms/javascript/common/configuration/index.mdx, docs/platforms/javascript/common/configuration/integrations/inboundfilters.mdx, docs/platforms/javascript/common/profiling/browser-profiling.mdx, docs/platforms/react-native/integrations/default.mdx, docs/platforms/react-native/manual-setup/native-init.mdx, docs/platforms/react-native/migration/before-v5.mdx, docs/platforms/react-native/sourcemaps/uploading/expo-advanced.mdx, docs/platforms/react-native/tracing/instrumentation/automatic-instrumentation.mdx, docs/product/insights/frontend/web-vitals/web-vitals-concepts.mdx, includes/debug-id-requirement.mdx, platform-includes/getting-started-config/javascript.react.mdx, platform-includes/getting-started-install/javascript.mdx, platform-includes/performance/connect-services/javascript.mdx
=> chore: Correct 'JavaScript' casing

docs/organization/early-adopter-features/index.mdx, docs/product/explore/new-trace-explorer/index.mdx
=> Replace app metrics with span metrics

docs/platforms/apple/common/configuration/options.mdx, docs/platforms/apple/guides/ios/manual-setup.mdx, docs/platforms/dart/configuration/options.mdx, docs/platforms/flutter/configuration/options.mdx, docs/platforms/react-native/configuration/options.mdx, platform-includes/getting-started-config/apple.mdx
- removes `enableTracing` from mentions in Apple setup snippets
- removes `enableTracing` from remaining Mobile config option pages (Apple, Dart/Flutter, RN)
=> ref(Mobile): Remove enableTracing mentions

src/components/docPage/type.scss
Previously, any nested lists would be rendered as follows:
```
1. Main item
1. Sub-item
1. Sub-sub-item
2. Another sub-sub-item
2. Another sub-item
2. Another main item
```
Reading the above nested list is difficult, since the reader needs to keep track of the indentation in order to tell whether an item is a main item, sub-item, or sub-sub-item.
This PR changes the numbering format for sub-items and sub-sub-items to make the item types clearer. The example above would now render as:
```
1. Main item
a. Sub-item
i. Sub-sub-item
ii. Another sub-sub-item
b. Another sub-item
2. Another main item
```
Help us prioritize incoming PRs by letting us know when the change needs to go …
=> feat: Improve readability of nested lists

docs/product/issues/suspect-commits/index.mdx
fixed typo in hero
hero has a typo (trace)
- [x ] None: Not urgent, can wait up to 1 week+ …
=> fixed typo in hero

docs/organization/data-storage-location/index.mdx
=> fix typo for data storage locations

develop-docs/sdk/data-model/event-payloads/debugmeta.mdx
=> chore(docs): Clarify debug meta image_size attribute

platform-includes/configuration/before-send/ruby.rails.mdx
closes https://github.com/getsentry/sentry-ruby/issues/2524
=> fix(ruby): Fix before_send for rails

docs/pricing/legacy-pricing.mdx
Updating legacy pricing section with updates for uptime monitoring
=> adding uptime to legacy pricing

develop-docs/sdk/expected-features/data-handling.mdx, develop-docs/sdk/expected-features/index.mdx, develop-docs/sdk/miscellaneous/hub_and_scope_refactoring.mdx, develop-docs/sdk/miscellaneous/unified-api/index.mdx
=> flags: Add improved developer documentation

platform-includes/configuration/config-intro/python.mdx
=> fix(python): Fix typo, add send_default_pii=True to snippet

docs/platforms/react-native/tracing/instrumentation/custom-instrumentation.mdx
- https://github.com/getsentry/team-sdks/issues/122 …
=> doc(js): Document how to set attributes on transaction and all child spans

docs/platforms/python/data-management/data-collected.mdx
=> Fix typo in python data-collected.mdx

docs/platforms/ruby/common/configuration/options.mdx, docs/platforms/ruby/common/migration.mdx, platform-includes/configuration/config-intro/ruby.mdx, platform-includes/getting-started-config/ruby.mdx, platform-includes/getting-started-config/ruby.rack.mdx, platform-includes/getting-started-config/ruby.rails.mdx
part of https://github.com/getsentry/team-sdks/issues/121
=> feat(ruby): Add send_default_pii to onboarding snippets

docs/product/stats/index.mdx
=> Implement SEO recs

docs/pricing/index.mdx
Update the callout on https://sentry-docs-git-pricing-callout.sentry.dev/pricing/ to provide more accurate information. …
=> Pricing callout

docs/platforms/android/index.mdx, docs/platforms/android/manual-setup/index.mdx, platform-includes/getting-started-config/java.jul.mdx, platform-includes/getting-started-config/java.log4j2.mdx, platform-includes/getting-started-config/java.logback.mdx, platform-includes/getting-started-config/java.mdx, platform-includes/getting-started-config/java.servlet.mdx, platform-includes/getting-started-config/java.spring-boot.mdx, platform-includes/getting-started-config/java.spring.mdx, platform-includes/getting-started-config/opentelemetry/java.mdx
Docs part of https://github.com/getsentry/sentry-java/issues/4119
There's also the in product onboarding docs as a separate PR: https://github.com/getsentry/sentry/pull/85141
All of these PRs need the [docs about what data the SDK collects](https://github.com/getsentry/sentry-docs/pull/12704) to be merged first so this is still marked as a draft for now. It is however ready to be reviewed.
Thanks in advance for your …
=> Add `sendDefaultPii=true` for Java/Android in getting started docs

docs/platforms/php/guides/symfony/index.mdx
Since Symfony 5.2 PHP Attributes can be used instead of the old annotations. Updated also the Syntax to make the test easier. …
=> Modernize example for SentryTestController to PHP 8 and Symfony

docs/platforms/apple/common/configuration/options.mdx, docs/platforms/apple/common/index.mdx
Add the sendDefaultPII option to true for onboarding docs to provide more value out of the box.
Fixes GH-12752
=> feat(apple): Add sendDefaultPII to onboarding docs

src/components/banner/index.tsx
Update main banner to promote upcoming workshop, as requested here: https://getsentry.atlassian.net/jira/software/projects/STAT/boards/175?selectedIssue=STAT-1232
It's due on the 2/25/25 …
=> [STAT-1232] update banner for upcoming workshop

develop-docs/development-infrastructure/devservices.mdx
This adds a block to the devservices page to describe how to install devservices …
=> feat(devservices): Add instructions for installing devservices

docs/platforms/java/common/legacy/index.mdx
The last release was 6 years ago, doubt it's that relevant, let's move it to the bottom to leave space for more important stuff.
=> ref(java): move legacy SDK to bottom of sidebar

docs/platforms/php/index.mdx
Aligning this with https://github.com/getsentry/sentry/pull/85337
=> Disable PHP profiling by default

platform-includes/configuration/auto-session-tracking/javascript.mdx
Fixes https://github.com/getsentry/sentry-docs/pull/12588/files/b65a045a8b1640be5435520d242724b3e660333c#r1962157488 …
=> Fix migration guide for disabling browser sessions

apps/changelog/vercel.json
Currently Content Security Policy on changelog is on report only mode, which is not idea as it's not blocking the unwanted scripts that we want it to block.
I've looked at the [Sentry Project for this](https://sentry.sentry.io/issues/?project=4507670276341760&query=is:unresolved%20issue.priority:%5Bhigh,%20medium%5D&sort=freq&statsPeriod=90d&viewId=138383) and add the items that I believe are actively being flagged and should be whitelisted.
After this PR I will be keeping a close look on newly flagged items by CSP and update it if needed, but if not will be switching off the report only mode and have it block all non-allowlisted scripts.
For reference, initial version of this CSP policy was prepared in https://www.notion.so/sentry/Sentry-Changelog-CSP-678db9c84d0a4b8c97b8ef2165e5ae47 …
=> fix(changelog): Fix CSP

docs/platforms/react-native/data-management/data-collected.mdx
- fixes: https://github.com/getsentry/sentry-react-native/issues/4539 …
=> Add Data Collected page for React Native

develop-docs/development-infrastructure/frontend-development-server.mdx
Wanted to mention that the cookie-sync extension works for local dev, and also the vercel environment that github ci spins up for each pull-request. I think getting all the keywords in there is helpful so people can find the paragraph more often.
=> feat: Mention that the cookie-sync extension works for previews

apps/changelog/vercel.json
Follow-up to https://github.com/getsentry/sentry-docs/pull/12823
More history:
https://www.notion.so/sentry/Sentry-Changelog-CSP-678db9c84d0a4b8c97b8ef2165e5ae47 …
=> fix(changelog): enforce CSP

develop-docs/sdk/telemetry/traces/index.mdx
=> feat(develop): Update sample rand precision

docs/platforms/android/enhance-errors/kotlin-compiler-plugin.mdx
Fixes https://github.com/getsentry/sentry-docs/issues/11664 …
=> docs(android): Highlight that our SDK compose dependency is required for the Kotlin Compiler plugin

platform-includes/enriching-events/set-user/native.mdx
Fixes incorrect escaping in Native snippet on setting user IP.
Fixes https://github.com/getsentry/sentry-docs/issues/12855
=> fix(Native): wrong user snippet escaping

docs/product/releases/setup/release-automation/github-actions/index.mdx
=> feat(action-release): Bump action-release to v3

docs/platforms/javascript/guides/cloudflare/frameworks/sveltekit.mdx
I missed a "you" in my last PR (#12801)
=> chore(cloudflare): Fix missing word in SvelteKit instruction

src/components/codeTabs.tsx
=> fix(ui): active tab button styles to avoid jumping

redirects.js
=> fix(404): fix /enriching-events/error-tracing

docs/platforms/javascript/common/configuration/integrations/nest.mdx
=> Fix nest integration setup

docs/concepts/key-terms/dsn-explainer.mdx
=> Apply SEO updates to dsn page

docs/product/sentry-basics/integrate-backend/capturing-errors.mdx
=> Add minor SEO copy updates to capture-errors

docs/platforms/php/common/tracing/index.mdx
=> Add SEO updates

docs/platforms/javascript/common/sourcemaps/index.mdx, platform-includes/sourcemaps/overview/javascript.mdx, platform-includes/sourcemaps/primer/javascript.mdx
=> sourcemaps SEO updates

docs/platforms/android/migration/index.mdx
Adds a section regarding SDK compatibility for migrating sentry-android to v8.
=> fix(android): Add Sentry Android SDK Compatibility for migrating sentry-android to v8

docs/cli/configuration.mdx
Minor copy edits, see preview at: https://sentry-docs-git-config-seo.sentry.dev/cli/configuration/ …
=> Apply SEO recs to cli/configuration/

docs/organization/integrations/compliance/index.mdx, docs/organization/integrations/compliance/vanta-eu/index.mdx, docs/organization/integrations/index.mdx
=> Masinette integration vanta eu

docs/product/dashboards/index.mdx
=> Update copy with SEO recs

docs/platforms/php/index.mdx, src/components/onboarding/index.tsx
Defaults onboarding options to unchecked, except for error monitoring
=> feat(platform): Default uncheck onboarding options

docs/platforms/java/common/configuration/options.mdx, docs/platforms/java/guides/jul/config.yml, docs/platforms/java/guides/log4j2/config.yml, docs/platforms/java/guides/logback/config.yml, docs/platforms/java/guides/servlet/config.yml, docs/platforms/java/guides/spring-boot/config.yml, docs/platforms/java/guides/spring/config.yml
=> Improve Java Options docs

src/middleware.ts
=> Update redirects to fix builds

platform-includes/getting-started-config/python.mdx
For a lot of integrations we include the code snippet to setup the SDK. In the include the include the buttons for "error monitoring", "performance", and "profiling" have been missing. (so the snippets did not let the user to select the features) …
=> Added the buttons to the getting-started-config include

docs/platforms/javascript/guides/react/features/react-router/v7.mdx
=> docs(js): Update stale reference

docs/platforms/ruby/common/configuration/options.mdx
=> feat(ruby): Add all missing ruby options

platform-includes/crons/requirements/java.mdx
Part of https://github.com/getsentry/sentry-java/issues/3522
=> feat(java): Mention that `aspectjweaver` is needed for crons

platform-includes/crons/requirements/java.mdx
In https://github.com/getsentry/sentry/pull/86970 I accidentally added it for all Java platforms.
=> fix(java): mention that aspectjweaver is required for Crons only on Spring Boot

platform-includes/getting-started-install/opentelemetry/java.mdx, platform-includes/getting-started-install/opentelemetry/java.spring-boot.mdx, platform-includes/getting-started-install/opentelemetry/java.spring.mdx, platform-includes/performance/opentelemetry-setup/with-java-agent/with-auto-init/java.mdx, platform-includes/performance/opentelemetry-setup/with-java-agent/without-auto-init/java.mdx, platform-includes/performance/opentelemetry-setup/with-java-agent/without-auto-init/java.spring-boot.mdx
Closes https://github.com/getsentry/sentry-java/issues/4222
=> feat(java): document adding the Sentry OTEL agent using JAVA_TOOL_OPTIONS

src/components/banner/index.tsx
Remove outdated banner from Docs.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest …
=> rm banner from docs

docs/platforms/apple/common/configuration/options.mdx, docs/platforms/apple/common/features/experimental-features.mdx
updates Apple experimental features page
=> chore(Apple): Updates Apple experimental features page

docs/concepts/key-terms/environments/index.mdx
=> SEO updates to environments

docs/platforms/android/index.mdx, docs/platforms/android/manual-setup/index.mdx
Adds SR config snippets to onboarding feature snippets for Android:
- ✅ Android (Getting Started)
- ✅ Android (Manual Setup)
Android part of https://github.com/getsentry/sentry-docs/pull/13034
related PR for in-product onboarding: https://github.com/getsentry/sentry/pull/87304
=> feat(SR): Add SR to Android onboarding features

docs/platforms/dotnet/common/configuration/heap-dumps.mdx
Documentation counterpart to https://github.com/getsentry/sentry-dotnet/pull/3981 (resolves https://github.com/getsentry/sentry-dotnet/issues/3605). 
Replaces https://github.com/getsentry/sentry-docs/pull/12846 since we couldn't get Vercel to run correctly on a PR from a fork (hoping it works from a branch instead). 
- cc: @bruno-garcia 
=> Heap dumps

apps/changelog/package.json, package.json, yarn.lock
bump sentry to try experimental https://github.com/getsentry/sentry-javascript/pull/15738
=> chore(deps): Bump sentry to `9.7.0-alpha.0`

docs/platforms/php/common/tracing/instrumentation/requests-module.mdx
Using `HandlerStack::create()` adds default middleware such as the one used for handling redirections. Manually creating a `HandlerStack` creates an empty one which will ignore certain Guzzle options. …
=> Use `HandlerStack::create()` in Guzzle tracing middleware snippet

docs/platforms/javascript/guides/nuxt/manual-setup.mdx
=> :fix typo in manual-setup.mdx

src/middleware.ts
fixes https://github.com/getsentry/sentry-docs/issues/13080
=> fix(elixir): Remove redirects since pages exist

next.config.js
we updated the project name in sentry
=> chore: Update project name for develop docs

next.config.js
This PR will fail the build on missing DSN env vars for production builds.
=> chore(platform): Crash build on missing DSN

docs/organization/integrations/debugging/codecomet/index.mdx, docs/organization/integrations/debugging/index.mdx, docs/organization/integrations/index.mdx
=> Masinette integration codecomet

docs/product/alerts/create-alerts/metric-alert-config.mdx
=> Update anomaly alerts docs

.github/workflows/algolia-index.yml
Hopefully the last follow up to https://github.com/getsentry/sentry-docs/pull/13099
=> fix(ci): Add env vars for dsn in algolia action

docs/platforms/javascript/common/configuration/integrations/unhandledrejection.mdx
resolves https://github.com/getsentry/sentry-docs/issues/12074 …
=> Use correct default mode in Node OnUnhandledRejection integration

docs/platforms/javascript/common/sourcemaps/troubleshooting_js/debug-ids/index.mdx
Follow-up of https://github.com/getsentry/sentry-docs/pull/13100#issuecomment-2754891680
=> fix(debug-ids): Fix broken link

docs/concepts/search/searchable-properties/session-replay.mdx
This prop was recently tested and added to suggestions in https://github.com/getsentry/sentry/pull/87926. It's camel cased.
=> ref(replays): update replay_type searchable prop

src/components/pageGrid.tsx
Closes https://github.com/getsentry/sentry-docs/issues/13160
=> fix: Ignore versioned pages in `PageGrid`

docs/platforms/javascript/guides/react-router/index.mdx
Small update about a wrong package import in the documentation  `@sentry/node` to `@sentry/react-router` …
=> docs(react-router): update import from `@sentry/node` to `@sentry/react-router`

docs/platforms/java/common/maven/index.mdx
Documents https://github.com/getsentry/sentry-maven-plugin/pull/137
=> feat(java): document multiple source roots feature of Maven plugin

docs/platforms/java/common/maven/index.mdx, platform-includes/getting-started-install/java.log4j2.mdx, platform-includes/getting-started-install/java.logback.mdx, platform-includes/getting-started-install/java.mdx, platform-includes/getting-started-install/java.spring-boot.mdx, platform-includes/getting-started-install/java.spring.mdx, platform-includes/source-context/java.mdx
Documents (and comes after) https://github.com/getsentry/sentry-maven-plugin/pull/126
=> feat(java): document versions validation feature of Maven plugin

docs/platforms/react-native/session-replay/index.mdx
=> feat(react-native): Add Session Replay experimental rendered option to the init code snippet

redirects.js
=> fix telegram notifications 404

docs/security-legal-pii/security/soc2.mdx
From [Slack convo](https://sentry.slack.com/archives/C8H0BQRDJ/p1744235971187739)
- [ x] Urgent deadline (GA date, etc.): Today
=> Update SOC2 documentation

docs/platforms/godot/configuration/options.mdx
=> feat(godot): Document `diagnostic_level` option

develop-docs/self-hosted/troubleshooting/docker.mdx
Accompanying https://github.com/getsentry/self-hosted/pull/3654 …
=> docs(self-hosted): troubleshooting guide around Amazon Linux 2023 and 'docker compose'

platform-includes/distributed-tracing/custom-instrumentation/go.mdx
fixing docs for trace injection, using incorrect context to get the hub.
=> fix(go) - tracing injection

src/components/platformSelector/index.tsx
closes https://github.com/getsentry/sentry-docs/issues/13350
=> feat(platform): Apply stricter matching in platform selector

docs/platforms/javascript/guides/nextjs/manual-setup.mdx
=> Fix router transition start snippet

docs/platforms/javascript/guides/cloudflare/index.mdx
ref https://github.com/getsentry/sentry-wizard/issues/824 …
=> feat(cloudflare): Document `wrapRequestHandler`

docs/pricing/quotas/manage-continuous-profile-hours.mdx
=> Add docs managing continuous profiling hours

develop-docs/sdk/telemetry/traces/span-data-conventions.mdx
=> Add naming conventions for flags on spans

develop-docs/self-hosted/index.mdx
Closes https://github.com/getsentry/self-hosted/issues/3644 …
=> docs(self-hosted): provide a note for air-gapped installation

docs/product/insights/retention-priorities.mdx
@indragiek discovered this page is missing, and nobody knows why, but there are links to it out in the wild that are 404ing. This isn't net new content, all I did was change some of the syntax so that it works in NextJS.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in …
=> Re-instate missing page

develop-docs/backend/application-domains/database-migrations/index.mdx
Adds the migration script to the develop docs.
=> feat(docs): Mention the update script in migration docs

docs/platforms/javascript/guides/react/features/react-router/v6.mdx, docs/platforms/javascript/guides/react/features/react-router/v7.mdx
closes https://github.com/getsentry/sentry-javascript/issues/16062
=> docs(js): Add comments for RR code snippets

docs/pricing/legacy-pricing.mdx
=> Update legacy-pricing.mdx with FAQ link

docs/pricing/quotas/manage-continuous-profile-hours.mdx, docs/pricing/quotas/manage-ui-profile-hours.mdx
Updating a couple links that we didn't have the URLs for when the new profiling docs were merged.
See links at the bottom of these pages to verify:
https://sentry-docs-git-missing-links.sentry.dev/pricing/quotas/manage-continuous-profile-hours/
https://sentry-docs-git-missing-links.sentry.dev/pricing/quotas/manage-ui-profile-hours/
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in …
=> Update profiling docs with migration guide link

docs/platforms/python/integrations/grpc/index.mdx, docs/platforms/python/profiling/index.mdx, docs/platforms/python/tracing/configure-sampling/index.mdx, docs/platforms/python/tracing/index.mdx, platform-includes/configuration/auto-session-tracking/python.mdx, platform-includes/configuration/before-breadcrumb-hint/python.mdx, platform-includes/configuration/before-send-fingerprint/python.mdx, platform-includes/configuration/before-send-hint/python.mdx, platform-includes/configuration/error-sampler/python.mdx, platform-includes/configuration/sample-rate/python.mdx, platform-includes/performance/opentelemetry-setup/python.mdx, platform-includes/performance/traces-sampler-as-filter/python.mdx, platform-includes/performance/traces-sampler-as-sampler/python.mdx, platform-includes/set-environment/python.mdx
Make sure `send_default_pii` is everywhere and also has a explanatory comment. Also removed some blank lines. …
=> Python has `send_default_pii` on every relevant `init()` call.

docs/platforms/rust/common/configuration/options.mdx, docs/platforms/rust/common/data-management/data-collected.mdx, docs/platforms/rust/common/tracing/instrumentation/automatic-instrumentation.mdx, docs/platforms/rust/guides/actix-web/index.mdx, docs/platforms/rust/index.mdx, platform-includes/configuration/config-intro/rust.mdx, platform-includes/getting-started-config/rust.mdx
Covers https://github.com/getsentry/team-sdks/issues/82 and https://github.com/getsentry/team-sdks/issues/121 for the Rust SDK
Also documents `max_request_body_size`
=> feat(rust): document data collected by the SDK and add `send_default_pii` to guides

docs/platforms/php/index.mdx
=> refactor: migrate php onboarding to new syntax

docs/product/explore/profiling/continuous-ui-profiling-migration-guide.mdx
We forgot to update this version number in the migration guide for the Continuous/UI Profiling GA.
=> Update Profiling SDK version number for iOS/macOS

docs/platforms/godot/configuration/options.mdx
Sync documentation to reflect changes in:
- https://github.com/getsentry/sentry-godot/pull/155 …
=> chore(godot): Sync restructured options

docs/pricing/legacy-pricing.mdx
reference on-demand budget instead of PAYG budget …
=> Update legacy-pricing.mdx to reflect am2 on-demand budgets

docs/security-legal-pii/security/mobile-privacy.mdx
=> adjust language to be clear on developer privacy responsability

docs/product/issues/issue-details/index.mdx
@limbonaut looks like we're missing docs for screenshots
=> add godot and maui to platforms with screenshot

docs/concepts/data-management/event-grouping/index.mdx
Just a super simply typo I saw when reading the docs! …
=> Fix small typo

develop-docs/ingestion/relay/creating-a-datacategory.mdx
It's become very common to add new data categories, this just writes the process down.
=> feat(relay-dev): Creating a new data category

docs/platforms/nintendo-switch/index.mdx, docs/platforms/playstation/index.mdx, src/components/platformIcon.tsx, src/data/platforms.yml
closes https://github.com/getsentry/team-gdx/issues/41 …
=> feat: playstation docs

docs/platforms/dart/common/index.mdx, docs/platforms/dart/guides/flutter/index.mdx, docs/platforms/dart/guides/flutter/manual-setup.mdx
=> fix(flutter): `sendDefaultPii` comment

develop-docs/sdk/data-model/envelope-items.mdx, develop-docs/sdk/telemetry/logs.mdx
SDK maintainers have asked for an example payload so they can quickly validate if something is right/wrong. This adds that. …
=> Add example full logs envelope payload

docs/product/onboarding/data-enrichment.mdx
Adding back a video that I had previously disabled because the google drive embed didn't work.
see: https://sentry-docs-git-add-vid.sentry.dev/product/onboarding/data-enrichment/#custom-instrumentation-for-any-additional-performance-metrics …
=> Embed vimeo vid in quickstart guide

develop-docs/development-infrastructure/devservices.mdx
* This PR updates the toggle documentation for devservices to give a more detailed view of what it does and how and when it should be used.
=> feat(toggle): Updating toggle docs

docs/platforms/react-native/manual-setup/expo.mdx
Tiny typo, but in a header so possibly affects SEO and in-page search
=> fix(RN): Typo in manual setup header

docs/platforms/apple/guides/ios/session-replay/index.mdx
While SR is usable on tvOS (and probably also visionOS), we don't have official support for it. Using it is not prevented, but there might be functional or performance-related issues
Preview: https://sentry-docs-git-kahest-sr-ios-otherplatforms-faq.sentry.dev/platforms/apple/guides/ios/session-replay/#faq
=> feat(SR): Add FAQ note about SR on non-iOS

docs/platforms/apple/common/index.mdx
Mention capturing uncaught exceptions for the macOS getting started page, which is a useful feature users should know about.
=> feat(apple): Uncaught exceptions in macOS setup

docs/platforms/godot/configuration/stack-traces.mdx
Link to Vulkan SDK in prerequisites in "Readable Stack Traces" guide. …
=> Godot: Mention Vulkan SDK as prerequisite on macOS

develop-docs/sdk/data-model/event-payloads/user.mdx
[Vercel Preview](https://develop-docs-bmq9r90m3.sentry.dev/sdk/data-model/event-payloads/user/)
Related to https://github.com/getsentry/sentry/pull/90993 , where we added the prefix `data.` to all unknown User Context keys, making them stand out in the UI.
It was confusing to some users that the UI showed the User data in a "prettified" manner, not matching the expected keys sent from the SDKs, so I'm adding some warnings/notes to the develop docs to clear this up.
*Make sure you've checked the …
=> chore: clarify user context UI and interface

develop-docs/application-architecture/overview.mdx
Fix the Event Data name to reflect silo region.
=> docs(overview): Fix event data region in mermaid

docs/platforms/javascript/common/enriching-events/scopes/index.mdx
Closes https://linear.app/getsentry/issue/FE-405/user-feedback-elaborate-on-current-scope-usage
=> fix(js): Clarify scope setting docs

docs/platforms/javascript/common/install/esm-without-import.mdx, docs/platforms/javascript/guides/nuxt/install/limited-server-tracing.mdx, docs/platforms/javascript/guides/solidstart/install/limited-server-tracing.mdx
Came up in https://discord.com/channels/621778831602221064/1369508106262020187
=> Clarify esm restrictions

docs/platforms/react-native/migration/sentry-expo.mdx
fixes: https://github.com/getsentry/sentry-docs/issues/12935
updated based on
- https://docs.expo.dev/versions/latest/sdk/constants/
- https://docs.expo.dev/versions/latest/sdk/device/
- https://docs.expo.dev/versions/latest/sdk/application/
- https://docs.expo.dev/versions/latest/sdk/updates/
Look, I get it. The …
=> Update Expo Migration Guide Tags Recommendation

docs/platforms/javascript/guides/astro/index.mdx
Adding small notice about using environment variables in Astro.
=> docs(astro): Add note about env docs

includes/logs/javascript-usage.mdx
Based on feedback from slack after merging in https://github.com/getsentry/sentry-docs/pull/13603 …
=> feat: Update snippet to use logger.X

includes/logs/javascript-usage.mdx
=> fix(logs): Remove extra word

docs/organization/integrations/debugging/index.mdx, docs/organization/integrations/debugging/tembo/index.mdx, docs/organization/integrations/index.mdx
=> Masinette integration Tembo

docs/platforms/dart/guides/flutter/troubleshooting.mdx, platform-includes/capture-error/dart.flutter.mdx
fixes https://github.com/getsentry/sentry-docs/issues/12213
=> fix(Flutter): Adds missing , in snippets

docs/platforms/rust/common/data-management/data-collected.mdx
Updating the docs to reflect information relevant for the latest release.
=> feat(rust): update data collected page with updated info

docs/product/stats/index.mdx
Closes https://github.com/getsentry/sentry-docs/issues/13092 …
=> Add Discarded Hash to list of filters on stats page

docs/product/explore/trace-explorer/index.mdx
Fixing the linting issue from this branch (https://github.com/getsentry/sentry-docs/pull/13652) and updating trace explorer docs with a link. 
=> Adding span metrics link to trace explorer docs

includes/feature-stage-alpha-logs.mdx
using `via` makes more sense than `on` in this case. …
=> Logs alpha note small wording change

platform-includes/logs/integrations/python.mdx, platform-includes/logs/options/python.mdx, platform-includes/logs/requirements/python.mdx, platform-includes/logs/setup/python.mdx, platform-includes/logs/usage/python.mdx
Fixes some issues with the logs docs
=> fix(python): fix Python logs docs

.github/CODEOWNERS
- Remove files that no longer exist
- Update file paths for items that were migrated after next.js
- Add notes to how this works
=> fix(CODEOWNERS): Fix outdated contents

platform-includes/performance/configure-sample-rate/javascript.react-router.mdx, platform-includes/performance/configure-sample-rate/javascript.solid.mdx, platform-includes/performance/configure-sample-rate/javascript.solidstart.mdx
Updates tracing code snippets for 
- react router
- solid
- solidstart
=> docs(js): Update tracing code snippets

docs/product/explore/logs/getting-started/index.mdx
Just created these two issues, realized we weren't tracking support for these just yet. …
=> Add Electron and React Native tracking issues for logs

docs/product/explore/logs/getting-started/index.mdx
=> Refactor logs getting started to use platformicons

develop-docs/sdk/telemetry/traces/dynamic-sampling-context.mdx
Related to https://github.com/getsentry/sentry-docs/pull/13688
=> docs(dsc): Rename `org` to `org_id`

docs/platforms/ruby/logs/index.mdx, docs/product/explore/logs/getting-started/index.mdx, platform-includes/logs/requirements/ruby.mdx, platform-includes/logs/setup/ruby.mdx, platform-includes/logs/usage/ruby.mdx
=> [ruby] initial docs for logs

develop-docs/sdk/telemetry/traces/trace-origin.mdx
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, …
=> Fix formatting in dev docs

docs/organization/dynamic-sampling/index.mdx
- There has been some confusion around this - add a small callout to clarify that dynamic sampling only applies to transactions and spans
- Closes TET-462
=> chore(dynamic-sampling): point out that dynamic sampling does not apply to errors

docs/platforms/javascript/guides/react-router/index.mdx
documents https://github.com/getsentry/sentry-javascript/issues/16160
=> docs(js): Update tracing integration for RR

docs/platforms/go/common/logs/index.mdx, platform-includes/logs/integrations/android.mdx, platform-includes/logs/integrations/java.mdx, platform-includes/logs/requirements/javascript.mdx
- Add snippet about js loader support w/ logs
- Add links to upcoming android logging integrations
- Update prose for Java logging integrations
- Format go logs doc and add upcoming go logging integrations
=> Add snippet about JS loader and update logging integration links

redirects.js
This PR fixes link which is autogenerated at https://sentry-sdks.sentry.io/settings/sentry-apps/expo/
Exists: https://docs.sentry.io/organization/integrations/deployment/expo/
Should redirect to the existing page: https://docs.sentry.io/organization/integrations/expo/
Look, I get it. The entity doing business as …
=> Redirect integrations/expo to integrations/deployment/expo

docs/platforms/javascript/guides/capacitor/index.mdx, package.json
`___PRODUCT_OPTION_END___ session-replay` was missing so it was cutting the sample snippet from Angular 12/13
This PR adds the mark to tell where session replay ends …
=> Add end product option mark

docs/product/explore/logs/getting-started/index.mdx
Missed documenting this - thanks to David-Graphlit on the Sentry discord for point this out! https://discord.com/channels/621778831602221064/1349050507926175805/1373425854792601690 …
=> Document .NET in upcoming logs section

includes/custom-measurements-supported-sdks.mdx
=> fixing 404 link to python doc

platform-includes/debug-symbols-apple/_default.mdx
Fixes the Fastlane Plugin link: …
=> Fix link for iOS fastlane plugin

docs/concepts/search/searchable-properties/session-replay.mdx
Depends on https://github.com/getsentry/sentry/pull/91315
Ref
- https://github.com/getsentry/team-replay/issues/566
=> feat(replay): document user.geo search props

develop-docs/self-hosted/releases.mdx
Adds documentation for hard stop for self-hosted at 25.5.1 …
=> chore(self-hosted): Add hard stop for 25.5.1

platform-includes/debug-symbols/dart-plugin/dart.mdx
=> add url prefix

docs/concepts/search/searchable-properties/session-replay.mdx
depends on https://github.com/getsentry/sentry/pull/92041
=> replay: document is_archived search prop

docs/organization/integrations/compliance/vanta-eu/index.mdx, docs/organization/integrations/compliance/vanta/index.mdx
- URL to vanta installation instructions was broken - update
=> chore(vanta): update url to vanta installation instructions

docs/cli/installation.mdx
=> cli macOS instead of osx

docs/platforms/javascript/common/troubleshooting/index.mdx
Addresses feedback from https://github.com/getsentry/sentry-javascript/issues/8105#issuecomment-2906733413
(cc @kylemh) …
=> fix(nextjs): Add more fine-grained hoist pattern to IITM troubleshooting

docs/product/explore/logs/getting-started/index.mdx
https://github.com/getsentry/sentry-unity/issues/2172 and https://discord.com/channels/621778831602221064/1376699803177717791/1376699803177717791
as well as github.com/getsentry/sentry-unreal/issues/883 …
=> feat(logs): Add tracking issue for unity and unreal

app/layout.tsx
Enables custom events in our plausible provider
=> feat(platform): Enable plausible tagged events

docs/security-legal-pii/security/ip-ranges.mdx
documents https://github.com/getsentry/sentry-docs/pull/13819
=> docs: Add callout on ip-ranges endpoint

develop-docs/backend/application-domains/kafka.mdx
Recover changes from #13834 and point to more detailed instructions in the shared Kafka README file.
=> Recover Kafka notes and make reference to deployment notes

docs/platforms/javascript/common/tracing/distributed-tracing/index.mdx, docs/platforms/javascript/guides/nextjs/manual-setup.mdx, includes/nextjs-app-router-14-config.mdx, platform-includes/distributed-tracing/how-to-use/javascript.nextjs.mdx, platform-includes/performance/configure-sample-rate/javascript.nextjs.mdx
ref https://github.com/getsentry/sentry-javascript/issues/16388
=> docs(js): Add note for distributed tracing in Next.js 14 App router

platform-includes/crons/setup/go.mdx
Go's cron upsert instructions are wrong, and can cause failed checkins as the checkinId is not specified - see discussion on getsentry/sentry#92822 …
=> fix(go): Update go cron to include the checkinId

platform-includes/getting-started-config/unreal.mdx
Related to https://github.com/getsentry/sentry-unreal/issues/871
=> Add notice about screenshot capturing to Unreal SDK configuration sample

docs/platforms/apple/guides/ios/session-replay/index.mdx
Replaces "website" with "app" in iOS session replay doc. …
=> Remove reference to website in iOS session replay doc

docs/platforms/elixir/integrations/plug_and_phoenix/index.mdx
Updating Elixir's Plug and Phoenix guide to reflect changes made in https://github.com/getsentry/sentry-elixir/issues/895
In short, `PlugCapture` makes a lot of sense for Cowboy applications but isn't needed for apps using new Bandit webserver.
**I believe it's best to go live the same time as next Sentry package version** …
=> docs(elixir): Only recommend Sentry.PlugCapture for Cowboy applications

docs/platforms/javascript/guides/cloudflare/frameworks/astro.mdx, docs/platforms/javascript/guides/cloudflare/frameworks/hono.mdx, docs/platforms/javascript/guides/cloudflare/frameworks/index.mdx, docs/platforms/javascript/guides/cloudflare/frameworks/remix.mdx, docs/platforms/javascript/guides/cloudflare/frameworks/sveltekit.mdx
Adding back sveltekit, remix, and astro Cloudflare guides
=> Fix - Restoring Cloudflare Framework Guides 

docs/platforms/javascript/guides/cloudflare/frameworks/astro.mdx, docs/platforms/javascript/guides/cloudflare/frameworks/hono.mdx, docs/platforms/javascript/guides/cloudflare/frameworks/remix.mdx, docs/platforms/javascript/guides/cloudflare/frameworks/sveltekit.mdx, docs/platforms/javascript/guides/cloudflare/index.mdx, platform-includes/getting-started-config/javascript.cloudflare.mdx, platform-includes/getting-started-config/javascript.cloudflare.workers.mdx, platform-includes/getting-started-install/javascript.cloudflare.mdx
- Move various snippets into includes
- Cover the 'release' attribute on all worker snippets
- General normalization
=> feat: Overhaul Cloudflare docs

docs/organization/data-storage-location/index.mdx
#9356 incorrectly updated this, these are stored in region silos.
=> chore(issues): Correct storage location in docs

docs/product/explore/logs/getting-started/index.mdx
ref https://github.com/getsentry/sentry-unreal/issues/883
=> Add unreal sdk to upcoming logs sdk section

docs/product/explore/logs/getting-started/index.mdx
Close https://github.com/getsentry/sentry-docs/issues/13998
Close https://github.com/getsentry/sentry-docs/issues/14020
=> fix(php): fix logs guide link

docs/platforms/dart/guides/flutter/session-replay/index.mdx
=> flutter: fix dsn placeholder

docs/platforms/dart/guides/flutter/migration.mdx
Add more info to the migration that makes it easier to troubleshoot if an error happens
=> flutter: update v9 migration doc

platform-includes/logs/usage/python.mdx
Documents based on feedback from https://github.com/getsentry/sentry-python/discussions/4220#discussioncomment-13491570
=> Document python attributes kwarg for logs

scripts/generate-md-exports.mjs
Should cut down build times significantly after the first run if the cache persists in Vercel
Locally my times went from 60 seconds down to 8 seconds.
=> ci(md): Add caching to md-export script

docs/platforms/javascript/common/configuration/integrations/vercelai.mdx
Closes [TET-683: Adjust vercel ai docs to include experimental_telemetry](https://linear.app/getsentry/issue/TET-683/adjust-vercel-ai-docs-to-include-experimental-telemetry)
=> chore(vercel-ai): recommend adding recordInputs and recordOutputs

platform-includes/configuration/integrations/javascript.nestjs.mdx
Markdown table formatting was corrected in `platform-includes/configuration/integrations/javascript.nestjs.mdx`. The changes addressed rendering issues caused by misaligned columns and extra pipe characters.
Specifically:
*   The table header separator row was adjusted by removing an extraneous `| --- |` to align with a 5-column structure.
*   The `supabaseIntegration` row was modified to remove an extra, empty column.
*   The checkmark in the `unleashIntegration` row was relocated to the correct "Additional Context" column, resolving its placement in an unintended extra column.
These adjustments ensure the table consistently renders with five columns: "Integration name", "Auto Enabled", "Errors", "Tracing", and "Additional Context", improving readability and visual alignment.
=> fix: Markdown table rendering for nestjs integrations

platform-includes/logs/usage/android.mdx, platform-includes/logs/usage/java.mdx
=> Document Java Log custom attributes

platform-includes/getting-started-features-expandable/_default.mdx, platform-includes/getting-started-verify-locate-data/javascript.mdx
Adding callouts to Logs docs and links from refs to the Sentry UI. Also removed a layer or redirect logic that's no longer needed.  …
=> Add Logs callouts and fixes

develop-docs/backend/application-domains/metrics.mdx
Because this has been removed from the codebase, so it could be confusing for users. …
=> Add removal note to metrics backend

docs/platforms/javascript/guides/nextjs/configuration/build/index.mdx
documents https://github.com/getsentry/sentry-javascript/pull/16718
=> docs(js): Document `errorHandler`option for nextjs

docs/platforms/dotnet/common/configuration/disable-integrations.mdx
Resolves https://github.com/getsentry/sentry-dotnet/issues/4266
cc: @Flash0ver 
=> Document how to disable RuntimeMarshalManagedExceptionCapture

develop-docs/sdk/telemetry/traces/modules/ai-agents.mdx
Just some typos and grammar fixes to develop docs. …
=> Minor changes to wording

docs/organization/integrations/integration-platform/ui-components/stacktrace-link.mdx
=> Update broken link in stack trace link

docs/platforms/javascript/guides/cloudflare/features/workflows.mdx
=> Update word in cloudflare workflows docs

scripts/generate-md-exports.mjs
context: markdown files with `# Tags` as the h1 are basically useless
=> feat(md): Use page title as the top level title

docs/product/insights/getting-started.mdx
=> Update documentation to include tracing

docs/platforms/react-native/session-replay/privacy/index.mdx
Stresses out that the mask/unmask components may not behave as expected with view flattening 
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. …
=> RN: Add warning on the mask/unmask behaviour with view flattening

platform-includes/getting-started-config/kotlin.kotlin-multiplatform.mdx
=> fix(kmp): getting started code snippet typo

docs/platforms/javascript/guides/nextjs/configuration/build/index.mdx
ref https://github.com/getsentry/sentry-javascript/pull/16867
=> docs(js): Update default value for `deleteSourcemapsAfterUpload` to `true`

docs/platforms/dart/guides/flutter/migration.mdx, docs/platforms/dart/guides/flutter/troubleshooting.mdx
Updates troubleshooting related to Linux issues for Flutter
=> flutter: update troubleshooting page

package.json, yarn.lock
We previously tested an alpha version of our SDK for dogfooding purposes, the testing period has concluded and we can now swap back to a stable release. …
=> chore: Swap back to stable `@sentry/nextjs` SDK

docs/platforms/dart/common/feature-flags/index.mdx, docs/platforms/javascript/common/configuration/integrations/featureflags.mdx, docs/platforms/javascript/common/configuration/integrations/launchdarkly.mdx, docs/platforms/javascript/common/configuration/integrations/openfeature.mdx, docs/platforms/javascript/common/configuration/integrations/statsig.mdx, docs/platforms/javascript/common/configuration/integrations/unleash.mdx, docs/platforms/javascript/common/feature-flags/index.mdx, docs/platforms/python/feature-flags/index.mdx, docs/platforms/python/integrations/launchdarkly/index.mdx, docs/platforms/python/integrations/openfeature/index.mdx, docs/platforms/python/integrations/statsig/index.mdx, docs/platforms/python/integrations/unleash/index.mdx, platform-includes/feature-flags/prerelease-alert/_default.mdx
=> ref(flags): remove open beta label

docs/platforms/php/guides/laravel/logs/index.mdx
Via Discord it came up that not all Laravel config files are up-to-date with out instructions. So add some common troubleshooting steps that should help people setup the logs beta.
/cc @AbhiPrasad (as discussed in Discord)
=> docs(laravel): Add logs beta troubleshooting steps

src/components/docPage/index.tsx
=> chore(ai): Hide copy llm button on mobile

docs/platforms/javascript/guides/nextjs/configuration/build/index.mdx
documents https://github.com/getsentry/sentry-javascript/issues/16683
=> docs(js): Add Next.js build option `disableManifestInjection`

docs/platforms/android/configuration/options.mdx, docs/platforms/android/tracing/instrumentation/automatic-instrumentation.mdx
added deadlineTimeout Android option …
=> Add deadlineTimeout Android option

docs/organization/integrations/index.mdx, docs/organization/integrations/issue-tracking/index.mdx, docs/organization/integrations/issue-tracking/starsling/index.mdx, docs/organization/integrations/notification-incidents/cased/index.mdx, docs/organization/integrations/notification-incidents/index.mdx
=> Masinette integration publication cased starsling

platform-includes/sensitive-data/set-tag/python.mdx, platform-includes/sensitive-data/set-user/python.mdx
[This section](https://docs.sentry.io/platforms/python/data-management/sensitive-data/#examples) in the Python docs is currently showing JS examples. Adding the missing examples in Python.
Direct link to preview: https://sentry-docs-git-ivana-pythonsensitive-data-python-examples.sentry.dev/platforms/python/data-management/sensitive-data/#examples
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of …
=> feat(python): Add missing sensitive data examples

develop-docs/backend/application-domains/options.mdx
=> Cleaning up the options documentation to prevent future confusion

includes/react-native-react-navigation-setup.mdx
This PR fixes an incorrect example in the documentation where `React.useRef()` was used with `NavigationContainer`.
React Navigation requires using `createNavigationContainerRef()` instead of `React.useRef()` to ensure proper access to navigation methods from outside React components.
This change ensures consistency with React Navigation's official recommendation and prevents potential issues when performing programmatic navigation.
Fixes: N/A
---
---
---
*Make sure you've checked the following …
=> docs(navigation): Use createNavigationContainerRef instead of React.useRef

docs/product/sentry-mcp/index.mdx
```
Added a note to the "OAuth Configuration (Recommended)" section on the Sentry MCP documentation page (`/product/sentry-mcp`). This note advises users to log out and back in to their LLM's MCP integration to refresh access if they've joined a new Sentry organization. …
```
=> Add note to Sentry OAuth configuration page

package.json, yarn.lock
=> chore: Bump `@sentry/nextjs` to `10.0.0-beta.0`

docs/platforms/python/integrations/strawberry/index.mdx
The Sentry docs for the `strawberry-graphql` integration named `fastapi` as a required dependency to get started with Strawberry's debug server. That's incorrect! To get started with the Strawberry debug server, installing `strawberry-graphql[debug-server]` is all that's needed. The `fastapi` dependency mentioned in the docs was completely unneeded/unused. 
(I'm co-maintaining `strawberry-graphql`, that's how I know ;) )
Look, I …
=> docs(strawberry): remove unneeded dependency

package.json, yarn.lock
=> chore: Bump @sentry/nextjs to v10

docs/platforms/python/integrations/index.mdx, docs/platforms/python/integrations/openai/index.mdx
This page was removed until we make the OpenAI integration in Python work with the new Otel based AI Agents dashboard and the "AI Spans" view in the trace waterfall. The SDK supports this now. 
For future me: This is the Commit that removed the pages:
https://github.com/getsentry/sentry-docs/commit/3cfe8384c46663313d58ba883dfa252004d9ea00
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of …
=> Bring back OpenAI integration page for Python

includes/console-intro/xbox.mdx
since we have CI for it and a devkit around to validate changes, lets  mention Xbox One support
=> xbox: support for xbox one

docs/security-legal-pii/security/soc2.mdx
Resolves [DOCS-9D7](https://sentry.sentry.io/issues/feedback/?feedbackSlug=docs%3A6768855861&project=1267915)
=> Add link to legal settings page

docs/product/ai-in-sentry/index.mdx
=> Adding Seer Query Assistant as one of the Gen AI features

platform-includes/sensitive-data/set-tag/apple.mdx
In [Scrubbing Sensitive Data](https://docs.sentry.io/platforms/apple/guides/ios/data-management/sensitive-data/), there's currently a typo in the example. This fixes it:
`birthady` -> `birthday` …
=> Fix typo in apple.mdx

docs/product/insights/ai/agents/getting-started.mdx, docs/product/insights/ai/mcp/getting-started.mdx
=> docs(ai) Fix Sentry import

package.json
leftover from https://github.com/getsentry/sentry-docs/pull/13987
=> chore: Remove unused workspaces

docs/product/insights/frontend/index.mdx
the existing link is to the backend page, but based on context it should be to the frontend page …
=> fix(insights/frontend): fix typo in link, backend --> frontend

docs/organization/integrations/debugging/index.mdx, docs/organization/integrations/debugging/sevvy/index.mdx, docs/organization/integrations/index.mdx
=> add Sevvy integration docs

redirects.js
=> fix: Adding redirect for moved hydrogen docs to cloudflare

docs/platforms/dart/guides/flutter/profiling/index.mdx
Make the wording a bit clearer
=> feat(flutter): update profiling docs

develop-docs/development-infrastructure/python-dependencies.mdx
https://linear.app/getsentry/issue/DI-1202/update-dev-docs-for-uv
this assumes https://github.com/getsentry/sentry/pull/97627 is merged btw
=> dev: update python dependency instructions

docs/organization/integrations/data-visualization/amazon-sqs/index.mdx, docs/organization/integrations/data-visualization/segment/index.mdx, docs/organization/integrations/data-visualization/splunk/index.mdx, docs/organization/integrations/issue-tracking/asana/index.mdx
=> chore(integrations): Fix availble -> available typo

platform-includes/logs/options/react-native.mdx, platform-includes/logs/requirements/react-native.mdx, platform-includes/logs/setup/react-native.mdx
Version 7.0.0 will no longer have logs as experimental, this PR updates the logs docs to move the options  away from experimental.
=> Logs(React-Native) Remove logs from experimental

docs/platforms/java/common/configuration/releases.mdx, platform-includes/configuration/auto-session-tracking/java.mdx
Clarifies that Release Health is actually supported for Java Desktop platforms
Closes https://github.com/getsentry/sentry-java/issues/4663
=> feat(releases): Clarify Java desktop Release Health support

docs/product/user-feedback/index.mdx
Reference User Feedback Basics Page on User Feedback Product Docs Homepage!
=> Reference User Feedback Basics Page on User Feedback Product Docs Homepage

docs/concepts/data-management/event-grouping/index.mdx
=> Fix typo in event grouping documentation

docs/platforms/react-native/manual-setup/manual-setup.mdx
In the [Configure Automatic Source Maps Upload](https://docs.sentry.io/platforms/react-native/manual-setup/manual-setup/#configure-automatic-source-maps-upload) section the suggested script broke in RN `0.81.1` due to the [addition of the quote in this line](https://github.com/facebook/react-native/pull/53194/files#diff-f54c12ea092578cc313644cb316f74e90eb246ed8b601411cfc85f55e06ffbd6L46).
This update removes the `\"` in the script for RN `0.81.1`.
This issue was reported as a docs issue internally and is related to https://github.com/getsentry/sentry-react-native/issues/5118
- Teamwork …
=> RN: Update Configure Automatic Source Maps Upload script for RN 0.81.1

docs/pricing/quotas/manage-seer-budget.mdx
=> Update seer budget docs

docs/product/alerts/alert-types.mdx, docs/product/dashboards/index.mdx
Updating to remove alert on plan availability for dashboards and metric alerts
Preview: 
https://sentry-docs-git-update-dashboards-alert.sentry.dev/product/dashboards/
https://sentry-docs-git-update-dashboards-alert.sentry.dev/product/alerts/alert-types/
=> Updating to remove alert on plan availability for dashboards and metric alerts

docs/platforms/apple/common/troubleshooting/index.mdx
If users do this it would actually cause the build to fail. It hasn't been required for a while but only recently started making builds fail.
=> Remove outdated docs

develop-docs/sdk/expected-features/index.mdx, develop-docs/sdk/telemetry/check-ins.mdx
=> fix(develop): Clarify that before_send should not apply to check-ins

develop-docs/development-infrastructure/environment/index.mdx, develop-docs/development-infrastructure/ngrok.mdx
Using `devservices up taskbroker` only works if you have taskbroker cloned locally which most people won't.
=> fix(tasks) Fix taskbroker startup docs

docs/product/partnership-platform/oauth-integration.mdx
reverting email to partnership-platform@sentry.io while we figure out the correct one …
=> Email update

platform-includes/llm-rules-logs/javascript.nextjs.mdx, platform-includes/llm-rules-logs/javascript.node.mdx, platform-includes/llm-rules-logs/javascript.react.mdx, platform-includes/llm-rules-platform/_default.mdx, platform-includes/llm-rules-platform/javascript.nextjs.mdx, platform-includes/llm-rules-platform/javascript.node.mdx, platform-includes/llm-rules-platform/javascript.react.mdx
Quick update to keep up with how Cursor handles rules. No contents of the rules changed, so nothing needed in Product  onboarding docs, as noted in the comment of these files, e.g https://github.com/getsentry/sentry/blob/master/static/app/gettingStartedDocs/javascript/nextjs.tsx.  …
=> Modernize Cursor rules format

docs/platforms/javascript/guides/wasm/index.mdx
=> Fix troubleshooting link

platform-includes/distributed-tracing/limiting-traces/python.mdx
=> Use raw string for regex

docs/organization/integrations/index.mdx, docs/organization/integrations/issue-tracking/index.mdx, docs/organization/integrations/issue-tracking/makeplane/index.mdx
=> feat: adds makeplane integration docs

docs/platforms/javascript/guides/ember/index.mdx, platform-includes/getting-started-prerequisites/javascript.ember.mdx
Updated the Ember quick start guide to follow our Quick Start guide template.
Closes: #14801 
=> docs(js): Update Ember quick start guide

src/components/codeContext.tsx
Use the new `/integration/` paths for the OTLP logs and traces endpoints. (This is new for traces and corrects a typo for logs).
=> fix(otlp): Update OTLP URLs

develop-docs/frontend/url-state.mdx
=> feat(frontend): document nuqs

docs/platforms/react-native/manual-setup/expo.mdx
Issue: https://github.com/getsentry/sentry-react-native/issues/5127
In short, the PR adds the missing setup for Expo in regard to session replay and logs.
=> Ref(Expo): Update Expo Getting Started docs.

docs/platforms/dotnet/common/configuration/options.mdx
Resolves https://github.com/getsentry/sentry-dotnet/pull/4452
- https://github.com/getsentry/sentry-dotnet/pull/4452
cc: @Flash0ver 
=> Documented backpressure handling option for .NET

develop-docs/self-hosted/tasks.mdx
Insights from my own findings & from Mark Story! …
=> docs(self-hosted): provide guide for scaling up taskbroker and taskworker

docs/product/insights/frontend/web-vitals/index.mdx, docs/product/insights/overview/filters-display/widgets.mdx
Copy refresh and update old Arcade. …
=> Web vitals refresh
