src/collections/_documentation/clients/cocoa/advanced.md

Under Change event before sending it, there's a typo in the sentence "You have to set the block somewhere in you code", it should be "You have to set the block somewhere in your code".

"you" to "your"

---

src/collections/_documentation/server/plugins.md

I saw that all the GitHub repositories of the official plugins were deprecated and pointed to a new official plugin repository so I changed the documentation accordingly.

Fix information about official plugins

---

src/_includes/components/alert.html
src/collections/_dev_components/includes/alert.md
src/collections/_documentation/error-reporting/quickstart.md

The following link will be possible with the code below:
```
https://docs.sentry.io/#jump-here
```
Note that when constructing urls with query parameters, the hash goes at the end
```
https://docs.sentry.io/?some=query#jump-here
```
```
{% include components/alert.html
deep_link="jump-here"
title="Pay attention"
content="This is the body of the alert"
level="danger"
%}
```

Feat: Add deep link support to alert component

---

src/collections/_documentation/platforms/go/migration.md

These are two simple revision to the golang example code syntax in the sentry-go migration document.

fix: Update go WrapWithExtra example typo

---

src/collections/_documentation/clients/react-native/manual-setup.md

Current import comment states that
```
#import <React/RNSentry.h> // versions of react < 0.40 
```
instead it should be
```
#import <React/RNSentry.h> // versions of  react-native < 0.40
```

Change RNSentry import comment

---

src/collections/_documentation/platforms/javascript/sourcemaps.md

(ref) rewriteFrames mention in source maps docs

---

.travis.yml

Travis has been slowly transitioning repos to a new build environment and ours flipped over last night, which broke everything. This fixes us to the previous environment.
Related reading: https://changelog.travis-ci.com/xenial-as-the-default-build-environment-99476

Require Trusty Travis Environment

---

src/collections/_documentation/workflow/integrations/integration-platform/index.md

A few links weren't working in-page and a few links weren't re-routing to Webhooks. This'll fix all that.

Fix links in Integration Platform index

---

src/collections/_documentation/clients/cocoa/dsym.md

- step required to add the dsym file as a dependency to the run script
- new build system in xcode 10 parallelizes dsym generation and run scripts so the input file is required as outlined in the following resources
- https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes/build_system_release_notes_for_xcode_10
- https://stackoverflow.com/questions/53205108/run-script-phase-after-dsym-is-generated-with-xcode-10-on-build
- https://stackoverflow.com/questions/52709928/build-phase-script-is-running-before-needed-files-are-created-in-xcode-10

Docs: Add step to `Upload Symbols with sentry-cli` section

---

src/collections/_documentation/cli/releases.md

Change `-commit` to `--commit` (add missing dash).

Fix typo in cli/releases.md

---

src/collections/_documentation/enriching-error-data/context.md

Replace incorrect use of `it's` with `its`.

Fix typo in enriching-error-data/context.md

---

src/collections/_documentation/development/sdk-dev/event-payloads/stacktrace.md

We are now formally deprecating `event.stacktrace` in favor of `thread.stacktrace` or `exception.stacktrace`. 
Sentry will retain support for top-level stack traces and normalize them into either an exception or thread. SDKs should deprecate top-level stacktrace attributes and remove them with the next major release.

ref(dev): Deprecate event.stacktrace

---

src/collections/_documentation/platforms/python/aiohttp.md
src/collections/_documentation/platforms/python/asgi.md
src/collections/_documentation/platforms/python/aws_lambda.md
src/collections/_documentation/platforms/python/beam.md
src/collections/_documentation/platforms/python/bottle.md
src/collections/_documentation/platforms/python/celery.md
src/collections/_documentation/platforms/python/django.md
src/collections/_documentation/platforms/python/falcon.md
src/collections/_documentation/platforms/python/gnu_backtrace.md
src/collections/_documentation/platforms/python/logging.md
src/collections/_documentation/platforms/python/redis.md
src/collections/_documentation/platforms/python/rq.md
src/collections/_documentation/platforms/python/sanic.md
src/collections/_documentation/platforms/python/serverless.md
src/collections/_documentation/platforms/python/sqlalchemy.md
src/collections/_documentation/platforms/python/tornado.md
src/collections/_documentation/platforms/python/wsgi.md

Prioritizing our most popular frameworks to the top of the sidebar for easier user access.

Update sidebar order

---

src/collections/_documentation/workflow/integrations/global-integrations.md

Add troubleshooting note for Jira Server when users receive a 4xx or 5xx error.
Help center article linked in note: https://help.sentry.io/hc/en-us/articles/360034547794-Why-am-I-receiving-a-4xx-5xx-error-for-the-Jira-Server-Integration-
cc @getsentry/cops / anyone - any feedback welcome for messaging in the Help Center article and/or the Troubleshooting note.

feat: Add troubleshooting note for Jira Server

---

src/collections/_documentation/platforms/python/index.md

also fixed what was supposed to be `{{default}}` showing up as ``
Now:
In this change:

(ref) Add link to Python fingerprinting code samples

---

src/collections/_documentation/api/events/get-group-events.md
src/collections/_documentation/api/events/get-project-events.md

The api docs generator is broken I guess so https://github.com/getsentry/sentry/pull/14529 didn't do anything

ref(api-docs): Document full param

---

_config.yml
src/_assets/css/_vendor/bootstrap/dist
src/_assets/css/_vendor/bootstrap/src
src/_assets/css/screen.scss

This patch replaces our hidden symlinks for bootstrap with the proper configuration so we can build the docs on Windows too.

build(config): Use proper configuration instaed of symlinks

---

src/collections/_documentation/workflow/search.md

Updates were made to Search and needed documentation. Added `status` to Issue Props. Also, sorted the Issue Props in alphabetical order.

added status and made issue props alphabetical

---

src/collections/_documentation/server/config.md

Follow up to https://forum.sentry.io/t/sentry-internal-debug-log-verbosity/7056/2?u=byk

feat(logging): Add section about logging to self-hosted

---

src/collections/_documentation/platforms/php/index.md

What it looks like now:
What it should look like / will look like after merging:

Fix formatting of levels in PHP docs

---

src/collections/_documentation/platforms/go/config.md

Served at https://docs.sentry.io/platforms/go/config/
This matches the typo fix in the source code @ https://github.com/getsentry/sentry-go/pull/50

Fix typo in Go configuration documentation

---

src/collections/_documentation/error-reporting/configuration/index.md

As emerged in https://github.com/getsentry/sentry-php/issues/881, we have two supported options in the PHP SDK not properly documented.

Mark two options as supported in the PHP SDK

---

src/collections/_documentation/workflow/releases.md

Update the JavaScript documentation link to point to the current JavaScript docs instead of the legacy client docs

Update javascript documentation link

---

src/collections/_documentation/server/performance.md

This issue emerged in getsentry/sentry-php#857. We found the fix, and this will suggest it.
For reference:
> When the `enable_compression` option was enabled it was affecting only the responses received by the server while first of all the requests should be compressed with GZIP. This PR fixes the problem. Note that if Sentry is running in uWSGI mode and behind a NGINX server as described in the [documentation](https://docs.sentry.io/server/performance/#performance-web-server) and the client sends a chunked request (as in our case) then a bug in the latter makes the proxied request have both the `Transfer-Encoding` and `Content-Length` headers set, which per HTTP/1.1 specs is not valid. For this reason Sentry will be unable to read the request content and will silently discard the event …

Add new fix to suggested WSGI config

---

src/collections/_documentation/clients/java/integrations.md

as compile is deprecated
https://developer.android.com/studio/build/dependencies#dependency_configurations

swap compile for implementation in android gradle snippet

---

src/collections/_documentation/platforms/go/goroutines.md

The order of the two examples and their descriptions are not the same.
It would read better if the descriptions are provided right before each example.
Also fixing `a Goroutines` -> `a Goroutine`

fix: Change the goroutine example order

---

src/collections/_documentation/server/config.md

specifying limitations of the `system.url-prefix`

update server config documentation

---

src/collections/_documentation/data-management/event-grouping/sdk-fingerprinting.md
src/collections/_documentation/data-management/fingerprint-database-connection-example/javascript.md
src/collections/_documentation/data-management/fingerprint-rpc-example/javascript.md
src/collections/_documentation/data-management/set-fingerprint/javascript.md
src/collections/_documentation/development/sdk-dev/unified-api.md
src/collections/_documentation/enriching-error-data/configure-scope/javascript.md
src/collections/_documentation/enriching-error-data/set-extra/javascript.md
src/collections/_documentation/enriching-error-data/set-level/javascript.md
src/collections/_documentation/enriching-error-data/set-tag/javascript.md
src/collections/_documentation/enriching-error-data/set-user/javascript.md
src/collections/_documentation/enriching-error-data/tracing.md
src/collections/_documentation/enriching-error-data/with-scope/javascript.md
src/collections/_documentation/platforms/javascript/advance-settings.md
src/collections/_documentation/platforms/javascript/index.md
src/collections/_documentation/platforms/javascript/react.md
src/collections/_documentation/platforms/node/index.md
src/collections/_documentation/platforms/node/koa.md
src/collections/_documentation/workflow/set-tag/javascript.md
src/collections/_documentation/workflow/visibility.md

ref: Use es5 syntax for JS examples

---

src/collections/_documentation/server/config.md

This feature is in the process of being removed. Since sampling already
doesn't work as expected, (there is no sampling of events in Snuba) we
should probably just remove the documentation.

feat: Remove sampling docs

---

src/collections/_documentation/server/installation/docker/index.md

I think `one at a time` is idiomatic vs `one at the time`. I also clarified that `one of them` is `one cron container`.
One thing I don't know yet (at this point in the docs - I just started reading) is what `beat processes` are? Are beat processes something that run in the worker node or possibly a typo?

one at the time -> one at a time

---

src/collections/_documentation/data-management/sensitive-data.md
src/collections/_documentation/error-reporting/configuration/index.md

fix: Improve docs of send-default-pii

---

src/collections/_documentation/error-reporting/getting-started-verify/native.md
src/collections/_documentation/platforms/native/index.md

Trailing commas are not generally allowed in C and C++, and the example should in fact read:
```c
sentry_capture_event(sentry_value_new_message_event(
/*   level */ SENTRY_LEVEL_INFO,
/*  logger */ "custom",
/* message */ "It works!"
));
```

fix(native): Fix syntax error in native message example

---

src/collections/_documentation/platforms/javascript/react.md

Fixes https://github.com/getsentry/sentry-docs/pull/1231/files/1e3e1416c4cc3a3750bb7d628960cfd993d37b38#diff-b9fbbcd7dd109912114415edf628bbcd

docs: Use ES6 in React as Babel is required for JSX usage anyway

---

src/collections/_documentation/platforms/index.md

Changed Dart to Flutter and gave it a new link because users were searching specifically for Flutter.

Updated Dart link in Community SDKs

---

src/collections/_documentation/cli/releases.md

Currently if you click the "repositories configured" link [here](https://docs.sentry.io/cli/releases/#sentry-cli-commit-integration) it goes to the top of the page because the name of the anchor is incorrect.

Fix broken link from commit integration page to releases page

---

src/collections/_documentation/platforms/php/laravel.md

Latest install's of sentry default to $exception instead of $e in the error handler file.
If this update isn't done no reports are processed and php artisan commands fail.

Update Sentry 5.x Compatibility

---

src/collections/_documentation/workflow/integrations/integration-platform/webhooks.md

ref(integration-platform): Link to user payload for webhooks

---

src/collections/_documentation/clients/elixir/config.md

https://github.com/getsentry/sentry-elixir/pull/364 (which fixes https://github.com/getsentry/sentry-elixir/issues/363) brings the Elixir SDK's `before_send_event` config option in line with other, similar config options (`beforeSend` and `before_send`) in the unified SDKs, in that it now recognizes a falsy return value as a signal to drop the event. This PR adds a sentence explaining that behavior to the Elixir config docs.

feat(elixir): Add sentence about `before_send_event` returning `nil`

---

src/collections/_documentation/development/contribute/environment.md

We have a top level Brewfile in sentry, but it's wrapped in a make recipe called `install-system-pkgs` which would only really make sense if we wanted to wrap other platforms in e.g. various linux distributions. Otherwise we might as well be calling it `install-macos-pkgs` and then, we might as well just tell people to run `brew bundle`.

ref(docs): recommend running brew bundle directly

---

src/collections/_documentation/development/contribute/environment.md

I don't think `mkvirtualenv` is worth all the extra fluff required to get it working; sourcing virtualenvs directly is easy, and removes the reader from that magic (brings them closer to how virtualenvs actually work).

ref(docs): remove mkvirtualenv recommendation for simplicity

---

src/collections/_documentation/platforms/go/migration.md

Small tweak - but I had to jump from https://docs.sentry.io/platforms/go/migration to the GitHub pkg readme to figure out how to get this imported!

Adds steps for installing/importing sentry-go/http for panic recovery

---

src/collections/_documentation/platforms/javascript/sourcemaps.md

`new sourceMap.SourceMapConsumer` returns a promise in the latest version
of `source-map` so it needs to be `await`ed.

Fix example on how to check source map

---

_config.yml

This adds `blockquote`, `li`, `h2`, and `h3` to the list of index nodes in posts

feat: add additional nodes to index in results

---

src/collections/_documentation/platforms/javascript/sourcemaps.md

Updated page to emphasize uploading the minified js file and the source maps file. This method is cheaper/faster and Sentry doesn't have to go the extra step to request information.

Update Sourcemaps instructions to prioritize uploading directly to Sentry

---

src/collections/_documentation/clients/cocoa/advanced.md

https://viawriting.com/to-vs-too/

Nitpick: use correct "too"

---

LICENSE
package.json

See the public announcement about this on: https://blog.sentry.io/2019/11/06/relicensing-sentry/

meta(LICENSE): Switch to Business Source License 1.1

---

src/collections/_documentation/platforms/node/sourcemaps.md
src/collections/_documentation/platforms/node/typescript.md

The Source Maps section of the JS index page was updated to prioritize uploading source maps and minified js files directly to Sentry. This update will bring consistency between JS and Node.

Update Node source maps to emphasize uploading directly

---

src/collections/_documentation/workflow/releases.md

While the old wording was true, it wasn't the _only_ time we'd grab 20 commits.
EDIT: Since the diff is for some reason not highlighting the changed part, the change was in the first clause of the final sentence.

fix(releases): Clarify conditions for fetching 20 commits

---

src/collections/_documentation/server/sso.md

Add SSO configuration for Sentry >= 9.1
- Google Auth
- GitHub Auth

Update SSO provider for self-hosted section

---

src/collections/_documentation/clients/java/integrations.md

Documenting the manual setup of proguard rules require instructing proguard not to strip exception names.
Relates to: https://github.com/getsentry/sentry-java/issues/711
Won't be needed on `sentry-android` 2.0.0, if https://github.com/getsentry/sentry-android/pull/124 gets merged.

fix: Suggest not stripping exception names

---

src/collections/_documentation/clients/java/usage.md

People copy and paste without reading. Since we're saying this is the less preferred way of doing things, let's let this be information rather than something that actually runs if they engage in blind copy pasta.

fix(java): Make second init statement a comment

---

src/collections/_documentation/workflow/integrations/integration-platform/index.md

We don't use the term Access Token anywhere except for the Integration Platform so it makes more sense to just call them tokens (or Auth Tokens) since that's what they are.

ref(integration-platform): Use term Token or Auth Token

---

__tests__/__snapshots__/documentation.js.snap
src/collections/_documentation/api/organizations/get-organization-users.md

Same format as:
https://docs.sentry.io/api/organizations/get-organization-projects/
Note: also add docstring here?:
https://github.com/getsentry/sentry/blob/master/src/sentry/api/endpoints/organization_users.py
I plan to link to this in the docs when we publish my blog post about [this sample internal integration](https://github.com/getsentry/sentry-round-robin), which uses this endpoint to get the users who can actually be assigned to issues in a given project.

Add get-organization-users API doc page

---

src/collections/_documentation/platforms/javascript/angular.md

Some customers were skipping the installation of @sentry/browser. This emphasizes that step.

Update Angular docs

---

src/collections/_documentation/error-reporting/configuration/before-send/go.md

Exported fields in Go always start with uppercase, thus user->User and
email->Email.
Because Event contains a User value, not a pointer, event.User is never
nil. Similarly, one cannot set event.User.Email = nil, as that won't
compile.

Fix wrong case, comparison and assignment

---

src/collections/_documentation/clients/java/integrations.md

adds documentation for global tags and extras using the logback appender.
I'm not sure what the target version is likely to be however? unlikely to remain 1.7.27

doc(java): Global tags/extra with logback appender encoder

---

src/collections/_documentation/workflow/integrations/index.md

Updates https://docs.sentry.io/workflow/integrations/
- Adds a heading at the top for Integrations Platform
- ...with the first paragraph straight from https://docs.sentry.io/workflow/integrations/integration-platform/

Add link from Integrations to Integration Platform

---

src/collections/_documentation/workflow/integrations/integration-platform/index.md

Tiny update :) Added a link to:
https://docs.sentry.io/workflow/integrations/integration-platform/#internal-integrations
The link points to this blog post and the repo for its sample code:
https://blog.sentry.io/2019/11/21/customize-your-sentry-workflow-a-sample-internal-integration 
@MimiDumpling Is there an existing convention for example code links / related blog posts? For example, a note/alert box thing like the one at the top of [the Node platform docs page](https://docs.sentry.io/platforms/node/)? Or italic text? Or leave it as is?
I also wasn't sure where best to place the link... below the diagram about not needing OAuth? Or immediately below the "Internal Integrations" heading? Or at the very top of the Integration Platform page? Hrmm.

Link to Round Robin integration on Internal Integrations page

---

src/collections/_documentation/data-management/sensitive-data.md

We check both keynames _and_ values for the blacklisted strings.

fix(data scrubbing): Clarify what gets scrubbed

---

src/collections/_documentation/server/installation/index.md

Instead of ssh link, which requires a Github account and
having a public key configured

fix(self-hosted): Use https:// link to clone the onpremise repository

---

src/collections/_documentation/platforms/android/index.md

Android SDK is now in beta. Updated the note at the top of the page to reflect this change.

updated Android alpha to beta

---

src/collections/_documentation/error-reporting/getting-started-install/browser.md
src/collections/_documentation/platforms/javascript/getting-started-install/browser.md
src/collections/_documentation/platforms/javascript/index.md

Per https://app.asana.com/0/1144304343179777/1150463182095777/f, which came from me asking "Is this right?" in #discuss-sdks and Cramer saying, "That should be in the docs somewhere..."
I added it in three places:
1) The getting started page, where we tell people how to CDN.
2) The JS index page, where we tell people how to CDN.
3) An embed we don't seem to use, related to the JS index page.
Questions:
1) Does it belong in all of these places?
2) I don't super love how it's worded (it's adapted from an answer to a support ticket, and I fear it still sounds too conversational), so are there improvements I could make?
3) On the JS index page, I debated whether it should go in the Lazy Loading section instead, since it's kinnnnnnda related? But in the end that's not exactly what it is, and …

feat(JS CDN): Add async/defer note

---

src/collections/_documentation/enriching-error-data/user-feedback-example/laravel.md
src/collections/_documentation/platforms/php/laravel.md

This updates a few things in the Laravel documentation:
/cc @HazAT (& @Jean85 & @ste93cry for textual / PHP SDK bits)

Update Laravel docs

---

src/collections/_documentation/error-reporting/configuration/index.md
src/collections/_documentation/platforms/javascript/index.md

Fixes https://app.asana.com/0/1144304343179777/1144580065042336
I didn't add anything about `SENTRY_DSN` since typically that is just a hardcoded static value, not something that needs to be configured through webpack.

feat(webpack): Add notes on configuring SENTRY_RELEASE

---

src/collections/_documentation/workflow/notifications/index.md

Both Slack and PagerDuty were previous under the Legacy Integrations section which doesn't exactly make sense since `(via "Service" as any individual integration)` is inaccurate.

separate-legacy-from-global-alert-integrations

---

src/collections/_documentation/data-management/sensitive-data.md

Sensitive Data page was missing a code snippet and additional instructions regarding `before-send`. Updated to include them.

Update Sensitive Data page with instructions for before-send (SDK)

---

src/collections/_documentation/platforms/go/index.md

The warning block renders below the code example, but refers to _the example below_, when there isn't any. So rather than moving the block above the code example, I just changed the word **below** to **above**.
Happy Holidays 🎅🎊🎄

going from above to below

---

src/collections/_documentation/clients/java/config.md

The aforementioned paragraph is trying to link to #configuration-methods. See https://docs.sentry.io/clients/java/config/#setting-the-dsn

Fix broken linking in config.md

---

src/collections/_documentation/platforms/node/express.md

The default value for flushTimeout is not 2000, it is undefined: 
https://github.com/getsentry/sentry-javascript/blob/645ff532941d9a23bb6531c6305e99544b356502/packages/node/src/handlers.ts#L293

Update express.md, flushTimeout default is not 2000

---

src/collections/_documentation/server/plugins.md

With plugin repos being archived, that information needed to be propagated here Our Asana plugin has instructions for on-prem users so they should be added here. I did not add instructions the existing instructions for BitBucket and Jira because those are deprecated and have replacements.

docs(plugins): update plugin listing and add Asana instructions

---

__tests__/__snapshots__/documentation.js.snap
src/collections/_documentation/workflow/notifications/index.md
src/webhook-plugin.md

**Context:**
We don't document the Webhook Plugin anymore (that I could find) let alone the payload that gets sent to the configured urls. It's unclear to me if it was intentional because it is a Legacy Integration and we would prefer to push people to use the Integration Platform for webhooks. However people still write in asking about this, and while we can point to the source code, it would be nice for people to discover it through the docs. 
**Changes:**
* Link to the Integration Platform in the Integrations with Notifications section to notify people of that option
* Add Webhooks as an option in the Legacy Integration section
> ![Screen Shot 2019-12-19 at 10 18 31 AM](https://user-images.githubusercontent.com/15368179/71198696-3972c000-2249-11ea-8fc9-299ea768b31b.png)
* Add Webhook …

Add webhook plugin page and payload documentation

---

Dockerfile.apidocs

`sentry:apidocs` needs libxmlsec1 for pip to build the wheel for xmlsec.
Should fix `bin/update-api-docs` (`docker run --rm sentry:apidocs`).

fix(build): xmlsec wheel requires libxmlsec1 deb package

---

src/collections/_documentation/workflow/integrations/index.md

Visually separate the Sentry created integrations from the ones created by a 3rd party to make it clear which ones we support and maintain.
How it looks currently:
How it'll look:

Separate integrations by maintainer

---

src/collections/_documentation/cli/index.md
src/collections/_documentation/cli/installation.md

Hi there! I created a [Scoop](https://scoop.sh) manifest for easy installation of sentry-cli on Windows, and it's PRd over at ScoopInstaller/Main#738. It would be great to see this documented once it's live!

Add installation instructions for CLI via Scoop

---

src/collections/_documentation/accounts/membership.md

- Update for the docs around open membership. Members can now join, leave, and *add other members to* teams if open membership is enabled.
- Removes the table for member roles and replaces it with a more general explanation of each role. I found the current table confusing, since roles can have different permissions depending on open/closed membership and whether an Admin is already in a team or not.
cc/ @ceorourke @mbauer404 Wondering what you think about removing the table. Okay with adding it back if you think it's helpful

ref: Update and clarify member roles

---

nginx.conf

This adds a keepalive timeout of 3600s to the docs nginx config to help us out over in ops-land.

meta: add keepalive timeout of 3600s to nginx config

---

Dockerfile

This updates our jekyll-base images to use 2020.01.23

meta: update jekyll-base to 2020.01.23

---

src/_assets/css/_includes/type.scss

fix(docs): Word joiner characters have width in Safari. Enforce 0 width on elements with .no-break

---

src/collections/_documentation/enriching-error-data/user-feedback-example/aspnetcore.md

The documentation should avoid using hard-coded DSNs in places where configuration settings are available as a single source of truth.

Use Dependency Injection for User Feedback on ASP.NET Core

---

src/collections/_documentation/platforms/go/migration.md

The called method SetExtras() can only be called on the scope, not as previously noted on the package level

Use SetExtras() on scope instead of package

---

src/collections/_documentation/clients/react-native/expo.md

Clarifying as a result of https://github.com/expo/sentry-expo/issues/87.

fix(expo): Note that `sentry-expo` doesn't catch native crashes

---

src/collections/_documentation/workflow/releases.md

I fixed this on the cli page in https://github.com/getsentry/sentry-docs/pull/1451 but forgot to update this here as well.

(fix): Escape backslash in workflow release docs

---

src/collections/_documentation/workflow/dashboards.md

Dashboards was dividing Discover v2 and Discover. This PR fixes that.

Changed side bar order for Dashboards

---

src/collections/_documentation/cli/configuration.md

The configuration values in `.sentryclirc` file and in environment
variables have been added to the configuration documentation so
not only "origin" is usable as vcs remote.
This update is related to getsentry/sentry-cli#637, and it should be merged only once the pull request is accepted.

Add configuration about vcs_remote

---

src/collections/_documentation/development/sdk-dev/features.md

Depending on the platform, there might not be a concept of a single
background thread. Therefore, prefer the more general "a background
thread" instead of the specific "the background thread".

Generalize statement the -> a

---

src/collections/_documentation/accounts/pricing.md

Customers frequently write into Support about their invoices or receipts. This addition to the Pricing FAQ will address those questions.

added section in FAQ about invoices and receipts

---

src/collections/_documentation/workflow/discover2/index.md

Updated the alert box at the top of Discover v2 and linked to Discover v1.

added link to Discover v1

---

src/collections/_documentation/workflow/search.md

- Move the tags syntax out of Advanced (it's not an advanced feature)
- Don't encourage using reserved keywords as tags (you may wish to... -> if you do..)
- organization filter list -> organization saved search

ref(search): Clarify search syntax

---

src/collections/_documentation/error-reporting/getting-started-install/browser.md
src/collections/_documentation/platforms/javascript/getting-started-install/browser.md
src/collections/_documentation/platforms/javascript/index.md

Code formatting doesn't appear to work in alert box titles, so remove this formatting.
**Before**:
**After**:

(fix) Reformat defer note in JS docs

---

src/collections/_documentation/enriching-error-data/breadcrumbs.md

Closes https://github.com/getsentry/sentry-javascript/pull/2415
The only thing that has to be fixed is displaying `boolean` values, which has been already reported few months ago, and there's open issue here: https://github.com/getsentry/sentry/issues/16637

docs: Remove str->str contraint from breadcrumb.data description

---

src/_data/platforms.yml

Format the config options correctly 
cc @bruno-garcia

fix: ASP.NET Core use PascalCase

---

src/collections/_documentation/development/contribute/environment.md

So in one fell swoop, brew removed python@2 and messed up their nvm, prompting me to switch our devenv documentation over to pyenv + volta ASAP.
I've deduced these new steps by the process of helping some people stand up a sentry dev environment on Mojave, from scratch. They should be relatively robust, but I have yet to truly follow these steps from start to end on a machine from scratch.
This requires and is blocked by the following changes in sentry: https://github.com/getsentry/sentry/pull/16954
Some notes:
- Unfortunately, Volta can't currently automagically install from what's pinned in `package.json`, so the node version's been hardcoded for now.

feat: new sentry devenv docs

---

__tests__/__snapshots__/documentation.js.snap
src/collections/_documentation/clients/java/integrations.md
src/collections/_documentation/clients/java/usage.md
src/collections/_documentation/platforms/android/index.md
src/collections/_documentation/platforms/android/migrate.md

Our Android SDK had some updates that needed documenting for the GA release. Updates include new content for the Releases section and a new page for Migration.

Update Android docs for GA release

---

src/collections/_documentation/platforms/index.md

@bruno-garcia created some lovely docs about Flutter and I thought it appropriate to link to them from the Platforms index page.

added link to Sentry's page about Flutter

---

src/collections/_documentation/development/sdk-dev/event-payloads/contexts.md

It's confusing to say it's related to `Request` since [the `Request` interface hangs off of the event](https://docs.sentry.io/development/sdk-dev/event-payloads/request/) directly and is not part of the context.
Happy to rephrase it, just would like not to say `Request` here.

fix: Don't mention Request

---

src/collections/_documentation/accounts/saml2.md
src/collections/_documentation/accounts/sso.md

Hi @MimiDumpling!!
This is my first PR on docs. I found that `.../SLS/...` should be in small letters (see this [line of code in getsentry/sentry](https://github.com/getsentry/sentry/blob/f7febb2015585d4f1d0a9070d7ffef5c6ffa8541/src/sentry/web/urls.py#L157)). I don't think this affects anything but it's a small change and I'm in favor of accuracy in docs.

fix(saml2): Fix typo in URL for SAML endpoint

---

src/collections/_documentation/platforms/react-native/manual-setup.md

`@sentry-react-native` to `@sentry_react-native`

Fixing incorrect package name

---

src/collections/_documentation/support/index.md

Add note about the Help Center if the answer can't be found in our docs. I also updated the Paid Support section to correctly point to where you can contact support.
Open to feedback on if this should actually be an alert "Note", wording, etc.

ref: Add note about Help Center

---

src/collections/_documentation/error-reporting/configuration/filtering.md

Hopefully this makes it clear to the reader that before_send can be used to prevent error spam.
Related issue: https://github.com/getsentry/sentry-python/issues/149
Thanks to @untitaker for the tip

update before send doc with error spam prevention

---

src/collections/_documentation/error-reporting/getting-started-config/go.md
src/collections/_documentation/error-reporting/getting-started-verify/browser.md
src/collections/_documentation/error-reporting/getting-started-verify/cordova.md
src/collections/_documentation/error-reporting/getting-started-verify/csharp.md
src/collections/_documentation/error-reporting/getting-started-verify/electron.md
src/collections/_documentation/error-reporting/getting-started-verify/go.md
src/collections/_documentation/error-reporting/getting-started-verify/node.md
src/collections/_documentation/error-reporting/getting-started-verify/php.md
src/collections/_documentation/error-reporting/getting-started-verify/python.md
src/collections/_documentation/error-reporting/getting-started-verify/rust.md
src/collections/_documentation/error-reporting/quickstart.md

Specific changes to the Go SDK and general changes to all platforms.

Revise Getting Started section

---

src/collections/_documentation/error-reporting/getting-started-verify/browser.md
src/collections/_documentation/error-reporting/getting-started-verify/cordova.md
src/collections/_documentation/error-reporting/getting-started-verify/electron.md
src/collections/_documentation/error-reporting/getting-started-verify/node.md
src/collections/_documentation/error-reporting/getting-started-verify/php.md
src/collections/_documentation/error-reporting/getting-started-verify/python.md
src/collections/_documentation/error-reporting/getting-started-verify/rust.md

Accidentally added through GitHub code change suggestions during code
review (in #1513).

fix: Remove unintentional trailing whitespace

---

src/collections/_documentation/error-reporting/configuration/drain-example/go.md
src/collections/_documentation/error-reporting/configuration/drain-example/javascript.md
src/collections/_documentation/error-reporting/configuration/drain-example/native.md
src/collections/_documentation/error-reporting/configuration/drain-example/python.md
src/collections/_documentation/error-reporting/configuration/drain-example/rust.md
src/collections/_documentation/error-reporting/configuration/draining.md

The original motivation was a continuation to getsentry/sentry-go#106, to clarify the usage of `Flush` in the Go SDK.
I went ahead and revised the contents for other languages as well.

Revise Shutdown and Draining section

---

src/collections/_documentation/error-reporting/quickstart.md

Testing the Git workflow with a minor grammar and typo fix in the quickstart.md file.

Fix typo in Getting Started

---

src/collections/_documentation/workflow/integrations/global-integrations.md
src/collections/_documentation/workflow/integrations/index.md

This PR adds docs for Bitbucket server. It's basically a combination of the Jira server docs for installation (replacing Jira with Bitbucket) and the Bitbucket for the features. The one difference is that the Bitbucket server integration cannot be used for issue management so that section from Bitbucket has been removed. I do realize that putting it in the `Issue Management` section when it doesn't actually do issues doesn't make sense but that's because we don't have a separate section for `Source Code Management` where this really belongs. We probably should do that in a future PR.
Some screenshots:
Another:

docs(integrations): adds bitbucket server docs

---

src/collections/_documentation/platforms/native/index.md

Native team recently updated the index page (https://github.com/getsentry/sentry-docs/pull/1517). This PR fixes a couple grammatical errors.

Update Native index page

---

src/_data/platforms.yml

I hope this is correct, goal should be that the onboarding wizard uses the new android docs.

chore: Update android wizard link

---

src/collections/_documentation/platforms/javascript/index.md
src/collections/_documentation/platforms/node/default-integrations.md

https://github.com/getsentry/sentry-javascript/issues/2452

docs: Add note regarding blacklist/whitelist and message events

---

src/collections/_documentation/clients/ruby/config.md

Fix typo on Configuration page

---

src/collections/_documentation/data-management/event-grouping/server-side-fingerprinting.md

I found myself constantly thinking that Server Side Fingerprinting was only available for:
```
- `type`: matches on an exception type
- `value`: matches on an exception value
- `message`: matches on a log message
```
I always forgot to go check in:
```
The matchers are the same as for grouping enhancements (https://docs.sentry.io/data-management/event-grouping/grouping-enhancements/#rules) 
but some extra ones are available:
```
**I didn't like how this was phrased, "same as x but here are extras y"** and upon leaving server side fingerprinting, it's overwhelming the amount of info on Custom Grouping Enhancements page. That's a separate area of documentation.
However **I do like** that the other types are listed under Examples:
https://docs.sentry.io/data-management/event-grouping/server-s …

List matchers from grouping enhancements

---

src/collections/_documentation/workflow/integrations/integration-platform/webhooks-verifying-signature/node.md
src/collections/_documentation/workflow/integrations/integration-platform/webhooks-verifying-signature/python.md
src/collections/_documentation/workflow/integrations/integration-platform/webhooks.md

Adds a language dropdown with code snippet for Node as well as Python to the webhooks page:
https://docs.sentry.io/workflow/integrations/integration-platform/webhooks/#verifying-the-signature
Do we want to add other language examples too? :)

Add language dropdown for verifying webhook signature

---

src/collections/_documentation/performance/distributed-tracing.md

This update makes the statement of value more clear. Thanks for the feedback, @benvinegar 
Before:
After:

Update: Tracing statement of value

---

src/collections/_documentation/performance/distributed-tracing.md

Distributed Tracing doc was missing a code example for sampling. This adds the code example.
Before:
After:

Update: Add JS code example for sampling

---

src/collections/_documentation/platforms/javascript/index.md

See the "Level" link in https://github.com/getsentry/sentry-docs/blob/f0a839fb0e1d884bcee0d83fccd4632495e6ad7e/src/_includes/platforms/event-contexts.md

Fix link to "Setting the Level" section in JS docs

---

src/collections/_documentation/data-management/advanced-datascrubbing.md

Also remove some useless value types that I might want to remove: booleans are never stripped, ever, and the event value type does not work at the moment.

ref(pii): Better explanation of selectors

---

nginx.conf
src/collections/_documentation/error-reporting/quickstart.md

The Error Tracing page was originally called Tracing. This fix redirects Tracing links to Error Tracing.

created redirect for error tracing

---

src/collections/_documentation/workflow/alerts-notifications/alerts.md
src/collections/_documentation/workflow/alerts-notifications/notifications.md

A few images were too big and now they're more consistent with the other screenshots.
**BEFORE:**
**AFTER**:

Resized images for Alerts and Notifications

---

src/collections/_documentation/platforms/react-native/codepush.md

My understanding is if the --dist doesn't get explicitly declared then it'll just be None which can present problems with the deminification of source maps
see merge where this was added: https://github.com/getsentry/sentry-cli/commit/ee81633876c1f19b27724dcb70cadb88ff05e7e2

Added --dist argument

---

src/collections/_documentation/workflow/integrations/integration-platform/ui-components.md

This PR adds more information about issue linking UI components:
- Adds information about the new `depends_on` field
- Adds missing information about request and response data for creating/linking issues
- Adds missing information about request information for retrieving options for a select field

docs(ecosystem): adds more docs on issue linking UI components

---

src/collections/_documentation/development/sdk-dev/event-payloads/breadcrumbs.md
src/collections/_documentation/development/sdk-dev/event-payloads/exception.md
src/collections/_documentation/development/sdk-dev/event-payloads/index.md
src/collections/_documentation/development/sdk-dev/event-payloads/threads.md

The server accepts several formats and normalizes event payloads to use
the values list form.
To reduce ambiguity, focus the documentation on the canonical form.

Clarify canonical format used for Breadcrumbs, Exceptions and Threads

---

src/collections/_documentation/data-management/advanced-datascrubbing.md

* Make writing more verbose to steer users into the right direction in settings. A tester expected Data Privacy Rules to be the sidebar tab's name (after skimming over the first section)
* Use new aliases from https://github.com/getsentry/relay/pull/532
* Bring back replace, see https://github.com/getsentry/relay/pull/542
Note: Do not deploy until relay has been released and bumped

fix: Update datascrubbers documentation based on feedback

---

src/collections/_documentation/development/sdk-dev/event-payloads/breadcrumbs.md

Nothing is strictly required, but empty breadcrumbs are not useful.
This is extracted from the conversation at https://github.com/getsentry/sentry-docs/pull/1554/files#r397478177.

Clarify requirements of Breadcrumbs payload

---

src/collections/_documentation/platforms/javascript/sentry-testkit.md

Currently the typed result of `sentryTestKit()` is the following:
```typescript
export interface TestkitResult {
testkit: Testkit;
sentryTransport: {
new (options: TransportOptions): Transport;
};
initNetworkInterceptor<T>(dsn: string, initCallback: (baseUrl: string, handleRequestBody: (requestBody: { [key: string]: any }) => void) => T): T;
localServer: LocalServer
}
```
Notice that `testkit` is all lower case.  
In the example above this is imported and used with inconsistent naming.  This is simply a fix for that.

fix: capitalization mismatch for `testKit` vs `testkit`

---

src/collections/_documentation/development/sdk-dev/event-payloads/breadcrumbs.md
src/collections/_documentation/development/sdk-dev/event-payloads/index.md

Fix examples that had numeric value as milliseconds instead of seconds (server only accepts seconds).
Update examples to use RFC3339 as a preferred format for readability.
Related to https://github.com/getsentry/sentry-go/issues/190.

fix: Clarify accepted timestamp formats

---

src/collections/_documentation/performance/distributed-tracing.md

Started out just fixing one typo, ended up proofreading the whole thing. 🤦🏻‍♀️
Things which happened here:
- Fix a handful of tiny typos
- Fix a few places where `each` was treated as a plural
- Fix JS code snippets so comments fit in the default viewport (no scrolling necessary) and so that indents are 2 spaces (the JS standard) rather than 4 spaces (the standard for Python)
- Make places with identical content (between node and browser) actually have identical content. In the long run might want to use includes, but there may be some bigger changes to the section anyway (given new integrations being built this quarter by the Client Infra/Web team), so I figured I'd wait until after that happens.
- General smoothing of language

ref(APM): Fix typos, minor wordsmithing

---

src/collections/_documentation/performance/discover/index.md
src/collections/_documentation/performance/discover/query-builder.md

Updating content based on recent UI changes. Circular Sentry avatars indicate pre-built queries. User avatars indicate saved queries. The user who creates a saved query will automatically have their avatar attached to the saved query.

Update Discover docs with new avatar details

---

src/collections/_documentation/workflow/alerts-notifications/index.md

A few changes to help distinguish between Issue Alerts and Metric Alerts.
**BEFORE**:
**AFTER**:

Update Alerts & Notifications

---

src/collections/_documentation/development/sdk-dev/event-payloads/sdk.md

- Update first sentence to match other interfaces
- Add missing 'Attributes' section header
- Clarify version format
- Clarify package format
- Update example to contain valid JSON
- Fix typo in example SDK name 'javscript' => 'javascript'

sdk-dev: Improve SDK Interface docs

---

nginx.conf

In the current version the link to the https://docs.sentry.io/workflow/releases doesnt work.
https://docs.sentry.io/workflow/releases/index works so I hope that change of the redirection will help.

fix redirection to releases

---

src/collections/_documentation/platforms/cocoa/index.md

`sessionTrackingIntervalMillis` is used as an override. 30000 is already the default and causes noise in the doc/configuration

fix: Remove unecessary config

---

src/collections/_documentation/development/sdk-dev/event-payloads/sdk.md

This is a follow up from https://github.com/getsentry/sentry-docs/pull/1604#discussion_r406766944

sdk-dev: Clarify naming of SDKs

---

src/collections/_documentation/development/sdk-dev/event-payloads/sdk.md

Some SDKs today already send a complete list of enabled SDKs, while the
docs suggested otherwise.
Updating the suggestion to have SDKs always send a full list, because
otherwise it is harder to provide insights in Sentry as we'd need to
maintain a mapping of default integrations for each SDK for each
released version.

sdk-dev: Document sending of default integrations

---

src/collections/_documentation/error-reporting/configuration/filtering.md

Highlighting `event` because it's also an argument, same as `hint`.

Highlight event argument for filtering documentation

---

src/collections/_documentation/enriching-error-data/set-environment/node.md
src/collections/_documentation/error-reporting/getting-started-config/node.md
src/collections/_documentation/platforms/javascript/angular.md
src/collections/_documentation/platforms/javascript/ember.md
src/collections/_documentation/platforms/javascript/getting-started-dsn/node.md
src/collections/_documentation/platforms/javascript/index.md
src/collections/_documentation/platforms/javascript/vue.md
src/collections/_documentation/platforms/node/connect.md
src/collections/_documentation/platforms/node/express.md
src/collections/_documentation/platforms/node/index.md
src/collections/_documentation/platforms/node/koa.md

Some people may get confused without providing both ways. See: https://github.com/getsentry/sentry-javascript/issues/1647
I verified that frameworks are imported correctly as well:
Also changed how integrations are imported to make it more obvious that they are completely independent from each other.

node: Unify imports syntax across all pages

---

nginx.conf

Removing a 302 from nginx.conf because it's unnecessary and incorrect.

Fix: Remove unnecessary redirect

---

src/collections/_documentation/performance/distributed-tracing.md

Sample rates in code examples needed an update to highlight the percentage of transactions captured. In addition, the Node example needed correction.

Update distributed tracing sample rates

---

src/collections/_documentation/performance/distributed-tracing.md

A few examples of `tracesSampleRate` are still set to 1. This PR sets them to .25

updated tracesSampleRate to .25

---

src/ip-ranges.md

Our IP Ranges page only applies to the SaaS product -- not on-prem or single tenant. Added the alert box to give readers the correct expectations.

Added alert box to IP Ranges page

---

src/collections/_documentation/development/sdk-dev/event-payloads/debugmeta.md
src/collections/_documentation/enriching-error-data/additional-data.md
src/collections/_documentation/workflow/releases/health.md

This was originally deprecated and thus undocumented. However, to render proper apple crash reports and addresses that can be fed into `addr2line`, it is useful to retain the original load address as `image_vmaddr`. 
Note that the description for the three platforms varies slightly.

feat(protocol): Document image_vmaddr

---

src/collections/_documentation/development/sdk-dev/features.md
src/collections/_documentation/development/sdk-dev/overview.md
src/collections/_documentation/development/sdk-dev/unified-api.md

This still uses `may` a few times.
I would ideally like to have hard guarantees around `configure_scope` and `add_breadcrumb`, right now it would be up to the discretion of the SDK.

docs: Clarify disabled SDK, and SDK Event Processing

---

src/collections/_documentation/platforms/cocoa/index.md

The recent change to the `.craft.yml` makes it so that we also publish the beta version to the registry
https://github.com/getsentry/sentry-cocoa/commit/bbcefde128cdb0d4718dfe2b40b7f2805f50dc52#diff-5d0582c415804fb1a47d79260b3faffb
This change updates the docs so we no longer have to manually bump the version here.
Please only merge this after the next publish with `craft` in `sentry-cocoa`

chore: No more manual version bumps sentry-cocoa

---

src/collections/_documentation/platforms/javascript/index.md

Switched the automatic and manual sections on the JS page.
**BEFORE**:
**AFTER**:

Update JavaScript capture errors sections

---

src/collections/_documentation/error-reporting/configuration/drain-example/javascript.md

process.exit() created confusion with browser javascript and NodeJS scripts

removed process.exit() from normal javascript

---

src/collections/_documentation/error-reporting/configuration/drain-example/node.md

Created a NodeJS help doc, because it confuses with process.exit() statement.

created a node.md for nodejs

---

Gemfile.lock

revert the gemfile.lock change from: https://github.com/getsentry/sentry-docs/pull/1646

fix: change back bundler version

---

src/collections/_documentation/platforms/react-native/sourcemaps.md

Customer wrote into Support about confusion over `setDist`. This PR gives a code example of how to use `setDist`.
Before:
After:

added example code to React Native for setDist

---

src/_assets/css/_includes/bootstrap-overrides.scss

As @rhcarvalho correctly points out [here](https://github.com/getsentry/sentry-docs/pull/1667#discussion_r422048896), actually headings have many advantages over text made to look like a heading by bolding it and putting it on its own line.
In markdown, it's the difference between `#### Dogs Rule` and `**Dogs Rule**`. In HTML it means anchor links, consistent styling, and better accessibility (vs. lack of all of those things).
So, a clear win for headings, right? It would be, except that with our current CSS, it's next to impossible to tell an `h4` (`#### Dogs Rule`) from an `h3` (`### Dogs Rule`), because the difference is only a 4% reduction in size. Since using `h4`s breaks the document's visual hierarchy, folks in many cases choose to use the fake heading in spite of its drawbacks, …

ref(css): Shrink `h4` to differentiate it from `h3` 

---

src/collections/_documentation/performance/discover/index.md

Discover needs content about how grouping results work in Discover.
**Before**:
**After**:

Updated Discover grouping content

---

src/collections/_documentation/clients/react-native/manual-setup.md
src/collections/_documentation/platforms/react-native/manual-setup.md

Add docs for ppl to add `EXTRA_PACKAGER_ARGS` to Xcode build script to make sure source maps are not bundled with the app.

fix: React native docs

---

__tests__/__snapshots__/documentation.js.snap
src/_data/platforms.yml
src/collections/_documentation/platforms/python/index.md
src/collections/_documentation/platforms/python/migration.md

This is https://forum.sentry.io/t/switching-to-sentry-python/4733 with some touch-ups. Paging cramer on this one because he's the other person who underwent a migration at sentry (for zeus)

ref: Add simple migration guide for Python

---

src/collections/_documentation/platforms/react-native/index.md

Added a yarn remove step for when upgrading in react native from `react-native-sentry` to `@sentry/react-native` instead of having the user just remove from the package.json.

ref: Added a yarn remove step to react-native upgrade docs

---

src/collections/_documentation/platforms/cocoa/integrations/objc.md
src/collections/_documentation/platforms/cocoa/integrations/swift.md
src/collections/_documentation/platforms/cocoa/usage.md

The SentryUIKitMemoryWarningIntegration is obsolete since Cocoa 5.0.0 since
we have breadcrumbs now. Therefore we remove this integration from the docs.
The integration itself is going to be removed with Cocoa 5.1.0.

fix(cocoa): Remove memory warning integration

---

src/_includes/sidebar.html

Discussion: https://sentry.slack.com/archives/C8H0BQRDJ/p1589612596369400
Don't know any frontend at all, but managed to fix it by removing this "active" thing, whatever that is. Also, I added a bogus href so `Resources` looks like every other section header in the sidebar. It was basically invisible before, which was inconsistent.
Also, the live reloader didn't work for me @dcramer. Another good reason to move the build system + framework to something better.

fix: weird visual glitch with Resources autoclicking

---

__tests__/__snapshots__/documentation.js.snap
src/collections/_documentation/workflow/releases/release-automation/bitbucket-pipelines/index.md
src/collections/_documentation/workflow/releases/release-automation/index.md
src/collections/_documentation/workflow/releases/release-automation/jenkins/index.md
src/collections/_documentation/workflow/releases/release-automation/netlify/index.md

Add Sentry Netlify build plugin to release automation docs.

Add Sentry Netlify build plugin to release automation docs

---

src/collections/_documentation/workflow/releases/set-release/rust.md

I fixed up the rust example as it requires `Option<String>`. I also added the DSN in the example, as it took me a while to realize how this works with the `sentry::ClientOptions` passed in `init(`.

fixed release example for rust

---

src/collections/_documentation/platforms/javascript/index.md

The example for fingerprints to [split up a group into more groups](https://docs.sentry.io/platforms/javascript/#example-split-up-a-group-into-more-groups-groups-are-too-big) is missing the `{{default}}` keyword. It is missing from the page source, as well, so I assume it is due to server-side processing trying to replace the double curly braces with a variable.
```javascript
scope.setFingerprint(['', path]);
```
...should be...
```javascript
scope.setFingerprint(['{{default}}', path]);
```
NOTE: I did not make a change to the last line, nor is it necessary, and I'm not sure why Github is showing a change. The addition it shows is something that already exists in the docs, so I don't know why GIthub shows it as an addition when viewing the "Preview."

"default" does not show up for fingerprint example

---

src/collections/_documentation/accounts/sso.md

Add information about session length to SSO docs. A customer wrote in asking about session length and whether it could be customized, so hopefully this'll help folks in the future self-service.

docs(api): Add session length info

---

src/collections/_documentation/platforms/react-native/index.md

Document the _Release Health_ feature for React Native users.
Please note I've removed the `Sentry.setRelease/setDist` docs since cannot affect the release used by the native SDKs doing release health. Values should be taken in during initialization. We might deprecate the methods in the future if possible.

react-native release health

---

src/collections/_documentation/platforms/javascript/index.md

ref: https://github.com/getsentry/sentry-javascript/pull/2627
ref: https://app.asana.com/0/1169125731075107/1178479294693625

Explicit Scope for JS SDKs

---

src/collections/_documentation/platforms/javascript/sourcemaps.md

Add something to the docs about how to get source maps to work with docker deployed environment.

feat(sourcemaps): Mention volume sharing across web & workers

---

src/collections/_documentation/platforms/javascript/index.md

In the js SDK, the `Sentry.setContext` method's second parameter takes in
an object only and not a string as per http://getsentry.github.io/sentry-javascript/classes/hub.scope.html#setcontext.
Users will attempt to pass a string:
https://github.com/getsentry/sentry-react-native/issues/694#issuecomment-640069758
Attempting to pass a string in the second parameter will encounter an error when processing the event:

fix: Fix bad example for setContext in js SDK

---

src/collections/_documentation/data-management/advanced-datascrubbing.md

Data Scrubbing is mostly equivalent and we are about to rename the project settings page to Security & Privacy to 1) be consistent with org options 2) encompass the stuff that is sort of related but not really data scrubbing
See also https://github.com/getsentry/sentry/pull/19215

ref(data-scrubbing): Remove all mentions of data privacy

---

nginx.conf

This PR redirects these broken links:
https://docs.sentry.io/workflow/integrations/slack/
https://docs.sentry.io/workflow/integrations/jira/

Fix: redirects for Slack and Jira

---

src/collections/_documentation/platforms/react-native/index.md

Fix: getsentry/sentry-react-native/issues/841

fix: add extra documentation for RN about configureondemand Gradle's feature

---

src/collections/_documentation/performance/distributed-tracing.md

Req: https://github.com/getsentry/sentry-javascript/pull/2675

docs: Vue tracing integration

---

src/collections/_documentation/performance/performance-metrics.md

Performance Metrics now has an explanation of `failure_rate()`.

Add: section about failure rate

---

src/collections/_documentation/platforms/python/django.md

I don't know if you'd like this changed, but I click the `Help us fix it` anyway :)
If Django 2.0 is still the major version being used, feel free to close this PR

Change link from Django 2.0 docs to Django 3.0

---

src/collections/_documentation/performance/distributed-tracing.md

We added a new `beforeNavigation` option to the `Tracing` integration, so this PR documents that.
See https://github.com/getsentry/sentry-javascript/pull/2691 for more details.

feat(tracing): Add section about beforeNavigation

---

src/collections/_documentation/workflow/alerts-notifications/alerts.md

Alert page had strange behavior with some text. This PR fixes them. Looks like leftover merge conflict resolution.

Fix: text in alert page

---

src/collections/_documentation/performance-monitoring/configuration/javascript.md

Add note about how we create `pageload`/`navigation` transactions:
> By default, the `pageload` and `navigation` transactions set a transaction name using `window.location.pathname`.
Also adjust the `beforeNavigate` example to be a bit more clear.
The other changes are just some formatting I did.

ref(tracing): Add note about location.pathname usage

---

src/collections/_documentation/performance-monitoring/configuration/python.md

The installation step was using the Node APM package. This now shows how to install via pip.

Update python installation step

---

src/collections/_documentation/platforms/javascript/getting-started-dsn/react.md
src/collections/_documentation/platforms/javascript/getting-started-install/react.md
src/collections/_documentation/platforms/javascript/react.md

This PR adds documentation for `@sentry/react`, our new React package.
This package also includes `Profiler` component, meant to be used as part of our tracing/am integrations, but I will open a separate PR for that after this.
See preview here:

feat: document new React usage

---

src/collections/_documentation/platforms/android/index.md

Fix https://github.com/getsentry/sentry-android/issues/472

introduce androidx support on the android docs

---

src/collections/_documentation/performance-monitoring/configuration/koa.md

Includes domain creation for better breadcrumbs handling and creation of transaction per request

New Koa configuration

---

src/collections/_documentation/performance-monitoring/configuration/react.md
src/collections/_documentation/performance-monitoring/setup.md

This PR adds performance docs for React. It walks through using the `@sentry/react` package and the Profiler to add React related spans to transactions.

feat: Add performance docs for react

---

src/collections/_documentation/workflow/alerts-notifications/alerts.md

The alerts page had a few broken links. This PR repairs the links.

Fix: Links in Alerts page

---

src/collections/_documentation/workflow/releases/index.md

Inform users of new functionality and flags available in the sentry-cli for releases.

feat: Update Releases docs with new sentry-cli set-commits behaviour

---

src/collections/_documentation/cli/releases.md

Inform users of new functionality and flags available in the sentry-cli for releases.
It is pretty much the same as https://github.com/getsentry/sentry-docs/pull/1813

feat: Update Release Management docs with new sentry-cli set-commits behaviour

---

README.md
gatsby/gatsby-config.js
gatsby/gatsby-node.js
gatsby/package.json
gatsby/src/components/alert.js
gatsby/src/components/codeBlock.js
gatsby/src/components/content.js
gatsby/src/components/jsCdnTag.js
gatsby/src/components/paramTable.js
gatsby/src/components/sidebar.js
gatsby/src/css/_includes/alert.scss
gatsby/yarn.lock

- Fix whitespace when markdown is used with alerts
- Add JsCdnTag for embedding version-based sentry-javascript script tag
- Add ParamTable component for rendering parameterized tables
- Ignore gatsby migrated files (via frontmatter) in gatsby sidebar generation
- Re-add support for prefix in code blocks (unused)

Additional Gatsby functionality

---

src/collections/_documentation/platforms/native/index.md

* Removes on-promise warning, as this is now supported.
* Clarify and update transport and backend sections.
* Bring code up-to-date.

docs: Update Native Documentation

---

src/collections/_documentation/platforms/php/index.md

The PHP option `excluded_app_paths` changed to `in_app_exclude`.

Fix: PHP option `excluded_app_paths` to `in_app_exclude`

---

src/collections/_documentation/clients/react-native/cocoapods.md
src/collections/_documentation/clients/react-native/codepush.md
src/collections/_documentation/clients/react-native/config.md
src/collections/_documentation/clients/react-native/expo.md
src/collections/_documentation/clients/react-native/index.md
src/collections/_documentation/clients/react-native/manual-setup.md
src/collections/_documentation/clients/react-native/ram-bundles.md
src/collections/_documentation/clients/react-native/sourcemaps.md

I couldn't figure out how to add the layout header we have everywhere else so I added it manually.
Fixes https://github.com/getsentry/sentry-docs/issues/1744

fix: Add note about depreacted react-native

---

src/collections/_documentation/performance-monitoring/configuration/koa.md

This PR formats the koa examples with prettier, and also adds a `span.sampled` field when continuing from trace header.

ref(tracing): Prettier koa code + add sampled

---

src/collections/_documentation/performance-monitoring/configuration/node.md

Add an example on how to configure the scope with transactions to be able to add trace context information for other Sentry events.

feat(apm): Add information on configuring scope with transaction for Node.js

---

src/collections/_documentation/performance-monitoring/getting-started.md
src/collections/_documentation/performance-monitoring/performance/transaction-summary.md

Removed duplicated section in Transaction Summary and updated first two sentences in Getting Started.

Remove: duplicated section in Transaction Summary

---

__tests__/__snapshots__/documentation.js.snap
src/collections/_documentation/platforms/python/airflow.md
src/collections/_documentation/platforms/python/index.md

As promised, here is the Apache Airflow documentation.
The idea here is that we can get them started sending errors, and then point them to the actual Airflow docs, which will be more update to date about configuration, usage, tags/breadcrumbs tracked etc.
Although there is no Python code here, Airflow uses the python SDK internally to send errors, so I figured it would be best to put it under Python for now. Please let me know if there is a better way to do this, I'd be happy to oblige.

feat: Add documentation about Apache Airflow

---

gatsby/src/docs/workflow/releases/health.mdx
src/collections/_documentation/platforms/native/index.md

Adds a section about release health to the Native docs, and links to it from the main Release Health documentation as well. Most of the text is copied from other platforms.

docs: Add Native Release Health sections

---

src/collections/_documentation/platforms/node/aws_lambda.md

installing `sentry_sdk` gives the following error:
```
error An unexpected error occurred: "https://registry.yarnpkg.com/sentry_sdk: Not found".
````
Fixed to `@sentry/node`

Fixing package name

---

src/collections/_documentation/platforms/javascript/react.md

Documentation for the new Redux integration included in @sentry/react: https://github.com/getsentry/sentry-javascript/pull/2717
Currently as it is part of the @sentry/react package we include it on the React page for now.

feat: Docs for new Redux integration in @sentry/react

---

gatsby/src/includes/user-feedback-example/django.mdx

- I think there's a grammatical mistake in the following line `Make sure you've got have the JavaScript SDK available:`.
- This PR fixes this typo in django.mdx file.
- If this is a typo, I can fix this typo in other examples as well, please let me know.

Docs: Fixes minor typo in user-feedback-example(django.mdx)

---

README.md
gatsby/src/docs/accounts/quotas/index.mdx
gatsby/src/docs/enriching-error-data/attachments/index.mdx
src/collections/_documentation/platforms/native/index.md
src/collections/_documentation/platforms/native/minidump.md
src/collections/_documentation/platforms/native/ue4.md

Size limits for attachments are now at 100MB. Additionally, this PR adds more information on size limits to the Native SDK and Attachments page.
See https://github.com/getsentry/relay/pull/671
See https://github.com/getsentry/develop/pull/90

ref: Bump and document attachment size limits

---

src/collections/_documentation/platforms/javascript/react.md

Missing a closing \``` causing code block to not be closed. Probably caused when merging in a suggestion and missed the \```

fix: Missing closing ``` in redux section on react page

---

__tests__/__snapshots__/documentation.js.snap
src/collections/_documentation/platforms/python/index.md
src/collections/_documentation/platforms/python/pure_eval.md

Related:
https://github.com/getsentry/sentry-python/issues/748
https://github.com/getsentry/sentry-python/issues/762
https://github.com/getsentry/sentry-python/issues/763 ~(still needs merging)~

Add page for pure_eval integration

---

src/collections/_documentation/platforms/javascript/sentry-testkit.md

Sentry Testkit code example needed an update with '___PUBLIC_DSN___' and clarification that Wix maintains the plugin.

Update: Sentry Testkit

---

src/collections/_documentation/platforms/react-native/touchevents.md

Changed the `TouchEventBoundary` prop from `ignoredDisplayNames` to `ignoreNames`and add regular expression examples

feat: Update React Native touch event docs to use ignoreNames

---

src/collections/_documentation/platforms/react-native/touchevents.md

Document how to have Touch Events work with minified component names in React Native production builds.
https://github.com/getsentry/sentry-react-native/issues/976

feat: Add docs on how to handle minified production builds for rn touch events

---

gatsby/src/docs/cli/dif.mdx

We need to update the CLI docs to improve this statement in creating source bundles:
Currently:
"Alternatively, specify the --include-sources parameter to the upload command, which generates source bundles on the fly during the upload. This requires that the upload is performed on the same machine as the application build."
It should say: 
"Alternatively, specify the --include-sources parameter to use the upload-dif command, which generates source bundles on the fly during the upload. This requires that the upload is performed on the same machine as the application build."

Update: CLI for creating source bundles

---

__tests__/__snapshots__/documentation.js.snap
gatsby/package.json
gatsby/yarn.lock
src/collections/_documentation/platforms/javascript/gatsby.md

We've run `@sentry/gatsby` for a couple days on develop, and we've tested it with multiple versions, so I think we are good to add documentation for it.
This PR adds documentation to add and configure `@sentry/gatsby` in your gatsby projects.
See the package here: https://github.com/getsentry/sentry-javascript/tree/master/packages/gatsby.
Also bumps `@sentry/gatsby` to `5.20.0` cause `5.18.0` tracing was broken.

feat: Add docs for @sentry/gatsby

---

src/collections/_documentation/performance-monitoring/configuration/python.md

This section is just a duplicate of the section above.

Remove duplicated Python setup in Performance

---

gatsby/src/docs/workflow/search/index.mdx
src/collections/_documentation/performance-monitoring/discover-queries/query-builder.md

Search now includes the conditions `OR` and `AND`. This PR is dependent on https://github.com/getsentry/sentry/pull/19718 AND replaces https://github.com/getsentry/sentry-docs/pull/1857

Add: search conditions `OR` and `AND`

---

gatsby/src/docs/workflow/debug-files.mdx
gatsby/src/docs/workflow/integrations/azure-devops/index.mdx
gatsby/src/docs/workflow/integrations/bitbucket/index.mdx
gatsby/src/docs/workflow/integrations/github/index.mdx
gatsby/src/docs/workflow/integrations/gitlab/index.mdx
gatsby/src/docs/workflow/integrations/integration-platform/index.mdx

Gatsby interprets HTML escapes in code escapes literal, which means they need to be rewritten to angle brackets. Otherwise, they render as `&lt;` and `&gt;` on the page. Note that this does not apply outside of code quotes, where we need those HTML escapes.

fix: HTML escapes in code

---

gatsby/src/docs/workflow/search/index.mdx

These properties exist in both discover and issue search but weren't in
the documentation.

Add missing event properties to search docs

---

gatsby/src/docs/workflow/releases/release-automation/github-actions/index.mdx
gatsby/src/docs/workflow/releases/release-automation/index.md

Add GitHub Actions to release automation docs.

Add GitHub Actions to release automation docs

---

gatsby/src/docs/workflow/alerts-notifications/alerts.mdx

A few fixes for the Alert page. Includes updating the FAQ, fixing a sentence, and a broken image.

Update: Alerts page

---

src/docs/workflow/integrations/slack/index.mdx

So, move it to its own section, as [before](https://github.com/getsentry/sentry-docs/pull/1696/files#r427689427).

fix(slack): Deleting legacy slack plugin is not part of the upgrade process

---

src/docs/product/integrations/jira/index.mdx

From: https://docs.sentry.io/product/integrations/jira/
**Before**
**After**

fix(jira): Link should be link, not markdown

---

src/components/layout.js
src/components/pages/doc.js
src/components/seo.js

Adds a meta header for robots to tell bots not to index old pages.

feat: Add robots meta header

---

src/docs/accounts/sso/saml2.mdx
src/docs/product/sentry-basics/guides/integrate-frontend/generate-first-error.mdx
src/docs/sdks/javascript/index.mdx

fix: Use Sentry to refer to the product, sentry.io to the URL

---

src/docs/api/permissions.mdx

This is my first PR here, so please let me know if I'm missing anything!
I believe that these rows are meant to be tables. They didn't get formatted as such because they were missing a header row. So I added a header row. Additionally, I made the methods under the **Projects** heading bold to match the rest of the documentation.
The [current state](https://docs.sentry.io/api/permissions/) looks like this: 
This PR fixes the table formatting so that it looks like this:

Fix table formatting on /api/permissions

---

src/docs/sdks/javascript/index.mdx

The alert label can come off, I think.

Remove alert from JS docs as they are now live

---

src/docs/platforms/react-native/codepush.mdx
src/docs/platforms/react-native/sourcemaps.mdx

The `Sentry.setRelease` and `Sentry.setDist` have been deprecated and setting these values have been moved to just passing them to `Sentry.init`
https://github.com/getsentry/sentry-react-native/pull/1009

Update docs to reflect new change to setting release and dist in React Native

---

src/docs/platforms/react-native/codepush.mdx

Prior docs were unclear what these commands do and that a `--deployment` would need to be specified to upload to deployments that aren't the default Production or Staging.
https://github.com/getsentry/sentry-cli/issues/415#issuecomment-673325836

feat: Better codepush release upload docs

---

src/includes/performance-monitoring/configuration/javascript.mdx

The `tracingOrigins` option is referenced as `traceOrigins` in the performance "getting started" documentation.

Fix: consistent naming of tracingOrigins option

---

src/docs/platforms/javascript/react.mdx

There is an extra `can` in the fallback description for the `ErrorBoundary`: https://docs.sentry.io/platforms/javascript/react/#fallback-reactreactnode-or-function

fix: Extra `can` in fallback for ErrorBoundary

---

.github/CODEOWNERS

Extracted from https://github.com/getsentry/sentry-docs/pull/1993#issue-466982710
> @AbhiPrasad 
> We should probably divide the docs into issue owners. I guess this is more of a meta level thing, but I think making sure the teams are at least pinged on PR is useful. I assume web platform would "own" the JS SDK for now.
---
For starters we can have the Web Team for all SDKs and override with more specific owners as needed.
This will cause the team to be pinged on PRs that touch files under the given path.

misc: Create CODEOWNERS

---

src/docs/sdks/javascript/index.mdx

The links for "on this page" are duplicated in the RH sidebar, so no need for them. And mobile is not a rational use case for maintaining this list.

Remove "on this page" list

---

src/docs/clients/csharp/index.mdx
src/docs/clients/javascript/index.mdx
src/docs/clients/node/index.mdx
src/docs/clients/php/index.mdx
src/docs/clients/python/index.mdx

Closes https://github.com/getsentry/sentry-docs/issues/1995
We should point customers toward using our new SDKs. This PR adds deprecation warnings to all raven clients that did not have them before.
As a side note, we should try to avoid our deprecated SDKs superseding our new SDKs in search results, not sure if there is an easy way around that though.
I used messaging we have from https://docs.sentry.io/clients/cocoa/, but let me know if there is anything more appropriate.

feat: Provide deprecation warnings for raven clients

---

README.md
gatsby-config.js
gatsby-node.js
package.json
plugins/gatsby-plugin-sentry-wizard/gatsby-node.js
plugins/gatsby-remark-variables/index.js
plugins/gatsby-remark-variables/package.json
src/docs/platforms/angular/index.mdx
src/includes/set-environment/cordova.mdx
src/includes/set-environment/csharp.mdx
src/includes/set-environment/electron.mdx
src/includes/set-environment/go.mdx
src/includes/set-environment/javascript.mdx
src/includes/set-environment/native.mdx
src/includes/set-environment/node.mdx
src/includes/set-environment/python.mdx
src/includes/set-environment/rust.mdx
src/utils/packageRegistry.js
src/wizard/javascript/index.md

This primarily adds support for template variables (or otherwise javascript functions) executable within any markdown content. An example is found in the ``README.md``. Generally speaking, its the same as Django or Liquid: ``{{ scoped_variable }}``.
Using the system it implements the PackageRegistry and adds it to the scope as ``packages``, thus making them callable with e.g. ``packages.version()``.
Additionally this makes a few small changes to other various Gatsby configurations to improve performance.

feat: Template variables in markdown

---

src/docs/clients/node/sourcemaps.mdx
src/docs/platforms/node/sourcemaps.mdx

This PR updates the filename used for webpack configuration. It appears to be a typo.
https://webpack.js.org/concepts/configuration/

docs(sourcemaps): update webpack config filename extension

---

README.md
src/docs/platforms/go/echo.mdx
src/docs/platforms/go/fasthttp.mdx
src/docs/platforms/go/gin.mdx
src/docs/platforms/go/http.mdx
src/docs/platforms/go/iris.mdx
src/docs/platforms/go/martini.mdx
src/docs/platforms/go/negroni.mdx

Go documentation: split consecutive code blocks

---

src/components/jsCdnTag.js
src/docs/product/performance/apm-to-tracing.mdx
src/includes/performance-monitoring/configuration/javascript.mdx
src/includes/performance-monitoring/configuration/koa.mdx
src/includes/performance-monitoring/configuration/node.mdx
src/includes/performance-monitoring/configuration/react.mdx
src/includes/performance-monitoring/configuration/vue.mdx
src/platforms/javascript/index.mdx
src/wizard/javascript/index.md
src/wizard/javascript/react.md

Switch all references from `@sentry/apm` to `@sentry/tracing`.
Also add an upgrade guide detailing the changes.

feat: Migrate from @sentry/apm to @sentry/tracing

---

src/platforms/dotnet/wpf.mdx

The existing link went to a page that does not have any documentation on the `SentrySdk.Init()` method. The new link goes to the correct location that describes how to initialize the SDK

Fix SentrySdk.Init link in WPF documentation

---

src/components/sidebar.js
src/docs/index.md

We used to point people to the homepage of on-premise, advocating for the nightly builds. With this patch, we point them to the latest release.
Rel: https://app.asana.com/0/1169344595888357/1190341230301201/f

 ref(onpremise): Point people to the latest release 

---

src/platforms/dotnet/wpf.mdx

Add a note to clarify that the SentrySDK should be initialized in the application constructor and not the `OnStartup()` event.
This is valuable to specify explicitly because it is not common to have a constructor in a WPF `Application` class. App initialization is usually all done in the `OnStartup()` event, but attempting to initialize the Sentry SDK in the `OnStartup()` event leads to obscure issues with Hub and Scope stack initialization as outlined in the [community forum](https://forum.sentry.io/t/user-context-not-submitting-consistently/10806/4?u=senti.mark.monteiro)

Clarify WPF initialization instructions

---

src/platforms/node/connect.mdx

A few small fixes:
- remove SDK version so it's not immediately out of date
- break up installation code blocks so they both show (rather than being two tabs)
- space out options to make them easier to read and clarify option descriptions
- other random nits

fix(connect): Minor edits to Connect docs

---

src/docs/product/sentry-basics/environments/index.mdx

Environment names with any forward slash characters in "/" will be rejected by Sentry, as per https://github.com/getsentry/sentry/issues/6595#issuecomment-349483277 .  
The forward slash is a natural delineator to use for hierarchical environment names, a new user who reads the documentation and submits environment names with forward slashes can be frustrated to discover later that they are not accepted.
This change extends the documentation to include the forward slash character along with the other documented forbidden characters in environment names.

Document prohibition of forward slashes in environment name

---

README.md
src/platforms/android/index.mdx
src/platforms/java/common/config.mdx
src/platforms/java/common/migration.mdx
src/platforms/java/guides/google-app-engine/index.mdx
src/platforms/java/guides/log4j/index.mdx
src/platforms/java/guides/log4j2/index.mdx
src/platforms/java/guides/logback/index.mdx
src/platforms/java/guides/logging/index.mdx
src/platforms/java/guides/spring/index.mdx
src/platforms/java/index.mdx
src/platforms/java/usage.mdx
src/utils/packageRegistry.js
src/wizard/java/android.md
src/wizard/java/appengine.md
src/wizard/java/index.md
src/wizard/java/log4j.md
src/wizard/java/log4j2.md
src/wizard/java/logback.md
src/wizard/java/logging.md

- Support dynamic versions when available
- Remove invalid instructions on index - you need to use an integration
- Move manual usage under core Java (its the same as a guide)
- Add DSN placeholders
- Similar tweaks to Android
- Modernize Gradle instructions

feat: Overhaul Java documentation

---

.vscode/settings.json
src/components/codeBlock.tsx
src/css/_includes/code-blocks.scss
src/platforms/javascript/common/config/sourcemaps.mdx

This adds a few small improvements to code tabs:
* code blocks that are shell/bash now chop off the leading `$` for copy paste
* made the active selection less confusing (gray/white bold)
* separate a use of yarn/npm into tabs.

feat: improvements to code tabs

---

src/includes/performance-monitoring/configuration/koa.mdx

This is a terminology fix. The children of a transaction are spans, not
transaction themselves.

fix: Transactions have spans

---

src/platforms/node/common/integrations/default-integrations.mdx

The only substantive changes here are:
1) To list out the options for the `http` integration
2) To provide default option values as comments in the code
3) To demonstrate how to disable a single integration
Other than that, it's just cleaning up the language a bit.

ref(node): Small tweaks to Default Integrations page

---

src/docs/product/performance/getting-started.mdx
src/platforms/javascript/guides/angular/index.mdx
src/wizard/javascript/angular.md

This is an arbitrary change (but an improvement) to trigger a clean vercel build.

Fix: Capitalize the S in JavaScript

---

gatsby-config.js

Algolia was previously configured to use a Freight variable, but now that we're on Vercel we need to use the current git ref they provide.

Fix: Update gatsby-config.js

---

src/platforms/android/index.mdx
src/platforms/android/timber.mdx
src/wizard/java/android.md

the expression implementation 'io.sentry:sentry-android:`{{% packages.version('sentry.android', '{version}') }}'` is not being executed, so the dependency is wrong like the plain text mentioned above, the syntax looks good though, not sure what's happening, it should take the 2nd argument which is `{version}`.

fix: android version placeholder

---

src/wizard/javascript/vue.md

It additionally attempts to show two separate blocks for installing via npm/yarn vs. CDN, since the installation code snippet is different depending on which you choose.
I also dropped the es6 alternative use case since that feels unnecessary to me (we're already giving people 2 choices).

docs(vue): Update Vue wizard for tracing

---

src/docs/clients/csharp/index.mdx
src/docs/clients/javascript/usage.mdx
src/platforms/elixir/config.mdx
src/platforms/elixir/index.mdx
src/platforms/elixir/usage.mdx
src/platforms/java/common/config.mdx
src/platforms/node/common/integrations/pluggable-integrations.mdx
src/wizard/javascript/angular.md

We use US spelling in docs.
Note that for Elixir 'behaviour' is used as a technical term and thus preserved with a link to its definition.

fix: behaviour => behavior

---

src/platforms/javascript/common/integrations/default.mdx

TryCatch is missing as a heading in the JS docs.

Add missing header

---

src/docs/accounts/quotas/manage-event-stream-guide.mdx

Delete and discard is available only for business plan users; the guide is not clear about this.

Add missing note to guide

---

src/platforms/python/guides/gcp-functions/index.mdx
src/wizard/python/pythongcpfunctions.md

See https://github.com/getsentry/examples/pull/54.
Also, `event, context` is the pubsub entrypoint signature, which isn't what most people use. I changed it to http for a more popular example.
And pinned `sentry_sdk>=0.17.0` just to be extra correct.

fix(gcf): add trailing list bracket to examples

---

src/platforms/ruby/index.mdx

Fix: typo in Ruby "Context" link

---

vercel.json

Reported over at the forums https://forum.sentry.io/t/infinite-redirects-while-open-https-docs-sentry-io-hosted-cli/10932?u=byk

fix(redirect): Fix infinite hosted/on-premise redirects

---

src/platforms/java/index.mdx
src/platforms/ruby/index.mdx
src/wizard/ruby/index.md
src/wizard/ruby/rack.md
src/wizard/ruby/rails.md

This was incorrectly changed from `/clients/` to `/platform/` in e9462c722de66c8485681755dd0502c987293b8c, missing the 's'.
Links to `.../ruby/install/` are removed because the content apparently doesn't exist.
Follows up on #2128.

fix: /platform/ -> /platforms/

---

src/docs/accounts/quotas/index.mdx
src/docs/accounts/quotas/manage-event-stream-guide.mdx

The links between the guide and the quotas content weren't quite correct. This PR fixes the links Tony identified as broken.

Fix links in quotas and guide

---

README.md
src/components/__tests__/__snapshots__/platformRedirectLink.test.js.snap
src/components/__tests__/platformRedirectLink.test.js
src/components/breadcrumbs.tsx
src/components/hooks/usePlatform.tsx
src/components/markdown.tsx
src/components/platformGrid.tsx
src/components/platformRedirectLink.tsx
src/components/platformSidebar.tsx
src/pages/platform-redirect.tsx
src/platforms/common/data-management/index.mdx
src/platforms/common/enriching-error-data/index.mdx
vercel.json

- /enriching-error-data/ and /data-management/ will help you get to the platform specific content
- /error-reporting/ will get you to platform root
If the `platform` value is passed to `/redirect-page/` it will automatically forward you.
Fixes #2180 
Fixes #2181

feat: Add redirects for legacy pages which no longer exist

---

package.json
src/utils/algolia.js
yarn.lock

I've left one last bit of legacy index stuff that is necessary to avoid breaking sentry in production. Once the global lib is there we can remove it.

Feat: partial algolia updates

---

src/gatsby/createPages/createDevelopmentApiReference.ts

We can reuse the pages in the following routes and route them under `route.replace(/api/g, "development-api")` for each route:
- `/api/`
- `/api/auth/`
- `/api/requests/`
- `/api/permissions/`
- `/api/pagination/`

feat: Reuse existing API reference pages

---

src/components/relayMetrics.tsx
src/gatsby/onCreateNode.ts
src/gatsby/sourceNodes/relayMetricsNodes.ts

Fixes onCreateNode to skip nodes that do not have an absolute file path set. For
such nodes, the `gatsby-source-filesystem` has a buggy resovler that throws an
error while trying to retrieve file information.
It seems that the intention of this hook was to inject attributes on markdown
pages. However, markdown snippet nodes, such as in Relay metrics, do not need 
the `slug` and `legacy` fields.
Along with this fix, the relationship between `RelayMetric` and
`RelayMetricDescription` was changed to many-to-one by adding a reference to the
`parent` id.

fix: Child markdown node interception

---

src/platforms/java/guides/spring/index.mdx

the original link was only a 404, this should fix it
before: https://docs.sentry.io/platforms/java/guides/spring/config/#setting-the-dsn
after: https://docs.sentry.io/platforms/java/configuration/options/#setting-the-dsn

fix: Link to DSN config option

---

src/components/developmentApiSidebar.tsx
src/components/dynamicNav.tsx
src/gatsby/createPages/createDevelopmentApiReference.ts
src/templates/developmentAPI.js
src/templates/developmentApiDoc.js
src/templates/developmentApiReference.js

We want to customize the sidebar of the OpenAPI docs and show something similar to the [Stripe docs](https://stripe.com/docs).
If a user wants to exit the OpenAPI Reference then they can use the breadcrumbs navigation.

feat: DevelopmentAPI Sidebar

---

src/docs/product/relay/index.mdx
src/docs/product/relay/metrics.mdx
src/docs/product/relay/modes.mdx
src/docs/product/relay/options.mdx
src/docs/product/relay/projects.mdx

Updates wording as suggested by @PeloWriter in https://github.com/getsentry/sentry-docs/pull/2197, and applies standard definition list formatting to options docs.

ref(relay): Update wording and formatting

---

src/docs/accounts/quotas/manage-event-stream-guide.mdx
src/platforms/go/common/migration.mdx
src/platforms/go/index.mdx
src/platforms/java/common/migration.mdx
src/platforms/php/guides/symfony/config.mdx
src/wizard/java/log4j.md
src/wizard/java/log4j2.md
src/wizard/java/logging.md
src/wizard/ruby/rails.md

- `/platforms/.*/config/` doesn't exist anymore, thanks to @joergi for reporting in https://github.com/getsentry/sentry-docs/pull/2199#issuecomment-689424309
- lgo4j2 => log4j2
- Fixed some anchors
---
Hacky way of checking the URLs involved:
```
for url in $(git diff --cached -U0 | rg '^\+[^+]' | rg --only-matching '\]\(([^)]+)\)' -r '$1'); do curl -LIso /dev/null -w "%{url_effective} %{http_code}\n" https://docs.sentry.io$url ; done | sort -u 
```

fix: More broken links

---

src/platforms/javascript/common/configuration/lazy-load-sentry.mdx

Also add an 'alt' for the image.
See https://docs.sentry.io/platforms/javascript/configuration/lazy-load-sentry/#additional-configuration
---
---

fix: Markdown for image instead of link

---

src/templates/doc.tsx

OpenAPI docs sidebar not showing up on `/development-api/` in production

fix: Show custom sidebar on "/development-api"

---

src/pages/platform-redirect.tsx

This changes the platform redirect text so it also covers cases that are not
legacy redirects.  This comes in useful when trying to link to the docs for
grouping from the Sentry settings where the platform is not known.

feat: change platform redirect wording to be used for non legacy redirects

---

src/platforms/node/common/sourcemaps.mdx
src/platforms/node/common/typescript.mdx

https://docs.sentry.io/platforms/node/sourcemaps/ would redirect to itself.
Same problem in https://docs.sentry.io/platforms/node/typescript/.

fix: Infinite redirect loop

---

src/platforms/index.mdx

The C++ one hasn't had updates in 2 years and we have sentry-native
Flutter is supported by our team
Zend has a discontinued notice on the readme

Remove not relevant community supported SDKs

---

vercel.json

That's what we had pre-Vercel and Gatsby, so keep canonical URLs with a
trailing slash.
Reference and explanation why the default value 'undefined' is harmful
(double indexing harming SEO):
https://vercel.com/docs/configuration#project/trailingslash/true

feat: Tell Vercel to use trailing slash on URLs

---

src/platforms/javascript/common/lazy-load-sentry.mdx
src/platforms/javascript/common/sourcemaps/hosting-publicly.mdx
src/platforms/javascript/common/sourcemaps/index.mdx
src/platforms/javascript/common/sourcemaps/multiple-origins.mdx
src/platforms/javascript/common/sourcemaps/tools/index.mdx
src/platforms/javascript/common/sourcemaps/tools/systemjs.mdx
src/platforms/javascript/common/sourcemaps/tools/typescript.mdx
src/platforms/javascript/common/sourcemaps/tools/uglifyjs.mdx
src/platforms/javascript/common/sourcemaps/tools/webpack.mdx
src/platforms/javascript/common/sourcemaps/troubleshooting.mdx
src/platforms/javascript/common/sourcemaps/validating.mdx
src/platforms/javascript/common/supported-browsers.mdx

It does not make sense to have the same URL in the 'redirect_from' list
of multiple pages, because visiting the given URL can only redirect to
one location, not multiple.
AFAIK the has never been content in those URLs we are redirecting from,
so either we need different redirects or none (the content under the
"common" directory is used to generate pages, but "common" is not part
of the resulting URLs).
Updates 84d8a9375bfa997632fe792655a6a1bc004c2a46

fix: Remove redirects

---

src/platforms/javascript/common/sourcemaps/index.mdx

/platforms/javascript/sourcemaps/ would forever redirect to itself.
https://docs.sentry.io/platforms/javascript/sourcemaps/

fix: Remove infinite redirect loop

---

src/platforms/javascript/common/sourcemaps/troubleshooting_js.mdx

The name of the JS file for troubleshooting appears to be causing aberrant behavior because it has the same name as the directory troubleshooting.
Renaming the file solves the conflict; tested this on my local.

Rename troubleshooting due to naming conflict

---

src/platforms/go/guides/echo/index.mdx
src/platforms/go/guides/fasthttp/index.mdx
src/platforms/go/guides/gin/index.mdx
src/platforms/go/guides/http/index.mdx
src/platforms/go/guides/iris/index.mdx
src/platforms/go/guides/martini/index.mdx
src/platforms/go/guides/negroni/index.mdx

It's repetitive. We get it, it's all middleware.

ref: Remove middleware term from Go integrations

---

src/gatsby/config.ts
src/templates/developmentAPI.js

Some pages was not rendering properly on docs.sentry.io/development-api/. This is because we assumed some data fields would be present, so in this PR we just made them conditionally render on the existence of those fields.
Also this PR will deploy the latest SHA of `getsentry/sentry-api-schema`

fix: Should be able to render despite missing data fields

---

src/components/sidebar.tsx
src/docs/product/integrations/index.mdx
src/docs/product/integrations/integration-platform/index.mdx
src/docs/product/sentry-basics/search/index.mdx

Moved Integrations into its own top tier section in the main navigation sidebar.

moved Integrations in main nav sidebar

---

src/platforms/java/guides/log4j/index.mdx
src/platforms/java/guides/log4j2/index.mdx
src/platforms/java/guides/logging/index.mdx
src/platforms/ruby/guides/rails/index.mdx

Updates `.../config/` to `.../configuration/options/`, as that's where we talk about DSN and other init options.
Closes #2296.
Thanks to @bago2k4 for sending the original PR.

fix: Broken links

---

src/docs/product/alerts-notifications/alerts.mdx
src/docs/product/integrations/integration-platform/index.mdx
src/docs/product/integrations/integration-platform/webhooks.mdx

Updating docs for Sentry App Metric Alerts.
I've updated the field names in https://github.com/getsentry/sentry/pull/20497.

Update webhook field names

---

src/platforms/ruby/common/configuration/options.mdx
src/platforms/ruby/common/integrations.mdx

Hello 👋, Ruby SDK's latest version [`3.1.0`](https://github.com/getsentry/raven-ruby/releases/tag/3.1.0) was just released. And this PR updates the documents to reflect the changes.

Update Ruby doc for latest 3.1 version

---

.github/CODEOWNERS

Adding the team to CODEOWNERS considerably increased the number of
GitHub notifications the team is getting on a daily basis, while most of
it ends up being noise, rather than PRs that are really waiting for an
approval or other input from the team.
A negative effect of excessive noise is that PRs that really need the
team's attention might accidentally be ignored, lost in the middle of
other unimportant notifications.
From now on we'd like to experiment with manually and explicitly
requiring our review on PRs that genuinely require it, leaving the
initial triage for the docs team that owns the repo as a whole.

misc(CODEOWNERS): Comment out web platform team

---

src/docs/product/integrations/integration-platform/webhooks.mdx

We needed a small note about how the stack frame order lists the oldest frame to the most recent.

Add: note about stack frame order

---

src/docs/product/relay/best-practices.mdx
src/docs/product/relay/getting-started.mdx
src/docs/product/relay/index.mdx
src/docs/product/relay/modes.mdx
src/docs/product/relay/options.mdx
src/docs/product/relay/projects.mdx

- Also reverts the sidebar order back to original.
- This also inlines links so that they no longer get out of sync with the page. 
- Finally, this reformats the best practices page.
Follow-up to https://github.com/getsentry/sentry-docs/pull/2331

fix(relay): Update links after moving to product

---

src/platforms/common/configuration/index.mdx
src/platforms/common/enriching-events/attachments/index.mdx
src/platforms/common/enriching-events/breadcrumbs.mdx
src/platforms/common/enriching-events/context.mdx
src/platforms/common/enriching-events/identify-user.mdx
src/platforms/common/enriching-events/index.mdx
src/platforms/common/enriching-events/scopes.mdx
src/platforms/common/enriching-events/tags.mdx
src/platforms/common/enriching-events/user-feedback.mdx
src/platforms/common/usage/index.mdx

This PR ensures that breakpad, crashpad, and minidumps don't display information that is not pertinent to their audience.

add unsupported to frontmatter for breakpad, crashpad, and minidumps

---

src/gatsby/config.ts

This PR updates the SHA to the [api-schema ](https://github.com/getsentry/sentry-api-schema) hopefully one last time before we go live with the new API docs to include the mostly cosmetic changes from https://github.com/getsentry/sentry-api-schema/pull/26

feat(api-docs): Update SHA one last time

---

src/gatsby/config.ts

This PR updates the SHA for the sentry-api-schema repo to include the change from https://github.com/getsentry/sentry-api-schema/pull/27

feat(api-docs): Update SHA to get latest schema

---

src/includes/configuration/before-send/php.mdx

Correcting the return type from Event to Sentry\Event in PHP before_send example.

Correcting return type

---

src/gatsby/config.ts

This PR updates the api-schema SHA again to include the changes from https://github.com/getsentry/sentry-api-schema/pull/28

feat(api-docs): Update api-schema SHA

---

src/docs/contributing/environment.mdx
src/gatsby/config.ts

This adds an environment variable `DISABLE_THUMBNAILS=1` that will disable the image thumbnail step of builds for faster development.

Add env var that disables image thumbnail step

---

src/docs/product/sentry-basics/search/index.mdx

Search for Releases only supports raw text and not query syntax.

Add: Note about Search for Releases

---

src/docs/cli/releases.mdx
src/platforms/common/configuration/releases.mdx

We need to let customers know that "/" is unavailable for release ids.

Add: restriction for release naming

---

src/__tests__/utils.test.js
src/templates/apiPage.tsx
src/utils.ts

All code formatted strings are formatted properly.
Naive parsing function should be O(n). **Can this be improved?**
*BEFORE*
*AFTER*

feat: Parse backticks as html code elements

---

src/components/platformGrid.tsx

I was bothered that a number of the Python integrations get cut off. This makes it so that the cards are no longer uniform, but I think it looks fine having Python as the one outlier (everything else lines up fine).
Before:
After:

fix(platforms): Let sub-platform list overflow

---

src/docs/accounts/quotas/index.mdx
src/docs/accounts/quotas/manage-event-stream-guide.mdx

Docs has many broken/dead fragment URLs because an anchored section of a page moved or was renamed.

Fix: broken fragment URLs (anchor tags)

---

src/docs/accounts/quotas/index.mdx
src/docs/clients/javascript/usage.mdx
src/docs/clients/node/index.mdx
src/docs/product/integrations/gcp-cloud-run/index.mdx
src/docs/product/sentry-basics/environments/index.mdx
src/docs/product/sentry-basics/guides/integrate-frontend/upload-source-maps.mdx
src/includes/getting-started-install/dotnet.mdx
src/platforms/android/migration.mdx
src/platforms/android/timber.mdx
src/platforms/common/enriching-events/user-feedback.mdx
src/platforms/dotnet/guides/log4net/index.mdx
src/platforms/dotnet/index.mdx
src/platforms/javascript/common/sourcemaps/index.mdx

Replaces any absolute URL in a markdown file that pointed to docs.sentry.io and instead uses a relative URL. This way I can navigate links on a local development build without being transported to the production website.

fix(urls): Use relative URLs instead of linking to docs.sentry.io

---

src/platforms/android/index.mdx
src/platforms/common/data-management/event-grouping/index.mdx
src/platforms/common/data-management/sensitive-data/advanced-datascrubbing.mdx

Fixed a few broken anchor tags in the Android docs.

Fix: broken anchor tags

---

src/platforms/common/configuration/filtering.mdx
src/platforms/common/performance/sampling.mdx
src/platforms/javascript/common/performance/index.mdx
src/platforms/javascript/index.mdx

Switch to using a `PlatformLink`, and move the sampling page to `common` to fix a broken link on the filtering page.
Now that the file is common, more parts will need to be "platform-ized" but this should fix the broken links for now and that can come in a follow-up PR.

fix(links): Move performance sampling page to common

---

src/wizard/javascript/react.md

Removes the big alert block trying to explain that `@sentry/react` is a wrapper around `@sentry/browser` (new users shouldn't know or care)

docs(react): Simplify React wizard help text

---

src/docs/product/releases/health.mdx

opening this one to continue https://github.com/getsentry/sentry-docs/pull/1923, too much conflicts

fix: event.level fatal is not a crashed session

---

src/platforms/php/guides/laravel/index.mdx
src/wizard/php/laravel.md

Once we merge this PR
https://github.com/getsentry/sentry-laravel/pull/392
It's one command the user needs to run to setup everything:
`php artisan sentry:publish --dsn=___PUBLIC_DSN___`
In case the user doesn't paste it with `--dsn` the command will prompt for the DSN.

feat: Simplify Laravel onboarding

---

src/components/platformSection.tsx
src/docs/contributing/pages/components.mdx
src/includes/framework-list/_default.mdx 
src/includes/framework-list/javascript.mdx

Introduce `noGuides` attribute on `PlatformContent` to enable hiding content from guide pages.

feat: Hide framework list from guides

---

src/platforms/android/usage/advanced-usage.mdx

Users don't know what `sentry-native` is:

Android: explain sentry-native

---

vercel.json

Currently this leads to an infinite redirect:
```
https://docs.sentry.io/platforms/native/context/
https://docs.sentry.io/platforms/native/enriching-events/context/
https://docs.sentry.io/platforms/native/enriching-events/enriching-events/context/
...
```

fix: Fix wildcard usage in platforms

---

src/includes/set-environment/ruby.mdx

`environment=` does not exist. Use `current_environment=` instead. See
https://github.com/getsentry/sentry-ruby/blob/94138234bdca8bd1cb44b36990b84b0ab5c0ff02/lib/raven/configuration.rb#L24.

fix: ruby environment config

---

src/includes/set-user/apple.mdx

Add a comment to set-user on Apple about setting the installation id of
the SDK as the userId of an event before queuing it for submission.
Only merge when https://github.com/getsentry/sentry-cocoa/pull/757 is released.

feat(apple): Set installation id as user id

---

src/platforms/dotnet/index.mdx

C# compile won't be happy with `1/0`. There must be at least a variable involved.

fix(dotnet): sample wouldn't compile

---

src/includes/performance/always-inherit-sampling-decision/javascript.mdx
src/includes/performance/always-inherit-sampling-decision/node.mdx
src/includes/performance/dynamic-sampling-function/javascript.mdx
src/includes/performance/dynamic-sampling-function/node.mdx
src/includes/performance/force-sampling-decision/javascript.mdx
src/includes/performance/force-sampling-decision/node.mdx
src/includes/performance/uniform-sample-rate/javascript.mdx
src/includes/performance/uniform-sample-rate/node.mdx
src/platforms/common/configuration/filtering.mdx
src/platforms/common/performance/sampling.mdx

Follow up to https://github.com/getsentry/sentry-docs/pull/2401.
Now that the sampling page is in `/common`, anything language-specific needs to be pulled out into includes so it can be swapped out.

fix(performance): Pull platform-specific content into includes

---

src/gatsby/config.ts
src/gatsby/utils/resolveOpenAPI.ts

We want to work locally with API docs so that people can make changes to the OpenAPI spec in Sentry but also be able to see what it would look like in docs.sentry.io/api/.
In this PR, I have implemented support for developers to set an environment variable `OPENAPI_LOCAL_PATH` that can be lead to their locally generated `openapi-derefed.json`. 
If it is able to resolve the path, `gatsby-plugin-openapi` will generate its' graphql nodes from the local `openapi-derefed.json`, else it defaults to fetching the `openapi-derefed.json` from the versioned commit in `getsentry/sentry-api-schema`.
ex: `OPENAPI_LOCAL_PATH=/Users/nisanthan.nanthankumar/Documents/sentry-api-schema/openapi-derefed.json yarn start`
- Support Hot-Reload. Maybe we can watch the file from the env variable. **Need to look …

ref: Move resolve function and implement support for local OpenAPI paths

---

src/components/dynamicNav.tsx
src/components/platformSidebar.tsx
src/components/sidebar.tsx
src/gatsby/createPages/createApiReference.ts
src/gatsby/createPages/createDocPages.ts
src/gatsby/createPages/createInternalDocPages.ts
src/gatsby/createPages/createPlatformPages.ts
src/gatsby/createSchemaCustomization/index.ts
src/utils.ts

Allow specifying sidebar_title in frontmatter to override the value in generated sidebar trees.

feat: Add support for sidebar_title

---

src/components/platformSidebar.tsx
src/platforms/common/performance/sampling.mdx
src/platforms/javascript/common/performance/capturing/automatic.mdx
src/platforms/javascript/common/performance/capturing/index.mdx
src/platforms/javascript/common/performance/capturing/manual.mdx
src/platforms/javascript/common/performance/index.mdx

Primarily with the purpose of making each heading one line.

ref(tracing): Reorganize and rename tracing sections in SDK docs

---

src/platforms/apple/migration.mdx

Move the migration guide from https://github.com/getsentry/sentry-cocoa/blob/master/MIGRATION.md in here.

feat(apple): Add migration guide from Github

---

src/gatsby/plugins/gatsby-plugin-openapi/types.ts
src/gatsby/utils/resolveOpenAPI.ts
src/templates/apiPage.tsx

In [this PR](https://github.com/getsentry/sentry/pull/21149) the `requestBody` is refactored to move the `example` below the `schema` and thus, the template must be refactored to account for the change. This PR adds in the "new" example to continue to display it properly in the cURL example.

ref(api-schema): Add new request body example

---

src/includes/before-breadcrumb/apple.mdx
src/includes/breadcrumbs-example/apple.mdx
src/includes/capture-error/apple.mdx
src/includes/capture-message/apple.mdx
src/includes/cocoa/integrations/apple.mdx
src/includes/cocoa/pass-scope/apple.mdx
src/includes/cocoa/scope-callback/apple.mdx
src/includes/configuration/auto-session-tracking/apple.mdx
src/includes/configuration/before-send/apple.mdx
src/includes/configuration/sample-rate/apple.mdx
src/includes/configuration/session-tracking-interval/apple.mdx
src/includes/configure-scope/apple.mdx
src/includes/getting-started-verify/apple.mdx
src/includes/set-context/apple.mdx
src/includes/set-environment/apple.mdx
src/includes/set-extra/apple.mdx
src/includes/set-fingerprint/basic/apple.mdx
src/includes/set-level/apple.mdx
src/includes/set-release/apple.mdx
src/includes/set-tag/apple.mdx
src/includes/set-user/apple.mdx
src/includes/trigger-crash/apple.mdx
src/includes/unset-user/apple.mdx
src/includes/with-scope/apple.mdx

Other platforms all display the import statement at the top of code samples,
because it is in our philosophy to assume novice developers.

fix(apple): Add imports for Apple code samples

---

src/gatsby/createPages/createApiPages.ts

fix: API docs column widths

---

src/docs/product/cli/dif.mdx

Correcting markdown note under ProGuard Mapping Upload, part of the note text was outside the markdown block.

Correcting markdown note

---

src/components/__tests__/configKey.test.js
src/components/__tests__/platformSection.test.js
src/components/hooks/usePlatform.tsx
src/components/platformContent.tsx
src/components/platformSection.tsx

This resolves an issue for guides which their base platform also includes a fallbackPlatform. For example, the `node.express` guide should fallback to `node`, then to `javascript`.

feat: Support full fallback path on platform content

---

vercel.json

Instead of using `.*` and causing infinite redirects because of too
liberal matchers, use `[^/]` and just duplicate.

fix: Duplicate redirects for guide-level

---

src/platforms/javascript/common/performance/capturing/automatic.mdx
src/platforms/javascript/common/performance/index.mdx

Note that we use `pageload` when referring to a specific type of transaction (by
its "op" value), and page load otherwise.

fix: Typos

---

src/platforms/java/guides/spring-boot/index.mdx

To avoid issues like https://github.com/getsentry/sentry-java/issues/970 this change makes it clear what's the minimum supported Spring Boot version.

Add minimum Spring Boot version to docs.

---

src/platforms/javascript/guides/react/components/errorboundary.mdx

The typo was "avaliable" instead of "available"

Fix typo in `errorboundary.mdx`

---

.github/workflows/test.yml

https://github.com/untitaker/hyperlink/commit/422d51f1dae067af25d491c06889814f7b088c87#diff-04c6e90faac2675aa89e2176d2eec7d8R46
That commit will show the filenames of the original markdown files *additionally*.
We're bumping cache name and pin by rev to make sure to get a commit that contains the new option.

chore: Update linkchecker to show markdown filenames

---

src/docs/product/sentry-basics/dsn-explainer.mdx
src/platforms/common/index.mdx

Add DSN page into Sentry Basics and link to that page from the Getting Started.

Move DSN content into a basic explainer

---

src/platforms/java/guides/spring-boot/index.mdx

Nothing wrong with it grammatically, but as it stands the meaning is ambiguous.

fix(spring-boot): Clarify meaning in `CustomEventProcessor` and related sections

---

src/docs/product/cli/dif.mdx

because of https://github.com/getsentry/sentry-android-gradle-plugin/pull/28

fix: remove android-manifest command from upload-proguard docs

---

src/includes/set-environment/ruby.mdx

Relevant URL: https://docs.sentry.io/platforms/ruby/guides/rails/configuration/environments/
`environment` isn't a valid config and causes the app to crash; I looked into the code and it seems like it's called `current_environment`.

Docs: Fix Ruby `current_environment` config name

---

src/__tests__/utils.test.js
src/gatsby/createSchemaCustomization/apiSchema.ts
src/gatsby/plugins/gatsby-plugin-openapi/gatsby-node.ts
src/gatsby/plugins/gatsby-plugin-openapi/types.ts
src/templates/apiPage.tsx
src/utils.ts

Original Problem:
On the API docs, the description field no longer formats backticks correctly, instead rendering them as "<code>id</code>" for example.
In this PR, I made the `gatsby-plugin-openapi` create child nodes for each API path's parameters and description. For this child nodes, I tagged as `text/markdown` so that the `gatsby-plugin-mdx` and `gatsby-transformer-remark` automatically parse the strings. Then we can render the result in the `<Markdown>` component. This removes the need to `dangerouslySetInnerHTML` for the params and the description.
I removed `parseBacticks` bc we don't need it anymore.
**Before**
**After**

fix: Render markdown formatting in description

---

src/platforms/java/guides/spring/index.mdx

Correcting some minor typos on Sentry Spring (https://docs.sentry.io/platforms/java/guides/spring/) page.

fix typos spring

---

src/docs/product/sentry-basics/search/index.mdx

Customer wrote in about confusion between `stack.package` and `stack.module`. Added a note to clarify the difference.

Add: note about `stack.package` for Native 

---

src/includes/getting-started-primer/python.django.mdx

Fix typo in django docs.

---

src/includes/performance/default-sampling-context/node.mdx

The same sentence makes up a generic paragraph before the include.
---
https://docs.sentry.io/platforms/node/guides/aws-lambda/performance/sampling/#default-sampling-context-data

fix: Remove repeated sentence

---

src/platforms/python/common/performance/index.mdx

`traces_sample_rate` is enabled by default:
https://github.com/getsentry/sentry-python/blob/d8c161fb289b44b5cd4b83d0bb31112031925713/sentry_sdk/consts.py#L35-L70

Remove Python Automatic Instrumentation section

---

vercel.json

This adds a redirect for Ember to fix search results in google not bringing you to the new guides.

fix: Force redirect for Ember

---

src/platforms/javascript/guides/react/components/errorboundary.mdx

Believe 'occured' should be: 'occurred'

Correct 'occurred' typo in code example

---

src/platforms/common/data-management/data-forwarding.mdx

Believe this is meant to say: "for `error` events"

Update data-forwarding.mdx - remove duplicate: "for for"

---

src/docs/product/sentry-basics/guides/integrate-backend/capturing-errors.mdx
src/docs/product/sentry-basics/guides/integrate-backend/configuration-options.mdx
src/docs/product/sentry-basics/guides/integrate-backend/getting-started.mdx
src/docs/product/sentry-basics/guides/integrate-frontend/configure-scms.mdx
src/docs/product/sentry-basics/guides/integrate-frontend/create-new-project.mdx
src/docs/product/sentry-basics/guides/integrate-frontend/generate-first-error.mdx
src/docs/product/sentry-basics/guides/integrate-frontend/initialize-sentry-sdk.mdx
src/docs/product/sentry-basics/guides/integrate-frontend/upload-source-maps.mdx

A few docs in the Guides section of Product needed descriptions in the front matter.

Add: front matter descriptions to Guides

---

.github/workflows/bump-openapi.yml
src/gatsby/utils/resolveOpenAPI.ts

Refactor our existing bump SHA action in `sentry-api-docs`, so that we have something similar to `./bin/bump-sentry` in getsentry.
This workflow listens to a workflow dispatch event and takes in a SHA. Then it will search and replace the with this latest SHA.
Concurrent PR: https://github.com/getsentry/sentry-api-schema/pull/32

feat(actions): Create new workflow to bump sentry-api-schema SHA

---

.github/workflows/bump-openapi.yml

sed on macos and linux are slightly different. 
There is an issue of sed on linux not being able to read the file path https://github.com/getsentry/sentry-docs/runs/1300790572?check_suite_focus=true
But I am not able to replicate this on MacOs. I think this should fix the issue.

fix(workflow): Fix sed command for linux

---

src/includes/performance/always-inherit-sampling-decision/python.mdx
src/includes/performance/custom-sampling-context/python.mdx
src/includes/performance/default-sampling-context/python.mdx
src/includes/performance/dynamic-sampling-function-intro/python.mdx
src/includes/performance/force-sampling-decision/python.mdx
src/includes/performance/traces-sample-rate/python.mdx
src/includes/performance/traces-sampler-as-filter/python.mdx
src/includes/performance/traces-sampler-as-sampler/python.mdx
src/includes/performance/uniform-sample-rate/python.mdx
src/platforms/common/configuration/filtering.mdx
src/platforms/common/configuration/options.mdx
src/platforms/common/performance/sampling.mdx

This add includes for both the filtering config page and the performance/sampling page for Python, and adds Python to the list of supported platforms for the latter, so that it will show up in the Python docs.

feat(tracing): Add python includes for transaction sampling

---

src/platforms/native/guides/ue4/index.mdx

Remove mentioning the DSN since correct configuration on UE4 requires the Unreal Engine Endpoint instead of the DSN.

fix(unreal): Do not mention DSN in the context of UE4

---

package.json
yarn.lock

Upgrade platformicons in order to display Spring and Spring Boot logos.

Upgrade platformicons

---

src/platforms/common/enriching-events/breadcrumbs.mdx

This PR does a few things:
- Adds a list of the keys which can be used in a manually-captured breadcrumb, along with a warning that sending keys other than those listed will result in the data being lost.
- Moves the `beforeBreadcrumb` example into the correct section.
- Explains how `beforeBreadcrumb` can be used to drop a breadcrumb.
- Does general wordsmithing.

ref(breadcrumbs): Add to and tweak common SDK breadcrumb content

---

src/platforms/go/guides/echo/index.mdx
src/platforms/go/guides/fasthttp/index.mdx
src/platforms/go/guides/gin/index.mdx
src/platforms/go/guides/http/index.mdx
src/platforms/go/guides/iris/index.mdx
src/platforms/go/guides/martini/index.mdx
src/platforms/go/guides/negroni/index.mdx

A few files in /guides needed front matter descriptions.

Add: front matter descriptions to /guides in /platforms

---

src/platforms/dotnet/guides/aspnet/index.mdx
src/platforms/dotnet/guides/aspnetcore/index.mdx
src/platforms/dotnet/guides/entityframework/index.mdx
src/platforms/dotnet/guides/extensions-logging/index.mdx
src/platforms/dotnet/guides/log4net/index.mdx
src/platforms/dotnet/guides/nlog/index.mdx
src/platforms/dotnet/guides/serilog/index.mdx
src/platforms/dotnet/guides/winforms/index.mdx
src/platforms/dotnet/guides/wpf/index.mdx

A few files in /guides needed descriptions in the front matter.

Add: front matter description to /guides in /platforms

---

src/platforms/react-native/advanced-setup.mdx
src/platforms/react-native/migration.mdx

Docs for users migrating to the 2.x version of the React Native SDK.
- Changes android package name from `io.sentry.RNSentryPackage` to `io.sentry.react.RNSentryPackage`
- Migration docs for users moving from 1.x to 2.x.
Linked PR:
https://github.com/getsentry/sentry-react-native/pull/1131

feat: React Native SDK 2.x migration docs

---

src/docs/product/relay/options.mdx

Related PR: https://github.com/getsentry/relay/pull/821

relay: Add `metrics.buffering` and `metrics.sample_rate` options

---

src/platforms/apple/common/migration.mdx

Merge only after https://github.com/getsentry/sentry-cocoa/pull/819 is merged and Cocoa 6.0.7 is released.

feat(apple): Update migration guide on enabled

---

src/platforms/apple/common/enriching-events/user-feedback.mdx

In the code sample for Swift user feedback was written UserFeedback.
This is fixed now.

fix(apple): Typo in UserFeedback

---

src/platforms/rust/guides/actix-web/index.mdx

A file in Rust's guide needed front matter description.

Add: front matter description to Rust guide

---

src/platforms/ruby/guides/rails/index.mdx

One file in Ruby guides needed front matter description.

Add: front matter description to Ruby guides

---

src/platforms/python/guides/aiohttp/index.mdx
src/platforms/python/guides/airflow/index.mdx
src/platforms/python/guides/asgi/index.mdx
src/platforms/python/guides/aws-lambda/index.mdx
src/platforms/python/guides/azure-functions/index.mdx
src/platforms/python/guides/beam/index.mdx
src/platforms/python/guides/bottle/index.mdx
src/platforms/python/guides/celery/index.mdx
src/platforms/python/guides/chalice/index.mdx
src/platforms/python/guides/django/http_errors.mdx
src/platforms/python/guides/falcon/index.mdx
src/platforms/python/guides/gcp-functions/index.mdx
src/platforms/python/guides/logging/index.mdx
src/platforms/python/guides/pyramid/index.mdx
src/platforms/python/guides/pyspark/index.mdx
src/platforms/python/guides/rq/index.mdx
src/platforms/python/guides/sanic/index.mdx
src/platforms/python/guides/serverless/index.mdx
src/platforms/python/guides/tornado/index.mdx
src/platforms/python/guides/tryton/index.mdx
src/platforms/python/guides/wsgi/index.mdx

A few files in Python guides needed front matter descriptions.

Add: front matter descriptions for Python guides

---

src/platforms/node/common/configuration/integrations/default-integrations.mdx

Fixes https://github.com/getsentry/sentry-javascript/issues/1661#issuecomment-718200921
Fixes https://github.com/getsentry/sentry-javascript/issues/2796#issuecomment-718204061

ref(node): Clarify usage of onFatalError option in node

---

src/includes/getting-started-config/android.mdx

I guess a few more are missing the `this` or `context`, need to search for it, it's a typo from copying the examples from Java which doesn't require the context.

add missing this (context) for android getting started config

---

src/platforms/javascript/common/configuration/integrations/plugin.mdx

The example seems to be trying to provide an arrow function with an inferred return, if so - then the parenthesis here is in the way

remove extra parenthesis

---

src/includes/performance/traces-sampler-as-sampler/python.mdx

Somehow all the `return`s in the return statements went missing.
Fixes #2660.

fix(tracing): Add missing `return`s to snippet

---

src/components/codeTabs.tsx

s/Php/PHP
Also, I alphabetized the relevant array, to make it easier to find stuff quickly.

fix(PHP): Correctly case PHP on code tabs

---

src/platforms/python/common/performance/index.mdx

This removes the `<Note>` component (so they text doesn't show up in grey) and pulls in more content from the JS version of the page, to bring them more in line.

ref(tracing): Improve note about sampling when testing on Python page

---

src/includes/capture-error/_default.mdx
src/platforms/common/index.mdx

This PR adds to the option to manually generate an event to the verification step in Getting Started.

Update common to include manual event generation

---

.github/workflows/test.yml

We will likely have to change the cache key to include package.json.
Follows up on #2666

chore: Use volta for main build

---

src/includes/performance/default-sampling-context-platform/javascript.mdx
src/includes/performance/default-sampling-context-platform/node.mdx
src/includes/performance/default-sampling-context-platform/python.mdx
src/includes/performance/default-sampling-context/javascript.mdx
src/includes/performance/default-sampling-context/node.mdx
src/includes/performance/default-sampling-context/python.aiohttp.mdx
src/includes/performance/default-sampling-context/python.asgi.mdx
src/includes/performance/default-sampling-context/python.aws-lambda.mdx
src/includes/performance/default-sampling-context/python.bottle.mdx
src/includes/performance/default-sampling-context/python.celery.mdx
src/includes/performance/default-sampling-context/python.django.mdx
src/includes/performance/default-sampling-context/python.falcon.mdx
src/includes/performance/default-sampling-context/python.flask.mdx
src/includes/performance/default-sampling-context/python.gcp-functions.mdx
src/includes/performance/default-sampling-context/python.mdx
src/includes/performance/default-sampling-context/python.pyramid.mdx
src/includes/performance/default-sampling-context/python.rq.mdx
src/includes/performance/default-sampling-context/python.tryton.mdx
src/includes/performance/default-sampling-context/python.wsgi.mdx

This documents the changes made in https://github.com/getsentry/sentry-python/pull/888, https://github.com/getsentry/sentry-python/pull/906, and https://github.com/getsentry/sentry-python/pull/916 - adding information to the default sampling context passed to `traces_sampler` for the `aiohttp`, `asgi`, `aws`, `bottle`, `celery`, `django`, `falcon`, `flask`, `gcp`, `pyramid`, `rq`, `tryton`, and `wsgi` integrations to the Python SDK. (Some of those didn't directly have it added but rely on the `wsgi` integration and therefore get it for free.)

feat(tracing): Document integration-specific default sampling context for Python

---

src/platforms/common/enriching-events/user-feedback.mdx

Unless I'm mistaking, it seems like the user properties are listed below, not above the line mentioned

User keys are actually listed _below_ the lines

---

src/platforms/common/configuration/options.mdx

Once Python SDK implemented this correctly we can remove the dupe.
https://github.com/getsentry/sentry-python/issues/926

fix: PHP request body

---

src/docs/contributing/approach/write-getting-started.mdx

Makes all code file references in the guide consistent and link to relevant GitHub pages in the getting started guide.

feat(sdk-guide): Make file references consistent

---

src/platforms/javascript/common/sourcemaps/index.mdx

Fix typo on JavaScript source maps page

---

src/docs/product/integrations/splunk/index.mdx

Our Splunk integration docs are out of date. When we try to setup an HEC with the self-service Splunk plan and our current docs, we fail to connect with a valid url. 
Our current docs provide the same instructions as the Splunk docs:
https://docs.splunk.com/Documentation/Splunk/8.1.0/Data/UsetheHTTPEventCollector#Send_data_to_HTTP_Event_Collector_on_Splunk_Cloud_instances
However, when we remove the `input` prefix from the url, we are able to connect to the Splunk instance and forward events. This has only been confirmed with the self-service Splunk Cloud plan.
Apparently for other plans, Splunk need to use `https-input` prefix, but we need to confirm whether this is still true.

fix(integrations): Update Splunk self-service HEC url

---

src/platforms/javascript/common/performance/capturing/manual.mdx

In case someone lands on the latter before the former.

fix(tracing): Add link to Enabling Tracing page from Manual Capture page

---

src/includes/getting-started-config/java.spring-boot.mdx
src/includes/getting-started-config/java.spring.mdx
src/includes/getting-started-install/java.log4j2.mdx
src/includes/getting-started-install/java.spring-boot.mdx
src/includes/getting-started-install/java.spring.mdx
src/platforms/java/common/configuration/index.mdx
src/platforms/java/guides/logback/index.mdx
src/platforms/java/guides/spring-boot/logging-frameworks.mdx
src/platforms/java/usage.mdx
src/wizard/java/spring-boot.md

- bump version to 3.2.0
- update proxy docs (https://github.com/getsentry/sentry-java/pull/1035)
- Update Spring exception resolver order docs (getsentry/sentry-java#1008)
- Update Java configuration (gh-725)

Java docs update

---

src/platforms/java/common/configuration/index.mdx

Adds docs about setting tags from the external configuration (https://github.com/getsentry/sentry-java/issues/981) and for each property that can be set externally adds an example on how to set it from the properties file, system property and environment variable.
Fixes https://github.com/getsentry/sentry-java/issues/992

Java: update configuration docs.

---

src/includes/performance/always-inherit-sampling-decision/java.mdx
src/includes/performance/custom-sampling-context/java.mdx
src/includes/performance/default-sampling-context-platform/java.mdx
src/includes/performance/default-sampling-context/java.mdx
src/includes/performance/dynamic-sampling-function-intro/java.mdx
src/includes/performance/enable-tracing/java.mdx
src/includes/performance/enable-tracing/java.spring-boot.mdx
src/includes/performance/force-sampling-decision/java.mdx
src/includes/performance/traces-sample-rate/java.mdx
src/includes/performance/traces-sample-rate/java.spring-boot.mdx
src/includes/performance/traces-sampler-as-sampler/java.mdx
src/includes/performance/traces-sampler-as-sampler/java.spring-boot.mdx
src/includes/performance/uniform-sample-rate/java.mdx
src/platforms/common/performance/sampling.mdx
src/platforms/java/common/performance/index.mdx
src/platforms/java/guides/spring-boot/performance/capturing/index.mdx
src/platforms/java/guides/spring-boot/performance/index.mdx

First batch of Java performance docs. Spring integration will come next.
Python Performance reference was used as the starting point.
Note: these docs use `Sentry#getSpan` method, which is currently under review: https://github.com/getsentry/sentry-java/pull/1070

Add Java & Spring Boot performance docs.

---

src/docs/clients/react-native/sourcemaps.mdx
src/docs/product/cli/releases.mdx
src/platforms/javascript/common/sourcemaps/troubleshooting_js.mdx
src/platforms/javascript/common/sourcemaps/uploading.mdx
src/platforms/react-native/sourcemaps.mdx

`upload-sourcemaps --rewrite` has been removed in https://github.com/getsentry/sentry-cli/pull/853 and will now cause an error when provided. This updates documentation to remove all mention of `--rewrite`.

fix(cli): Update all mention of --rewrite

---

src/platforms/javascript/guides/vue/index.mdx
src/platforms/javascript/guides/vue/integrations/components.mdx
src/wizard/javascript/vue.md

Just small updates to use Vue SDK vs. the integration.

ref: Update Vue docs for SDK

---

src/docs/contributing/approach/write-data-management.mdx
src/includes/upload-dif/native.mdx
src/includes/upload-dif/native.wasm.mdx
src/platforms/common/configuration/index.mdx
src/platforms/common/data-management/debug-files.mdx
src/platforms/common/data-management/event-grouping/index.mdx
src/platforms/common/data-management/event-grouping/sdk-fingerprinting.mdx
src/platforms/common/data-management/sensitive-data/index.mdx
src/platforms/common/enriching-events/breadcrumbs.mdx
src/platforms/common/enriching-events/context.mdx
src/platforms/common/enriching-events/identify-user.mdx
src/platforms/common/enriching-events/index.mdx
src/platforms/common/enriching-events/scopes.mdx
src/platforms/common/enriching-events/tags.mdx
src/platforms/common/enriching-events/user-feedback.mdx
src/platforms/common/usage/index.mdx
src/platforms/native/common/debug-information.mdx
src/platforms/native/guides/wasm/index.mdx

Initial documentation to use wasm with Sentry.

feat(wasm): Add initial docs for WASM

---

src/platforms/node/guides/express/index.mdx

As of https://github.com/getsentry/sentry-javascript/pull/3078 the integration can also take a router instead of an app.

feat(express): Add option of passing router to tracing integration

---

src/platforms/native/guides/ue4/index.mdx

Since symbol status is now visible in the event page, I believe we can remove this.
If this needs to stay, it should be reworded as it's unclear if we're talking about Sentry project or Unreal project here. And what one would find there that would help clarify what needs to be uploaded.

ref(unreal): remove unnecessary note

---

src/wizard/javascript/angular.md
src/wizard/javascript/angularjs.md
src/wizard/javascript/backbone.md
src/wizard/javascript/browser.md
src/wizard/javascript/ember.md
src/wizard/javascript/gatsby.md
src/wizard/javascript/react.md
src/wizard/javascript/vue.md

This tells users to by default enable session health in the JS onboarding wizard.
Eventually, we want to make this the default behaviour but we decided to do this with a major release because it might upset some people if we sneak this into a minor bump.
This will give us some graceful way to get more customers using Release Health for JS.
_Also fixed backbone and angular1 docs._

feat: Add Release Health to wizard

---

src/platforms/native/config.yml

The Native SDK uses snake_case for its function names, but was incorrectly
tagged as "canonical".

fix(native): Switch caseStyle to snake_case

---

src/includes/unset-user/native.mdx
src/platforms/common/enriching-events/identify-user.mdx
src/platforms/native/context.mdx

Removes duplicated information from the separate context documentation for
native and adds docs for `sentry_remove_user`.

fix(native): Update identify-user documentation

---

src/docs/product/integrations/github/index.mdx
src/docs/product/integrations/gitlab/index.mdx

**Stack Trace Linking:**
This feature is an addition to our already existing GH and GitLab integrations, but will only be available for EA. This feature is a little bit of a test in terms of how intuitive it will be for users to set up. We actually have two ways for users to set it up, which I have named **Quick Setup** and **Manual Setup**. This [PR](https://github.com/getsentry/sentry/pull/22329) has a bit more information on that.
The documentation I've added here is for the **Manual Setup**, which users will be directed to if they click an integration in the Setup Modal added in https://github.com/getsentry/sentry/pull/22329, **OR** potentially if they are setting up GH/GitLab for the first time and end up on the configuration settings page. This page will now have both a …

feat(stacktrace-link): Add minimal docs

---

src/includes/configuration/config-intro/javascript.mdx
src/includes/configuration/config-intro/rust.mdx
src/platforms/common/configuration/options.mdx
src/platforms/elixir/configuration/options.mdx
src/platforms/go/common/configuration/options.mdx
src/platforms/java/common/configuration/index.mdx
src/platforms/java/common/legacy/configuration/index.mdx

Adds a missing noun to the description of passing basic options to the init function or method. Whether it is a function or method depends on the platform.
Note that I had to remove the code backticks from descriptions as they are not being rendered by our page grid component:

fix: Correct wording of basic options intro

---

gatsby-ssr.js

```
$ rg --files -t html public/ | xargs du -hsc | rg total
613M    total
```
before it was 1.1GB
see https://github.com/gatsbyjs/gatsby/issues/1526

fix(build): Do not inline bootstrap into every html page

---

src/platforms/native/guides/crashpad/index.mdx

fix(native): Show a stronger warning on crashpad vs native SDK

---

src/includes/getting-started-config/ruby.rack.mdx
src/platforms/ruby/common/configuration/options.mdx
src/wizard/ruby/rack.md

There will be some breaking changes/new config options coming with Ruby SDK's `4.1.0` version. This PR is to keep the documents up-to-date.

Documents update for Ruby SDK 4.1.0

---

src/includes/set-release/apple.mdx

@jan-auer asked for an example in a DM and other SDKs have it too. Therefore I added it.

feat(apple): Add example for default release name

---

src/platforms/common/configuration/releases.mdx

A link from the SDK content to the releases product content has been missing (though the sentence was sadly still there), and the link to setting up needing refreshing due to the refactor.

Add missing links

---

src/platforms/flutter/usage/advanced-usage.mdx

I've also fixed another minor mistake
This was requested in https://github.com/getsentry/sentry-dart/pull/259

Add FlutterError limitations to docs

---

src/platforms/common/configuration/options.mdx

The attach-stacktrace on the options is default on for Android, Apple, and Java. This is now updated for the docs.
@bruno-garcia did we also set the default to `true` for .NET? If so ping me, so I update the PR.

fix: Update attach-stacktrace default

---

src/includes/attachment-max-size/apple.mdx
src/includes/attachment-max-size/java.mdx
src/platforms/common/enriching-events/attachments/index.mdx

Add docs for max attachment size on Apple. This feature is currently
only supported on Apple, but more platforms are going to follow.
Therefore, we hide the feature for other platforms, but already use
PlatformContent.

feat(apple/java): max attachment size

---

src/includes/set-user/native.mdx
src/platforms/common/enriching-events/identify-user.mdx

Documents the special `{{auto}}` value for `user.ip_address` for all SDKs.
Client-side SDKs set this by default, whereas in server-side SDKs this must be
set manually.
Since the Native SDK is used in both contexts, we document `{{auto}}` explicitly
in the code example.
---
---
Fixes https://github.com/getsentry/sentry-docs/issues/2821

fix(native): Document ip_address {{auto}}

---

src/platforms/java/common/configuration/index.mdx

Note - setting `inAppIncludes` and `inAppExcludes` from external configuration has been added in 4.0 which is currently in alpha stage.
This should be merged after https://github.com/getsentry/sentry-java/pull/1145
Fixes #2801

Add `inAppIncludes` and `inAppExcludes` options to Java docs.

---

src/docs/product/error-monitoring/breadcrumbs/index.mdx

It was inconvenient to read about types and not being able to actually look what kind of types are available. This fix it.

Update breadcrumbs docs to include types link

---

src/components/guideGrid.tsx

The platform icons from the 'platformicons' package do not have any
border or drop shadow, but type.scss adds them for any image inside
the 'prose' class, which the guide icons are automatically part of,
since they art part of the main content block.
A similar workaround is already added in platformGrid.tsx, while the
icons in the platform navigation dropdown do not need it as they are
not part of the main content (prose section).

Remove border and drop shadow from platform icons in guide

---

.github/workflows/stale.yml

https://app.asana.com/0/1199602781063150/1198192573081727
- Labels un-triaged issues with `Status: Stale` after three weeks of inactivity.
- Closes issues so labeled after one more week of inactivity.
- Use `Status: Accepted` to hold open indefinitely.

meta: Implement stalebot

---

src/docs/product/alerts-notifications/issue-alerts.mdx

Adding the default trigger "When an event occurs" note to alert triggers session as this question comes up quite frequently in support.

Add default trigger note

---

src/platforms/common/enriching-events/attachments/index.mdx

Specify the valid content types. Brought up in here https://github.com/getsentry/sentry-docs/pull/2826#issuecomment-755500370 and also fixed in the develop docs: https://github.com/getsentry/develop/pull/238

fix: Specify valid content types for attachments

---

.github/workflows/stale.yml

Heads up, @PeloWriter. We're adding another label for stalebot to ignore, to allow holding open an issue without communicating that we've strongly committed to it.

meta: Tell stalebot to ignore `Status: On Hold`

---

src/platforms/common/enriching-events/attachments/index.mdx

The attachments API is going to be stable with sentry-cocoa 6.1.0.
Therefore we can remove the note about the alpha release.
Only merge this PR after sentry-cocoa 6.1.0 is released.

feat(apple): Remove note on beta for attachments

---

src/includes/getting-started-install/rust.mdx
src/platforms/rust/guides/actix-web/index.mdx
src/platforms/rust/index.mdx
src/wizard/rust/index.md

This uses the current release-registry version of the Rust SDK.
It also updates some examples to use Releases, and updates the Actix docs to the current version.

fix: Update docs to the most recent Rust SDK version

---

src/docs/product/data-management-settings/index.mdx
src/platforms/common/data-management/sensitive-data/index.mdx

- Recommend Relay as alternative to either SDK or server-side scrubbing
- Do not give clear recommendation for SDK-scrubbing in product docs --
this entirely depends on your legal/privacy needs. Simply point out
advantages and disadvantages
- Remove duplicated intro to sensitive data in product docs and make
platform page the central starting point, as that's what most things
link (and redirect) to.

ref: Update sensitive data management

---

src/css/_includes/code-blocks.scss

fix(ui): added styles for active tab in code blocks

---

src/includes/unset-user/go.mdx

Add snippet for unset-user in Go

---

src/includes/performance/default-sampling-context-platform/python.mdx
src/includes/performance/default-sampling-context/python.bottle.mdx
src/includes/performance/default-sampling-context/python.django.mdx
src/includes/performance/default-sampling-context/python.falcon.mdx
src/includes/performance/default-sampling-context/python.flask.mdx
src/includes/performance/default-sampling-context/python.pyramid.mdx
src/includes/performance/default-sampling-context/python.tryton.mdx
src/includes/performance/default-sampling-context/python.wsgi.mdx

In particular, this points people to look in `wsgi_environ` for (all the parts of) the request URL.
Fixes https://github.com/getsentry/sentry-python/issues/969.

fix(python): Make default sampling context comments more helpful

---

src/platforms/common/configuration/draining.mdx

`Sentry.close()` is not supported on React Native so this PR sets it as not supported.
One person has tried using it: https://github.com/getsentry/sentry-react-native/issues/1279

fix: Add RN to "Shutdown and Draining" not supported list

---

src/platforms/ruby/common/performance/index.mdx

Just fixing a minor typo in a code example where "transaction" is misspelled.

Fix typo in performance monitoring page

---

src/platforms/common/enriching-events/attachments/index.mdx

The current attachment intro mostly mentions crash reports, but you can attach
them to all types of events.

fix: Attachments intro

---

src/platforms/react-native/sourcemaps.mdx

Latest react-native cli names the bundles as index.android.bundle when building a release. 
I recently faced with a source map issue about this.
I was following the docs but it was inaccurate.

Bundle name change

---

src/platforms/common/performance/index.mdx

Quick fix to make it clear that RN instrumentation is manual only and not automatic yet. This is because the current documentation with references to automatic tracing has confused users such as: https://stackoverflow.com/questions/65750585/sentry-react-native-performance-not-recording-anything

fix: Remove references to auto instrumentation in RN and make clear that it is manual

---

src/docs/product/releases/health/index.mdx

`/product/releases/health/` is already the generated URL. Adding it to `redirect_from` creates an infinite redirect loop when visiting the page using a direct link.
https://user-images.githubusercontent.com/1523305/105028007-c097f600-5a50-11eb-9050-b91fdf12d69a.mp4

fix: Remove /product/releases/health/ redirect

---

src/platforms/apple/common/usage.mdx

Add a point to known limitations to update to 6.x.x for better release
health data for Apple.

feat(apple): Update for better release health data

---

src/docs/product/releases/index.mdx

To help users find their release health info, added a brief explainer to find Release Health via Issue Details or from the Releases home page.

Add navigation information

---

src/platforms/apple/common/usage.mdx

Add a comment about Sentry on-prem minimum version since sentry-cocoa 6.0.0.

feat(apple): Add comment about min on-prem version

---

src/docs/product/cli/releases.mdx

Fixes a minor typo where "artifacts" is misspelled.

docs(sentry-cli): fix typo on releases page

---

src/platforms/javascript/guides/wasm/index.mdx

_not sure_ if the example should be there, but some people may want to learn about Wasm and try it out I guess(?).

docs(sentry-javascript): Add @sentry/wasm page

---

src/platforms/common/performance/capturing/automatic.mdx

React-Native specific override for performance auto instrumentation docs.
Note that this does not mention the configuration options for the routing instrumentations such as `shouldSendTransaction` as the API could change to use `beforeNavigate` in a following version following https://github.com/getsentry/sentry-javascript/pull/3192.

feat(react-native): React Native auto performance docs

---

src/components/banner.tsx
src/components/basePage.tsx
src/components/layout.tsx
src/css/_includes/banner.scss
src/css/_includes/index.scss
src/css/_includes/sidebar.scss
src/css/screen.scss
src/pages/index.tsx

This adds a dismissible banner that allows for promoting things, in this case, an upcoming work shop. 
Right now it looks like this:
I don't love this, but due to the css layout and the way jest is configured, this is about the only way to get something in the app by the deadline. With some refactoring of things, we could do more of a traditional banner, but that will require a surprising amount of effort.

Add a promo banner

---

src/docs/product/integrations/azure-devops/index.mdx
src/docs/product/integrations/jira/index.mdx

Automatic issue creation is only available on the new Business plans, so we want to make that very clear in the documentation.

fix(ticket rules): Indicate feature availability by plan

---

src/platforms/common/configuration/options.mdx

During the docs migration it seems like dotnet's options went missing

add missing dotnet options

---

src/includes/configuration/auto-session-tracking/javascript.mdx
src/platforms/common/configuration/options.mdx
src/wizard/javascript/angular.md
src/wizard/javascript/angularjs.md
src/wizard/javascript/backbone.md
src/wizard/javascript/browser.md
src/wizard/javascript/ember.md
src/wizard/javascript/gatsby.md
src/wizard/javascript/index.md
src/wizard/javascript/react.md
src/wizard/javascript/vue.md

Since version `6`, we have it enabled by default and therefore we don't need this anymore.

feat: Remove autoSession from Wizard

---

src/platforms/javascript/guides/react/components/errorboundary.mdx

The docs previously showed passing a component to the fallback prop. However the fallback prop takes a React _element_ not a React _component_:
https://github.com/getsentry/sentry-javascript/blob/a833f0ec0a186f0672a536ea8f7d3b129a71a4fe/packages/react/src/errorboundary.tsx#L111-L121
You can additionally verify that by checking the TypeScript types:
https://github.com/getsentry/sentry-javascript/blob/a833f0ec0a186f0672a536ea8f7d3b129a71a4fe/packages/react/src/errorboundary.tsx#L30
Since the difference between React elements and React components can be confusing, here's [a link to the React glossary for more information](https://reactjs.org/docs/glossary.html#elements).

fix(react): Fix docs for ErrorBoundary fallback prop

---

src/platforms/php/common/performance.mdx

This is to "fix" copy pasta errors where users paste in the examples but they won't work because of missing imports or being inside their own namespace causing unneeded confusion.
Fixes getsentry/sentry-php#1159.
/cc @HazAT

Prefix PHP tracing examples with namespaces

---

src/platforms/common/data-management/debug-files/symbol-servers.mdx

We support the unified format but we did not yet document it. We also support `debuginfod` but I figured given the lack of adoption at the moment we can leave it out for the moment.
Unified however is what our symsorter produces and particularly open source on-prem customers have been using it.

feat: Document unified format

---

src/includes/before-breadcrumb/xamarin.mdx
src/includes/configuration/before-send/xamarin.mdx
src/includes/configuration/config-intro/xamarin.mdx
src/includes/configuration/drain-example/xamarin.mdx
src/includes/getting-started-config/xamarin.mdx
src/includes/getting-started-verify/xamarin.mdx
src/includes/set-environment/xamarin.mdx
src/includes/set-fingerprint/basic/xamarin.mdx
src/includes/set-fingerprint/database-connection/xamarin.mdx
src/includes/set-fingerprint/rpc/xamarin.mdx
src/includes/set-fingerprint/static/xamarin.mdx
src/includes/set-release/xamarin.mdx
src/platforms/dotnet/guides/xamarin/config.yml
src/platforms/dotnet/guides/xamarin/ignoring-exceptions.mdx
src/platforms/dotnet/guides/xamarin/index.mdx

The following pull request adds to sentry-docs the Xamarin and Xamarin forms doc page.

feat: Xamarin docs

---

src/wizard/dotnet/xamarin.md

The following pull request adds to the doc a Wizard for Xamarin Forms.

feat: Xamarin Wizard

---

src/platforms/common/configuration/options.mdx

I have Sentry SDK logging enabled in Prod, with `info`. Helps me see what the SDK does in logs.
Dart, .NET and Java have it.

document diagnostic logger

---

src/wizard/dotnet/aspnet.md

An ASP.NET Classic wizard for the current version (which requires only `Sentry`).
#2669 will introduce docsonce the SDK v3 is released. That'll require installing `Sentry.AspNet` so this wizard install command will need to change then.
We're over a month away though.

aspnet wizard

---

src/platforms/elixir/index.mdx

Just noticed a typo while reading the docs.

Fix: remove extra "crashed"

---

src/platforms/javascript/guides/vue/index.mdx

Also applies auto-formatting to the Vue doc. See the first commit for the actual
change.

fix(vue): Render a correct DSN placeholder

---

src/wizard/javascript/angularjs.md
src/wizard/javascript/backbone.md
src/wizard/javascript/browser.md
src/wizard/javascript/ember.md
src/wizard/javascript/index.md
src/wizard/javascript/react.md
src/wizard/javascript/vue.md
src/wizard/node/awslambda.md
src/wizard/node/gcpfunctions.md

```
yarn prettier:fix src/wizard/javascript/* src/wizard/node/*
```
Inspired by #2982 to apply standard formatting to other JavaScript snippets.

chore: Reformat JavaScript code with prettier

---

src/css/_includes/global-header.scss

Based on https://css-tricks.com/hash-tag-links-padding/
Fixes https://github.com/getsentry/sentry-docs/issues/2685

Fix: push anchor headers below fixed top bar

---

src/css/_includes/global-header.scss

Reverts getsentry/sentry-docs#2987
The fix introduced a bug misaligning the anchor link and header text. The link needs to be shifted down as well, will look into it another time.

Revert "Fix: push anchor headers below fixed top bar"

---

src/includes/performance/enable-tracing/react-native.mdx
src/includes/performance/tracingOrigins-example/react-native.mdx
src/platforms/common/performance/index.mdx
src/platforms/react-native/performance/included-instrumentation.mdx

This PR includes:
- Documentation on the new `beforeNavigate` option and the typing if they use the React Navigation instrumentation.
- Note that at least 2.2.0 is required for auto performance.
- Fixes the `tracesOrigins` example not being RN-specific.
- Expands a little on custom routing instrumentation.
closes #2995

feat: Docs for GA React Native Performance

---

src/platforms/apple/common/usage.mdx

Add a note to known limitations on how to use Carthage for Apple Silicon. There was an open issue for that. See https://github.com/getsentry/sentry-cocoa/issues/866.

feat(apple): Note on Carthage for Apple Silicon

---

src/platforms/javascript/guides/react/components/errorboundary.mdx

Remove the same option mentioned twice in order to avoid any confusion.

Remove redundant option onUnmount

---

src/platforms/common/configuration/options.mdx

`.sentryclirc` was never a thing in `@sentry/node` nor any other SDK. It works only in `sentry-cli`.
Mentioning sentry-cli here is also kinda redundant.

fix: Remove sentryclirc and sentry-cli mention from Node options docs

---

src/includes/getting-started-install/native.mdx

On Windows it builds in Debug mode by default.
See also:
#439
#442

fix(native): Suggest release build

---

src/includes/performance/beforeNavigate-example/javascript.mdx
src/includes/performance/group-transaction-example/javascript.mdx

As `replaceAll` generally isn't supported on older browsers. A good alternative is to just use the `replace` function.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll

docs(sentry-javascript): Use replace instead of replaceAll

---

src/gatsby/sourceNodes/packageRegistryNodes.ts

This fixes `master`
There is a bug in the registry / craft
that now added empty files entries without a checksum.
This makes the checksum check optional.

fix: Make checksum check optional

---

src/docs/product/accounts/sso/azure-sso.mdx

Correcting the relay state URL. The screenshot still needs to be updated, unfortunately, I do not have access to an Azure account to get an updated one.

Adding organisation slug to relay state URL

---

package.json
yarn.lock

This is mostly to upgrade `node-forge` which has a security vulnerability in earlier versions. That said the newest version of Gatsby brings in many bug fixes and some performance upgrades, especially for development.

upgrade(gatsby): Upgrades gatsby & gatsby-cli to latest stable

---

src/includes/attachment-init-with-bytes/dotnet.mdx
src/includes/attachment-init-with-path/dotnet.mdx
src/includes/attachment-upload/dotnet.mdx
src/includes/performance/custom-sampling-context/dotnet.mdx
src/includes/with-scope/dotnet.mdx
src/platforms/common/performance/index.mdx

These are no longer needed in latest version.

Remove 'using Sentry.Protocol' from .NET docs

---

src/includes/performance/traces-sampler-as-sampler/dotnet.mdx

Related: https://github.com/getsentry/sentry-dotnet/issues/799

Fix a typo in .NET docs

---

src/platforms/react-native/hermes.mdx

Fix inconsistency between incorrect link text version (1.5.1) and link target version (1.51.1)

Fix @sentry/cli version inconsistency in hermes.mdx

---

src/docs/product/security/ssl.mdx

It is what it is. Giving some users more of a sunset period than initially required.

fix(tls): Bump TLSv1/1.1 sunset to March.

---

src/platforms/flutter/index.mdx

We're updating the guide to reflect the latest version so it no longer adds value linking there.

Remove link to Flutter guide

---

src/docs/product/sentry-basics/search/index.mdx

Adding an assigned_or_suggested section as well as me_or_none to the assigned section.
In the future, we may want to elaborate on suggested assignees in another section and link to it from here.

Add `assigned_or_suggested` syntax to Search docs

---

src/includes/performance/configure-sample-rate/java.spring-boot.mdx
src/includes/performance/configure-sample-rate/java.spring.mdx
src/includes/performance/connect-errors-spans/java.mdx
src/includes/performance/traces-sampler-as-sampler/java.spring.mdx
src/platforms/common/performance/index.mdx

- on the top of Java performance added links to Spring and Spring Boot guides
- updated sampling function example in Spring & Spring Boot to have already a request taken out from the context.
Replaces https://github.com/getsentry/sentry-docs/pull/2974 as it was easier to start from scratch than resolve conflicts.

Make Java docs less confusing and easier to follow.

---

src/docs/product/alerts-notifications/issue-alerts.mdx
src/docs/product/alerts-notifications/metric-alerts.mdx
src/docs/product/sentry-basics/guides/alert-notifications/issue-alerts.mdx
src/docs/product/sentry-basics/guides/alert-notifications/metric-alerts.mdx

Changing every instance of `Grant Members Alerts Write` to `Let Members Create and Edit Alerts` because I renamed it in the app to make it easier to read: https://github.com/getsentry/sentry/pull/23800

fix(copy): updated path to match new copy in the app

---

src/docs/product/sentry-basics/guides/error-tracing/index.mdx

access_json was defined but not actually used.

error-tracing: use the defined log_format

---

src/docs/product/accounts/quotas/index.mdx

Further clarifying that spike protection currently applies only to error events.

Clarify spike protection applies to error events

---

src/wizard/unity/index.md

In the Unity wizard, I click 3 times to get the line selected (note **no spaces at the end**):
Paste it in Unity:
I just get an error on the console:
Basically no indication of what went wrong.
In reality, there's a space at the end of the line, and Unity can't handle it (nor it says that's what's wrong in the error message):
Hit backspace and:
Adding now works as expected.

Note about Unity UPM installation gotcha

---

src/platforms/dotnet/guides/xamarin/index.mdx
src/wizard/dotnet/xamarin.md

This PR aims to include the naming change of DisableXamarinFormsCache to DisableOfflineCaching, additionally, the version is no longer hardcoded.

Update Xamarin docs.

---

src/platforms/python/guides/rq/index.mdx

Extend docs with tips from https://github.com/getsentry/sentry-python/issues/935 and https://github.com/getsentry/sentry-python/issues/907 to initialise Sentry once per (Flask) app and import it in `rq worker`'s settings file. 
Calling `sentry_sdk.init` in the worker's configuration per the  current docs (https://docs.sentry.io/platforms/python/guides/rq/) results in undelivered messages and exceptions.

RqIntegration documentation: add tip to call sentry_sdk.init once in (Flask) app

---

src/platforms/common/enriching-events/user-feedback.mdx

Until we release Unity on top of .NET, this doc needs to be hiden

userfeedback not supported for unity.lite

---

src/platforms/python/common/performance/included-instrumentation.mdx

auto_enabling_integrations was removed in 0.19.0 according to [0].
@silent1mezzo and I encountered some confusion in this area, since the documentation gave us the impression that the listed operations are always instrumented. In fact, they are only instrumented within existing transactions, and one isn't created automatically.
[0] https://github.com/getsentry/sentry-python/blob/master/CHANGELOG.md#0190

ref: del auto_enabling, explain non-included

---

src/includes/performance/add-spans-example/java.mdx
src/includes/performance/enable-manual-instrumentation/java.mdx
src/includes/performance/retrieve-transaction/java.mdx

We either need to capture explicitly, or rethrow the exception to the caller

fix(java): rethrow exception

---

src/platforms/common/data-management/debug-files/symbol-servers.mdx

The casing rules for symstore were not correct. This mistake has been here from
the beginning, and symbolicator has always applied the now described mixed
casing rules.

fix(native): Describe correct casing of the SymStore layout

---

src/includes/getting-started-config/javascript.mdx

Change getting started step to include a static release name, as without some JS build tool, it wouldn't work.

ref: Set javascript release value

---

src/platforms/common/performance/index.mdx

The verification step for performance was causing confusion. It made it seem as if transactions would be simply sent, when in fact for some SDKs, you need to first use custom instrumentation to start and stop a transaction to test. This fix modifies the verification step appropriate to the instrumentation supported in each SDK.

Update performance monitoring verification step

---

src/docs/product/sentry-basics/dsn-explainer.mdx

- "the SDK will just not send any events" => "will not send data"
The important part here is removing "just". The SDK may do/ not do other things as well, such as skipping initialization of certain internal state, on the discretion of the SDK implementation.
- Remove `Secret Key = secret`: is has been removed from the example and stayed here probably by accident
- Remove reference to `/store/` endpoint. This is not necessarily useful for users and can be confusing since SDKs talk to different endpoints, `/store/` being just one of them.
Closes #1635

Clarify DSN explainer

---

package.json
src/components/markdown.tsx
src/css/_includes/code-blocks.scss
src/css/screen.scss
yarn.lock

This replaces the `prism-tomorrow` theme with a custom Sentry-branded theme.

ref(ui): use prism-sentry theme for code snippets

---

src/css/_includes/global-header.scss

The new prism theme was setting z-index 1 on code blocks for whatever
reason

ref(css): Give global-header a larger z-index

---

src/platforms/node/guides/express/performance/index.mdx

Express was relying on the common content, which of course doesn't have anything express-specific. This makes a separate page so that that content can be included.

fix(express): Add express integration to code snippet

---

src/includes/performance/set-transaction-current-scope/java.mdx
src/platforms/common/performance/custom-instrumentation.mdx

Fixes https://github.com/getsentry/sentry-docs/issues/3016

Java: how to set a transaction to the current Scope.

---

src/docs/product/sentry-basics/dsn-explainer.mdx
src/platforms/common/configuration/options.mdx

PR https://github.com/getsentry/sentry-docs/pull/1723 raised some good conversation, which is captured here (I've closed that PR with a pointer to this one as the branch was very stale)

Add DSN utilization

---

src/platforms/common/usage/index.mdx

The capture exception function should be formatted appropriately for the
corresponding platform.

docs(usage): Format capture exception for platform

---

src/includes/configuration/sample-rate/java.spring-boot.mdx

The config for sentry.sample-rate was invalid for yaml form.

correct application.yaml for sample-rate config

---

src/platforms/common/configuration/options.mdx

We added this for Apple recently, see
https://github.com/getsentry/sentry-cocoa/pull/923.
Only merge when sentry-cocoa 6.1.5 is released.

feat(apple): Enable sendDefaultPii

---

src/platforms/node/common/performance/index.mdx

Initializing tracing is a side effect of the import, so we need it, even if we don't use it directly.

fix(performance): Add note about unused `@sentry/tracing` import

---

src/includes/getting-started-install/android.mdx
src/includes/getting-started-install/java.log4j2.mdx
src/includes/getting-started-install/java.logback.mdx
src/includes/getting-started-install/java.mdx
src/includes/getting-started-install/java.spring-boot.mdx
src/includes/getting-started-install/java.spring.mdx
src/includes/performance/configure-sample-rate/java.spring-boot.mdx
src/includes/performance/configure-sample-rate/java.spring.mdx
src/includes/performance/enable-manual-instrumentation/java.spring-boot.mdx
src/includes/performance/enable-manual-instrumentation/java.spring.mdx
src/includes/performance/set-transaction-current-scope/java.mdx
src/platforms/android/integrations/timber.mdx
src/platforms/android/usage/advanced-usage.mdx
src/platforms/java/common/configuration/transport.mdx
src/platforms/java/guides/spring-boot/logging-frameworks.mdx
src/platforms/java/usage.mdx

Java: bump dependency versions to 4.2.0

---

src/platforms/common/data-management/sensitive-data/index.mdx

In this issue https://github.com/getsentry/sentry-docs/issues/3153, we surfaced a broken link. This PR fixes it.

Update broken link in sensitive Data 

---

src/docs/product/cli/dif.mdx
src/platforms/common/data-management/debug-files/index.mdx

Fix #3046
We can't completely remove the support of `debug files` for ProGuard because we still need to support debug files for NDK.
Also, the debug files page tell how to use sentry-cli manually, hence this small change is a quick win instead of moving or duplicating the content around.

Fix: special case Proguard mapping location

---

src/includes/configuration/drain-example/apple.mdx

See Android https://docs.sentry.io/platforms/android/configuration/draining/

Fix: Add missing Apple draining example

---

src/platforms/common/enriching-events/context.mdx

Not all SDKs truncate; this update makes that more clear.

Fix truncation statement

---

src/platforms/javascript/common/install/lazy-load-sentry.mdx

A substantial rewrite of the JS Loader page, with the aim of clarifying and being more explicit about what each option does.

ref(JS): Rework JS Loader page

---

src/wizard/node/awslambda.md

Adding the comment telling users to adjust traces sample rate in production. This comment was present only in the performance pages, not on the instrumentation guide in the Sentry web ui.

Adding trace rate comment for prod deploy

---

src/platforms/node/guides/aws-lambda/index.mdx

Adding the comment telling users to adjust traces sample rate in production. This comment was present only in the performance pages, not on the getting started page.

Add tracesSampleRate comment for prod deploys

---

src/platforms/native/guides/minidumps/index.mdx

I founded a typo `yout`, it need to be corrected to `you` 😊

fix a typo in minidump doc

---

src/docs/product/accounts/membership.mdx

These asterisks are either a formatting issue or linked to some long lost footnotes that are no longer on the page. This PR removes them

fix(membership): Remove gratuitous asterisks

---

src/docs/support/index.mdx

Fixed broken links to Help Center from docs Support page.

fixing broken links to help center

---

src/includes/configuration/offline/javascript.mdx
src/platforms/javascript/common/configuration/integrations/plugin.mdx

See https://github.com/getsentry/sentry-javascript/pull/2778
Remove backticks from plugin.mdx's description; PageGrid doesn't render them as monospace, so they appear as literals in the [index page](https://docs.sentry.io/platforms/javascript/configuration/integrations/), and the default.mdx description doesn't use them for its class names.

Add documentation for Offline integration

---

src/includes/set-user/dart.mdx

The documentation currently suggests that creating a user with `User(email: 'jane.doe@example.com')` is enough, but [the implementation refuses](https://github.com/getsentry/sentry-dart/blob/dd380f283576cbf816c19b358aacf9f76bf4c963/dart/lib/src/protocol/user.dart#L35) and [asks explicitly](https://github.com/getsentry/sentry-dart/blob/dd380f283576cbf816c19b358aacf9f76bf4c963/dart/lib/src/protocol/user.dart#L28) for either an ip or an id.
```dart
class User {
...
/// At a minimum you must set an [id] or an [ipAddress].
assert(id != null || ipAddress != null)
...
}
````
So adding an ID in the example makes it easy for the user to copy/paste some code that will work on the first try.
```dart
User(id: 1234, email: 'jane.doe@example.com')
```
Edit: [Direct …

Update the set-user scope example in Dart

---

src/docs/clients/javascript/usage.mdx
src/docs/product/accounts/quotas/index.mdx

Size limits are an implementation detail at this point, and we're describing them at multiple places. The best place to list the actual size limits is in the develop docs. Quota and platform docs (especially the legacy RavenJS documentation) should be unspecific and link to those places, instead.
Requires https://github.com/getsentry/develop/pull/276
Fixes #3094

fix: Clarify payload size limits and link to develop

---

src/includes/getting-started-install/react-native.mdx

RN >= does not need to run the link step

fix: Split react native install code blocks

---

src/platforms/dotnet/guides/nlog/index.mdx

Release 3.x of the .NET SDK changes DSN to take a string instead of object - update NLog docs accordingly

Fix NLog DSN Constructor documentation

---

src/platforms/apple/common/dsym.mdx

`upload_symbols_to_sentry` doesn't exist, it's called `sentry_upload_dsym`
ref: https://github.com/getsentry/sentry-fastlane-plugin#uploading-symbolication-files

fix: Use correct fastlane command

---

src/platforms/node/guides/aws-lambda/index.mdx

Hi,
This fixes a small typo to make the use of "its" possessive, instead of a contraction.

fix: Correct a small typo

---

src/platforms/index.mdx

It's WordPress not Wordpress (sorry for the nitpicky fix).

Fix WordPress casing

---

src/platforms/javascript/common/sourcemaps/tools/webpack.mdx

Webpack by default generates file into dist folder https://webpack.js.org/configuration/#:~:text=default:%20dist

Update webpack.mdx with default webpack generated file location

---

src/components/basePage.tsx
src/components/guideGrid.tsx
src/components/hooks/usePlatform.tsx
src/components/platformSidebar.tsx
src/components/tableOfContents.tsx

At @PeloWriter's behest, I've moved "Other guides" from the left sidebar, to the right.
We had discussed also removing the list from the body of the guides, but that is a potentially dogmatic change that is easy enough for the content team to handle themselves if they would like to do it.
This PR is dependent on #3249 where I had to fix a bug to make `usePlatform` work.

Feat: move other guides to sidebar

---

src/components/markdown.tsx
src/components/video.tsx

At @PeloWriter's behest, this adds video components to MDX docs. There are currently no instances of them in use.
```html
<VimeoEmbed id="375329202" />
<YouTubeEmbed id="cp2U0E3dpO4" />
```

Add video components

---

src/platforms/common/index.mdx

We are adjusting the Getting Started page to ensure users can access related guides more efficiently, thus they don't need to be listed only on the primary platform page.

Move framework list off common as it's in the RH sidebar

---

src/platforms/react-native/migration.mdx
src/platforms/react-native/performance/included-instrumentation.mdx

1. Fixes the routing instrumentation initialization method. Previous method of initialization caused issues: https://github.com/getsentry/sentry-react-native/issues/1361
2. Documentation on the new configuration option: https://github.com/getsentry/sentry-react-native/pull/1370
3. Examples of `Profiler` and `useProfiler`. https://github.com/getsentry/sentry-react-native/pull/1372
Maybe we should document this over in the React package too? Only `withProfiler` is documented.

feat: Update RN included instrumentation performance docs

---

src/platforms/common/configuration/filtering.mdx

Hide hins in the filtering section because the Apple SDK doesn't support them.

fix(apple): Hide hints in configuration / filtering

---

.github/workflows/stale.yml

This PR adds the 2 new triage labels to replace old ones:
1. `Status: Accepted` -> `Status: In Progress`
2. `Status: On Hold` -> `Status: Backlog`

ci(stalebot): Add new triage labels

---

src/docs/clients/cocoa/dsym.mdx
src/platforms/apple/common/dsym.mdx

Copying the bash code for uploading dSYMs via the copy button
removed the leading $. This is fixed now by using text instead.
Fixes GH-2893

fix(apple): Copy bash code missing character

---

src/includes/configuration/before-send/ruby.mdx

NOTE: if you don't do this, it will bomb when trying to filter sensitive data in contexts where this is not set (e.g. cron scripts running in your app env, active job processing)

Use safe navigation operator in ruby example config

---

src/components/codeContext.tsx
src/includes/configure-scope/rust.mdx

The initial typo was found on [this page](https://docs.sentry.io/platforms/javascript/sourcemaps/) of the documentation.
After searching through the repository I found another typo, also "exmaple".
This PR fixes both typo's.

Fix "exmaple" typo's in 2 locations

---

src/platforms/common/performance/index.mdx

If you don't set a sample rate (or use the `tracesSampler`, then in fact _no_ transactions will be sent, because tracing will be off entirely. That's clearly not what we mean.

fix(tracing): Fix wording about sample rate

---

src/docs/product/dashboards/index.mdx

Dashboards is now GA; EA note is no longer applicable.

Remove EA note

---

src/platforms/apple/common/configuration/integrations/default.mdx

The SentryAutoSessionTrackingIntegration was missing in the list of
integrations. This is fixed now.
Fixes GH-3276

feat(apple): Add AutoSessionTrackingIntegration

---

src/includes/set-user/dart.mdx

This is how the set-user scope example looks right now:
```dart
import 'package:sentry/sentry.dart';
Sentry.configureScope(
(scope) => scope.user = User(id: 1234, email: 'jane.doe@example.com'),
);
```
But `User.id` is a String, so there are missing quotation marks around `1234`.
How it should look:
```dart
import 'package:sentry/sentry.dart';
Sentry.configureScope(
(scope) => scope.user = User(id: "1234", email: 'jane.doe@example.com'),
);
```
#3244 may be related.

Fix the set-user scope example in Dart

---

src/platforms/apple/common/configuration/out-of-memory.mdx

fix(apple): Remove typo dot in OOM

---

src/includes/configuration/before-send/ruby.mdx

Users can filter the entire event payload with Rails' parameter filter, which would make things a lot simpler.

Simplify Ruby's before_send example

---

src/docs/product/accounts/sso/azure-sso.mdx

Using **bold** instead of `code` is better to indicate action. Example:
**Org Settings > Auth** is so much clearer/obvious than `Get metadata`.

ref(azure): Change usage of bold, add final step for successful login

---

src/platforms/common/configuration/options.mdx

We are going to enable Apple once 7.0.0 GA is released. I added this to https://github.com/getsentry/sentry-docs/issues/3307 to not forget about it.
Fixes GH-2879

feat: Add MaxCacheItems to basic options

---

src/includes/capture-error/native.mdx

https://github.com/getsentry/sentry-dart/issues/386
Android NDK requires the exception to be a `values` list, the protocol is flexible enough but we don't parse it like this on Android (relying on Gson).

Fix sentry-native capture exception with values list

---

src/components/hooks/__tests__/usePlatform.test.js

The bug was fixed by ca52c4269f5, this just adds a test.

Add test for usePlatform() when specifying an explicit platform

---

src/platforms/native/guides/breakpad/index.mdx
src/platforms/native/guides/minidumps/index.mdx

Use same formatting and similar language.
The references to the Apple and Electron SDKs in the minidump docs
have been removed, as the link points to the root of the native
platform docs, which in turn links to all the guides, and alternate
SDKs. This gives a more consistent flow than duplicating the content
at multiple levels (resulting in slight differences over time due to
bitrot).

Align notes about using standalone crash reporting backends

---

src/platforms/common/index.mdx

We moved the frameworks off the primary list into the RH sidebar to make space for the feature overview. User feedback is that we need a more aggressive pointer to the list. This note addition is a compromise to enable surfacing of the guides more aggressively while preserving vertical space on the page.

Add note to look for frameworks

---

src/platforms/common/index.mdx

The note would end up in in guides as well due to the missing
noGuides attribute.
The PlaformSection was also excluding more than the guide redirection,
causing sub-guides to lose content. If we want to do this the change
should probably happen along with a followup to add it back to the
sub-guides unless they explicitly don't want that content.
The redirect is also now a green note, instead of a warning. Warnings
should be reserved for very extraordinary cases.

Fix redirect from platform docs to specific guides

---

src/platforms/common/index.mdx

Fixes https://github.com/getsentry/sentry-javascript/issues/3378

docs(js): Add note regarding browser devtools not triggering errors

---

src/platforms/dotnet/index.mdx

This isn't relevant since we mult-itargeted netstandard2.0 and net461

ref: remove dotnet 4.7 advise

---

src/includes/getting-started-install/react-native.mdx

`bundleRelease` are famous for android build nowadays.

docs: update react-native.mdx

---

src/platforms/dotnet/migration.mdx

@PeloWriter do you think it would be possible to create a Migration section and add articles there? For example:
```
-- .NET
+-- Migration
+-- From SharpRaven to SentrySdk
+-- From SentrySdk v2.x to v3.0
```
cc @bruno-garcia

.NET: migration from SharpRaven

---

src/platforms/common/configuration/index.mdx
src/platforms/common/configuration/sampling.mdx
src/platforms/common/performance/index.mdx

Update the performance index page so that Unity content displays. A later PR will address the `init` code sample issue.

Unity: Enable performance content

---

src/docs/product/integrations/index.mdx

To make it clearer on what we support v not support on each integration.

fix(integrations): Separate out metric alerts v issue alerts

---

src/includes/getting-started-install/unity.mdx

Bump to latest unity lite.
Note: The include and common content needs to be moved to the new Unity SDK, which uses release registry for bumping:
Tracked on: https://github.com/getsentry/sentry-docs/issues/3407

Unity lite bump

---

src/includes/performance/default-sampling-context/python.bottle.mdx
src/includes/performance/default-sampling-context/python.django.mdx
src/includes/performance/default-sampling-context/python.falcon.mdx
src/includes/performance/default-sampling-context/python.flask.mdx
src/includes/performance/default-sampling-context/python.pyramid.mdx
src/includes/performance/default-sampling-context/python.tryton.mdx

This links to the spec for the `wsgi` `environ` object, so people know exactly what's in the data they're being passed when running a `traces_sampler` in the Python SDK.

feat(python): Add link to `environ` object docs to `wsgi` transaction sampling includes

---

src/platforms/ruby/common/migration.mdx

This PR fixes an example code in the migration guide for Ruby to make the behaviors of the before code and the after code same.

Fix migration guides to make the behaviors of two codes same

---

src/docs/product/integrations/integration-platform/index.mdx

Docs PR to reflect the changes made in https://github.com/getsentry/sentry/pull/25458. The two changes are:
* Make it explicit that permissions are scoped to the organization, you can't limit the integration to only have access to certain projects/teams within an integration (at least for now). 
* Mention that Managers and Owners are the ones that can create the internal or public integrations.

ref(integration-platform): Update permissions language

---

src/docs/product/integrations/github/index.mdx
src/docs/product/integrations/gitlab/index.mdx

Stack trace linking is no longer in EA, so we should have removed the note

ref(stacktrace-link): Remove EA note

---

src/includes/capture-error/javascript ember.mdx
src/includes/capture-error/javascript.angular.mdx
src/includes/capture-error/javascript.cordova.mdx
src/includes/capture-error/javascript.gatsby.mdx
src/includes/capture-error/javascript.nextjs.mdx
src/includes/capture-error/javascript.react.mdx
src/includes/capture-error/javascript.vue.mdx

In the nextjs SDK, the happy path uses `sentry-wizard` to create config files and pre-fill them with `Sentry.init()` calls. For this reason, we don't show those calls on the Getting Started page (they can be found on the Manual Setup page, to which we link multiple times). We also don't show any `Sentry.captureException()` calls, as those appear on the Manual Usage page, to which we also link multiple times.
As a result of all this, there's no opportunity/reason to include the import line (`import * as Sentry from @sentry/nextjs`) anywhere on that page. It's included on the Manual Setup page, but up until how hasn't been included on the Manual Usage page. As Manual Usage is a logical next stop after Getting Started, it's important to include the import there, since that may be the first …

fix(nextjs): Add import to manual usage snippet

---

src/platforms/javascript/common/install/index.mdx

The "Installation Methods" page only applies to the browser SDK (not any of the framework SDKs), because it's the only one we serve from a CDN and the only one we have a loader for. This PR hides it from all of the JS guides which inherit from browser, since it doesn't apply to them.

fix(JS): Hide install link everywhere but browser

---

src/includes/getting-started-config/javascript.nextjs.mdx
src/platforms/javascript/common/sourcemaps/tools/webpack.mdx
src/platforms/javascript/guides/nextjs/manual-setup.mdx
src/platforms/javascript/guides/nextjs/manual-setup/index.mdx

Now that the nextjs SDK has been released, we've gotten some good feedback from folks trying to set it up using the docs. This addresses a few of the points raised, as do https://github.com/getsentry/sentry-docs/pull/3433 and https://github.com/getsentry/sentry-docs/pull/3434.
Changes in this PR:
- Remove unnecessary intermediate page between Getting Started and Manual Setup pages
- Simplify code snippets on Manual Setup page, as option of using the env variables is mentioned below
- Rework the Configuration section of Getting Started, to link to:
- examples of the wizard's created files
-  docs on `Sentry.init()` options and setting global context (as those are both things they'll need to do in the created files)
- manual usage instructions

fix(nextjs): Post-release cleanup

---

src/includes/set-context/dart.mdx
src/includes/set-context/dotnet.mdx
src/includes/set-context/go.mdx
src/includes/set-context/php.mdx
src/includes/set-context/ruby.mdx
src/includes/set-context/rust.mdx

Fixes #3448 (fixes the Go example, and additionally other platforms not listed in the issue).
Note: the Java/Kotlin example is left for another pass.

fix: setContext examples in multiple platforms

---

src/platforms/javascript/guides/gatsby/index.mdx

The defaulting rules changed in https://github.com/getsentry/sentry-javascript/commit/cb66fa46dccc6fc7d7edd906284f3bf10eff5c39.
Fixes #3360.

fix: Update default release for Vercel

---

src/platforms/common/configuration/options.mdx

Currently leaking markdown in [`allowUrls`](https://docs.sentry.io/platforms/javascript/configuration/options/#allow-urls):

Clean up URL in JS docs - allowUrls

---

src/includes/configuration/auto-session-tracking/native.mdx
src/includes/configuration/drain-example/native.mdx
src/includes/getting-started-config/native.mdx
src/includes/getting-started-config/native.qt.mdx
src/wizard/native/index.md
src/wizard/native/qt.md

A soon-to-be-released version of native renames `sentry_shutdown` to `sentry_close` so make sure the docs reflect that.

ref: Rename sentry_shutdown

---

src/platforms/apple/common/migration.mdx

Only merge once 7.0.0 of sentry-cocoa is released.

feat(apple): Migration guide for 7.x.x

---

src/includes/getting-started-config/javascript.nextjs.mdx
src/includes/getting-started-verify/javascript.nextjs.mdx

This updates the next.js docs to tell our users they need to wrap API calls manually.

feat: Ref update next.js config

---

src/includes/getting-started-primer/javascript.nextjs.mdx

[We no longer rely on the nextjs plugin system](https://github.com/getsentry/sentry-javascript/pull/3462). This updates the warning about it to a) remove mention of said system, and b) make it sound a little less dire while still letting people know that things aren't entirely stable yet. H/t to @PeloWriter for the wording.

fix(nextjs): Tone down beta note

---

src/platforms/ruby/common/configuration/options.mdx

Without wrapping with array it gives the exception:
```
.rvm/gems/ruby-2.6.6/gems/sentry-rails-4.3.2/lib/sentry/rails/railtie.rb:66:in `inject_breadcrumbs_logger': undefined method `include?' for :sentry_logger:Symbol (NoMethodError)
```

Wrong argument format for breadcrumbs_logger

---

src/docs/contributing/approach/product-docs/index.mdx
src/docs/contributing/approach/product-docs/write-index.mdx
src/docs/contributing/approach/sdk-docs/common_content.mdx
src/docs/contributing/approach/sdk-docs/index.mdx
src/docs/contributing/approach/sdk-docs/write-configuration.mdx
src/docs/contributing/approach/sdk-docs/write-data-management.mdx
src/docs/contributing/approach/sdk-docs/write-enriching-events.mdx
src/docs/contributing/approach/sdk-docs/write-getting-started.mdx
src/docs/contributing/approach/sdk-docs/write-performance.mdx
src/docs/contributing/approach/sdk-docs/write-usage.mdx

Add How to Write - Index Pages for product in contributor docs
Restructure Approach section to fit new Product Docs section

Add How to Write - Index Pages in contributor docs

---

src/css/_includes/type.scss

Visible when the browser/page width is 1280px.

fix(ui): Fix content reflow on hover

---

src/includes/getting-started-primer/javascript.nextjs.mdx

Currently, the minimum Next.js supported version for the Next.js SDK is `10.0.0`; but this was missing in the docs. This PR adds it.

ref(nextjs): Add minimum Next.js supported version

---

src/platforms/common/configuration/draining.mdx

The PHP transport is synchronous, that means all requests to Sentry always go out before the PHP process ends.
In short, it's never necessary to "drain" the SDK transport by calling "flush" like in other SDKs.
This pull request removes this auto-generated page from common content: https://docs.sentry.io/platforms/php/configuration/draining/

fix: Remove draining section for PHP

---

src/platforms/php/common/configuration/transports.mdx
src/platforms/php/common/integrations.mdx
src/platforms/php/guides/symfony/index.mdx
src/platforms/php/guides/symfony/performance/pm-integrations.mdx

Adding initial content to cover the Symfony tracing after a brief convo with @HazAT. Related to https://github.com/getsentry/sentry-docs/issues/3463,
Fixes https://github.com/getsentry/sentry-docs/issues/3463

Initial content for Symfony performance integrations

---

src/docs/clients/cocoa/advanced.mdx
src/docs/clients/cocoa/dsym.mdx
src/docs/clients/cocoa/migration.mdx

We've had an issue related to updates of our old content. This update highlights the new SDK at the top of each Cocoa page.

Add deprecation note to cocoa client pages

---

src/platforms/php/guides/symfony/index.mdx

Update Symfony Monolog integration to use the [`hub_id` option](https://github.com/symfony/monolog-bundle/pull/393) introduced in MonologBundle v3.7.

Update Symfony Monolog integration

---

src/docs/product/alerts-notifications/issue-alerts.mdx

Reading through the docs I saw this:
This PR fixes the markdown for the list of issue creating integrations

fix(copy): Issue Alerts Actions List

---

package.json
yarn.lock

This should resolve the security warning we keep getting on is-svg. The breaking change between 3.x and 4.x is dropping Node 6 support which doesn't affect us.
Same as getsentry/sentry#25295.

upgrade: force is-svg to >=4.2.2

---

package.json
yarn.lock

This is mostly to upgrade `socket.io` which has a security vulnerability in earlier versions. That said the newest version of Gatsby brings in many bug fixes and some performance upgrades, especially for development.

upgrade(gatsby): Upgrades gatsby to 2.32.13, latest stable

---

src/platforms/java/migration.mdx

Migration docs related to: https://github.com/getsentry/sentry-docs/pull/3293

Java: Migration for deprecating `sentry.enable-tracing`

---

src/includes/set-fingerprint/database-connection/apple.mdx

The code sample was missing a few characters to compile. This is fixed now.

fix(apple): Typo in fingerprint for database

---

src/includes/getting-started-config/javascript.nextjs.mdx

This PR adds the corresponding docs for https://github.com/getsentry/sentry-javascript/pull/3495, where the `process.env.NODE_ENV` is added as the `environment` by default.

Add default Next.js event environment

---

src/includes/getting-started-primer/javascript.nextjs.mdx

Currently, the SDK needs the `next.config.js` to be loaded async: vercel/next.js#22578
This change was introduced in v10.0.8: https://github.com/vercel/next.js/releases/tag/v10.0.8

fix(nextjs): Update minimum supported version to 10.0.8

---

src/platforms/javascript/guides/nextjs/manual-setup.mdx

> You can add the properties file to your VCS, excluding any sensitive data (like tokens), and add it to the environment variables.
It was unclear to what the final "it" referred. This reorganizes the sentence to make it clearer.

fix(nextjs): Clarify wording re: CLI config

---

.github/workflows/issue-status-helper.yml

I are a bot, here to deploy [issue-status-helper.yml](https://github.com/getsentry/.github/blob/c47baae9fa40046424bda5ff741a8216b2f6f623/.github/workflows/issue-status-helper.yml). 🤖

meta(gha): Deploy action issue-status-helper.yml

---

src/platforms/common/performance/index.mdx

A user assumed that the sentry-cocoa SDK already supports automatic
instrumentation. This is fixed now by clarifying this.

fix(apple): Clarification for manual transactions

---

src/css/_includes/grid.scss

Enable scrollable right sidebar introduced in https://github.com/getsentry/sentry-docs/pull/3539 on certain screen widths

fix: Scrollable right sidebar should be responsive friendly

---

src/platforms/common/performance/index.mdx
src/platforms/javascript/guides/react/configuration/integrations/react-router.mdx
src/platforms/javascript/guides/react/index.mdx

A number of customers miss the fact that we have a React Router integration and can do parameterization.
Highlight this integration on `Getting Started` for React and Performance Set Up.

Make React Router more visible

---

.github/workflows/issue-routing-helper.yml

I are a bot, here to deploy [issue-routing-helper.yml](https://github.com/getsentry/.github/blob/c3d0c77c6dfb3998a37ba62476f51281f424f132/.github/workflows/issue-routing-helper.yml). 🤖

meta(gha): Deploy action issue-routing-helper.yml

---

src/docs/product/releases/setup/index.mdx

Small change to add missing word to link description. Affects https://docs.sentry.io/product/releases/

Add missing word

---

src/includes/getting-started-config/unity.mdx

This is relevant but not on the getting started:
* `Assets/Resources/Sentry/SentryOptions.json` - Sentry settings
* `Assets/Resources/Sentry/link.xml` - [a special file](https://docs.unity3d.com/Manual/ManagedCodeStripping.html) for [ILL2CPP](https://docs.unity3d.com/Manual/IL2CPP.html) builds

add dsn to unity getting started

---

package.json
yarn.lock

[CVE-2020-7753](https://github.com/advisories/GHSA-w5p7-h5w8-2hfq)

upgrade(trim): Force trim>=1.0.1 to get security fix

---

src/platforms/react-native/migration.mdx

Migration docs for RN 2.5.x using a code snippet from https://github.com/getsentry/sentry-react-native/pull/1511 to handle the breaking ANDROID_ID change.
Fixes https://github.com/getsentry/sentry-react-native/issues/1489
Related from Flutter: #3564

feat: Migration docs for RN 2.5.x regarding the ANDROID_ID

---

src/platforms/android/migration.mdx
src/platforms/java/migration.mdx

Related to: https://github.com/getsentry/sentry-docs/issues/3567

Java: add migration entry about nullability annotations.

---

src/platforms/common/configuration/options.mdx

docs(node): Add caCerts option to node configuration page

---

src/includes/getting-started-config/javascript.nextjs.mdx

The Next.js SDK is strongly connected to the Vercel integration, and the docs weren't linking to it.

docs(nextjs): Link to Vercel integration

---

src/docs/product/integrations/vercel/index.mdx

The Next.js SDK now references the Vercel integration (change in https://github.com/getsentry/sentry-docs/pull/3586). This PR does the opposite: reference the Next.js SDK from the Vercel integration, to cross-link them.

Link Next.js SDK from Vercel integration

---

src/platforms/common/configuration/options.mdx
src/platforms/dotnet/guides/aspnetcore/index.mdx

Remove deprecated `IncludeRequestPayload` option from example and documentation, use `MaxRequestBodySize` instead.

Remove deprecated `IncludeRequestPayload` option

---

src/platforms/common/enriching-events/context.mdx

From [linked issue 3543](https://github.com/getsentry/sentry-docs/issues/3543):
This an issue with: Platform documentation
I didn't check all of the platforms, but it's present in at least the Python and JS docs.
https://docs.sentry.io/platforms/python/enriching-events/context/#structured-context
https://docs.sentry.io/platforms/javascript/enriching-events/context/#structured-context
(Perhaps worth your checking all of them, though.)
The docs on adding structured contexts say that "There are no restrictions for naming contexts or their fields" but it seems to me like the key "type" has a special meaning inside of a context.
That feels like a restriction worth documenting to me.
FWIW, the linked contexts interface developer documentation gives me more of an impression that "type" is …

add type caveat for contexts

---

src/components/sidebarLink.tsx
src/css/_includes/sidebar.scss

This is *not* logically equivalent but I can't find a case in the sidebar where it makes a difference.
This is continuation from #2776 and removes another 300MB from `public/`, bringing down the total to 284MB.

fix: Hide sidebar entries without CSS

---

src/includes/configuration/auto-session-tracking/javascript.mdx
src/includes/configuration/auto-session-tracking/node.mdx

This PR:
- Adds docs on how Release health in server-side (node) operates

feat(node): Add docs for server side release health

---

src/docs/product/accounts/quotas/manage-event-stream-guide.mdx

Fixes the section on which issues are consuming quota. Currently includes a confusing reference to content that no longer exists. From issue 3580:
Issue
This an issue with:
https://docs.sentry.io/product/accounts/quotas/manage-event-stream-guide/#-what-issues-are-consuming-my-quota
Description
The Sentry workflow starts with a real-time alert notifying you about an error in your code. If you want to take a more proactive approach to resolve your busiest errors, follow steps 1 - 6 from above. For step 4 select the columns as seen below:
I don't see any steps "above" in this guide which relate to this?

fix issues consuming quota section of Manage Your Event Stream

---

src/components/basePage.tsx

We've updated our guidelines and want our users to feel more welcomed to contribute to Docs. This change updates our base page footer to incorporate our Contributor Guidelines and our new Issues Template:

Update CTA for GitHub

---

src/platforms/node/common/performance/database.mdx

Implementation: https://github.com/getsentry/sentry-javascript/pull/3483

ref: Node DB auto-instrumentation docs

---

src/platforms/android/migration.mdx
src/platforms/react-native/migration.mdx

Fixes https://github.com/getsentry/sentry-docs/issues/3591

Migrate Gradle plugin v1 to v2

---

src/platforms/common/configuration/index.mdx
src/platforms/common/data-management/index.mdx
src/platforms/common/enriching-events/index.mdx
src/platforms/common/usage/index.mdx
src/platforms/kotlin/config.yml
src/platforms/kotlin/index.mdx
src/wizard/android/index.md
src/wizard/java/index.md

Kotlin is an increasingly popular search item, and users aren't able to find that it's supported by our Java and Android SDKs. This PR adds a page that directs users to the supported SDKs. The PR also update the wizards for Android and Java to more clearly identify the different code snippets.

Add Kotlin pointer page

---

src/platforms/javascript/guides/nextjs/manual-setup.mdx

The [Sentry Webpack plugin](https://github.com/getsentry/sentry-webpack-plugin) outputs logs that may be annoying for some users, especially when running in `dryRun` mode. Adding `silent` suppresses all logs, decreasing noise to users.

docs(nextjs): Add `silent` option in default webpack config

---

src/platforms/javascript/guides/nextjs/manual-setup.mdx

Extending the Webpack usage on Next.js is not an option with the only purpose of generating and uploading source maps; it's required to initialize the SDK.

fix(nextjs): Clear up the extended webpack goal of Next.js

---

src/platforms/common/performance/index.mdx

The Cocoa SDK doesn't support automatic performance monitoring yet.
Customers think they get transactions out of the box. This is fixed
now by displaying the section on custom instrumentation for
verifying performance.

fix(apple): Verifying Performance

---

src/platforms/android/using-ndk.mdx

Plugin https://github.com/howardpang/androidNativeBundle migrated from JCenter to MavenCentral, but the group and artifact id needed to change, hence updating our docs

Update Android Native Bundle group

---

src/includes/enriching-events/scopes/with-scope/apple.mdx

The code sample for withScope was missing setting the level. This is fixed now.
Fixes GH-3601

fix(apple): Incomplete withScope code sample

---

src/includes/configuration/sample-rate/ruby.mdx

This cost us a few hours of stress as we thought it was a legit thing to be configured -- however, this mistake caused us to turn on performance sampling, quickly exceed the quota and cause all kinds of alarms to go off. :/

Fix incorrect sampling configuration method.

---

src/wizard/unity/index.md

As a quick fix removing the image altogether and adding a DSN.
We can figure out how to add the Window image later

unity wizard dsn

---

src/wizard/java/index.md

Assumes #3646 will get merged.
* Added `debug=true` which help customers troubleshoot installation issues
* Removed Kotlin snippets (too verbose without proper tooling support, aka: tabs). Kotlin gets its own wizard (#3646)
* Performance monitoring opt-in with a code snippet on how to get started for validation.
@maciejwalkowiak

java wizard with performance

---

src/platforms/javascript/guides/nextjs/manual-setup.mdx

Both the [`sentry.client.config.js`](https://github.com/getsentry/sentry-wizard/blob/f42afd7ad600bfdbc5692b3f3acbb957281cbfce/scripts/NextJs/configs/sentry.client.config.js#L7) and [`sentry.server.config.js`](https://github.com/getsentry/sentry-wizard/blob/f42afd7ad600bfdbc5692b3f3acbb957281cbfce/scripts/NextJs/configs/sentry.server.config.js#L7) generated by the Wizard have a variable to get the DSN from the environment, which the code samples in the manual-setup/ don't. This PR adds these, to be more consistent and reduce any confusion that may exist.

Update incomplete Next.js manual-setup code samples

---

.github/CODEOWNERS

I was covering the areas for the Web Platform team to shield the rest of the team from notifications, but now need to reduce the amount of notifications I'm getting.
The expectation is that the triage process will take care of directing attention to the Web team (or any other team) when necessary.

Remove self from CODEOWNERS

---

src/includes/getting-started-config/dotnet.mdx
src/includes/getting-started-config/dotnet.xamarin.mdx
src/includes/getting-started-verify/dotnet.xamarin.mdx
src/platforms/dotnet/guides/aspnet/index.mdx
src/platforms/unity/unity-lite.mdx
src/wizard/dotnet/aspnet.md

The goal is to add performance monitoring to more _getting started_ and _wizard_s.
Also, to always suggest `Debug=true` to help users troubleshoot their setup.
Blocked by GA of .NET for the nicer API to start/finish transaction for ASP.NET Classic
/cc @Tyrrrz

perf in getting started

---

src/includes/enriching-events/import/javascript.nextjs.mdx

On enriching events page, even if the platform Next.js is selected, the imported SDK is `@sentry/browser`. The import must be from `@sentry/nextjs`.

fix(nextjs): Import Next.js SDK on enriching-content

---

src/docs/product/integrations/aws-lambda/how-it-works.mdx

Because it looks strange (kinda broken) now:

docs(lambda): Remove unnecessary colons

---

src/platforms/common/configuration/options.mdx
src/platforms/common/data-management/sensitive-data/index.mdx

Part of: #3605
(Might need to also update [inbound filters](https://docs.sentry.io/platforms/node/configuration/integrations/default-integrations/#inboundfilters) on Node, if this gets approved.)

Node: Review Options List

---

src/platforms/common/enriching-events/identify-user.mdx

"the connection" for users can read as: The connection between my users and my server. But we mean here exclusively: The connection between Sentry's SDK and Sentry's server.

clarify auto ip address

---

src/includes/performance/automatic-instrumentation-intro/javascript.mdx
src/includes/performance/automatic-instrumentation-intro/javascript.nextjs.mdx
src/includes/performance/beforeNavigate-example/javascript.mdx
src/includes/performance/beforeNavigate-example/javascript.nextjs.mdx
src/includes/performance/configure-sample-rate/javascript.nextjs.mdx
src/includes/performance/enable-automatic-instrumentation/javascript.mdx
src/includes/performance/enable-automatic-instrumentation/javascript.nextjs.mdx
src/includes/performance/enable-tracing/javascript.nextjs.mdx
src/includes/performance/filter-span-example/javascript.nextjs.mdx
src/includes/performance/group-transaction-example/javascript.mdx
src/includes/performance/retrieve-transaction/javascript.mdx
src/includes/performance/tracingOrigins-example/javascript.mdx
src/includes/performance/tracingOrigins-example/javascript.nextjs.mdx
src/includes/performance/what-instrumentation-provides/javascript.mdx
src/includes/performance/what-instrumentation-provides/javascript.nextjs.mdx
src/platforms/common/performance/connect-services.mdx
src/platforms/common/performance/index.mdx
src/platforms/common/performance/instrumentation/index.mdx
src/platforms/common/performance/troubleshooting-performance.mdx
src/platforms/javascript/common/performance/instrumentation/automatic-instrumentation.mdx

This follows up on https://github.com/getsentry/sentry-docs/pull/3653, which added mentions of performance to the nextjs docs, but didn't actually add the performance docs themselves. This does so, and includes the following changes:
- add nextjs-specific code samples where required
- turn spots where nextjs needs to override the main JS content into includes
- simplify example code for `BrowserTracing` options
- remove note about skipping setup page, as it contains useful information about sampling and testing
- do general wordsmithing

feat(nextjs): Add nextjs performance docs

---

src/includes/enriching-events/scopes/with-scope/dart.mdx

https://github.com/getsentry/sentry-dart/releases/tag/5.1.0
cc @ueman

Remove beta note from dart withScope

---

src/platforms/dotnet/guides/uwp/config.yml
src/platforms/dotnet/guides/uwp/index.mdx
src/wizard/dotnet/uwp.md
src/wizard/dotnet/winforms.md
src/wizard/dotnet/wpf.md
src/wizard/dotnet/xamarin.md

By default, if you use the .NET SDK as is. It'll not register unhandled exceptions, this PR provides documentation on how to register unhandled exceptions on a UWP application.
Additionally, the following frameworks got their wizard updated with a more complete setup including SDK initialization with performance monitoring, Verify, and performance monitoring sample.
- Xamarin
- WPF
- WinForms
- UWP

Add UWP doc and update .NET wizard

---

src/includes/configuration/config-intro/apple.mdx
src/includes/getting-started-config/apple.mdx
src/platforms/apple/common/configuration/out-of-memory.mdx

Use YES/NO (BOOL) instead of @YES/@NO (NSNumber).

fix(apple): Use YES/NO in samples

---

src/platforms/javascript/common/configuration/integrations/default.mdx

Ref: https://github.com/getsentry/sentry-javascript/pull/3620

Document `serializeAttribute` option of browser breadcrumbs.

---

src/platforms/javascript/common/configuration/webworkers/index.mdx
src/platforms/javascript/guides/webworkers/index.mdx

Adds simple documentation on Web Workers support.

Add guide for web workers.

---

src/platforms/javascript/common/configuration/integrations/rrweb.mdx

Two fixes to the [rrweb docs](https://docs.sentry.io/platforms/javascript/guides/nextjs/configuration/integrations/rrweb/) here:
- So as not to have to copy-paste the snippet into multiple includes, for the sole purpose of changing the import, this adds a comment letting folks know to use their main SDK.
- Since nextjs is cross-platform, this also adds a note reminding people that the integration is browser-only.
Fixes #3703.

fix(JS): Update `rrweb` docs for nextjs

---

src/platforms/php/common/configuration/transports.mdx

Hello, as I can see, SpoolTranspot was removed, see [#1080](https://github.com/getsentry/sentry-php/pull/1080). So the reference here may be misguiding.

Remove SpoolTransport mention in php transports doc

---

src/docs/product/sentry-basics/guides/migration/index.mdx

I gather that sentry-basics is coming up for an overhaul. Short of that, here's a small revision to the SaaS migration guide. The primary motivation here is to stop referring to self-hosted Sentry as "open-source" Sentry ... _Sentry_ is open-source Sentry! 💃

open-source → self-hosted in SaaS migration guide

---

src/wizard/javascript/vue.md

Prevents users from adding sentry to vue 3 project.
This saves users from going through with the current tutorial if they have vue 3 project.
Relevant issue: https://github.com/getsentry/sentry-javascript/issues/2925

Mention vue 3 incompatibility

---

src/platforms/python/guides/celery/index.mdx

Fix https://github.com/getsentry/sentry-docs/issues/3697

fix: Clarify when Celery integration should be initialized

---

src/docs/product/issues/index.mdx
src/docs/product/sentry-basics/search/index.mdx
src/docs/product/sentry-basics/search/premade-saved-searches.mdx
src/docs/product/sentry-basics/search/saved-searches.mdx
src/docs/product/sentry-basics/search/searchable-properties.mdx

Chunks Search content out into three pages (+ other minor updates for style and accuracy):
- Search
- Searchable Properties
- Saved Searches

restructure Search content

---

src/includes/getting-started-primer/javascript.vue.mdx

Complements https://github.com/getsentry/sentry-docs/pull/3704.
I realized the previous PR was updating only the wizard.
This PR adds a note to the first sentence in https://docs.sentry.io/platforms/javascript/guides/vue/.

vue: Document supported version range

---

src/wizard/javascript/nextjs.md

- Set correct expectations upon installing the `@sentry/nextjs` in regards to tracking API routes.
- Separate manual and automatic (sentry wizard) installation guides

docs(nextjs): improve order of installation steps

---

src/includes/configuration/config-intro/unity.mdx

Clarified to disable the SDK via config window if the user decides to initialize it programmatically. (and removed random line break)

Fix: Unity options clarification

---

src/includes/getting-started-config/dotnet.xamarin.mdx

A simple fix for the getting started config example that was using the wrong variable name for SentryOptions.

fix Xamarin getting started

---

src/includes/configuration/drain-example/react-native.mdx

Reword the shutdown/draining page, and mention new flush method, awaiting https://github.com/getsentry/sentry-react-native/pull/1547

feat: Reword RN shutdown-drain + mention flush

---

src/platforms/common/data-management/debug-files/file-formats.mdx
src/platforms/common/data-management/debug-files/identifiers.mdx
src/platforms/common/data-management/debug-files/index.mdx
src/platforms/common/data-management/debug-files/symbol-servers.mdx

Possibly a nitpick on the same boat as `Javascript` -> `JavaScript` and `.Net` -> `.NET` but the correct format for it is `Mach-O`: https://en.wikipedia.org/wiki/Mach-O
[👁️ ](https://www.youtube.com/watch?v=yxxj73JCV4Q)

ref: macho -> mach-o

---

src/docs/product/alerts/create-alerts/issue-alert-config.mdx
src/docs/product/releases/index.mdx

Adds missing redirect from old Alerts & Settings to Issue Alert Configuration 
Adds link to deploy notifications from Releases page

add missing redirect for old alerts & settings page

---

src/includes/enriching-events/user-feedback/example-widget/dotnet.aspnet.mdx
src/includes/getting-started-config/dotnet.mdx
src/includes/getting-started-config/dotnet.xamarin.mdx
src/platforms/common/configuration/options.mdx
src/platforms/dotnet/guides/aspnet/index.mdx
src/platforms/dotnet/guides/aws-lambda/index.mdx
src/platforms/dotnet/guides/entityframework/index.mdx
src/platforms/dotnet/guides/extensions-logging/index.mdx
src/wizard/dotnet/uwp.md
src/wizard/dotnet/wpf.md

This is a small refactor to the dotnet docs, fixing some code snippets, removing deprecated references, and also other minor fixes.
Some notes below are related to things that I didn't edit at the moment and I would like an opinion on what todo:
* https://docs.sentry.io/platforms/dotnet/guides/wpf/configuration/options/#environment
* https://docs.sentry.io/platforms/dotnet/guides/aspnetcore/#overview-of-the-features
* https://docs.sentry.io/platforms/dotnet/guides/aspnet/#configuring
' to the EF doc?
* https://docs.sentry.io/platforms/dotnet/guides/aspnet/#capturing-the-affected-user
* https://github.com/getsentry/sentry-dotnet-ef/tree/main/samples/Sentry.Samples.AspNet.Mvc
* https://docs.sentry.io/platforms/dotnet/guides/log4net/#configuration

ref: Sentry dotnet doc

---

package.json
yarn.lock

Related to https://github.com/getsentry/platformicons/pull/45/ and https://github.com/getsentry/platformicons/pull/46

chore(platformicons): updated to 4.3.0 in docs

---

src/includes/configuration/auto-session-tracking/react-native.mdx

This improves instructions on how to disable auto session tracking.
Most importantly, the correct attribute is used in the code block, which is most likely to be copy/pasted.

Clarify disabling auto session tracking on React Native

---

src/platforms/common/configuration/options.mdx

This PR enhances the documentation on how to use the `initialScope` option by providing two code snippets; one to use it as an object and another to use it as a callback function

docs(js): Enhance initialScope options docs

---

src/includes/configuration/auto-session-tracking/javascript.mdx

Documents that users should be set on initialScope when initialising the SDK to receive user adoption release health data due to recent change on the SDK that drops user data from session if user is defined after `Sentry.init` 
Ref: https://github.com/getsentry/sentry-javascript/pull/3701

docs(js): Enhance release health document

---

src/includes/getting-started-primer/javascript.nextjs.mdx

We still have a few known limitations when deploying on Vercel that the team hopefully is able to resolve with the help of Vercel next week.

ref: Remove next.js EA alert

---

src/platforms/javascript/guides/nextjs/manual-setup.mdx

@sentry/nextjs does not support the serverless target. This patch
adds a note to the manual configuration section of the nextjs docs
that surfaces this. It also recommends user's use the
experimental-serverless-trace option as an alternative.
The note was put in an alert under manual configuration as only a few
users will hit this situation.

fix(nextjs): Indicate that the serverless target is not supported

---

src/includes/getting-started-primer/javascript.nextjs.mdx

In the Alert component, linking sometimes doesn't work as expected. Moving the content so that the link is earlier on the line seems to fix the issue.

Update link to display properly

---

src/platforms/javascript/guides/react/components/profiler.mdx

👋 I noticed that content in an `Alert` is being styled as code block due to indenting on https://docs.sentry.io/platforms/javascript/guides/react/components/profiler/. 
This PR removes the indentation.

Remove indentation from Alert in React profiler page

---

package.json
yarn.lock

Fixes a security issue: https://github.com/advisories/GHSA-px4h-xg32-q955

upgrade(normalize-url): Upgrade normalize-url to 4.5.1

---

package.json
yarn.lock

Fixes a security issue: https://github.com/advisories/GHSA-7p7h-4mm5-852v

upgrade(trim-newlines): Upgrade trim-newlines to 4.0.2

---

package.json
yarn.lock

Fixes a security issue: https://github.com/advisories/GHSA-hwj9-h5mp-3pm3
Note that we forced some `6.x` versions to `7.x` but the only breaking change between them was dropping support for old Node versions.

upgrade(postcss): Upgrade postcss to 7.0.36

---

src/includes/getting-started-primer/apple.mdx

Update list of types of errors based on KSCrash, as SentryCrash was
forked from [KSCrash](https://github.com/kstenerud/KSCrash#kscrash-handles-the-following-kinds-of-crashes).
[A long time ago](https://github.com/getsentry/sentry-docs/pull/3420#issuecomment-824433222) @bruno-garcia pinged me to update this.

fix(apple): List of types of errors

---

src/includes/getting-started-config/ruby.delayed_job.mdx
src/includes/getting-started-config/ruby.mdx
src/includes/getting-started-config/ruby.sidekiq.mdx
src/includes/getting-started-install/ruby.resque.mdx
src/platforms/ruby/guides/resque/config.yml

Mainly for adding an entry for the new `sentry-resque` integration.

Update Ruby SDK's doc for version 4.6.0

---

.github/workflows/unroute-new-issue.yml

I are a bot, here to deploy [unroute-new-issue.yml](https://github.com/getsentry/.github/blob/7931bd5fe56576ca30adb0e3fc5f629fd4e8bb59/.github/workflows/unroute-new-issue.yml). 🤖
------------
Note: Merge together with https://github.com/getsentry/sentry-docs/pull/3812.

meta(gha): Deploy action unroute-new-issue.yml
