getsentry/sentry-docs

platform-includes/migration/javascript-v8/important-changes/javascript.nextjs.mdx
https://github.com/getsentry/sentry-javascript/discussions/13103#discussioncomment-11618821 raised that our migration guide is a bit outdated/wrong/could be improved. This PR fixes it.
=> Fix v8 migration guide for Next.js to align with wizard

docs/platforms/dotnet/common/configuration/options.mdx
Correct the dotnet docs regarding the valid values for `MaxRequestBodySize`.
Based on `sentry-dotnet` code:
https://github.com/getsentry/sentry-dotnet/blob/main/src/Sentry/Extensibility/RequestSize.cs
`None` is a valid
I encountered the following error:
`"Message":"Failed to convert configuration value at 'Sentry:MaxRequestBodySize' to type 'Sentry.Extensibility.RequestSize'`
when setting the `appsettings.json` value `Sentry:MaxRequestBodySize` to `never`
=> docs(dotnet): valid value for RequestSize

platform-includes/capture-message/javascript.mdx
Extends the example on `captureMessage` to show the usage of optional params.
ref https://github.com/getsentry/sentry-docs/issues/9979
=> docs(js): Extend example on `captureMessage`

docs/product/explore/session-replay/mobile/performance-overhead.mdx, docs/product/explore/session-replay/web/performance-overhead.mdx
Low impact change, but i was looking at these pages and just a little confused because I had 'JavaScript' selected in the top-left.
**Before**
| `/product/explore/session-replay/web/performance-overhead/` | `/product/explore/session-replay/mobile/performance-overhead/` |
| --- | --- |
| ![SCR-20250107-kixt](https://github.com/user-attachments/assets/ee391ccc-0fa0-437b-9e7c-6c7e77d14e98) | ![SCR-20250107-kiyy](https://github.com/user-attachments/assets/3de4c770-7fd5-4493-ae5f-31771f90b8a0) |
| ![SCR-20250107-kmva](https://github.com/user-attachments/assets/58a7f69d-c119-4be0-ba8d-0b153c3e423f) | ![SCR-20250107-kmwg](https://github.com/user-attachments/assets/4a35a72e-4e89-4bd7-be81-8e3d7464a3f8) |
=> fix(replay): Be a little clearer about whether the page is mobile or web specific at the top

docs/organization/integrations/feature-flag/generic/index.mdx
follow-up on https://github.com/getsentry/sentry-docs/pull/12270, missed a spot
=> ref(flags): rename self-serve in generic ffs index

docs/platforms/react-native/session-replay/index.mdx
The call is out of context, so customers were not sure where to put this, or the fact that it should update the current call they have under `integrations`.
=> mobile: react native options

docs/platforms/php/common/tracing/instrumentation/custom-instrumentation.mdx
https://github.com/getsentry/projects/issues/524
=> Document how to attach data attributes onto a span/transaction in PHP

docs/platforms/java/common/tracing/troubleshooting/index.mdx, platform-includes/performance/create-transaction-bound-to-scope/java.mdx, platform-includes/performance/enable-manual-instrumentation/java.mdx
Improve `bindToScope` docs for Java as some customers were confused by missing spans due to the transaction not being bound to the scope.
Closes https://github.com/getsentry/sentry-java/issues/3760
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional …
=> Improve `bindToScope` docs for Java

docs/platforms/javascript/common/session-replay/configuration.mdx
We had a comment that it was unclear whether the tree shaking step when adding a custom worker script for replay was optional.
https://github.com/getsentry/sentry-javascript/discussions/14794#discussioncomment-11744828
=> Clarify that tree shaking replay worker is optional

docs/platforms/react-native/sourcemaps/uploading/codepush.mdx
Small typo fix, the command example is correct, just the text was not updated.
=> fix(codepush): Typo use `sourcemaps upload` not `react-native appcenter`

docs/platforms/android/session-replay/index.mdx, docs/platforms/apple/guides/ios/session-replay/index.mdx
Update SR Mobile Masking intro based on 
- https://github.com/getsentry/sentry-docs/pull/11798#discussion_r1840461911 …
=> chore: Update iOS and Android SR privacy

docs/security-legal-pii/scrubbing/attachment-scrubbing.mdx
ref: https://github.com/getsentry/relay/issues/4368
=> Clarify limitations of attachment scrubbing

develop-docs/sdk/miscellaneous/feature-branches.mdx
=> Move python feature branch docs; add java learnings

develop-docs/backend/application-domains/database-migrations/index.mdx
After https://github.com/getsentry/sentry/pull/83140 and https://github.com/getsentry/sentry/pull/83143 these no longer apply
=> Remove backup testing notes

src/components/expandable.tsx
This prevents expandable titles showing up in the ToC
=> fix(platform): Only render permalinks as h2 in expandable

docs/platforms/dotnet/common/migration/index.mdx
Should fix up https://github.com/getsentry/sentry-docs/issues/12318
=> fix(docs): Fix syntax highlighting for .NET migration guide

docs/platforms/dotnet/common/migration/index.mdx, platform-includes/configuration/config-intro/dotnet.xamarin.mdx, platform-includes/enriching-events/attachment-upload/dotnet.mdx, platform-includes/getting-started-config/dotnet.xamarin.mdx, platform-includes/performance/automatic-instrumentation-integrations/dotnet.mdx, platform-includes/performance/opentelemetry-setup/dotnet.mdx
I noticed that we are using `o` and `options` interchangeably. I caught this while referencing docs for a blog post. I *think* I caught all of the instances, but I'm not positive. I'd like to see this in preview so that I can go through one more time to be sure.
=> Changing `o` to `options` for Xamarin docs

docs/platforms/python/integrations/index.mdx, docs/platforms/python/integrations/typer/index.mdx
https://github.com/getsentry/sentry-python/pull/3869 adds the Typer integration to the Python SDK. Adding docs.
**Note:** This is not released yet, so please don't merge yet. It can however be reviewed already.
=> feat(python): Add Typer integration docs

docs/platforms/python/integrations/unleash/index.mdx
=> fix(flags): Remove get_variant example from unleash docs

docs/platforms/python/feature-flags/index.mdx
This paragraph is a dup of the one under ### Generic API, and also isn't correct (none of the integrations expose an API).
=> ref(flags): remove dup paragraph from python FF index

develop-docs/self-hosted/geolocation.mdx, develop-docs/self-hosted/index.mdx, develop-docs/self-hosted/releases.mdx, develop-docs/self-hosted/troubleshooting/kafka.mdx
Companion PR for getsentry/self-hosted#3490
=> ref(self-hosted): Update docs for GeoIP update and `dc up -d`

develop-docs/sdk/telemetry/traces/index.mdx
Adjusts the dev docs on sample_rand to require 30 less IQ points when reading. I used myself (borderline dyslexic) as a benchmark.
=> Simplify and make sample rand docs more specific

docs/platforms/python/troubleshooting.mdx
=> feat(python): Add troubleshooting for multiprocessing deprecation

develop-docs/sdk/expected-features/data-handling.mdx
Noticed this was using outdated API names.
=> Update develop docs data handling section for new APIs

docs/platforms/javascript/guides/sveltekit/manual-setup.mdx
The SvelteKit SDK injects a small inline `<script>` into the server-side rendered HTML responses of SvelteKit applications. Due to concerns raised with setting a nonce to except this script from being blocked, this PR removes the nonce documentation in favor of a better, hash-based CSP exception approach.
=> ref(sveltekit): Remove nonce approach in favor of hash for optional CSP config

src/middleware.ts
closes https://github.com/getsentry/sentry-docs/issues/12280
=> fix(404): Add redirect for incident.io integration

app/globals.css, app/layout.tsx
Shortens the disclaimer text for the kapa ai model
=> chore(platform): Update disclaimer text for chatbot

docs/platforms/python/integrations/launchdarkly/index.mdx, docs/platforms/python/integrations/openfeature/index.mdx, docs/platforms/python/integrations/unleash/index.mdx
Update python integration docs to follow the pattern of [clickhouse-driver](https://docs.sentry.io/platforms/python/integrations/clickhouse-driver/). Versions are based on `tox.ini` and extras_require dict in `setup.py` of python repo. Using the extra (e.g. `[launchdarkly]`) will automatically install the required dependencies.
LD after:
Before:
=> ref(flags): update python supported vers and install snippets

docs/platforms/javascript/common/feature-flags/index.mdx, docs/platforms/python/feature-flags/index.mdx, docs/product/explore/feature-flags/index.mdx, platform-includes/feature-flags/change-tracking-list/_default.mdx, platform-includes/feature-flags/enable-change-tracking/_default.mdx
Adds a link to the unleash webhook docs, which we were missing before.
Modifies/renames `enable-change-tracking` PlatformContent to be the list of webhook docs. These are platform-agnostic but I'm using PlatformContent to reuse this list.
In summary,
**Before**: platform FFs -> product/explore FFs -> webhook doc
**After**: 
platform FFs -> webhook doc
product/explore FFs -> webhook doc
**/product/explore/feature-flags/ Before**
**After**
**/platforms/[javascript or python]/feature-flags/ Before** (links to /product/explore/feature-flags/)
**After**
=> ref(flags): link to unleash webhook docs and flatten change tracking links

docs/platforms/android/profiling/index.mdx
I believe the spacing on the docs is incorrect. 
It is correct on the [Tracing page](https://docs.sentry.io/platforms/android/tracing/):
But incorrect on the [Profiling page](https://docs.sentry.io/platforms/android/profiling/):
=> Fix spacing on the Android Profiling docs

develop-docs/frontend/network-requests.mdx
Realized that the doc on this hasn't been updated for v5
=> chore(develop): Update dev frontend networks requests page for isLoading -> isPending

docs/platforms/php/common/configuration/options.mdx, docs/platforms/php/guides/symfony/configuration/symfony-options.mdx
Follow up on https://github.com/getsentry/sentry-symfony/issues/907
=> Clean up Symfony options

docs/platforms/javascript/guides/react/features/react-router/v6.mdx, docs/platforms/javascript/guides/react/features/react-router/v7.mdx
Documents: https://github.com/getsentry/sentry-javascript/pull/14854
=> Add React SDK's `wrapCreateMemoryRouterVX` docs.

src/components/track-reader-depth.tsx, src/hooks/usePlausibleEvent.tsx, src/types/plausible.ts
Adds `usePlausibleEvent` hook which will be used in upcoming tracking tasks
closes https://github.com/getsentry/sentry-docs/issues/12241
=> feat(platform): Add reusable hook for custom plausible events

docs/platforms/dart/tracing/instrumentation/custom-instrumentation.mdx, docs/platforms/flutter/tracing/instrumentation/custom-instrumentation.mdx, platform-includes/performance/improving-data/dart.mdx
Closes https://github.com/getsentry/sentry-dart/issues/2554 …
=> feat(flutter): document how to add data to spans/transactions

platform-includes/getting-started-verify/javascript.nuxt.mdx
I think this should be `server/api/*`, I've never seen event handlers directly under `server`, but feel free to correct me if I'm wrong. …
=> docs(nuxt): correct api directory

platform-includes/profiling/automatic-instrumentation-headers/javascript.nuxt.mdx
Correcting some leftovers from `Next.js`. …
=> docs(nuxt): correct framework name and file path

platform-includes/distributed-tracing/how-to-use/javascript.nuxt.mdx
It appears the browser tracing integration is automatically configured for Nuxt: https://github.com/getsentry/sentry-javascript/blob/e59055092c546274eb3767da56ec32944f14b075/packages/nuxt/src/runtime/plugins/sentry.client.ts#L45
I think it's enough to configure `tracePropagationTargets`, but please correct me if I'm wrong. …
=> docs(nuxt): drop duplicate browser tracing integration

platform-includes/configuration/capture-console/javascript.deno.mdx, platform-includes/configuration/contextlines/javascript.deno.mdx, platform-includes/configuration/debug/javascript.deno.mdx, platform-includes/configuration/dedupe/javascript.deno.mdx, platform-includes/configuration/extra-error-data/javascript.deno.mdx, platform-includes/configuration/rewrite-frames/javascript.deno.mdx, platform-includes/configuration/sessiontiming/javascript.deno.mdx, platform-includes/crons/setup/javascript.deno.mdx, platform-includes/getting-started-config/javascript.deno.mdx, platform-includes/performance/configure-sample-rate/javascript.deno.mdx
- Closes https://github.com/getsentry/sentry-javascript/issues/15087
=> feat(deno): Remove references to `deno.land` registry

develop-docs/sdk/telemetry/client-reports.mdx
ref https://github.com/getsentry/team-sdks/issues/116
My prettier formatted this page, but the main change is to add `buffer_overflow` as a discard reason.
The reason we have `buffer_overflow` as a separate item to `queue_overflow` is that in the future when we send log items in envelopes we'll increment `queue_overflow` for the transport queue. We want to differentiate between the transport queue and the internal buffer explicitly.
After this we need to add the [reason to snuba](https://github.com/getsentry/snuba/blob/1a2528dacaf7415f71866bf2602ce473832d938c/rust_snuba/src/processors/outcomes.rs#L15-L27) as a new client discard reason.
=> feat(develop): Propose new discard reason for buffer overflow

docs/platforms/javascript/common/user-feedback/index.mdx, platform-includes/user-feedback/sdk-api-example/javascript.mdx
Closes https://github.com/getsentry/sentry-docs/issues/10822
Closes https://github.com/getsentry/sentry-docs/issues/11635
- Rewords https://docs.sentry.io/platforms/javascript/user-feedback/#user-feedback-api so it's clear `associatedEventId` is optional. 
- Splits the "stand-alone" and "w/eventId" usecases into 2 separate tabs in the code snippet.
- Removes link to deprecated HTTP endpoint
**Standalone**
**w/eventId**
**Before**
=> ref(feedback): update JS SDK API example

develop-docs/frontend/upgrade-policies.mdx, docs/cli/crons.mdx, docs/organization/authentication/sso/okta-sso/okta-scim.mdx, docs/platforms/javascript/common/tracing/index.mdx, docs/platforms/native/common/enriching-events/attachments/index.mdx, docs/platforms/unity/data-management/store-minidumps-as-attachments/index.mdx, docs/platforms/unity/enriching-events/attachments/index.mdx, docs/platforms/unity/native-support/index.mdx, docs/platforms/unreal/configuration/setup-crashreporter/index.mdx, docs/platforms/unreal/data-management/store-minidumps-as-attachments/index.mdx, docs/platforms/unreal/enriching-events/attachments/index.mdx, docs/platforms/unreal/index.mdx, docs/product/crons/getting-started/index.mdx, docs/product/insights/ai/llm-monitoring/getting-started/index.mdx, docs/product/releases/setup/release-automation/netlify/index.mdx, docs/security-legal-pii/security/security-policy-reporting.mdx, includes/opentelemetry-available.mdx
This level does not exist, so this does nothing.
=> fix: Drop unsupported `level="note"` for Alert

docs/contributing/pages/components.mdx, docs/platforms/javascript/common/best-practices/shared-environments.mdx, docs/platforms/javascript/common/session-replay/index.mdx, docs/platforms/javascript/common/sourcemaps/uploading/esbuild.mdx, docs/platforms/javascript/guides/nextjs/manual-setup.mdx, includes/metrics-api-change.mdx, src/components/alert/index.tsx, src/components/alert/styles.scss
We do not use success at all, and danger only in few places, where we can also use `warning` instead.
=> feat: Drop `success` and `danger` Alert levels

includes/store-minidumps-as-attachments-intro.mdx
Following up on the suggestion made [here](https://github.com/getsentry/sentry-docs/pull/12398#discussion_r1924160314)
=> ref(store-minidumps): Add link to the word 'Minidump'

platform-includes/crons/setup/php.laravel.mdx
Recovery Tolerance and Failure Tolerance were missing.
Aligned the docs comments with our UI.
=> Add missing Laravel Crons parameters

docs/platforms/javascript/common/configuration/integrations/prisma.mdx
Ref: https://github.com/getsentry/sentry-javascript/issues/14793
Fixes: https://github.com/getsentry/sentry-docs/issues/12184
Adds instructions on how to configure the SDK for prisma v6.
Depends on release of https://github.com/getsentry/sentry-javascript/pull/15128
=> Add instructions on how to support prisma v6

apps/changelog/package.json, apps/changelog/sentry.server.config.ts
Fixes crashing changelog because of prisma instrumentation version mismatch.
=> fix: Use prisma instrumentation of current prisma versoin

docs/platforms/javascript/common/session-replay/understanding-sessions.mdx
@lforst noticed this, the example was incorrect, this receives an error event.
=> fix(replay): Fix `beforeErrorSampling` example

docs/product/stats/index.mdx
Since all the 'filtered' reasons are going to be displayed on the stats page (see [PR](https://github.com/getsentry/sentry/pull/83916)), it makes sense to remove 'others' from the documentation. However, I’d still like to keep the most common reasons listed in the docs, especially since the inbound filters documentation doesn’t include all of them.
=> ref(stats): Remove 'other' from Filters

docs/platforms/javascript/common/tracing/instrumentation/custom-instrumentation/index.mdx
Documents how users can add an attribute to all spans in a transaction event with the JS SDKs
=> doc(js): Document how to set attribute on all spans

docs/platforms/android/enriching-events/scopes/index.mdx, docs/platforms/java/common/enriching-events/scopes/index.mdx
Closes getsentry/sentry-java#4067
=> Add Kotlin examples and fix typo in Java and Android Scopes docs

docs/contributing/pages/components.mdx, docs/platforms/javascript/common/troubleshooting/index.mdx, src/components/alert.tsx, src/components/alert/index.tsx, src/components/callout/index.tsx, src/components/callout/styles.scss, src/components/expandable.tsx
For this, I extracted the `Alert` component stuff into a more generic `Callout` component, which the `Alert` extends.
The `Expandable` can now use the same basis, ensuring we have the same style etc, and just pass some more stuff into it.
For this, the `Callout` component also allows to pass `id` and `titleOnClick` attributes which we need for the Expandable.
I made sure that permalinks continue to work. I tweaked the behavior a bit, now it does not scroll into view when you open a permalink expandable, this should be a bit more subtle now. You can try the behavior on any Troubleshoot page in the JS repo, for example.
=> feat: Update `Expandable` style

src/components/platformFilter/style.module.scss, src/components/search/index.tsx, src/components/search/searchResultItems.tsx, src/components/search/util.ts, src/hooks/useListKeyboardNavigate.tsx
Enables scrolling with keyboard arrow keys, by nesting the `useListKeyboardNavigate` within search results
=> fix(platform): Enable scrolling via keyboard buttons

docs/organization/integrations/issue-tracking/jira/index.mdx, docs/platforms/javascript/guides/express/index.mdx
As this comes up quite regularly, I figured it may make sense to explicitly call out our support for Express v5, and link to the tracking issue (https://github.com/getsentry/sentry-javascript/issues/13674) for details.
=> feat(express): Add warning about express v5

docs/platforms/native/common/tracing/instrumentation/custom-instrumentation.mdx, platform-includes/performance/improving-data/native.mdx
Closes https://github.com/getsentry/sentry-native/issues/1112
=> docs(native): document how to set attribute on spans/transactions

docs/platforms/javascript/guides/aws-lambda/install/esm-npm.mdx
When going through the docs for sentry installation on aws lambdas (js), I've noticed that in one place initialization file name is different from the rest (`instrumentation.mjs` instead of `instrument.mjs`), so I changed it to be consistent. …
=> docs(js): Fix incorrect instrument.mjs filename

platform-includes/performance/traces-sampler-as-sampler/ruby.mdx
Updates example for sample rate, to match PR for https://github.com/getsentry/sentry-ruby/pull/2403 - That means that we now follow "correct" Sentry op.name `queue.process`, instead of custom `sidekiq`. …
=> Adjust for sentry-ruby changes

develop-docs/sdk/data-model/event-payloads/debugmeta.mdx
While looking at the docs I saw that the `type` field for proguard is missing, this PR adds that field to fix the docs.
=> fix(proguard): Add type field for debug images doc

platform-includes/getting-started-config/javascript.cloudflare.mdx, platform-includes/performance/configure-sample-rate/javascript.cloudflare.mdx
=> docs(cloudflare): several semantic and stylistic fixes in code examples for cloudflare workers

docs/organization/integrations/feature-flag/unleash/index.mdx, docs/platforms/javascript/common/feature-flags/index.mdx
Forgot to link this in
- https://docs.sentry.io/platforms/javascript/feature-flags/
- https://docs.sentry.io/organization/integrations/feature-flag/unleash/
=> ref(flags): add missing links to unleash JS integration page

docs/platforms/javascript/common/configuration/options.mdx
This is deprecated and should not be used anymore.
=> feat(js): Drop `enableTracing` from docs

docs/platforms/java/common/configuration/filtering.mdx, platform-includes/configuration/ignore-errors/java.mdx, platform-includes/configuration/ignore-errors/java.spring-boot.mdx, platform-includes/configuration/ignore-exceptions/java.mdx, platform-includes/configuration/ignore-exceptions/java.spring-boot.mdx, platform-includes/configuration/ignore-transactions/java.mdx, platform-includes/configuration/ignore-transactions/java.spring-boot.mdx
Closes https://github.com/getsentry/sentry-java/issues/2660
=> Document `ignoredErrors` and `ignoredTransactions` for Java and Spring Boot

develop-docs/application-architecture/feedback-architecture.mdx, develop-docs/sdk/expected-features/index.mdx
Correct links to https://develop.sentry.dev/sdk/data-model/envelope-items/#user-report---deprecated
=> fix(feedback): fix broken links to user-report envelope item

develop-docs/integrations/github.mdx
Closes https://github.com/getsentry/self-hosted/issues/3509 …
=> docs(integrations): github app name must not contain any spaces

docs/platforms/kotlin/guides/kotlin-multiplatform/configuration/gradle.mdx
Gradle configuration had the wrong file name
Closes https://github.com/getsentry/sentry-kotlin-multiplatform/issues/319 …
=> fix(kmp): wrong field name in configuration

docs/platforms/javascript/guides/nextjs/manual-setup.mdx
Updates the manual setup docs to reflect latest Next.js version.
=> docs(js): Update Next.js instrumentation instructions

docs/platforms/native/common/configuration/options.mdx
This updates the documentation for the debug `option`. The existing documentation was already slightly out of date and this also adds documentation for a new default when running on debug-build: https://github.com/getsentry/sentry-native/pull/1128
=> feat(native): enable debug-option by default in debug-build.

docs/platforms/apple/common/tracing/instrumentation/custom-instrumentation.mdx, platform-includes/performance/improving-data/apple.mdx
Add docs for how to attach data onto span/transaction. Similar to https://github.com/getsentry/sentry-docs/pull/12367.
Fixes https://github.com/getsentry/sentry-docs/issues/12521.
=> feat(apple): Attach data onto a span/transaction

docs/platforms/dotnet/common/profiling/index.mdx, docs/platforms/dotnet/common/profiling/troubleshooting/index.mdx
=> enha: update .NET profiling docs after AddProfilingIntegration() was added

app/[[...path]]/page.tsx
Actually use the noindex frontmatter property to instruct search engines not to index pages that have it.
=> fix(docs): Instruct robots not to index pages that have `noindex` frontmatter property

src/components/platformFilter/client.tsx
makes the platform filter less fuzzy resulting in more relevant matches
=> fix: More precise home page platform search

src/middleware.ts
`yarn dev:developer-docs` starts a nextJs devServer on localhost:3000/, which immediately yields a 301 - Permanent Redirect to localhost:3000/getting-started/
since Permanent Redirects get cached by the browser, all other projects that start a devserver on localhost:3000 will then redirect to /getting-started/, which likely doesn't exist.
Since port 3000 is a popular port to be used in development, this permanent redirect can interfere with other projects, which is not a great DX (ask me how I know 😂 ).
This fix changes redirects to HTTP Status Code 302 in development mode, which is a temporary redirect that doesn't get cached by browsers; in production, it's still fine to issue 301, as caching by the browser will make the redirect faster
Help us prioritize incoming PRs by letting us know …
=> fix: don't do permanent redirects in dev mode

docs/platforms/react-native/manual-setup/metro.mdx
Adds answer to https://github.com/getsentry/sentry-react-native/issues/4459 directly to the docs. …
=> Add Custom Babel Transformers to Sentry Metro Plugin page

docs/product/issues/suspect-commits/index.mdx
=> Add SEO recommendations to suspect commits page

platform-includes/configuration/integrations/javascript.mdx
Caputure console integration works as error handler sending events to Sentry. 
Marking this integration as "error handler" on this page.
=> Mark captureconsole as error reporting integration

docs/contributing/pages/components.mdx
Updated the Components page in our "Contributing to Docs" to provide information on how to use the updated Alert and Expandable components.
#12466
#12468
closes https://github.com/getsentry/sentry-docs/issues/12053
=> update Contributing to Docs on Alert and Expandable components

docs/contributing/pages/components.mdx
There was a small display issue caused by improperly formatted text (missing space between paragraphs).
I've updated it so that everything looks as it should.
=> fix text formatting in Contributing to the Docs 

docs/product/insights/ai/index.mdx, includes/performance-moving.mdx
work for https://github.com/getsentry/sentry/issues/81492
The ai overview page is going away for now, so we should remove any references to it.
=> docs(insights): remove ai overview page docs

platform-includes/performance/improving-data/ruby.mdx
see https://github.com/getsentry/team-sdks/issues/122
=> feat(ruby): Add snippet for adding data to transaction and all its spans

docs/platforms/apple/guides/ios/session-replay/index.mdx
This is based on the change in https://github.com/getsentry/sentry-java/pull/3741
* redactAllText and redactAllImages are no longer valid in Xcode, and have been replaced with maskAllText and maskAllImages
- [ X] None: Not urgent, can wait up to 1 week+ …
=> Change redactAllText and redactAllImages to maskAllText and maskAllImages

package.json, yarn.lock
This PR bumps the platformicons dependency to version [8.0.0](https://www.npmjs.com/package/platformicons/v/8.0.0), based on the changes introduced in the [PR](https://github.com/getsentry/platformicons/pull/198).
=> chore: Bump platformicons

docs/platforms/javascript/guides/aws-lambda/tracing/instrumentation/automatic-instrumentation.mdx, docs/platforms/javascript/guides/ember/tracing/instrumentation/automatic-instrumentation.mdx, docs/platforms/javascript/guides/gcp-functions/tracing/instrumentation/automatic-instrumentation.mdx, includes/node-automatic-instrumentation.mdx
Removing remaining mentions of this deprecated/removed options for JS.
=> ref(js): Remove `enableTracing` mentions

docs/platforms/javascript/common/enriching-events/breadcrumbs/index.mdx
This log level does not actually exist there.
Fixes https://github.com/getsentry/sentry-javascript/issues/15293
=> fix(js): Remove `critical` as breadcrumb log level

src/components/platformCategorySection.tsx, src/types/platform.tsx
Let's see if this breaks somehow, but I can't see anything in the code that would actually use the enums directly 🤔
=> ref: Remove TS enums in favor of type constant strings

docs/platforms/dotnet/common/configuration/options.mdx, docs/platforms/powershell/configuration/options.mdx, docs/platforms/unity/configuration/options.mdx
The .NET SDK removed the option `enable tracing` [here](https://github.com/getsentry/sentry-dotnet/pull/3569) that has been part of the `5.0.0` release.
=> fix(.NET): Removed `enable-tracing` from options

redirects.js
=> fix: 2fa 404

docs/platforms/javascript/common/migration/v8-to-v9.mdx
Adds the migration guide for v9 of the JS SDK.
Resolves https://github.com/getsentry/sentry-javascript/issues/14290
=> Add JS v9 migration guide

docs/platforms/javascript/guides/nextjs/configuration/build/index.mdx
This updates `/platforms/javascript/guides/nextjs/configuration/build/` to include all build options from `withSentryConfig` – the data basically mirrors our ts interface.
=> docs(js): Update build options for Next.js

docs/platforms/rust/common/tracing/instrumentation/custom-instrumentation.mdx
Closes https://github.com/getsentry/sentry-rust/issues/733
To be merged after the required changes are merged and released in the SDK
=> feat(rust): add instructions on how to add data to a span/transaction

docs/pricing/index.mdx
Minor update to add included uptime monitor to pricing page
=> Add uptime monitor to included pricing

docs/product/releases/index.mdx
Minor Edits based on recommendations from our SEO agency.  …
=> Implement SEO recs

docs/product/explore/discover-queries/index.mdx
Minor Edits based on recommendations from our SEO agency. …
=> implement SEO recs discover page

docs/platforms/javascript/guides/cloudflare/frameworks/remix.mdx, docs/platforms/javascript/guides/remix/frameworks/hydrogen.mdx
Fixes the Cloudflare setup page in Remix. As the page is inside the platform "Remix" it showed the Remix wizard setup in the `PlatformContent`.
issue mentioned in a comment: https://github.com/getsentry/sentry-javascript/issues/5610#issuecomment-2637594290
=> fix(cloudflare): Use correct setup snippets for Hydrogen

docs/platforms/elixir/integrations/oban/index.mdx
We added a new feature to the Elixir SDK. This is docs for it.
=> Add new feature to Oban docs (Elixir)

docs/platforms/javascript/common/configuration/filtering.mdx, includes/platforms/configuration/options/warn-before-send-span.mdx, platform-includes/configuration/before-send-span/javascript.mdx
This pr updates the documentation of the behaviour of `beforeSendSpan` in the v9 JS SDK.
documents https://github.com/getsentry/sentry-javascript/pull/14831
=> docs(v9/js): Update beforeSendSpan documentation

docs/platforms/javascript/common/configuration/sampling.mdx, platform-includes/performance/sampling-function-intro/javascript.mdx, platform-includes/performance/traces-sampler-as-sampler/javascript.mdx
Swaps over to documenting `inheritOrSampleWith` over parentSampled as migration guide for v9. Wasn't done with a versioned docs page because it was too annoying.
Resolves https://github.com/getsentry/sentry-javascript/issues/15124
=> [v9] Encourage using `inheritOrSampleWith` for `tracesSampler` in js

src/components/codeBlock/code-blocks.module.scss
Right now the Rust index page shows up like this
The reason is that the `table` class is applied to `[dependencies]`, and that class has `display: table`.
This fixes that.
=> fix(rust): fix strange formatting of Cargo.toml in Rust index page

docs/platforms/java/guides/spring-boot/index.mdx, docs/platforms/java/guides/spring/index.mdx
At the moment, due to the fact that they are merged with the Java guide, the "using a framework" alert shows up in the Spring and Spring Boot guides. This should not happen, as Spring and Spring Boot are frameworks.
This PR separates Spring and Spring Boot onboarding guides from the Java ones to avoid this.
It also adds subtitles to the pages e.g. "Learn how to use Sentry's Spring Boot SDK".
The content of the guides remains the same.
=> ref(java): separate Spring and Spring Boot guides from Java guide

develop-docs/frontend/strict-typescript-settings-guide.mdx
This PR adds a new guide for working with strict compiler settings in the frontend section, as we’ve recently enabled `noImplicitAny` and `noUncheckedIndexedAccess` in `tsconfig.json`.
The goal of this guide is to give developers an overview of the most common issues they might now face, with examples how to fix and avoid them.
=> feat(frontend):add guide for strict typescript settings

src/components/platformCategorySection.tsx, src/components/platformSection.tsx
Decided not to merge it due to logical conflicts (e.g. should category take precedence over name ?) and instead add docs so the user can decide which component (or a combination of both to use).
closes https://github.com/getsentry/sentry-docs/issues/12086
=> chore: Add jsdocs for `PlatformSection` and `PlatformCategorySection`

src/components/focus-active-link.tsx
The current behavior of the sidebar is is jarring when dealing with items below the fold
this PR makes it smarter and behave as expected
closes #10978
=> fix: smarter sidebar scrolling behavior

docs/platforms/javascript/common/configuration/integrations/childProcess.mdx
***SHOULD NOT BE MERGED BEFORE JAVASCRIPT V9 RELEASE***
- Ref https://github.com/getsentry/sentry-javascript/pull/15105
=> feat(v9/node): `childProcessIntegration` additional features

src/components/header.tsx, src/components/search/index.tsx
Since we integrated ai into our search, the response quality has suffered (bc users mostly just search for keywords in the search bar) which is why we want to try a hybrid approach.
This pr brings back the ASK AI button next to the search input
=> feat(platform): Add ask ai button

platform-includes/debug-information-files/_default.mdx
A user did not know we support uploading PE files which costed them some hours of debugging
=> chore(debug-files): Mention PE files in the top-level debug files list

src/components/search/index.tsx
This pr removes the `Explain ...` prefix when opening kapa ai from search
=> fix: Update default kapa query

docs/platforms/python/integrations/litestar/index.mdx
See https://github.com/getsentry/sentry-python/pull/4021 …
=> docs(litestar): Document `failed_request_status_codes`

docs/product/issues/issue-views/index.mdx
Updates the Issue Views docs to reflect the fact that page filters now save to views.
This feature is slated to release on Thursday, Feb 13th
(This feature has not been released just yet, and I will not merge these docs changes until it is)
=> docs(issue-views): Update Issue Views docs to reflect page filter persistence

develop-docs/sdk/data-model/envelope-items.mdx
Mark both statsd and metric meta envelope items as deprecated.
=> fix: Mark metric envelope items as deprecated

docs/platforms/python/profiling/index.mdx
The newly introduced `profile_session_sample_rate` defaults to `0.0` and needs to be set to use continuous profiling. …
=> docs(profiling): Add profile_session_sample_rate docs for python

platform-includes/getting-started-primer/java.spring-boot.mdx
The linked GitHub projects contain a "main" instead of "master" branch.
=> fix: links

docs/platforms/javascript/common/configuration/integrations/statsig.mdx, docs/platforms/javascript/common/feature-flags/index.mdx, platform-includes/configuration/integrations/javascript.mdx, platform-includes/configuration/statsig/javascript.angular.mdx, platform-includes/configuration/statsig/javascript.astro.mdx, platform-includes/configuration/statsig/javascript.ember.mdx, platform-includes/configuration/statsig/javascript.gatsby.mdx, platform-includes/configuration/statsig/javascript.mdx, platform-includes/configuration/statsig/javascript.nextjs.mdx, platform-includes/configuration/statsig/javascript.nuxt.mdx, platform-includes/configuration/statsig/javascript.react.mdx, platform-includes/configuration/statsig/javascript.remix.mdx, platform-includes/configuration/statsig/javascript.solid.mdx, platform-includes/configuration/statsig/javascript.solidstart.mdx, platform-includes/configuration/statsig/javascript.svelte.mdx, platform-includes/configuration/statsig/javascript.sveltekit.mdx, platform-includes/configuration/statsig/javascript.vue.mdx
Documents
- https://github.com/getsentry/sentry-javascript/pull/15319
- https://github.com/getsentry/sentry-javascript/pull/15347
Adding platform specific config after feedback on javascript
Ref 
- https://github.com/getsentry/team-replay/issues/536
=> feat(flags): document statsig browser integration

docs/platforms/native/configuration/transports.mdx
Related to https://github.com/getsentry/sentry-native/pull/1111
=> feat(native): honor `http_proxy` environment variables

docs/platforms/android/data-management/data-collected.mdx, docs/platforms/java/common/data-management/data-collected.mdx
Closes https://github.com/getsentry/sentry-java/issues/4118
Closes https://github.com/getsentry/sentry-java/issues/4092 …
=> Document what data Java/Android SDK collects

docs/platforms/python/feature-flags/index.mdx, docs/platforms/python/integrations/index.mdx, docs/platforms/python/integrations/statsig/index.mdx
Documents
- https://github.com/getsentry/sentry-python/pull/4022
Ref
- https://github.com/getsentry/team-replay/issues/536
=> feat(flags): document statsig python integration

docs/platforms/apple/common/configuration/app-hangs.mdx, docs/platforms/apple/common/features/experimental-features.mdx
The SDK will measure the duration of app hangs on version 8.45.0 and above.
=> feat(apple): Add duration of app hangs

src/components/communitySupportedPlatforms/index.tsx
I changed the list of community sdks into a `<ul>`
I ran the indexing locally, it seems to pick them up
closes  #12639
=> fix: index index community sdks

docs/platforms/python/integrations/statsig/index.mdx, docs/platforms/python/integrations/unleash/index.mdx
This should be mentioned explicitly in the doc for [unleash](https://docs.sentry.io/platforms/python/integrations/unleash/), not in the tab title. For statsig, this is wrong/irrelevant (accidental copy-paste)
=> ref(flags): remove is_enabled note from unleash and statsig python docs

develop-docs/sdk/expected-features/index.mdx
Updating the dev docs, as this option is set to `medium` by default in (almost) all of the SDKs.
=> feat(dev-docs): update `maxRequestBodySize` default to `medium`

platform-includes/feature-flags/next-steps/_default.mdx, platform-includes/feature-flags/next-steps/javascript.mdx, platform-includes/feature-flags/next-steps/python.mdx
Takes users directly to the FF index page for their platform. 
- [js](https://docs.sentry.io/platforms/javascript/feature-flags/#enable-evaluation-tracking)
- [python](https://docs.sentry.io/platforms/python/feature-flags/#enable-evaluation-tracking)
Right now:
https://docs.sentry.io/product/issues/issue-details/feature-flags/
Also the current links are "half broken" - take you to the right page, but not the section defined by `#`. Think this is cause the [redirect](https://github.com/getsentry/sentry-docs/blob/2de5e4661624350efad0feaafef8136a4b49ea8f/redirects.js#L963-L966)
=> ref(flags): use platform specific links for next steps alert

src/middleware.ts
This was resulting in being unable to view these docs for javascript.
Confirmed [/platforms/javascript/security-policy-reporting/](https://sentry-docs-git-mrduncan-fix-javascript-security-redirect.sentry.dev/platforms/javascript/security-policy-reporting/) is now working correctly.
=> fix(csp): Remove javascript redirect

docs/platforms/apple/common/data-management/data-collected.mdx
Add a page to describe which data the Apple SDK collects.
Fixes GH-12751
=> feat: Add Apple Data Collected Page

docs/platforms/apple/common/install/cocoapods.mdx, docs/platforms/apple/common/troubleshooting/index.mdx
Adds a note to the getting started page in to disable user script sandboxing when using Cocoapods, with details on the issue in the troubleshooting guide.
=> feat(apple): add troubleshooting for Cocoapods user script sandbox setup

docs/platforms/javascript/common/index.mdx, includes/nextjs-turbopack-warning-expandable.mdx, platform-includes/getting-started-prerequisites/_default.mdx, platform-includes/getting-started-verify/javascript.nextjs.mdx
- Created a new file in `/includes` for Next.js Turbopack warning 
- Created a new folder `/getting-started-prerequisites` in `/platform-includes` and a file containing the "prerequisites" content for quick start guides (only javascript for now)
- replaced content with includes 
Issue: #12700 
=> Create and use includes for quick start prerequisites and Next.js Turbopack warning

docs/concepts/search/searchable-properties/issues.mdx
Part of https://github.com/getsentry/sentry-docs/issues/12776
=> Add note for FF search in Searchable Properties page for Issues.mdx

docs/platforms/javascript/common/feature-flags/index.mdx, docs/platforms/python/feature-flags/index.mdx, platform-includes/feature-flags/change-tracking-list/_default.mdx
Restructures both generic eval tracking descriptions at:
https://docs.sentry.io/platforms/python/feature-flags/
| Before    | After |
| -------- | ------- |
| <img width="570" alt="Screenshot 2025-02-18 at 4 13 42 PM" src="https://github.com/user-attachments/assets/5359c61f-ff47-4708-8da2-40f804040eaa" />  | <img width="383" alt="Screenshot 2025-02-18 at 4 15 32 PM" src="https://github.com/user-attachments/assets/1f6171ba-3708-449c-86ed-aac26b5e2326" />   |
https://docs.sentry.io/platforms/javascript/feature-flags/
| Before    | After |
| -------- | ------- |
| <img width="558" alt="Screenshot 2025-02-18 at 4 16 23 PM" src="https://github.com/user-attachments/assets/e694397d-6659-4d8a-bbfa-ab8f1570948e" />  | <img width="380" alt="Screenshot 2025-02-18 at 4 16 38 PM" …
=> ref(flags): restructure generic api and integration docs

develop-docs/sdk/expected-features/index.mdx
In Java SDK, these are no longer default = `false` but `true` since v7. …
=> Update HTTP Client Errors default for `captureFailedRequests`

docs/platforms/javascript/guides/electron/index.mdx
Much of the docs around native crashes in child processes was outdated for the Electron versions we support. I've replaced it with a table detailing what child processes are supported on each platform.
=> feat(electron): Update child process details

platform-includes/getting-started-install/javascript.nextjs.mdx, platform-includes/getting-started-next-steps/javascript.nextjs.mdx
Some small updates based on the feedback received on the Next.js manual quick start guide:
- added new item to the "What does the installation wizard change inside your application?" list
- updated title of the Expandable that offers user support if they have issues setting up the SDK
=> docs(nextjs): Minor updates on manual guide

docs/platforms/dart/configuration/options.mdx, docs/platforms/dart/data-management/data-collected.mdx, docs/platforms/dart/index.mdx, docs/platforms/flutter/configuration/options.mdx, docs/platforms/flutter/data-management/data-collected.mdx, docs/platforms/flutter/index.mdx
Add details about data collection and the `sendDefaultPii` flag to the getting started
closes https://github.com/getsentry/sentry-dart/issues/2692
closes https://github.com/getsentry/sentry-dart/issues/2691
=> feat(dart & flutter): add data collected page and `sendDefaultPii` to getting started

develop-docs/self-hosted/troubleshooting/sentry.mdx
Closes https://github.com/getsentry/self-hosted/issues/2962 …
=> docs(self-hosted): troubleshooting guide for errors caused of minified assets by CDNs

docs/platforms/javascript/guides/electron/configuration/integrations/mainprocesssession.mdx, platform-includes/configuration/auto-session-tracking/javascript.electron.mdx
When v6 of the Electron SDK is releases, `autoSessionTracking` has been removed so sessions can be disabled by filtering out the session integration.
=> feat(electron): Disable sessions now `autoSessionTracking` has been removed

docs/platforms/javascript/common/configuration/integrations/unleash.mdx, docs/platforms/python/integrations/unleash/index.mdx
Our Unleash implementation patches the `is_enabled`/`isEnabled` method only. Let's mention this method to avoid potential confusion.
`is_enabled` is the main way users evaluate boolean flags, but you could technically use the result of `get_variant` too. We chose not to support the latter which is explained in depth on https://github.com/getsentry/sentry-python/pull/3914
=> ref(flags): mention is_enabled method for Unleash eval tracking

src/components/platformIcon.tsx
Fixes the logo to the correct one for `actix-web`, which was previously showing up with the Rust logo instead because `rust-actix` didn't match the platform name.
=> fix(rust): fix logo for actix-web

platform-includes/enriching-events/set-user/apple.mdx
Add a comment to the setUser code snipped to point out users have to start the SDK before.
=> feat(apple): Start the SDK before calling setUser

docs/platforms/dotnet/common/configuration/options.mdx, docs/platforms/unity/configuration/options/index.mdx
Added documentation to the new `BeforeCapture` callbacks for `ViewHierarchy` and `Screenshots` added in https://github.com/getsentry/sentry-unity/pull/2023
Also updated the naming of the hooks in the .NET SDK as they changed to `SetBeforeX` in https://github.com/getsentry/sentry-dotnet/pull/2351
=> feat(Unity): `BeforeCapture` hooks for `ViewHierarchy` and `Screenshots`

docs/platforms/java/common/configuration/options.mdx
Closes https://github.com/getsentry/sentry-docs/issues/12105
=> fix(java): mention that send-default-pii must be enabled for HTTP request bodies to be captured

develop-docs/self-hosted/index.mdx
There is been a typo in docs and self-hosted PR title which has been reported in https://github.com/getsentry/self-hosted/issues/3582. This PR will fix that.
- [Sentry Docs …
=> Fix self-hosted minimum docker compose version

redirects.js
Follow up on https://github.com/getsentry/sentry/pull/85677
New page live: https://docs.sentry.io/api/replays/retrieve-a-count-of-replays-for-a-given-issue-or-transaction/
=> ref(replays): add redirect for new replay count api doc

docs/platforms/unreal/configuration/setup-crashreporter/index.mdx
This PR adds a side-by-side comparison of the two crash-capturing tools available for Unreal Engine: the default Crash Reporter and Sentry's UE plugin.
Related to https://github.com/getsentry/sentry-unreal/issues/704
Supersedes #12763
=> Add UE Crash Reporter and Sentry Unreal SDK comparison

platform-includes/crons/setup/php.laravel.mdx
Some subtle differences how and where you define scheduled tasks between different Laravel versions.
=> [laravel] Version specific Cron guides

docs/platforms/javascript/common/session-replay/configuration.mdx, docs/platforms/javascript/common/session-replay/understanding-sessions.mdx
Clarifies that beforeErrorSampling is only triggered in `buffer` mode.
closes https://github.com/getsentry/sentry-javascript/issues/15470
=> docs(replay): Clarify beforeErrorSampling

docs/platforms/react-native/index.mdx, docs/platforms/react-native/manual-setup/expo.mdx
The line numbers of the code snippet are off and the buttons to show and hide do not work because of that.
This also added the options to the Expo setup and moved the buttons closer to the code.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional …
=> Fix React Native Onboarding Option Buttons

platform-includes/sourcemaps/overview/javascript.mdx
This alert seems unnecessary for Server-side JS SDKs. …
=> Only show Browser vs React Native source maps alert for browser sdks

docs/platforms/apple/common/data-management/data-collected.mdx
Document the only usage of sendDefaultPii in the Cocoa SDK. See [Cocoa SDK](https://github.com/search?q=repo%3Agetsentry%2Fsentry-cocoa+sendDefaultPii+&type=code).
Fixes GH-12751
=> fix(apple): Usages of sendDefaultPii

platform-includes/configuration/before-send/dart.mdx, platform-includes/configuration/before-send/flutter.mdx
Fix incorrect documentation on how to remove/reset event values.
Relates to https://github.com/getsentry/sentry-dart/issues/2672
- [[v9]: Not possible to remove information in beforeSend (make SentryEvent and related classes mutable)](https://github.com/getsentry/sentry-dart/issues/2672)
=> docs(flutter): Fix event serverName reset in samples

docs/platforms/python/tracing/instrumentation/custom-instrumentation/index.mdx, platform-includes/distributed-tracing/custom-instrumentation/python.mdx
There was some [confusion](https://github.com/getsentry/sentry-python/issues/4096) regarding `start_transaction` and how it can be used, so adding a clarifying comment to the docs.
Also fixing a couple of typos found along the way. …
=> feat(python): Clarification regarding start_transaction

docs/platforms/android/overhead/index.mdx, docs/platforms/apple/common/overhead/index.mdx, docs/platforms/dart/overhead/index.mdx, docs/platforms/flutter/overhead/index.mdx, docs/product/explore/profiling/getting-started.mdx
Some broken links are breaking builds right now, this PR fixes them. …
=> Fix broken links

platform-includes/troubleshooting/dotnet.mdx
As concluded in  https://github.com/getsentry/sentry-dotnet/issues/3889 Hot Reload isn't supported with static libraries. Adding a note to the troubleshooting page.
Closes getsentry/sentry-dotnet#3959
=> Adding unsupported hot reload

docs/platforms/java/common/integrations/reactor.mdx
Adds docs for the new Reactor integration
Part of https://github.com/getsentry/sentry-java/issues/3144
=> feat(java): add Reactor integration docs

docs/platforms/javascript/guides/nextjs/manual-setup.mdx, platform-includes/capture-error/javascript.nextjs.mdx
In the process of reworking the Next.js Manual Setup page, we need to move content to other places.
This PR focuses on the "Capturing Errors" related information from the setup page.
What I did:
- added a "Capturing Errors in `error.js` Files" subsection to Capturing Errors and Events page & moved content from the "Manual Setup" page to it
=> move content about error capturing to "Capturing Errors and Events" from "Manual Setup" (Next.js)

docs/platforms/python/integrations/asyncio/index.mdx
Also, remove the information about tracing and performance; it is not really relevant to the rest of the content on this page, and hovering over the "?" icon on the selection boxes explains what these do.
=> docs(python): Clarify how to init SDK in `async` app

docs/platforms/javascript/common/configuration/integrations/unleash.mdx, platform-includes/configuration/unleash/javascript.ember.mdx, platform-includes/configuration/unleash/javascript.gatsby.mdx, platform-includes/configuration/unleash/javascript.mdx, platform-includes/configuration/unleash/javascript.nextjs.mdx, platform-includes/configuration/unleash/javascript.nuxt.mdx, platform-includes/configuration/unleash/javascript.react.mdx, platform-includes/configuration/unleash/javascript.remix.mdx, platform-includes/configuration/unleash/javascript.solid.mdx, platform-includes/configuration/unleash/javascript.solidstart.mdx, platform-includes/configuration/unleash/javascript.svelte.mdx, platform-includes/configuration/unleash/javascript.sveltekit.mdx, platform-includes/configuration/unleash/javascript.vue.mdx
Documents changes made in 
https://github.com/getsentry/sentry-javascript/pull/15343/files
https://github.com/getsentry/sentry-javascript/pull/15345/files
v8 update not released yet, not merging until then (see TODO)
=> ref(flags): update unleashIntegration param

docs/product/insights/getting-started.mdx
In a new organization, when I navigate to performance monitoring or the mobile/frontend/backend products within insights, I encounter the following empty state:
By clicking on the 'Set Up' button I am redirected to
This happens because, in the PR, we moved all the performance docs to insights, but the "Getting Started" documentation was [deleted](https://github.com/getsentry/sentry-docs/pull/12720/files#diff-c96d9efe4a56b03fc4212c0a817f04ccb2997fa35b7026d4376f4e6e87df43a6). I attempted to find similar documentation, but we don't have anything available. Therefore, I am restoring it, now under insights, fixing the issue but we'll need to update the copies accordingly cc @DominikB2014
=> fix(insights): Fix broken getting-started link

docs/platforms/javascript/guides/react-router/config.yml, platform-includes/getting-started-config/javascript.react-router.mdx, platform-includes/getting-started-install/javascript.react-router.mdx, platform-includes/getting-started-primer/javascript.react-router.mdx, platform-includes/getting-started-sourcemaps/javascript.react-router.mdx
Updates the react router guide to use the new rr package.
Closes https://github.com/getsentry/sentry-javascript/issues/15191
**Only merge this once the package got published and verified!**
=> docs(react-router): Update guide for `@sentry/react-router`

src/middleware.ts
When navigating through the `/sourcemaps/troubleshooting_js/legacy-uploading-methods/` pages, when I click on the nextjs platform, I am redirected to the javascript, which is not expected. see:
https://github.com/user-attachments/assets/574529d6-2bc5-4f31-8fe2-2865444eaa82
=> fix(nextjs-redirects): Fix unexpected nextjs redirects

docs/platforms/javascript/guides/react/features/component-names.mdx
Adds a note on ignoring component annotation option.
ref https://github.com/getsentry/sentry-javascript-bundler-plugins/issues
=> docs(react): Add note on ignoring components

redirects.js
Using a wildcard is better than listing things out one-by-one.
I checked locally that `/product/dev-toolbar/` redirects to `/product/sentryr-toolbar/` and also `/product/dev-toolbar/setup/` continues going to `/product/sentry-toolbar/setup/`
Relates to https://github.com/getsentry/sentry-docs/issues/12876
=> fix(toolbar): Fix redirects for all /dev-toolbar/ to be /sentry-toolbar/

package.json, yarn.lock
Needed for https://github.com/getsentry/sentry-docs/security/dependabot/157
=> chore(deps): Bump vitest to 3.0.7

src/components/search/index.tsx
Receiving errors on this function not being available, added a fallback
=> fix(platform): Add fallback for crypto.randomUUID()

src/components/track-reader-depth.tsx
Seeing this error come up quite frequently on legacy browsers.
=> fix(platform): Replace findLast() with filter().pop()

src/components/platformSelector/style.module.scss
This was super jarring to my eyes for some reason.
Before:
After:
There is still a vertical alignment issue I believe but I couldn't be bothered to fix rn.
=> style: Adjust gap for icons in platform selector

src/components/codeKeywords/orgAuthTokenCreator.tsx, src/components/orgAuthTokenNote.tsx
Users sometimes commit their auth tokens because the docs don't communicate that this is something that should be kept secret.
While we have warnings about not committing the token in our [wizard here](https://github.com/getsentry/sentry-wizard/blob/f89b4f80731da8857a5a1bd4ab32d93b9a6ba898/src/sourcemaps/sourcemaps-wizard.ts#L304), there is no warning when just following the docs.
=> fix(auth-creator): Add warnings to not commit token

docs/platforms/javascript/common/configuration/filtering.mdx
=> Add minor SEO edits for js/filtering

develop-docs/self-hosted/sso.mdx
Closes https://github.com/getsentry/self-hosted/issues/3481 …
=> docs(self-hosted): remove deprecated github sso auth config

docs/platforms/dotnet/common/configuration/heap-dumps.mdx
Documentation for the functionality added in https://github.com/getsentry/sentry-dotnet/pull/3667
- cc: @aritchie @bruno-garcia 
=> Added documentation for automatic heap dumps

src/components/codeBlock/codeBlock.spec.ts, src/components/codeBlock/index.tsx, vitest.config.mjs
Code blocks can contain diff markers (+ or -) at the beginning of code blocks which get copied as well when copying the code. 
This modifies the function for copying code on click and adds an effect to handle copy-events initiated manually (not by clicking "copy code".
closes https://github.com/getsentry/sentry-docs/issues/12802
=> feat(code-block): Do not copy diff markers

docs/api/index.mdx
Adjustments to getting started steps, breaking tutorials out into separate header, 
=> reverting changes to sentry api reference landing

docs/platforms/javascript/common/migration/v8-to-v9.mdx
Correct typos according to https://github.com/getsentry/sentry-javascript/blob/8973d5301d0991d7548e64a842bdb1a50682f11a/packages/core/src/types-hoist/options.ts#L25. …
=> fix: correct typo in javascript v8-to-v9.mdx

platform-includes/getting-started-sourcemaps/javascript.react-router.mdx
I was testing the new `@sentry/react-router` SDK and followed the guide to upload my sourcemaps and noticed it didn't. Upon closer look I found out the `sentryOnBuildEnd` is a Promise and thus should be awaited. …
=> docs(react-router): update sourcemaps buildEnd hook snippet

docs/organization/integrations/feature-flag/generic/index.mdx, docs/organization/integrations/feature-flag/launchdarkly/index.mdx, docs/organization/integrations/feature-flag/statsig/index.mdx, docs/organization/integrations/feature-flag/unleash/index.mdx
The old settings w/"Add New Provider" is now nested under `/change-tracking`
=> ref(flags): update change tracking settings links

.github/ISSUE_TEMPLATE/issue-content-01-sdks.yml, .github/ISSUE_TEMPLATE/issue-content-02-product.yml, .github/ISSUE_TEMPLATE/issue-content-03-develop.yml, .github/ISSUE_TEMPLATE/issue-platform-404.yml, .github/ISSUE_TEMPLATE/issue-platform-bug.yml, .github/ISSUE_TEMPLATE/issue-platform-improvement.yml
- Automatically apply issue types to new issues
- Remove legacy labels for `improvement` and `bug`
=> chore(github): Use issue types in templates

develop-docs/self-hosted/configuration.mdx, develop-docs/self-hosted/index.mdx, develop-docs/self-hosted/releases.mdx
The configuration section is too cluttered for me. Trying to shift things over, and then I can put the "Architecture Reference" section (referenced here https://github.com/getsentry/self-hosted/issues/3585) …
=> docs(self-hosted): move configuration guide outside of index

docs/platforms/javascript/guides/remix/frameworks/hydrogen.mdx
Documents: https://github.com/getsentry/sentry-javascript/pull/15450
Resolves: https://github.com/getsentry/sentry-docs/issues/12885
=> Update Remix Hydrogen Docs

src/components/codeKeywords/orgAuthTokenCreator.tsx
This pr will wrap all code snippets containing a generated auth token, so it is apparent to our users when they only copy partial token.
Decided against generally wrapping all code snippets because it messes up ALL of our comments.
before:
after:
closes https://github.com/getsentry/sentry-docs/issues/11999
=> fix(platform): Wrap auth token code snippets

docs/platforms/javascript/common/sourcemaps/index.mdx, platform-includes/sourcemaps/overview/javascript.mdx, platform-includes/sourcemaps/primer/javascript.mdx
=> Add minor SEO updates

docs/platforms/javascript/common/configuration/filtering.mdx, platform-includes/configuration/filter-application-key/javascript.mdx, platform-includes/configuration/filter-application-key/javascript.nextjs.mdx, platform-includes/configuration/filter-application-key/javascript.nuxt.mdx, platform-includes/configuration/filter-application-key/javascript.react-router.mdx, platform-includes/configuration/filter-application-key/javascript.solidstart.mdx, platform-includes/configuration/filter-application-key/javascript.sveltekit.mdx
The code snippets for adding options to the bundler plugins in Meta-framework SDKs are misleading as they show usage of each bundler plugins. However, the Meta-frameworks already include those plugins under the hood and the options should be passed differently. 
related to this issue: https://github.com/getsentry/sentry-javascript/issues/13286
=> docs(js): Add Meta-framework settings for filter integration

docs/platforms/android/integrations/apollo4/index.mdx, docs/platforms/java/common/tracing/instrumentation/apollo4.mdx
Adds docs for the (to be released) Apollo 4 integration https://github.com/getsentry/sentry-java/pull/4166
To be merged after release
The content is copied from Apollo 3 docs. I have only changed imports and removed the callout speaking about version 4 being not supported by Sentry.
=> feat(android): add Apollo 4 docs

docs/platforms/android/integrations/apollo2/index.mdx, docs/platforms/java/common/tracing/instrumentation/apollo2.mdx
Updates "Apollo" to be renamed to "Apollo 2" to avoid confusion as we already have "Apollo 3" and soon we will have "Apollo 4".
Also updates the callout about the versions to point to the upcoming "Apollo 4" docs pages.
Comes after https://github.com/getsentry/sentry-docs/pull/12729 
=> ref(android): rename Apollo 2 to mention version and update callout

docs/platforms/apple/common/configuration/app-hangs.mdx
Add docs for fatal app hangs starting with Cocoa SDK 8.46.0.
=> feat(apple): Add fatal app hangs

docs/organization/authentication/sso/index.mdx
Added a specification on the last step for setting up JumpCloud SSO. This should avoid confusion on which attributes to use.
=> Clarify JumpCloud SSO actions

develop-docs/sdk/data-model/event-payloads/exception.mdx
The `source` property as described in the RFC was missing: 
https://github.com/getsentry/rfcs/blob/main/text/0079-exception-groups.md#source …
=> Added missing exception mechanism property.

docs/platforms/android/configuration/options.mdx, docs/platforms/java/common/configuration/options.mdx
Fixes the docs around in-app-includes and excludes for Android and Java.
Relevant Android PR: https://github.com/getsentry/sentry-java/pull/4240 …
=> chore(Android): Update docs to match actual SDK behavior

platform-includes/distributed-tracing/custom-instrumentation/android.mdx, src/middleware.ts
Now `/apollo` will redirect to the newest `/apollo4`.
Mentioned and linked to `apollo2` explicitly where needed.
=> Fix Apollo links

src/components/sandboxLink.tsx
- Part of https://github.com/getsentry/projects/issues/87
- Changes the sandbox link to point to the new sandbox available at: https://sandbox.sentry.io/ 
- Will be merged after the new sandbox is publicly available
=> chore(demo-mode): change sandbox link

docs/platforms/javascript/guides/solidstart/index.mdx
The docs for Solid Start still had a mention to `sentrySolidStartVite` which we removed with v9. …
=> fix(solidstart): Remove outdated `sentrySolidStartVite` option

develop-docs/application-architecture/feedback-architecture.mdx
Thread: https://github.com/getsentry/sentry-dotnet/pull/3981#discussion_r1986119049
=> fix(feedback): rm per-feedback attach limit

src/middleware.ts
404 lints work fine but the link can still be reachable from Google
Closes https://github.com/getsentry/sentry-docs/issues/12969
=> Add redirect for Apollo Java link still reachable from Google that 404s

docs/platforms/javascript/guides/gatsby/index.mdx
Contributes to https://github.com/getsentry/projects/issues/799
=> fix(gatsby): make it clear where to put Sentry SDK config

docs/platforms/javascript/guides/remix/frameworks/hydrogen.mdx
Updates the example to make sure `instrumentBuild` runs after SDK initialization.
=> fix(remix): Move `instrumentBuild` inside `fetch` callback.

docs/platforms/native/advanced-usage/backend-tradeoffs/index.mdx
Related to Native SDK PR https://github.com/getsentry/sentry-native/pull/1152
=> feat(native): add Crashpad retry mechanism

docs/platforms/unreal/data-management/store-minidumps-as-attachments/index.mdx
on Android we have our own stack walker, and we don't capture minidumps.
=> unreal minidump not on android

platform-includes/getting-started-config/ruby.resque.mdx
closes https://github.com/getsentry/sentry-ruby/issues/1772
=> feat(ruby): Add note about RUN_AT_EXIT_HOOKS=1 for resque

develop-docs/frontend/network-requests.mdx
Small typo fix I noticed reading through the developer docs under frontend network requests.
=> fix(develop): Import hook instead of queryClient

platform-includes/getting-started-config/javascript.angular.mdx
while working on #12983 I noticed that the highlighted line numbers were all over the place. This PR fixes them for Angular Getting Started
=> fix(angular): Adjust highlighted line numbers in getting started snippets

docs/organization/integrations/debugging/index.mdx, docs/organization/integrations/debugging/sourcery/index.mdx, docs/organization/integrations/index.mdx
=> Masinette sourcery integration

docs/platforms/python/configuration/filtering/index.mdx
We can do a better job being more clear about the `Event` and `Hint` types that are handy for callbacks like `before_send`, see https://github.com/getsentry/sentry-python/issues/4122. …
=> feat(python): Add a note about the Event and Hint types

platform-includes/getting-started-install/java.jul.mdx, platform-includes/getting-started-install/java.log4j2.mdx, platform-includes/getting-started-install/java.logback.mdx, platform-includes/getting-started-install/java.mdx, platform-includes/getting-started-install/java.servlet.mdx, platform-includes/getting-started-install/java.spring-boot.mdx, platform-includes/getting-started-install/java.spring.mdx
The OTEL option will now be checked by default on the getting started guides for Java backend platforms.
OTEL is fully integrated with the SDK by now and improves scopes and trace propagation.
It can be enabled independently from tracing, which we still leave unchecked by default.
=> feat(java): enable OTEL by default in onboarding options

docs/platforms/javascript/common/opentelemetry/custom-setup.mdx, docs/platforms/javascript/common/opentelemetry/using-opentelemetry-apis.mdx
This fixes some things pointed out in https://github.com/getsentry/sentry-javascript/pull/15518, which are no longer compatible with OTEL v2. We already have a replacement for this in place.
=> feat(js): Stop using `provider.addSpanProcessor()`

docs/product/issues/issue-details/feature-flags/index.mdx
closes https://github.com/getsentry/sentry-docs/issues/13013
=> ref(flags): mention 100 flag limit in product docs

docs/platforms/javascript/guides/remix/frameworks/hydrogen.mdx
This cleans up the instructions for shopify hydrogen remix.
I'm also going to add a guide for plain remix apps with cloudflare.
=> Clean up shopify hydrogen remix guide

docs/concepts/search/searchable-properties/issues.mdx, docs/product/issues/issue-details/feature-flags/index.mdx, docs/product/issues/issue-details/index.mdx
on https://docs.sentry.io/product/issues/issue-details/feature-flags/:
on https://docs.sentry.io/product/issues/issue-details/#feature-flags:
on searchable properties page (https://docs.sentry.io/concepts/search/searchable-properties/issues/#flags):
closes https://github.com/getsentry/sentry-docs/issues/12776
=> ref(flags): add note about feature flag search

docs/platforms/apple/guides/ios/session-replay/index.mdx, docs/platforms/apple/guides/ios/session-replay/performance-overhead.mdx, package.json
Adds documentation for two new options for Session Replay in Cocoa SDK, introduced with [v8.47.0](https://github.com/getsentry/sentry-cocoa/releases/tag/8.47.0), mainly due to https://github.com/getsentry/sentry-cocoa/pull/4940 (which might be worth mentioning as further reading).
=> feat(apple): add new options for Session Replay

docs/platforms/javascript/common/troubleshooting/index.mdx
Fixes https://github.com/getsentry/sentry-javascript/issues/9787
=> Add instructions not to set `sideEffects: false` in `package.json`

docs/platforms/dart/guides/flutter/integrations/index.mdx, includes/dart-integrations/index.mdx, includes/dart-integrations/slow-and-frozen-frames-instrumentation.mdx
Add * to Slow and Frozen Frames integrations, since there is a scenario where auto-instrumentation will not work.
=> fix(flutter): add missing auto-enabled checks

src/components/sidebar/index.tsx
=> fix(platform): sidebar deep links 404s

src/components/platformFilter/style.module.scss
The height was slightly off between items with and without guides.
=> style: Fix grid layout for platforms

docs/product/insights/getting-started.mdx
Update Dart and Flutter platform links in product insights getting-started section.
https://docs.sentry.io/product/insights/getting-started/
=> fix(docs): update Dart and Flutter platform links in getting-started.mdx

docs/product/stats/index.mdx
Add a section on the outcome documentation explaining that the to large will now be of the form `Too Large <reason>` with reason pointing the user to exactly what was too large. In a further step this would also be further split per attachment type in the case of the "attachment" being too large.
Sentry PR: https://github.com/getsentry/sentry/pull/87078
Relay PR: https://github.com/getsentry/relay/pull/4558
=> feat(outcomes): Add documentation for new information on outcome "Too Large".

apps/changelog/package.json, package.json, yarn.lock
We somehow did not receive any events using 9.7.0-alpha.0
=> chore(deps): Bump sentry to 9.8.0

src/components/askAiSearchParams.tsx, src/components/home.tsx
Adds listener for search param `askAI=true` (only on the root page) for automatically displaying kapa dialog.
=> feat(platform): Add askAI search params

apps/changelog/package.json, package.json, yarn.lock
bump again, since we now have client events again
=> chore(deps): Bump `@sentry/nextjs` to 9.7.0-alpha.0

.github/workflows/lint-404s.yml
Missed this in https://github.com/getsentry/sentry-docs/pull/13099
=> fix(ci): Add env vars for start command

docs/platforms/javascript/common/profiling/node-profiling.mdx
Update continuous profiling docs for nodejs. Requires https://github.com/getsentry/sentry-javascript/pull/15635 to be released
=> docs: update continuous profiling docs

apps/changelog/src/app/changelog/%5Fadmin/[id]/edit/page.tsx, apps/changelog/src/client/components/navbar.tsx, src/components/header.tsx, src/components/mobileMenu/index.tsx
=> fix(sandbox): use link to new sandbox

docs/platforms/javascript/common/usage/index.mdx, docs/platforms/javascript/guides/react/features/error-boundary.mdx, docs/platforms/javascript/guides/react/index.mdx, platform-includes/capture-error/javascript.react.mdx
Documents https://github.com/getsentry/sentry-javascript/pull/15746 released in `9.8.0` of the Sentry React SDK.
`captureReactException` is a method exposed that users can use if they don't want to use the Sentry Error Boundary component, but instead their own custom Error Boundary component.
=> feat(react): Document `Sentry.captureReactException`

docs/platforms/javascript/config.yml, src/components/breadcrumbs/index.tsx, src/components/platformFilter/client.tsx, src/components/platformSelector/index.tsx, src/docTree.ts, src/types/platform.tsx
Today, it is a bit confusing in some cases, but especially JavaScript, that the top level platform is called "JavaScript" (which all guides inherit from), but actually it is just Browser JavaScript.
This adds a new field which, when set for a platform, will lead to a slightly different behavior:
And
Some notes:
1. When you click on the top level "JavaScript" in the sidebar, it will basically "redirect" to "Browser JavaScript"
2. For other platforms that have not set this field, nothing changes - so with this PR, only JS changes.
3. The breadcrumbs are a bit tricky/weird, there I opted to leave it as it is for now 🤔 it's a bit inconsistent, but everything else is quite tricky as the hierarchy needs to change based on if a guide is selected etc. we may tweak this still...
=> feat: Allow to have top level alias for platforms

docs/platforms/native/advanced-usage/backend-tradeoffs/index.mdx, docs/platforms/native/common/configuration/options.mdx
Related to https://github.com/getsentry/sentry-native/pull/1153
Updated pages' preview
- [Backend tradeoffs](https://sentry-docs-git-feat-nativecrashpad-wait-for-upload.sentry.dev/platforms/native/advanced-usage/backend-tradeoffs/#when-shouldnt-i-use-the-crashpad-backend)
- [Options](https://sentry-docs-git-feat-nativecrashpad-wait-for-upload.sentry.dev/platforms/native/configuration/options/#crashpad-wait-for-upload)
=> feat(native): add `crashpad-wait-for-upload` option

docs/platforms/python/profiling/index.mdx
This should now use the `start_profile_session` and `stop_profile_session` apis and mention `profile_lifecycle="trace"`. …
=> feat(profiling): Update python continuous profiling docs

package.json, yarn.lock
ref https://github.com/getsentry/sentry-docs/issues/13120
This is a quickfix for unblocking users from using dev-mode.
Since we do not have any authorization middleware implemented we can ignore https://github.com/vercel/next.js/security/advisories/GHSA-f82v-jwr5-mffw for now
@lforst feel free to merge or close
=> fix(platform): Downgrade next to 15.1 to unblock dev mode

docs/platforms/javascript/guides/fastify/features/error-handler.mdx, docs/platforms/javascript/guides/fastify/features/index.mdx
Documents https://github.com/getsentry/sentry-javascript/pull/15771, released in JS SDK `9.9.0`.
=> feat(fastify): Document shouldHandleError

app/[[...path]]/page.tsx, src/components/include.tsx, src/components/platformContent.tsx, src/mdx.ts
ref https://github.com/getsentry/sentry-docs/pull/13088#pullrequestreview-2706404914
Add some calls to react [cache](https://react.dev/reference/react/cache) to memoize `getFileBySlug`.  Also do the same for `updatePathIfVersionedFileDoesNotExist`.
=> perf: Add caching to expensive file computations

sentry.client.config.ts
Let's give this a try in our docs project to see how well it works. Happy to close if anyone has concerns regarding sessionStorage usage but we already use Replay in docs, so we already write and read from it. With this change, we can link to a previous trace even if users hard-navigate or hard-reload the page.
=> feat(sentry): Store previous trace information in `sessionStorage`

docs/platforms/javascript/guides/aws-lambda/install/cjs-layer.mdx
I noticed that this link was dead!
=> fix(js): Fix link to AWS lambda layer configuration

docs/product/explore/session-replay/mobile/index.mdx
The previous link brought users to the Replay docs homepage: https://docs.sentry.io/product/explore/session-replay/, as opposed to the specific replay for BE errors instructions.
=> Update Link for Replays for BE Errors.mdx

docs/platforms/javascript/common/troubleshooting/index.mdx
Based on a suggestion from https://github.com/getsentry/sentry-javascript/issues/15826 …
=> Add note about server-side tunneling with JS

src/components/codeBlock/code-blocks.module.scss, src/components/codeHighlights/codeHighlights.tsx
I noticed that in code blocks where the last line is highlighted it doesn't get shown. There's a good example in the TanStack Start React guide:
The code block ends abruptly and it doesn't show how to wrap the `defaultStreamHandler` with Sentry's `wrapStreamHandlerWithSentry`. I checked the mdx page and noticed that there's only one missing line from the code block and it's also the highlighted one.
The changes I made ensure that we "flush" any started highlight groups at the end before returning the markup. The previous implementation relied on having a non-highlighted line that follows a highlighted one in order to "flush" the group.
This PR would fix any code blocks that highlight the last line(s). I'm not sure if there are other instances other than the TanStack Start one.
After the …
=> fix(mdx): push last highlighted line when making highlight blocks

docs/platforms/javascript/common/tracing/index.mdx
Since we have a dedicated page about this, we should link there instead of to the generic options, which have less information than other places.
Generally, I wonder if it really makes sense to have the "Configure Sample Rate" page under "Set Up Tracing" as well as the "Sampling" page under configuration, which have almost-but-not-quite the same information as of now 🤔 IMHO one of these should stay and the other should go (personally I would vote for configuration/sampling and linking there from the tracing docs)
=> feat(js): Streamline links for explanations about tracing sampling

docs/platforms/android/troubleshooting/index.mdx, docs/platforms/android/troubleshooting/mixed-versions/index.mdx, docs/platforms/java/common/troubleshooting/index.mdx, docs/platforms/java/common/troubleshooting/mixed-versions/index.mdx
Using multiple Java SDK modules/dependencies with different versions is not supported, almost certainly leads to crashes at some point and in new SDK versions will result in an early crash of the SDK on `init`. This page shall help customers understand what's going on and how to resolve the issue.
Look, I get it. The …
=> Troubleshooting Guide for mixed versions in Java / Android SDK

src/components/codeHighlights/codeHighlights.tsx
This PR changes the styling of our code highlights based on feedback I received after #12983:
- left border changed from pink to purple to avoid mistaking it for a negative diff code line
- fixed too much left padding for individual lines in highlight block
- narrowed down vertical padding of highlight blocks. I personally still prefer the current 2px padding over no padding at all but happy to debate this further :) 
- cleaned up some unnecessary css values
Before:
After:
*Make sure you've checked …
=> ref: Adjust code highlight block styling

docs/platforms/javascript/guides/remix/manual-setup.mdx
Remix roots are not wrapped with `@sentry/react`'s `ErrorBoundary` starting from Remix version 2.
We dropped support for Remix v1, so the docs are not valid anymore.
Resolves: https://github.com/orgs/getsentry/projects/31/views/19?pane=issue&itemId=103941554&issue=getsentry%7Csentry-javascript%7C15883
=> fix(remix): Remove deprecated `ErrorBoundary` options.

docs/platforms/nintendo-switch/index.mdx, src/components/platformIcon.tsx, src/data/platforms.yml, src/middleware.ts
closes https://github.com/getsentry/team-gdx/issues/40 …
=> feat: nintendo switch

platform-includes/distributed-tracing/how-to-use/javascript.astro.mdx, platform-includes/distributed-tracing/how-to-use/javascript.cloudflare.mdx, platform-includes/distributed-tracing/how-to-use/javascript.mdx, platform-includes/distributed-tracing/how-to-use/javascript.nextjs.mdx, platform-includes/distributed-tracing/how-to-use/javascript.node.mdx, platform-includes/distributed-tracing/how-to-use/javascript.nuxt.mdx, platform-includes/distributed-tracing/how-to-use/javascript.remix.mdx, platform-includes/distributed-tracing/how-to-use/javascript.solidstart.mdx, platform-includes/distributed-tracing/how-to-use/javascript.sveltekit.mdx
Simplifying initial trace propagation example to not use a regex based example. Creates a more gradual increase in complexity through the other examples. 
Added a callout that for services running on different ports on the same origin.
=> Simplifying Trace Propagation Examples; Adding origin callout.

develop-docs/backend/application-domains/database-migrations/index.mdx
Was just talking with @MichaelSun48 and I believe this is worded in a slightly confusing way. If the column you're looking to drop is not nullable, you should make it nullable first before removing references. lmk if this makes sense @wedamija
=> fix(docs): clarify database migrations

docs/platforms/javascript/guides/svelte/index.mdx
Closes https://github.com/getsentry/sentry/issues/88305
=> feat(svelte): additional switch for v5/v4

src/components/tableOfContents.tsx
Not sure why I even added this, but this seems unnecessary!
Closes https://github.com/getsentry/sentry-docs/issues/13159
=> fix: Improve `<TableOfContents>` to allow empty sections

docs/platforms/android/tracing/instrumentation/perf-v2.mdx
PerfV2 is GA and opt-out since v8 of the SDK - updated the page to reflect this.
=> chore(Android): Update Performance V2 docs

docs/platforms/javascript/common/tracing/configure-sampling/index.mdx
This PR improves the "Tracing > Configure Sampling" page in two main ways:
1. It introduces proper headings for the two main sections - this way, you can link there, and it makes more sense structurally IMHO.
2. It fixes the `tracesSampler` examples - you should _always_ use `inheritOrSampleWith` for the default sample rate, otherwise you break propagation. We need to make sure to use this consistently in examples!
=> fix(js): Fix hierarchy and examples for sample rate configuration

src/components/sidebarTableOfContents/index.tsx
This updates the sidebar table of content (TOC) component to not show hidden headings:
https://github.com/user-attachments/assets/1d06f6ce-f44d-42b9-bceb-c0a9feaffc25
For this, we check `element.checkVisibility()` which is a _relatively_ new [API](https://developer.mozilla.org/en-US/docs/Web/API/Element/checkVisibility#browser_compatibility).
Additionally, we register a mutation observer to check if the visible headings change, and if they do we update the sidebar.
Closes https://github.com/getsentry/sentry-docs/issues/13073
=> fix(platform): Ensure hidden sections are not show in sidebar TOC

docs/platforms/javascript/common/configuration/options.mdx, docs/platforms/javascript/guides/vue/index.mdx
This PR brings our Vue Getting Started page up to date. We changed options around a bit in v9 and forgot to remove some removed options from docs. Also did some minor improvements while I was at it.
- Removed the entire "Vue specific Options" subsection as it doesn't really make sense in a Vue-specific onboarding guide:
- Removed `logErrors` as this is now just default behaviour
- Removed `tracingOptions` 
- Moved `attachProps` to general options page (`PlatformSection`ed of course)
- Added `attachErrorHandler` to general options page (`PlatformSection`ed of course)
- Added highlighting to `Sentry.init` code block
closes https://github.com/getsentry/sentry-docs/issues/13157
=> fix(vue): Remove outdated Vue SDK options

develop-docs/sdk/data-model/event-payloads/contexts.mdx
The h3 for the examples kind of messed up the sidebar hierarchy, making it harder to parse.
Before:
After:
=> feat(develop): Clean up contexts page structure

docs/platforms/rust/common/source-context/index.mdx
Closes https://github.com/getsentry/sentry-docs/issues/9625
This is the process we use for relay.
It works on Linux and macOS, not sure yet how to do this on Windows but we can add it in the future.
=> feat(rust): document how to set up source context

docs/platforms/java/common/source-context/index.mdx
Closes https://github.com/getsentry/sentry-docs/issues/13196
=> fix(java): fix typo in Source Context docs

docs/platforms/rust/common/source-context/index.mdx
Complements https://github.com/getsentry/sentry-docs/pull/13151 to close https://github.com/getsentry/sentry-docs/issues/9625
=> feat(rust): document how to set up source context on macOS

docs/platforms/javascript/guides/aws-lambda/index.mdx, docs/platforms/javascript/guides/aws-lambda/install/index.mdx
After a quick convo with @mydea, this PR rewords and restructures the Node AWS Lambda installation methods sections.
* On the main page, I turned around the sentence to more clearly see which method to follow for which setup
* on the installation methods page:
* removed PageGrid as it was distracting from the actually important information
* added missing links 
* shortened some sentences and removed indecisive language ("you should...")
=> ref(js-aws-lambda): Reword installation method selection

docs/platforms/javascript/guides/aws-lambda/install/esm-npm.mdx
The `NODE_OPTIONS: "--import instrument.mjs"` example needs to be `NODE_OPTIONS: "--import ./instrument.mjs"` to work correctly. The example image is correct, but the docs are not.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and …
=> Update esm-npm.mdx to show correct config with AWS Lambda

platform-includes/configuration/integrations/javascript.astro.mdx, platform-includes/configuration/integrations/javascript.mdx, platform-includes/configuration/integrations/javascript.nextjs.mdx, platform-includes/configuration/integrations/javascript.nuxt.mdx, platform-includes/configuration/integrations/javascript.remix.mdx, platform-includes/configuration/integrations/javascript.solidstart.mdx, platform-includes/configuration/integrations/javascript.sveltekit.mdx, platform-includes/configuration/integrations/javascript.vue.mdx
The change is on this page, for all the frameworks i found that have a specific Browser Integrations section
https://docs.sentry.io/platforms/javascript/configuration/integrations/
I've grouped all the FF integrations together. This is an improvement as-is because we're giving more reach to the FF integrations for JS frameworks with a browser component.
Pages will look like this now:
=> feat(feature flags): Add feature flag integrations to js frameworks with Browser Integrations sections

docs/platforms/javascript/common/tracing/configure-sampling/index.mdx
Noticed this is a bit off now, so fixing/aligning doc structure here.
=> ref(js): Small fixes to configure sampling structure

docs/concepts/key-terms/tracing/span-metrics.mdx, docs/platforms/javascript/common/configuration/filtering.mdx, docs/platforms/javascript/common/tracing/span-metrics/examples.mdx, docs/platforms/javascript/common/tracing/span-metrics/index.mdx
This fixes some of the code examples around span metrics in JS.
=> fix(js): Fix span metrics examples

docs/platforms/javascript/common/tracing/index.mdx, docs/platforms/javascript/common/tracing/instrumentation/index.mdx
This updates the custom instrumentation docs for JS (tracing):
1. Link to new API pages for more complete list of APIs
2. Updating the "Custom Instrumentation" section on "Set up tracing" to link to APIs, instrumentation, and span metrics
3. Fixing one or two examples
=> feat(js): Update JS tracing instrumentation docs

src/components/dynamicNav.tsx, src/components/guideGrid.tsx, src/components/search/index.tsx, src/components/search/search.module.scss, src/components/search/searchResultItems.tsx, src/components/sidebar/defaultSidebar.tsx, src/components/sidebar/platformSidebar.tsx, src/components/sidebar/style.module.scss, src/components/sidebarTableOfContents/index.tsx, src/components/sidebarTableOfContents/style.module.scss
We use this quite a lot to just generically mean "heading", but this is incorrect - a h6 has to be structure below a h5, not just randomly. This PR changes this to use a different heading that makes more sense or just a div+class instead. Nothing should change visually.
=> fix(platform): Replace incorrect usage of `<h6>`

docs/platforms/javascript/guides/express/index.mdx
We've fixed this in https://github.com/getsentry/sentry-javascript/issues/13674 - so we can remove this note now …
=> Remove note about express 5

docs/platforms/javascript/guides/cloudflare/features/d1.mdx, docs/platforms/javascript/guides/cloudflare/frameworks/astro.mdx, docs/platforms/javascript/guides/cloudflare/frameworks/remix.mdx, docs/platforms/javascript/guides/cloudflare/frameworks/sveltekit.mdx, docs/platforms/javascript/guides/cloudflare/index.mdx, docs/platforms/javascript/guides/hono/index.mdx, platform-includes/sourcemaps/primer/javascript.cloudflare.mdx
ref https://github.com/getsentry/sentry-wizard/issues/824
Update cloudflare snippets so that both `jsonc` and `toml` config are referred to. Also move `jsonc` to be the default shown because it matches the docs. …
=> Update cloudflare config snippets to use jsonc

docs/platforms/python/profiling/index.mdx
- Moves the paragraph about missing sampling when manually starting & stopping profiling to after the snippet where it should belong semantically.
=> chore(profiling): move the sampling paragraph to the right place in python profiling docs

docs/organization/integrations/deployment/vercel/index.mdx
Add details for the Vercel native marketplace integration.  
=> Vercel Native Marketplace integration docs

src/components/sidebar/index.tsx, src/components/sidebar/style.module.scss
**Problem Statement**
The framework you’ve picked is really important, but it scrolls away. So if you arrived at docs via a search you might be looking at instructions for a random framework and not realize it. Other hints on the page are:
- The url (not a huge hint if you’re looking at javascript but want NextJS),  
- ‘Home / Platforms / JavaScript / Next.js’ breadcrumb but that scrolls away too
- Package details in the right column, hard to spot that.
**Solution**
When the window is wide the navigation sidebar will now have a sticky Platform dropdown. So that dropdown is always visible, and users can easily see what docs are they reading. The nav links below will scroll behind the platform dropdown.
In narrow modes, when you have to click to see this whole nav column, the scrolling is …
=> feat: Keep the Platform/Language/Framework dropdown visible and scroll nav below it

docs/platforms/android/index.mdx
https://github.com/getsentry/sentry/pull/85861
This PR only updates android. The prio of order of tabs could be changed, and this could be applied to flutter and iOS install in docs. PRs welcome:)
=> Add tabs to reflect the new binaries available

docs/platforms/javascript/common/tracing/instrumentation/automatic-instrumentation.mdx, docs/platforms/javascript/guides/nextjs/manual-setup.mdx, platform-includes/configuration/integrations/javascript.nextjs.mdx, platform-includes/configuration/integrations/lazy-loading-replay/javascript.nextjs.mdx, platform-includes/distributed-tracing/how-to-use/javascript.nextjs.mdx, platform-includes/migration/javascript-v8/v7-deprecation/javascript.nextjs.mdx, platform-includes/performance/configure-sample-rate/javascript.nextjs.mdx, platform-includes/profiling/automatic-instrumentation-setup/javascript.nextjs.mdx, platform-includes/session-replay/setup/javascript.nextjs.mdx, platform-includes/tracing/sample-rate/javascript.nextjs.mdx, platform-includes/tracing/trace-sampler/javascript.astro.mdx, platform-includes/tracing/trace-sampler/javascript.nextjs.mdx
We changed what file we want users to create for client instrumentation because Next.js added the `instrumentation-client.ts` hook as a native mechanism.
I thought of doing versioned docs but that is a huge pain in the butt for all of the places we have the client config. The SDK logs a warning to migrate you from `sentry.client.config.ts` to `instrumentation-client.ts` in any case.
=> Refer to `instrumentation-client.ts` instead of `sentry.client.config.ts` for Next.js

docs/platforms/javascript/guides/remix/index.mdx
Fixes https://github.com/getsentry/sentry-docs/issues/13253
=> Remove alert about remix not supporting cloudflare

docs/platforms/apple/common/index.mdx, docs/platforms/apple/common/profiling/index.mdx, docs/platforms/apple/index.mdx
Update the Apple profiling docs to explain the new iteration of profiling and the deprecation of all prior versions of the API. 
For https://github.com/getsentry/sentry-cocoa/issues/4996 …
=> feat: update docs for profiling v2

docs/platforms/react-native/manual-setup/expo/gradle.mdx
This PR fixes the default values of the Expo Sentry Android Gradle Plugin configuration options [to align with the plugin code](https://github.com/getsentry/sentry-react-native/blob/main/packages/core/plugin/src/withSentryAndroidGradlePlugin.ts#L23).
Look, I get it. The entity doing business as "Sentry" was …
=> RN: fixes SAGP Expo plugin default option values

docs/platforms/react-native/tracing/instrumentation/expo-router.mdx
StoreClient means the app _is_ running in Expo Go, so this predicate was doing the opposite of what it intended.
Regardless, there's an easier-to-understand check if the app is running in Expo Go, and it's what is recommended by the Expo docs: https://docs.expo.dev/guides/using-sentry/#initialize-sentry …
=> Fix Expo Go check in Expo Router instructions

docs/platforms/javascript/guides/nextjs/index.mdx, docs/platforms/javascript/guides/nextjs/manual-setup.mdx, docs/platforms/javascript/guides/nuxt/index.mdx, docs/platforms/javascript/guides/react/index.mdx, docs/platforms/javascript/guides/tanstackstart-react/index.mdx, platform-includes/getting-started-features-expandable/_default.mdx, platform-includes/getting-started-features-expandable/javascript.node.mdx, platform-includes/getting-started-node/javascript.mdx, platform-includes/getting-started-prerequisites/javascript.nuxt.mdx, platform-includes/getting-started-verify-locate-data/javascript.node.mdx
- Rework the Nuxt Getting Started guide into a Quick Start guide.
- Create and use new platform-includes for reusable content
Closes: #13188
=> docs(js): Create Nuxt Quick Start guide for wizard installation

develop-docs/sdk/data-model/event-payloads/contexts.mdx
When reading the Trace Context docs, I assumed that `client_sample_rate` (like all the other fields) was expected to be set by the client. Instead, this field is generated in Relay. If a client sets this field, it will be ignored and overwritten. Added a note to the docs for this field to clarify how it is meant to be used.
=> fix(develop): clarify trace context's client_sample_rate

develop-docs/sdk/data-model/event-payloads/contexts.mdx
Develop docs for the trace context include fields that are not supported or not supposed to be ingested.
=> Cleanup none-supported fields from trace context

platform-includes/performance/enable-manual-instrumentation/native.mdx
Someone noticed that we didn't actually document how to start a child span of a span (since this is different from starting a child span of a transaction). The feature itself has existed for a while and is demonstrated on the [sentry-native example](https://github.com/getsentry/sentry-native/blob/master/examples/example.c#L473-L490).
=> feat(native): improve custom instrumentation docs with child span creation

docs/platforms/javascript/common/profiling/node-profiling.mdx
Prevent the code snippet from "eating" the rest of the page.
=> fix(node-profiling): Code snippet without end sequence

docs/organization/membership/index.mdx
Deletes this alert 
located [here](https://docs.sentry.io/organization/membership/#adding-new-members)
I'm pretty sure adding members is no longer an EA feature 😅
=> ref(member-docs): remove early access alert for adding members

docs/platforms/javascript/common/best-practices/index.mdx, docs/platforms/javascript/common/migration/index.mdx
IMHO this page is less important as the general setup pages, so it makes sense to move this down.
=> ref(js): Move "Special Use Cases" down in sidebar order

docs/platforms/go/common/tracing/instrumentation/custom-instrumentation/index.mdx
added more details on how to use the go sdk for custom instrumentation. Changes are: 
1. Adding span & transaction attributes 
2. Setting/updating transaction & span data
3. Attaching data attributes with `BeforeSendTransaction`
=> feat(go): Update transaction & span instrumentation docs 

src/components/sidebar/index.tsx, src/components/sidebar/style.module.scss
This removes the "hack" to only show the scrollbar on hover. Which is nice in theory, but got really jumpy now.
IMHO it is ok to just always show this, def. better than the current jumpy version!
I also aligned the padding on top so it is consistent around for the sidebar.
https://github.com/user-attachments/assets/f5fe550e-2775-4675-858d-2b256ee46f88
https://github.com/user-attachments/assets/354034ec-64f5-43f8-aed1-8bee55ffcd6c
=> fix(style): Ensure scrollbar is consistent

docs/platforms/python/tracing/span-lifecycle/index.mdx
Removing the manual option from this doc
Fixes #13290 
=> fix: Remove manual config section from python span lifecycle page

docs/platforms/javascript/guides/nextjs/manual-setup.mdx
this was wrong - preview fix [here](https://sentry-docs-git-fixrouter-config-next.sentry.dev/platforms/javascript/guides/nextjs/manual-setup/#initialize-sentry-client-side-and-server-side-sdks)
=> Fix captureRouterTransitionStart for Next.js

docs/organization/integrations/index.mdx, docs/organization/integrations/notification-incidents/glueai/index.mdx, docs/organization/integrations/notification-incidents/index.mdx
=> Souredoutlook integration publication/glue

docs/platforms/react-native/session-replay/index.mdx
RN SDK supports browser replay, but it was not part of the docs.
=> feat(react-native): Add Browser replay init to the RN docs

docs/platforms/apple/common/enriching-events/screenshots/index.mdx
Explain why the Cocoa SDK can't capture screenshots for all types of crashes.
=> fix(apple): Not taking screenshots for all crashes

develop-docs/backend/application-domains/email.mdx, develop-docs/self-hosted/email.mdx
Closes https://github.com/getsentry/self-hosted/issues/2990 …
=> docs(self-hosted): detailed email docs regarding best practices

docs/pricing/index.mdx
Changes based on: https://www.notion.so/sentry/Pricing-Docs-dc9e21de12f3486fb446be3aae08368d?d=12f8b10e4b5d80f392d0001c13e4470d …
=> Apply updates from notion to /pricing/ (AM3)

docs/pricing/legacy-pricing.mdx
=> Add updates to AM2 billing docs

docs/product/stats/index.mdx
=> Update stats page with dropped profile hours info

docs/platforms/java/guides/spring-boot/webflux.mdx, platform-includes/getting-started-primer/java.spring-boot.mdx, platform-includes/getting-started-primer/java.spring.mdx
Closes https://github.com/getsentry/sentry-java/issues/2913
=> feat(java): document minimum framework versions for WebFlux support

docs/platforms/javascript/config.yml, src/components/breadcrumbs/index.tsx
E.g. for this change: https://github.com/getsentry/sentry-docs/pull/13392
It makes more sense to have the `sidebar_title` be in the breadcrumbs, than the page title.
=> feat(platform): Use `sidebar_title` for breadcrumbs

docs/contributing/pages/components.mdx, docs/platforms/go/common/data-management/data-collected.mdx, docs/platforms/go/common/migration.mdx, docs/platforms/go/guides/echo/index.mdx, docs/platforms/go/guides/fasthttp/index.mdx, docs/platforms/go/guides/fiber/index.mdx, docs/platforms/go/guides/gin/index.mdx, docs/platforms/go/guides/http/index.mdx, docs/platforms/go/guides/iris/index.mdx, docs/platforms/go/guides/negroni/index.mdx, docs/platforms/go/guides/slog/index.mdx, docs/platforms/go/guides/zerolog/index.mdx, platform-includes/getting-started-config/go.mdx, platform-includes/getting-started-verify/go.mdx
see https://github.com/getsentry/team-sdks/issues/82
=> Add go data collection page & SendDefaultPII option on docs

docs/platforms/javascript/common/configuration/options.mdx
This may be a bit confusing, that this is not the same type of span as you get in e.g. `startSpan` callbacks.
=> feat(js): Add clarification for `beforeSendSpan` argument

docs/platforms/apple/common/index.mdx, docs/platforms/javascript/guides/hono/index.mdx, src/components/docPage/type.scss, src/mdx.ts, src/rehype-onboarding-lines.js, src/remark-format-code.js
closes #12955
I migrated Hono to the new syntax as an example
more context on the issue  👆
=> feat: Inline onboarding product options syntax

includes/nextjs-turbopack-warning-expandable.mdx
Updates the turbopack warning to reflect the latest SDK and Next.js support.
=> Update turbopack warning

develop-docs/backend/application-domains/feature-flags/flagpole.mdx
Expand the documentation on flagpole context
=> fix: Add more context data to flagpole documentation

docs/platforms/dart/common/index.mdx, docs/platforms/dart/guides/flutter/index.mdx, docs/platforms/dart/guides/flutter/manual-setup.mdx
=> refactor: migrate Dart and Flutter sdks to inline product options syntax

docs/concepts/search/searchable-properties/session-replay.mdx
followup to https://github.com/getsentry/sentry/pull/89768
=> docs(replays): add count_traces to searchable properties

platform-includes/getting-started-config/powershell.mdx
Turned out there were two spots:
* https://github.com/getsentry/sentry-docs/pull/13426
=> powershell senddefaultpii landing page

platform-includes/configuration/config-intro/powershell.mdx
Turned out there were two spots:
* https://github.com/getsentry/sentry-docs/pull/13427
=> add senddefaultpii to powershell

docs/platforms/unreal/configuration/options.mdx, platform-includes/getting-started-config/unreal.mdx
This PR adds `SendDefaultPii` to Unreal Engine SDK options list and adds corresponding code snippet to the onboarding docs.
Related to https://github.com/getsentry/team-sdks/issues/121
=> Unreal: Document and add `SendDefaultPii = true` to onboarding docs

docs/platforms/java/guides/spring/tracing/instrumentation/automatic-instrumentation.mdx
Tested with the Spring sample and it works.
Closes https://github.com/getsentry/sentry-docs/issues/11475
=> fix(java): fix `RestTemplate` auto-instrumentation guide

docs/product/explore/session-replay/index.mdx
closes https://github.com/getsentry/sentry-docs/issues/13445
=> ref(replay): clarify web & mobile distinction in product docs

docs/platforms/javascript/common/tracing/span-metrics/examples.mdx
=> Update spelling in examples.mdx

docs/platforms/go/guides/echo/index.mdx, docs/platforms/go/guides/fasthttp/index.mdx, docs/platforms/go/guides/fiber/index.mdx, docs/platforms/go/guides/gin/index.mdx, docs/platforms/go/guides/http/index.mdx, docs/platforms/go/guides/iris/index.mdx, docs/platforms/go/guides/logrus/index.mdx, docs/platforms/go/guides/negroni/index.mdx, docs/platforms/go/guides/slog/index.mdx, docs/platforms/go/guides/zerolog/index.mdx
=> refactor: migrate Golang and related guides to inline product options syntax

docs/security-legal-pii/security/ip-ranges.mdx
Updates IP ranges docs page to include our dynamic IP addresses endpoint.
=> Add docs on new API endpoint for dynamic IP retrieval

docs/platforms/javascript/guides/tanstackstart-react/index.mdx
I noticed a few missing imports, highlights, and also a typo in the TanStack Start guide:
- Missing `wrapCreateRootRouteWithSentry` import
- Missing Sentry prefix when defining an error boundary component
**Question**: a similar guide is shown in Sentry itself after you create a project. Would this PR fix that one as well, or should I open a separate PR on that repo?
=> fix(tanstackstart): added missing imports, highlights, and typos

docs/platforms/python/configuration/filtering/index.mdx, docs/platforms/python/profiling/index.mdx, docs/platforms/python/tracing/configure-sampling/index.mdx, docs/platforms/python/tracing/instrumentation/custom-instrumentation/index.mdx, docs/platforms/python/tracing/span-lifecycle/index.mdx, docs/platforms/python/tracing/span-metrics/index.mdx, docs/platforms/python/tracing/troubleshooting/index.mdx, platform-includes/configuration/before-breadcrumb-hint/python.mdx, platform-includes/configuration/before-send-fingerprint/python.mdx, platform-includes/configuration/before-send-hint/python.mdx, platform-includes/configuration/before-send-transaction/python.mdx, platform-includes/configuration/error-sampler/python.mdx, platform-includes/enriching-events/breadcrumbs/before-breadcrumb/python.mdx, platform-includes/performance/traces-sampler-as-filter/python.mdx, platform-includes/performance/traces-sampler-as-sampler/python.mdx, platform-includes/set-fingerprint/database-connection/python.mdx
Some users where complaining because they did not know how to properly type their hooks that they can define for configuring Sentry SDK. This update adds those types to the code snippets.
This PR needs this PR for all types to be available publicly to use: https://github.com/getsentry/sentry-python/pull/4315
Preview (examples):
- https://sentry-docs-git-antonpirker-python-typing.sentry.dev/platforms/python/configuration/sampling/
- https://sentry-docs-git-antonpirker-python-typing.sentry.dev/platforms/python/configuration/filtering/#example-before_send
- https://sentry-docs-git-antonpirker-python-typing.sentry.dev/platforms/python/tracing/span-lifecycle/#adding-attributes-to-all-spans
- https://sentry-docs-git-antonpirker-python-typing.sentry.dev/platforms/python/tracing/configure-sampling …
=> Add types to code snippets for hooks

docs/platforms/python/data-management/data-collected.mdx
The documentation was wrong in this case. We always do send headers, but we filter sensitive information. …
=> Fix: What http headers are collected in the Python SDK

docs/platforms/apple/common/index.mdx
The watchOS getting started page showed instructions for the AppDelegate, which doesn't exist on watchOS. This is fixed now by explaining how to start the SDK in the WKExtensionDelegate. …
=> fix(apple): Getting started for watchOS

platform-includes/debug-symbols-apple/_default.mdx, platform-includes/getting-started-config/ruby.mdx, platform-includes/getting-started-config/ruby.rack.mdx, platform-includes/getting-started-config/ruby.rails.mdx, platform-includes/getting-started-config/ruby.resque.mdx
=> refactor: migrate ruby and related sdks to inline product options sytnax

platform-includes/getting-started-config/java.mdx, platform-includes/getting-started-config/java.spring-boot.mdx, platform-includes/getting-started-config/opentelemetry/java.mdx
=> refactor: migrate java sdks to inline product options syntax

docs/platforms/android/index.mdx, src/rehype-onboarding-lines.js
=> refactor: migrate android onboarding options to inline syntax

platform-includes/getting-started-config/python.mdx
=> refactor: migrate python platform-includes to inline options syntax

docs/contributing/pages/components.mdx, package.json, platform-includes/debug-symbols-apple/_default.mdx, src/rehype-onboarding-lines.js
documents https://github.com/getsentry/sentry-docs/pull/13361
=> docs(contributing): Document new syntax for onboarding snippets

src/components/sidebar/developDocsSidebar.tsx
simply adds some padding to the dev docs sidebar that got lost in https://github.com/getsentry/sentry-docs/pull/13354
=> fix(style): Add padding for dev docs sidebar

docs/contributing/pages/components.mdx
a workaround to show up `___PRODUCT_OPTION_START___` and `___PRODUCT_OPTION_END___` markers on contributing docs
=> fix onboarding lines contributing docs

src/components/sidebarTableOfContents/index.tsx
We have a lot of issues like this: https://sentry.sentry.io/issues/5543047544/?project=1267915
> SyntaxError: Failed to construct 'IntersectionObserver': rootMargin must be specified in pixels or percent.
TBH not sure how that happens, but I guess we can try to be defensive here. Maybe inner height is missing somehow?
=> fix(platform): Avoid IntersectionObserver issues

develop-docs/sdk/expected-features/index.mdx
As part of https://github.com/getsentry/team-sdks/issues/109#issuecomment-2775965613 we want to clarify that any `HTTP 2xx` should be treated as succesfull.
=> docs(sdk): Clarify HTTP response codes considered successful

platform-includes/getting-started-use/javascript.nestjs.mdx
**DO NOT MERGE before [this](https://github.com/getsentry/sentry-javascript/pull/16066) was released**
documents https://github.com/getsentry/sentry-javascript/pull/16066
=> docs(js): Add section on microservices for error handling

docs/platforms/dotnet/common/troubleshooting.mdx
Add troubleshooting entry when using Proxy Servers. Impacts all .NET SDKs.
See also getsentry/sentry-dotnet#4118
=> docs(dotnet): add Proxy Server troubleshooting

apps/changelog/src/client/components/editor.tsx
Was really annoying not being able to see the cursor when the text area was empty.
=> feat(changelog): Add missing form-textarea class to editor

platform-includes/sourcemaps/troubleshooting/javascript.mdx
It is possible for a faulty integration to break sourcemaps. We spent too much time to find it so it will be useful to add it to the doc.
See: https://github.com/PostHog/posthog-js/issues/1753 …
=> ref(sourcemaps): added faulty community-maintained packages to troubleshooting doc

docs/platforms/native/common/data-management/data-collected.mdx
[Vercel Preview](https://sentry-docs-git-feat-nativedatacollectiondocs.sentry.dev/platforms/native/data-management/data-collected/)
As part of the initiative to have this information visible for each SDK, we also add this page for the native one.
We can take inspiration from the [Python](https://docs.sentry.io/platforms/python/data-management/data-collected/) or [Android ](https://docs.sentry.io/platforms/android/data-management/data-collected/) versions of this page, adapting it to what exists in Native.
We don't have `send_default_pii` as an option yet, so we should just document the PII that gets sent automatically by using the native SDK.
- Teamwork makes the dream work, so please add a reviewer to …
=> feat(native): add data collected page

docs/security-legal-pii/security/mobile-privacy.mdx
Adds explanation on how users are identified on Mobile, and for which purpose.
=> chore(legal): Add note about how users are identified on Mobile

docs/platforms/javascript/common/sourcemaps/uploading/uglifyjs.mdx
uglify's `-o` should point to the minified output, not to the sourcemap
=> Fix uglify example command

docs/platforms/javascript/common/configuration/filtering.mdx
Clarify that `denyUrl` applies to stack frame origin, not the page that an error comes from.
=> fix(js): Update `denyUrls` text in filtering page

develop-docs/sdk/telemetry/logs.mdx
=> feat: More clearly document log envelope item in logs spec

docs/organization/integrations/index.mdx, docs/organization/integrations/issue-tracking/factory/index.mdx, docs/organization/integrations/issue-tracking/index.mdx, docs/organization/integrations/issue-tracking/teamcamp/index.mdx
=>  Factory and Teamcamp integrations

docs/platforms/kotlin/guides/kotlin-multiplatform/configuration/options.mdx, docs/platforms/kotlin/guides/kotlin-multiplatform/data-management/data-collected.mdx
Part of https://github.com/getsentry/team-sdks/issues/82
=> Add data collected page for KMP

develop-docs/development-infrastructure/devservices.mdx
This change adds documentation for the new toggle command in devservices and outlines how/when it is used.
=> feat(toggle): Adding docs for the toggle command

platform-includes/sourcemaps/legacy-troubleshooting/javascript.mdx, platform-includes/sourcemaps/legacy-uploading-methods/javascript.mdx, platform-includes/sourcemaps/troubleshooting/javascript.mdx
Noone can point to where such a limit is actually defined if we indeed have one.
At least for the supported `sentry-cli` based SourceMap upload flow. It is quite possible that the 40M limit refers to the legacy "single release file upload" endpoints which are deprecated and rarely used, and we would rather work towards removing those endpoints altogether.
---
While working on this, I noticed that the 3 files I touched are pretty much ~90% the same. I don’t know enough about the docs to maybe work towards merging those pages, so I didn’t touch that.
=> Remove note about 40M SourceMap Limit

docs/platforms/unreal/data-management/data-collected.mdx
This PR adds "Data Collected" page to Unreal Engine SDK docs where PII that it collects is listed.
Closes https://github.com/getsentry/sentry-docs/issues/13434
=> Add "Data Collected" page for Unreal Engine SDK

docs/platforms/android/data-management/data-collected.mdx, docs/platforms/java/common/data-management/data-collected.mdx
=> Fix HTTP headers section in data collected for Java and Android SDK

develop-docs/frontend/using-rtl.mdx
Ref https://github.com/getsentry/frontend-tsc/issues/85
The internal development docs were referencing the old way of mocking router state in frontend tests. Updates with the new method of doing so.
=> chore(develop): Update frontend router testing guidance

docs/platforms/native/advanced-usage/backend-tradeoffs/index.mdx
fixes https://github.com/getsentry/sentry-native/issues/1213
Also cleaned up the remaining text a bit
=> fix(native): add another `crashpad` benefit on macOS to the backend tradeoffs

includes/dart-integrations/app-start-instrumentation.mdx
Add note that in some cases app starts might not be accurate and should be disabled
=> flutter: Add note to app start integration

docs/platforms/javascript/common/configuration/integrations/vercelai.mdx, docs/platforms/javascript/common/data-management/data-collected/index.mdx
Adds a "Data Collected" page to JavaScript-based SDKs
Preview: https://sentry-docs-k1k33l012.sentry.dev/platforms/javascript/data-management/data-collected/
closes https://github.com/getsentry/sentry-docs/issues/13407
=> feat(javascript): Add "Data Collected"

docs/pricing/index.mdx, docs/pricing/quotas/manage-cron-monitors.mdx
=> Incorporate Uptime Monitors Into The Crons Management Page

docs/organization/integrations/compliance/elba/index.mdx, docs/organization/integrations/compliance/index.mdx, docs/organization/integrations/index.mdx
=> Masinette integrations elba

docs/product/onboarding/data-enrichment.mdx
Disabling a video that isn't rendering correctly, will re-implement it once we have it up on Vimeo. …
=> Remove non-functioning video embed

docs/organization/early-adopter-features/index.mdx, includes/insights-session-health-body.mdx
we GA'd session health on insights
=> ref(docs): rm session health from early adopter

docs/pricing/quotas/spike-protection.mdx
The [Minimum Event Calculation](https://docs.sentry.io/pricing/quotas/spike-protection/#minimum-event-calculation) section hasn't been updated to account for the different minimum floors for each SKU. `500` is only relevant to errors.
=> fix(spike protection): correct floor calculation explanation

develop-docs/sdk/telemetry/logs.mdx
=> Refine SDK behavior docs for logs to make buffering more clear

docs/platforms/javascript/common/configuration/integrations/console.mdx
As per https://github.com/getsentry/sentry-javascript/issues/15439#issuecomment-2786624106 this warning is no longer needed as of [9.13.0](https://github.com/getsentry/sentry-javascript/releases/tag/9.13.0
) where Cloudflare/Vercel (edge) support was added. Not entirely sure if there are other platforms that are still not supported will leave that one with you.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is …
=> docs: remove outdated/misleading warning

develop-docs/backend/api/design.mdx
In particular, this removes a bunch of stray backslashes, like `\{`.
It also uses more consistent formatting of paths, related to slashes and placeholders.
=> Make the API Design doc a bit more consistent

docs/platforms/apple/common/troubleshooting/index.mdx
Explain how to resolve a compilation error when subclassing specific classes in the troubleshooting guide.
Fixes https://github.com/getsentry/sentry-cocoa/issues/5079.
=> feat(apple): Troubleshooting for subclass error

docs/platforms/javascript/guides/cloudflare/index.mdx
ref https://linear.app/getsentry/issue/BUNDLER-51
quick note that aligns with https://developers.cloudflare.com/workers/wrangler/configuration/#source-maps …
=> feat(cloudflare): Add jsonc instructions for sourcemaps upload

docs/platforms/apple/common/data-management/data-collected.mdx, docs/platforms/apple/common/index.mdx
- the goal is to link to this page from wizard and other places, where we don't necessarily know which platform the user is interested in - we want to ensure that user is aware that data collected might vary from platform to platform
- see e.g. https://github.com/getsentry/sentry-wizard/pull/981
- only shown on `/platforms/apple/data-management/data-collected/`, not shown on a platform-specific version (guide) of the page (i.e. `/platforms/apple/guides/<platform>/data-management/data-collected/`) …
=> chore(Apple): Adds callout that data collected is platform specific

docs/platforms/xbox/index.mdx, package.json, src/components/platformIcon.tsx, src/data/platforms.yml, yarn.lock
closes https://github.com/getsentry/team-gdx/issues/42 …
=> feat: xbox docs

docs/platforms/apple/common/configuration/app-hangs.mdx
Remove the experimental notes and bump the min version. We have to release 8.50.0 before merging this PR. Related to https://github.com/getsentry/sentry-cocoa/issues/4927.
=> feat(apple): Make app hangs V2 GA

docs/platforms/unity/tracing/index.mdx
I think here we could improve a lot what tracing does for Unith game devs.
That blurb is clearly some copy paste of whatever backend framework this was written for.
Linking to you ur new doc on tracing is also a good opportunity.
@bitsandfoxes Feel free to close this PR and take over if u have more ideas
Relates to: https://github.com/getsentry/sentry-docs/pull/13516/
=> unity: note on tracing powering errors

docs/platforms/react-native/integrations/component-names.mdx
The docs reference both "reactComponentAnnotation" and "annotateReactComponents", the latter one seems to be the correct one …
=> Fix old option name for the component annotation docs

docs/platforms/python/configuration/options.mdx, docs/platforms/python/index.mdx, docs/platforms/python/integrations/asgi/index.mdx, docs/platforms/python/integrations/asyncio/index.mdx, docs/platforms/python/integrations/aws-lambda/manual-instrumentation/index.mdx, docs/platforms/python/integrations/beam/index.mdx, docs/platforms/python/integrations/celery/crons.mdx, docs/platforms/python/integrations/celery/index.mdx, docs/platforms/python/integrations/cloudresourcecontext/index.mdx, docs/platforms/python/integrations/django/index.mdx, docs/platforms/python/integrations/gcp-functions/index.mdx, docs/platforms/python/integrations/grpc/index.mdx, docs/platforms/python/integrations/langchain/index.mdx, docs/platforms/python/integrations/litestar/index.mdx, docs/platforms/python/integrations/ray/index.mdx, docs/platforms/python/integrations/rq/index.mdx, docs/platforms/python/integrations/rust_tracing/index.mdx, docs/platforms/python/integrations/sanic/index.mdx, docs/platforms/python/integrations/serverless/index.mdx, docs/platforms/python/integrations/socket/index.mdx, docs/platforms/python/integrations/spark/index.mdx, docs/platforms/python/integrations/strawberry/index.mdx, docs/platforms/python/integrations/tryton/index.mdx, docs/platforms/python/integrations/wsgi/index.mdx, platform-includes/getting-started-config/python.mdx
=> docs(profiling): Update python onboarding to use continuous profiling

docs/platforms/unreal/index.mdx
We still need a proper section on the docs describing how to get access, and some level of detail to it as much as we're allowed to add
=> unreal engine: note on xbox and playstation support

docs/platforms/apple/guides/ios/session-replay/index.mdx, docs/platforms/apple/guides/ios/session-replay/performance-overhead.mdx, docs/platforms/react-native/session-replay/index.mdx
Starting with sentry-cocoa v8.50.0 the experimental view renderer is now considered GA and enabled by default. It is possible to opt-out by setting the option `options.sessionReplay.enableViewRendererV2 = false`
=> chore(apple): Remove enableExperimentalViewRenderer after GA

docs/platforms/apple/common/configuration/app-hangs.mdx
Remove referencing 8.45.0 in the app hangs docs, as the feature is GA since 8.50.0.
=> fix(apple): App hangs V2 remove confusing version

docs/platforms/native/advanced-usage/stack-overflow-handling/index.mdx
Intermediate draft for stack overflow handling in advanced usage. Not ready for review.
Relates to https://github.com/getsentry/sentry-native/pull/1196 …
=> feat(native): add stack overflow handling to advanced usage

platform-includes/enriching-events/scopes/configure-scope/native.mdx, platform-includes/enriching-events/set-user/native.mdx, platform-includes/sensitive-data/set-user/native.mdx
Relevant vercel preview pages
- https://sentry-docs-plsrr24j2.sentry.dev/platforms/native/enriching-events/scopes/#configuring-the-scope
- https://sentry-docs-plsrr24j2.sentry.dev//platforms/native/enriching-events/identify-user/
- https://sentry-docs-plsrr24j2.sentry.dev/platforms/native/data-management/sensitive-data/#examples
Related to the change in https://github.com/getsentry/sentry-native/pull/1228
From now on, we provide the `sentry_value_new_user(id, username, email, ip_address)` function that fills out the correct keys. This should reduce user error & confusion with what keys are processed by Sentry (see the [original issue](https://github.com/getsentry/sentry-native/issues/1225) the function was added for).
Help us prioritize incoming PRs by letting us know when the change …
=> feat(native): update `set_user` calls to use new `new_user` function output

.github/CODEOWNERS
the getsantry bot now auto merges the prs on this file, so we don't need to manually approve the prs. 
currently its jut creating noise and noone looks at the prs anyway so removing api-tsc
=> :wrench: chore: remove api tsc from open api hash file codeowners

docs/platforms/javascript/guides/react-router/index.mdx
Should document changes made in https://github.com/getsentry/sentry-javascript/pull/16197
TL;DR: Users no longer need to pass SentryOptions to the Vite global config—this is now handled under the hood by the React Router Vite plugin.
=> docs(react-router): Update source maps section for a PR

docs/platforms/python/migration/2.x-to-3.x.mdx
We'll release an alpha version of the new major of the Python SDK soon. Preparing a migration guide to go with it.
**Direct link to preview:** https://sentry-docs-git-ivana-pythonmigration-guide-30.sentry.dev/platforms/python/migration/2.x-to-3.x …
=> feat(python): Add the 3.x migration guide

docs/platforms/javascript/common/configuration/integrations/prisma.mdx, docs/platforms/javascript/common/configuration/integrations/prisma__v8.x.mdx, platform-includes/configuration/integrations/javascript.astro.mdx, platform-includes/configuration/integrations/javascript.bun.mdx, platform-includes/configuration/integrations/javascript.connect.mdx, platform-includes/configuration/integrations/javascript.fastify.mdx, platform-includes/configuration/integrations/javascript.hapi.mdx, platform-includes/configuration/integrations/javascript.nestjs.mdx, platform-includes/configuration/integrations/javascript.nextjs.mdx, platform-includes/configuration/integrations/javascript.node.mdx, platform-includes/configuration/integrations/javascript.nuxt.mdx, platform-includes/configuration/integrations/javascript.remix.mdx, platform-includes/configuration/integrations/javascript.solidstart.mdx, platform-includes/configuration/integrations/javascript.sveltekit.mdx
Documents https://github.com/getsentry/sentry-javascript/pull/16073 …
=> feat: Add note that prisma is enabled by default

docs/platforms/python/migration/2.x-to-3.x.mdx
I just copied the Discord link from our readme, but it looks like that was not pointing to our Discord in the first place. Fixing both in the readme and here …
=> Fix Discord link

docs/platforms/javascript/guides/cloudflare/features/durableobject.mdx, docs/platforms/javascript/guides/cloudflare/index.mdx
Documents https://github.com/getsentry/sentry-javascript/issues/15975 / https://github.com/getsentry/sentry-javascript/pull/16180 …
=> feat(cloudflare): Add docs for durable objects instrumentation

docs/platforms/javascript/common/apis.mdx, docs/platforms/javascript/common/enriching-events/tags/index.mdx
Closes https://linear.app/getsentry/issue/FE-394/user-feedback-tags-with-spaces-cause-problems
=> feat(js): Better document tag key/value requirements

develop-docs/sdk/data-model/event-payloads/sdk.mdx
This PR adds documentation for `settings` in the `sdk` context.  This enables the SDK to control certain mechanisms without relying on "magic values" like `{{auto}}` for `ip_address`.
Currently only `infer_ip` is implemented but new fields might be introduced in the future.
See https://github.com/getsentry/relay/pull/4623 …
=> Update documentation for event payload

docs/platforms/rust/common/source-context/index.mdx
Just a typo, it needs to be `profile` for it to work
=> fix(rust): fix typo in source context docs

package.json, yarn.lock
Bumps `platformicons` to the latest version.
The Rust and Actix icons have been improved, plus some new icons have been added.
=> chore(deps): bump platformicons

platform-includes/configuration/drain-example/apple.mdx
Updating the Apple drain doc to include the `close ( )` method. 
Liked to #13468
=> Add `close( )` method to Apple drain doc

develop-docs/application-architecture/feedback-architecture.mdx
`user-feedback-replay-clip` was added in self-hosted v24.7.1 and removed in v25.4.0. Therefore if you're on v25.3.0 keep that clip config in your install. Once you get past 25.3.0 then it's ok to remove.
**Timeline**
- March 17 
- [v25.3.0](https://github.com/getsentry/sentry/releases/tag/25.3.0) released
- March 24
- Depends on https://github.com/getsentry/sentry/pull/87770
- Depends on https://github.com/getsentry/sentry/pull/87771
- Depends on https://github.com/getsentry/sentry-options-automator/pull/3386
- April 15
- [v25.4.0](https://github.com/getsentry/sentry/releases/tag/25.4.0) released
=> chore: user-feedback-replay-clip feature is always enabled

docs/platforms/dotnet/common/configuration/heap-dumps.mdx
=> nitpick csharp code snippet

platform-includes/performance/add-spans-example/native.mdx
[Vercel Preview](https://sentry-docs-htn2uy3fb.sentry.dev/platforms/native/tracing/instrumentation/custom-instrumentation/#:~:text=it%20to%20Sentry.-,By%20default%2C,-transactions%20will%20inherit)
Related to the feature added in https://github.com/getsentry/sentry-native/pull/1137 & the update to native tracing in https://github.com/getsentry/sentry-native/pull/1200
Since transactions no longer create a new `trace_id`, we want to document how to set up a trace boundary with `sentry_set_trace()`. …
=> Add set_trace example

develop-docs/sdk/expected-features/index.mdx, develop-docs/sdk/telemetry/traces/distributed-tracing/index.mdx, develop-docs/sdk/telemetry/traces/dynamic-sampling-context.mdx, develop-docs/sdk/telemetry/traces/index.mdx
We currently have no plans to add support for the W3C `traceparent` header in our SDKs. Removing the docs around this.
=> Remove `traceparent` docs

docs/platforms/dotnet/index.mdx
The main page for the .NET SDK docs currently includes a hard coded DSN... which would be confusing for users.
- [ X ] None: Not urgent, can wait up to 1 week+
cc: @vaind @bruno-garcia @Flash0ver 
=> Fix hard coded DSN in the dotnet docs

develop-docs/sdk/data-model/event-payloads/contexts.mdx
The Electron SDK has started including this:
https://github.com/getsentry/sentry-electron/blob/bcfdbfec0c6d2f3eb28430fb8d0121d4b61123ac/src/main/integrations/gpu-context.ts#L20
=> feat(develop): Add `driver_version` to GPU context

docs/platforms/javascript/common/configuration/integrations/breadcrumbs.mdx, docs/platforms/javascript/common/data-management/data-collected/index.mdx, docs/platforms/javascript/guides/electron/configuration/integrations/additionalcontext.mdx, docs/platforms/javascript/guides/electron/configuration/integrations/electronbreadcrumbs.mdx, docs/platforms/javascript/guides/electron/configuration/integrations/gpucontext.mdx, docs/platforms/javascript/guides/electron/configuration/integrations/net.mdx
Adds to the JavaScript "Data Collected" page to include additional details for Electron. This PR also adds a missing GPU integration which needing referencing and updated a couple of other integrations that had out of date configuration options.
=> feat(electron): Add "Data Collected"

docs/platforms/rust/common/tracing/instrumentation/automatic-instrumentation.mdx
Documents the newly released OTEL integration for the Rust SDK.
Content is largely the same as the crate docs available here https://crates.io/crates/sentry-opentelemetry
Closes https://github.com/getsentry/sentry-rust/issues/781
=> feat(rust): document OTEL integration

develop-docs/sdk/telemetry/logs.mdx, docs/platforms/android/logs/index.mdx, docs/platforms/java/common/logs/index.mdx, docs/product/explore/logs/getting-started/index.mdx, platform-includes/logs/integrations/android.mdx, platform-includes/logs/integrations/java.mdx, platform-includes/logs/options/android.mdx, platform-includes/logs/options/java.mdx, platform-includes/logs/requirements/android.mdx, platform-includes/logs/requirements/java.mdx, platform-includes/logs/setup/android.mdx, platform-includes/logs/setup/java.mdx, platform-includes/logs/usage/android.mdx, platform-includes/logs/usage/java.mdx
=> Basic docs for Java Logging

.github/workflows/codeowner_assignment.yaml
Adding a check so that if a codeowner is already in the requested reviewer list then skip it, otherwise every new commit to the PR will trigger the workflow to readd the codeowner.
=> fix(codeowners): Skip requested reviewers

docs/platforms/native/common/configuration/filtering.mdx, docs/platforms/native/common/configuration/options.mdx, platform-includes/configuration/before-send-transaction/native.mdx, platform-includes/performance/traces-sampler-as-sampler/native.mdx
Part of https://github.com/getsentry/sentry-native/pull/1236
=> feat(native): update transaction docs

platform-includes/profiling/node-profiling/javascript.mdx
We dont support Node 16 in the SDK anymore, and Node 24 was just added. …
=> fix: Reflect most recent node version support for node profiling

develop-docs/sdk/telemetry/traces/dynamic-sampling-context.mdx
Seems like it should have been TODO comment in a first place, 3 years ago.
Since in 3 years it hasn't been touched, seems to be good to deleted
=> docs: remove old DSC content

docs/product/explore/logs/getting-started/index.mdx
Removing Go from Upcoming SDKs …
=> Remove go and ruby from upcoming SDKs in logs getting started

develop-docs/sdk/expected-features/data-handling.mdx
Tag key char limit was increased to 200: 
- https://github.com/getsentry/relay/blob/master/relay-event-normalization/src/lib.rs#L57-L66
- https://github.com/getsentry/sentry/blob/master/src/sentry/sentry_metrics/consumers/indexer/tags_validator.py#L11-L12
- https://github.com/getsentry/sentry/blob/master/src/sentry/sentry_metrics/configuration.py#L15-L17
=> correct tag key char limit

includes/dart-integrations/routing-instrumentation.mdx
We'll remove support for manual TTID, we can remove the docs of it.
=> fix(flutter): Remove outdated manual TTID API

platform-includes/getting-started-install/javascript.azure-functions.mdx
noticed that we showed the generic browser JS (CDN and NPM package) installation instructions instead of the `@sentry/node` SDK for Azure. This PR adds an `azure-functions` specific install snippet.
=> fix(azure-functions): Show correct installation snippet

develop-docs/development-infrastructure/devservices.mdx
```
➜ devservices toggle snuba LOCAL
usage: devservices [-h] [--version] COMMAND ... toggle [-h] [--debug] [service_name] [{local,containerized}]
devservices [-h] [--version] COMMAND ... toggle: error: argument runtime: invalid choice: 'LOCAL' (choose from local, containerized)
```
Look, I get it. The entity doing …
=> fix: devservices use local not LOCAL

docs/organization/integrations/deployment/expo/index.mdx, docs/organization/integrations/deployment/index.mdx
We are in process of shipping an integration with the Expo EAS platform. Serves to document and reference setting up the integrations with Sentry.
[Preview](https://sentry-docs-git-featadd-expo-integration.sentry.dev/organization/integrations/deployment/expo/)
=> Add Expo Integrations Docs

src/components/expandable/index.tsx, src/components/expandable/style.module.scss
The previous approach was not working on safari, so we just conditionally render the icon altogether now.
=> fix(platform): Fix expandable state

src/instrumentation.ts
This is a temporary change to evaluate effects on grouping in Sentry.
=> feat(platform): Set `sentry.source` to `custom` for edge requests

src/components/sidebarTableOfContents/index.tsx, src/components/sidebarTableOfContents/style.module.scss
Instead of enlarging the text to two rows, long menu items get an ellipsis at the end, like here:
closes https://github.com/getsentry/sentry-docs/issues/13766
=> feat(menu): Add ellipsis to cut long menu items

src/components/expandable/index.tsx, src/components/expandable/style.module.scss
fixes UI regression introduced in https://github.com/getsentry/sentry-docs/pull/13752
=> fix(platform): Fix chevron state + expandable stylings

platform-includes/logs/usage/dart.mdx
Updates snippets since currently attributes with hyphens cant be filtered so let's not make it harder for the user to figure out why and give them a snippet with immediate success
=> fix(flutter): Update logs snippet

docs/platforms/javascript/common/configuration/integrations/vercelai.mdx
`Sentry.vercelAIIntegration` is not a constructor so drop the `new` keyword.
=> Fix Vercel AI instructions

platform-includes/llm-rules-logs/javascript.nextjs.mdx, platform-includes/llm-rules-logs/javascript.node.mdx, platform-includes/llm-rules-logs/javascript.react.mdx, platform-includes/llm-rules-platform/_default.mdx, platform-includes/llm-rules-platform/javascript.nextjs.mdx, platform-includes/llm-rules-platform/javascript.node.mdx, platform-includes/llm-rules-platform/javascript.react.mdx
This fixes some content that was added in https://github.com/getsentry/sentry-docs/pull/13752:
1. Moves logs down below tracing, as that is IMHO more important (and stable - logs is still experimental 😬 ) (should not affect LLMs too much, but for consistency sake with other things...)
2. Remove the line about adding the `logger` integration, which does not exist
3. Fix the tracing snippets to be better - what we recommended there was actually not what we would want users to do.
=> fix(js): Fix LLM instruction docs

platform-includes/debug-symbols/dart-plugin/dart.flutter.mdx
=> dart.flutter add url_prefix

docs/platforms/react-native/session-replay/index.mdx, docs/platforms/react-native/session-replay/privacy/index.mdx
Adds warning about the current masking issue with manual init. …
=> Add SR RN native manual init warning

docs/platforms/python/configuration/options.mdx
A small hint that changing this option will result in changed grouping of errors into issue.  …
=> Python hint about changed grouping by changing of an option

docs/platforms/javascript/common/configuration/integrations/amqplib.mdx, docs/platforms/javascript/common/configuration/integrations/bunserver.mdx, docs/platforms/javascript/common/configuration/integrations/connect.mdx, docs/platforms/javascript/common/configuration/integrations/fastify.mdx, docs/platforms/javascript/common/configuration/integrations/hapi.mdx, docs/platforms/javascript/common/configuration/integrations/koa.mdx, docs/platforms/javascript/common/configuration/integrations/lrumemoizer.mdx, docs/platforms/javascript/common/configuration/integrations/tedious.mdx
We don't use class based integrations so these aren't needed anymore
=> fix: Remove new keyword from js integrations

docs/platforms/javascript/common/configuration/options.mdx
These SDKs have never had this option. …
=> Remove `autoInitializeNativeSdk` from Capacitor and Cordova options

docs/platforms/dotnet/common/troubleshooting.mdx
Added docs on troubleshooting "Detected package version outside of dependency constraint" errors. 
Resolves https://github.com/getsentry/sentry-dotnet/issues/4095 (see [comment](https://github.com/getsentry/sentry-dotnet/issues/4095#issuecomment-2834487925))
- cc: @Flash0ver 
=> Detected package version outside of dependency constraint

docs/platforms/unreal/configuration/setup-crashreporter/index.mdx
This PR adds a note about the platforms where `Crash Reporter` is supported as an addition to the `CRC vs Sentry SDK` comparison.
=> Unreal Engine: Add note on supported platforms for Crash Reporter

docs/platforms/unreal/configuration/debug-symbols/index.mdx
This PR updates the `Debug Symbols Uploading` section of the Unreal SDK documentation by explaining how to force the generation of `dSYM` files when building a game for Mac or iOS. This helps resolve the issue of missing line numbers in call stacks for events captured on these platforms (https://github.com/getsentry/sentry-unreal/issues/917).
=> Add instruction how force `dSYM` generation in Unreal Engine for Mac/iOS builds

docs/platforms/javascript/guides/nestjs/features/event-emitter.mdx
documents https://github.com/getsentry/sentry-javascript/pull/16306
ref https://github.com/getsentry/sentry-javascript/issues/15218
=> docs(js): Add note on nestjs `OnEvent` decorators

docs/platforms/python/integrations/celery/crons.mdx
A clarifying sentence to explain how to avoid double instrumentation of Celery beat tasks in Python.  …
=> Clarify double instrumentation issue

docs/platforms/react-native/sourcemaps/uploading/hermes.mdx
This adds a section explaining when and why Hermes source maps might not be correct for application using Hermes. …
=> Add Hermes manual source maps Troubleshooting section

docs/platforms/apple/guides/ios/session-replay/customredact.mdx
The code snippets had white space prefix which doesn't seem to be intentional and looks bad in the rendered website. …
=> Fix iOS SR Custom Redact whitespace prefix in code snippets

docs/platforms/javascript/common/configuration/integrations/graphqlclient.mdx, platform-includes/configuration/integrations/javascript.astro.mdx, platform-includes/configuration/integrations/javascript.capacitor.mdx, platform-includes/configuration/integrations/javascript.cordova.mdx, platform-includes/configuration/integrations/javascript.gatsby.mdx, platform-includes/configuration/integrations/javascript.mdx, platform-includes/configuration/integrations/javascript.nextjs.mdx, platform-includes/configuration/integrations/javascript.nuxt.mdx, platform-includes/configuration/integrations/javascript.remix.mdx, platform-includes/configuration/integrations/javascript.solidstart.mdx, platform-includes/configuration/integrations/javascript.sveltekit.mdx, platform-includes/configuration/integrations/javascript.vue.mdx, platform-includes/configuration/integrations/javascript.wasm.mdx
Documents PR https://github.com/getsentry/sentry-javascript/pull/13783 mentioned in issue https://github.com/getsentry/sentry-javascript/issues/13399
closes https://github.com/getsentry/sentry-docs/issues/13800
=> docs(javascript): Add docs for GraphQL Client

docs/platforms/elixir/integrations/telemetry/index.mdx
Docs for [this change](https://github.com/getsentry/sentry-elixir/pull/887).
=> Add docs for Elixir/Telemetry integration

platform-includes/getting-started-install/unity.mdx
See:
* https://github.com/getsentry/sentry-unity/issues/2162
=> remove version pinning Unity repo

app/layout.tsx
ref https://docs.kapa.ai/integrations/website-widget/user-tracking#disabling-user-tracking
> As of June 25th 2025, Kapa's widget will use opt-out tracking by default, rather than the current opt-in approach. This means [anonymous user tracking](https://docs.kapa.ai/integrations/website-widget/user-tracking#anonymous-user-tracking) is enabled automatically unless [explicitly disabled](https://docs.kapa.ai/integrations/website-widget/user-tracking#disabling-user-tracking). This change helps provide better analytics and user journey insights while still maintaining privacy compliance options. Review the configuration options below to ensure your implementation aligns with your privacy requirements.
This PR disables tracking.
@stephanie-anderson fyi
=> feat(platform): Explicitly disable kapa tracking

platform-includes/logs/requirements/python.mdx
https://github.com/getsentry/sentry-python/releases/tag/2.28.0
This moves off of using `otel_log`, which we want to avoid sdk users sending.
=> Update min python version to be 2.28.0

docs/platforms/javascript/guides/aws-lambda/install/cjs-layer.mdx, docs/pricing/index.mdx
Updating pricing for Seer launch, see https://sentry-docs-git-seer-pricing.sentry.dev/pricing/ for preview. …
=> Seer pricing

docs/platforms/javascript/common/configuration/integrations/browserapierrors.mdx, docs/platforms/javascript/common/troubleshooting/index.mdx
Documents a new option added via https://github.com/getsentry/sentry-javascript/pull/16412. Also added a troubleshooting section as adding this option was the result of investigating a user-reported SDK issue (https://github.com/getsentry/sentry-javascript/issues/16398) …
=> feat(browser): Document `unregisterOriginalCallbacks` option in `browserApiErrors` integration page

docs/platforms/rust/guides/actix-web/config.yml, docs/platforms/rust/guides/actix-web/index.mdx, docs/platforms/rust/index.mdx
Summary:
- change display name to `Actix Web`
- follow new getting started structure (Install, Configure, Verify)
- remove (contradicting) mentions of implementation details
- update dependency snippet to match the recommended way to depend on this integration
- include more useful config options that were not mentioned …
=> refactor(actix): improve Actix docs

docs/platforms/javascript/common/configuration/options.mdx
Implicitly reported via https://github.com/getsentry/sentry-javascript/pull/16439 that according to the type in the options page, the `beforeSendSpan` callback can return `null`. This is no longer the case since v9 of the SKD.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions …
=> fix(js): Fix incorrect `beforeSendSpan` callback type

docs/product/explore/trace-explorer/index.mdx
Making these docs a bit clearer re: traces, transactions, spans
=> Quick update to trace explorer doc

docs/platforms/apple/common/troubleshooting/index.mdx
Add an entry to the troubleshooting guide on a bug leading to unsymbolicated stacktraces for non fatal events.
The hotfix 8.52.1 is under progress and should be released soon.
=> feat(apple): Explain unsymbolicated stacktraces

docs/platforms/javascript/guides/hono/index.mdx, platform-includes/getting-started-use/javascript.hono.mdx
Update the hono include to be semi-correct (uncertain if used currently).
=> feat: Improve Hono docs to cover errors + Node.js

docs/platforms/javascript/guides/react-router/index.mdx
documents https://github.com/getsentry/sentry-javascript/pull/16470
documents https://github.com/getsentry/sentry-javascript/pull/16481
=> docs(js): Add alert on auto-instrumentation for react-router framework

docs/product/relay/operating-guidelines.mdx
Adds description with versions for relay binaries and how long we support each operating system.
I also added a description to the build config to update the documentation in case it gets updated: https://github.com/getsentry/relay/pull/4794
=> ref: add minimum required OS version for relay binary

docs/platforms/apple/common/index.mdx
Add code snippet for reporting uncaught NSExceptions on macOS, because users often miss that step during setup.
=> feat(apple): Code for NSExceptions in configure

apps/changelog/package.json, next.config.ts, package.json, yarn.lock
- Moves `next.config.js` to `next.config.ts`
- Removes some deprecated/unused SDK options
- Bumps the sentry SDK to latest
=> chore(platform): Move next config file + bump sentry

docs/platforms/unreal/configuration/options.mdx
Related to https://github.com/getsentry/sentry-unreal/pull/953
=> Unreal Engine: Add option to delay app shutdown until Crashpad completes crash report upload

docs/platforms/php/common/configuration/options.mdx, docs/platforms/php/common/logs/index.mdx, docs/product/explore/logs/getting-started/index.mdx, platform-includes/logs/options/php.mdx, platform-includes/logs/requirements/php.mdx, platform-includes/logs/setup/php.mdx, platform-includes/logs/usage/php.mdx
Document the Logs integration for PHP (getsentry/sentry-php#1813).
This PR is pending the release of the PHP SDK version 4.12.0.
=> Document the Logs integration for PHP

docs/platforms/godot/configuration/options.mdx, docs/platforms/godot/configuration/stack-traces.mdx, platform-includes/capture-message/godot.mdx, platform-includes/configuration/before-send/godot.mdx, platform-includes/configuration/config-intro/godot.mdx, platform-includes/configuration/sample-rate/godot.mdx, platform-includes/enriching-events/breadcrumbs/breadcrumbs-example/godot.mdx, platform-includes/enriching-events/set-context/godot.mdx, platform-includes/enriching-events/set-tag/godot.mdx, platform-includes/enriching-events/set-user/godot.mdx, platform-includes/enriching-events/unset-user/godot.mdx, platform-includes/getting-started-install/godot.mdx, platform-includes/getting-started-primer/godot.mdx, platform-includes/getting-started-verify/godot.mdx, platform-includes/sensitive-data/set-tag/godot.mdx, platform-includes/sensitive-data/set-user/godot.mdx, platform-includes/set-environment/godot.mdx, platform-includes/set-level/godot.mdx, platform-includes/set-release/godot.mdx
Synchronize Godot documentation with the latest changes. …
=> Godot: Synchronize documentation with latest changes

docs/platforms/javascript/common/index.mdx, docs/platforms/javascript/guides/angular/manual-setup.mdx, docs/platforms/javascript/guides/astro/index.mdx, docs/platforms/javascript/guides/capacitor/index.mdx, docs/platforms/javascript/guides/electron/index.mdx, docs/platforms/javascript/guides/ember/index.mdx, docs/platforms/javascript/guides/gatsby/index.mdx, docs/platforms/javascript/guides/nextjs/manual-setup.mdx, docs/platforms/javascript/guides/nuxt/manual-setup.mdx, docs/platforms/javascript/guides/react-router/index.mdx, docs/platforms/javascript/guides/react/index.mdx, docs/platforms/javascript/guides/remix/manual-setup.mdx, docs/platforms/javascript/guides/solid/index.mdx, docs/platforms/javascript/guides/svelte/index.mdx, docs/platforms/javascript/guides/sveltekit/manual-setup.mdx, docs/platforms/javascript/guides/tanstackstart-react/index.mdx, docs/platforms/javascript/guides/vue/index.mdx, platform-includes/getting-started-config/javascript.mdx, src/components/onboarding/index.tsx
A "User Feedback" checkbox was added to the onboarding component, allowing users to opt-in to user feedback integration during setup.
Changes were made to `src/components/onboarding/index.tsx`:
*   The `optionDetails` object was updated to include a new `'user-feedback'` entry. This defines the checkbox's display name ("User Feedback") and a descriptive tooltip: "Collect user feedback from anywhere in your application with an embeddable widget that allows users to report bugs and provide insights."
*   The `OPTION_IDS` array was extended to include `'user-feedback'`, ensuring the new checkbox appears in the setup flow alongside existing options like tracing and session replay.
This modification successfully integrates the new UI element. However, it was confirmed that the checkbox's state …
=> Add user feedback integration checkbox

docs/security-legal-pii/scrubbing/protecting-user-privacy.mdx
Changes requested/approved by Loretta on the Legal team, preview url: https://sentry-docs-git-privacy-updates.sentry.dev/security-legal-pii/scrubbing/protecting-user-privacy/ …
=> Add updates regarding replay to user privacy page

docs/product/insights/ai/llm-monitoring/getting-started/index.mdx
The `docs/product/insights/ai/llm-monitoring/getting-started/index.mdx` page was updated to document JavaScript SDK support for LLM monitoring via the Vercel AI integration.
Key changes include:
*   The previous alert stating "This feature is currently only available in the Python SDK" was removed.
*   Content was restructured with new "Supported SDKs" sections for Python and JavaScript.
*   A dedicated JavaScript section was added, detailing support for the Vercel AI integration.
*   A comprehensive list of supported JavaScript platforms was included, using `LinkWithPlatformIcon` components, such as Node.js, Next.js, SvelteKit, Nuxt, and various server/serverless frameworks.
*   An alert was added to clarify that the Vercel AI integration is limited to Node.js and Bun runtimes and …
=> Update llm monitoring documentation for JavaScript

src/components/expandable/index.tsx
The copy logic within the `Expandable` component in `src/components/expandable/index.tsx` was refined to prevent unwanted inline code from being copied.
Previously, the copy button selected all `<code>` elements, including inline code snippets like `.cursorrules` and `rules.md` from explanatory text.
The changes implement a more selective approach:
*   **Primary Selection**: The component now first attempts to copy content from `pre code` elements, which typically contain main code blocks.
*   **Fallback Filtering**: If no `pre code` blocks are found, a fallback mechanism filters all `<code>` elements. It excludes:
*   Code elements found within paragraphs.
*   Short code snippets (less than 100 characters), which are likely inline.
*   **Final Fallback**: If no suitable code blocks are …
=> Fix copy button output on logging page

docs/product/sentry-toolbar/faq.mdx, docs/product/sentry-toolbar/setup.mdx
New content look like this:
Related to https://github.com/getsentry/sentry/pull/93206
Related to https://github.com/getsentry/sentry-options-automator/pull/4119
=> docs(toolbar): Update @sentry/toolbar docs to include help for CSP issues

platform-includes/getting-started-config/go.mdx
=> fix(go): Remove usage of spaces

docs/concepts/key-terms/dsn-explainer.mdx, docs/organization/getting-started/index.mdx, docs/pricing/quotas/index.mdx, docs/pricing/quotas/manage-event-stream-guide.mdx, docs/product/sentry-basics/distributed-tracing/create-new-project.mdx, docs/product/sentry-basics/integrate-backend/getting-started.mdx, docs/product/sentry-basics/integrate-frontend/create-new-project.mdx
- There was some feedback about not finding the client keys - looking at the settings, it makes sense that you would look only under Project > Settings > Project and not further down. 
- Not sure whether this is a conscious choice to not refer to the sub-group in settings. If this change is useful, we should probably also update all other project settings paths in the docs.
=> chore(dsn): update reference to dsn settings from settings -> client keys to settings -> sdk setup -> client keys

docs/platforms/react-native/migration/sentry-expo.mdx
closes: https://linear.app/getsentry/issue/RN-195/what-to-do-with-the-post-publish-hook-in-appconfigjs-when-migrating-to …
=> Add `postPublish` hooks removal to `sentry-expo` migration guide

docs/platforms/python/integrations/logging/index.mdx, docs/platforms/python/integrations/loguru/index.mdx, platform-includes/logs/integrations/python.mdx
- add basic Loguru setup examples to the [Structured logs page](https://sentry-docs-git-ivana-pythonloguru-sentry-logs.sentry.dev/platforms/python/logs/#loguru)
- link to the logs docs page from the [Loguru integration page](https://sentry-docs-git-ivana-pythonloguru-sentry-logs.sentry.dev/platforms/python/integrations/loguru/)
- link to the logs docs page from the [logging integration page](https://sentry-docs-git-ivana-pythonloguru-sentry-logs.sentry.dev/platforms/python/integrations/logging/)
Closes https://github.com/getsentry/sentry-python/issues/4461
- Please give the docs team up to 1 week to review your PR unless you've added …
=> feat(python): Add Loguru to Sentry logs docs

docs/security-legal-pii/scrubbing/advanced-datascrubbing.mdx
Adds an example to better visualise the behaviour of the deep wildcard selector (`**`) if used in a sub-path.
closes RELAY-15
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize …
=> ref(pii): add example for wildcard selector

platform-includes/logs/setup/php.laravel.mdx
The current example uses the previous log driver, which creates issues instead of logs.
=> Fix Laravel log driver name

docs/platforms/unreal/index.mdx, docs/platforms/unreal/install/index.mdx
This PR moves the detailed description of all Sentry Unreal Engine SDK installation options to a dedicated `Installation Methods` page. This simplifies the landing page and lets us clearly highlight the recommended installation method which is downloading the SDK from the GitHub Releases page.
=> Move Unreal Engine SDK installation options to a separate page

docs/platforms/unity/configuration/il2cpp/index.mdx
The documentation for IL2CPP support was updated to include Xbox in the list of supported platforms.
*   The file `docs/platforms/unity/configuration/il2cpp/index.mdx` was modified.
*   "Xbox" was added to the bulleted list of platforms that support IL2CPP line number support.
*   This change reflects confirmation that IL2CPP line number support functions on Xbox.
The updated list now includes:
*   Windows (*currently limited to Unity 2021.3 or newer)
*   macOS
*   Linux
*   Android
*   iOS
*   Xbox
=> Add Xbox to IL2CPP support list

docs/platforms/javascript/common/configuration/integrations/vercelai.mdx
- Updates the top snippet to include `recordInputs` and `recordOutputs` options.
- Switches the model used in other snippets
=> feat(vercelai): include input/output options

src/components/callout/styles.scss, src/components/codeBlock/code-blocks.module.scss, src/components/codeHighlights/codeHighlights.tsx, src/components/codeTabs.tsx
Code snippets across the documentation application now feature a consistent border style, aligning with the `Expandable` component's `callout` styling for visual cohesion.
This involved updating borders to `1px solid var(--accent-11)` and `border-radius` to `6px` across various code-related components.
Also updated callout-info boxes to an accent of 6 instead to reduce visual of the container itself. Text styling is unchanged to still pull in on text as needed, Creates a better contast. 
Specific changes were applied to:
*   Main code blocks in `src/components/codeBlock/code-blocks.module.scss`:
*   `pre[class*='language-']` now has `border: 1px solid var(--accent-11)` and `border-radius: 6px`.
*   The `pre` element's `border-radius` was also updated to `6px` for consistency.
*   Code …
=> feat: Change visual emphasis of code snippets and info callout

docs/platforms/android/user-feedback/configuration/index.mdx, docs/platforms/android/user-feedback/index.mdx, docs/platforms/java/common/user-feedback/index.mdx, platform-includes/user-feedback/sdk-api-example/android.mdx, platform-includes/user-feedback/sdk-api-example/java.mdx
added new User Feedback API instructions
added new User Feedback Widget configuration options
=> Add Android new User Feedback instructions

docs/platforms/javascript/common/configuration/integrations/koa.mdx
Documents https://github.com/getsentry/sentry-javascript/pull/16553, released with https://github.com/getsentry/sentry-javascript/releases/tag/9.29.0
=> feat: Document `ignoreLayersType` in koa integration

docs/platforms/javascript/guides/cloudflare/features/durableobject.mdx, platform-includes/getting-started-config/javascript.cloudflare.workers.mdx, platform-includes/logs/setup/javascript.cloudflare.mdx, platform-includes/performance/configure-sample-rate/javascript.cloudflare.mdx
Explicitly using `Env` should help with some type issues. Part of https://github.com/getsentry/sentry-javascript/pull/16650 …
=> feat(cloudflare): Use explicit Env casting

src/instrumentation-client.ts
Adds the future-proof way of instrumenting client-side navigations by using `onRouterTransitionStart`
=> feat(platform): Add onRouterTransitionStart

platform-includes/performance/configure-sample-rate/javascript.hono.mdx
Hono tracing page pointed to our browser sdk and also to our `browserTracingIntegration`, proof:
Now it point's to our node sdk:
=> Fix(hono): custom hono tracing instrumentation code

vercel.json
Now that we are [internally dogfooding these as logs](https://sentry.sentry.io/explore/logs/?project=4507503193292800) we can enable success.
=> chore(nel): Enable 1% NEL success

docs/platforms/react-native/migration/sentry-expo.mdx
EnableInExpoDevelopment looks like it disable sentry on non dev envs.
`__DEV__` is under prod = false which would mean Sentry = disabled or? …
=> EnableInExpoDevelopment looks like it disable sentry on non dev envs

platform-includes/distributed-tracing/custom-instrumentation/javascript.mdx
The documentation in `platform-includes/distributed-tracing/custom-instrumentation/javascript.mdx` was updated to correct the usage of `span.setStatus`.
*   Previously, `span.setStatus({ code: 'error' });` was used.
*   This has been changed to `span.setStatus({ code: 2, message: 'error' });`.
This modification aligns the documentation with the Sentry JavaScript SDK's `SpanStatus` interface, which expects a numerical `code` (following OpenTelemetry standards) rather than a string. The numerical code `2` signifies an 'error' status. This ensures that `span.setStatus` correctly updates the span's status, resolving issues where the status was not visually reflected due to incorrect API parameter types.
=> Update documentation for span.setStatus method

docs/platforms/python/integrations/index.mdx, docs/platforms/python/integrations/openai-agents/index.mdx
Documentation on how to use the AI Agents integration for the `openai-agents` package.  …
=> Python docs for the `openai-agents` integration

docs/platforms/javascript/common/sourcemaps/uploading/wrangler.mdx, platform-includes/sourcemaps/overview/javascript.cloudflare.mdx, platform-includes/sourcemaps/upload/primer/javascript.cloudflare.mdx
Documents the changes from https://github.com/getsentry/sentry-wizard/pull/999
ref https://github.com/getsentry/sentry-javascript/issues/14841
A new sourcemaps guide for Wrangler was added to the Cloudflare documentation.
*   A new guide, `docs/platforms/javascript/common/sourcemaps/uploading/wrangler.mdx`, was created.
*   It details both automatic setup via the Sentry Wizard and manual configuration.
*   Manual steps include installing `@sentry/cli`, configuring `sentry-cli`, and modifying the `package.json` scripts.
*   The `deploy` script is updated to include `--outdir`, `--upload-source-maps`, and `--var SENTRY_RELEASE:$(sentry-cli releases propose-version)`.
*   A `sentry:sourcemaps` script is added to create releases and upload sourcemaps.
*   A `postdeploy` script is introduced …
=> Create wrangler sourcemaps guide for Cloudflare

includes/platforms/configuration/integrations/requestdata.mdx
In 9.x, [`RequestDataIncludeOptions`](https://github.com/getsentry/sentry-javascript/blob/c37d4e5a7546be97afa92ae5d7950cc7b6542cdd/packages/core/src/integrations/requestdata.ts#L8-L15) no longer has `user`. Presumably because of this change from the migration guide:
> The `requestDataIntegration` will no longer automatically set the user from `request.user` when `express` is used. Starting in v9, you'll need to manually call `Sentry.setUser()` e.g. in a middleware to set the user on Sentry events.
However the option is still listed here: https://docs.sentry.io/platforms/javascript/guides/nextjs/configuration/integrations/requestdata/
This PR updates the docs to match the new types.
- Please give the docs team up to 1 …
=> Docs: Remove include.user from RequestData integration

docs/platforms/dotnet/common/user-feedback/index.mdx
Resolves https://github.com/getsentry/sentry-dotnet/pull/4284
See:
- https://github.com/getsentry/sentry-dotnet/pull/4284#discussion_r2152350658
cc: @Flash0ver 
=> Describe what happens to invalid email addresses in feedback

docs/platforms/javascript/guides/react-router/index.mdx, docs/platforms/javascript/guides/react/features/react-router/v7.mdx
Documentation for the React Router framework SDK was updated to reflect its transition from an alpha to a beta state.
closes https://github.com/getsentry/sentry-javascript/issues/16689
=> docs(js): Mark `@sentry/react-router` as beta

docs/concepts/data-management/filtering/index.mdx
We got some docs under Replay Details, added:
* https://github.com/getsentry/sentry-docs/pull/9975
But there's a dedicated page for Inbound Filters, so adding Replay info there too.
The note for stats being confusing can be updated once we address:
* https://github.com/getsentry/sentry/issues/93772
=> update inbound filters page with Session Replay details

docs/platforms/javascript/common/apis.mdx, docs/platforms/javascript/common/tracing/instrumentation/index.mdx
This adds missing docs about setting span status in JS SDKs.
=> feat: Add span status docs

develop-docs/sdk/telemetry/profiles/sample-format-v2.mdx
=> fix(profiling): fix sample v2 timestamp doc

docs/platforms/javascript/common/configuration/integrations/fetchIntegration.mdx, platform-includes/configuration/integrations/javascript.cloudflare.mdx
[Cursor created PR - Reviewed by me]
Broken links in the Cloudflare configuration documentation have been resolved.
*   A new file, `docs/platforms/javascript/common/configuration/integrations/fetchIntegration.mdx`, was created.
*   This addresses a 404 error caused by a missing page referenced by `fetchIntegration` in the integrations table.
*   The file includes metadata, documentation for `Sentry.fetchIntegration`, configuration options (`breadcrumbs`, `shouldCreateSpanForRequest`), and usage examples, specifically noting its relevance to Cloudflare Workers.
*   The link for `requestDataIntegration` in `platform-includes/configuration/integrations/javascript.cloudflare.mdx` was updated.
*   The previous link, `./requestDataIntegration`, had incorrect casing and pointed to a …
=> Fix broken link in Cloudflare docs

app/[[...path]]/page.tsx
Removing unnecessary escape characters that are showing up in SERP.
To verify go to https://sentry-docs-git-fix-title-ampersand.sentry.dev/ and confirm that when you hover over the tab, you see the ampersand in the title and not the escaped chars you'll see on the production site. …
=> Remove escape characters from hompage title and desc

docs/platforms/javascript/common/configuration/integrations/featureflags.mdx, docs/platforms/javascript/common/configuration/integrations/launchdarkly.mdx, docs/platforms/javascript/common/configuration/integrations/openfeature.mdx, docs/platforms/javascript/common/configuration/integrations/statsig.mdx, docs/platforms/javascript/common/configuration/integrations/unleash.mdx, docs/platforms/python/feature-flags/index.mdx, docs/platforms/python/integrations/launchdarkly/index.mdx, docs/platforms/python/integrations/openfeature/index.mdx, docs/platforms/python/integrations/statsig/index.mdx, docs/platforms/python/integrations/unleash/index.mdx
Since JS [9.31.0](https://github.com/getsentry/sentry-javascript/releases/tag/9.31.0) our FF integrations capture flags on spans, which are sent in [transaction events](https://develop.sentry.dev/sdk/data-model/event-payloads/transaction/). This PR updates the JS integration docs to mention this, and renames "trace events" to "transaction events" in python
=> ref(flags): mention spans/txn event support in JS integration docs

docs/platforms/react-native/troubleshooting/index.mdx
=> fix: Typo in RN troubleshooting docs

develop-docs/sdk/overview.mdx
This was missing before in our develop docs, now with the help of Cursor has been added with the note that it has restricted access
=> docs(playstation): Add playstation endpoint info to the docs

docs/organization/integrations/feature-flag/generic/index.mdx, docs/platforms/javascript/common/configuration/integrations/openfeature.mdx, docs/platforms/javascript/common/feature-flags/index.mdx, docs/platforms/python/feature-flags/index.mdx, docs/platforms/python/integrations/openfeature/index.mdx
Makes some quality improvements to our Openfeature eval tracking and Generic change tracking pages. The secret length restrictions were added in https://github.com/getsentry/sentry/pull/94721
=> ref(flags): add list of openfeature providers and generic webhook secret length

docs/platforms/unity/troubleshooting/index.mdx
Users no longer need to mess around with Editor scripts and can make use of the programmatic configuration for those scenarios now as well.
=> fix(Unity): Update troubleshooting snippet

develop-docs/sdk/telemetry/logs.mdx
Quick note to make it clear that 64-bit unsigned integer should always be sent as a string
=> Clarify 64-bit unsigned integer behaviour in logs

docs/platforms/python/integrations/openfeature/index.mdx
Openfeature needs a provider to evaluate flags.
=> fix(flags): add missing provider line to openfeature python code example

docs/product/insights/overview/index.mdx, docs/product/releases/setup/index.mdx
```
This PR makes two documentation updates:
1.  Removes "With insights," from the first paragraph of the Insights overview page (`docs/product/insights/overview/index.mdx`) to eliminate redundancy with the page's H2 and description.
2.  Adds content to the "Agent Pipelines vs Direct LLM Calls" callout on the Agents dashboard page (`docs/product/insights/agents/dashboard.mdx`). This provides important context on the difference between AI pipelines and direct LLM calls, and includes a link to relevant manual instrumentation documentation.
- Please give the docs team up to 1 week to review your PR unless you've added an urgent due date …
```
=> Assorted copy & URL updates

docs/platforms/javascript/guides/nextjs/configuration/build/index.mdx, docs/platforms/javascript/guides/nextjs/manual-setup.mdx
documents https://github.com/getsentry/sentry-javascript/pull/16626
=> docs(js): Update nextjs docs on `tunnelRoute` option

src/docTree.ts
Currently, the python page for [shutdown and draining](https://docs.sentry.io/platforms/python/configuration/draining/) navigates to a different version of itself upon clicking "Next". I added a check to filter out versioned pages in filterVisibleSiblings.
Issue: https://github.com/getsentry/sentry-docs/issues/14272
Fixes GH-14272
=> fix(ui): Filter versioned files from navigation tree.

docs/platforms/javascript/guides/express/index.mdx, platform-includes/getting-started-node/javascript.mdx, platform-includes/getting-started-verify/javascript.express.mdx
Reviewed and updated the Express Quick Start guide.
=> docs(js): Review and  update Express Quick Start guide

docs/platforms/android/configuration/options.mdx, docs/platforms/android/troubleshooting/index.mdx, docs/platforms/javascript/common/troubleshooting/index.mdx
Added Android troubleshooting entry for ad blockers
Updated proxy option
Closes https://github.com/getsentry/sentry-android-gradle-plugin/issues/658
=> Add Android troubleshooting entry for ad blockers

docs/product/issues/issue-details/query-injection-issues/index.mdx
this pr adds a page for Query Injection Vulernability Issues.
=> chore(detectors): Add page for Query Injection Issues

platform-includes/enriching-events/add-attachment/native.mdx
Documentation for attaching bytes using the Native SDK, as introduced by the following PR:
- https://github.com/getsentry/sentry-native/pull/1275 …
=> feat(native): attach bytes

docs/organization/integrations/source-code-mgmt/azure-devops/index.mdx, docs/organization/integrations/source-code-mgmt/bitbucket/index.mdx, docs/organization/integrations/source-code-mgmt/github/index.mdx, docs/organization/integrations/source-code-mgmt/gitlab/index.mdx
It's always been a source of confusion since it would not make any mention of the automatic code mapping derivation (only available for GitHub).
There are also some automatic commit fixes.
=> chore(derived_code_mappings): Remove call out

develop-docs/application-architecture/dynamic-sampling/architecture.mdx
There is an implementation detail in dynamic sampling rules: a condition needs to be added, otherwise the ruleset is not considered valid. The documentation does not contain any reference to this, and it's frustrating to figure out the correct way of specifying a catch-all yourself, therefore I'm adding this here.
=> chore(dynamic-sampling): add hint about conditions in dynamic sampling rules

docs/platforms/javascript/common/configuration/integrations/event-loop-block.mdx
A bad rebase meant that this was not included with https://github.com/getsentry/sentry-docs/pull/14302
=> fix: Make sure event loop block integration is documented

docs/platforms/javascript/guides/cloudflare/frameworks/nuxt.mdx, docs/platforms/javascript/guides/cloudflare/frameworks/sveltekit.mdx
Remove the Cloudflare install as it's automatically installed.
Merged after this is released: https://github.com/getsentry/sentry-javascript/pull/16873
=> docs(cloudflare): Remove install for Nuxt/SvelteKit

docs/platforms/javascript/common/user-feedback/configuration/index.mdx
Also added a note for how to use `eventID` to link back to sentry.io
Related to https://github.com/getsentry/sentry-javascript/pull/16835
Related to https://github.com/getsentry/sentry-javascript/issues/16836
=> docs(feedback): Update docs for onSubmitSuccess to include eventID 

develop-docs/application-architecture/dynamic-sampling/fidelity-and-biases.mdx
While working on DS biases, I noticed a lot of quite complicated language in the documentation that makes it hard to understand the topic. This PR aims to clarify the language without removing important information.
=> chore(dynamic-sampling): clarify develop documentation about biases

docs/platforms/android/configuration/multi-process-apps.mdx
=> Make the behaviour of SentryAndroid.init clearer in multiprocess

develop-docs/application-architecture/feedback-architecture.mdx, docs/platforms/javascript/common/user-feedback/configuration/index.mdx
Followup from https://github.com/getsentry/sentry-docs/pull/14310#discussion_r2198457651
=> fix(feedback): Dont escape url template

docs/concepts/data-management/data-forwarding.mdx
These integrations are no longer visible and will be deleted.
=> add-derprecate-note

docs/platforms/dotnet/common/tracing/instrumentation/custom-instrumentation/caches-module.mdx
`SetExtra` was deprecated.
Relates to:
* https://github.com/getsentry/sentry-dotnet/pull/4336
=> fix(dotnet): caching example used deprecated API

docs/platforms/react-native/session-replay/index.mdx, docs/platforms/react-native/session-replay/privacy/index.mdx
Updates the RN Masking warning to inform users that RN Text and Images are masked correctly since http://github.com/getsentry/sentry-cocoa/releases/tag/8.52.0
Since http://github.com/getsentry/sentry-cocoa/releases/tag/8.52.0 has an warning due to symbolication issues, let's wait for http://github.com/getsentry/sentry-cocoa/releases/tag/8.52.1 before merging this.
*Make sure you've …
=> Update SR RN masking warning with the fixed SDK version

includes/python-use-older-sdk-for-legacy-support.mdx
We have an info note on some Python integration pages that suggests switching to an older SDK major if a framework/Python version is not supported on the current one. Currently it mentions specific SDK versions. Make it more generic so that it doesn't get out of date if we release a new major.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is …
=> ref: Make note about supported versions more generic

docs/platforms/apple/common/profiling/index.mdx
As noted here: https://github.com/getsentry/sentry-cocoa/issues/3637#issuecomment-2787837554
We have a limitation where we cannot control what happens to a launch profiler if the SDK is never started after a profiled app launch. …
=> profiling(cocoa): add note about stopping launch profiler

develop-docs/sdk/data-model/event-payloads/index.mdx
The list of accepted values for platform is very outdated. We should just remove it from over here. …
=> fix: remove outdated list of acceptable platforms

docs/platforms/python/enriching-events/scopes/index.mdx, platform-includes/enriching-events/scopes/configure-scope/python.mdx
The example for `new_scope` didn't actually use `new_scope`.
Direct link to preview: https://sentry-docs-git-ivana-pythonfix-new-scope-example.sentry.dev/platforms/python/enriching-events/scopes/#changing-the-scope …
=> fix(python): Fix `new_scope` example

docs/product/ai-in-sentry/sentry-prevent-ai/index.mdx
Sentry Prevent AI just updated their permissions, and docs need to reflect the same. The Gen AI toggle, plus a Prevent toggle are now a part of the on/off flow for prevent AI. 
=> Updating Prevent AI docs to add latest permissions UX

docs/platforms/javascript/guides/nuxt/features/vue-router.mdx
Removing the Log-in notice from the router page as it is not needed here and is misleading. I also rewrote the text a bit to include an example.
=> docs(nuxt): Remove Log-in notice from router page

platform-includes/performance/opentelemetry-setup/without-java-agent/java.mdx
`-Dotel.java.global-autoconfigure.enabled=true` alone leads to lazy init of the OpenTelemetry SDK.
If Sentry API is used before any OpenTelemetry API then calls like `Sentry.captureMessage` etc. don't work.
We'd have to ensure eager init of the OpenTelemetry SDK in order to have Sentry initialized early like this:
```
import io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdk;
class Main {
static {
AutoConfiguredOpenTelemetrySdk.initialize();
}
}
```
Due to this requiring the `java` arg AND code, it's easier to just rely on the second method in docs that only need code changes.
Help us prioritize incoming PRs by letting us know when the change needs to go …
=> Remove setup variant for Java OpenTelemetry agentless setup

docs/platforms/python/integrations/rq/index__v3.x.mdx
Document what span attributes will be attached to transactions by default by our builtin integrations. This PR updates RQ. Rest will follow.
I created a new 3.x page for this since it's new behavior in 3.0.
Direct link to preview: https://sentry-docs-git-ivana-pythondefault-attrs-rq.sentry.dev/platforms/python/integrations/rq__v3.x#default-span-attributes
Look, I get it. The entity doing business as "Sentry" was incorporated in the …
=> feat(python): Document default span attrs in RQ, update for 3.0

docs/platforms/android/configuration/using-ndk.mdx
Extends NDK troubleshooting docs for debug images and how to invalidate the cache.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact …
=> docs(android): Extend NDK troubleshooting docs for debug images

docs/platforms/javascript/common/logs/index.mdx, docs/platforms/javascript/guides/capacitor/index.mdx, docs/product/explore/logs/getting-started/index.mdx, platform-includes/logs/requirements/javascript.capacitor.mdx
On version 2.0.0, we  introduced logging support for Capacitor
This PR adds all the changes and how to use logging on React Native.
=> feat(capacitor) logs documentaiton

docs/platforms/javascript/common/best-practices/web-workers.mdx, docs/platforms/javascript/common/configuration/integrations/webworker.mdx, platform-includes/configuration/integrations/javascript.mdx
closes https://github.com/getsentry/sentry-javascript/issues/16977
closes https://github.com/getsentry/sentry-javascript/issues/16974
This PR adds documentation for two new `WebWorker`-related APIs:
- `Sentry.webWorkerIntegration()`
- `Sentry.registerWebWorker()`
More details in https://github.com/getsentry/sentry-javascript/pull/16981
I also gave the entire web worker guide a facelift, removed some unnecessary `notSupported` platforms and added an integration page for the new integration. Also, the guide now includes a paragraph about configuring Vite correctly for worker builds which was raised in https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/755.
- Teamwork makes the dream work, …
=> feat(js): Update web worker guide with new `webWorkerIntegration` APIs

docs/platforms/javascript/guides/nextjs/index.mdx, docs/platforms/javascript/guides/nextjs/manual-setup.mdx
Session replay code was showing up in the code blocks whether or not `session replay` was selected as a feature to install. 
=> Fixing session replay responsiveness in code blocks

platform-includes/logs/options/javascript.mdx, platform-includes/logs/setup/javascript.cloudflare.mdx, platform-includes/logs/setup/javascript.mdx
Documents https://github.com/getsentry/sentry-javascript/pull/17092 …
=> feat(js): switch option to use non-experimental option for logs

docs/product/uptime-monitoring/automatic-detection.mdx
This PR updates the uptime monitoring documentation to:
- Remove the unsupported robots.txt option for disabling automatic detection
- Emphasize that deleted uptime alerts won't be re-created automatically
- Simplify the disabling section for better clarity
The robots.txt feature is not currently supported, so the best way to disable automatic detection is to simply delete the uptime alert.
=> docs: Update uptime monitoring automatic detection disable instructions

docs/platforms/javascript/common/configuration/integrations/event-loop-block.mdx, docs/platforms/javascript/guides/electron/configuration/event-loop-block.mdx
The `eventLoopBlockIntegration` has now been exported from the Electron SDK.
This PR updates the docs to correctly document this feature for Electron.
=> feat(electron): Document `eventLoopBlockIntegration`

docs/platforms/javascript/guides/cloudflare/features/workflows.mdx
In this PR we removed the UUID limitations around `instanceId`s in Cloudflare workflows.
- https://github.com/getsentry/sentry-javascript/pull/17121
This PR updates the docs to reflect this change!
=> fix(cloudflare): Allow non-uuid instance IDs in workflows

develop-docs/self-hosted/index.mdx
Previously, it was stated that RHEL-based distro is a no-go for installing self-hosted Sentry. But somebody did it with Amazon Linux 2023 (which is a Fedora derivative, very similar to RHEL). interestingly with SELinux enabled, and... you can just read the screenshot below. I'm adding that to the docs since that is so useful.
=> docs(self-hosted): update Linux compatibility with Amazon Linux 2023

docs/concepts/otlp/index.mdx, src/components/codeContext.tsx
Sentry is working on OTLP ingestion! This'll allow customers to configure their OpenTelemetry SDKs to send traces directly to Sentry. This is a major departure from our current OTLP support, which mostly requires users to configure their SDKs in special ways.
We are gearing up for a Limited Availability Beta with a few select customers. While we expect to hold their hand for a lot of it, it's still a good idea to have some public documentation they can refer to.
I'm looking for feedback from the Docs team on where to best place this kind of generic documentation (I took a shot!) and from the SDKs team for how to make this document play nice with existing SDK documentation about OpenTelemetry.
=> feat(otlp): Add basic OTLP beta documentation

develop-docs/sdk/telemetry/replays.mdx
Documents some of the behavior for session vs buffer modes. It may not be complete, but it's a good starting point. Feel free to suggest what else could be added here.
=> feat(develop): Introduce SDK behaviour section for replays

docs/platforms/python/tracing/span-metrics/index__v3.x.mdx
Adding a 3.x version of the Span Metrics page. The contents are identical except for changing 2.x-style `set_data()` to 3.x-style `set_attribute()`.
Since the 3.x page is a brand new file, it shows up all green on the diff. This is the actual difference between the old page and the new `index__v3.x.mdx` page:
```diff
--- index.mdx   2025-07-21 14:06:41
+++ index__v3.x.mdx     2025-07-28 09:44:24
@@ -23,11 +23,11 @@
span = sentry_sdk.get_current_span()
if span:
-    span.set_data("database.rows_affected", 42)
-    span.set_data("cache.hit_rate", 0.85)
-    span.set_data("memory.heap_used", 1024000)
-    span.set_data("queue.length", 15)
-    span.set_data("processing.duration_ms", 127)
+    span.set_attribute("database.rows_affected", 42)
+    span.set_attribute("cache.hit_rate", 0.85)
+ …
```
=> feat(python): Add 3.x version of span metrics page

docs/platforms/javascript/common/configuration/options.mdx, platform-includes/distributed-tracing/how-to-use/javascript.nextjs.mdx, platform-includes/distributed-tracing/how-to-use/javascript.node.mdx, platform-includes/distributed-tracing/how-to-use/javascript.nuxt.mdx, platform-includes/distributed-tracing/how-to-use/javascript.remix.mdx, platform-includes/distributed-tracing/how-to-use/javascript.solidstart.mdx, platform-includes/distributed-tracing/how-to-use/javascript.sveltekit.mdx
Docs for `strictTraceContinuation` and `orgId` ([related PR](https://github.com/getsentry/sentry-javascript/pull/16313)). 
I'm not 100% sure where I should put the `orgId` as it does not 100% fit into the "Tracing Options" section but it's currently only used for tracing.
closes https://github.com/getsentry/sentry-javascript/issues/16308
=> docs(js): Add docs for `strictTraceContinuation` and `orgId`

docs/platforms/kotlin/guides/compose-multiplatform/index.mdx
`# Compose Multiplatform` is unnecessary since the page already displays a header by default
=> fix(compose-multiplatform): remove unnecessary header

docs/platforms/android/user-feedback/index.mdx
We introduced a new static API to show the user feedback form in Android, to simplify usage. …
=> Update Android User Feedback static API

docs/concepts/otlp/index.mdx, includes/feature-available-alpha-otlp.mdx
- **Add enrollment information** so people know who to contact to try OTLP
- **Remove platform link**, since it was broken for almost everyone: it's platform content that only exists in JavaScript, so linking there from a general concepts document didn't work well
=> fix(otlp): OTLP docs small improvements

docs/platforms/react-native/session-replay/performance-overhead.mdx
Adds `replaysSessionQuality` option in React Native session replay options
⚠️ Please merge after https://github.com/getsentry/sentry-react-native/pull/5001 is released …
=> RN: Adds replaysSessionQuality option

docs/platforms/javascript/guides/tanstackstart-react/index.mdx
The docs reference @sentry/tanstackstart-router which does not exist. The function is exported by @sentry/tanstackstart-react though …
=> Fix reference to non-existent tanstackstart-router

docs/platforms/unreal/install/index.mdx
This PR updates Unreal SDK installation methods page after the support of two separate package versions for GitHub and FAB was removed in https://github.com/getsentry/sentry-unreal/pull/1030.
Related to https://github.com/getsentry/team-gdx/issues/13
=> Update Unreal Engine SDK installation methods page

develop-docs/sdk/data-model/envelope-items.mdx
=> feat: Clarify log envelope container

docs/concepts/key-terms/environments/index.mdx
Currently, some platforms include this information in their docs while others don't, making it difficult to provide a platform specific link in our app. Given that we already have a dedicated document covering environments and that this document can be used by any platform, we can just add a section describing the naming requirements. 
**Preview**
Contributes to https://linear.app/getsentry/issue/TET-975/link-releaseandenv-processing-errors-to-docs
=> feat: Add naming requirements to the environment doc

docs/platforms/python/configuration/options.mdx
We raised the default in https://github.com/getsentry/sentry-python/releases/tag/2.34.0, updating here.
**Direct link to preview:** https://sentry-docs-git-ivana-pythonupdate-max-value-length.sentry.dev/platforms/python/configuration/options/#max_value_length
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in …
=> fix(python): Update default of `max_value_length`

docs/platforms/python/migration/2.x-to-3.x.mdx
We're [adding new API](https://github.com/getsentry/sentry-python/pull/4642) in 3.x, documenting it in the migration guide.
**Direct link to preview:** https://sentry-docs-git-ivana-pythonnew-trace.sentry.dev/platforms/python/migration/2.x-to-3.x#tracing
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order …
=> Add `new_trace` to Python migration guide

docs/platforms/javascript/common/migration/v9-to-v10.mdx
> [!IMPORTANT] 
> This is opened as a draft PR to ensure it's only merged after we release v10. Reviews can already happen.
=> feat(js): Add v10 migration guide

platform-includes/capture-message/native.mdx, platform-includes/enriching-events/set-context/native.mdx, platform-includes/performance/improving-data/native.mdx
Related to the changes in https://github.com/getsentry/sentry-native/pull/1326 , we update our docs where they explicitly mention the available `sentry_value_t` types.
=> fix(native): update `sentry_value_t` example with 64-bit integer types

develop-docs/sdk/data-model/event-payloads/contexts.mdx
Document the Response Context for events, including all fields, according to the implementation in [Relay](https://github.com/getsentry/relay/blob/1bdc463896fb6f1425fac10915fa49799ecc5d85/relay-event-schema/src/protocol/contexts/response.rs#L11). Note that we don't include `inferred_content_type` because that's always overridden by Relay anyways.
=> feat(develop): Update Response Context

platform-includes/set-fingerprint/basic/native.mdx
This came up in a Discord thread, and we didn't really have this documented anywhere.
For manual event captures, we already provide a simple `sentry_value_set_by_key(event, "fingerprint", fp);` example, but this does not help with fingerprinting crashes. Hence I added an example of using `sentry_set_fingerprint("myFingerPrint", NULL);` which sets the global fingerprint list to `["myFingerPrint"]`.
=> chore(native): add example of global fingerprint setting

docs/platforms/go/common/logs/index.mdx, includes/logs/go-ctx-usage-alert.mdx, platform-includes/getting-started-include-logs-config/go.mdx
Changing the docs to adhere with the logging API signature changes in Go.
=> feat(go): Modify docs to follow logger API changes

docs/platforms/react-native/manual-setup/expo.mdx
A relatively minor change: the current version of docs for Expo seems a bit outdated in a sense that it asks you to make a change to the project that doesn't match the actual project that's being generated by Expo.
This PR fixes that and makes it a bit easier for newcomers to understand what changes need to be made.
=> docs(react-native): Update the docs in accordance to how the current structure of an Expo project looks like

platform-includes/profiling/automatic-instrumentation-setup/_default.mdx, platform-includes/profiling/automatic-instrumentation-setup/javascript.angular.mdx, platform-includes/profiling/automatic-instrumentation-setup/javascript.astro.mdx, platform-includes/profiling/automatic-instrumentation-setup/javascript.electron.mdx, platform-includes/profiling/automatic-instrumentation-setup/javascript.nextjs.mdx, platform-includes/profiling/automatic-instrumentation-setup/javascript.nuxt.mdx, platform-includes/profiling/automatic-instrumentation-setup/javascript.react.mdx, platform-includes/profiling/automatic-instrumentation-setup/javascript.remix.mdx, platform-includes/profiling/automatic-instrumentation-setup/javascript.svelte.mdx, platform-includes/profiling/automatic-instrumentation-setup/javascript.sveltekit.mdx, platform-includes/profiling/automatic-instrumentation-setup/javascript.vue.mdx
Removes all occurrences of `profilesSampler` in the JS browser SDKs as this API is not available and also deprecated, so we won't implement it.
- https://github.com/getsentry/sentry-javascript/issues/16773#issuecomment-3143858577
- https://github.com/getsentry/sentry-javascript/issues/17279
=> docs(browser): Delete deprecated `profilesSampler`

docs/platforms/python/migration/2.x-to-3.x.mdx
We'll be changing this in 3.0, adding to migration guide.
**Direct link to preview:** https://sentry-docs-git-ivana-pythonlogs-options-migration-guide.sentry.dev/platforms/python/migration/2.x-to-3.x#configuration …
=> feat(python): Add `enable_logs`, `before_send_log` to 3.x migration guide

docs/platforms/javascript/common/troubleshooting/index.mdx
ref https://github.com/getsentry/sentry-javascript/issues/16093
=> docs(js): Add troubleshooting for client instrumentation hook warning

platform-includes/logs/usage/php.laravel.mdx
ref https://github.com/getsentry/sentry/pull/97217
=> Switch from `sentry` -> `sentry_logs` for laravel logs channel

app/[[...path]]/page.tsx, docs/platforms/apple/common/user-feedback/configuration/index.mdx, src/types/frontmatter.ts
This is one option for fixing the table formatting issue in https://github.com/getsentry/sentry-docs/pull/14227
=> allow specifying docs pages as full width if their content requires it

src/components/onboarding/index.tsx
1. Errors
2. Logs
3. Replays
4. Tracing
5. Profiling
related https://github.com/getsentry/sentry/pull/96544
=> feat: re-organize onboarding options

docs/platforms/javascript/common/configuration/integrations/openai.mdx, platform-includes/configuration/integrations/javascript.astro.mdx, platform-includes/configuration/integrations/javascript.aws-lambda.mdx, platform-includes/configuration/integrations/javascript.bun.mdx, platform-includes/configuration/integrations/javascript.connect.mdx, platform-includes/configuration/integrations/javascript.fastify.mdx, platform-includes/configuration/integrations/javascript.gcp-functions.mdx, platform-includes/configuration/integrations/javascript.hapi.mdx, platform-includes/configuration/integrations/javascript.nestjs.mdx, platform-includes/configuration/integrations/javascript.nextjs.mdx, platform-includes/configuration/integrations/javascript.node.mdx, platform-includes/configuration/integrations/javascript.nuxt.mdx, platform-includes/configuration/integrations/javascript.remix.mdx, platform-includes/configuration/integrations/javascript.solidstart.mdx, platform-includes/configuration/integrations/javascript.sveltekit.mdx
Documents OpenA integration added with https://github.com/getsentry/sentry-javascript/pull/17022 …
=> feat: Document OpenAI integration

docs/concepts/data-management/event-grouping/index.mdx
The "Update Grouping" option does not exist anymore, as the latest grouping algorithm is automatically applied. I have edited the docs to reflect this information.
=> Modified grouping behavior clarification

docs/concepts/data-management/filtering/index.mdx
=> Adding docs for Log Inbound filters

docs/organization/data-storage-location/index.mdx
Correcting references to metadata storage location to reflect that source map and symbol data is stored regionally.
=> correcting region storage for symbol and source map metadata

docs/platforms/godot/configuration/options.mdx
Add documentation for `disabled_in_editor_play` option added in:
- getsentry/sentry-godot/pull/262 
Remove option according to changes:
- getsentry/sentry-godot/pull/277 …
=> Godot: Document `disabled-in-editor-play` option

src/components/docImage.tsx, src/components/docImage/docImage.spec.tsx, src/components/docImage/index.tsx, src/components/imageLightbox/imageLightbox.spec.tsx, src/components/imageLightbox/index.tsx, src/components/lightbox/lightbox.spec.tsx
Adding full component testing after finding a malformed image URL in prod.  …
=> Fix image path issue & add test coverage for new lightbox

docs/product/partnership-platform/account-provisioning-api.mdx, docs/product/partnership-platform/index.mdx, docs/product/partnership-platform/oauth-integration.mdx
Draft of converting 2 internal docs into public facing partnership enablement pages
- account provisioning
- oauth
New section under "product walkthroughs" which "walkthrough" is maybe a stretch, but this is a start and we can put it where we agree makes the most sense, and be discoverable.
[preview](https://sentry-docs-git-featpartnersadd-enablement-docs.sentry.dev/product/partnership-platform)
=> feat(partners)add-enablement-docs

docs/platforms/javascript/common/migration/v9-to-v10.mdx
Mentions a fix to be introduced in [10.4.0](https://github.com/getsentry/sentry-javascript/pull/17364) in the migration guide given it has quite a lot of impact, albeit belated (should have been like this since v9). 
This change is now mentioned in:
- 10.4.0 changelog
- in-repo migration guide
- in-docs migration guide (this PR)
=> fix(js/browser): Amend user IP + `sendDefaultPii` change to v10 migration guide

docs/platforms/javascript/common/configuration/options.mdx
Adds documentation for the new `ignoreSpans` option to be released with SDK version 10.2.0.
SDK PR: https://github.com/getsentry/sentry-javascript/issues/16820
Develop Docs spec change: https://github.com/getsentry/sentry-docs/pull/14571
closes #14569  …
=> feat(js): Add `ignoreSpans` documentation to Options page

docs/platforms/unreal/tracing/instrumentation/custom-instrumentation.mdx, platform-includes/performance/improving-data/unreal.mdx
Preview: https://sentry-docs-git-unreal-attach-data.sentry.dev/platforms/unreal/tracing/instrumentation/custom-instrumentation/
* Add transaction and span set_data documentation
* Relates to https://github.com/getsentry/projects/issues/524
=> [Unreal] Add transaction and span set_data documentation

includes/logs/javascript-console-logging-integration.mdx, platform-includes/llm-rules-logs/javascript.nextjs.mdx, platform-includes/llm-rules-logs/javascript.node.mdx, platform-includes/logs/requirements/javascript.mdx
In `9.41.0` of the JS SDK, we dropped the experimental `enableLogs` option. Given we document snippets without the experimental option everywhere, let's bump the min version in the docs: https://github.com/getsentry/sentry-javascript/blob/develop/CHANGELOG.md#9410
This is the version we will lock in for GA.
While I was here, I also cleaned up the `consoleLoggingIntegration` so that we follow the order log < warn < error.
=> feat: Update min js sdk version for logging and update console logging snippet

docs/platforms/unreal/enriching-events/breadcrumbs/index.mdx, docs/platforms/unreal/enriching-events/context/index.mdx, docs/platforms/unreal/enriching-events/scopes/index.mdx, platform-includes/enriching-events/attach-screenshots/unreal.mdx, platform-includes/enriching-events/breadcrumbs/breadcrumbs-example/unreal.mdx, platform-includes/enriching-events/set-context/unreal.mdx
Key Changes:
- Updated some C++ examples to use `FSentryVariant` type instead of string (https://github.com/getsentry/sentry-unreal/pull/971)
- Added notice about using local scopes on Windows/Linux (https://github.com/getsentry/sentry-unreal/pull/928)
- Fixed supported platforms for screenshot feature
=> Unreal Engine: Update plugin docs

develop-docs/sdk/data-model/envelopes.mdx
Source: https://github.com/getsentry/relay/blob/795827327a79e2fb164037c58d16678267979e8e/relay-config/src/config.rs#L713
LOGS-280
=> ref(ourlogs): Add log size limit

docs/platforms/android/configuration/options.mdx, docs/platforms/java/common/configuration/options.mdx, docs/platforms/java/guides/spring-boot/advanced-usage.mdx
… Boot
Documents https://github.com/getsentry/sentry-java/pull/4612 …
=> Add documentation for onDiscard callback in Java, Android, and Spring Boot

docs/platforms/javascript/guides/cloudflare/frameworks/hydrogen-react-router.mdx, docs/platforms/javascript/guides/cloudflare/frameworks/hydrogen-remix.mdx
Documents: https://github.com/getsentry/sentry-javascript/pull/17145
=> docs(js): Add docs for Hydrogen with RR7

docs/product/insights/ai/mcp/getting-started.mdx
Final touches to our MCP Server instrumentation docs before the launch tomorrow (Thursday, August 14).
- put an alert to let users know the minimum version requirement to use our MCP Server instrumentation (inspo from [here](https://docs.sentry.io/platforms/javascript/guides/express/sourcemaps/uploading/esbuild/)).
- change wording a bit to talk about MCP Observability rather than MCP Monitoring.
=> docs(mcp): Update getting started guide to include SDK version requirement and terminology change

docs/platforms/javascript/common/configuration/integrations/http.mdx
documents https://github.com/getsentry/sentry-javascript/pull/17370
=> docs(js): Add docs for `ignoreStaticAssets`

docs/platforms/dotnet/common/logs/index.mdx, docs/platforms/dotnet/guides/extensions-logging/index.mdx, docs/product/explore/logs/getting-started/index.mdx, platform-includes/logs/integrations/dotnet.mdx, platform-includes/logs/options/dotnet.mdx, platform-includes/logs/requirements/dotnet.mdx, platform-includes/logs/setup/dotnet.mdx, platform-includes/logs/usage/dotnet.mdx
Add documentation for [Sentry Structed Logs](https://docs.sentry.io/product/explore/logs/getting-started/) for `dotnet`.
=> docs(dotnet/logs): add Logs for the .NET SDK

docs/platforms/javascript/guides/remix/frameworks/index.mdx, redirects.js
Closes https://github.com/getsentry/sentry-docs/issues/14607
Fixes redirect from https://github.com/getsentry/sentry-docs/pull/14645 to React Router docs
Fixes https://docs.sentry.io/platforms/javascript/guides/remix/frameworks/ hydrogen on cf link …
=> fix Hydrogen on CF docs link redirects

src/components/sdkOption.tsx
SDK option tables were missing their bottom borders because the PlatformSection inside of them was rendering a div, semantically we shouldn't have divs inside our tables. I added a function and some logic to manually check the platform instead.
See a platform options page such as: https://sentry-docs-git-table-borders.sentry.dev/platforms/python/configuration/options/ and compare to what we have in prod: https://docs.sentry.io/platforms/python/configuration/options/
*Make sure you've checked the …
=> Update sdkOption to avoid rendering divs inside of tables

docs/platforms/android/logs/index.mdx, docs/platforms/dart/common/logs/index.mdx, docs/platforms/dart/guides/flutter/logs/index.mdx, docs/platforms/go/common/logs/index.mdx, docs/platforms/java/common/logs/index.mdx, docs/platforms/javascript/common/logs/index.mdx, docs/platforms/php/common/logs/index.mdx, docs/platforms/php/guides/laravel/logs/index.mdx, docs/platforms/python/logs/index.mdx, docs/platforms/react-native/logs/index.mdx, docs/platforms/ruby/logs/index.mdx, docs/platforms/rust/common/logs/index.mdx, docs/product/explore/logs/index.mdx
In #14583, @coolguyzone noticed a missing hyphen: see https://github.com/getsentry/sentry-docs/pull/14583#discussion_r2271395947.
This PR is applying the fix for the other platforms as well.
=> docs(logs): fix hyphenation

docs/platforms/javascript/common/best-practices/web-workers.mdx, docs/platforms/javascript/common/configuration/integrations/webworker.mdx
I incorrectly referred to `Sentry.registerWebWorker` by `Sentry.registerWorker` when reworking our web worker docs in #14395. 
Closes https://github.com/getsentry/sentry-javascript/issues/17443 …
=> fix(js): Fix references of `registerWorker` to `registerWebWorker`

docs/security-legal-pii/security/ssl.mdx
Remove the announcement for change of root as we have since returned to Digicert, which was our previous state anyway.
=> Remove SSL root change announcement

src/components/breadcrumbs/index.tsx, src/components/copyMarkdownButton.tsx, src/components/docPage/index.tsx
=> fix: Fix breadcrumb + markdown button allignment

docs/platforms/javascript/guides/nuxt/index.mdx, docs/platforms/javascript/guides/nuxt/install/cli-import.mdx, docs/platforms/javascript/guides/nuxt/install/index.mdx, docs/platforms/javascript/guides/nuxt/manual-setup.mdx
Nuxt is now out of Beta: https://github.com/getsentry/sentry-javascript/pull/17400
=> docs(nuxt): Remove beta, add dev mode command, add cloudflare link

docs/platforms/apple/common/index.mdx, docs/platforms/apple/common/logs/index.mdx, platform-includes/logs/options/apple.mdx, platform-includes/logs/requirements/apple.mdx, platform-includes/logs/setup/apple.mdx, platform-includes/logs/usage/apple.mdx
Add docs for experimental structured logs for Apple platforms.
Closes https://github.com/getsentry/sentry-cocoa/issues/5986
- [Structured Logs: Docs](https://github.com/getsentry/sentry-cocoa/issues/5986)
=> docs(apple): Add docs for structured logs

platform-includes/sourcemaps/overview/javascript.nextjs.mdx
- Fix enabled/disabled typo
- Make clear that default: true is the default
- Make clearer that source maps options are optional for set-up
- 
=> fixing some errors from nextjs-source-map-updates branch

docs/platforms/unity/troubleshooting/index.mdx
With the Unity SDK version `4.0.0 and newer` there is a proper workaround to this problem.
=> feat(Unity ): Added `APK+OBB` initialization to troubleshooting

docs/platforms/unity/troubleshooting/known-limitations.mdx
Dropping this screenshot here for proof:
=> chore: Updated known limitation in Unity with Cysharp

docs/platforms/javascript/guides/nextjs/index.mdx
Just realized we're missing the router instrumentation here, also the browserTracingIntegration is added by default.
=> docs(js): Fix Next.js client tracing config

docs/platforms/unity/troubleshooting/known-limitations.mdx
Added Mono specific section to the Known Limitations.
=> chore(Unity): Added Mono & Line Numbers to Known Limitations

docs/platforms/javascript/guides/aws-lambda/install/layer.mdx, docs/platforms/javascript/guides/aws-lambda/install/npm.mdx
Updates the docs to reflect that manual wrapping is not needed anymore for both CJS and ESM.
=> docs(aws): Remove manual setup steps for ESM

docs/pricing/quotas/index.mdx, docs/pricing/quotas/manage-logs-quota.mdx
=> First pass at logs quota doc

docs/pricing/index.mdx, docs/pricing/legacy-pricing.mdx
DO NOT MERGE BEFORE LOGS GA.
See changes on:
https://sentry-docs-git-logs-ga-billing.sentry.dev/pricing/
https://sentry-docs-git-logs-ga-billing.sentry.dev/pricing/legacy-pricing/ …
=> Update AM3 and legacy billing for logs GA, DO NOT MERGE BEFORE LOGS GA

platform-includes/performance/add-spans-example/java.mdx, platform-includes/performance/create-transaction-bound-to-scope/java.mdx
There's no `it`, should be `span`. …
=> Fix reference to span in processOrderBatch function

docs/platforms/unreal/configuration/options.mdx
Related to https://github.com/getsentry/sentry-unreal/pull/1054
=> Unreal Engine: Update info about reading certain options from env vars

docs/organization/integrations/cloud-monitoring/aws-lambda/index.mdx
The AWS integration supports both ESM and CJS now
=> docs(aws-integration): Remove alert that ESM is not supported

docs/platforms/python/index.mdx
`init()`-ing in an async function is not always possible (e.g. in an async web framework like FastAPI) and also not always necessary.
**Direct link to preview:** https://sentry-docs-git-ivana-pythonasync-init.sentry.dev/platforms/python/ …
=> ref(python): Update wording regarding async init

src/components/versionSelector/index.tsx
This PR makes a change to the order in which we show the version select items if a docs page has multiple versions: Instead of sorting the version designator alphabetically, this PR attempts to sort them by recent to oldest. For now, this only looks at the major number, since the version designator can be arbitrary and we can't assume proper semver (see example).If we can't extract a proper major version, we continue to sort alphabetically.
Before:
After:
(the 10x version in this screenshot serves an illustrative purpose. I'm not shipping that anytime soon :D)
(This PR is brought to you by a sidequest while working on updating sveltekit docs and encountering weird ordering. Happy to close/adjust as reviewers see fit :) )
Help us prioritize incoming PRs by letting us know when the change …
=> fix: Order versioned docs select items by recency

docs/platforms/playstation/index.mdx, docs/platforms/unity/game-consoles/index.mdx, docs/platforms/unreal/game-consoles/index.mdx, docs/platforms/xbox/index.mdx
We need to update the docs for Unreal, Unity, PlayStation, Xbox, and Nintendo Switch to include details about the pricing for console access.  …
=> Updating Console Access Pricing In Docs

docs/platforms/javascript/common/configuration/integrations/vercelai.mdx, docs/platforms/javascript/common/tracing/instrumentation/ai-agents-module.mdx, docs/product/insights/ai/agents/getting-started.mdx, src/components/docPage/type.scss
- Fix /configuration/integrations/vercelai/ 404 and set supported sdks
- Simplify AI Agents manual instrumentation: example-first; specs in Expandables; added OpenAI link.
- Update compatibility with Vercel AI SDK v5 (ai >=3 <6). …
=> docs(js):  Fix Vercel AI integration 404 and simplify AI Agents docs

docs/platforms/python/configuration/options.mdx, docs/platforms/python/index.mdx, docs/platforms/python/integrations/logging/index.mdx, docs/platforms/python/integrations/loguru/index.mdx, platform-includes/getting-started-config/python.mdx, platform-includes/logs/integrations/python.mdx, platform-includes/logs/options/python.mdx, platform-includes/logs/setup/python.mdx
We'll be promoting the `enable_logs` and `before_send_log` options to regular SDK options. (We'll still keep the experimental counterparts until 3.0.)
Preparing this; merging will need to wait until the change has been released. …
=> feat(python): Replace experimental logs options with regular ones

develop-docs/sdk/telemetry/traces/modules/ai-agents.mdx
Add more details to `gen_ai.request.messages` span description.
- Relates to https://github.com/getsentry/sentry-conventions/pull/122
=> feat(gen_ai): Add details to request messages description

docs/platforms/php/common/logs/index.mdx, docs/platforms/php/guides/symfony/configuration/symfony-options.mdx, docs/product/explore/logs/getting-started/index.mdx, platform-includes/logs/default-attributes/php.symfony.mdx, platform-includes/logs/options/php.symfony.mdx, platform-includes/logs/requirements/php.symfony.mdx, platform-includes/logs/setup/php.symfony.mdx, platform-includes/logs/usage/php.symfony.mdx
=> feat(logs): add documentation for symfony logging

docs/platforms/javascript/common/configuration/options.mdx, docs/platforms/javascript/common/tracing/distributed-tracing/dealing-with-cors-issues/index.mdx
To be merged after https://github.com/getsentry/sentry-javascript/pull/17509 was released
This PR adds documentation for the new, browser-SDK-only, `propagateTraceparent` option (see [develop docs](https://develop.sentry.dev/sdk/telemetry/traces/#propagatetraceparent)). It also adjusts our "Dealing with CORS Issues" page to include `traceparent` in the `CORS` configuration if users opted into the option.
Look, I get it. The entity …
=> feat(js): Add `propagateTraceparent` option documentation

docs/product/ai-in-sentry/index.mdx
=> fix(docs): fix typo on AI in Sentry page

develop-docs/backend/application-domains/tasks/running-workers.mdx, develop-docs/self-hosted/tasks.mdx
We should give guidance on how to operate taskbroker/workers in self-hosted environments as there will be installs that need more than a single broker/worker
Refs STREAM-439
=> feat: Add taskworker self-hosted docs

develop-docs/backend/application-domains/asynchronous-workers.mdx, develop-docs/backend/application-domains/tasks/index.mdx, develop-docs/backend/application-domains/tasks/running-workers.mdx, develop-docs/backend/application-domains/tasks/task-lifecycle.mdx, develop-docs/backend/application-domains/tasks/terminology-and-concepts.mdx, develop-docs/development-infrastructure/devservices.mdx, develop-docs/self-hosted/tasks.mdx
Add the taskworker usage guide content from notion to our public documentation.
Refs STREAM-439
=> feat: Add taskworker usage guide content

docs/platforms/javascript/guides/sveltekit/sourcemaps/index.mdx, platform-includes/sourcemaps/overview/javascript.mdx, platform-includes/sourcemaps/overview/javascript.nuxt.mdx, platform-includes/sourcemaps/overview/javascript.solidstart.mdx, platform-includes/sourcemaps/overview/javascript.sveltekit.mdx, platform-includes/sourcemaps/overview/javascript.tanstackstart-react.mdx, platform-includes/sourcemaps/primer/javascript.cloudflare.mdx, platform-includes/sourcemaps/primer/javascript.mdx, platform-includes/sourcemaps/primer/javascript.nuxt.mdx, platform-includes/sourcemaps/primer/javascript.solidstart.mdx, platform-includes/sourcemaps/primer/javascript.tanstackstart-react.mdx
- nuxt - add wizard and update walkthrough
- browser JS - update walkthrough
- sveltekit - add the wizard as an option, update walkthrough
- solid start - add wizard and update walkthrough
- tanstack - add manual instructions and update walkthrough
- cloudflare - add wizard, show updated walkthrough
=> updating multiple JS frameworks to and more detailed source map info

develop-docs/frontend/using-rtl.mdx
Also adds docs about additionalWrapper
=> docs(sentry): Add dev docs for `renderHookWithProviders`

develop-docs/backend/application-domains/tasks/index.mdx, develop-docs/backend/application-domains/tasks/terminology-and-concepts.mdx
h1 headings are not included in the 'on this page' sidebar. Only h2 and lower are included in the page contents.
=> fix(tasks) Update headings to improve sidebar

docs/platforms/react-native/tracing/instrumentation/time-to-display.mdx
Time To Initial Display / Time To Full Display works with the new architecture after certain changes done in the past: https://github.com/getsentry/sentry-react-native/pull/5081
It still needs to be re-implemented as a turbo module, and that will be handled later but at least it can be used now.
=> Update time-to-display.mdx to remove the indication that TTID/TTFD doesn't work with the new architecture

develop-docs/sdk/expected-features/rate-limiting.mdx
Adds the missing category, as defined in Relay: https://github.com/getsentry/relay/blob/a00af6b85faff6c60e66bfdd54adb7c9f1d856c2/relay-base-schema/src/data_category.rs#L49
=> feat(develop): Add `monitor` category to rate limiting docs

docs/cli/crons.mdx, docs/platforms/javascript/common/crons/index.mdx, docs/platforms/python/crons/index.mdx, docs/platforms/python/integrations/celery/crons.mdx, includes/javascript-crons-upsert.mdx, platform-includes/crons/requirements/dotnet.mdx, platform-includes/crons/requirements/elixir.mdx, platform-includes/crons/requirements/go.mdx, platform-includes/crons/requirements/java.mdx, platform-includes/crons/requirements/javascript.aws-lambda.mdx, platform-includes/crons/requirements/javascript.azure-functions.mdx, platform-includes/crons/requirements/javascript.connect.mdx, platform-includes/crons/requirements/javascript.express.mdx, platform-includes/crons/requirements/javascript.gcp-functions.mdx, platform-includes/crons/requirements/javascript.koa.mdx, platform-includes/crons/requirements/javascript.mdx, platform-includes/crons/requirements/javascript.node.mdx, platform-includes/crons/requirements/php.mdx, platform-includes/crons/requirements/python.mdx, platform-includes/crons/requirements/ruby.mdx, platform-includes/crons/setup/elixir.mdx, platform-includes/crons/setup/go.mdx, platform-includes/crons/setup/java.mdx, platform-includes/crons/setup/php.mdx, platform-includes/crons/setup/ruby.mdx
Fixes https://github.com/getsentry/sentry-docs/issues/14959
=> fix(crons): Broken create links

docs/platforms/javascript/common/configuration/options.mdx
This PR 
- adds an `availableSince` property to the `ignoreSpans` filter option
- removes and repositions a `PlatformCategorySection` component which incorrectly excluded a couple of tracing options from server-side JS guides.
=> ref(js): Clarify min version of `ignoreSpans` and fix incorrect platformCategory excludes

docs/platforms/javascript/common/configuration/options.mdx
I noticed that we added some `<PlatformCategorySection>` wrapped sections to the options page. Instead of this, we should always use the `categorySupported` option on `SdkOption`, as this takes care of showing a info message in meta frameworks if an option is only available on client or server.
=> fix(js): Fix option platform checks

develop-docs/ingestion/relay/relay-best-practices.mdx
See for example https://github.com/getsentry/relay/pull/5144.
=> Document catchall variant for protocol enums

docs/product/sentry-mcp/index.mdx
Adds MCP setup guide for codex and warp
=> feat(MCP Docs) Codex + Warp docs

docs/platforms/unreal/configuration/options.mdx
This PR adds a notice to the Unreal plugin configuration documentation highlighting the importance of plugin loading order when configuring custom callback handlers.
=> Unreal Engine: Add notice about loading custom callback handler classes

docs/platforms/android/configuration/options.mdx, docs/platforms/android/tracing/trace-propagation/index.mdx, docs/platforms/java/common/configuration/options.mdx, docs/platforms/java/common/tracing/trace-propagation/index.mdx
Add docs for https://github.com/getsentry/sentry-java/pull/4671 …
=> docs(java): Add docs for propagateTraceparent option

docs/platforms/php/guides/symfony/configuration/symfony-options.mdx, docs/platforms/php/guides/symfony/integrations/index.mdx
=> Update options + symfony specific integrations doc

docs/platforms/javascript/common/apis.mdx, docs/platforms/javascript/common/tracing/instrumentation/automatic-instrumentation.mdx, src/components/sdkApi.tsx
This PR adds documentation for the new `reportPageLoaded()` API which is coupled to the new `enableReportPageLoaded` option in the `browserTracingIntegration`. Both have been added via https://github.com/getsentry/sentry-javascript/pull/17724 and released in [10.13.0](https://github.com/getsentry/sentry-javascript/releases/tag/10.13.0).
Also added a new `availableSince` prop to the `SdkApi` component.
closes https://linear.app/getsentry/issue/FE-607/docs-for-reportpageloaded
*Make sure you've checked …
=> feat(js): Add `reportPageLoaded()` documentation

docs/platforms/android/configuration/options.mdx
removed environment variables references in Android options, as they are not used
Resolves https://github.com/getsentry/sentry-java/issues/4169 …
=> Remove environment variables in Android options

docs/concepts/otlp/index.mdx, includes/feature-available-alpha-logs.mdx, includes/feature-available-alpha-otlp.mdx, includes/feature-available-alpha-tracing.mdx, includes/feature-stage-alpha-metrics.mdx, includes/feature-stage-beta-metrics.mdx, src/components/codeContext.tsx
resolves https://linear.app/getsentry/issue/LOGS-347/add-docs-for-otlp-logs-endpoint
=> feat(otlp): Add docs for OTLP logs endpoint

docs/platforms/javascript/common/apis.mdx, docs/platforms/javascript/common/tracing/instrumentation/index.mdx
Adds documentation for `Sentry. setActiveSpanInBrowser(span)` which is added via https://github.com/getsentry/sentry-javascript/pull/17714. To be merged only after the feature was released. This is still based on #15006 because I need the `availableSince` prop on the `SdkApi` component.
closes https://linear.app/getsentry/issue/FE-608/docs-for-setspanactive
Look, I get it. The entity doing business as "Sentry" was incorporated in …
=> feat(js): Add documentation for `setActiveSpanInBrowser(span: Span)`

docs/cli/releases.mdx, docs/platforms/android/configuration/releases.mdx, docs/platforms/apple/common/configuration/releases.mdx, docs/platforms/dart/common/configuration/releases.mdx, docs/platforms/dart/guides/flutter/configuration/releases.mdx, docs/platforms/dotnet/common/configuration/releases.mdx, docs/platforms/elixir/configuration/releases.mdx, docs/platforms/go/common/configuration/releases.mdx, docs/platforms/godot/configuration/releases.mdx, docs/platforms/java/common/configuration/releases.mdx, docs/platforms/javascript/common/configuration/releases.mdx, docs/platforms/kotlin/guides/kotlin-multiplatform/configuration/releases.mdx, docs/platforms/native/common/configuration/releases.mdx, docs/platforms/php/common/configuration/releases.mdx, docs/platforms/powershell/configuration/releases.mdx, docs/platforms/react-native/configuration/releases.mdx, docs/platforms/ruby/common/configuration/releases.mdx, docs/platforms/rust/common/configuration/releases.mdx, docs/platforms/unity/configuration/releases.mdx, docs/platforms/unreal/configuration/releases.mdx, docs/product/releases/naming-releases.mdx, includes/bind-release-version.mdx
I noticed we had a lot of duplicate pages with the same docs related to release names. 
The goal of this PR is to:
1. Move Release Name related content out of platform docs, and into a central place. It's not platform specific knowledge really
2. De-duplicate whatever is left over in the platform docs, so it's easier to maintain links to the central docs going forward.
The new central page is available at: `/product/releases/naming-releases/`
- this content was taken from other places and re-worked a little.
Some existing pages are now more streamlined and will link to the new central location:
- `/cli/releases/`
- `/platforms/javascript/configuration/releases/` (19 platform pages with the exact same content)
| New page | CLI Releases | Platform pages |
| --- | --- | --- |
| <img …
=> docs(releases): De-duplicate release naming docs, and centralize in /product/releases/naming-releases/

docs/product/test-analytics/index.mdx
Test Analytics UX has some updates that would be useful for people to know about. 
=> Adding v0 and dashboard refresh info to TA

docs/concepts/otlp/index.mdx, docs/organization/early-adopter-features/index.mdx, includes/feature-available-alpha-logs.mdx, includes/feature-available-ea-logs.mdx
ref https://linear.app/getsentry/issue/LOGS-361/move-otlp-logs-endpoint-to-ea
=> feat(otlp): Move otlp logs endpoint to EA

docs/product/issues/ownership-rules/index.mdx
We mention that we support GitLab syntax, even though we don't really support it, and there's substantial differences between GitHub and GitLab syntax. Explicitly mention that we support GitHub syntax, and don't support special GitLab things like sections. See https://github.com/getsentry/sentry/issues/86351 for an example
Resolves https://github.com/getsentry/sentry-docs/issues/9565
=> fix(codeowners): don't support GitLab syntax

develop-docs/sdk/telemetry/spans/span-protocol.mdx
Checked with @Dav1dde -- we should send type `'double'` for floating point numbers.
=> fix(span-first): Update attribute type from 'float' to 'double'

docs/product/test-analytics/sentry-prevent-cli/index.mdx
These docs are using an incorrect url
(Personally I would prefer if you update the project itself to be sentry-prevent-cli)
=> Fix prevent-cli url

docs/platforms/apple/common/tracing/instrumentation/automatic-instrumentation.mdx
Remove the section on before Cocoa SDK v 8.18.0, which we released in Jan 2024, to simplify the app start tracing docs.
=> fix(apple): Simplify app start tracing

docs/platforms/javascript/common/configuration/integrations/google-genai.mdx, docs/platforms/javascript/common/tracing/instrumentation/ai-agents-module.mdx, platform-includes/configuration/integrations/javascript.astro.mdx, platform-includes/configuration/integrations/javascript.aws-lambda.mdx, platform-includes/configuration/integrations/javascript.bun.mdx, platform-includes/configuration/integrations/javascript.connect.mdx, platform-includes/configuration/integrations/javascript.fastify.mdx, platform-includes/configuration/integrations/javascript.gcp-functions.mdx, platform-includes/configuration/integrations/javascript.hapi.mdx, platform-includes/configuration/integrations/javascript.nestjs.mdx, platform-includes/configuration/integrations/javascript.nextjs.mdx, platform-includes/configuration/integrations/javascript.node.mdx, platform-includes/configuration/integrations/javascript.nuxt.mdx, platform-includes/configuration/integrations/javascript.remix.mdx, platform-includes/configuration/integrations/javascript.solidstart.mdx, platform-includes/configuration/integrations/javascript.sveltekit.mdx
Documents Google Gen AI integration …
=> feat: Document Google Gen AI Integration

docs/platforms/python/integrations/index.mdx, package.json, src/components/platformIcon.tsx, yarn.lock
- Bump platformicons to 9.0.1
- Add the Langgraph SVGs and the langgraph platform
- Use the Langgraph platform in the Python integration docs
Closes TET-1225
=> feat(platform): Bump platformicons & add langgraph platform

docs/concepts/otlp/index.mdx, src/components/codeContext.tsx
1. re-organize sections in otlp docs
2. add example collector config for both traces and logs
3. add android and flutter sdks to traceparent section (as per https://linear.app/getsentry/project/implement-traceparent-support-in-client-sdks-d842ae07e7d4/updates)
4. removes backend js platforms from traceparent section
=> feat: Add example collector config to otlp docs + extra cleanup

docs/security-legal-pii/scrubbing/server-side-scrubbing/index.mdx
Sentence is a bit awkward, this should make it clearer what is actually ment.
=> fix(pii-scrubbing): Fix up sentence structure

docs/platforms/react-native/sourcemaps/uploading/codepush.mdx
Fixes https://github.com/getsentry/sentry-react-native/issues/5148
Updates Codepush instructions to use a separate dir for sourcemaps to avoid including them in releases
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna …
=> RN: Update Codepush instructions to use a separate dir for sourcemaps

docs/platforms/apple/common/tracing/instrumentation/automatic-instrumentation.mdx
Clearly point out that the prewarmed app start tracing drops two spans and remove the confusing part of not being able to reliably measuring app starts. …
=> fix(apple): Clarify prewarmed app starts

docs/platforms/javascript/common/configuration/integrations/openai.mdx, docs/platforms/javascript/common/configuration/integrations/vercelai.mdx, docs/platforms/javascript/common/tracing/instrumentation/ai-agents-module.mdx, src/components/platformLink.tsx
* Updates formatting of the alert - there was a typo, and with Deno SDK supported, expanding the version support
* `platformLink` gets similar treatment to `platformSection`. this fixes ai integration docs for js. ie: cf workers support vercelai but not openai. 
Platform link example:
https://sentry-docs-git-sergical-docs-deno-vercel-ai.sentry.dev/platforms/javascript/guides/deno/tracing/instrumentation/ai-agents-module/ vs https://docs.sentry.io/platforms/javascript/guides/deno/tracing/instrumentation/ai-agents-module/ - deno only supports vercelai, im sure there are other ones that should be updated as well
|--------|--------|
| <img width="2442" height="404" alt="CleanShot 2025-09-30 at 09 23 50@2x" src="https://github.com/user-attachments/assets/17a1d181-5005-4065-b9 …
=> fix(docs) fixes formatting, updates platformLink

develop-docs/services/chartcuterie.mdx
We use `pnpm` instead of `yarn` now so update the Chartcuterie docs to reflect that. I also fixed a typo.
=> fix(chartcuterie): Update yarn -> pnpm

docs/platforms/javascript/guides/nextjs/configuration/build/index.mdx
The link was moved by Next.js in https://github.com/vercel/next.js/pull/78842 …
=> fix(nextjs): update link to runAfterProductionCompile hook

develop-docs/self-hosted/experimental/reverse-proxy.mdx
Added the `0` symbol to the list of allowed characters for project IDs in the reverse proxy configuration. This restores proxy functionality for DSNs like:
```
https://public@sentry.example.com/10
https://public@sentry.example.com/100
https://public@sentry.example.com/101
etc.
``` …
=> fix: Allow '0' in project IDs for reverse proxy
