- src/docs/product/relay/options.mdx
Updates config options according to getsentry/relay#985.
> ref(relay): Update docs for buffering configs

- src/platforms/javascript/common/configuration/integrations/default.mdx
This PR fixes the incorrect formatting on [Default Integrations](https://docs.sentry.io/platforms/javascript/guides/react/configuration/integrations/default/) page for React SDK.
> Fixed incorrect formatting.

- src/docs/product/security/mobile-privacy.mdx
Users are required to inform if their app requires IDFA and often reach out asking about ti:
> Apple no use of IDFA

- src/platforms/android/common/proguard.mdx
Fixes https://github.com/getsentry/sentry-docs/issues/3488
> Add rule default info

- src/platforms/dotnet/migration.mdx
Relates to: https://github.com/getsentry/sentry-dotnet/issues/962
> [dotnet] Add migration about serialization

- src/docs/product/sentry-basics/guides/alert-notifications/index.mdx
- src/docs/product/sentry-basics/guides/alert-notifications/issue-alerts.mdx
- src/docs/product/sentry-basics/guides/alert-notifications/metric-alerts.mdx
Updates:
Alert Builder content
Alert Wizard content
> Alert Builder updates for GA and Alert Wizard fixes

- src/platforms/android/migration.mdx
- src/platforms/java/migration.mdx
> Java: Add migration docs for binding transaction to the scope.

- src/platforms/javascript/guides/nextjs/manual-setup.mdx
Be more explicit about what to do with the configuration of the app.
> Next.js app configuration

- package.json
- yarn.lock
> upgrade(xmlhttprequest-ssl): Force version to be above 1.6.2

- src/platforms/android/migration.mdx
> Migration: Android v5

- src/platforms/java/guides/spring/advanced-usage.mdx
> Document setting user filter on spring for transactions

- src/includes/set-fingerprint/rpc/apple.mdx
This sample was missing for Apple.
Fixes GH-3507
> feat(apple): Add RPC fingerprint sample

- src/css/_includes/grid.scss
Fixes https://github.com/getsentry/sentry-docs/issues/3254
https://user-images.githubusercontent.com/139499/117362191-f5597d00-ae88-11eb-9dc8-96839a4e01bf.mp4
> fix: Enable right side to scroll vertically

- src/includes/set-release/elixir.mdx
Fixes https://github.com/getsentry/sentry-docs/issues/3339
> feat: Add release option fox elixir

- src/wizard/javascript/nextjs.md
> Add Next.js to the Wizard

- src/includes/performance/add-spans-example/javascript.mdx
- For automatic spans configureScope must be called, calling that out
specifically so that users are more aware of this
- Also show how to get hub too
> ref(javascript): Update manual instrumentation docs

- src/platforms/flutter/migration.mdx
> Flutter Migration guide 5.1.0

- src/includes/set-fingerprint/basic/ruby.mdx
- src/includes/set-fingerprint/database-connection/ruby.mdx
- src/includes/set-fingerprint/rpc/ruby.mdx
> Add fingerprint examples for sentry-ruby

- src/includes/configuration/before-send/ruby.mdx
- src/includes/configuration/before-send/ruby.rails.mdx
- src/includes/performance/traces-sampler-as-sampler/ruby.mdx
I hope this makes examples easier to understand for users with different setups.
Related issues:
- https://github.com/getsentry/sentry-ruby/issues/1443
- https://github.com/getsentry/sentry-ruby/issues/1429
> Improve Ruby SDK's documents

- src/docs/product/sentry-basics/search/index.mdx
Fixes the content issue raised in https://github.com/getsentry/sentry-docs/issues/3584.
> Fix incorrect include

- src/includes/enriching-events/scopes/with-scope/dart.mdx
Fixes https://github.com/getsentry/sentry-docs/issues/3566
cc @marandaneto
> feat(Dart): With Scope Docs

- .github/workflows/issue-routing-helper.yml
I are a bot, here to deploy [issue-routing-helper.yml](https://github.com/getsentry/.github/blob/57bd472f2ba4a4fe2b6273d2efef592786e7e664/.github/workflows/issue-routing-helper.yml). 🤖
> meta(gha): Deploy action issue-routing-helper.yml

- src/docs/product/cli/releases.mdx
Ref: https://github.com/getsentry/sentry-cli/pull/963
> feat(cli): Add --ignore-missing flag documentation

- package.json
- yarn.lock
> chore(platformicons): updated to 4.2.0

- src/includes/enriching-events/scopes/with-scope/dart.mdx
the feature itself is fine, it's more about the availability
> Fix: Beta withScope for Dart

- src/pages/index.tsx
> Show Unity on the landing page

- src/wizard/dotnet/index.md
> performance wizard dotnet

- src/wizard/dotnet/aspnetcore.md
Didn't test the snippets yet. @Tyrrrz @lucas-zimerman 
Relates to #3647
> wizard aspnetcore perf

- src/wizard/kotlin/index.md
@PeloWriter @maciejwalkowiak @marandaneto thoughts?
> kotlin wizard

- src/platforms/common/enriching-events/scopes.mdx
- src/platforms/kotlin/index.mdx
> Document Kotlin coroutines support

- src/docs/product/sentry-basics/environments/index.mdx
As far as I can tell environments are available on all top-level features, including Dashboards.
> Remove incorrect line

- src/platforms/android/configuration/integrations/okhttp.mdx
> Document OkHttp callback for Android

- src/includes/getting-started-config/javascript.nextjs.mdx
- src/includes/getting-started-primer/javascript.nextjs.mdx
- src/platforms/javascript/guides/nextjs/manual-setup.mdx
Docs for the new performance monitoring of the Next.js SDK.
> Add Next.js SDK's performance monitoring docs

- src/includes/configuration/before-breadcrumb-hint/android.mdx
- src/includes/configuration/before-breadcrumb-hint/java.mdx
- src/includes/enriching-events/scopes/with-scope/java.mdx
- src/includes/performance/configure-sample-rate/java.spring-boot.mdx
- src/includes/performance/configure-sample-rate/java.spring.mdx
- src/includes/performance/set-transaction-current-scope/java.mdx
- src/includes/performance/traces-sampler-as-filter/android.mdx
- src/includes/performance/traces-sampler-as-filter/java.mdx
- src/includes/performance/traces-sampler-as-sampler/java.spring-boot.mdx
- src/includes/performance/traces-sampler-as-sampler/java.spring.mdx
- src/includes/set-fingerprint/static/java.mdx
- src/platforms/java/guides/spring-boot/advanced-usage.mdx
- src/platforms/java/usage.mdx
- Update Kotlin samples to match API nullability updated in Java SDK 5.0 (#3567)
- Fix minor mistakes in Kotlin samples.
> Java: polish Kotlin sample code.

- src/includes/getting-started-primer/android.mdx
- src/includes/getting-started-primer/apple.mdx
- src/includes/getting-started-primer/capacitor.mdx
- src/includes/getting-started-primer/dart.mdx
- src/includes/getting-started-primer/flutter.mdx
- src/includes/getting-started-primer/go.mdx
- src/includes/getting-started-primer/java.jul.mdx
- src/includes/getting-started-primer/java.log4j2.mdx
- src/includes/getting-started-primer/java.logback.mdx
- src/includes/getting-started-primer/java.mdx
- src/includes/getting-started-primer/java.spring-boot.mdx
- src/includes/getting-started-primer/java.spring.mdx
- src/includes/getting-started-primer/javascript.cordova.mdx
- src/includes/getting-started-primer/javascript.ember.mdx
- src/includes/getting-started-primer/javascript.nextjs.mdx
- src/includes/getting-started-primer/javascript.vue.mdx
- src/includes/getting-started-primer/native.qt.mdx
- src/includes/getting-started-primer/node.mdx
- src/includes/getting-started-primer/python.django.mdx
- src/includes/getting-started-primer/python.flask.mdx
- src/includes/getting-started-primer/python.mdx
- src/includes/getting-started-primer/react-native.mdx
- src/includes/getting-started-primer/ruby.mdx
- src/platforms/common/configuration/options.mdx
Also replaces "cacheing" with "caching"
> remove italic styling from primers

- src/wizard/dotnet/aspnetcore.md
@Tyrrrz 
Should we change this everywhere?
> connect span to error aspnetcore

- src/platforms/index.mdx
> feat(platforms): Add link to NestJS SDK

- src/docs/product/cli/configuration.mdx
ref: https://github.com/getsentry/sentry-cli/pull/970
> docs(cli): Add pipeline and custom_header config options

- src/platforms/android/migration.mdx
- src/platforms/java/migration.mdx
Fix https://github.com/getsentry/sentry-java/issues/1510
> Add new breaking changes on Java/Android

- src/platforms/common/configuration/options.mdx
Relates to https://github.com/getsentry/sentry-dart/pull/482
cc @marandaneto
> Add Dart option docs for `considerInAppFramesByDefault`

- src/includes/getting-started-install/android.mdx
- src/includes/getting-started-primer/android.mdx
- src/platforms/android/common/android-video.mdx
- src/platforms/android/migration.mdx
Adding this content to better surface what we offer to those users who prefer to use video to learn about our SDKs.
> Add video content

- src/platforms/common/configuration/options.mdx
- src/platforms/javascript/common/troubleshooting/index.mdx
SDK implementation: https://github.com/getsentry/sentry-javascript/pull/3521
> docs(js): Document tunnel option and how it helps with adblockers

- src/platforms/common/configuration/options.mdx
- src/platforms/java/common/configuration/index.mdx
> Document "ignored-exceptions-for-type" configuration option.

- src/docs/product/projects/index.mdx
Relates to https://github.com/getsentry/sentry/pull/26299
> feat: Add crash free sessions to Projects Homepage

- src/includes/getting-started-install/unity.mdx
- src/wizard/unity/index.md
Related to https://github.com/getsentry/sentry-unity/issues/228
> Note on broken Unity UPM

- src/platforms/android/common/performance/instrumentation/automatic-instrumentation.mdx
requires cutting a release still
> Feat: App start span for Android

- src/docs/product/releases/setup/release-automation/jenkins/index.mdx
Ensure that the install of Sentry CLI always returns true, as the example on Freestyle project does
> Install of sentry cli in pipeline must return true

- src/platforms/common/configuration/options.mdx
We have a note for Browser but nothing for mobile.
> describe auto session for mobile

- src/platforms/javascript/common/troubleshooting/index.mdx
Links to a location pending this PR: https://github.com/getsentry/examples/pull/93
> tunnel example dotnet

- src/platforms/javascript/common/troubleshooting/index.mdx
Closes https://github.com/getsentry/sentry-docs/issues/3766
> docs(js): Explain why relative url is recommended

- src/platforms/android/using-ndk.mdx
move Symbolicate Stack Traces and mildly restructure.
> Update NDK content

- src/includes/getting-started-primer/dotnet.mdx
> [.NET] Add release health to the list of features

- package.json
- yarn.lock
Fixes a security issue: https://github.com/advisories/GHSA-ww39-953v-wcq6
> upgrade(glob-parent): Upgrade glob-parent to 5.1.2

- package.json
- yarn.lock
Fixes a security issue: https://github.com/advisories/GHSA-6fc8-4gx4-v693
> upgrade(ws): Upgrade ws to 7.4.6

- src/platforms/common/configuration/filtering.mdx
Resolves https://github.com/getsentry/sentry-docs/issues/3778
> Add link to developer docs from Filtering

- src/includes/enriching-events/attachment-upload/java.mdx
similar to #3797
merge once Java repo is released
> Add clearAttachments to java docs

- src/includes/getting-started-install/unity.mdx
- src/platforms/unity/common/troubleshooting.mdx
A troubleshooting section for common issues that keep coming up. (draft)
> Unity: Troubleshooting section

- src/includes/configuration/auto-session-tracking/dotnet.mdx
> fix: release health typo

- src/docs/product/alerts/create-alerts/issue-alert-config.mdx
related https://github.com/getsentry/develop/pull/373
https://getsentry.atlassian.net/browse/WOR-1049
Some docs on the new % of session based alerting
> docs(alerts): Add session percentage alert condition

- src/platforms/common/configuration/options.mdx
> fix session timeout 30 seconds

- src/platforms/react-native/troubleshooting.mdx
Initial troubleshooting page for React Native with mentions to common issues and their fixes.
1. Source maps
2. Xcode CLI command
3. Release Health/Codepush
> feat: Initial troubleshooting page for RN

- src/wizard/capacitor/index.md
Adds an initial Capacitor wizard
> feat: Add Capacitor wizard

- src/wizard/python/sanic.md
This PR updates the versions the SDK supports in the Python SDK Sanic integration
> feat(python): Updates Sanic versions supported

- src/docs/product/alerts/notifications/index.mdx
We have 80% notifications for transactions now!
> fix(billing) Update 80% notification docs

- src/docs/product/accounts/sso/okta-sso.mdx
> fix(okta): Alert breaking indentation

- src/includes/performance/enable-automatic-instrumentation/javascript.mdx
As per concerns brought up in https://github.com/getsentry/sentry-docs/issues/3885
> fix(perf): Reference correct TracingIntegrations variable

- src/includes/getting-started-config/javascript.angular.mdx
- src/includes/performance/configure-sample-rate/javascript.mdx
- src/includes/performance/configure-sample-rate/javascript.react.mdx
- src/includes/performance/enable-automatic-instrumentation/javascript.mdx
- src/includes/performance/enable-automatic-instrumentation/javascript.react.mdx
- src/includes/performance/what-instrumentation-provides/javascript.react.mdx
> Add React-specific content for perf-monitoring.

- src/docs/product/sentry-basics/tracing/event-detail.mdx
> feat(span group): add blurb

- src/docs/product/releases/usage/index.mdx
Update front matter because of new child Sort & Filter page
> update releases usage page front matter

- src/includes/getting-started-config/javascript.vue.mdx
- src/includes/getting-started-install/javascript.vue.mdx
- src/includes/getting-started-primer/javascript.vue.mdx
- src/includes/getting-started-verify/javascript.vue.mdx
- src/includes/performance/configure-sample-rate/javascript.vue.mdx
- src/platforms/javascript/guides/vue/configuration/integrations/index.mdx
- src/platforms/javascript/guides/vue/configuration/integrations/vue-router.mdx
- src/wizard/javascript/vue.md
To be released once `6.10.0` is out.
> feat(vue): Rework Vue documentation to include Vue2 and Vue3 support

- src/docs/product/accounts/quotas/index.mdx
Adds information about spike protection being org-level and how it works.
> add clarity to spike protection content 

- src/docs/product/accounts/sso/azure-sso.mdx
- src/docs/product/accounts/sso/okta-sso/okta-scim.mdx
For the next week or two, users need to reach out directly to participate in SCIM's beta, as there are some addendum docs that need to be sent while we're still in the review process with our partners. (and isn't turned on for EA users at the moment).
> fix(scim): update SCIM EA note

- src/platforms/javascript/guides/nextjs/manual-setup.mdx
> fix(nextjs): Fix typo

- src/platforms/javascript/common/sourcemaps/troubleshooting_js.mdx
Not sure about the wording, but the content itself is valid.
> docs(js): Add dist to source maps troubleshooting page

- src/platforms/apple/common/dsym.mdx
Should avoid disappoints during EA.
> Update availability of appstore connect

- src/platforms/javascript/common/troubleshooting/index.mdx
> fix: tunnel snippet csharp

- src/includes/getting-started-primer/apple.mdx
Only merge when sentry-cocoa 7.2.0 GAs and https://github.com/getsentry/sentry-cocoa/pull/1258 is merged.
> feat(apple): Breadcrumbs for HTTP requests

- src/platforms/java/common/configuration/index.mdx
Fixes: https://github.com/getsentry/sentry-java/issues/1309
> Java: document offline caching

- src/platforms/java/guides/spring-boot/record-user.mdx
- src/platforms/java/guides/spring-boot/webflux.mdx
> Java: Add Webflux integration docs.

- src/platforms/apple/common/dsym.mdx
Added a link for the correct auth token permissions. Improved headings
and minor fixes to wording.
Fixes GH-3997
> fix(apple): Minor improvements for dSYMs

- src/docs/product/accounts/sso/okta-sso/okta-scim.mdx
We are letting all orgs who use okta enable SCIM and leaving the beta alert up for a little bit longer.
> feat(scim): Change messaging for okta beta

- src/platforms/java/guides/spring-boot/logging-frameworks.mdx
#3808 rebased on the top of master.
Closes #3808
> Add log4j2 dependency configuration.

- src/docs/product/releases/usage/sorting-filtering.mdx
> Update release sorting & filtering for GA

- src/includes/getting-started-config/node.mdx
Fixes: https://github.com/getsentry/sentry-docs/issues/3683
> Add explanation for unused `@sentry/tracing` import statement.

- src/includes/performance/automatic-instrumentation-integrations/dotnet.mdx
- src/platforms/dotnet/common/performance/instrumentation/automatic-instrumentation.mdx
Fixed heading level that was breaking RH sidebar navigation and changed to title case
> fix heading level and case

- src/platforms/apple/common/performance/instrumentation/automatic-instrumentation.mdx
> feat(apple): Clarify HTTP request support for PM

- src/platforms/dotnet/common/troubleshooting.mdx
Fixes wording of explanation of an error
> fix .dotnet troubleshooting wording

- src/data/platforms.yml
- src/includes/configuration/before-send-fingerprint/dart.mdx
- src/includes/configuration/before-send-hint/dart.mdx
- src/includes/configuration/before-send/dart.mdx
- src/includes/enriching-events/attachment-init-with-bytes/dart.mdx
- src/includes/enriching-events/attachment-init-with-path/dart.mdx
- src/includes/enriching-events/attachment-max-size/dart.mdx
- src/includes/enriching-events/attachment-upload/dart.mdx
- src/includes/enriching-events/user-feedback/sdk-api-example/dart.mdx
- src/includes/set-fingerprint/basic/dart.mdx
- src/includes/set-fingerprint/database-connection/dart.mdx
- src/includes/set-fingerprint/rpc/dart.mdx
- src/platforms/common/enriching-events/attachments/index.mdx
- src/platforms/common/enriching-events/scopes.mdx
- src/platforms/common/enriching-events/user-feedback.mdx
- src/platforms/dart/migration.mdx
- src/platforms/dart/usage/advanced-usage.mdx
- src/platforms/flutter/migration.mdx
Closes https://github.com/getsentry/sentry-docs/pull/4095
Continues https://github.com/getsentry/sentry-docs/pull/3901
> Flutter v6 docs

- src/platforms/android/using-ndk.mdx
Closes https://github.com/getsentry/sentry-docs/issues/3743
> Add Troubleshooting to Android NDK

- src/platforms/python/common/configuration/integrations/django.mdx
django project's url is changed.
> Change django project url

- src/includes/configuration/capture-console/javascript.mdx
- src/includes/configuration/debug/javascript.mdx
- src/includes/configuration/dedupe/javascript.mdx
- src/includes/configuration/enable-pluggable-integrations/javascript.mdx
- src/includes/configuration/extra-error-data/javascript.mdx
- src/includes/configuration/offline/javascript.mdx
- src/includes/configuration/reporting-observer/javascript.mdx
- src/includes/configuration/rewrite-frames/javascript.mdx
Fixes https://github.com/getsentry/sentry-docs/issues/4107
> docs(js): Update CDN integration examples

- src/includes/enriching-events/breadcrumbs/automatic-breadcrumbs/_default.mdx
https://github.com/getsentry/sentry-docs/issues/4009
> Add description of DOM events

- src/docs/product/releases/release-details.mdx
Release comparison is now GA, removing EA disclaimers.
> feat: GA release comparison

- src/docs/product/accounts/sso/okta-sso/okta-scim.mdx
been in production for a couple of week and no real issues, think we're good to remove the beta tag.
> feat(scim): remove beta tag

- src/platforms/javascript/common/install/lazy-load-sentry.mdx
Unless I'm misreading the sentence badly, i think this needs to have a not. I could well be wrong
> Add a not (typo) to lazy loading page

- src/includes/configuration/auto-session-tracking/dotnet.mdx
- src/includes/configuration/config-intro/dotnet.nlog.mdx
- src/includes/enriching-events/set-tag/dotnet.nlog.mdx
- src/includes/enriching-events/set-user/dotnet.nlog.mdx
- src/includes/set-environment/dotnet.nlog.mdx
- src/includes/set-release/dotnet.nlog.mdx
- src/platforms/dotnet/guides/nlog/configuration/advanced-configuration-example.mdx
- src/platforms/dotnet/guides/nlog/index.mdx
Updates documentation related to NLog.
cc: @bruno-garcia 
Closes #4114
> dotnet(nlog): Update NLog specific documentation

- src/includes/configuration/config-intro/dotnet.mdx
- src/includes/enriching-events/attachment-init-with-bytes/dotnet.mdx
- src/includes/enriching-events/attachment-init-with-path/dotnet.mdx
- src/includes/enriching-events/scopes/configure-scope/dotnet.mdx
- src/includes/enriching-events/scopes/with-scope/dotnet.mdx
- src/includes/enriching-events/set-user/dotnet.mdx
- src/includes/enriching-events/unset-user/dotnet.mdx
- src/includes/set-level/dotnet.mdx
- src/includes/set-release/dotnet.mdx
- src/includes/set-release/dotnet.nlog.mdx
- Updates release version location documentation
- Add samples for unsetting user
- Clean up / add some F# code samples
> fix(dotnet): Update dotnet code samples

- src/platforms/android/common/performance/instrumentation/automatic-instrumentation.mdx
similar to https://docs.sentry.io/platforms/android/configuration/releases/#androidx-support
> Mention removal of AndroidX Core

- src/wizard/android/index.md
similar to C#
https://github.com/getsentry/sentry-docs/blob/master/src/wizard/dotnet/index.md
> Align transaction name and op - Android wizard

- src/wizard/apple/index.md
We didn't mention performance in the wizard. This is fixed now.
> feat(apple): Add performance to wizard

- src/components/banner.tsx
turning on docs banner for 10/5 workshop
> Turn on Docs banner

- src/docs/product/accounts/membership.mdx
Adjust heading notation to fix right side menu navigation
> Heading adjusting

- src/platforms/dotnet/guides/xamarin/index.mdx
This PR adds the new option from Xamarin that allows users to have events with screenshots automatically.
> Include screenshot option for Xamarin

- src/wizard/java/spring-boot.md
- src/wizard/java/spring.md
> Add performance to Java wizard and its integrations.

- src/platforms/apple/common/performance/instrumentation/automatic-instrumentation.mdx
> fix(apple): APM broken link

- src/docs/product/accounts/sso/azure-sso.mdx
Fixes beta note that was updated incorrectly while resolving a merge conflict
> fix azure scim beta note

- src/platforms/python/common/configuration/integrations/httpx.mdx
- src/platforms/python/common/configuration/integrations/index.mdx
> Document Python HTTPX integration

- src/components/banner.tsx
> feat change docs banner

- src/platforms/javascript/guides/gatsby/index.mdx
- src/wizard/javascript/gatsby.md
Fixes the Gatsby code samples in the getting started page and onboarding wizard.
> fix(gatsby): Code samples in getting started page and wizard

- src/docs/product/cli/send-event.mdx
ref: https://github.com/getsentry/sentry-cli/pull/1058
NOTE: Merge once `1.71.0` is released.
> docs(cli): Update send-event with stored files reading

- src/docs/product/alerts/alert-types.mdx
Removes EA note and moves up plan note
> remove EA note for crash rate alerts

- src/docs/product/sentry-basics/guides/enrich-data/index.mdx
Light-weight style and grammar edit of this content ahead of moving it
> put your data to work improvements

- src/wizard/android/index.md
- src/wizard/capacitor/index.md
- src/wizard/dart/index.md
- src/wizard/dotnet/aspnet.md
- src/wizard/dotnet/aspnetcore.md
- src/wizard/dotnet/awslambda.md
- src/wizard/dotnet/gcpfunctions.md
- src/wizard/dotnet/uwp.md
- src/wizard/dotnet/winforms.md
- src/wizard/dotnet/wpf.md
- src/wizard/dotnet/xamarin.md
- src/wizard/flutter/index.md
- src/wizard/java/index.md
- src/wizard/kotlin/index.md
- src/wizard/react-native/index.md
@lucas-zimerman @jennmueng Would you please help review the relevant wizards?
> wizard performance enabled

- src/docs/product/data-management-settings/event-grouping/stack-trace-rules.mdx
This code sample does not match the description, courtesy to @rohitkataria-sentryio
> fix: Code sample in stack-trace-rules.mdx

- src/docs/product/accounts/sso/index.mdx
Add note about sso expiry for upcoming change (https://github.com/getsentry/sentry/pull/29422)
> feat(sso): add note about org sso 

- src/platforms/android/configuration/manual-init.mdx
DSN is an integral part of the manual initialisation
> Add DSN in the manual init

- src/wizard/elixir/index.md
Update as per https://github.com/getsentry/sentry-elixir/pull/472. 
Co-authored-by: Daniel Morgan <danmorgz@googlemail.com>
> elixir: Update crashed process exceptions guide

- src/wizard/android/index.md
Add a note about Room integration to the Android wizard with a caveat that this is in beta
> feat(android): Note about Room instrumentation

- src/docs/product/sentry-basics/guides/integrate-backend/capturing-errors.mdx
- src/docs/product/sentry-basics/guides/integrate-backend/configuration-options.mdx
- src/docs/product/sentry-basics/guides/integrate-backend/getting-started.mdx
- src/docs/product/sentry-basics/guides/integrate-backend/index.mdx
- src/docs/product/sentry-basics/guides/integrate-frontend/configure-scms.mdx
- src/docs/product/sentry-basics/guides/integrate-frontend/create-new-project.mdx
- src/docs/product/sentry-basics/guides/integrate-frontend/generate-first-error.mdx
- src/docs/product/sentry-basics/guides/integrate-frontend/index.mdx
- src/docs/product/sentry-basics/guides/integrate-frontend/initialize-sentry-sdk.mdx
- src/docs/product/sentry-basics/guides/integrate-frontend/upload-source-maps.mdx
PR makes high-level style and grammar edits on tutorials ahead of moving them up one level in docs.
> style and grammar edits on tutorials

- src/platforms/react-native/sourcemaps.mdx
resolves a lot of issues like https://github.com/getsentry/sentry-react-native/issues/914#issuecomment-963244589
> Set custom releand and dist via environment variables

- src/wizard/android/index.md
Notes aren't support since it's a plain `.md` file
> fix(android): Change <note> to blockquote

- src/docs/product/alerts/create-alerts/issue-alert-config.mdx
Adds a new h3 section in Issue Alert Configuration for percent-based alerts
> create section for percent-based alerts

- src/platforms/react-native/troubleshooting.mdx
Closes https://github.com/getsentry/sentry-docs/issues/4344
> Remove expo warning

- src/includes/enriching-events/scopes/configure-scope/react-native.mdx
- src/platforms/react-native/troubleshooting.mdx
similar to Android https://docs.sentry.io/platforms/android/enriching-events/scopes/#configuring-the-scope
> Document enableNdkScopeSync option for RN

- src/includes/getting-started-install/react-native.mdx
so you read the `note` before executing the command
> Change sorting of the note for RN linking

- .github/ISSUE_TEMPLATE/config.yml
- .github/workflows/release.yml
- src/platforms/dart/migration.mdx
https://github.com/getsentry/self-hosted/issues/796
> Rename onpremise to self-hosted

- src/platforms/unity/troubleshooting.mdx
> unity: troubleshooting dll conflict

- src/docs/contributing/pages/components.mdx
Adds PlatformIdentifier to Contributing to Docs
Alphabetizes mdx components page
> add PlatformIdentifier component to contributing docs

- src/docs/product/alerts/create-alerts/metric-alert-config.mdx
Updates metric alert config page with rule name limitations
> unique rule names for metric alerts

- src/components/banner.tsx
Swapped Shift banner for open source event banner on docs
> Updated docs banner.tsx

- src/platforms/common/data-management/debug-files/symbol-servers.mdx
Coming from https://github.com/getsentry/sentry/issues/30282#issuecomment-984645897 ... @flub Is this note accurate?
cc: @yayanet
> Note iOS symbol server limitation in self-hosted

- src/platforms/react-native/manual-setup/hermes.mdx
- src/platforms/react-native/manual-setup/ram-bundles.mdx
Adding note for not supported Hermes and RAM Bundles https://reactnative.dev/docs/ram-bundles-inline-requires
> Add note for Hermes and RAM Bundles

- src/platforms/common/enriching-events/user-feedback.mdx
Closes https://github.com/getsentry/sentry-docs/issues/4089
> Hide user-feedback for React Native

- src/docs/product/alerts/create-alerts/routing-alerts.mdx
- src/docs/product/integrations/cloud-monitoring/aws-lambda/index.mdx
- src/docs/product/integrations/cloud-monitoring/gcp-cloud-run/index.mdx
- src/docs/product/integrations/data-visualization/amazon-sqs/index.mdx
- src/docs/product/integrations/data-visualization/splunk/index.mdx
- src/docs/product/integrations/debugging/rookout/index.mdx
- src/docs/product/integrations/deployment/heroku/index.mdx
- src/docs/product/integrations/deployment/vercel/index.mdx
- src/docs/product/integrations/feature-flag/split/index.mdx
- src/docs/product/integrations/notification-incidents/amixr/index.mdx
- src/docs/product/integrations/notification-incidents/msteams/index.mdx
- src/docs/product/integrations/notification-incidents/pagerduty/index.mdx
- src/docs/product/integrations/notification-incidents/slack/index.mdx
- src/docs/product/integrations/notification-incidents/spikesh/index.mdx
- src/docs/product/integrations/project-mgmt/asana/index.mdx
- src/docs/product/integrations/project-mgmt/clickup/index.mdx
- src/docs/product/integrations/project-mgmt/jira/index.mdx
- src/docs/product/integrations/project-mgmt/linear/index.mdx
- src/docs/product/integrations/project-mgmt/shortcut/index.mdx
- src/docs/product/integrations/project-mgmt/teamwork/index.mdx
- src/docs/product/integrations/source-code-mgmt/azure-devops/index.mdx
- src/docs/product/integrations/source-code-mgmt/bitbucket/index.mdx
- src/docs/product/integrations/source-code-mgmt/github/index.mdx
- src/docs/product/releases/setup/release-automation/index.mdx
Fixes role permission notes for integrations
Adds notes where they are missing
Makes styling of role permission notes consistent
> fix role permissions info for integrations

- src/platforms/react-native/performance/instrumentation/automatic-instrumentation.mdx
Similar to https://docs.sentry.io/platforms/android/performance/instrumentation/automatic-instrumentation/#androidx-support
> AndroidX support for RN apps

- src/docs/product/relay/getting-started.mdx
Adds link to Relay index page from Getting Started page
> add link to relay index page

- src/platforms/android/common/performance/instrumentation/automatic-instrumentation.mdx
merge once https://github.com/getsentry/sentry-java/releases/tag/5.4.4 is released
> Rename Fragment span operation

- src/includes/performance/add-spans-example/javascript.mdx
> Fix "';' expected." error in example code

- src/components/layout.tsx
- src/components/navbar.tsx
- src/css/_includes/global-header.scss
- src/css/_includes/grid.scss
Fix #3837
The suggestions dropdown is also fairly usable, but requires further
love by somebody smarter.
Putting up random reviewers from suggestions.
> fix(ui): Make searchbar usable on mobile [INGEST-581]

- src/includes/getting-started-primer/android.mdx
- src/platforms/android/common/performance/instrumentation/automatic-instrumentation.mdx
- src/platforms/android/configuration/integrations/apollo.mdx
> ref(android): Move apollo-android under Integrations section

- src/platforms/python/guides/sanic/index.mdx
See https://github.com/getsentry/sentry-python/pull/1292
> Update Sanic versions in documentation 

- src/includes/getting-started-install/javascript.react.mdx
Attempts to fix react code snippet by forcing a build by way of a small change (adding a line break)
Issue [4547](https://github.com/getsentry/sentry-docs/issues/4547)
> fix react code snippet - second attempt

- src/wizard/android/index.md
Has to be merged after #4575 and #4574
> ref: Update android wizard with latest SAGP version and new File I/O integration

- src/platforms/node/guides/koa/index.mdx
Using `=>` to create a function in the sample code for consistency.
> use arrow function in sample code for consistency

- src/platforms/common/configuration/options.mdx
> Add missing PHP options

- src/docs/product/integrations/integration-platform/webhooks.mdx
Fixes issue [4580](https://github.com/getsentry/sentry-docs/issues/4580)
> fix webhooks docs anchor link issue

- .github/workflows/release.yml
> Attempt to become the release actor

- src/wizard/apple/ios.md
- src/wizard/apple/macos.md
Explain how to init the Cocoa SDK when using SwiftUI
in the wizard.
> feat(apple): Add SwiftUI init to wizard

- src/api/auth.mdx
- src/api/index.mdx
- src/api/pagination.mdx
- src/api/permissions.mdx
- src/api/ratelimits.mdx
- src/api/requests.mdx
- src/gatsby/createPages/createApiReference.ts
Document focuses on giving relevant information to API Users regarding the rate limit and how to monitor it.
> feat(ratelimits): Added page for rate limit in api reference

- src/docs/product/integrations/integration-platform/webhooks.mdx
Follow up to https://github.com/getsentry/sentry/pull/31222
Update docs with the new fields.
> feat(webhooks): Add issue_id to event_alert and error.created

- src/docs/product/cli/configuration.mdx
https://github.com/getsentry/sentry-cli/blob/master/CHANGELOG.md#1720
> docs(cli): Add changes related to sentry-cli 1.72.0 release

- src/docs/product/dashboards/widget-library/index.mdx
Updates the Widget Library Issue Widget title and description reflect recent changes made to widget
> feat(dashboards): Widget Library Issue Widget title and description update.

- src/docs/product/accounts/quotas/index.mdx
Adds brief explanation of 429 status code behaviour to quota management docs
> add 429 behaviour explanation

- src/components/dynamicNav.tsx
- src/css/_includes/sidebar.scss
This is in response to https://github.com/getsentry/sentry-docs/issues/4509
> giving titles active style and colors more similar to other links

- src/platforms/php/common/configuration/transports.mdx
- src/platforms/php/guides/symfony/configuration/symfony-options.mdx
I've tried to address the [feedback provided](https://github.com/getsentry/sentry-docs/issues/3479#issuecomment-1021978559) by @Jean85 to improve the Symfony and transport docs for PHP.
> Update Symfony config docs

- src/platforms/dotnet/guides/aspnet/index.mdx
> fix(aspnet): last item is addaspnet

- src/docs/product/dashboards/custom-dashboards/index.mdx
- src/docs/product/dashboards/index.mdx
- This adds documentation explaining how there's a section where dashboards can be created from templates
- TODO: Need to update the `dashboard-management.png` before merging
> feat(dashboards): Add a section for the dashboard templates

- src/includes/getting-started-install/javascript.react.mdx
Just needs to close the snippet
> docs: update react getting started code example

- src/docs/product/dashboards/widget-library/index.mdx
Mis-named widget and updating the query condition.
> fix(docs): Widget Library docs bug fixes

- src/api/ratelimits.mdx
Also removed references to org rate limits being higher.
> fix(ratelimits): Added some text on webhooks

- src/docs/product/relay/options.mdx
See https://github.com/getsentry/relay/pull/1175
> doc(relay): Describe `relay.override_project_ids` [INGEST-927]

- src/docs/product/accounts/sso/index.mdx
- Adds basic instructions for configuring jumpcloud SAML
- Adds a note about generic SCIM integration.
> feat(sso): add jumpcloud SAML 

- .github/workflows/issue-routing-helper.yml
I are a bot, here to deploy [issue-routing-helper.yml](https://github.com/getsentry/.github/blob/bd98b16ca1d7a9959448024d1fc4fdde1e9c9e49/.github/workflows/issue-routing-helper.yml). 🤖
> meta(gha): Deploy workflow issue-routing-helper.yml

- src/docs/product/dashboards/widget-library/index.mdx
Adding new Issue Widget use cases.
> Widget Library Documentation Edit

- src/components/banner.tsx
@imatwawana and @dorothymlee - i took down the old workshop and added the new event
> added devops js banner

- src/docs/contributing/approach/product-docs/write-index.mdx
Removes link to Writing Style Guide from Contributors docs to reduce confusion
> remove writing style guide link

- src/platforms/unity/migration.mdx
Added a migration guide how to go about the new programmatic configuration in combination with the editor configuration window.
> feat(unity): Added options configuration to migration page

- src/platforms/javascript/guides/nextjs/manual-setup.mdx
> fix(typo): Spelling mistake on source maps

- src/platforms/react-native/manual-setup/manual-setup.mdx
- src/platforms/react-native/troubleshooting.mdx
Context: https://github.com/getsentry/sentry-react-native/issues/2067#issuecomment-1055938894
> Add nvm volta workaround for node on troubleshooting page for RN

- src/gatsby/config.ts
- src/gatsby/plugins/gatsby-remark-terms/index.js
- src/gatsby/plugins/gatsby-remark-terms/package.json
> feat: Add very simple glossary [INGEST-901]

- src/gatsby/utils/resolveOpenAPI.ts
update sha to latest to show new API doc endpoints added (want it to be up to date for shipped announcement tmrw)
> chore(apidocs): update api-schema sha

- src/gatsby/createSchemaCustomization/apiSchema.ts
- src/gatsby/plugins/gatsby-plugin-openapi/types.ts
- src/templates/apiPage.tsx
> add items to openapi query path params

- src/platforms/dart/configuration/integrations/logging.mdx
Merge only after https://github.com/getsentry/sentry-release-registry/pull/66
> Set logging with versioning from release registry

- src/platforms/common/enriching-events/event-processors.mdx
- vercel.json
Removed final page redirect and added an entry to the vercel.json file to fix navigation.
> moved page redirect to vercel.json file entry

- .github/workflows/enforce-license-compliance.yml
First try for https://github.com/getsentry/.github/issues/81.
> Bring back FOSSA

- src/includes/getting-started-primer/unity.mdx
- src/platforms/unity/native-support/index.mdx
I added the Windows native support to the primer & native support page.
Resolves https://github.com/getsentry/sentry-docs/issues/4822
> feat(unity): Windows native support

- package.json
- yarn.lock
> chore(platformicons): updated to 4.3.2

- src/components/banner.tsx
Monday.com workshop completed, updated to next workshop
> updated docs banner

- src/platforms/flutter/migration.mdx
Context https://github.com/getsentry/sentry-dart/issues/745
> Add breaking change entry for Flutter 6.4

- src/platforms/common/configuration/options.mdx
https://github.com/getsentry/sentry-react-native/blob/17fd6144b1f975219ad580bb3c92902a417b5712/src/js/options.ts#L82-L86
> Remove initial scope from RN docs

- src/platforms/common/data-management/debug-files/upload/index.mdx
We might want to swap out the complete content of this page instead of just adding the note. This could be a temporary workaround from the current 'misleading' format
> add a note about unity auto upload

- src/platforms/apple/common/performance/instrumentation/automatic-instrumentation.mdx
Only merge after https://github.com/getsentry/sentry-cocoa/pull/1711 is released.
> feat(apple): Flag for UIViewControllerTracking

- src/platforms/common/enriching-events/identify-user.mdx
Clarifying language around collection vs storage
> update description for ip addresses

- src/platforms/android/common/gradle.mdx
Merge after 3.1.0 of SAGP is shipped.
> feat(android): Update Gradle docs with auto-installation and okhttp instrumentation

- src/platforms/common/configuration/options.mdx
Merge after https://github.com/getsentry/sentry-react-native/pull/2175 gets released
> Add normalizeMaxBreadth for RN

- src/docs/clients/ruby/processors.mdx
Removes redirect that appears to be circular
> remove redirect

- .github/workflows/enforce-license-compliance.yml
Part of https://github.com/getsentry/.github/issues/81.
> Factor FOSSA out into a separate action

- src/platforms/dotnet/common/troubleshooting.mdx
Resolves getsentry/sentry-dotnet#321
> Add note about async main in .NET

- src/platforms/flutter/common/performance/instrumentation/automatic-instrumentation.mdx
Fixes https://github.com/getsentry/sentry-docs/issues/4908
cc @ueman
> Document AssetBundle for Flutter

- src/platforms/common/configuration/options.mdx
Merge after https://github.com/getsentry/sentry-java/pull/1967
> Document attach-screenshot for Android

- src/docs/product/integrations/issue-tracking/jira/index.mdx
Replaces PR 4855 (got old and had merge conflicts)
> specify jira integration permissions

- src/platforms/flutter/common/performance/instrumentation/automatic-instrumentation.mdx
Address https://github.com/getsentry/sentry-dart/issues/827 issue
> GoRouter instrumentation Flutter

- .github/PULL_REQUEST_TEMPLATE.md
First try.
https://github.com/getsentry/.github/pull/76 for _every_ repo
> Pilot a cheap CLA

- src/platforms/android/configuration/integrations/fragment.mdx
- src/platforms/android/configuration/integrations/okhttp.mdx
- src/platforms/android/configuration/integrations/timber.mdx
[ Issue # and PR description here ]
----
> chore(android): Bump SAGP 3.1.0-beta.1 for auto-install

- src/docs/product/sentry-basics/enrich-data/index.mdx
Clarifies wording about page filters
----
> updated wording for new filter UI

- src/components/banner.tsx
[ Issue # and PR description here ]
----
> updated docs banner for pycon workshop

- src/docs/product/sentry-basics/migration/index.mdx
Adds information about a migration export option that's not docker
> update export section of migration docs

- src/platforms/flutter/common/performance/instrumentation/automatic-instrumentation.mdx
> Flutter vitals GA

- src/wizard/android/index.md
> feat(android): Note about beta auto-installation feature on the wizard

- src/includes/getting-started-primer/flutter.mdx
- src/platforms/flutter/common/performance/instrumentation/automatic-instrumentation.mdx
----
By submitting this pull request, I confirm that Sentry can use, modify, copy, and redistribute this contribution, under Sentry's choice of terms.
> Document AssetBundle and Platform exception Flutter

- src/platforms/unity/native-support/index.mdx
I updated the native docs for mobile, going a bit more into detail, giving Android and iOS their own heading.
> chore(unity): Updated Native

- src/components/banner.tsx
----
By submitting this pull request, I confirm that Sentry can use, modify, copy, and redistribute this contribution, under Sentry's choice of terms.
> hid banner

- src/platforms/apple/common/performance/instrumentation/automatic-instrumentation.mdx
Only merge after releasing https://github.com/getsentry/sentry-cocoa/pull/1802
> Apple: Remove note on ViewController name matching

- src/includes/enriching-events/user-feedback/sdk-api-example/dart.mdx
Closes https://github.com/getsentry/sentry-docs/issues/5020
> Fix user feedback code snippet on Dart

- .github/PULL_REQUEST_TEMPLATE.md
See https://github.com/getsentry/.github/pull/92.
> Bring in CLA Lite

- src/includes/getting-started-primer/apple.mdx
----
By submitting this pull request, I confirm that Sentry can use, modify, copy, and redistribute this contribution, under Sentry's choice of terms.
> apple link to oom

- src/docs/product/security/terms.mdx
Add a note in parentheses about limitations for self-serve BAA
> add (Business plans or higher) to BAA link

- src/includes/getting-started-primer/android.mdx
- src/platforms/android/common/performance/instrumentation/automatic-instrumentation.mdx
- src/platforms/common/configuration/options.mdx
Merge after https://github.com/getsentry/sentry-java/pull/1975
> feat(android): UI events transactions

- src/platforms/unity/troubleshooting.mdx
Aims to answer the question: "How can I disable Sentry for a specific platform?"
> feat(unity): Added automation snippet to troubleshooting

- src/docs/product/releases/usage/archive-release.mdx
- src/docs/product/releases/usage/restore-release.mdx
- src/docs/product/releases/usage/sorting-filtering.mdx
- src/docs/product/releases/usage/time-range.mdx
- Reorders pages under Usage
- Retitles Change Time Range page
- General style/wording fixes
> reorder and update releases usage pages

- src/docs/product/alerts/best-practices.mdx
- src/docs/product/alerts/create-alerts/issue-alert-config.mdx
- src/docs/product/alerts/create-alerts/routing-alerts.mdx
- src/docs/product/integrations/debugging/rookout/index.mdx
- src/docs/product/integrations/feature-flag/split/index.mdx
- src/docs/product/integrations/index.mdx
- src/docs/product/integrations/integration-platform/index.mdx
- src/docs/product/integrations/integration-platform/internal-integration.mdx
- src/docs/product/integrations/integration-platform/ui-components/index.mdx
- src/docs/product/integrations/integration-platform/webhooks.mdx
- src/docs/product/integrations/integration-platform/webhooks/comments.mdx
- src/docs/product/integrations/integration-platform/webhooks/errors.mdx
- src/docs/product/integrations/integration-platform/webhooks/installation.mdx
- src/docs/product/integrations/integration-platform/webhooks/issue-alerts.mdx
- src/docs/product/integrations/integration-platform/webhooks/issues.mdx
- src/docs/product/integrations/integration-platform/webhooks/metric-alerts.mdx
- src/docs/product/integrations/issue-tracking/clickup/index.mdx
- src/docs/product/integrations/issue-tracking/height/index.mdx
- src/docs/product/integrations/issue-tracking/linear/index.mdx
- src/docs/product/integrations/issue-tracking/shortcut/index.mdx
- src/docs/product/integrations/issue-tracking/teamwork/index.mdx
- src/docs/product/integrations/notification-incidents/amixr/index.mdx
- src/docs/product/integrations/notification-incidents/spikesh/index.mdx
Fixes feature name capitalization
Properly styles references to integration platform docs
> fix integration platform capitalization

- src/platforms/javascript/common/configuration/integrations/plugin.mdx
Resolves https://github.com/getsentry/sentry-docs/issues/4939
> Add `toJSON()` explanation for `ExtraErrorData`

- src/docs/product/releases/health/index.mdx
Adds definitions for a user 
Adds example for crash-free user
Adds more information about sessions and session status
> add more user & session release health details

- src/platforms/unity/troubleshooting.mdx
> fix: typos in Unity troubleshooting

- src/includes/configuration/sample-rate/go.mdx
> feat(go): Add `SampleRate` code sample for go

- src/platforms/common/configuration/options.mdx
> Document `enabled` option for JS SDKs.

- src/platforms/dotnet/guides/maui/config.yml
- src/platforms/dotnet/guides/maui/index.mdx
Adding initial documentation for .NET MAUI
> Add first docs for .NET MAUI

- .github/workflows/bump-api-schema-sha.yml
Follow-up to #5153 to handle [this failure case](https://github.com/getsentry/sentry-docs/runs/6922429236?check_suite_focus=true#step:3:34)
> Go through a PR to work with branch protections

- .github/workflows/bump-api-schema-sha.yml
← #5154
https://github.com/getsentry/sentry-docs/runs/6922670781?check_suite_focus=true#step:3:37
> Oops, there is no --branch long opt

- .github/workflows/bump-api-schema-sha.yml
&larr; https://github.com/getsentry/sentry-docs/pull/5155
[fixes these](https://github.com/getsentry/sentry-docs/pull/5155)
> Fix bugs in PR branch name and push

- .github/workflows/prepare-release.yml
> Rename Release action to Prepare Release

- src/platforms/dotnet/guides/maui/index.mdx
- Update status of install issue
- Add features overview
- Add MAUI options
- Move preview status section up
> More .NET MAUI docs

- src/platforms/android/troubleshooting.mdx
> android anr troubleshooting opt-out

- src/docs/clients/javascript/integrations.mdx
- src/docs/clients/react-native/sourcemaps.mdx
- src/platforms/react-native/manual-setup/hermes.mdx
- src/platforms/react-native/sourcemaps.mdx
> Call reset cache when calling RN bundle

- src/css/_includes/terms.scss
- src/css/_includes/variables.scss
- src/css/screen.scss
- src/gatsby/plugins/gatsby-remark-terms/index.js
> adding new styles and making it somewhat more accessible

- src/platforms/common/enriching-events/tags.mdx
Closes https://github.com/getsentry/sentry-docs/issues/5014
> feat(tags): Document tag keys+values validation [TET-95]

- src/includes/getting-started-primer/unity.mdx
> unity: state supported platforms

- src/platforms/react-native/manual-setup/hermes.mdx
https://github.com/facebook/react-native/issues/34043#issuecomment-1163796634
> Add note about Hermes path on RN 0.69

- src/platforms/apple/common/performance/instrumentation/automatic-instrumentation.mdx
Mention since when we stop reporting pre-warm starts and point
out the GH issue.
> fix(apple): Clarify pre-warm start

- src/components/banner.tsx
> updated banner

- src/components/banner.tsx
> updated URL

- src/platforms/react-native/troubleshooting.mdx
https://github.com/getsentry/sentry-react-native/issues/2267
> Troubleshooting entry for RN autolinking

- src/includes/set-level/unity.mdx
I added a Unity-specific snippet for `set-level`.
> fix(unity): Set-Level snippet

- src/docs/product/integrations/cloud-monitoring/aws-lambda/index.mdx
- src/platforms/dotnet/guides/xamarin/troubleshooting.mdx
- src/platforms/flutter/troubleshooting.mdx
- src/platforms/javascript/common/troubleshooting/index.mdx
- src/platforms/javascript/guides/cordova/troubleshooting.mdx
Addresses @drguthals comments at https://github.com/getsentry/sentry-docs/pull/5194#pullrequestreview-1018073588 (which I missed when responding to review over there) and https://github.com/getsentry/sentry-docs/pull/5194#discussion_r905784314.
> Standardize links to GH Issues

- src/includes/set-level/apple.mdx
Add missing set-level snippet for Apple.
> feat(apple): Set level snippet

- src/platforms/dotnet/guides/maui/index.mdx
Updating docs for MAUI Preview 2
> Updating for MAUI Preview 2

- src/platforms/react-native/troubleshooting.mdx
> Fix Sentry CLI path respecting the RN node path

- src/platforms/react-native/manual-setup/hermes.mdx
- src/platforms/react-native/sourcemaps.mdx
This PR likely replaces https://github.com/getsentry/sentry-docs/pull/5236
> Fix commands for React Native and Hermes

- src/platforms/dart/configuration/integrations/dio.mdx
https://github.com/getsentry/sentry-dart/pull/914
> Dart/Flutter Dio is GA

- src/docs/product/accounts/pricing.mdx
Adds links at top of Pricing & Billing page for quicker navigation
> add links to pricing page

- src/includes/enriching-events/unset-user/javascript.mdx
Fixes https://github.com/getsentry/sentry-docs/issues/3595
> Align set user with unset user shortcut (JS/RN)

- src/docs/product/integrations/data-visualization/amazon-sqs/index.mdx
- src/docs/product/integrations/data-visualization/splunk/index.mdx
- src/docs/product/integrations/debugging/rookout/index.mdx
- src/docs/product/integrations/deployment/heroku/index.mdx
- src/docs/product/integrations/deployment/vercel/index.mdx
- src/docs/product/integrations/feature-flag/split/index.mdx
- src/docs/product/integrations/issue-tracking/asana/index.mdx
- src/docs/product/integrations/issue-tracking/clickup/index.mdx
- src/docs/product/integrations/issue-tracking/height/index.mdx
- src/docs/product/integrations/issue-tracking/jira/index.mdx
- src/docs/product/integrations/issue-tracking/linear/index.mdx
- src/docs/product/integrations/issue-tracking/shortcut/index.mdx
- src/docs/product/integrations/issue-tracking/teamwork/index.mdx
- src/docs/product/integrations/notification-incidents/amixr/index.mdx
- src/docs/product/integrations/notification-incidents/msteams/index.mdx
- src/docs/product/integrations/notification-incidents/pagerduty/index.mdx
- src/docs/product/integrations/notification-incidents/slack/index.mdx
- src/docs/product/integrations/notification-incidents/threads/index.mdx
- src/docs/product/integrations/source-code-mgmt/azure-devops/index.mdx
- src/docs/product/integrations/source-code-mgmt/bitbucket/index.mdx
- src/docs/product/integrations/source-code-mgmt/github/index.mdx
- src/docs/product/integrations/source-code-mgmt/gitlab/index.mdx
Add alt text for integration documentation images.
> chore(integrations): Add alt text for images

- src/platforms/javascript/common/configuration/integrations/plugin.mdx
Fixes #4215 
This integration is not supported for Electron
> fix(electron): Don't show Offline integration for Electron

- src/wizard/dotnet/maui.md
> Add MAUI Wizard page

- src/wizard/dotnet/index.md
- src/wizard/dotnet/maui.md
Minor improvements for MAUI to the Wizard
> Minor MAUI text improvements

- src/platforms/index.mdx
Update dead link to new Strapi plugin for v4+
> update Strapi link

- src/platforms/apple/common/configuration/out-of-memory.mdx
Only merge after releasing https://github.com/getsentry/sentry-cocoa/pull/1970.
> feat(apple): Not reporting OOMs on simulators

- src/docs/product/integrations/integration-platform/ui-components/formfield.mdx
This PR changes Bool -> Boolean, and corrects one of the field props
> fix(docs): Correct boolean on Select field

- src/platforms/android/troubleshooting.mdx
> android debug tips

- src/docs/product/sentry-basics/search/searchable-properties.mdx
- This updates the searchable properties so timestamp is an issue property too
> fix: Timestamp is an issue property too

- src/components/banner.tsx
> updated docs banner to DEX

- src/wizard/apple/ios.md
> wizard(ios) opt-in to screenshots

- src/platforms/react-native/manual-setup/codepush.mdx
Solution given by @marandaneto https://github.com/getsentry/sentry-react-native/issues/2372#issuecomment-1194020493
> Describe --version-name for iOS

- src/docs/product/accounts/sso/azure-sso.mdx
- src/docs/product/accounts/sso/index.mdx
- src/docs/product/accounts/sso/okta-sso/index.mdx
- src/docs/product/accounts/sso/okta-sso/okta-scim.mdx
- src/docs/product/accounts/sso/ping-sso.mdx
- src/docs/product/accounts/sso/saml2.mdx
Add blurbs in documentation pages for SAML and SCIM on warning users to update relevant configuration values when an organization slug name has been updated.
> chore(hybrid-cloud): Add generic docs for SCIM/SAML when renaming an org.

- src/platforms/common/configuration/options.mdx
> Add experimental flags section under common options

- src/platforms/apple/common/performance/instrumentation/automatic-instrumentation.mdx
> fix cocoa ui event perf option name

- src/platforms/common/performance/index.mdx
> fine tune connecting services doc

- src/platforms/javascript/guides/capacitor/ionic.mdx
- src/platforms/javascript/guides/cordova/ionic.mdx
Hide from search the mention of Ionic on Cordova.
Add an Ionic page for Capacitor.
> Ref: Ionic Docs on Capacitor and Cordova

- src/platforms/unity/configuration/il2cpp.mdx
> feat(unity): IL2CPP

- src/includes/getting-started-config/javascript.remix.mdx
> Fix spacing for Remix SDK snippet

- .github/CODEOWNERS
> split mobile code owners

- src/docs/product/sentry-basics/metrics/index.mdx
Renamed Custom Performance Measurement to Custom Performance Metric
> Renamed Custom Performance Measurement to Custom Performance Metric

- src/docs/product/dashboards/custom-dashboards/index.mdx
Page filters and the new release filter on dashboard
can now be saved.
> feat(dashboards): Add EA docs for Dashboard Filters

- src/platforms/dotnet/common/troubleshooting.mdx
> dotnet note how to debug large payload

- src/platforms/unity/configuration/il2cpp.mdx
* remove additional note on symbol upload
* remove reference to Sentry CLI
> unity: clarify symbol upload

- src/includes/enriching-events/attach-screenshots/javascript.electron.mdx
- src/platforms/common/enriching-events/screenshots.mdx
Related to:
https://github.com/getsentry/sentry-electron/issues/521
> feat(electron): Add screenshot docs

- src/platforms/common/data-management/debug-files/index.mdx
> show dif page for dotnet

- src/docs/product/integrations/data-visualization/grafana.mdx
- src/docs/product/integrations/data-visualization/segment/index.mdx
- src/docs/product/integrations/deployment/vercel/index.mdx
- src/docs/product/integrations/feature-flag/split/index.mdx
- src/docs/product/integrations/index.mdx
- src/docs/product/integrations/issue-tracking/index.mdx
- src/docs/product/integrations/issue-tracking/sourcegraph.mdx
- src/docs/product/integrations/notification-incidents/spikesh/index.mdx
- src/docs/product/integrations/session-replay/fullstory.mdx
- src/docs/product/integrations/session-replay/openreplay.mdx
- src/docs/product/integrations/troubleshooting.mdx
- src/docs/product/releases/setup/release-automation/bitbucket-pipelines/index.mdx
- src/docs/product/releases/setup/release-automation/github-actions/index.mdx
- src/docs/product/releases/setup/release-automation/netlify/index.mdx
This PR:
Fixes capitalization of Sourcegraph
Includes various wording improvements
Includes various style fixes
> style and wording fixes

- src/includes/getting-started-config/javascript.remix.mdx
Documents: https://github.com/getsentry/sentry-javascript/pull/5524
> Add manual Express wrapper example.

- src/components/banner.tsx
> updated banner back to DEX

- src/includes/getting-started-config/javascript.remix.mdx
Adding a version note as per review: https://github.com/getsentry/sentry-docs/pull/5425#discussion_r946789444
> Add version note for Remix manual Express wrapper.

- src/docs/clients/node/typescript.mdx
- src/platforms/node/common/typescript.mdx
Resolves https://github.com/getsentry/sentry-docs/issues/5426
> Fix type declaration in typescript event frame configuration

- src/docs/product/accounts/quotas/index.mdx
This PR includes fixes for:
- a few typos
- missing punctuation
- extra punctuation
- a missing word
> Fix typos and tweak punctuation

- src/platforms/python/guides/asgi/index.mdx
Added information about our specific integrations for various ASGI frameworks to the ASGI guide. So people looking for a ASGI integration see that we have specific integrations for their ASGI based framework.
> Python ASGI integration guide update

- src/docs/product/accounts/pricing.mdx
Adds missing states where sales tax is collected
> add more states to tax section

- src/platforms/python/guides/fastapi/index.mdx
- src/platforms/python/guides/starlette/index.mdx
- src/wizard/python/fastapi.md
- src/wizard/python/starlette.md
Because the integrations are now auto enabled.
> Updated Starlette/FastAPI setup documentation

- src/platforms/react-native/manual-setup/hermes.mdx
Move note to make it easier to find
> move note for using RN v0.69+

- src/platforms/react-native/manual-setup/codepush.mdx
Reason: https://stackoverflow.com/questions/73273418/how-to-wrap-app-component-while-using-sentry-with-codepush-react-native
> Mention Sentry wrap and code push for RN

- src/docs/product/dashboards/custom-dashboards/index.mdx
> docs: Remove the EA note for dashboard filters

- src/docs/product/data-management-settings/server-side-sampling/current-limitations.mdx
- src/docs/product/data-management-settings/server-side-sampling/getting-started.mdx
- src/includes/sampling-supported-sdks.mdx
Replace two identical lists with an include to maintain parity
> add include for dynamic sampling supported sdks

- src/platform-includes/getting-started-primer/python.django.mdx
> fix(django): Bump minimum supported django version to 1.8

- src/includes/alpha-note.mdx
- src/includes/beta-note.mdx
- src/includes/preview-note.mdx
Adds generic alpha, beta, and preview notes as includes
> add generic alpha, beta, and preview notes

- src/platforms/apple/troubleshooting.mdx
Added information on how to Troubleshoot crash report duplications.
> feat(apple): Troubleshooting duplicated crash report

- src/platforms/common/configuration/options.mdx
Resolves: https://github.com/getsentry/sentry-docs/issues/5508
> fix(unity) clarify offline default value

- src/platforms/common/configuration/options.mdx
> Update default cache path docs for MAUI

- src/platform-includes/enriching-events/import/react-native.mdx
- src/platforms/common/enriching-events/attachments/index.mdx
- https://github.com/getsentry/sentry-react-native/pull/2463
> feat(react-native): Add Attachments

- src/platform-includes/debug-symbols-apple/_default.mdx
Came up in https://github.com/getsentry/sentry/issues/38198.
> feat(apple): Mention where to view dSYMs

- src/platform-includes/configuration/auto-session-tracking/javascript.electron.mdx
> Fix minor typo

- src/platforms/python/guides/sanic/index.mdx
Update the explicit enumeration of known versions that work with the SDK.
> Update known supported Sanic versions

- src/docs/clients/csharp/index.mdx
- src/platform-includes/getting-started-primer/dotnet.mdx
- src/platforms/dotnet/common/compatibility.mdx
Should help with #5534 for at least some of the search results.
Also updated the compatibility info to match current.
> Update .NET info

- src/platforms/flutter/troubleshooting.mdx
Depends on https://github.com/getsentry/publish/issues/1382
> Flutter iOS symbolication

- src/wizard/apple/ios.md
Update the latest experimental features.
> feat(apple): Wizard update experimental features

- src/platform-includes/getting-started-config/apple.mdx
Mention experimental features in getting started to reach more users.
> feat(apple): Experimental feats in getting started

- src/platforms/react-native/troubleshooting.mdx
Information for people who encounter this issue https://github.com/getsentry/sentry-react-native/issues/2442
> Add RN 0.60.3 failing build information

- src/platform-includes/enriching-events/set-user/flutter.mdx
- src/platform-includes/sensitive-data/set-user/dart.mdx
Fixes https://github.com/getsentry/sentry-docs/issues/5514
> Fix set user for flutter

- src/docs/product/integrations/deployment/vercel/index.mdx
This updates the description for Vercel in the docs.
> Update Vercel docs.

- src/includes/sampling-supported-sdks.mdx
https://github.com/getsentry/sentry-dart/pull/1004
> Adds Dart and Flutter SDK to supported SDKs for DS

- src/platform-includes/enriching-events/user-feedback/sdk-api-example/react-native.mdx
- src/platform-includes/getting-started-primer/react-native.mdx
- src/platforms/common/enriching-events/user-feedback.mdx
Add userFeedback and fix missing features on the sdk getting started page
> feat(react-native): Add UserFeedback

- src/docs/product/integrations/source-code-mgmt/github/index.mdx
Related
https://github.com/getsentry/sentry/pull/39276
> Now members can also add repositories

- src/platform-includes/getting-started-config/apple.mdx
- src/platforms/apple/common/performance/instrumentation/automatic-instrumentation.mdx
- src/wizard/apple/ios.md
Both features will GA in the next release.
Only merge after releasing https://github.com/getsentry/sentry-cocoa/pull/2212 and https://github.com/getsentry/sentry-cocoa/pull/2213.
> feat(apple): Core data and file IO tracking GA

- src/platforms/android/configuration/integrations/room-and-sqlite.mdx
Closes https://github.com/getsentry/sentry-android-gradle-plugin/issues/349
> chore(android): Clarify SQLite instrumentation PII risks

- src/platforms/common/enriching-events/identify-user.mdx
It already exists in develop docs, see
https://github.com/getsentry/develop/pull/685.
Only merge after releasing https://github.com/getsentry/sentry-cocoa/pull/2234.
> feat: Add user segment

- src/platform-includes/getting-started-primer/apple.macos.mdx
- src/platform-includes/getting-started-primer/apple.mdx
Add start-up crashes to the list of features.
Only merge after releasing https://github.com/getsentry/sentry-cocoa/pull/2220.
> feat(apple): Start-up crashes

- src/docs/product/data-management-settings/dynamic-sampling/current-limitations.mdx
Updates link to new DS discord channel
> update discord channel link

- gatsby-ssr.js
Reverts getsentry/sentry-docs#5587
> Revert "feat: adds gtm script"

- src/platforms/react-native/manual-setup/native-init.mdx
https://github.com/getsentry/sentry-react-native/pull/2517
Reason https://github.com/getsentry/sentry-cocoa/issues/2262
> Fix manual init with auto performance for RN and iOS

- src/includes/sampling-supported-sdks.mdx
Sentry .NET SDK 3.22.0 - now with Dynamic Sampling!
New and improved!
> Add .NET to DS docs

- src/includes/sampling-supported-sdks.mdx
Updates android compatible version for dynamic sampling 6.5.0 or higher
> fix(sampling): Update android supported version to 6.5.0

- src/platform-includes/performance/automatic-performance-metrics/android.mdx
> ref(android): Use platform link for perf metrics

- gatsby-ssr.js
Updated GTM so the consent banner shows up correctly and the robot shouldn't appear.
> feat: adds gtm script v2

- src/platforms/flutter/troubleshooting.mdx
- src/platforms/flutter/upload-debug.mdx
> Mention obfuscate debug symbols for Flutter

- .github/workflows/test.yml
Checking if this works to fix volta on builds.
> ref(tools): Fix volta on docs

- src/platforms/unity/troubleshooting.mdx
@bitsandfoxes can you please confirm this is resolved?
> chore(unity): remove outdated troubleshooting section

- src/platforms/common/configuration/options.mdx
Add missing docs for options dist. Copied from
https://develop.sentry.dev/sdk/event-payloads/#optional-attributes.
> feat: Add options dist

- src/platforms/python/guides/pyspark/index.mdx
Updated note about the SDK and Spark compatibility; added Spark 3.1 to the supported versions.
> Added Spark 3.1 compatibility note.

- src/platforms/unity/troubleshooting.mdx
closes [sentry-unity#884](https://github.com/getsentry/sentry-unity/issues/884)
> unity: add known limiation

- src/platforms/php/guides/symfony/configuration/symfony-options.mdx
I took the code from the [package](https://github.com/getsentry/sentry-symfony/blob/master/UPGRADE-4.0.md) and adapted it.
> Symfony: Explain how to ignore some exceptions

- src/docs/product/issues/issue-details/performance-issues/n-one-queries.mdx
should be `select_related` instead
> fix(perf-issues): `selected_related` typo

- src/docs/product/integrations/source-code-mgmt/azure-devops/index.mdx
- src/docs/product/integrations/source-code-mgmt/bitbucket/index.mdx
- src/docs/product/integrations/source-code-mgmt/github/index.mdx
fixes https://getsentry.atlassian.net/browse/WOR-2247
> fix(integrations): Add `fixes <SHORT-ID>` pitfalls with squashed commits

- src/components/banner.tsx
> updated copy for docs banner

- src/docs/contributing/pages/frontmatter.mdx
Also adds an example of a component for in the draft property description
> clarify how notoc property works

- src/platform-includes/performance/automatic-performance-metrics/flutter.mdx
- src/platforms/common/performance/instrumentation/performance-metrics.mdx
> Auto perf metrics for Flutter

- src/platforms/dotnet/guides/maui/index.mdx
Adding some more details about our .NET MAUI offering.
> Update .NET MAUI info

- src/platforms/dotnet/guides/uwp/index.mdx
> Update UWP guidance

- src/platform-includes/getting-started-install/react-native.mdx
- src/platforms/react-native/uninstall.mdx
Context
- https://github.com/getsentry/sentry-react-native/issues/1139
> Add React-Native SDK uninstall steps

- src/platforms/android/configuration/integrations/fragment.mdx
Documentation change related to https://github.com/getsentry/sentry-java/pull/2299
> Added documentation for customizing fragment lifecycle breadcrumbs

- src/platforms/index.mdx
Updated to include link to `sentry-clj`
> Update index.mdx to include sentry-clj

- src/components/banner.tsx
> post the cloudflare workshop banner

- src/platforms/go/common/configuration/options.mdx
Updating the Go `Client.Options` that were recently added.
> Update Go client options

- src/platforms/php/guides/laravel/index.mdx
> Update Laravel error handler

- src/platform-includes/performance/traces-sampler-as-filter/ruby.mdx
- src/platform-includes/performance/traces-sampler-as-sampler/ruby.mdx
fixes https://github.com/getsentry/sentry-ruby/issues/1938
> fix(ruby): Fix traces_sampler examples to use new op

- src/platforms/node/common/configuration/integrations/default-integrations.mdx
These [have been added](https://github.com/getsentry/sentry-javascript/pull/6191) and already made it into a release.
> Add new tracing options for node `Http` integration

- src/docs/product/data-management-settings/event-grouping/fingerprint-rules.mdx
Closes https://github.com/getsentry/sentry-docs/issues/5825.
> feat(grouping): Note about fingerprint rule precedence

- src/components/platformSidebar.tsx
- src/platforms/common/performance/index.mdx
Change _Set Up_ to _Set Up Performance_ so that it's clearer what this page is when it's displayed in a PageGrid
> update page title and remove old notes

- src/platforms/python/guides/fastapi/index.mdx
Code example is missing imports
> Add import to code example

- src/platforms/php/guides/symfony/index.mdx
> minor copy update to match php lingo

- src/platforms/flutter/common/performance/instrumentation/automatic-instrumentation.mdx
Closes https://github.com/getsentry/sentry-docs/issues/5419
> Routers first in the automatic inst page for Flutter

- src/platform-includes/sourcemaps/upload/systemjs/javascript.mdx
> typo(sourcemaps): fix typo

- src/platforms/common/data-management/sensitive-data/index.mdx
Fixes https://github.com/getsentry/sentry-docs/issues/5876
> Add missing platform identifier for `send-default-pii`

- src/platforms/python/common/configuration/integrations/index.mdx
- vercel.json
Adds redirects for pages removed on #5591
> add redirects for deleted django and flask integration pages

- src/platforms/android/configuration/manual-init.mdx
It's not clear where to write this piece of code. So, I have mentioned the file name of the Java file.
Please confirm the file name is correct or not
> feat(Android): Improve manual init docs

- src/platforms/common/enriching-events/identify-user.mdx
Fixes https://github.com/getsentry/sentry-docs/issues/5901
> Clarify how IPs are collected for JS SDKs

- .github/CODEOWNERS
> Update OWNERS file with session-replay related folders

- src/docs/product/integrations/issue-tracking/jira/index.mdx
In order to match the code:
https://github.com/getsentry/sentry/blob/a94d5af633853f6682c01667b33d9151f1a0882e/src/sentry/web/urls.py#L759
> Substitue jira_server for jira-server

- src/components/banner.tsx
> removed cloudflare workshop banner

- src/docs/product/sentry-basics/key-terms.mdx
Update order to be alphabetical.
> changed page to alphabetical order

- src/docs/product/crons/getting-started.mdx
Fixes: https://github.com/getsentry/sentry-docs/issues/5993
> feat(crons): Add curl example alongside CLI/python

- src/docs/product/crons/index.mdx
> Fix typo/missed word

- src/docs/product/integrations/session-replay/index.mdx
Resolves https://github.com/getsentry/sentry-docs/issues/5997
> replay: note on 3rdparty

- src/docs/product/crons/alerts.mdx
> ref(crons): Correct typo on alerts page

- src/docs/product/issues/issue-details/performance-issues/n-one-queries.mdx
Based on some feedback, more detailed explanations:
- Clarify span truncation
- Explain the source span
- Add note about fingerprinting
> feat(perf-issues): Clarify N+1 Queries issues

- Makefile
- src/css/_includes/development-api.scss
- src/templates/apiPage.tsx
- Add make preview-api-docs helper
- Improve readability for URL on endpoint details
> feat: Improvements for API docs

- src/platform-includes/configuration/before-send-fingerprint/python.mdx
> fix(python): Fix before_send example

- src/platform-includes/enriching-events/attach-viewhierarchy/flutter.mdx
- src/platform-includes/getting-started-primer/flutter.mdx
- src/platforms/common/configuration/options.mdx
- src/platforms/common/enriching-events/viewhierarchy.mdx
Depends on https://github.com/getsentry/sentry-dart/pull/1189
> View hierarchy docs for Flutter

- src/platforms/common/enriching-events/viewhierarchy.mdx
> Fix typo view hierarchy

- src/platforms/apple/common/migration.mdx
@philipphofmann probably check your README and releases as well.
> Fix enableWatchdogTerminationTracking typo

- src/components/banner.tsx
> turning on the banner to promote the replay ama

- src/docs/product/releases/release-details.mdx
- src/docs/product/sentry-basics/enrich-data/index.mdx
- src/platforms/common/configuration/releases.mdx
- src/platforms/native/configuration/backends/crashpad.mdx
Relates to: https://github.com/getsentry/sentry/discussions/42716
> feat(session): Remove session duration

- src/platforms/dotnet/guides/maui/index.mdx
- src/wizard/dotnet/maui.md
- Drop pre-release section
- Use regular version parameters instead of pre-release
- Update code sample
> Update MAUI docs

- src/platforms/javascript/guides/nextjs/manual-setup.mdx
Resolves https://github.com/getsentry/sentry-docs/issues/6080
> Add Next.js edge runtime and middleware documentation

- src/platforms/react-native/troubleshooting.mdx
- https://github.com/getsentry/sentry-react-native/issues/2721
> add expo-dev-client transactions fix to troubleshooting

- src/platforms/javascript/common/session-replay/index.mdx
> feat(replay): Fix outdated max session life

- src/includes/beta-note-opentelemetry.mdx
> Include PM email until we get an OTEL specific one

- src/platforms/javascript/common/troubleshooting/session-replay.mdx
Common Replay specific troubleshooting scenarios.
Links to
* https://github.com/getsentry/sentry-javascript/issues/6519
To be updated once support is added ^
I copied some [from the FAQ](https://help.sentry.io/product-features/other/what-is-session-replay/)
Resolves https://github.com/getsentry/sentry-docs/issues/5970
> replay: troubleshooting docs

- src/includes/beta-note-opentelemetry.mdx
- src/platforms/java/common/performance/instrumentation/opentelemetry.mdx
> updating with otel google group

- src/platforms/dotnet/guides/maui/index.mdx
> dotnet(maui): line numbers supported

- src/platforms/apple/common/configuration/http-client-errors.mdx
- src/platforms/apple/common/migration.mdx
- src/platforms/apple/common/performance/instrumentation/automatic-instrumentation.mdx
Update docs to reflect properly which features are enabled by default since 8.0.0.
> fix(apple): Default enabled features for 8.0.0

- src/platforms/apple/common/configuration/app-hangs.mdx
Explain changes in the algorithm of detecting app hangs with v 7.24.0
> feat(apple): Explain accuracy of app hangs

- src/docs/product/crons/getting-started.mdx
> ref(crons): Document latest functionality for editing checkin status

- src/docs/product/session-replay/index.mdx
> replay: remove waitlist - open beta

- src/platform-includes/sourcemaps/upload/vite/javascript.mdx
https://github.com/getsentry/sentry-docs/pull/6114
> fix: vite configuration for sourcemap

- src/docs/product/accounts/sso/okta-sso/okta-scim.mdx
Remove beta tag as we have released this feature for everyone!
> fix(scim): remove beta tag for SCIM for roles

- src/platform-includes/session-replay/install/javascript.capacitor.mdx
- src/platform-includes/session-replay/setup/javascript.capacitor.mdx
- src/platforms/javascript/common/session-replay/configuration.mdx
- src/platforms/javascript/common/session-replay/index.mdx
- src/platforms/javascript/common/session-replay/privacy.mdx
- src/wizard/javascript/replay-onboarding/capacitor/1.install.md
- src/wizard/javascript/replay-onboarding/capacitor/2.configure.md
Docs for Session replay for capacitor
> replay: capacitor

- src/docs/product/session-replay/index.mdx
- src/includes/beta-note-session-replay.mdx
> replay: remove email

- src/platforms/flutter/troubleshooting.mdx
https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.7.0
> Update min Flutter version for iOS obfuscation support

- src/components/banner.tsx
updating the banner with info for the new ama. 
> swap SR for JPC banner

- src/platform-includes/performance/opentelemetry-setup/with-java-agent/without-auto-init/java.mdx
- src/platform-includes/performance/opentelemetry-setup/without-java-agent/java.mdx
- src/platform-includes/performance/opentelemetry-setup/without-java-agent/java.spring-boot.mdx
Fixes #6125 by adding Kotlin sampes to OTEL docs.
> Add Kotlin samples for OTEL docs

- src/wizard/javascript/replay-onboarding/nextjs/2.configure.md
Just a small adjustment because we recently added that config file.
> Add hint about edge config in combination with Replay integration

- src/platforms/common/index.mdx
> updates to next installation

- src/docs/product/sentry-basics/migration/index.mdx
> Remove `\` before $

- src/platform-includes/getting-started-install/javascript.nextjs.mdx
Add faster way for new Sentry users to set up a Sentry account and set up Sentry on their Next.js project at the same time.
> updating nextjs config

- src/platforms/react-native/migration.mdx
- https://github.com/getsentry/sentry-react-native/issues/2722#issuecomment-1408891894
> Fix migration scripts RN SDK 4.8 to 4.9

- src/platforms/flutter/common/performance/instrumentation/automatic-instrumentation.mdx
Reason: https://github.com/getsentry/sentry-dart/issues/1251#issuecomment-1410426395
> Update docs with no child logic in Flutter

- src/docs/product/data-management-settings/scrubbing/server-side-scrubbing.mdx
related https://github.com/getsentry/relay/pull/1789
> ref(pii): update the docs on PII scribbing and objects removal

- src/platforms/dotnet/common/configuration/msbuild.mdx
Further improvements to the .NET MSBuild docs page.
> Update MSBuild docs

- src/platform-includes/performance/always-inherit-sampling-decision/go.mdx
- src/platform-includes/performance/configure-sample-rate/go.mdx
- src/platform-includes/performance/custom-sampling-context/go.mdx
- src/platform-includes/performance/traces-sampler-as-filter/go.mdx
- src/platform-includes/performance/traces-sampler-as-sampler/go.mdx
Closes https://github.com/getsentry/sentry-go/issues/551
> Update Go TracesSampler examples

- src/platforms/common/data-management/debug-files/symbol-servers.mdx
Fixes https://github.com/getsentry/sentry/issues/43767.
> feat: Add information about debuginfod, nuget, ppdbs

- src/includes/beta-note-session-replay.mdx
- src/platform-includes/session-replay/install/javascript.electron.mdx
- src/platform-includes/session-replay/pre-requisites/javascript.capacitor.mdx
- src/platform-includes/session-replay/pre-requisites/javascript.electron.mdx
- src/platform-includes/session-replay/pre-requisites/javascript.mdx
- src/platform-includes/session-replay/setup/javascript.electron.mdx
- src/platforms/javascript/common/session-replay/index.mdx
- src/platforms/javascript/common/session-replay/privacy.mdx
> feat(electron): Session Replay for Electron

- src/platform-includes/session-replay/pre-requisites/javascript.electron.mdx
Fixes a mistake I made on a PR suggestion on: https://github.com/getsentry/sentry-docs/pull/6209
> fix(electron): min replay version

- src/docs/product/issues/issue-details/performance-issues/index.mdx
- src/docs/product/issues/issue-details/performance-issues/n-one-api-calls.mdx
- Explain span requirements
- Fix capitalization
> feat(n1-api-calls): Documentation clarifications

- src/platform-includes/enriching-events/add-attachment/python.mdx
- src/platforms/common/enriching-events/attachments/index.mdx
> feat(python): Add attachments docs

- src/includes/opentelemetry-available.mdx
- src/platforms/common/performance/index.mdx
> Link to OTEL docs from Set Up Performance

- src/platforms/common/performance/instrumentation/opentelemetry.mdx
Link to config page from OTEL page
> Convert filtering section to additional config

- src/platform-includes/enriching-events/attach-viewhierarchy/react-native.mdx
- src/platform-includes/getting-started-primer/react-native.mdx
- src/platforms/common/enriching-events/viewhierarchy.mdx
- https://github.com/getsentry/sentry-react-native/pull/2708
> Add view hierarchy docs for react native

- src/platforms/dotnet/guides/winforms/index.mdx
> Fix c# syntax error in winforms guide

- src/docs/product/accounts/pricing.mdx
Reverts getsentry/sentry-docs#6264
> Revert "Update pricing.mdx"

- src/docs/product/integrations/index.mdx
Add link to Vanta integration docs on Integrations index
> add Vanta docs to integration index

- package.json
- src/components/search.tsx
- yarn.lock
Integrate click analytics with algolia so we can get some info on queries and tune them
> feat(docs): add search analytics

- src/docs/product/accounts/quotas/index.mdx
> Update index with replay quota

- src/docs/product/accounts/quotas/manage-event-stream-guide.mdx
On-demand description was lacking a reference to the replay category
> add replays to per category description

- src/platform-includes/configuration/before-send-transaction/php.symfony.mdx
- src/platforms/common/configuration/filtering.mdx
- src/platforms/common/configuration/options.mdx
- src/platforms/php/guides/symfony/configuration/symfony-options.mdx
- src/platforms/php/guides/symfony/index.mdx
- src/wizard/php/symfony.md
Update the docs to reflect changes in [Symfony SDK v4.6.0](https://github.com/getsentry/sentry-symfony/releases/tag/4.6.0).
> Symfony v4.6.0

- src/docs/product/issues/issue-details/performance-issues/index.mdx
You can't search Discover for issues.
> Update description to remove Discover

- src/docs/product/issues/issue-details/performance-issues/main-thread-io.mdx
- Removes the EA note from file io, planning to GA it once this merges: https://github.com/getsentry/getsentry/pull/9610/files
> Remove the EA note from file IO

- src/platform-includes/getting-started-install/react-native.mdx
> Fix RN SDK v4 steps link

- src/platform-includes/enriching-events/attach-screenshots/unity.mdx
Resolves https://github.com/getsentry/sentry-unity/issues/1161
> fix(unity): PII in screenshots

- src/platforms/javascript/common/session-replay/index.mdx
Some of the language felt dated and a little wordy.
The PII comments are better covered in our Privacy FAQ: https://docs.sentry.io/product/session-replay/protecting-user-privacy/
> feat(replays): Tweak SDK config index page language

- src/wizard/javascript/react.md
Reverts getsentry/sentry-docs#6355
Some unforeseen problems...
> Revert "[Modified] React Wizard"

- src/components/banner.tsx
> hide the banner

- src/platforms/node/common/profiling/index.mdx
Add install step to profiling node
> fix(profiling): add installation to profiling-node

- src/wizard/apple/index.md
Modified apple wizard to use `enableTracing` option.
> feat(apple): Use `enableTracing` in wizard

- src/platforms/android/migration.mdx
Migration docs for https://github.com/getsentry/sentry-java/pull/2578
> chore(android): Add migration docs for 6.15.0

- src/platform-includes/getting-started-primer/javascript.nextjs.mdx
let's add to docs that we support edge and middleware, validate which products are available. (errors, performances, and any caveats to that - missing breadcrumps or wonky stack traces).
It is all automatic? No user config only need version x.xx with the new config file?
> Edge and middleware

- src/docs/product/accounts/early-adopter.mdx
- src/docs/product/issues/issue-details/performance-issues/index.mdx
Update the table with new types, remove EA label
> Update Performance Issue Types

- src/platform-includes/getting-started-primer/unity.mdx
> Update unity.mdx to fix some spelling

- src/platforms/flutter/upload-debug.mdx
Relates to https://github.com/getsentry/sentry-dart/issues/1281
> Sentry Dart plugin is GA

- src/wizard/javascript/react.md
- Each step is broken down
- Describes what the instructions will set up
> Chore(wizard)react

- src/platforms/dotnet/common/configuration/msbuild.mdx
Update docs to match https://github.com/getsentry/sentry-dotnet/pull/2216
> Improve .NET MSBuild advice

- src/platform-includes/debug-symbols-apple/_default.mdx
Fixes https://github.com/getsentry/sentry-docs/issues/6415
> Fix include sources command for iOS

- src/platforms/javascript/common/configuration/sentry-testkit/index.mdx
Sentry-testkit project was moved to original author personal repo, and now the docs should be updated respectivly.
> docs(javascript): update sentry-testkit page

- src/platforms/common/data-management/debug-files/symbol-servers.mdx
I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.
> Fix symsorter link in "Symbol Servers"

- src/docs/product/accounts/getting-started/index.mdx
- src/docs/product/issues/suspect-commits/index.mdx
> feat(commit-context): Add documentation about commit context fallback

- src/docs/product/data-management-settings/scrubbing/advanced-datascrubbing.mdx
- src/platform-includes/configuration/auto-session-tracking/flutter.mdx
- src/platform-includes/configuration/before-breadcrumb-hint/dart.mdx
- src/platform-includes/configuration/before-send-fingerprint/dart.mdx
- src/platform-includes/configuration/before-send-hint/dart.mdx
- src/platform-includes/configuration/before-send/dart.mdx
- src/platform-includes/enriching-events/breadcrumbs/before-breadcrumb/dart.mdx
- src/platform-includes/enriching-events/scopes/configure-scope/dart.mdx
- src/platform-includes/getting-started-primer/flutter.mdx
- src/platform-includes/performance/distributed-tracing/dart.mdx
- src/platform-includes/set-fingerprint/basic/dart.mdx
- src/platform-includes/set-fingerprint/database-connection/dart.mdx
- src/platform-includes/set-fingerprint/rpc/dart.mdx
- src/platforms/android/common/performance/instrumentation/automatic-instrumentation.mdx
- src/platforms/common/configuration/options.mdx
- src/platforms/common/enriching-events/viewhierarchy.mdx
- src/platforms/dart/common/performance/instrumentation/automatic-instrumentation.mdx
- src/platforms/dart/configuration/integrations/dio.mdx
- src/platforms/dart/configuration/integrations/file.mdx
- src/platforms/dart/configuration/integrations/http-integration.mdx
- src/platforms/dart/migration.mdx
- src/platforms/flutter/common/configuration/integrations/user-interaction-instrumentation.mdx
- src/platforms/flutter/common/performance/instrumentation/automatic-instrumentation.mdx
- src/platforms/flutter/migration.mdx
Doc changes for https://github.com/getsentry/sentry-dart/releases/tag/7.0.0-rc.2
> Flutter 7 GA

- src/platform-includes/getting-started-config/dart.mdx
- src/platform-includes/getting-started-config/flutter.mdx
- src/wizard/dart/index.md
- src/wizard/flutter/index.md
Fix https://github.com/getsentry/sentry-docs/issues/5734
> Point out tracesSampleRate in Getting Started for Dart and Flutter

- src/docs/clients/javascript/sourcemaps.mdx
> Update broken sourcemaps blog link

- src/docs/product/accounts/quotas/manage-event-stream-guide.mdx
non-paid accounts have access to grace period. 
This PR changes the grace period section of the quota management docs to reflect this
> adjust qualifications for grace period

- src/platform-includes/getting-started-primer/flutter.mdx
- src/platforms/android/configuration/integrations/file-io.mdx
- src/platforms/android/configuration/integrations/fragment.mdx
- src/platforms/android/configuration/integrations/room-and-sqlite.mdx
- src/platforms/dart/common/performance/instrumentation/automatic-instrumentation.mdx
- src/platforms/dart/configuration/integrations/file.mdx
- src/platforms/flutter/common/configuration/integrations/sqflite-instrumentation.mdx
- src/platforms/flutter/common/performance/instrumentation/automatic-instrumentation.mdx
Relates to https://github.com/getsentry/sentry-dart/releases/tag/7.2.0
> sqflite integration for Flutter

- src/platform-includes/getting-started-config/python.flask.mdx
other framework specific snippetes reflect the SDKs auto-detection for enabling integrations. Updating Flask to do the same
https://docs.sentry.io/platforms/python/guides/flask/
> reflect auto-detection

- bin/lint-docs.ts
- src/gatsby/onPostBuild.ts
- src/wizard/javascript/react/index.md
- src/wizard/javascript/react/with-error-monitoring-and-performance.md
- src/wizard/javascript/react/with-error-monitoring-and-replay.md
- src/wizard/javascript/react/with-error-monitoring-performance-and-replay.md
- src/wizard/javascript/react/with-error-monitoring.md
Add different react document versions that will be used according to the user's selection in the new onboarding.
**For more details:** 
https://www.figma.com/file/FS0IXznUH0FfIlRD0EyY5O/Specs%3A-Onboarding-v3?node-id=40-1304&t=3TZVm319SNZw3H1P-0
> feat(wizard): Add react wizard variants - [TET-774]

- src/platforms/react-native/troubleshooting.mdx
- https://github.com/getsentry/sentry-react-native/issues/2856
> Add info about xcode cloud source maps uploads

- src/platform-includes/configuration/before-send-transaction/python.mdx
Replaces https://github.com/getsentry/sentry-docs/pull/6364
> Improve `before_send_transaction`docs

- src/docs/product/profiling/getting-started.mdx
- src/docs/product/profiling/index.mdx
- src/platforms/common/profiling/index.mdx
- src/platforms/php/common/profiling/index.mdx
- src/wizard/php/profiling-onboarding/php/0.alert.md
- src/wizard/php/profiling-onboarding/php/1.install.md
- src/wizard/php/profiling-onboarding/php/2.configure-performance.md
- src/wizard/php/profiling-onboarding/php/3.configure-profiling.md
Might need some changes on Sentry to make the wizard work.
Closes https://github.com/getsentry/team-profiling/issues/206
> PHP profiling

- src/platform-includes/getting-started-primer/react-native.mdx
- src/platforms/react-native/performance/instrumentation/automatic-instrumentation.mdx
- src/platforms/react-native/performance/instrumentation/ui-instrumentation.mdx
- src/platforms/react-native/performance/instrumentation/user-interaction-instrumentation.mdx
- https://github.com/getsentry/sentry-react-native/pull/2835
- https://github.com/getsentry/sentry-react-native/pull/2865
> feat(rn): Add UI Instrumentation

- src/components/banner.tsx
update banner: someone needs to add bitly &/or update text if there is a better marketing pitch
> CodeCov & Sentry AMA Banner

- src/docs/product/crons/getting-started/cli.mdx
- src/docs/product/crons/getting-started/index.mdx
- src/docs/product/crons/index.mdx
- src/platforms/common/crons/index.mdx
- fixes incorrect example for heartbeat request
- adds new configuration instructions for Crons CLI
> Additional Crons docs improvements

- src/platforms/common/crons/index.mdx
Fixes incorrect key for a monitor config
> update incorrect monitor config key

- src/platforms/common/profiling/index.mdx
- src/platforms/node/common/profiling/index.mdx
- src/wizard/node/profiling-onboarding/node/3.configure-profiling.md
The import order is no longer required
> fix(profiling): update install instructions

- src/docs/product/accounts/quotas/index.mdx
Make the quota management page easier to read and understand.
> Update quota management page

- src/platforms/common/configuration/options.mdx
> fix: update typo fuction -> function

- src/platforms/apple/troubleshooting.mdx
Added troubleshooting informations for projects using Tuist as package manager.
The problem was described [here](https://github.com/getsentry/sentry-cocoa/issues/2556).
> feat(apple): Troubleshooting for Tuist

- src/wizard/apple/index.md
- src/wizard/apple/ios.md
- src/wizard/apple/macos.md
Point out all ways to install the SDK in the wizard.
> feat(apple): Show all install methods in wizard

- src/platforms/node/common/configuration/integrations/pluggable-integrations.mdx
See: https://github.com/getsentry/sentry-javascript/releases/tag/7.46.0
> fix(node): Add note about Undici versions

- sentry.config.js
To test DOM Element Search for Text Content on Sentry org. Requires updating SDK version - min 7.44.2
> Unmask Platform Links on Docs Site

- src/docs/product/crons/getting-started/cli.mdx
> Update alert wording in Crons CLI

- src/platforms/java/guides/jul/usage/advanced-usage.mdx
Fixes https://github.com/getsentry/sentry-docs/issues/6539
> Change link for JUL MDC and add dependency

- src/platform-includes/sourcemaps/overview/javascript.remix.mdx
closes https://github.com/getsentry/sentry-docs/issues/6582
> ref(js): Fix remix source maps deletion command

- src/docs/product/integrations/index.mdx
- src/docs/product/integrations/notification-incidents/index.mdx
- src/docs/product/integrations/notification-incidents/signl4/index.mdx
> create index.mdx for SIGNL4 Integration

- src/docs/product/user-feedback/index.mdx
Addresses points from: https://github.com/getsentry/sentry-docs/pull/6471/files
> user feedback docs

- src/platforms/python/common/configuration/integrations/grpc.mdx
- src/platforms/python/common/configuration/integrations/socket.mdx
documentation for changes in [this](https://github.com/getsentry/sentry-python/pull/1911) pull request on python sdk
> Add socket and grpc integration docs

- src/platforms/node/common/profiling/index.mdx
- src/wizard/node/profiling-onboarding/javascript-nextjs/1.install.md
- src/wizard/node/profiling-onboarding/node/1.install.md
> fix(profiling): change min sdk requirement

- src/platforms/node/common/profiling/index.mdx
- src/wizard/node/profiling-onboarding/javascript-nextjs/0.alert.md
- src/wizard/node/profiling-onboarding/javascript-nextjs/1.install.md
- src/wizard/node/profiling-onboarding/javascript-nextjs/2.configure-performance.md
- src/wizard/node/profiling-onboarding/javascript-nextjs/3.configure-profiling.md
- src/wizard/node/profiling-onboarding/node/1.install.md
Add nextjs docs for onboarding wizard
> feat(profiling): add nextjs docss

- src/platforms/node/common/configuration/integrations/default-integrations.mdx
ref https://github.com/getsentry/sentry-javascript/issues/7697
cc @timfish
> fix(node): Say that Node LocalVariables only works with Node  18+

- package.json
- scripts/remove-preview-deployments.ts
- yarn.lock
ref: https://github.com/getsentry/sentry-docs/issues/6588
To try to respect Vercel rate limits, this script is pretty slow. I will leave it overnight to completely delete all the previews.
Pushing this up so @shanamatthews if you need to run again in the future you can!
> feat(docs): Add preview delete script

- src/css/_includes/code-blocks.scss
- src/css/_includes/type.scss
- src/gatsby/config.ts
> add margin-bottom to images and code blocks

- src/platform-includes/getting-started-config/apple.mdx
- src/platforms/apple/common/performance/instrumentation/automatic-instrumentation.mdx
Change a few wrong enablePreWarmedAppStartTracking to enablePreWarmedAppStartTracing.
> fix(apple): enablePreWarmedAppStartTracing

- src/docs/product/accounts/pricing.mdx
> Add pricing note

- src/docs/product/accounts/pricing.mdx
> pricing language tweak

- src/platforms/apple/troubleshooting.mdx
Adding an explanation on what to do if the user sees this error: `[SentryFileManager:439] Failed to write data to path`
> feat(apple): Troubleshooting "Failed to write data to path"

- src/platforms/react-native/migration.mdx
> Add related JS SDK migration links to RN SDK migration guide

- src/docs/product/sentry-basics/search/searchable-properties.mdx
Removes EA note on device classification
> chore(mobile): removes ea note on device classification

- src/components/banner.tsx
> update banner for syntax

- src/platform-includes/getting-started-config/react-native.mdx
- https://github.com/getsentry/sentry-docs/issues/5735 …
> Add tracesSampleRate to the main initialize RN SDK code snippet

- src/platform-includes/getting-started-install/react-native.mdx
- src/wizard/react-native/index.md
> feat(rn): Update to new one-line command to install RN SDK

- src/platforms/common/crons/index.mdx
- src/platforms/common/crons/troubleshooting-crons.mdx
> feat(crons): Add environment support to the HTTP examples

- src/platforms/node/guides/koa/index.mdx
ref https://github.com/getsentry/sentry-javascript/pull/7873
> fix(node): Add error handling to koa snippet

- src/docs/product/integrations/deployment/vercel/index.mdx
> Be explicit that the Vercel integration will only work with the Next.js SDK

- vercel.json
This PR should fix the most of these awful errors:
The change is similar to https://github.com/getsentry/static-sites/pull/1592 https://github.com/getsentry/static-sites/pull/1641 https://github.com/getsentry/static-sites/pull/1642
> CSP: add sources that are in use but reported as violations

- src/docs/product/issues/issue-details/ai-suggested-solution/index.mdx
> fix(suggested-solution): Add redirect to the new URL

- src/platform-includes/configuration/enable-pluggable-integrations-lazy/javascript.mdx
- src/platforms/javascript/common/configuration/integrations/plugin.mdx
Since we've had a few support requests for this recently, I think it makes sense to document this method properly.
> feat: Add docs for `client.addIntegration()`

- src/docs/product/integrations/deployment/index.mdx
- src/docs/product/releases/setup/release-automation/github-deployment-gates/index.mdx
> Add docs for github deployment gates

- src/css/_includes/global-header.scss
- src/css/_includes/type.scss
> fix(ui): Improve anchor jump link alignments

- src/docs/product/relay/options.mdx
Adding new spooling configuration options:
* path to the file
* max memory size
* max disk size
* max / min connections
> feat(relay): Add spooling configuration options

- src/docs/product/issues/issue-details/ai-suggested-solution/index.mdx
Removing the early adopters note since the feature is now GA
> ref(suggested-solution): Remove early-adopters note

- src/platforms/common/profiling/index.mdx
Polishing docs ahead of profiling GA release.
> supply objc snippets for profiling setup

- src/platforms/react-native/troubleshooting.mdx
> fix(rn): Fix app start apple troubleshooting link

- src/platforms/apple/common/configuration/app-hangs.mdx
Explain how the app hang algorithm works on a high level and why it can be a bit inaccurate in certain circumstances to clarify expectations to the feature.
Fixes GH-6614
> feat(apple): Explain app hang algorithm

- src/platforms/common/performance/index.mdx
- src/platforms/php/common/profiling/index.mdx
- src/platforms/php/guides/laravel/profiling/index.mdx
- src/platforms/php/guides/symfony/profiling/index.mdx
Add dedicated Laravel & Symfony docs for Profiling.
> Add Laravel and Symfony Profiling docs

- src/wizard/php/profiling-onboarding/laravel/1.install.md
- src/wizard/php/profiling-onboarding/laravel/2.configure-performance.md
- src/wizard/php/profiling-onboarding/laravel/3.configure-profiling.md
- src/wizard/php/profiling-onboarding/php/2.configure-performance.md
- src/wizard/php/profiling-onboarding/symfony/1.install.md
- src/wizard/php/profiling-onboarding/symfony/2.configure-performance.md
- src/wizard/php/profiling-onboarding/symfony/3.configure-profiling.md
https://github.com/getsentry/sentry-docs/pull/6713 and https://github.com/getsentry/sentry-docs/pull/6716 need to be merged first.
> Add Laravel and Symfony Profiling wizard

- src/docs/product/profiling/getting-started.mdx
- src/platforms/common/profiling/index.mdx
- src/platforms/node/common/profiling/index.mdx
- src/platforms/php/common/profiling/index.mdx
- src/platforms/php/guides/laravel/profiling/index.mdx
- src/platforms/php/guides/symfony/profiling/index.mdx
Clarify what happens to the profiles sent after the beta closed.
> chore(profiling): Add end of profiling beta alert

- src/platforms/python/common/configuration/integrations/redis.mdx
We released a update to the Python Redis integration allowing the users to change the data trimming behaviour of the integration.
> [Python SDK] Updated Redis integration to include `max_data_size` parameter

- .github/workflows/bump-api-schema-sha.yml
> fix: update bump api schema action with linting

- package.json
- src/components/codeBlock.tsx
- yarn.lock
> ref(js): Use navigator.clipboard over copy-to-clipboard package

- src/docs/product/sentry-basics/search/searchable-properties.mdx
See: https://github.com/getsentry/sentry/pull/48035
> Replay Search fields: Add testid

- src/platform-includes/debug-symbols-apple/_default.mdx
Clarify that bitcode is deprecated.
> feat(apple): Clarify bitcode is deprecated

- src/docs/product/profiling/performance-overhead.mdx
Add a page describing the performance overhead of enabling profiling in production.
> docs(profiling): Add page about performance overhead

- src/components/banner.tsx
🚨 please dont merge - rahul will merge when ready.  …
> update banner with profiling ama

- package.json
- yarn.lock
See https://github.com/gatsbyjs/gatsby/issues/29326
> fix(build): Lock plugin-transform-spread for now

- src/platforms/apple/common/performance/instrumentation/automatic-instrumentation.mdx
- src/platforms/common/enriching-events/viewhierarchy.mdx
Clarified that view hierarchy feature and automatic UI event transactions don't work with SwiftUI.
> Feat(apple): Add missing information regarding SwiftUI

- package.json
- yarn.lock
> chore(deps): Drop is-svg

- src/includes/debug-id-requirement.mdx
- src/platform-includes/sourcemaps/upload/cli/javascript.mdx
- src/platform-includes/sourcemaps/upload/systemjs/javascript.mdx
- src/platform-includes/sourcemaps/upload/typescript/javascript.mdx
- src/platform-includes/sourcemaps/upload/uglifyjs/javascript.mdx
- src/platform-includes/sourcemaps/uploading-without-debug-ids/javascript.mdx
- src/platforms/javascript/common/sourcemaps/uploading-without-debug-ids.mdx
Resolves https://github.com/getsentry/sentry/issues/47237
> Uploading sourcemaps without debug ids

- src/docs/product/cli/configuration.mdx
- src/docs/product/profiling/mobile-app-profiling.mdx
- src/platform-includes/performance/automatic-instrumentation-integrations/dotnet.mdx
- src/platform-includes/session-replay/setup/javascript.capacitor.mdx
- src/platforms/common/enriching-events/viewhierarchy.mdx
- src/platforms/java/guides/spring-boot/record-user.mdx
- src/platforms/javascript/common/session-replay/configuration.mdx
- src/platforms/kotlin-multiplatform/initialization-strategies.mdx
- src/platforms/node/common/performance/database/auto-instrument.mdx
- src/wizard/react-native/index.md
These were missed in earlier PRs and snuck into the code only formatting
PR
> chore(prettier): A little more minor formatting cleanup

- bin/react-to-product-owners-yml-changes.sh
cf. https://github.com/getsentry/sentry-docs/pull/6862
> Only add .github/labels.yml (not whole venv!)

- .github/labels.yml
I tested out the automation but it had nothing to change:
https://github.com/getsentry/sentry-docs/actions/runs/4889623748/jobs/8728296698
This will give it something trivial to change.
> Test out label update automation

- src/wizard/node/profiling-onboarding/javascript-nextjs/3.configure-profiling.md
- src/wizard/node/profiling-onboarding/node/3.configure-profiling.md
- src/wizard/node/profiling-onboarding/remix/3.configure-profiling.md
Change `traceSampleRate` to `tracesSampleRate` in node profiling wizard.
> fix(profiling): Fix typo in node profiling wizard

- src/platform-includes/enriching-events/add-attachment/java.mdx
The specified code samples don't compile for Java and Kotlin. This PR fixes this by adding code that compiles.
> fix(java): Attachment hint code sample

- src/platforms/php/guides/laravel/other-versions/lumen.mdx
We decided to bring back support for Laravel Lumen.
To be merged once https://github.com/getsentry/sentry-laravel/pull/685 is released.
> Reintroduce Lumen

- src/platforms/php/guides/laravel/configuration/laravel-options.mdx
Add missing Laravel options that were introduced in the recent past.
> Add missing Laravel options

- src/platforms/common/data-management/debug-files/upload/index.mdx
The doc incorrectly states that uploads are automatic. This has changed and it's not automatic anymore. Also point to the msbuild doc that should be set up in the maui project.
Fix incorrect and missing infos in maui doc. …
> Maui: link to correct settings to upload symbols

- src/platforms/javascript/common/session-replay/configuration.mdx
> replay: privacy link from config

- src/platforms/javascript/common/configuration/micro-frontend-support.mdx
Fixes a couple of syntax errors in the MFE docs and formats them with prettier.
> Tidy MFE support doc example code

- src/components/smartLink.tsx
This PR fixes a problem with hash URLs when we try to construct them for a link
> fix(urls): fix hash url params

- vercel.json
Seems like we enabled GA4 on docs.sentry.io. While we don't yet enforce CSP, but would be nice to fix those CSP violations:
https://sentry.sentry.io/issues/1288985014/
https://sentry.sentry.io/issues/3353244451/
https://sentry.sentry.io/issues/3538407916/
> CSP: allow connect to `analytics.google.com` and `region1.analytics.google.com`

- src/platforms/php/common/performance/instrumentation/automatic-instrumentation.mdx
We currently offer no auto instrumentation for PHP, so we should inform people about Profiling.
> Add profiling hint to PHP

- src/platforms/javascript/guides/nextjs/manual-setup.mdx
> Add instructions of how to opt out of auto crons for Next.js

- src/docs/product/issues/issue-details/index.mdx
small edit in issue details page
> Update issue details page

- src/components/banner.tsx
> remove banner

- src/css/_includes/sidebar.scss
> Improved sidebar hover states

- src/docs/product/accounts/early-adopter.mdx
- src/docs/product/issues/issue-details/performance-issues/consecutive-http/index.mdx
Going to GA soon so we should remove the EA notes.
> chore(consecutive-http): Remove EA notes

- .github/workflows/react-to-product-owners-yml-changes.yml
- .github/workflows/test.yml
- src/docs/product/issues/issue-details/ai-suggested-solution/index.mdx
Committed via https://github.com/asottile/all-repos
> ref: reference SENTRY_INTERNAL_APP_ID from vars

- src/gatsby/utils/fetchCache.ts
I think this may have "fixed" our registry fetching issue
> ref(js): Improve retry comments + logging

- src/docs/product/issues/issue-details/ai-suggested-solution/index.mdx
- src/platforms/react-native/configuration/app-hangs.mdx
> Add App Hangs documentation for RN SDK

- src/platforms/common/performance/index.mdx
Clarify the Improve Response Time section for Laravel and Symfony.
> Clarify PHP response time for performance

- src/platform-includes/sourcemaps/overview/javascript.vue.mdx
- src/platform-includes/sourcemaps/primer/javascript.sveltekit.mdx
- src/platform-includes/sourcemaps/upload/esbuild/javascript.mdx
- src/platform-includes/sourcemaps/upload/rollup/javascript.mdx
- src/platform-includes/sourcemaps/upload/vite/javascript.mdx
- src/platform-includes/sourcemaps/upload/webpack/javascript.mdx
- src/platforms/javascript/guides/sveltekit/manual-setup.mdx
Updates/prepares the docs for the Javascript bundler plugins for their V2 release.
> Update bundler plugin documentation for V2 release

- src/platform-includes/getting-started-install/kotlin-multiplatform.mdx
Let's merge this PR before https://github.com/getsentry/sentry-docs/pull/6975 because it might take a bit longer due to code review.
Related to https://github.com/getsentry/sentry-kotlin-multiplatform/issues/95
> Fix Cocoa version - KMP

- src/platforms/apple/common/install/swift-package-manager.mdx
Added extra information on how to install Sentry SDK with SPM.
> feat(apple): Update installation with SPM

- src/components/banner.tsx
[Add banner for upcoming webinar](https://getsentry.atlassian.net/browse/STAT-145)
> Banner Update

- src/platform-includes/getting-started-verify/javascript.sveltekit.mdx
> fix(sveltekit): Fix verify setup code snippet

- src/docs/product/accounts/early-adopter.mdx
Add link to team-level roles preview on early adopters page
> Add team-level roles to EA features

- src/css/_includes/banner.scss
> fix(ui): Alignment of banner closer button X

- src/components/apiSidebar.tsx
- src/components/basePage.tsx
- src/components/codeBlock.tsx
- src/components/codeContext.tsx
- src/components/navbarPlatformDropdown.tsx
- src/components/pageContext.tsx
- src/components/platformContent.tsx
- src/components/platformSection.tsx
- src/components/relayMetrics.tsx
- src/components/search.tsx
- src/components/smartLink.tsx
- src/components/tableOfContents.tsx
- src/templates/apiPage.tsx
In preperation for react 17 and 18
> ref(js): Avoid using React.*

- src/components/__tests__/__snapshots__/header.test.js.snap
- src/components/__tests__/__snapshots__/platformLink.test.js.snap
- src/components/sidebarLink.tsx
- src/components/smartLink.tsx
- src/css/_includes/sidebar.scss
> feat(ui): Add chevrons to nav items w/ children

- package.json
- yarn.lock
> deps(js): Bump emotion 10 -> 11

- src/platform-includes/getting-started-install/react-native.mdx
Should be this way in all docs and marketing pages ie /for pages
> Update react-native wizard@latest

- src/platforms/android/configuration/app-not-respond.mdx
Mention ANR mechanism as it's important for those who count/filter events
> chore(android): Mention ANR mechanism

- src/docs/product/issues/issue-details/ai-suggested-solution/index.mdx
Re-arranged some information and added some more detail about which event data we send, in order to make the data processing piece more obvious and answer questions popping up on Github.
> Add data processing info.mdx

- src/platform-includes/performance/configure-sample-rate/dart.mdx
`Sentry.init` accepts a callback function as an argument, so everything inside `{}` is a function flow, not an object. So every line should end with `;` and not `,`. …
> Fix dart code snippet in performance section

- src/docs/product/issues/ownership-rules/index.mdx
> Update CODEOWNERS max size in Limitations section

- src/platforms/common/enriching-events/attachments/index.mdx
> Correct typo.

- src/components/banner.tsx
> turn off banner
