design/templates/layout.html, docs/learn/user-feedback.rst
=> Add User Feedback to Learn

design/templates/layout.html, docs/index.rst, docs/serverdev/index.rst
Fixes https://github.com/getsentry/sentry-docs/issues/33.
Looking for answers on all #TODO statements and generic feelings.
@getsentry/infrastructure
=> First passthrough for 'Contributing to Sentry'

docs/index.rst, docs/quickstart.rst
https://github.com/getsentry/sentry/pull/3537
@mitsuhiko
=> Necessary changes to go with getsentry/sentry#3537

docs/clients/table.rst.inc
cc @getsentry/team
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/sentry-docs/51)
=> Update supported platforms on index page w/ latest frameworks

docs/clientdev/advanced.rst, docs/learn/quotas.rst
@getsentry/team
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/sentry-docs/56)
=> Fix typo: stacktrace's -> stacktraces

docs/serverdev/index.rst
@LewisJEllis @getsentry/ops
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/sentry-docs/57)
=> Add note about pg on OSX.

design/templates/layout.html
cc @getsentry/ui @mitsuhiko
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/sentry-docs/58)
=> Move doc scripts to bottom of <body> for perf

design/templates/layout.html, docs/index.rst, docs/integrations/index.rst, docs/integrations/jira.rst
@getsentry/plugins
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/sentry-docs/61)
=> add integrations page + jira specific page

docs/integrations/index.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/sentry-docs/62)
=> make sure jira is included in toctree

design/less/main.less
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/sentry-docs/63)
=> Add elixir icon

docs/integrations/hipchat.rst, docs/integrations/index.rst
@getsentry/plugins
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/sentry-docs/64)
=> Add HipChat docs

design/templates/layout.html, docs/integrations/bitbucket.rst, docs/integrations/index.rst
@cameronmcefee
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/sentry-docs/65)
=> Adding bitbucket docs

design/templates/layout.html, docs/integrations/github.rst, docs/integrations/index.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/sentry-docs/68)
=> adding github integrations page

Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/sentry-docs/66)
=> Move docs to root

docs/internal/environment.rst
As of 39da7243 that's the recommended approach.
=> Remove note about running redis and postgres as startup service

docs/integrations/jira.rst
I figure it'd be nice to link to the plugin itself.
=> Add link to jira plugin

docs/clientdev/interfaces/contexts.rst
Bit me here: https://github.com/getsentry/raven-ruby/issues/583
=> Contexts clarification

docs/clientdev/attributes.rst
=> Reduce Little Caesars quotient

design/js/main.js, search-config.json
modify the `search-config.json` and `initRigidSearch()` to handle the changes being made to rigidsearch indexing and scoring.
cc @mitsuhiko
=> Search edits

search-config.json
Make it so clients is higher so search results make more sense. Tweaking rigidsearch as well.
cc @benvinegar @mitsuhiko
=> change scoring

design/js/main.js
=> make path look better

design/templates/layout.html, docs/clientdev/interfaces/index.rst, docs/clientdev/interfaces/repos.rst
=> Add repos interface

docs/clientdev/attributes.rst, docs/clientdev/context.rst, docs/clientdev/data-handling.rst, docs/clientdev/interfaces/breadcrumbs.rst, docs/clientdev/interfaces/exception.rst, docs/clientdev/interfaces/http.rst, docs/clientdev/overview.rst
Minor changes I made as I was checking up on `clientdev` docs and how `raven-java` compares.
=> Minor cleanup of some clientdev docs.

docs/ip-ranges.rst
This will soon end up unsustainable, but it is what it is.
cc @MeredithAnya
=> Update ip ranges.

design/templates/layout.html
This is prepped for when this lands: https://github.com/getsentry/raven-java/pull/311
=> Update layout for new Java docs.

docs/pricing.rst
Need to make sure the links are 👌
=> Add section on managing event volume to pricing doc

design/templates/layout.html
Added react-native link to the sidebar
@HazAT @mitsuhiko
=> add react native link

docs/index.rst, docs/learn/releases.rst
formatting is pretty messed up still and i need to add some code samples, but wanted to get this up for now. going to fix up a bit more later tonight.
@mitsuhiko are there docs for / did you add deploy creation to sentry-cli?
=> wip - add learn/releases page

design/templates/layout.html
=> actually add releases tab to sidebar

design/less/main.less, docs/learn/releases.rst
@ckj soo this is almost there, but is spilling off the page. i think maybe it's just a css issue now if you wanna check it out tomorrow?
=> try to just add class to note on releases

design/templates/layout.html
Depends on https://github.com/getsentry/raven-js/pull/928
=> s/angular 1/angularjs and s/angular 2/angular in template 

docs/learn/releases.rst
https://twitter.com/snowpong/status/859693302588866560
=> Release team member permissions

docs/learn/releases.rst
Updated docs to be merged when we start fetching commits without start_sha
=> Update releases docs

docs/learn/releases.rst
=> make repo name example clearer

nginx.conf
=> add redirects for project release endpoints

docs/integrations/github.rst
=> Lowercase u in GitHub

docs/internal/contributing.rst
See: https://github.com/getsentry/brain/pull/93#issuecomment-326411758
=> ref: Backport commit guideline additions

design/js/main.js, design/less/main.less, design/templates/layout.html
The marketing folks would like to add Hubspot to the docs. This adds cookie permission banner we're using elsewhere and a link to Hubspot.
=> Cookies and hubspot

docs/learn/quotas.rst
Add information on filtering by releases and error-messages and fix reference to location of inbound filters within UI.
=> Document new inbound filters and update reference.

design/js/main.js, design/less/main.less, design/templates/layout.html
The marketing folks have requested more trackers. In the process of adding them, I've removed my previous tracker banner implementation for one that's more consistent in usage and is easier for me to copy between sites.
=> feat: add trackers

docs/internal/environment.rst
I'm not sure sure if it's called `root address of the server`, as I don't want to tear down my env for the 4th time :P
=> docs: Add note about project root address

design/less/main.less, design/templates/layout.html
This adds a sign up button to docs
=> Add sign up button on docs

docs/pricing.rst
Pointing to our pricing page, per user feedback that the "pricing docs" don't have any actual pricing information.
=> updating pricing note

design/templates/layout.html
Related: https://github.com/getsentry/raven-node/pull/419
=> docs: Add Node TypeScript docs

docs/learn/context.rst
=> Remove extra 'are'

docs/quickstart.rst
Idea is to make the workflow discoverable at a point where people are looking for content like that. This seemed like a reasonable place (open to other ideas). Long-term perhaps the blog post can be a section in the docs / tutorial / "resource" etc.
=> Link to workflow from quickstart

docs/clientdev/interfaces/exception.rst, docs/clientdev/interfaces/index.rst, docs/clientdev/interfaces/mechanism.rst
Adds docs for the Exception Mechanism, as specified here:
https://paper.dropbox.com/doc/Mechansim-Vw3DiX7a5wpUUPSq0egPt
=> feat(clientdev): Add exception mechanism

docs/learn/membership.rst
When Open Membership is disabled...
=> Only manager/owner can invite/approve member

docs/learn/quotas.rst
=> fix(docs): Fix typos

docs/pricing.rst
=> Remove mentions of org wide rate limits

docs/learn/releases.rst
Make step 2 clearer and give more context in step 1
=> Update releases documentation

docs/learn/quotas.rst
Adapted from https://github.com/getsentry/sentry-docs/pull/277
=> Add spike protection to quotas docs

src/_js/lib/DynamicLoad.js, src/_layouts/doc.html
When dynamically loading page contents, this jumps you back to the top of the page
=> Scroll to the top of the page when dynamically loading content

src/_layouts/doc.html
=> fix(ui): apply move .bg-dark to .sidebar

src/_js/lib/DynamicLoad.js
I wasn't paying attention in my haste and did a garbage job of fixing the scroll-to-top behavior.
=> Fix: only jump to top on new pages

src/collections/_documentation/server/installation/python/index.md
Port getsentry/sentry#5092 to the new docs.
=> fix(docs) Fix broken link.

src/support.md
fixes SE-65
https://getsentry.atlassian.net/browse/SE-65
100% open to wording changes.
=> Update support page

src/_data/platforms.yml, src/_layouts/_platform/_index.json, src/_layouts/_platform/platform.json, src/_layouts/json.json, src/_plugins/platform_api.rb
Resolves https://forum.sentry.io/t/link-to-docs-leads-to-login-page-that-is-unusable/4617
=> Fix: absolute platform api doc url

src/collections/_documentation/integrations/github-enterprise.md, src/collections/_documentation/integrations/github.md, src/collections/_documentation/integrations/githubenterprise.md, src/collections/_documentation/integrations/jira.md
Docs for some of our new integrations. Pictures to come in the next few days, but want to have instructions live for when we contact early adopters tomorrow morning.
=> Jira, Github, GHE Drafts: Early adopters edition

src/_js/lib/Search.js
This displays the message "No results" if the search page is queried with an empty string.
=> feat: handle empty search query

src/_assets/css/_includes/grid.scss, src/_assets/css/_includes/sidebar.scss, src/_includes/feedback_footer.html, src/_layouts/doc.html
I found a couple quirks in the flexbox layout that this probably irons out.
=> fix: improve layout again

src/_js/lib/DynamicLoad.js, src/_layouts/doc.html
- Untoggle the feedback button when the user navigates to a different page
- Reduce the vertical padding a bit
=> Tweaks to docs-feedback bar

src/_js/lib/User.js, src/_js/lib/UserContent.js, src/collections/_documentation/clients/cocoa/dsym.md, src/collections/_documentation/clients/java/modules/android.md
Some docs are broken because the name switched to id
=> fix: Remove overloaded name method

src/_js/lib/User.js
=> fix (user data): account for cases where project has no id

src/_js/lib/PlatformContent.js
The original fix for this was under the assumption that `location.href`
does not contain the anchor.
=> fix: Fix anchors again

src/collections/_documentation/clients/python/integrations/lambda.md
=> fix: Document supported arguments for LambdaClient

src/collections/_documentation/platforms/python/flask.md
=> fix: Fix missing information in flask docs

bin/update-api-docs
=> fix(docs) Fix typo

src/collections/_documentation/clients/ruby/config.md
https://github.com/getsentry/raven-ruby/issues/852
=> Clarify Ruby client's sanitize_fields

src/_data/platform_icons.yml, src/_includes/platform_icon_links.html, src/collections/_documentation/platforms/javascript/browser.md, src/collections/_documentation/platforms/javascript/loader.md, src/collections/_documentation/platforms/javascript/node.md
=> fix: Change links in platforms

src/_data/platforms.yml
Correlates with https://github.com/getsentry/sentry/pull/9910
=> fix: Display of AWS Lambda integration

src/_data/platform_icons.yml, src/_data/platforms.yml, src/collections/_documentation/platforms/python/index.md, src/collections/_documentation/platforms/python/sanic.md
correlates with https://github.com/getsentry/sentry/pull/9911
=> feat: Add docs for sanic platform

src/_js/lib/UserContent.js
This is the first step toward fixing https://sentry.io/sentry/docs/issues/704877366. This will stop the errors, and adds some debug information to try to figure out why it's failing in the first place.
=> fix: no project error

src/collections/_documentation/clients/javascript/usage.md
Fixed a few typos in the documentation on maximum payload size.
=> Improve documentation

src/_js/lib/UserContent.js
This should resolve https://sentry.io/sentry/docs/issues/707859471
=> import raven

nginx.conf
Fixes https://github.com/getsentry/sentry-cordova/issues/89
=> fix: Add redirect for ionic

src/collections/_documentation/platforms/javascript/default-integrations.md, src/collections/_documentation/platforms/javascript/index.md
ref: https://getsentry.atlassian.net/browse/SDK-442
=> feat: Default JS SDKs integrations

src/collections/_documentation/learn/user-feedback-example/browser.md, src/collections/_documentation/learn/user-feedback-example/electron.md, src/collections/_documentation/learn/user-feedback.md
Fix: https://github.com/getsentry/sentry/issues/4646#issuecomment-427093755
=> docs: Add user email and name to feedbackDialog options

src/collections/_documentation/learn/releases.md
=> (ref) Add link to membership page

nginx.conf
Currently in Report-Only mode.
=> Slapping in CSP policy

src/collections/_documentation/platforms/javascript/express.md
Reverts getsentry/sentry-docs#447
Merge once we merge https://github.com/getsentry/sentry-javascript/pull/1637/
=> Revert "docs: Explain getHubFromCarrier in express"

src/_js/lib/Feedback.js
=> fix(analytics): Cast to int

src/collections/_documentation/product/quotas.md
=> (ref) Remove mentions of legacy plans, clean up wording

src/collections/_documentation/learn/quickstart.md
"Adding context (tags, user and extra information)"
=> "Identifying users via context"-> "Adding context"

src/collections/_documentation/platforms/javascript/react.md
=> fix: Update react.md

src/collections/_documentation/learn/cli/elf.md
=> Fix objcopy command on linux.

src/collections/_documentation/clients/javascript/sourcemaps.md
=> (ref) Add mentions of SourceMap HTTP header to source map docs

src/collections/_documentation/platforms/javascript/advance-settings.md
reference: https://github.com/getsentry/sentry-javascript/issues/1656
=> docs: Add explanation of BrowserClient

src/collections/_documentation/learn/context.md, src/collections/_documentation/learn/with-scope/csharp.md, src/collections/_documentation/learn/with-scope/javascript.md, src/collections/_documentation/learn/with-scope/python.md, src/collections/_documentation/learn/with-scope/rust.md
=> fix: Clarify how to remove context data

src/collections/_documentation/learn/environments.md
=> fix: update environments

src/collections/_documentation/platforms/python/rq.md
Fix https://github.com/getsentry/sentry-python/issues/151
=> fix: Add note about init order for RQ

src/_layouts/api.html
While debugging another issue I discovered this derelict tag
=> Remove extra closing tag

src/collections/_documentation/platforms/minidump/index.md
=> feat(minidump): Document event attachments for minidump requests

src/collections/_documentation/clients/java/modules/log4j.md, src/collections/_documentation/platforms/javascript/vue.md
=> fix: Broken wizards

src/collections/_documentation/product/discover.md
Include new "project_name" field. Add "received" and include "datetime"
types. Add section on saved queries.
=> feat: Update Discover docs

src/collections/_documentation/platforms/python/pyramid.md
=> fix: Fix copypaste error

src/collections/_documentation/platforms/python/logging.md
Fix https://github.com/getsentry/sentry-python/issues/157
=> doc: Document log handler classes in Python

src/collections/_documentation/product/discover.md
These were introduced in https://github.com/getsentry/sentry/pull/10426
=> feat(discover): Update field documentation to reflect new aliases

src/_assets/css/_includes/user-content-ui.scss, src/_assets/css/screen.scss, src/_js/lib/UserContentUI.js, src/_js/lib/__snapshots__/UserContentUI.test.js.snap
This adds a max-height to the user-content picker so it'll scroll when someone has a lot of projects.
=> Add a max-height to the user-content switcher menu

src/collections/_documentation/workflow/discover.md
Added in https://github.com/getsentry/sentry/pull/10471
=> feat(discover): Add issue field

src/collections/_documentation/workflow/discover.md
Depends on https://github.com/getsentry/sentry/pull/10505
=> feat(discover): Add geo fields

src/_layouts/legacy-client.html
=> fix: Fix dead link

src/collections/_documentation/error-reporting/configuration/index.md
@mitsuhiko This seems like it resolves DOCS-16. Or is it more complicated than I understand?
=> add browsernpm to support list for url lists

src/collections/_documentation/platforms/dotnet/aspnetcore.md, src/collections/_documentation/platforms/dotnet/entityframework.md
* ASP.NET Core
* Entity Framework
=> fix: titles for .NET integrations

__tests__/__snapshots__/documentation.js.snap, src/collections/_documentation/development/sdk-dev/interfaces/gpu.md, src/collections/_documentation/development/sdk-dev/interfaces/index.md
@mitsuhiko Should this be a top level inf or under contexts?
=> GPU Interface

nginx.conf
A first pass at this, just to get it done and stop all our stuff from 404ing as quickly as possible. Will come back to the problem of cleaning up the file (nesting locations, etc) separately.
=> fix(nginx): Handle trailing slashes (or lack thereof)

src/collections/_documentation/accounts/quotas.md
fixed a typo additioanl to additional
=> typo quotas.md

src/collections/_documentation/workflow/discover.md
Depends on https://github.com/getsentry/sentry/pull/10766
=> feat: Update discover docs with new field names

src/collections/_documentation/accounts/membership.md
=> (chore) Update membership table

src/collections/_documentation/platforms/javascript/index.md
=> fix: IE 11 docs

src/collections/_documentation/data-management/relay/pii-config/index.md, src/collections/_documentation/data-management/relay/pii-config/methods.md, src/collections/_documentation/data-management/relay/pii-config/types.md
Merge after semaphore 0.2.6 is released
=> fix: Updates for general-powered PII stripping

src/collections/_documentation/platforms/node/sourcemaps.md, src/collections/_documentation/platforms/node/typescript.md
🎅
Tested everything manually, step-by-step, just to make sure it's all accurate. Works 💯
=> docs: Source Maps and TypeScript docs for @sentry/node

src/collections/_documentation/platforms/javascript/default-integrations.md, src/collections/_documentation/platforms/javascript/pluggable-integrations.md, src/collections/_documentation/platforms/node/default-integrations.md, src/collections/_documentation/platforms/node/pluggable-integrations.md
=> docs: Updated all JS/Node integrations and created Pluggable Integrations pages

src/collections/_documentation/workflow/integrations/azure-devops.md, src/collections/_documentation/workflow/integrations/bitbucket.md, src/collections/_documentation/workflow/integrations/github.md, src/collections/_documentation/workflow/integrations/gitlab.md, src/collections/_documentation/workflow/integrations/heroku.md, src/collections/_documentation/workflow/integrations/jira.md, src/collections/_documentation/workflow/integrations/sessionstack.md, src/collections/_documentation/workflow/integrations/splunk.md
- removes blockquoted images
- adds info or warning styling to notes
- bolds instead of quotes button text
- makes images clickable
- adds required permissions to the top of the section
- breaks configuration instructions into steps
=> Format integration docs

src/collections/_documentation/platforms/python/django.md
lmk if you need this for other frameworks.
=> doc: Explain how to log 404s in django

src/collections/_documentation/workflow/search.md
=> fix(workflow): typo

src/collections/_documentation/clients/javascript/sourcemaps.md
=> Fix broken links

src/collections/_documentation/workflow/integrations/index.md
=> Move GitLab link up to global integrations

src/collections/_documentation/server/faq.md
=> fix: Formatting of server FAQ

src/collections/_documentation/error-reporting/configuration/config-intro/php.md, src/collections/_documentation/error-reporting/configuration/filtering.md, src/collections/_documentation/error-reporting/getting-started-install/php.md, src/collections/_documentation/platforms/php/default-integrations.md, src/collections/_documentation/platforms/php/index.md, src/collections/_documentation/platforms/php/laravel.md
- I updated some spelling and language/grammar in the PHP docs. This will make communication a bit more clear.
- Also put Notes in alert boxes for consistency throughout docs. 
@HazAT, will you take a look? :)
=> Updated spelling and grammar

__tests__/__snapshots__/documentation.js.snap, src/collections/_documentation/workflow/integrations/legacy-integrations/index.md
=> fix: Update broken link

src/_js/lib/PlatformContent.js
=> fix: Doubled config keys

__tests__/__snapshots__/documentation.js.snap, src/collections/_documentation/api/index.md, src/collections/_documentation/api/permissions.md
=> Add API permissions page

src/collections/_documentation/platforms/javascript/ember.md
https://twitter.com/MarkoMiklo/status/1090771077058289665
=> ref: Use ember-auto-import in Ember.js docs

src/collections/_documentation/clients/cocoa/advanced.md
Docs for https://github.com/getsentry/sentry-cocoa/pull/284
=> feat: Add memory pressure docs for cocoa

src/collections/_documentation/clients/java/modules/android.md
WIP: To be merged after:
https://github.com/getsentry/symbolic/pull/125
And PRs to sentry and sentry-cli with new symbolic and gradle plugin.
=> [WIP] ref: Remove note of R8 unsupported

src/_layouts/relay.html
see: https://docs.sentry.io/data-management/relay/
=> added space

src/collections/_documentation/clients/php/integrations/laravel.md
Correction of a mispelled word
=> Correction of a mispelled word

src/collections/_documentation/platforms/javascript/index.md
=> fixed spacing for {{default}}

src/collections/_documentation/platforms/javascript/index.md
Changed 'This is my fake error message' to "This is my fake error message"
=> fixed string and code snippets

src/collections/_documentation/platforms/node/default-integrations.md
Closes https://github.com/getsentry/sentry-javascript/issues/1909
=> docs: Document node's unhandled promise rejection handler override

src/_js/lib/Tracking.js
To get a sense of how many users do one vs the other to inform future analytics work
=> Record whether users accept or decline cookies

src/collections/_documentation/workflow/discover.md, src/collections/_documentation/workflow/visibility.md
https://docs.sentry.io/workflow/visibility/
https://docs.sentry.io/workflow/discover/
=> Remove EA & Beta from Visibility features

Dockerfile.local, README.md
I was struggling in using the bootstrap script, since it seems tailored for Mac usage. So, I wrote down a small Dockerfile with instructions which is able to do the same, but in a containerized way.
=> Docker development local container

src/_assets/css/_includes/type.scss
=> Feat: Add top margin to any h2 that is not the first child

src/collections/_documentation/platforms/python/celery.md
This is just copypasted from RQ where the same stuff applies
=> fix: Give celery docs some love

src/collections/_documentation/error-reporting/configuration/index.md
=> doc: C# supports InAppInclude

src/collections/_documentation/development/sdk-dev/interfaces/contexts.md
=> doc: Device properties

src/collections/_documentation/platforms/php/laravel.md
@HazAT WDYT?
Triggered by: #204
=> Add note about local development for Laravel

src/collections/_documentation/platforms/dotnet/serilog.md
=> fix: Use DSN instead of key

src/_js/lib/Search.js
This removes the Algolia brand callout that missed in my previous pr.
=> fix: Remove remaining Algolia callout

src/collections/_documentation/platforms/php/default-integrations.md
=> Correct the amount of memory the PHP SDK reserves

__tests__/__snapshots__/documentation.js.snap, src/_data/platform_icons.yml, src/_data/platforms.yml, src/collections/_documentation/platforms/python/bottle.md, src/collections/_documentation/platforms/python/index.md
related to https://github.com/getsentry/sentry-python/pull/300#issuecomment-477344421 which is being supervised by @untitaker
=> doc: New Python Bottle integration

src/collections/_documentation/enriching-error-data/breadcrumbs-example/javascript.md
Needed to pass script typescript compiler checks.
=> Use enum instead of string

src/collections/_documentation/platforms/python/rq.md
=> fix: Fix wording of RQ docs for RQ 1.0

src/_js/lib/Page.js, src/_js/lib/Trackers.js, src/_js/lib/Tracking.js
Similar to https://github.com/getsentry/blog/pull/531
=> Add docs analytics to another GA property

src/_includes/LEGACY_platform_icon_links.html, src/_includes/platform_icon_links.html
This fixes broken links on the platform pages
=> Remove raw from link helper

src/collections/_documentation/workflow/integrations/index.md
added Rookout to the list of Global Integrations on the Integrations index page
=> added Rookout to Global Integrations

src/collections/_documentation/workflow/integrations/integration-platform/index.md
=> removed duplicate title

__tests__/__snapshots__/documentation.js.snap, src/_data/platform_icons.yml, src/_data/platforms.yml, src/collections/_documentation/platforms/python/falcon.md, src/collections/_documentation/platforms/python/index.md
For the Falcon integration implemented here: https://github.com/getsentry/sentry-python/pull/346
=> doc: New Python Falcon integration

src/collections/_documentation/platforms/python/falcon.md
=> Minor Python Falcon integration docfix

src/_plugins/platform_api.rb
Check the diff using the whitespace option
=> Reduce code indentation w/ guard statment in platform API

src/collections/_documentation/clients/react-native/index.md
Tiny change, why do we use so much italics for code :o
=> More minor backtick code quote correcting

nginx.conf
=> fixed redirects

src/collections/_documentation/platforms/javascript/ember.md
The docs weren't working for me and I could see the import wasn't working correctly.  Looking at the Vue integration docs gave me some insights.  This change worked for me.
=> Correct usage of Integrations for ember

src/collections/_documentation/enriching-error-data/user-feedback.md
As requested in https://github.com/getsentry/sentry-javascript/pull/2061#issuecomment-490838244.
Please tell me if you feel like it should be described more in-depth. :)
Also, feel free to make changes if needed.
=> Added onLoad callback option to user-feedback

.vscode/settings.json, src/_assets/css/_includes/bootstrap-overrides.scss, src/_data/platform_icons.yml, src/_includes/platform_icon_links.html, src/_layouts/doc.html, src/_plugins/document_path_tree.rb, src/_plugins/unless_filter.rb, src/collections/_documentation/clients/cocoa/index.md, src/collections/_documentation/clients/elixir/index.md, src/collections/_documentation/clients/go/index.md, src/collections/_documentation/clients/java/index.md, src/collections/_documentation/clients/react-native/index.md, src/collections/_documentation/clients/ruby/index.md, src/collections/_documentation/error-reporting/getting-started-install/browser.md, src/collections/_documentation/error-reporting/getting-started-install/browsernpm.md, src/collections/_documentation/platforms/dotnet/index.md, src/collections/_documentation/platforms/index.md, src/collections/_documentation/platforms/javascript/getting-started-install/angular.md, src/collections/_documentation/platforms/javascript/getting-started-install/browser.md, src/collections/_documentation/platforms/javascript/getting-started-install/browsernpm.md, src/collections/_documentation/platforms/javascript/getting-started-install/ember.md, src/collections/_documentation/platforms/javascript/getting-started-install/react.md, src/collections/_documentation/platforms/javascript/getting-started-install/vue.md, src/collections/_documentation/platforms/javascript/index.md, src/collections/_documentation/platforms/minidump/index.md, src/collections/_documentation/platforms/node/index.md, src/collections/_documentation/platforms/php/index.md, src/collections/_documentation/platforms/python/index.md, src/collections/_documentation/platforms/rust/index.md, src/collections/_documentation/platforms/unrealengine/index.md
=> feat: Various changes

.gitignore, .vscode/extensions.json, .vscode/settings.json, _config.dev.yml, _config.yml, bin/test-algolia, package.json, src/_assets/css/_includes/search.scss, src/_assets/css/_includes/variables.scss, src/_data/documentation_categories.yml, src/_includes/components/platform_content.html, src/_js/lib/Search.js, src/_layouts/default.html, src/_plugins/algolia_hooks.rb, src/_plugins/ci_sort_filter.rb, src/collections/_documentation/cli/configuration.md, src/collections/_documentation/clients/java/agent.md, src/collections/_documentation/clients/java/config.md, src/collections/_documentation/clients/java/context.md, src/collections/_documentation/clients/java/integrations.md, src/collections/_documentation/clients/java/migration.md, src/collections/_documentation/clients/java/usage.md, src/collections/_documentation/home/index.md, src/collections/_documentation/platforms/javascript/cordova.md, src/collections/_documentation/platforms/javascript/electron.md, src/collections/_documentation/server/index.md, src/collections/_documentation/server/installation/docker/index.md, src/collections/_documentation/support/index.md, src/collections/_documentation/workflow/integrations/global-integrations.md, yarn.lock
- Add test index to Algolia
- Add categories to most pages
- Upgrade Babel to 7
- Enable template literals in babel
- Enable chaining inm babel
=> feat: Improve search

src/collections/_documentation/error-reporting/getting-started-config/rust.md
=> ref(rust): Remove uneeded extern crate sentry

src/collections/_documentation/platforms/python/pyramid.md
The logic to determine what errors should be reported is unusually complex for Pyramid. Let me know if you have a better way to structure this entire page @MimiDumpling, I tend to make too many bulletpoint lists when my sentences get too long.
=> fix: Update docs for Python SDK 0.9.0

src/collections/_documentation/platforms/node/koa.md
The Koa usage of the official document is wrong. I'v corrected it.
=> Correct the koa usage

src/collections/_documentation/server/internal-metrics.md
Seems like the class path is incorrent in the docs
=> fix DogStatsdMetricsBackend class path

src/collections/_documentation/data-management/sensitive-data.md
This should also help search find this page when you input "PII".
=> ref: Add use-case blurbs (focus on PII) to sensitive data

src/collections/_documentation/error-reporting/quickstart.md, src/collections/_documentation/platforms/index.md
- People do not need to roll their own SDK - move that topic elsewhere
- None of the SDKs presented are secret-key based
- Fix some minor language
=> feat: Simplify quickstart

src/collections/_documentation/clients/react-native/expo.md
it aint much but it’s honest work
=> Fix typo in sentry-expo docs

src/collections/_documentation/clients/elixir/config.md, src/collections/_documentation/clients/elixir/index.md, src/collections/_documentation/clients/elixir/plug.md, src/collections/_documentation/clients/elixir/usage.md
closes https://github.com/getsentry/sentry-elixir/issues/339
=> update elixir docs

src/collections/_documentation/platforms/dotnet/index.md, src/collections/_documentation/platforms/javascript/index.md, src/collections/_documentation/platforms/python/index.md
=> fix: Add changelog links to platform pages

src/collections/_documentation/accounts/sso.md
Endpints -> endpoints. Feel free to merge if 👍!
=> Fixes typo in sso.md

src/collections/_documentation/platforms/python/index.md
Its a named parameter, not a dictionary/hash
=> Fix dsn parameter in python docs

src/collections/_documentation/platforms/node/sourcemaps.md
Ref: https://github.com/getsentry/sentry-javascript/issues/2021
=> docs: Update Sourcemaps RewriteFrame integration for Node

src/collections/_documentation/error-reporting/configuration/index.md, src/collections/_documentation/platforms/node/connect.md, src/collections/_documentation/platforms/node/express.md
ref: https://github.com/getsentry/sentry-javascript/pull/2146
=> docs: Update node frameworks doc to include shouldHandleError option

src/_js/lib/Sidebar.js
Makes it possible to reach `/platforms/python` from `/platforms/python/flask`
=> feat: Scroll sidebar element into view

src/collections/_documentation/clients/java/config.md
Resolves getsentry/sentry-java#571
=> feat: Java lint config

src/collections/_documentation/platforms/javascript/ionic.md
Add export before class SentryIonicErrorHandler.
=> fix(ionic): Add export before class SentryIonicErrorHandler

src/collections/_documentation/platforms/php/index.md
Added more information onto the PHP index page to make it easier for a developer to get what they need in one place for the PHP SDK.
=> Condensed PHP SDK to one page

.vscode/settings.json, src/_plugins/release_registry.rb, src/collections/_documentation/enriching-error-data/user-feedback-example/aspnetcore.md, src/collections/_documentation/enriching-error-data/user-feedback-example/browser.md, src/collections/_documentation/enriching-error-data/user-feedback-example/django.md, src/collections/_documentation/enriching-error-data/user-feedback-example/flask.md, src/collections/_documentation/enriching-error-data/user-feedback-example/laravel.md, src/collections/_documentation/enriching-error-data/user-feedback-example/php.md, src/collections/_documentation/error-reporting/getting-started-install/browser.md, src/collections/_documentation/platforms/javascript/angular.md, src/collections/_documentation/platforms/javascript/ember.md, src/collections/_documentation/platforms/javascript/getting-started-install/browser.md, src/collections/_documentation/platforms/javascript/index.md, src/collections/_documentation/platforms/javascript/vue.md
ref: https://github.com/getsentry/sentry-javascript/issues/966
=> feat: Use new release checksums feature to provide SRI

src/collections/_documentation/platforms/node/connect.md, src/collections/_documentation/platforms/node/express.md
@MimiDumpling you can merge right away, it's verified from technical standpoint :)
=> docs: Update requestHandler options in Node

src/collections/_documentation/platforms/javascript/index.md
Need to install @sentry/integrations to use additional pluggable integrations
=> fix: path and package of pluggable integrations

src/collections/_documentation/clients/java/integrations.md, src/collections/_documentation/clients/java/usage.md
To be merged once packages show up on Maven central:
https://search.maven.org/search?q=io.sentry
=> chore: Sentry for Java 1.7.26

src/collections/_documentation/platforms/minidump/crashpad.md
WaitForHandlerStart can be used only with asynchronous_start=true
=> Fix code snippet

src/collections/_documentation/server/installation/docker/index.md, src/collections/_documentation/server/installation/index.md
https://github.com/getsentry/sentry/issues/12673
=> Note Postgres supported versions

src/collections/_documentation/clients/java/integrations.md, src/collections/_documentation/clients/java/usage.md
Waiting for it to show up:
https://search.maven.org/search?q=g:io.sentry
=> chore: Bump Sentry Java SDK

src/collections/_documentation/clients/elixir/index.md
To match from https://github.com/getsentry/sentry-elixir/issues/356
=> update elixir compile docs

src/collections/_documentation/server/filestore.md
Add documentation, so users don't have to find endpoint_url here https://github.com/getsentry/sentry/issues/5466
=> Add documentation for using MinIO as filestore

src/collections/_documentation/platforms/php/index.md
This PR is to address the fixes done in getsentry/sentry-php#822.
=> [PHP] Update description of the excluded_exceptions option

src/collections/_documentation/platforms/python/beam.md
related: https://github.com/getsentry/sentry/pull/14534
=> fix: Add minimum version of apache beam supported

src/collections/_documentation/platforms/go/config.md
=> Change SampleRate type to float64

src/collections/_documentation/clients/java/config.md
=> fix: Java custom SentryClientFactory example

src/collections/_documentation/platforms/react-native/index.md
**Currently**:
**After this PR:**
**Currently**:
**After this PR:**
=> (ref)React Native: Fix typo, code formatting, and format notes

src/collections/_documentation/error-reporting/configuration/config-intro/aspnetcore.md, src/collections/_documentation/error-reporting/getting-started-config/aspnetcore.md, src/collections/_documentation/platforms/dotnet/aspnetcore.md
=> feat: Sample for ASP.NETCore 3

src/collections/_documentation/guides/integrate-frontend/configure-scms.md
Nobody likes things that hurt.
=> chore(proofreading): Remove pain

nginx.conf
=> fix(nginx): Fix a rewrite rule for DIF pages

src/collections/_documentation/workflow/integrations/legacy-integrations.md
=> Add mention of which plans we support

src/collections/_documentation/platforms/javascript/index.md
#1068 
Update JS example to use the Sentry Severity Constant
=> Update Set Level JS Example

src/collections/_documentation/workflow/search.md
Adds information about the new tags[] syntax going live soon.
=> Adding tags[] syntax blurb

src/collections/_documentation/workflow/search.md
I prefer this wording...and product_id was just wrong.
=> fix(text): Changing the text

src/collections/_documentation/platforms/index.md
Flutter wasn't showing up with any Search results. Added flutter to keywords in front matter.
=> Fix/ added Flutter to keywords

src/collections/_documentation/guides/alert-notifications/index.md, src/collections/_documentation/guides/integrate-frontend/configure-scms.md, src/collections/_documentation/guides/integrate-frontend/create-new-project.md, src/collections/_documentation/guides/integrate-frontend/generate-first-error.md, src/collections/_documentation/guides/integrate-frontend/index.md, src/collections/_documentation/guides/integrate-frontend/initialize-sentry-sdk.md, src/collections/_documentation/guides/integrate-frontend/upload-source-maps.md
Ido made a great Guide inside of Docs. Just going through the content and doing some sprucing up.
=> Update/ Grammar and Spelling for Guides

src/collections/_documentation/development/sdk-dev/unified-api.md, src/collections/_documentation/guides/alert-notifications/creating-custom-rules.md, src/collections/_documentation/guides/integrate-frontend/configure-scms.md, src/collections/_documentation/server/sso.md
Adding folks as reviewers based on GitHub's suggestions.
=> fix: Address the double "the"s

__tests__/__snapshots__/documentation.js.snap, src/collections/_documentation/platforms/python/index.md, src/collections/_documentation/platforms/python/pyspark.md
Documentation for PySpark
Dependent on https://github.com/getsentry/sentry-python/pull/519/
=> Add documentation for PySpark

src/collections/_documentation/development/sdk-dev/event-payloads/exception.md
Please check the field name is correct. I think it should be changed to 'mechanism' following documents. Or is it alias?
=> Json example in exception interface

src/collections/_documentation/clients/ruby/context.md
Ref:
- https://github.com/getsentry/raven-ruby/releases/tag/v2.12.0
- https://github.com/getsentry/raven-ruby/pull/920
=> feat: Scope of tags_context/extra_context in Ruby

src/collections/_documentation/workflow/releases.md
Fixes https://app.asana.com/0/1144304343179777/1146130459036962/f
=> ref(docs): Clarify wording in releases documentation

src/collections/_documentation/platforms/node/pluggable-integrations.md
Hello,
Just something I found while browsing the docs. I hope it helps.
Thanks for the nice documentation.
=> A small typo and a grammar fix

src/collections/_documentation/development/sdk-dev/event-payloads/index.md
fixes documentation problem raised in https://github.com/getsentry/sentry/issues/6576
=> add max tag length

src/collections/_documentation/clients/ruby/integrations.md
=> Fix markup

src/collections/_documentation/clients/java/integrations.md
fix: https://github.com/getsentry/sentry-docs/issues/1228
=> fixed anr docs

src/collections/_documentation/platforms/javascript/index.md
Customer wrote in and asked for more communication regarding config for JS. This link will help them find that page.
=> added link to CLI config and authentication

src/collections/_documentation/platforms/node/index.md
=> Add mention of using aws lambda node

src/collections/_documentation/clients/java/usage.md
Fixes: [GROW-508](https://getsentry.atlassian.net/browse/GROW-508)
=> fix(java): Expose DSN in example code

src/collections/_documentation/clients/ruby/processors.md
Edit docs to reflect how to actually add processors to sentry config
=> docs: Update processors.md to be correct on adding processors to config chain

src/collections/_documentation/data-management/sensitive-data.md
Fixes https://app.asana.com/0/1144304343179777/1146130459036962
=> ref(docs): Clarify which data structures we scrub

src/collections/_documentation/cli/dif.md, src/collections/_documentation/workflow/debug-files.md
Ref https://github.com/getsentry/sentry-cli/pull/619
=> feat(sentry-cli): Document upload-dif --wait

__tests__/__snapshots__/documentation.js.snap, src/collections/_documentation/platforms/node/serverless.md
Some Node customers need a serverless option with AWD Lambda. Created a page for them to use as a reference.
=> Update Node instructions for serverless with AWS Lambda

src/collections/_documentation/platforms/react-native/cocoapods.md
Specificed a podspec file not a path.
=> Update cocoapods instructions from path -> podspec

src/collections/_documentation/platforms/go/iris.md
Updates taken from already merged README.md update in the main repo, so no need to double-check them https://github.com/getsentry/sentry-go/pull/78
@MimiDumpling feel free to merge them directly yourself :)
=> docs(go): Update Go Iris integration to v12

src/collections/_documentation/platforms/node/default-integrations.md, src/collections/_documentation/platforms/node/index.md
Introduced in the latest release.
=> docs(node): Update unhandled rejection handler options

src/collections/_documentation/workflow/notifications/index.md
Forgot a link to Project Settings. Added the link.
=> Add link to Notifications index page

__tests__/__snapshots__/documentation.js.snap, src/collections/_documentation/platforms/go/goroutines.md, src/collections/_documentation/platforms/go/index.md, src/collections/_documentation/platforms/go/integrations.md, src/collections/_documentation/platforms/go/migration.md, src/collections/_documentation/platforms/go/panics.md, src/collections/_documentation/platforms/go/serverless.md, src/collections/_documentation/platforms/go/transports.md
Closes https://github.com/getsentry/sentry-go/issues/61
=> docs(go): Add section about handling panics

src/collections/_documentation/api/organizations/index.md
Forgot to include this in my previous PR #1336 :)
=> Add get-organization-users link to index

src/collections/_documentation/clients/node/typescript.md
=> Missing statement

src/collections/_documentation/development/sdk-dev/features.md, src/collections/_documentation/development/sdk-dev/overview.md, src/collections/_documentation/development/sdk-dev/unified-api.md
Small updates as I was reading the docs :)
=> Miscellaneous fixes

src/collections/_documentation/server/installation/index.md
The Self-Hosted install page was recently updated. I went through and cleaned up some spelling/grammar/language.
=> Updated self-hosted index page

src/_data/documentation_categories.yml, src/collections/_documentation/accounts/membership.md
Also renames the membrship page to 'Organization Management' to cover
more topics than just membership.
=> feat: Add docs to transfer a project / Remove an org

src/collections/_documentation/clients/cocoa/index.md
SPM support will come soon.
Updated docs accordingly. Added heading to every install method, since we have 3 distinct install methods now.
=> sentry-cocoa: adds SPM. adds heading to install methods.

src/collections/_documentation/data-management/event-grouping/grouping-enhancements.md
Once a copy-editor, always a copy-editor.
=> fix(language): Tiny tweaks to the grouping enhancement page 

src/collections/_documentation/platforms/javascript/index.md
Went through the JS index page and removed any sections that feel "too noisy." The goal was to trim the page a bit because it's so massive. Let me know if any topics need to stay instead of being removed.
=> Update JS index page

src/collections/_documentation/cli/configuration.md
Minor fixes to CLI config docs
=> CLI Configuration typos and grammar fixes

src/collections/_documentation/clients/cocoa/advanced.md
=> Add shouldSendEvent snippet in Cocoa docs

src/collections/_documentation/platforms/node/typescript.md
@MimiDumpling can you please check the wording here? I'm sure it can be better 😅
=> docs: Add dealing with TSLib section to TypeScript docs

src/collections/_documentation/workflow/release-examples/javascript.md, src/collections/_documentation/workflow/releases.md, src/collections/_documentation/workflow/set-release/csharp.md, src/collections/_documentation/workflow/set-release/go.md, src/collections/_documentation/workflow/set-release/javascript.md, src/collections/_documentation/workflow/set-release/native.md, src/collections/_documentation/workflow/set-release/php.md, src/collections/_documentation/workflow/set-release/python.md, src/collections/_documentation/workflow/set-release/rust.md
=> Add Javascript Example to Releases Documentation

src/collections/_documentation/platforms/python/django.md
Fixes https://app.asana.com/0/1144304343179777/1144580065042341
=> feat(django): Mention send_default_pii in config example

src/collections/_documentation/platforms/javascript/react.md
Removed not used `error` argument
=> removed not used error argument.

src/collections/_documentation/clients/java/integrations.md
fix: https://github.com/getsentry/sentry-java/issues/802
=> fix anr typo on docs

_config.yml, src/_plugins/algolia_hooks.rb
- index code/pre blocks
- correct indexing of platforms
=> Various fixes for search

src/collections/_documentation/workflow/search.md
Add an example of how to combine these as well as the fact that you can search on `message`, which is pretty useful.
=> Add negation + wildcard example and message param

src/collections/_documentation/error-reporting/configuration/index.md
=> in-app-include is now supported by PHP

src/collections/_documentation/cli/configuration.md
Sentry DSN is supported in the CLI.
=> Adds SENTRY_DSN information

src/collections/_documentation/server/cli/createuser/index.md
Documentation for:
https://github.com/getsentry/sentry/pull/16440
=> docs: adds docs for fix-6763

src/collections/_documentation/platforms/go/index.md
Matching changes from getsentry/sentry-go#152.
=> docs(go): Update example and note about Flush

src/collections/_documentation/platforms/python/default-integrations.md
One typo, a few spots where it seemed like it could be a tiny bit clearer.
=> ref(language): Wordsmith Python default integrations page

src/collections/_documentation/server/sso.md
Fixes an [issue reported on the forum](https://forum.sentry.io/t/upgrade-9-0-with-github-sso-9-1-internal-server-error/8613?u=byk) and getsentry/onpremise#373.
=> fix(sso): Update and simplify SSO docs

src/collections/_documentation/error-reporting/configuration/index.md
=> Add blurb about reading in env vars for config

src/collections/_documentation/platforms/android/index.md
fix docs for https://github.com/getsentry/sentry-java/pull/815
=> support of uploading native symbols and source code

src/collections/_documentation/development/contribute/environment.md
Blocked by https://github.com/getsentry/sentry/pull/16785 and https://github.com/getsentry/getsentry/pull/3556.
=> feat: direnv setup instructions

src/collections/_documentation/server/integrations/github/index.md
Follow up to #1487, addressing https://git.io/JvZMx
=> fix(github): Fix GitHub SSO Auth URL

src/collections/_documentation/platforms/node/connect.md, src/collections/_documentation/platforms/node/express.md
ref: https://github.com/getsentry/sentry-javascript/pull/2467
=> docs: Node client ip address extraction

src/collections/_documentation/performance/distributed-tracing.md
Updated spacing in the JavaScript and Node.js code examples.
=> Update: distributed tracing

src/collections/_documentation/performance/discover/index.md
First paragraph of Discover needed an update.
**BEFORE:**
**AFTER:**
=> updated first paragraph

src/collections/_documentation/data-management/advanced-datascrubbing.md
Given that we no longer expose the PII config in its rawest form the
documentation is now outdated and can also be a lot simpler.
=> ref(pii): Update/trim documentation for new UI

src/collections/_documentation/platforms/python/logging.md
=> fix(python) Use exception instead of error

src/collections/_documentation/clients/ruby/index.md
=> Update Ruby version

nginx.conf
Docs need an update for Visibility (now called Dashboards) and Discover (now nested under Performance).
=> Redirects for Visibility and Discover v1

src/collections/_documentation/platforms/javascript/index.md
Closes https://github.com/getsentry/sentry-javascript/issues/2518
=> docs(js): CORS and different origins

src/collections/_documentation/platforms/javascript/getting-started-dsn/react.md
Local files use relative import
=> fix typo in react documentation

src/collections/_documentation/development/sdk-dev/event-payloads/exception.md
=> Remove broken internal link, add missing link

src/collections/_documentation/development/sdk-dev/unified-api.md
We will remove the internal notion doc
=> ref: Small changes to unified SDK docs

src/collections/_documentation/development/sdk-dev/event-payloads/contexts.md
Getting it better step by step.
=> ref(sdk-dev): Improve Contexts Interface docs

src/collections/_documentation/workflow/alerts-notifications/index.md
Link for Issue Owners went to the wrong page. Updated with correct link.
=> fixed link for Issue Owners

src/collections/_documentation/platforms/cocoa/index.md
Just noticed the document went on to say `as described in the previous example.` so adding more information on how to do that after the basic setup.
=> describe how to change the session timeout

src/collections/_documentation/platforms/cocoa/enableAutoSessionTracking/objc.md, src/collections/_documentation/platforms/cocoa/enableAutoSessionTracking/swift.md, src/collections/_documentation/platforms/cocoa/index.md, src/collections/_documentation/platforms/cocoa/init/objc.md, src/collections/_documentation/platforms/cocoa/init/swift.md, src/collections/_documentation/platforms/cocoa/integrations/objc.md, src/collections/_documentation/platforms/cocoa/integrations/swift.md, src/collections/_documentation/platforms/cocoa/sessionTrackingIntervalMillis/objc.md, src/collections/_documentation/platforms/cocoa/sessionTrackingIntervalMillis/swift.md
- beta.4
- Session Health Changes
=> fix[sentry-cocoa]: Use new Start Syntax

src/collections/_documentation/performance/distributed-tracing.md
Changing from marketing email to new mailbox.
=> Update Performance feedback email

src/collections/_documentation/workflow/alerts-notifications/alerts.md, src/collections/_documentation/workflow/alerts-notifications/index.md
=> updated alert box for Metric Alerts

src/collections/_documentation/platforms/python/celery.md
Formatting changes that make the code sample consistent with other code samples, say https://docs.sentry.io/platforms/python/redis/
=> Consistency with other pages & better line length.

src/collections/_documentation/workflow/releases/index.md
Closes https://github.com/getsentry/sentry-cli/issues/723
=> docs(cli): Mention Working with Projects section inside cli workflow docs

src/collections/_documentation/platforms/cocoa/index.md, src/collections/_documentation/workflow/releases/health.md
remove beta markers from Cocoa SDK
=> update sdks versions

_config.yml, src/_includes/learn-sdk.md, src/_js/lib/UserContentUI.js
Just two typos and a comment. Clearing the decks for the next big project. :-)
=> chore: Fix tiny things

src/collections/_documentation/clients/cocoa/index.md
=> Added alert box to legacy Cocoa page

src/collections/_documentation/clients/java/integrations.md
=> add alert box for old Android Client

src/collections/_documentation/workflow/search.md
=> Add `release:latest` to Search docs

src/collections/_documentation/performance/discover/index.md
=> Add section about Performance Tab in Discover

src/collections/_documentation/performance/performance-homepage.md, src/collections/_documentation/performance/performance-metrics.md
=> Add: Beta note on new Performance pages

nginx.conf
=> onprem(config): Redirect /server/config to develop docs

src/collections/_documentation/performance/discover/index.md, src/collections/_documentation/performance/distributed-tracing.md, src/collections/_documentation/performance/performance-metrics.md
Merges metrics content from Distributed Tracing and Performance Metrics. Also, reorders the subpages in Performance to make Performance Metrics the index page.
=> Combine metrics content for Performance and Tracing

src/collections/_documentation/enriching-error-data/environments.md
https://www.dropbox.com/s/fdvj15or49cpc14/Screenshot%202020-04-23%2000.04.46.png?dl=0
=> Correct the restrictions on environment names.

src/collections/_documentation/platforms/javascript/angular.md, src/collections/_documentation/platforms/javascript/index.md
Merge only once sentry-javascript `5.16.0` is released.
=> docs(js): Rewrite Angular documentation and add TryCatch options

src/collections/_documentation/platforms/android/index.md, src/collections/_documentation/platforms/cocoa/index.md, src/collections/_documentation/platforms/react-native/index.md
@MimiDumpling reviews from #1720
Please note a section there is copied over into 3 docs, maybe we can use an include instead?
=> fix spelling

src/collections/_documentation/enriching-error-data/environments.md
=> Update: Environments first paragraph

src/collections/_documentation/data-management/advanced-datascrubbing.md
Write example in a way where it does not assume too much about how the UI looks.
=> fix(data-scrubbing): Update example to match new UI

src/collections/_documentation/clients/javascript/config.md, src/collections/_documentation/clients/javascript/usage.md, src/collections/_documentation/platforms/python/flask.md, src/collections/_documentation/workflow/integrations/global-integrations.md, src/collections/_documentation/workflow/integrations/integration-platform/index.md, src/collections/_documentation/workflow/integrations/integration-platform/ui-components.md
=> fix(md): html escaping issues in code block

src/collections/_documentation/accounts/quotas/index.md, src/collections/_documentation/accounts/quotas/manage-event-stream-guide.md
Fixing terminology in content describing block lists.
=> Update terminology, descriptors

src/_includes/tracking_widget.html
This matches our other sites and style guide
=> Feat: Update tracking widget for consistency

src/collections/_documentation/platforms/android/index.md
placing it in the right section.
=> fix: move multidex support to the Advanced Usage section

src/collections/_documentation/performance/getting-started/javascript.md
ref: https://forum.sentry.io/t/sentrys-apm-docs-alpha/7843/6?u=hazat
`@sentry/tracing` is not yet released
=> fix: Import

src/collections/_documentation/platforms/python/sanic.md
Fix https://github.com/getsentry/sentry-python/issues/720
=> fix: Make it more explicit which versions we support

src/collections/_documentation/platforms/javascript/index.md
=> docs: Add section about adblockers in JS documentation

src/collections/_documentation/performance-monitoring/performance/transaction-summary.md
=> feat(perf-summary): added metrics sidebar links

__tests__/__snapshots__/documentation.js.snap, src/collections/_documentation/platforms/react-native/touchevents.md
Add docs describing how to use the new touch events feature for `@sentry/react-native` soon to be introduced.
=> feat: Docs for react native touch events

src/collections/_documentation/performance-monitoring/configuration/javascript.md, src/collections/_documentation/performance-monitoring/configuration/python.md, src/collections/_documentation/performance-monitoring/getting-started.md, src/collections/_documentation/performance-monitoring/performance/event-detail.md
Fix: remove duplicates and reformat sections of Performance
=> Fix: remove duplicates and reformat sections of Performance

gatsby/src/components/codeBlock.js, gatsby/src/components/codeContext.js, gatsby/src/components/codeTabs.js, gatsby/src/components/content.js
- Correct error handling on XHR requests
- Ensure defaults are always present
- Restore pre-existing behavior with contextual variables
=> Various fixes for code blocks

src/collections/_documentation/performance-monitoring/configuration/python.md
Python Performance installation instructions needed some updating.
=> Fix: Performance installation instructions

src/collections/_documentation/performance-monitoring/performance/index.md, src/collections/_documentation/performance-monitoring/performance/transaction-summary.md
=> small grammar fixes

src/collections/_documentation/platforms/android/index.md
Fix getsentry/sentry-java/issues/727
Also getsentry/sentry-android-gradle-plugin/issues/8
=> be explicit about the sentry conf. file in the root folder for the Android Gradle Plugin

src/collections/_documentation/platforms/javascript/index.md, src/collections/_documentation/platforms/javascript/sourcemaps.md, src/collections/_documentation/workflow/releases/index.md
Please do not merge before the functionality will be enabled.
=> Update location of the source maps in the UI.

src/collections/_documentation/performance-monitoring/configuration/javascript.md
Updated code example to have options for CDN and without CDN.
=> Update: Performance JS instructions for CDN and without CDN

server.js, src/_layouts/legacy-client.html
=> fix: Make url to open more clear

src/collections/_documentation/performance-monitoring/configuration/javascript.md, src/collections/_documentation/performance-monitoring/configuration/koa.md, src/collections/_documentation/performance-monitoring/configuration/node.md, src/collections/_documentation/performance-monitoring/configuration/python.md, src/collections/_documentation/performance-monitoring/configuration/react.md, src/collections/_documentation/performance-monitoring/configuration/vue.md
& tracingOrigins clarification
=> ref: Sample Rate wording

src/collections/_documentation/cli/releases.md
=> Update: cli release for mobile

src/collections/_documentation/cli/releases.md
Missed Mimi's feedback https://github.com/getsentry/sentry-docs/pull/1823#discussion_r448668363 before merging
=> fix: Formatting content

src/collections/_documentation/accounts/pricing.md, src/collections/_documentation/accounts/quotas/index.md
Updates to the FAQs for Pricing and Quotas content to support new pricing model.
=> Pricing and Quotas content update

src/collections/_documentation/performance-monitoring/getting-started.md
=> Remove beta flag for Performance Monitoring

src/collections/_documentation/cli/configuration.md, src/collections/_documentation/cli/releases.md, src/collections/_documentation/clients/javascript/integrations.md, src/collections/_documentation/clients/react-native/cocoapods.md, src/collections/_documentation/clients/react-native/index.md, src/collections/_documentation/platforms/react-native/hermes.md, src/collections/_documentation/platforms/react-native/index.md, src/collections/_documentation/platforms/react-native/manual-setup.md
Updated instances of "react-native" -- that aren't code based -- to "React Native."
=> Update: instances of react-native that aren't code based

gatsby/src/includes/user-feedback-example/aspnetcore.mdx, gatsby/src/includes/user-feedback-example/flask.mdx, gatsby/src/includes/user-feedback-example/javascript.mdx, gatsby/src/includes/user-feedback-example/laravel.mdx, gatsby/src/includes/user-feedback-example/php.mdx
- Fixes grammatical mistake in use-feedback-example files
=> Docs: Fixes typo in user-feedback-example files

nginx.conf, server.js
Update nginx.conf and server.js for the JS SDK docs.
=> Update SDK folder for Gatsby

src/_includes/platforms/python/request-data.md
Fix https://github.com/getsentry/sentry-python/issues/769
=> fix: Clarify how scopes work in Flask/Django

src/_includes/platforms/python/request-data.md
Follow-up on https://github.com/getsentry/sentry-docs/pull/1937.
=> fix: Clarify request scope once again

gatsby/src/components/sidebar.js
Starting to move a few things around. Sharing with Daniel so we can manage the banner and robots noindex and variables.
=> {WIP} Update/platforms sidebar

gatsby/src/docs/accounts/quotas/index.mdx
`custom-inbound-filters` and `discard-groups` are available on the Business plan
=> fix(docs): Fix custom inbound filter plan

src/collections/_documentation/performance-monitoring/performance/metrics.md
Updating the docs to reflect the actual threshold for frustrated users.
=> ref(AM): Define `Frustration` threshold accurately

gatsby/plugins/gatsby-plugin-sentry-wizard/gatsby-node.js
We were hitting what appears to be a race condition due to this, and while the function calls appear correct, moving to sync has fixed the issue.
=> ref: Move to sync functions

gatsby/src/docs/workflow/search/index.mdx
=> Add: Definitions for non-aggregates and aggregates

gatsby/package.json, gatsby/plugins/gatsby-plugin-sentry-wizard/gatsby-node.js, gatsby/yarn.lock
- Remove permalink icons
- Add highlight class to code block
=> fix: Correct styles on wizard

src/docs/performance-monitoring/getting-started.mdx
Removing references to Beta and providing some details around adding transactions to subscription
=> ref(AM): Update Getting Started w/ Performance

src/wizard/csharp/index.md
Fixes https://github.com/getsentry/sentry/issues/20117
=> Updated C# docs to fix markdown error

src/includes/performance-monitoring/configuration/javascript.mdx
Removes duplicate code lines at the end
=> fix(PerformanceMonitoring): Remove duplicate code from configuration example

src/docs/error-reporting/quickstart.mdx
Managing the current quickstart so that users can easily jump to Performance Monitoring.
=> Connecting PM to the quickstart

src/docs/sdks/javascript/errors/feedback.mdx, src/docs/sdks/javascript/integrations/custom.mdx, src/docs/sdks/javascript/integrations/plugin.mdx
Needs to be all caps to be dynamically replaced with user's DSN
https://docs.sentry.io/sdks/javascript/errors/feedback/#integrate-the-feedback-widget
https://docs.sentry.io/sdks/javascript/config/filter/#using-before-send
=> fix: Public_DSN => PUBLIC_DSN

plugins/gatsby-plugin-sentry-wizard/gatsby-node.js, src/docs/platforms/javascript/ember/index.mdx, src/docs/platforms/javascript/vue/index.mdx, src/wizard/javascript/angular.md, src/wizard/javascript/browser.md, src/wizard/javascript/ember.md, src/wizard/javascript/index.md, src/wizard/javascript/vue.md
Fixes an issue in wizard generation so that markdown processing is ensured to happen first.
=> ref: Remove hardcoded versions

plugins/gatsby-plugin-code-tabs/index.js, src/components/codeBlock.js, src/components/codeTabs.js, src/docs/platforms/javascript/index.mdx
Also removes ordering in CodeTabs so we can be explicit.
=> fix: Correct js instructions for esm

src/components/breadcrumbs.js, src/components/layout.js
=> feat: Add breadcrumbs

src/docs/cli/configuration.mdx
I was reading the docs and saw that the code blocks were slightly off, so I figured I'd fix it really quick.
This is my first time submitting a PR to this repo, so while I scanned the CoC let me know if there's more I should do.
=> Fix: Correct Markdown Code Block Fences

src/platforms/rust/guides/actix-web/index.mdx, src/platforms/rust/index.mdx
- Move actix-web into guides
- Add quickstart information to index
=> feat: Overhaul Rust docs

src/docs/product/integrations/index.mdx
Updated index page for Integrations to differentiate org level vs project level integrations. Also added tables to communicate integrations features and their associated integrations.
=> Update: Integrations index/landing page

src/platforms/react-native/advanced-setup.mdx, src/platforms/react-native/cocoapods.mdx, src/platforms/react-native/codepush.mdx, src/platforms/react-native/expo.mdx, src/platforms/react-native/hermes.mdx, src/platforms/react-native/index.mdx, src/platforms/react-native/migration.mdx, src/platforms/react-native/ram-bundles.mdx, src/platforms/react-native/sourcemaps.mdx, src/platforms/react-native/touchevents.mdx
- Various language
- Move manual setup to advanced setup
=> feat: Overhaul RN docs

src/platforms/index.mdx
=> fix: broken smart link

src/docs/product/alerts-notifications/alerts.mdx
Please don't merge until I remove the feature flag for this
=> Add PagerDuty to list of available metric alert actions

src/platforms/javascript/common/integrations/default.mdx
And swap the order of the last two sentences for clarity.
=> fix: Replace non-inclusive language

src/wizard/javascript/angular.md
Tried the code out and it works.
=> feat: Add tracing to angular wizard

package.json, src/components/basePage.tsx, src/components/layout.tsx, src/components/navbar.tsx, src/components/search.tsx, yarn.lock
This passes the current page path and platforms to the search lib so it'll prioritize.
=> Feat: priority search results

src/docs/product/integrations/bitbucket/index.mdx, src/docs/product/integrations/github/index.mdx, src/docs/product/integrations/gitlab/index.mdx, src/docs/product/integrations/jira/index.mdx
Each on-prem integration should have a troubleshoot section regarding IP addresses.
=> Add: Troubleshoot section to on-prem integrations

src/docs/accounts/quotas/manage-event-stream-guide.mdx, src/docs/clients/cocoa/migration.mdx, src/docs/clients/javascript/integrations.mdx, src/docs/clients/javascript/tips.mdx, src/docs/clients/javascript/usage.mdx, src/docs/product/sentry-basics/guides/getting-started/index.mdx
And a few more improvements in surrounding text.
=> fix: checkout -> check out

src/docs/accounts/quotas/manage-event-stream-guide.mdx, src/docs/clients/cocoa/migration.mdx, src/docs/clients/javascript/index.mdx, src/docs/clients/javascript/integrations.mdx
This is a follow up from https://github.com/getsentry/sentry-docs/pull/2116#pullrequestreview-477862150, thanks @PeloWriter for all the suggested edits.
=> fix: Several small language changes

src/platforms/php/common/config.mdx
#stepbystep
Update the documented php options. First step bringing it to the new structure.
=> feat: Update php options

src/docs/meta/terms.md
=> updated url to point to our new dpa.

nginx.conf, vercel.json
Follow up to getsentry/develop#123
=> ref(onpremise): Point on-premise redirects to develop/onpremise

src/wizard/python/pyramid.md
Updated a few things:
1. Turned this into a working Pyramid application similar to other languages/frameworks
2. Added an error and performance example
3. Fixed indentation
=> Add performance to pyramid docs

src/platforms/native/guides/ue4/advanced-config.mdx, src/platforms/native/guides/ue4/releases.mdx
The releases part is a bit of copy paste all over the docs atm. We should be able to reuse text here.
=> feat(unreal): Document custom properties/releases

src/css/_includes/index.scss
Sorry for the double branch/PR
=> switching to flex for logos in home hero

src/components/basePage.tsx, src/templates/platform.tsx
=> feat: Add platform/guide name to SEO title

src/utils/algolia.js
Another step toward normalizing our algolia records. I'll remove the dupes later once the search lib has been updated.
=> Feat: normalize index keys

src/platforms/common/configuration/capture.mdx, src/platforms/javascript/common/configuration/install-cdn.mdx
The page is now named "Advanced Capturing" - feedback welcome
Also added missing frontmatter to the CDN file.
=> Move capture info into configuration 

src/platforms/javascript/common/performance.mdx, src/platforms/javascript/index.mdx
Closes https://github.com/getsentry/sentry-docs/pull/2195
=> ref: Remove notes about apm

src/platforms/java/guides/logback/index.mdx, src/wizard/java/logback.md
Follow up on #2199, fixing other occurrences of the same broken link.
=> fix: Broken links

src/platforms/index.mdx
=> Add AdonisJS

vercel.json
=> fix(redirect): Send /server/queue to develop/services/queue

src/platforms/dotnet/index.mdx, src/platforms/php/common/configuration/transports.mdx
Amends b19e172c5fa56faa26eca1eff26d7c5d1bb4db8c.
=> fix: Use HTTPS in links where possible (take 2)

src/gatsby/config.ts, src/gatsby/utils/algolia.ts
I'd previously configured this in the wrong place.
=> fix: add partial updates

package.json, src/components/platformIcon.tsx, yarn.lock
=> feat(logo-update): changing svg source

src/components/platformIcon.tsx
=> fix: dotnet logo

src/platforms/javascript/common/sourcemaps/index.mdx
Updates 84d8a9375bfa997632fe792655a6a1bc004c2a46
Follows up on #2215 and #2253
=> fix: Add redirect from old URL

.gitignore, src/docs/product/integrations/integration-platform/webhooks.mdx
- Clean up the page and make the sections consistent.
- Add a section for Metric Alerts
=> Add SentryApp Metric Alerts webhook section

.vscode/extensions.json
We don't use Liquid anymore, but we do use mdx.
=> chore(VSCode): Update extension recommendations

package.json
If we can fix everything (`yarn prettier:fix:all`) it's nice to be able to check everything, too.
=> feat(build): Add `prettier:check:all` to package.json

src/docs/product/relay/best-practices.mdx, src/docs/product/relay/index.mdx
=> feat(relay): Add a section with best practices for external relays

src/platforms/javascript/guides/gatsby/index.mdx, src/wizard/javascript/gatsby.md
=> feat: Improve Gatsby docs

bin/lint-docs.js
Currently only identifies missing wizard content.
=> feat: Add tool to look for core doc issues

src/gatsby/config.ts, src/gatsby/createPages/createApiPages.ts, src/gatsby/createPages/createDevelopmentApiReference.ts, src/gatsby/createPages/createDocPages.ts, src/gatsby/createPages/createInternalDocPages.ts, src/gatsby/createPages/createPlatformPages.ts, src/gatsby/utils/algolia.ts
this will let us add searchable terms to docs that don't appear within the content
=> feat: index keywords

src/api/pagination.mdx
I found that the first two lines added confusion about pagination, so I removed them. I also reworded the last line of the paragraph.
=> feat: Clarify pagination doc page

src/css/_includes/development-api.scss, src/gatsby/config.ts, src/templates/developmentApi.tsx
=> fix: Update styles + link

src/gatsby/config.ts
Updates to latest version of https://github.com/getsentry/sentry-api-schema
=> feat(api-docs): Update SHA to include event payloads

src/gatsby/config.ts
Updates to latest version of https://github.com/getsentry/sentry-api-schema which includes example requests for PUT and POST endpoints, fixes a couple responses, and standardizes capitalization and punctuation.
=> feat(api-docs): Update SHA to include PUT & POST request examples

src/gatsby/config.ts, src/gatsby/createPages/createDevelopmentApiDocPages.ts, src/templates/developmentApi.tsx
- Add header for Content-Type
- Add flag for PUT request
- Handle multipart/form-data
=> feat: Improve cURL display logic

src/docs/product/relay/best-practices.mdx, src/docs/product/relay/getting-started.mdx
* Turn the list into a table
* Add "Network" section
* Update Docker instructions
* A few other minor fixes
The first PR: #2255 
---
Preview:
=> relay: Refactor best-practices page

src/gatsby/onPostBuild.ts, src/wizard/apple/index.md, src/wizard/apple/ios.md, src/wizard/apple/macos.md, src/wizard/minidump/index.md
- Ensure all wizard links are absolute
- Hard error on invalid relative links
=> fix: Correct links in wizard

src/platforms/common/configuration/options.mdx
=> fix: Re-add normalize depth for JS and Node

src/components/codeContext.tsx, src/docs/product/security-policy-reporting.mdx, src/platforms/javascript/common/sourcemaps/index.mdx, src/platforms/javascript/common/sourcemaps/tools/webpack.mdx, src/platforms/javascript/common/sourcemaps/troubleshooting_js.mdx
- Remove ORG_NAME and PROJECT_NAME as they create confusion
- Add ORG_INGEST_DOMAIN
- Remove useless config in webpack example
=> ref: Various cleanup

.dockerignore, Dockerfile
Not sure where this is used but I wanted to fix while I'm working on something related.
=> ref(docker): More optimized Docker stuff

src/docs/product/relay/getting-started.mdx
=> ref(relay): Inline docker instructions into getting started guide

src/platforms/javascript/guides/vue/index.mdx
=> Fix typo in Vue integration docs

src/components/pageGrid.tsx, src/docs/contributing/pages/components.mdx, src/platforms/common/configuration/index.mdx, src/platforms/common/data-management/index.mdx, src/platforms/common/enriching-events/index.mdx, src/platforms/common/usage/index.mdx, src/platforms/javascript/index.mdx, src/platforms/php/common/default-integrations.mdx, src/platforms/php/common/performance.mdx, src/platforms/php/index.mdx
- Add nextPages and header attributes to PageGrid
- Add sidebar_order to all sections
- Add descriptions for various pages
=> feat: Add auto generated next steps to PHP

src/components/basePage.tsx, src/components/seo.tsx, src/templates/doc.tsx, src/templates/platform.tsx, src/templates/wizardDebug.tsx
- Stop using frontmatter for toc
- Remove reference to file in SEO
=> fix: Standardize on page context for all page props

vercel.json
~This triggers a redirect chain that involves platform selector~
=> fix: Fix 404 of advanced data scrubbing

src/gatsby/createPages/createDocPages.ts, src/platforms/python/guides/aws-lambda/index.mdx, src/platforms/python/guides/gcp-functions/index.mdx
Support for Performance on Python/Servelress
=> redoing transaction updates for serverless in a new branch

src/gatsby/config.ts
=> ref: Remove yaml source

src/platforms/apple/common/install/cocoapods.mdx
=> iOS min version 9

src/includes/getting-started-install/apple.ios.mdx, src/includes/getting-started-install/apple.macos.mdx, src/includes/getting-started-install/apple.mdx, src/includes/getting-started-install/apple.tvos.mdx, src/includes/getting-started-install/apple.watchos.mdx, src/wizard/apple/index.md, src/wizard/apple/ios.md, src/wizard/apple/macos.md
Document minimum versions for iOS, tvOS, watchOS, and macOS.
=> feat(apple): Minimum OS versions

src/platforms/common/performance/sampling.mdx
=> fix(tracing): Fix typo in sampling precedence docs

src/wizard/android/index.md
I rather hard code the version now than make people go to GitHub.
We **need** to add craft on this repo.
=> improve android wizard

src/components/content.tsx, src/components/hooks/usePlatform.tsx, src/components/platformContent.tsx, src/docs/contributing/pages/components.mdx
- Remove unused fallbackPlatform
- Remove internal type from queries
=> ref: Minor optimization for PlatformContent

yarn.lock
Run `yarn-deduplicate yarn.lock` to deduplicate packages.
=> build(yarn): Deduplicate packages

src/docs/product/alerts-notifications/alert-settings.mdx, src/docs/product/alerts-notifications/index.mdx, src/docs/product/alerts-notifications/issue-alerts.mdx, src/docs/product/alerts-notifications/metric-alerts.mdx, src/docs/product/alerts-notifications/notifications/index.mdx
Updated Alerts & Notifications with some Adi suggestions.
=> Update: Alerts & Notifications

src/docs/product/accounts/quotas/index.mdx
Quotas page needed a little extra context on quota notification.
=> Add: content about Quota notification

src/docs/product/releases/health.mdx
Definition of Active Users in Release Health needed updating.
=> Update: active users definition

src/includes/capture-error/flutter.mdx, src/includes/capture-message/flutter.mdx, src/includes/configuration/config-intro/flutter.mdx, src/includes/set-context/flutter.mdx, src/includes/set-environment/flutter.mdx, src/includes/set-extra/flutter.mdx, src/includes/set-release/flutter.mdx
Adds code examples for the ff. in Flutter:
* Intro Config
* Set Context
* Set Environment
* Set Extra
* Set Release
* Error Capture
* Message Capture
Fixes #2309
=> feat: Add partial examples for using Sentry with flutter

src/docs/product/accounts/user-settings/index.mdx
Updated wording to encourage users to download their 2FA codes before they're lost.
=> Update: downloading 2FA codes

src/platforms/javascript/common/configuration/integrations/custom.mdx, src/platforms/javascript/common/configuration/integrations/default.mdx, src/platforms/javascript/common/configuration/integrations/plugin.mdx, src/platforms/javascript/common/configuration/integrations/rrweb.mdx
Added redirects for the move into Configuration
=> update JS integration redirects

src/platforms/java/guides/spring-boot/index.mdx
=> Improving spring boot docs

src/includes/sensitive-data/set-tag/_default.mdx, src/includes/sensitive-data/set-user/_default.mdx, src/platforms/common/data-management/sensitive-data/index.mdx
Adding a default for languages that don't yet have a code sample.
=> Add default for sensitive data includes

src/docs/product/accounts/quotas/manage-event-stream-guide.mdx
Some of this content assumes access to Discover, which isn't accurate for all customers. Thus, edited to what all users can do.
=> Update quotas doc to remove Discover

src/platforms/javascript/common/performance/index.mdx
Correcting function call to match import: addGlobalEventProcess -> addGlobalEventProcessor
=> Fixing grouping transaction example

src/platforms/android/common/proguard.mdx, src/platforms/android/migration.mdx
I've also raised https://github.com/getsentry/sentry-android-gradle-plugin/issues/30
=> fix: gradle plugin extra config

src/docs/product/integrations/gitlab/index.mdx
Going through old submitted PRs and adding what's relevant.
https://github.com/getsentry/sentry-docs/pull/1096
https://github.com/getsentry/sentry-docs/pull/760
https://github.com/getsentry/sentry-docs/pull/972
=> Add: clarification for GitLab

src/docs/product/security/ip-ranges.mdx
[WIP] Can't put down a concrete date since we haven't gotten the proper buy-in on when we're announcing the change.
Everything else is up for critique.
=> feat(ip-ranges): Add Organization Domain IP Address.

src/platforms/android/usage/advanced-usage.mdx
related https://github.com/getsentry/sentry-java/pull/977
=> fix: state the fixed version about the native pointers on android

src/includes/getting-started-config/python.flask.mdx
Adding traces_sample_rate enabling performance by default
=> Update flask config

src/platforms/javascript/guides/react/configuration/integrations/react-router.mdx, vercel.json
React Router Integration needed a redirect
=> Add: redirect for react router

src/platforms/common/data-management/event-grouping/grouping-enhancements.mdx, src/platforms/common/data-management/event-grouping/index.mdx, src/platforms/common/data-management/event-grouping/sdk-fingerprinting.mdx, src/platforms/common/data-management/event-grouping/server-side-fingerprinting.mdx
Small improvements to the Issue Grouping section of docs to alleviate Support tickets on the topic.
=> Update: Event Grouping

src/docs/contributing/platforms/index.mdx
All kinds of crazy things happen if you don't do this.
=> fix(dev): Add note about `supported`/`notSupported` for subtrees

src/docs/product/integrations/amazon-sqs/index.mdx, src/docs/product/integrations/amixr/index.mdx, src/docs/product/integrations/asana/index.mdx, src/docs/product/integrations/azure-devops/index.mdx, src/docs/product/integrations/bitbucket/index.mdx, src/docs/product/integrations/clickup/index.mdx, src/docs/product/integrations/clubhouse/index.mdx, src/docs/product/integrations/gcp-cloud-run/index.mdx, src/docs/product/integrations/github/index.mdx, src/docs/product/integrations/gitlab/index.mdx, src/docs/product/integrations/heroku/index.mdx, src/docs/product/integrations/integration-platform/index.mdx, src/docs/product/integrations/integration-platform/ui-components/index.mdx, src/docs/product/integrations/integration-platform/webhooks.mdx, src/docs/product/integrations/jira/index.mdx, src/docs/product/integrations/linear/index.mdx, src/docs/product/integrations/msteams/index.mdx, src/docs/product/integrations/pagerduty/index.mdx, src/docs/product/integrations/rookout/index.mdx, src/docs/product/integrations/slack/index.mdx, src/docs/product/integrations/split/index.mdx, src/docs/product/integrations/splunk/index.mdx, src/docs/product/integrations/teamwork/index.mdx, src/docs/product/integrations/vercel/index.mdx
Continuing work on front matter descriptions
=> Update: front matter descriptions

src/components/hooks/usePlatform.tsx, src/components/navbar.tsx, src/components/navbarPlatformDropdown.tsx, src/pages/index.tsx
- Move search box up
- Add standard dropdowns to header
=> feat: Improve navigation from homepage

src/platforms/apple/common/enriching-events/user-feedback.mdx
Add documentation about user feedback on Apple.
=> feat(apple): Add docs on user feedback

src/docs/product/security/index.md, src/docs/product/security/ip-ranges.mdx, src/docs/product/security/soc2.md, src/docs/product/security/ssl.mdx, src/docs/product/security/terms.md
Docs in the Security section needed descriptions in the front matter.
=> Add: front matter descriptions to Security

src/docs/product/releases/release-automation/bitbucket-pipelines/index.mdx, src/docs/product/releases/release-automation/circleci/index.mdx, src/docs/product/releases/release-automation/github-actions/index.mdx, src/docs/product/releases/release-automation/index.mdx, src/docs/product/releases/release-automation/jenkins/index.mdx, src/docs/product/releases/release-automation/netlify/index.mdx, src/docs/product/releases/release-automation/travis-ci/index.mdx
Docs in the Releases section needed descriptions in the front matter.
=> Add: front matter descriptions to Releases

src/docs/product/accounts/index.mdx, src/docs/product/cli/configuration.mdx, src/docs/product/cli/dif.mdx, src/docs/product/cli/index.mdx, src/docs/product/cli/installation.mdx, src/docs/product/cli/releases.mdx, src/docs/product/cli/send-event.mdx, src/docs/product/error-monitoring/filtering/index.mdx, src/docs/product/index.mdx, src/docs/product/security-policy-reporting.mdx, src/docs/support/index.mdx
Updated last few Product docs with descriptions in the front matter.
=> Add: front matter description to remaining product docs

src/gatsby/utils/resolveOpenAPI.ts
Update comment to reflect new location of Github workflow.
=> fix(workflow): Update comment on a workflow dependency

src/wizard/java/index.md
Update the wizard for Java using the updated Getting Started content.
=> Update Java Wizard

src/platforms/dotnet/common/ignoring-exceptions.mdx, src/platforms/dotnet/common/unit-testing.mdx, src/platforms/javascript/common/configuration/sentry-testkit/index.mdx, src/platforms/javascript/common/install/cdn.mdx, src/platforms/javascript/common/install/lazy-load-sentry.mdx, src/platforms/javascript/common/install/npm.mdx, src/platforms/javascript/common/sourcemaps/hosting-publicly.mdx, src/platforms/javascript/common/sourcemaps/multiple-origins.mdx, src/platforms/javascript/common/sourcemaps/troubleshooting_js.mdx, src/platforms/javascript/common/sourcemaps/uploading.mdx, src/platforms/javascript/common/sourcemaps/validating.mdx
A few files in the Common directories needed front matter descriptions.
=> Add: front matter descriptions to files in common Part II

src/platforms/android/common/enriching-events/context/default-context.mdx, src/platforms/android/common/proguard.mdx, src/platforms/apple/common/install/carthage.mdx, src/platforms/apple/common/install/cocoapods.mdx, src/platforms/apple/common/install/index.mdx, src/platforms/apple/common/install/swift-package-manager.mdx, src/platforms/common/configuration/index.mdx, src/platforms/common/data-management/data-forwarding.mdx, src/platforms/common/data-management/debug-files.mdx, src/platforms/common/data-management/event-grouping/grouping-enhancements.mdx, src/platforms/common/data-management/event-grouping/index.mdx, src/platforms/common/data-management/event-grouping/sdk-fingerprinting.mdx, src/platforms/common/data-management/event-grouping/server-side-fingerprinting.mdx, src/platforms/common/data-management/sensitive-data/advanced-datascrubbing.mdx, src/platforms/common/data-management/sensitive-data/index.mdx, src/platforms/common/enriching-events/context.mdx, src/platforms/common/enriching-events/identify-user.mdx, src/platforms/common/enriching-events/tags.mdx, src/platforms/common/usage/set-level.mdx
A few files in the Common directories needed front matter descriptions.
=> Add: front matter descriptions to files in common

src/platforms/native/common/debug-information.mdx, src/platforms/node/common/configuration/filtering/hints.mdx, src/platforms/node/common/configuration/integrations/default-integrations.mdx, src/platforms/node/common/configuration/integrations/index.mdx, src/platforms/node/common/configuration/integrations/pluggable-integrations.mdx, src/platforms/python/common/configuration/filtering/hints.mdx, src/platforms/python/common/configuration/integrations/default-integrations.mdx, src/platforms/python/common/configuration/integrations/django.mdx, src/platforms/python/common/configuration/integrations/flask.mdx, src/platforms/python/common/configuration/integrations/gnu_backtrace.mdx, src/platforms/python/common/configuration/integrations/pure_eval.mdx, src/platforms/python/common/configuration/integrations/redis.mdx, src/platforms/python/common/configuration/integrations/sqlalchemy.mdx, src/platforms/ruby/common/configuration/integrations.mdx, src/platforms/ruby/common/configuration/options.mdx, src/platforms/ruby/common/heroku.mdx, src/platforms/ruby/common/processors.mdx, src/platforms/ruby/common/usage.mdx
A few files in /common needed front matter descriptions.
=> Add: front matter descriptions to /common in /platforms

src/platforms/javascript/common/performance/index.mdx
=> fix(transactions): Fix typo

src/platforms/common/enriching-events/context.mdx
ref https://github.com/getsentry/sentry-python/issues/899
=> fix: Fix context types

src/platforms/android/integrations/timber.mdx, src/platforms/android/migration.mdx, src/platforms/go/common/configuration/options.mdx, src/platforms/javascript/common/configuration/integrations/default.mdx, src/platforms/javascript/common/configuration/integrations/plugin.mdx, src/platforms/javascript/common/install/lazy-load-sentry.mdx, src/platforms/javascript/guides/react/index.mdx, src/platforms/node/common/configuration/integrations/default-integrations.mdx, src/platforms/node/common/enriching-events/event-processors.mdx, src/platforms/ruby/common/configuration/integrations.mdx, src/platforms/ruby/common/configuration/options.mdx
Fixed several 404s with redirects.
=> Fix: 404s with redirects

src/platforms/python/guides/aiohttp/index.mdx
Documenting [PR](https://github.com/getsentry/sentry-python/pull/876) in sentry-python
=> Update aiohttp integration docs

src/platforms/android/common/enriching-events/user-feedback.mdx, src/platforms/apple/common/enriching-events/user-feedback.mdx, src/platforms/java/common/enriching-events/user-feedback.mdx
Only merge after releasing java 3.1.2
=> feat(java): Add docs for user feedback

src/docs/product/cli/send-event.mdx
Changed the example to public dsn.
=> Fix: public dsn

src/platforms/python/guides/gcp-functions/index.mdx
=> fix(typo): Remove stray AWS reference on CGP page

src/platforms/python/guides/pyramid/index.mdx, src/wizard/python/pyramid.md
https://github.com/getsentry/sentry-python/issues/909
=> fix: Add version constraint to Pyramid docs

src/platforms/dotnet/guides/wpf/index.mdx
Changing title (the original is too long)
adding explicit event subscription
/cc @Tyrrrz
=> wpf: subscribe to event

src/docs/product/alerts-notifications/notifications/index.mdx
Added the percentage event volume used to trigger a quota notification.
=> Add: percentage event volume 

src/wizard/javascript/browser.md, src/wizard/javascript/index.md
This PR uses the updated content from the Getting Started page for JS and inserts it into both the browser and JS wizard pages.
=> Update wizard content for JavaScript

src/platforms/java/guides/log4j2/advanced_usage.mdx, src/platforms/java/guides/logback/index.mdx
=> Clarify that MDC manages data on a per-thread basis.

src/docs/product/data-management-settings/attachment-scrubbing.mdx
Feedback from merged PR.  Thanks for still reviewing!
=> style: Some improvements to minidump scrubbing docs

src/docs/product/relay/index.mdx
Pretty sure these are both cons.
=> Fix typo in Relay docs

src/platforms/common/usage/index.mdx
I had to read that particular sentence thrice to understand what it is the intended meaning. 
Based on my understanding, I have now updated the wording. Cheers!
=> Fix confusing grammar

.github/workflows/test.yml
Getting some linenumber support here
=> chore: Update hyperlink

src/includes/getting-started-install/apple.watchos.mdx
Clarify that we have limited support for watchOS so users don't have wrong
expectations.
=> fix(apple): Limited support for watchOS

src/platforms/java/common/configuration/index.mdx
=> Java - add docs timeouts docs.

src/wizard/dotnet/awslambda.md
=> Wizard copy of the Lambda support for .NET

src/platforms/java/common/configuration/index.mdx
Fixes https://github.com/getsentry/sentry-java/issues/1072
=> Fix property names for proxy configuration.

src/api/auth.mdx
some additional information for those trying to generate/find on-prem auth tokens.
=> feat(auth): Add information about self-hosted auth tokens

src/platforms/javascript/common/install/lazy-load-sentry.mdx
Add the reference to the loader source code which contains a lot of useful comments.
=> docs(js): Update lazy-load-sentry.mdx

src/platforms/javascript/common/sourcemaps/tools/webpack.mdx
I think this is the right completion, but would appreciate if someone who has more knowledge about our webpack plugin could confirm.
=> fix(webpack-docs): Complete webpack docs sentence

src/docs/product/sentry-basics/search/index.mdx
=> Document how to filter by linked issue

src/platforms/node/common/performance/database.mdx
=> feat: Add node.js db docs

src/platforms/node/guides/express/index.mdx
Some newlines had gone on walkabout and landed in the wrong place.
=> fix(express): Group comments with the options to which they pertain

src/platforms/ruby/guides/rails/index.mdx
=> Fix typo in rails platform guide

src/platforms/apple/common/usage.mdx
Add know limitations to advanced usage as we also have it for [Flutter](https://docs.sentry.io/platforms/flutter/usage/advanced-usage/#known-limitations).
=> feat(apple): Add known limitations

.github/workflows/lock.yml
https://app.asana.com/0/1169344595888357/1198192573081731
=> Lock old closed issues and PRs

src/platforms/native/guides/ue4/index.mdx
Googling for this problem showed that forum post as the first result already (at least for me).
I had issues again setting this up and the ideas on that thread helped me. So pointing to it.
=> Point UE4 users to the forum

src/includes/getting-started-install/dart.mdx, src/includes/getting-started-install/flutter.mdx, src/wizard/dart/index.md, src/wizard/flutter/index.md
Dart and Flutter still not using craft or release registry
=> bump dart and flutter version

src/wizard/dotnet/winforms.md
=> feat(wizard): winforms

src/wizard/dotnet/wpf.md
=> feat: dotnet wpf

src/docs/product/integrations/gitlab/index.mdx
=> docs: fix typo

src/platforms/dotnet/guides/nlog/index.mdx
=> Fix NLog config example by placing Debug-option correctly

.github/workflows/lock.yml
https://github.com/getsentry/.github/issues/11
=> meta: Fork lockbot for security

src/platforms/flutter/usage/advanced-usage.mdx
=> Flutter split abi

src/docs/product/releases/health.mdx
=> ref(releases): Further clarify the meaning of "crashed" sessions

src/platforms/apple/config.yml
Opened because https://github.com/getsentry/sentry-docs/pull/2848 and https://github.com/getsentry/sentry-docs/pull/2840
=> feat(apple): Add categories to config

src/includes/getting-started-primer/java.spring.mdx
Fixes https://github.com/getsentry/sentry-java/issues/1051
=> Document minimum Spring Framework version.

src/includes/getting-started-primer/java.mdx, src/platforms/android/index.mdx
Just out of desperation, so the search shows something I want to mention Android and Java are also the place to go for folks looking for Kotlin. And we have code snippets already in Kotlin.
#2849 #2777
=> Mention support for Kotlin

src/platforms/common/data-management/event-grouping/fingerprint-rules.mdx
Follow up to https://github.com/getsentry/sentry/pull/22474
=> Added docs for new fingerprinting rule substitutions

src/docs/product/data-management-settings/server-side-scrubbing.mdx
Also fix remaining comments of https://github.com/getsentry/sentry-docs/issues/214
=> fix: Clarify usage of keys vs values

.github/CODEOWNERS
Expanding the codeowners file to include wizard and some platforms that didn't have any
=> Code owners for the wizard

src/docs/product/integrations/bitbucket/index.mdx, src/docs/product/integrations/github/index.mdx, src/docs/product/integrations/gitlab/index.mdx, src/docs/product/integrations/jira/index.mdx, src/platforms/apple/common/migration.mdx, src/platforms/javascript/common/sourcemaps/troubleshooting_js.mdx, src/platforms/react-native/migration.mdx
=> fix: It is on-premises, not on-premise

src/docs/product/cli/index.mdx, src/pages/index.tsx
Add keywords and link from homepage so CLI content is easier to find.
=> Better surface CLI content

src/platforms/javascript/common/troubleshooting/index.mdx
ref: https://github.com/getsentry/sentry-javascript/issues/3185#issuecomment-764548711
=> docs(javascript): Add sentry-trace header troubleshooting entry

src/wizard/java/spring-boot.md
Update the Spring Boot wizard as noted in https://github.com/getsentry/sentry-docs/issues/2897
=> Update Spring Boot wizard

src/wizard/java/log4j2.md
Add wizard to support log4j2 as noted in issue https://github.com/getsentry/sentry-docs/issues/2897.
=> Add log4j2 wizard

src/wizard/java/logback.md
Adding a wizard for the Logback integration as noted in issue #2897.
=> Add Logback wizard

src/wizard/java/spring.md
Adding a wizard for Spring integration as noted in issue https://github.com/getsentry/sentry-docs/issues/2897
=> Add wizard for Spring integration

src/includes/java/performance/getting-started/java.mdx, src/includes/performance/enable-tracing/android.mdx, src/includes/performance/enable-tracing/java.mdx, src/includes/performance/traces-sampler-as-sampler/android.mdx, src/platforms/java/common/performance/index.mdx
=> Fix: Performance docs for Android do not mention spring boot

src/components/banner.tsx
Taking down the banner that's for tomorrow's workshop.
=> Remove January banner

src/platforms/dotnet/guides/aspnet/index.mdx
To be merged once .NET 3.0 comes out
=> .NET Sentry SDK v3.0.0 - ASP.NET integration

src/includes/user-feedback-example-widget/dotnet.aspnet.mdx, src/includes/user-feedback-example-widget/dotnet.aspnetcore.mdx
This PR changed it: https://github.com/getsentry/sentry-dotnet/pull/644
Once 3.0.0 goes GA, we'll merge this.
Same as #2669
=> .NET Sentry SDK v3.0.0 - sentryid namespace

src/wizard/react-native/index.md
=> fix(wizard): react native markdown

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/issue.md
=> meta: Add issue templates and directions

.github/workflows/validate-new-issue.yml
I are a bot. 🤖
https://github.com/getsentry/.github/blob/7ef208419a2a6e5c1cb569c73e3b3d96dd2ddf9a/.github/workflows/validate-new-issue.yml
=> meta(gha): Deploy action validate-new-issue.yml

package.json, yarn.lock
=> platformicons 4.1.1 (unreal)

src/platforms/common/configuration/options.mdx
I'm horrible when it comes to expressing my thoughts and I'm also bad in English, so please help me if there is a better way to formulate this.
=> Document additional Sentry options in .NET SDK

src/components/banner.tsx
Enable signup for Release Health with JavaScript
=> Turn on banner for RH workshop

src/platforms/common/configuration/filtering.mdx, src/platforms/common/enriching-events/transaction-name.mdx, src/platforms/common/performance/connect-services.mdx, src/platforms/common/performance/index.mdx, src/platforms/common/performance/sampling.mdx
Fixes #3058 as Cordova does not support performance
=> fix: Remove performance docs from cordova

src/includes/getting-started-install/android.mdx, src/includes/getting-started-install/java.mdx, src/platforms/android/usage/advanced-usage.mdx, src/wizard/android/index.md, src/wizard/java/index.md
See: https://github.com/getsentry/sentry-java/issues/1227
=> jcenter deprecated

src/platforms/dotnet/migration.mdx
=> dotnet migraton namespace

src/includes/configuration/before-send-fingerprint/java.spring-boot.mdx, src/includes/configuration/before-send-hint/java.mdx, src/includes/configuration/before-send-hint/java.spring-boot.mdx, src/includes/configuration/before-send/java.mdx, src/includes/configuration/before-send/java.spring-boot.mdx, src/includes/configuration/config-intro/java.spring-boot.mdx, src/includes/configuration/sample-rate/java.spring-boot.mdx, src/includes/set-environment/java.spring-boot.mdx, src/includes/set-release/java.spring-boot.mdx
Adds Spring Boot specific code samples.
=> Improve Spring Boot configuration and setup guides.

src/includes/performance/connect-errors-spans/java.mdx
=> Java: Fix code snippets in connecting errors with spans.

src/docs/product/sentry-basics/guides/integrate-backend/capturing-errors.mdx, src/docs/product/sentry-basics/guides/integrate-backend/configuration-options.mdx, src/docs/product/sentry-basics/guides/integrate-backend/getting-started.mdx, src/docs/product/sentry-basics/guides/integrate-frontend/configure-scms.mdx, src/docs/product/sentry-basics/guides/integrate-frontend/create-new-project.mdx, src/docs/product/sentry-basics/guides/integrate-frontend/generate-first-error.mdx, src/docs/product/sentry-basics/guides/integrate-frontend/initialize-sentry-sdk.mdx, src/docs/product/sentry-basics/guides/integrate-frontend/upload-source-maps.mdx
Otherwise they are sorted by title, which is wrong.
=> Fix tutorial sidebar order

src/includes/getting-started-config/java.servlet.mdx, src/includes/getting-started-install/java.servlet.mdx, src/platforms/java/guides/servlet/config.yml
=> Java: add Servlet integration docs.

src/includes/set-fingerprint/basic/php.mdx, src/includes/set-fingerprint/database-connection/php.mdx, src/includes/set-fingerprint/rpc/php.mdx
=> Add PHP set-fingerprint code

src/docs/clients/react-native/manual-setup.mdx
=> Add fnm as alternate node version manager in manual documentation

src/includes/performance/add-spans-example/python.mdx
=> fix: Remove remnants of less-nice transaction API

src/components/codeBlock.tsx
https://user-images.githubusercontent.com/1421724/108447261-6d15f500-7214-11eb-9d3a-533b18a55087.mov
https://user-images.githubusercontent.com/1421724/108447267-6f784f00-7214-11eb-983c-229de1db04d2.mov
=> ref(code-block): Animate implicit changes

src/includes/performance/connect-errors-spans/java.mdx, src/includes/performance/custom-sampling-context/java.mdx, src/includes/performance/enable-manual-instrumentation/java.mdx, src/includes/performance/force-sampling-decision/java.mdx, src/includes/performance/retrieve-transaction/java.mdx
Relfect changes from https://github.com/getsentry/sentry-java/issues/1241
=> Java: reflect changes from gh-1241

.github/ISSUE_TEMPLATE/issue.md
This update combines two pieces of the template with the goal of making it more efficient (and still useful).
=> Update Docs Template

src/platforms/dotnet/guides/aspnetcore/index.mdx, src/platforms/dotnet/guides/aspnetcore/performance/included-instrumentation.mdx
=> Add Sentry ASP.NET Core tracing docs

src/includes/set-fingerprint/database-connection/apple.mdx
This was missing for Apple. Sample code for RPC fingerprinting is missing as well. I'm going to add this with another PR.
=> feat(apple): Add fingerprint database connection

src/includes/configuration/before-send-fingerprint/dart.mdx, src/includes/set-fingerprint/basic/dart.mdx, src/includes/set-fingerprint/database-connection/dart.mdx, src/includes/set-fingerprint/rpc/dart.mdx
Fix: https://github.com/getsentry/sentry-dart/issues/304
=> Fix: Dart beforeSend filtering by exception type

src/docs/product/data-management-settings/filtering/index.mdx
Responding to https://github.com/getsentry/sentry-docs/issues/3139
=> Add error message filtering to Inbound Filters content

src/docs/product/sentry-basics/search/index.mdx
Completing initial updates to structure of this content for improved usability.
Lines 90, 139, 141 require review
=> update Search content

src/platforms/common/enriching-events/scopes.mdx
This is accurate with the current implementation.
=> docs(scope): Add note regarding withScope ignoring exceptions

src/includes/getting-started-primer/react-native.mdx, src/wizard/react-native/index.md
=> Update React Native wizard 

src/wizard/react-native/index.md
Minor change to the package name
=> Fix wizard package

src/docs/product/dashboards/custom-dashboards/index.mdx, src/docs/product/dashboards/index.mdx
Linked to https://github.com/getsentry/sentry-docs/pull/3200
=> feat(discv2): minor edits from #3200

src/components/platformContent.tsx
=> Link to template chooser for new issues

src/docs/product/projects/project-details/index.mdx
We now display frequent _unhandled_ issues on project details. (https://github.com/getsentry/sentry/pull/24302)
=> feat: Project details frequent unhandled issues

src/css/_includes/global-header.scss, src/css/_includes/type.scss
I've resolved the remaining issues that @rhcarvalho commented in https://github.com/getsentry/sentry-docs/pull/2993
Based on:
- https://stackoverflow.com/questions/10732690/offsetting-an-html-anchor-to-adjust-for-fixed-header
- https://css-tricks.com/hash-tag-links-padding/
Closes https://github.com/getsentry/sentry-docs/issues/2685
=> fix: push anchor headers below fixed top bar

src/docs/product/dashboards/custom-dashboards/index.mdx
Add redirect from customize-dashboards to custom-dashboard
=> add customize redirect

src/components/banner.tsx
Upcoming Tech Education banner
=> Add March 2021 banner

vercel.json
This will complement https://github.com/getsentry/sentry/pull/24295
=> feat: Add redirect for Sessions API

src/includes/set-context/dotnet.mdx
=> Fix .NET 'set-context' docs

src/docs/product/releases/health/index.mdx
We'll be soon deploying a change to release health where we add support for both user and session based adoption calculation.
=> feat: Update release health adoption docs

src/platforms/native/guides/ue4/advanced-config.mdx
Add ".ToSharedRef()" to the first parameter in FJsonSerializer::Serialize
=> Update for 4.26 compilation

src/platforms/common/configuration/sampling.mdx
=> Missing space between link and text

src/includes/performance/configure-sample-rate/dotnet.mdx, src/includes/performance/sampling-function-intro/dotnet.mdx
As discussed this morning, @bruno-garcia 
cc @maciejwalkowiak @marandaneto 
I welcome any suggestions to improve wording 🙂
=> .NET: Improve docs on custom sampling

src/includes/performance/traces-sampler-as-sampler/dotnet.mdx
=> .NET: add IsParentSampled to dynamic sampling example

src/includes/performance/traces-sampler-as-filter/android.mdx, src/includes/performance/traces-sampler-as-filter/java.mdx, src/includes/performance/traces-sampler-as-filter/java.spring-boot.mdx, src/includes/performance/traces-sampler-as-filter/java.spring.mdx, src/includes/performance/traces-sampler-as-sampler/java.spring-boot.mdx, src/includes/performance/traces-sampler-as-sampler/java.spring.mdx
As noted by @bruno-garcia https://github.com/getsentry/sentry-java/pull/1328/
=> Java: add code samples for filtering transactions using sampler function

src/docs/product/cli/dif.mdx
https://github.com/getsentry/sentry-docs/issues/3283
=> Specify sentry-cli permissions for uploading debug files

src/docs/product/issues/states-triage/index.mdx
Making updates and one fix for Issue States and Triage content
=> updates to issue states and triage

src/includes/performance/default-sampling-context/python.tornado.mdx
https://github.com/getsentry/sentry-python/pull/1060
=> feat: add traces_sampler snippet for tornado

src/includes/getting-started-config/android.timber.mdx, src/includes/getting-started-verify/android.timber.mdx
added missing imports
Kotlin snippets first
Verify actually captures the exception using the Timber API
=> Improve Timber docs

package.json, yarn.lock
Connected to https://github.com/getsentry/platformicons/pull/38 and https://github.com/getsentry/sentry/pull/24730
=> feat(new platform): added ionic for docs

src/docs/product/alerts-notifications/metric-alerts.mdx
Updates for EA changes to Alert Details page
=> alert details ea updates

src/docs/product/issues/index.mdx, src/docs/product/issues/reprocessing/index.mdx
Fixing broken redirects on Issues index page and Reprocessing page
=> fix broken redirects in Issues pages

src/platforms/php/guides/symfony/config.mdx, src/platforms/php/guides/symfony/index.mdx
See https://github.com/getsentry/sentry-symfony/blob/master/UPGRADE-4.0.md
This addresses https://github.com/getsentry/sentry-docs/pull/3137#pullrequestreview-615546347 and generally other changes to bring the Symfony docs into a better state.
Closes #3233
=> Symfony: update config to match latest releases

src/platforms/dotnet/migration.mdx
=> [.NET] Note obsolete API removed

src/includes/performance/traces-sampler-as-filter/android.mdx, src/includes/performance/traces-sampler-as-filter/java.mdx, src/includes/performance/traces-sampler-as-filter/java.spring-boot.mdx, src/includes/performance/traces-sampler-as-filter/java.spring.mdx
=> Java: Add parentSampled check for traces-sampler-as-filter docs

src/docs/product/integrations/aws-lambda/index.mdx
I have raised this with support.
=> AWS Lambda integration - serverless framework deployment documentation

src/includes/performance/configure-sample-rate/dotnet.aspnetcore.mdx, src/includes/performance/traces-sample-rate/dotnet.aspnetcore.mdx, src/includes/performance/traces-sampler-as-sampler/dotnet.aspnetcore.mdx
=> .NET: add tracing setup docs for ASP.NET Core

src/platforms/dotnet/guides/aspnetcore/builtin-sampling-context.mdx
Not 100% sure where to put this so help is appreciated.
cc @bruno-garcia
=> .NET: built-in custom sampling context data on ASP.NET Core

src/docs/product/accounts/quotas/index.mdx
Fix highlight on spike protection
=> Fix highlight on spike protection

src/docs/clients/react-native/manual-setup.mdx
=> fix typo in RN setup guide

src/includes/performance/distributed-tracing/dotnet.mdx, src/includes/performance/distributed-tracing/java.mdx, src/platforms/common/performance/custom-instrumentation.mdx
Closes #3338
cc @marandaneto @bruno-garcia
=> .NET: document distributed tracing

src/platforms/javascript/common/sourcemaps/index.mdx
ref: https://github.com/getsentry/sentry-javascript/issues/2876#issuecomment-815824671
closes: https://github.com/getsentry/sentry-javascript/issues/2876
=> docs(js): Add gatsby source maps instructions

src/platforms/common/usage/index.mdx
hello, so I might be wrong (please correct me if so), but based on my observation, this is the case.
Motivation is to have a more accurate description of the behavior because the current one leaves out these important details. 
Thanks!
=> docs: clarify error and rejection logging

src/platforms/dotnet/guides/aspnet/index.mdx
Has confused ppl that this is a requirement.
=> Remove aspnet advise for 4.8

src/docs/product/integrations/jira/index.mdx
Add note to automatic issue management configuration to indicate that it's not applicable for Jira Server per the following ticket:
https://getsentry.atlassian.net/browse/ISSUE-1204
=> add note for automatic issue management configuration

src/includes/getting-started-primer/javascript.nextjs.mdx
augment note to emphasize experimental state of the plugin
=> Note on plugin status for Next JS

src/docs/product/sentry-basics/guides/grouping-and-fingerprints/index.mdx
Fix mismatch between text and screenshot in Grouping Issues content
=> fix screenshot text mismatch in Grouping Issues content

src/platforms/javascript/common/configuration/integrations/default.mdx
Added a code example for LinkedErrors.
=> Provided clarity around LinkedErrors

src/docs/product/accounts/pricing.mdx
Add New Mexico to sales tax list. Request from Theresa G (Finance team)
=> Add New Mexico to sales tax list
