getsentry/sentry-docs

src/docs/product/accounts/membership.mdx

Update the table on the [membership](https://docs.sentry.io/product/accounts/membership/#membership
) page to reflect current member roles needed to remove a repository. I consolidated the rows since the same permissions are needed for adding and removing.
See https://github.com/getsentry/sentry/pull/18987 where we updated this in the product.

ref(membership): Update add/remove repo role

---

src/platforms/react-native/manual-setup/codepush.mdx

The Codepush documentation is quite confusing because it immediately mentions needing to pass a `release` and `dist` property but does not explain what they are.
They are covered later on in the Source Maps section, but that would not have been read if the user is reading docs in a linear fashion, leaving them confused.
I have added a link to the source maps section so the user is able to get some more context on what they are for.

Update codepush.mdx to clarify 'release' and 'dist' parameters

---

src/includes/enriching-events/attachment-upload/apple.mdx

Only merge after https://github.com/getsentry/sentry-cocoa/pull/1195 is released.

feat(apple): ClearAttachments on Scope

---

src/includes/configuration/sourcemaps/tools/webpack/advanced-usage/javascript.mdx
src/includes/configuration/sourcemaps/tools/webpack/advanced-usage/javascript.nextjs.mdx
src/platforms/javascript/common/sourcemaps/tools/webpack.mdx

The advanced usage of Webpack was valid in a prior version of the SDK. This PR updates that code sample, besides removing some comments to reduce noise. If a user wants to read that noise or just learn more about it, a link to the `manual-setup` page has been included.

fix(nextjs): Update code sample in Advanced Usage of Webpack

---

src/includes/configuration/sourcemaps/tools/webpack/advanced-usage/javascript.nextjs.mdx
src/platforms/javascript/guides/nextjs/manual-setup.mdx

This PR adds docs for the options introduced in https://github.com/getsentry/sentry-javascript/pull/3771, which allow the user to disable the addition of `SentryWebpackPlugin` to server and client builds.

feat(nextjs): Document options for disabling webpack plugin

---

src/platforms/javascript/common/configuration/integrations/default.mdx

Ref: https://github.com/getsentry/sentry-javascript/pull/3755
It's on release [6.8.0](https://github.com/getsentry/sentry-javascript/releases/tag/6.8.0).

Update `serializeAttribute` documentation to cover multiple attributes.

---

src/platforms/ruby/common/migration.mdx

Just updated the URL for the link to 'Advanced Data Scrubbing' in the ruby migration guide

Fix/Update 'Advanced Data Scrubbing' Link

---

src/platforms/ruby/common/migration.mdx

Keeps the document up-to-date and addresses the feedback in https://github.com/getsentry/sentry-docs/issues/3823.

Improve Ruby SDK's migration guide

---

src/platforms/common/performance/connect-services.mdx

Working with @HazAT, this content makes the Connect Services page common to all SDKs that support performance. Note that the information for JS and its family of guides continues to be more detailed, and the display of that content is constrained to only that family of SDKs.

Update Connect Services to common 

---

src/includes/configuration/sourcemaps/tools/webpack/advanced-usage/javascript.mdx
src/includes/configuration/sourcemaps/tools/webpack/advanced-usage/javascript.nextjs.mdx
src/platforms/javascript/common/sourcemaps/index.mdx
src/platforms/javascript/common/sourcemaps/tools/webpack.mdx

Nothing major here, mostly just carryover from comments on https://github.com/getsentry/sentry-docs/pull/3677 which didn't get in before it was merged.
- Use `devtool` in all snippets so that sourcemaps are generated correctly
- Fix setting `devtool` in nextjs (set it on `config`)
- Remove stray `configureWebpack` wrapper in two snippets
- Remove `productionBrowserSourceMaps` from nextjs config since [we no longer use it](https://github.com/getsentry/sentry-javascript/pull/3765)
- Remove `SentryWebpackPluginOptions` from nextjs snippet not using plugin

fix(sourcemaps): Small fixes in webpack snippets

---

src/includes/configuration/auto-session-tracking/dotnet.mdx
src/includes/configuration/auto-session-tracking/unity.mdx
src/includes/getting-started-primer/unity.mdx
src/platforms/common/configuration/releases.mdx

Worth noting:
1. I didn't link to `https://docs.sentry.io/platforms/unity/configuration/releases/` as we did on other pages (like [.NET](https://docs.sentry.io/platforms/dotnet/), [Apple](https://docs.sentry.io/platforms/apple/guides/ios/), ..) but instead linked to the ["Release and Health" part of the SDK itself](https://docs.sentry.io/platforms/unity/configuration/releases/). The reason is that we have more specific information like for example we detect release automatically from Unity.
Would it make sense to edit the common content for Release and Health and link to `https://docs.sentry.io/platforms/unity/configuration/releases/` from there instead?
2. I rephrased it. On the other docs we say:
> Release Health tracks crash free users and sessions
So to be clear we're not "tracking …

Release Health for Unity

---

src/platforms/common/configuration/options.mdx
src/platforms/react-native/manual-setup/native-init.mdx

Adds a "Hybrid SDK Options" section for `enableNative` for RN, Capacitor, and Cordova. And `autoInitializeNativeSdk` for RN. Maybe applicable to flutter too cc @marandaneto?
Adds a page documenting how to manually initialize the native sdks in React Native:
https://github.com/getsentry/sentry-react-native/issues/1631

feat: Hybrid SDK options and React Native manual native initialization page

---

src/platforms/javascript/common/troubleshooting/index.mdx
src/platforms/javascript/common/troubleshooting/supported-browsers.mdx
src/platforms/javascript/guides/capacitor/troubleshooting.mdx

Fix for users on Capacitor 2 who run into a deployment target issue.
Includes the error as a quote so users who search with the error text might hit this page.

feat: Troubleshooting page for Capacitor with iOS Deployment Version fix

---

src/includes/enriching-events/attachment-upload/dotnet.mdx

Doc for this feature: https://github.com/getsentry/sentry-dotnet/issues/1041 (being able to clear attachments from Sentry's scope.
Merge once a new release of the SDK with the feature is made.

Add ClearAttachments to .NET doc

---

src/platforms/python/guides/celery/index.mdx

Celery v5 has already been released and the Alert still said to wait for an "upcoming release"

ref(python): Update alert for celery with v5 of celery released

---

src/platforms/javascript/guides/react/components/errorboundary.mdx

Addressing feedback brought up in https://github.com/getsentry/sentry-docs/issues/3874
Add some more context on what `resetError()` is doing and how it works.

chore(react): Update details about ErrorBoundary resetError

---

src/docs/product/accounts/sso/azure-sso.mdx

Users will encounter `Error AADSTS650056 - Misconfigured application` if they didn't include a trailing slash in the Identifier field when setting up Sentry on Azure AD. It causes some back-and-forth between them and support, which isn't ideal.
This adds an explicit alert for it so users can be warned of this subtle error.

feat: Add alert for Identifier field

---

src/docs/product/releases/health/setup.mdx

I missed adding .NET to the list when I extended the release health docs for it.
Closes https://github.com/getsentry/sentry-docs/issues/3895

.NET: Added to the list of supported SDKs for release health

---

src/platforms/node/guides/koa/index.mdx

The previous implementation didn't trace database queries performance. The current implementation gives the chance of finishing spans before closing the transaction.

Fix koa tracing code snippet to trace database queries

---

src/docs/product/integrations/integration-platform/ui-components/index.mdx

See: https://docs.sentry.io/product/integrations/integration-platform/ui-components/#issue-link for image not loading.
Can see that this is fixed in https://sentry-docs-git-abhi-fix-clubhouse-links.sentry.dev/product/integrations/integration-platform/ui-components/#issue-link

fix: Use correct clubhouse image links

---

src/includes/configuration/config-intro/javascript.ember.mdx
src/includes/getting-started-config/javascript.ember.mdx
src/includes/performance/beforeNavigate-example/javascript.ember.mdx
src/includes/performance/configure-sample-rate/javascript.ember.mdx
src/includes/performance/enable-automatic-instrumentation/javascript.ember.mdx
src/includes/performance/enable-tracing/javascript.ember.mdx
src/includes/performance/filter-span-example/javascript.ember.mdx
src/includes/performance/tracingOrigins-example/javascript.ember.mdx
src/platforms/javascript/guides/ember/configuration/ember-options.mdx
src/wizard/javascript/ember.md

Now that sdk 6.5+ is out, we can use Sentry.init and pass config options similar to how the other frameworks work. This will split the config for Sentry itself from Ember specific config. 
The Ember config will still be set in the config files, but the Sentry options can now be sent when init is called. The only exception is that browser tracing options need to be passed as a special option (under browserTracingOptions) since Ember provides a custom integration which currently needs to be setup after the app is initialized.
I still need to go through and check each page since I worked on it before putting up another PR, wanted to see any initial feedback.

docs(ember): Update Ember docs for new config

---

src/platforms/javascript/common/configuration/integrations/default.mdx
src/platforms/javascript/common/configuration/integrations/plugin.mdx

Fixes https://github.com/getsentry/sentry-docs/issues/3870

Update dedupe docs

---

src/includes/enriching-events/set-context/native.ue4.mdx
src/includes/enriching-events/set-tag/native.ue4.mdx
src/includes/enriching-events/set-user/native.ue4.mdx
src/includes/enriching-events/unset-user/native.ue4.mdx
src/platforms/common/enriching-events/context.mdx
src/platforms/common/enriching-events/identify-user.mdx
src/platforms/common/enriching-events/tags.mdx
src/platforms/common/enriching-events/transaction-name.mdx
src/platforms/native/guides/ue4/advanced-config.mdx

Expands the existing Advanced Configuration code snippet with more examples for
configuring tags and custom contexts. Also enables the Enriching Events section
for supported functions.
Since performance monitoring is not supported on UE4, this also disables the
transaction name document for UE4.

feat(ue4): Enable enriching events content for UE4

---

src/docs/product/releases/health/index.mdx
src/docs/product/releases/health/release-details.mdx
src/docs/product/releases/index.mdx
src/docs/product/releases/usage/sorting-filtering.mdx
src/docs/product/sentry-basics/search/searchable-properties.mdx

This adds search features for the `release.stage` feature to the #3903

feat(docs): Release adoption stages filtering

---

src/platforms/node/guides/aws-lambda/container-image/index.mdx
src/platforms/node/guides/aws-lambda/index.mdx
src/platforms/python/guides/aws-lambda/container-image/index.mdx
src/platforms/python/guides/aws-lambda/index.mdx

This PR adds docs for both Python and Node on how to use Sentry's AWS Layer as a container image on AWS

feat(aws-lambda): Add docs on using Sentry as a Container Image

---

src/docs/product/accounts/sso/okta-sso/okta-scim.mdx

- Another round of feedback from Okta, they'd like us specifically to call out not supporting the "Import Users" feature due to our missing firstName/lastName.

fix(scim): update troubleshooting blurb about import users

---

src/includes/getting-started-primer/javascript.nextjs.mdx

As of https://github.com/getsentry/sentry-javascript/pull/3811, the SDK should now work in API routes.

fix(nextjs): Remove note about API routes not working

---

src/docs/product/security-policy-reporting.mdx

Include a note that sentry needs to be in the allowed host list or submitting a CSP report will also fail.
Fixes getsentry/sentry#27524

fix(csp) Improve CSP docs around policy requirements

---

src/includes/getting-started-config/javascript.capacitor.mdx

We fixed the incorrect release/dist example in the "Other Platforms" tab but not the Angular tab.

fix: Fix the Release and Dist content in the capacitor init for angular

---

src/docs/product/accounts/sso/azure-sso.mdx
src/docs/product/accounts/sso/okta-sso/okta-scim.mdx

it seems like unless you add a new line at the beginning and end of the content of an HTML element in our markdown docs, it will not render the contents as markdown. interesting. anyways, this fixes the broken mailto link on the SCIM pages.

fix(scim): fix broken mailto rendering

---

src/platforms/javascript/common/install/lazy-load-sentry.mdx

The way we're currently phrasing this, it makes it seem like tracing will start working once the SDK is loaded, which isn't true.
Fixes https://github.com/getsentry/sentry-javascript/issues/3054#issuecomment-827214249.

fix(js): Clarify that loader does not include tracing features

---

src/includes/getting-started-install/android.mdx
src/includes/getting-started-install/java.jul.mdx
src/includes/getting-started-install/java.log4j2.mdx
src/includes/getting-started-install/java.logback.mdx
src/includes/getting-started-install/java.mdx
src/includes/getting-started-install/java.servlet.mdx
src/includes/getting-started-install/java.spring-boot.mdx
src/includes/getting-started-install/java.spring.mdx
src/platforms/android/configuration/bill-of-materials.mdx
src/platforms/java/common/configuration/bill-of-materials.mdx

To be merged once Sentry Java BOM is shipped passed a preview phase i.e: 5.1.0
/cc @maciejwalkowiak 
See: https://github.com/getsentry/sentry-docs/pull/3832
:trollface:

Java: Add BOM docs.

---

src/platforms/android/common/proguard.mdx

all buildscript {} blocks must appear before any plugins {} blocks in the script

fix Gradle plugin code snippet order

---

src/platforms/elixir/index.mdx
src/wizard/elixir/index.md

As of version 8, [the Elixir plugin has an additional dependency](https://github.com/getsentry/sentry-elixir#installation).

fix(elixir): add required hackney dependency to installation steps

---

src/docs/product/integrations/source-code-mgmt/github/index.mdx
src/docs/product/integrations/source-code-mgmt/gitlab/index.mdx
src/docs/product/issues/issue-owners/index.mdx

Add business plan note to code owners docs

Add business plan note for code owners

---

src/platforms/react-native/manual-setup/hermes.mdx
src/platforms/react-native/sourcemaps.mdx
src/platforms/react-native/troubleshooting.mdx

Make Hermes source maps less confusing by providing clear code examples instead of just instructions. This PR took a while due to needing lots of testing, turns out the whole three-step process isn't even needed for Hermes on iOS.
- Adds detailed guide on Hermes source maps for Android.
- Adds a warning on the source maps page about Hermes on Android and links to this guide.
- Adds a section in the troubleshooting page about Hermes on Android.
Addresses https://github.com/getsentry/sentry-react-native/issues/1270

feat: Clearer instructions for Hermes sourcemaps

---

src/platforms/apple/common/performance/instrumentation/automatic-instrumentation.mdx

enableAutoUIPerformanceTracking was renamed to enableAutoPerformanceTracking.
Only merge after https://github.com/getsentry/sentry-cocoa/pull/1209 is released.

ref(apple): Rename option for enabling auto performance

---

src/platforms/apple/common/dsym.mdx
src/platforms/common/data-management/debug-files/index.mdx

https://getsentry.atlassian.net/browse/NATIVE-101
The getting-started pages already link to docs to set up debug files "with bitcode".
A new section is added explaining the credentials needed and how to set them up. It also adds a note periodic re-authentication.
No note is added for size-limitations yet, as those are not documented anywhere else either.

feat: Document AppStore Connect integration

---

src/platforms/index.mdx

In spite of the name, it's no longer based on `raven`, thankfully.

feat(SDKs): Add second nestjs SDK to community SDK list

---

src/includes/performance/retrieve-transaction/apple.mdx

The code sample for retrieving the current span was wrong. Instead of
SentrySDK.span it stated SentrySDK.getSpan(), which doesn't
exist in the SDK. This is fixed now.

fix(apple): SentrySDK.span

---

src/docs/product/integrations/integration-platform/ui-components/index.mdx
src/includes/getting-started-config/javascript.vue.mdx
src/includes/getting-started-verify/javascript.electron.mdx
src/includes/performance/configure-sample-rate/javascript.vue.mdx
src/platforms/javascript/common/configuration/integrations/default.mdx
src/platforms/javascript/common/troubleshooting/index.mdx
src/platforms/javascript/guides/react/configuration/integrations/react-router.mdx
src/platforms/javascript/guides/react/configuration/integrations/redux.mdx
src/platforms/javascript/guides/vue/configuration/integrations/vue-router.mdx
src/platforms/node/common/configuration/integrations/default-integrations.mdx
src/platforms/node/guides/connect/index.mdx
src/platforms/node/guides/express/index.mdx
src/platforms/react-native/touchevents.mdx
src/wizard/cordova/index.md
src/wizard/electron/index.md
src/wizard/javascript/backbone.md
src/wizard/javascript/browser.md
src/wizard/javascript/index.md
src/wizard/javascript/vue.md
src/wizard/node/connect.md
src/wizard/node/express.md

For consistency and appropriate casing. Follow-up to https://github.com/getsentry/sentry-docs/pull/3965, which I accidentally closed by changing the branch name.

chore(JS): Spell out JS in snippet language headers

---

src/platforms/javascript/guides/react/components/errorboundary.mdx

Docs fix as a follow-up from https://github.com/getsentry/sentry-javascript/pull/3857

Show ReactElement as fallback in ErrorBoundary example

---

src/platforms/javascript/common/troubleshooting/index.mdx

Update examples to stop reading the target host from request body.
Instead, use explicit host configuration.
Similarly, limit project ID to a set of known IDs.
Fixes #3945.

tunnel: Update proxy examples

---

src/platforms/apple/common/dsym.mdx

Users need to be aware of when builds will become available.

Describe the 1h timeperiod for AppStoreConnect

---

src/docs/product/relay/options.mdx

The correct configuration key is `host_header` inside the `http` section.

Fix typo in Relay docs

---

src/components/layout.tsx
src/gatsby/createPages/createPlatformPages.ts
src/gatsby/utils/algolia.ts

This PR addresses a couple of issues:
- Allow guide pages to be indexed. This was previously disabled because our filtering was bad, but now that it's improved, there's no reason to do this.
- Send the guide along with the platform to allow for biasing search results. This will let us float contextual results higher if you're searching within a platform or guide.
I tested this change within the Angular guide, ensuring that searching "options" would yield the Angular configuration options when in the angular guide pages, and Javascript configuration options when in the javascript docs.
This PR _does not_ address keywording platforms, so searching "angular options" still won't get what you want.

Feat: index guides for search

---

src/docs/contributing/pages/components.mdx

Adds guidance for the use of notes and alerts

add note and alert guidance to contributor docs

---

src/platforms/android/common/proguard.mdx

Fixes #3893
This PR adds documentation for the variant filtering feature shipped with the Gradle plugin: https://github.com/getsentry/sentry-android-gradle-plugin/pull/140

Document the variant filtering feature

---

src/includes/getting-started-config/javascript.nextjs.mdx
src/includes/getting-started-verify/javascript.nextjs.mdx
src/platforms/javascript/guides/nextjs/manual-setup.mdx

This documents the change in https://github.com/getsentry/sentry-javascript/pull/3847, which allows for TypeScript versions of `sentry.server.config.js` and `sentry.client.config.js`, by adding TypeScript versions of those files to the code blocks.
It also includes a few other small fixes:
- Also add a Typescript version of the `withSentry` code snippet, both on the manual setup page and the getting started page.
- Move the alert about not supporting the `serverless` target into the section about `next.config.js`, which is where it's relevant.
- Remove the split between the snippet for `sentry.server.config.js` and `sentry.client.config.js`, as they were the exact same code. Instead, both filenames are listed on the snippet.
- Add filenames to the two `next.config.js` snippets which were …

feat(nextjs): Add option to have TS sentry config files, other small fixes

---

src/docs/product/cli/configuration.mdx

not sure if `warning` is an alias for `warn` but seeing sentry-clis code, its wrong: https://github.com/getsentry/sentry-cli/blob/e51e11302567dba927abc7f8383cf2d5b22c517b/src/commands/mod.rs#L231

Update default log level typo

---

src/includes/getting-started-config/java.spring-boot.mdx
src/includes/getting-started-config/java.spring.mdx

The behavior has changed in https://github.com/getsentry/sentry-java/commit/a13796d05828bb40c96231ff25067d53b6b5ac92

Java: adjust docs on default value for Spring's `exceptionResolverOrder`

---

src/docs/product/accounts/quotas/index.mdx

Our nomenclature with respect to spike protection being "active" or "inactive" is very misleading. This aims to clarify, at least a little, what it means to be "inactive."

fix(billing): Clarify spike protection inactivation

---

src/docs/product/alerts/notifications/index.mdx

We no longer check for projected overage anymore. Notifications are always sent when an account reaches 80% usage.

Update quota notification docs

---

src/docs/contributing/pages/components.mdx
src/docs/product/issues/index.mdx

Fixes heading level in Issues page so that RH sidebar renders properly
Moves placement of link text in Notes section of mdx components page in Contributing to Docs

fix issues page headings and link in mdx components page

---

src/docs/product/alerts/create-alerts/issue-alert-config.mdx
src/docs/product/alerts/notifications/notification-settings.mdx
src/docs/product/integrations/notification-incidents/slack/index.mdx

Added EA docs for Slack personal and team notifications
Changes:
- Added Personal and Team Notifications sections
- Removed section on upgrading Slack
Changes:
- Added a Delivery Method section to Alerts, Workflow, and Deploy sections
Changes:
- Removed specific language mentioning "emails only"
- Added section for Team Slack Notifications

Added EA docs for Slack personal and team notifications

---

src/platforms/java/performance/instrumentation/open-feign.mdx

Java: Add OpenFeign integration docs.

---

src/platforms/react-native/sourcemaps.mdx

As per the CLI --help command, it should be `upload-sourcemaps`. There is an extra space between 'source' and 'maps'. Based on https://docs.sentry.io/product/cli/releases/ page.

fix release sourcemap param typo

---

src/docs/product/integrations/source-code-mgmt/gitlab/index.mdx

- Move troubleshooting step from https://help.sentry.io/product-features/integrations/gitlab-why-am-i-getting-a-500-response-during-installation-or-configuration/
- Minor correction to the Sentry user level access that is requred

docs: add troubleshooting step

---

src/docs/product/integrations/source-code-mgmt/github/index.mdx

- Move the troubleshooting steps from https://help.sentry.io/product-features/integrations/github-why-can-t-i-add-a-repository/
- Make a minor adjustment to the access level required to setup the integration

docs: add steps in troubleshooting

---

src/docs/product/relay/getting-started.mdx
src/docs/product/relay/index.mdx
src/docs/product/relay/modes.mdx
src/docs/product/relay/projects.mdx
src/docs/product/security/index.mdx

Adds more notes re: managed mode in Relay
Fixes a broken link in the Security page

add mode notes in relay docs

---

src/platforms/ruby/common/configuration/options.mdx

This option is planned to be removed in the future and I want to discourage users from using it.

Deprecate sentry-ruby's async config option

---

src/docs/product/data-management-settings/event-grouping/stack-trace-rules.mdx

It does not help the user and implies more than it needs to (as not all
attributes are available). It's like saying "this button has style
consistent with this other button someplace else in the product". It
would belong in internal design docs.

fix(grouping): Remove useless byline about being consistent with discover

---

src/platforms/unity/configuration/native-support.mdx

Added a `native support page` to explain how Unity gets it and to link towards Cocoa.
Also to provide a clear way to opt-out of it.

feat: Unity native support page

---

src/includes/getting-started-primer/python.mdx
src/platforms/php/guides/laravel/other-versions/lumen.mdx

We spelled Performance `Perfomance` in two separate places. This fixes it.

Fix two performance typos

---

src/includes/getting-started-config/react-native.mdx
src/includes/performance/enable-tracing/react-native.mdx
src/platforms/react-native/performance/instrumentation/automatic-instrumentation.mdx

- Adds optional steps to wrap the app with Sentry and enable performance monitoring on the RN set up page.
- RN no longer requires the tracing integration to be set up, will only need a sample rate for auto performance.
- Documentation on the app start, slow/frozen frames, and js stall measurements.
- Re-organize the automatic instrumentation page to better guide through the enabling of auto performance before explaining about the features and configuration options.
Part of https://github.com/getsentry/sentry-react-native/issues/1701

feat: React Native performance and measurements

---

src/platforms/node/common/performance/database.mdx

Ref: https://github.com/getsentry/sentry-javascript/pull/3894

feat: Update examples to cover `pg-native` integration usage.

---

src/docs/product/data-management-settings/event-grouping/index.mdx

Replaces hardcoded link to SDK Fingerprinting content in Issue Grouping docs with platform redirect

replace hardcoded link with platform redirect

---

src/docs/product/integrations/source-code-mgmt/azure-devops/index.mdx

ADO allows a user in the Project Collections Administrators group to install integrations. The sentry integration now correctly allows this as well.

docs(azure): Update the note about permissions

---

src/platforms/common/data-management/debug-files/file-formats.mdx

This fixes a broken link to a part of symbolicator. Pretty straightforward stuff.

ref: Fix a broken link

---

src/platforms/python/guides/sanic/index.mdx

[Version 1.3](https://github.com/getsentry/sentry-python/releases/tag/1.3.0) included support for Sanic 21.3+

Add supported version to Sanic integration

---

src/docs/product/cli/dif.mdx

This change updates the directory location of `sentry-debug-meta.properties` to where is can currently be found as the previous location seems invalid. It also provides a more adequate description of directory paths.

Update `sentry-debug-meta.properties` location

---

src/docs/product/alerts/create-alerts/issue-alert-config.mdx
src/docs/product/alerts/notifications/notification-settings.mdx
src/docs/product/integrations/notification-incidents/slack/index.mdx

Do not merge until GA! 
This PR removes the note about needing to be on EA to use the features, as when it's merged it will be released to GA.

DO NOT MERGE feat(notification platform): Remove EA mention

---

src/docs/product/alerts/create-alerts/issue-alert-config.mdx

Adds "percent" to keywords for issue alert configuration so users can find percent-based issuer alerts when searching "percent." Currently, pages with the word "percentage" are favoured by the search engine because of the space after the word "percent" in the issue alert content.

add percent to keywords for issue alert configuration

---

src/platforms/javascript/guides/nextjs/manual-setup.mdx

All the properties in a Next.js project used to be in `sentry.properties`, used by Sentry CLI. The auth token is the only property that shouldn't be committed to the VCS, so it has been moved to `.sentryclirc`. This allows committing `sentry.properties` and ignoring `.sentryclirc` to safely commit everything but the auth token.

Update Next.js `sentry-cli` configuration

---

src/docs/product/alerts/create-alerts/issue-alert-config.mdx

Remove percent keyword as its addition is creating unexpected behaviour with search. Now, all the sub-headings of the issue alert configuration page are returned as search results, rather than the pages we were getting before + the issue alert config page.

remove percent keyword issue alert config

---

src/docs/product/releases/health/index.mdx

This PR adds missing documentation on server mode sessions in `releases/health`
fixes #4070

feat(release-health): Add missing doc on server mode sessions

---

src/platforms/apple/common/dsym.mdx

Update the state of EA and pricing.  A number of smaller tweaks:
- Some notes and callouts to make the document read more natural.
- Switch back to iTunes credentials naming since that is what is used
in the UI as well.

ref(appconnect): Tweaks, EA and pricing updates (NATIVE-188)

---

src/docs/product/alerts/create-alerts/issue-alert-config.mdx

Adds the term "percent-based alerts" to page for improved search

add percent-based alerts terminology

---

src/includes/getting-started-config/javascript.nextjs.mdx

The new `.sentryclirc` file was added to the manual setup page on https://github.com/getsentry/sentry-docs/pull/4105, but not to the getting started page. This PR adds it there.
Closes https://github.com/getsentry/sentry-docs/issues/4122.

fix(nextjs): Add `.sentryclirc` to list of created files in the getting started page

---

src/platforms/dotnet/common/performance/instrumentation/automatic-instrumentation.mdx

This PR corrects the PR names for the DisableDiagnosticSource integration.
The function definitions can be found here
https://github.com/getsentry/sentry-dotnet/blob/f47367ca406b98286aeaa0e57cbd917a1f3ea6ae/src/Sentry.DiagnosticSource/SentryOptionsDiagnosticExtensions.cs#L11-L16 for AddDiagnosticSourceIntegration
and 
https://github.com/getsentry/sentry-dotnet/blob/f47367ca406b98286aeaa0e57cbd917a1f3ea6ae/src/Sentry.DiagnosticSource/SentryOptionsDiagnosticExtensions.cs#L18-L24 for DisableDiagnosticSourceIntegration

Fix function names for DiagnosticSource integration.

---

src/docs/product/issues/index.mdx

This was in EA but we didn't release it for GA

Remove issue display options from docs

---

src/platforms/javascript/guides/nextjs/manual-setup.mdx

Fixes the format of the `.sentryclirc` file.

fix(nextjs): Correct format of `.sentryclirc`

---

src/platforms/react-native/performance/instrumentation/automatic-instrumentation.mdx

The RN SDK now supports React Navigation V6 using the same instrumentation as V5 in https://github.com/getsentry/sentry-react-native/pull/1768. So we remove the V5 prefix and just call it the React Navigation instrumentation.

ref: React Native support for React Navigation V6

---

src/includes/configuration/decluttering/javascript.mdx

What was once v6 has become v7 in our planning, and this updates the note about the removal of `whitelistUrls` and `blacklistUrls` to reflect that.

fix(js): Fix deprecation version for `whitelistUrls` and `blacklistUrls`

---

src/platforms/apple/common/dsym.mdx

It is supposed to be GA, at least by the time we merge this.

Remove EA note from appstore connect.

---

src/includes/performance/automatic-instrumentation-integrations/dotnet.mdx
src/platforms/dotnet/common/performance/instrumentation/automatic-instrumentation.mdx

- Moved Diagnostic Source explanation to the include file, by that, the AspNET Core will also include the documentation of it.
- Added the missing using Sentry into the sample for disabling/enabling Diagnostic Source.

Refactor DiagnosticSource docs.

---

src/docs/product/accounts/quotas/index.mdx

Clarifies the language around spike protection so that it's clear that it's enabled by default. Currently the language makes it sound like you have to enable it.

update wording about spike protection being enabled

---

src/docs/product/accounts/sso/index.mdx
src/docs/product/accounts/sso/saml2.mdx

Add and remove notes pertaining to plan-based availability for SSO features
- Github and Google - Team+ and Trial
- SAML2 - Biz+, no Trial

update plan notes for sso features

---

package.json
yarn.lock

This is to address [CVE-2021-23440](https://github.com/advisories/GHSA-4jqc-8m5r-9rpr)

upgrade(set-value): Force set-value>=4.0.1

---

src/docs/product/integrations/deployment/vercel/index.mdx

This fixes the note about using the webpack plugin as part of the vercel integration if you're running a nextjs app, to correctly indicate that for those folks, the step is unnecessary.

fix(nextjs): Clarify vercel integration webpack plugin instructions for nextjs apps

---

src/includes/getting-started-install/react-native.mdx
src/platforms/react-native/troubleshooting.mdx

Warn users about incompatibilities and version mismatch when using `sentry-expo` along with a warning about the current version `3.x` not working with `sentry-expo`.
https://github.com/getsentry/sentry-react-native/issues/1773

feat(RN): Add expo warnings and troubleshooting

---

src/includes/getting-started-primer/apple.macos.mdx
src/includes/getting-started-primer/apple.mdx
src/includes/getting-started-primer/apple.watchos.mdx
src/includes/getting-started-primer/note/apple.mdx

The feature set of MacOS and WatchOS included too many features
and confuses users.
This is fixed now by removing the nonsupported features.
@imatwawana, I had to copy the pages. Is there maybe a way to reuse some common text of the pages?

fix(apple): Features for macOS and watchOS

---

src/platforms/ruby/common/migration.mdx

Method tag_context do not exist in sentry-raven gem
Correct method is `tags_context`
Source: https://github.com/getsentry/sentry-ruby/tree/master/sentry-raven#context
PS: Thanks for your work :)

Fix typo in method example

---

src/includes/enriching-events/set-user/android.mdx
src/includes/enriching-events/set-user/apple.mdx
src/includes/enriching-events/set-user/dart.mdx
src/includes/enriching-events/set-user/flutter.mdx
src/includes/enriching-events/set-user/react-native.mdx

Align or add info on fallback for userID to installationID for
Android, Apple, Dart, and ReactNative.

fix: Add fallback userID to mobile SDKs

---

src/platforms/apple/common/performance/instrumentation/automatic-instrumentation.mdx

The HTTP instrumentation on Apple can lead to crashes. We want to point this
out in the docs to warn our users.
Only merge after https://github.com/getsentry/sentry-cocoa/pull/1349 is released.

feat(apple): Warning about HTTP instrumentation

---

src/platforms/react-native/performance/instrumentation/automatic-instrumentation.mdx

Documentation on the setup for the React Native Navigation instrumentation. Also adds a bullet-pointed section on top for ease of navigation and seeing the options of what we have because the sidebar does not show a list of the libraries we support.
NOTE: Do not merge this until `3.2.0-beta.1` is actually released.

feat(RN): React Native Navigation routing instrumentation

---

src/css/screen.scss

Use antialiasing (instead of the default sub-pixel rendering) for font smoothing, to make docs look more in line with the main app + our designs on Figma, and reduce font bleeding in white text on dark backgrounds.
Before - with the default sub-pixel rendering:
After - with antialiasing:

feat(ui): Add font smoothing

---

src/platforms/android/common/performance/instrumentation/apollo.mdx
src/platforms/java/performance/instrumentation/apollo.mdx

Java: document Apollo Android integration

---

src/platforms/python/common/configuration/integrations/index.mdx

Links in the integrations index are currently maintained manually, and a link to the Flask integration is missing.

Add missing link to Flask integration

---

src/docs/product/cli/releases.mdx

Unescaped, the backslash does not appear in the docs either on GitHub or live at https://docs.sentry.io/product/cli/releases/#creating-releases. This change escapes it so that it appears.

Fix unescaped backslash

---

src/docs/product/integrations/integration-platform/ui-components/index.mdx
src/docs/product/integrations/integration-platform/webhooks.mdx

Docs describes the required/optional fields for the Alert Rule Action UI component, provides an example and the webhook payload.

feat(alert-rules): Docs on Alert Rule UI Components

---

src/platforms/unity/native-support.mdx

Until now the docs only referred to the Android & iOS docs for symbol upload.

Unity: Expanded the native symbols upload 

---

src/includes/getting-started-primer/javascript.nextjs.mdx
src/platforms/javascript/guides/nextjs/manual-setup.mdx

There seem to be a number of changes in Next 12 which can break the SDK (depending on how you use it), so for the moment, let's make it clear that we're not expecting that combo to work out of the box.

fix(nextjs): Add note about lack of Next 12 support

---

src/components/markdown.tsx
src/components/sandboxLink.tsx
src/docs/contributing/linking.mdx
src/platforms/common/configuration/options.mdx

This allows you to add links to the sandbox in docs.
Usage:
```
<SandboxLink scenario="releases">sandbox</SandboxLink>
```
This will automatically take you to the correct project based on the current project selection so there's usually no need to specify `projectSlug`.

Add SandboxLinks component

---

src/components/markdown.tsx
src/components/navbar.tsx
src/components/sandboxLink.tsx
src/pages/index.tsx

This PR adds a Demo button to the navbar. When you click on it, it takes you to the Sentry sandbox.
Meanwhile, this PR also adds the `SandboxOnly` component so that it's available to use in mdx files also.

Sandbox btn

---

src/includes/sourcemaps/upload/webpack/javascript.mdx
src/platforms/javascript/guides/gatsby/index.mdx

Adds the docs supporting the Gatsby SDK initialization in a config file, see https://github.com/getsentry/sentry-javascript/pull/4064.

Add Gatsby docs for sentry config file

---

src/platforms/dotnet/guides/aspnetcore/index.mdx

Update the values listed on this page for the `MaxRequestBodySize` option for `appsettings.json` to match those available in the `Sentry.Extensibility.RequestSize` enumeration (https://github.com/getsentry/sentry-dotnet/blob/main/src/Sentry/Extensibility/RequestSize.cs). The current value `never` is not a valid value and the values should start with an uppercase letter.

Docs: Fix `MaxRequestBodySize` values

---

src/platforms/dotnet/guides/xamarin/troubleshooting.mdx

This PR adds an additional solution for users unable to send Events/Envelopes due to an issue with Xamarin for Android.
The URL path `...ingest.sentry.io...` uses Let's encrypt certificate where `sentry.io...` doesn't.
More information can be found here: https://github.com/xamarin/xamarin-android/issues/6351

Add troubleshooting for SSL error for Xamarin Android

---

src/platforms/javascript/common/troubleshooting/index.mdx

Requested by https://github.com/getsentry/sentry-ruby/issues/1597

docs(ruby): Add rails example for tunneling route

---

src/platforms/php/common/performance.mdx

In PHP the transaction is not automatically set to the Hub when it is created. I added the manual call to setSpan() that allow users to retrieve it later with getTransaction()
Tagging @stayallive for additional review as SDK mainteiner.

Add setSpan to custom instrumentation

---

src/docs/product/data-management-settings/filtering/index.mdx
src/docs/product/sentry-basics/environments/index.mdx

Replaces platform links to JavaScript-specific content with platform redirects so users can choose their platform on the following pages:
https://docs.sentry.io/product/sentry-basics/environments/#creating-environments
https://docs.sentry.io/product/data-management-settings/filtering/

replace platform links with platform redirects

---

src/platforms/common/enriching-events/breadcrumbs.mdx

Fixes link at the end of the Breadcrumbs SDK page that links back to the same page:
https://docs.sentry.io/platforms/python/guides/django/enriching-events/breadcrumbs/
_For information about what can be done with the hint, see Filtering Events._

fix circular link on common breadcrumbs page

---

src/includes/set-environment/elixir.mdx

Hi! Thanks for awesome library and documents ✨ 
`environment_name` configuration example missing in Elixir.
I think better  example has both `:prod` and `Mix.env()` configuration 👍 
Is ok??

docs(elixir): add elixir example for environment name configuration

---

package.json
src/gatsby/config.ts
yarn.lock

Upgrading gatsby-plugin-sharp from 2.x to 2.12 gives us lazy image builds (images are scaled and optimized when page is loaded), so image thumbnails are no longer generated on yarn develop. This is the biggest contributor to build times in local development.

ref(build): Upgrade gatsby-plugin-sharp

---

src/platforms/python/guides/pyspark/index.mdx

We've got some users asking about this. Let's make sure we are clear that the worker integration is not support for Spark 3.

add note about Spark 3 support

---

src/platforms/node/guides/aws-lambda/index.mdx

Follow https://github.com/getsentry/sentry-javascript/pull/4130

doc(serverless/aws-lambda)/Add documentation for captureAllSettledReasons option

---

src/wizard/ruby/index.md
src/wizard/ruby/rack.md
src/wizard/ruby/rails.md

Every other SDK sets traces sample rate to 1.0. Ruby/Rails/Rack set it to 0.5 even though the comment says 1.0

Update ruby traces sample rate to align with comment and other platforms

---

src/docs/product/data-management-settings/event-grouping/index.mdx

Mention that it works in sequential order, from stacktrace to message and not all at the same time.
@imatwawana Not sure if that's the best way to phrase this. It's important to specify that basically we base the grouping decision initially by stack trace and if that is not detected, then we will check exception info, and if that's missing too then we fallback to message.

Update text for default grouping algorithm

---

src/includes/getting-started-config/react-native.mdx
src/platforms/react-native/troubleshooting.mdx

Document how to fix promise rejection handling in troubleshooting page, also mention it on the getting started page as this is a major feature. 
Wait for https://github.com/getsentry/sentry-react-native/pull/1886 before merging.

feat(RN): Troubleshooting doc for promise rejection handling in React Native

---

src/includes/enriching-events/set-tag/apple.mdx

Hi,
Looking at https://docs.sentry.io/platforms/apple/guides/ios/enriching-events/tags/, it looked like the parameters key and value for `setTag` where reversed (probably due to them be in the reverse order in other languages).

fix(apple): Reverse parameters for scope.setTag

---

src/docs/product/integrations/deployment/vercel/index.mdx

It's currently not obvious that this step isn't independent of installation but part of it.
Fixes https://github.com/getsentry/sentry-docs/issues/4308.

fix(integrations): Clarify Vercel/Sentry project-linking step

---

src/includes/enriching-events/scopes/with-scope/apple.mdx

Searched for other occurrences of reversed parameters for scope.setTag for Cocoa. Brought up in https://github.com/getsentry/sentry-docs/pull/4377

fix(apple): Set tag parameters for with-scope

---

src/platforms/java/common/configuration/integrations/graphql.mdx
src/platforms/java/common/configuration/integrations/index.mdx
src/platforms/java/common/graphql.mdx

Related to https://github.com/getsentry/sentry-java/issues/1802

Add `sentry-graphql` docs.

---

src/platforms/apple/common/performance/instrumentation/automatic-instrumentation.mdx

We released a new fix for an issue with HTTP instrumentation on Apple.
The warning now states to update to 7.5.3.
Only merge after 7.5.3 is released, see https://github.com/getsentry/publish/issues/668.

feat(apple): Update alert on web APM

---

src/docs/product/issues/states-triage/index.mdx

Changes link to content about resolving issues with commits from GitLab to GitHub

change resolve with commit link from gitlab to github

---

src/platforms/android/common/proguard.mdx

Adds more intro text to ProGuard page
Fixes typo in page description
Addresses (in part) [issue 4421](https://github.com/getsentry/sentry-docs/issues/4421)

added intro text to proguard docs

---

src/platforms/unity/native-support.mdx

Android does not have to be done manually (but still can be).
So I've split the Debug Symbols section into Android, iOS, and Manual upload.
Will be reworked once more when the automated upload for iOS gets added.

feat(unity): Added automated Android symbol upload

---

src/platforms/dotnet/guides/aspnet/troubleshooting.mdx

This will help users that try to set their tags into Application_Start thinking it'll be available to all requests, but turned out they are only available on the scope from the framework initialization.

ASP.NET troubleshooting for global tags.

---

src/docs/product/alerts/best-practices.mdx
src/docs/product/alerts/index.mdx
src/docs/product/alerts/notifications/index.mdx

Moves Alerts Best Practices up one level in navigation
Adds required redirect
Updates sidebar order of pages under Alerts

move alert best practices up one level

---

src/docs/product/data-management-settings/event-grouping/stack-trace-rules.mdx
src/includes/in-app-frames/apple.mdx
src/platforms/common/usage/in-app-frames.mdx

The content on marking frames as in app for Cocoa/Apple was on the
common product docs. This is fixed now by moving it to an
extra platform page.
Fixes GH-4371

ref(apple): Move in app frames to platform page

---

src/includes/getting-started-install/react-native.mdx

Make sentry wizard its own bash instead of a tab

---

src/platforms/ruby/common/migration.mdx

It looks like `backtrace` is supported as per https://github.com/getsentry/sentry-ruby/pull/1550

Add backtrace to options for `capture_message`

---

src/includes/getting-started-verify/apple.mdx

The getting started verify section of Apple described crashing the app
SentrySDK.crash(). WatchOS doesn't support crashes though. Therefore,
the page now explains how to capture an error instead,
like Android or Java.
This came up in https://github.com/getsentry/sentry-cocoa/issues/406#issuecomment-982414653.

fix(apple): Getting Started  Verify

---

src/includes/performance/filter-span-example/react-native.mdx

The documentation for the [`shouldCreateSpanForRequest`](https://docs.sentry.io/platforms/react-native/performance/instrumentation/automatic-instrumentation/#shouldcreatespanforrequest) section shows the `BrowserTracing` integration, which may lead to confusion (as seen in the screenshot below). This PR adds a snippet for the `react-native` platform so the correct integration shows

[React Native] Fix integration example for shouldCreateSpanForRequest

---

src/includes/enriching-events/attachment-upload/unity.mdx

Came up here: https://github.com/getsentry/sentry-unity/issues/448
The Unity SDK has the Global Hub Mode set by default which prevents `WithScope` from working as it relies on `PushScope`.

fix(unity): Attachment upload sample

---

src/platforms/unity/native-support.mdx

The Unity SDK now provides automated symbol upload for both Android and iOS.

feat(unity): Automated symbol upload

---

src/docs/product/issues/issue-owners/index.mdx

Adds a note indicating that issue ownership rules take precedence over codeowners info

add note about issue owners precedence over codeowners

---

src/includes/enriching-events/attachment-init-with-path/unity.mdx
src/includes/enriching-events/attachment-upload/unity.mdx
src/platforms/common/enriching-events/attachments/index.mdx

Modified snippets and replaced lines about `local scope` to be more Unity-specific. Unity has only a global scope.

feat(unity): Attachment docs

---

src/includes/getting-started-primer/javascript.nextjs.mdx

Reverts message back to what it originally was now that [Next.js 12 is supported](https://github.com/getsentry/sentry-javascript/pull/4093)

Fix Next.js intro note to account for Next.js 12 support

---

src/docs/product/accounts/sso/saml2.mdx

Generic SAML2 providers can now use SCIM, so let's reflect that in the docs.

update SCIM docs for SAML2 Providers

---

src/platforms/go/common/migration.mdx

Similar to #2040.
Affected page https://docs.sentry.io/platforms/go/migration/#integrations

fix: Split consecutive code blocks in Go migration guide

---

src/docs/product/sentry-basics/tracing/distributed-tracing.mdx
src/includes/performance/control-data-truncation/javascript.mdx
src/platforms/javascript/guides/angular/components/tracehelpers.mdx
src/platforms/javascript/guides/react/components/profiler.mdx

Update the span operations for performance monitoring in docs based on
what has been outlined in https://develop.sentry.dev/sdk/performance/span-operations/.

Update span operations in docs

---

src/platforms/apple/common/dsym.mdx

Add --force-foreground for calling sentry-cli in the Xcode run script
phase. This flag lets Xcode wait for the upload process to finish.
I had issues with uploading dSYMS with Xcode. Adding this flag fixed it for me and it also makes sense to wait until the dSYMS are uploaded.

fix: Add --force-foreground to Xcode Run Script

---

src/platforms/javascript/common/sourcemaps/troubleshooting_js.mdx

Per @souredoutlook 
Currently we list the "Verify artifact names match sourceMappingURL value" step in our source maps troubleshooting guide above the "Verify Artifact Names Match Stack Trace Frames". Given that we've tightened source map fetch timeouts and recommend to always upload, switching the order of these two steps, as "Verify Artifact Names Match Stack Trace Frames" is the advice that's more relevant to users that upload.

change order of JS source maps troubleshooting steps

---

.github/ISSUE_TEMPLATE/build-issue.yml
.github/ISSUE_TEMPLATE/config.yml

@imatwawana Here is that additional issue template we discussed a few weeks ago, for issues related to the docs build pipeline.

Add a template for build issues

---

src/docs/product/alerts/create-alerts/issue-alert-config.mdx

Add more details on how the approximation of percent-based alerts.
> This is approximated by taking the number of sessions in the last hour and scaling it to the alerting window appropriately. For example, if the alert is configured to look at the last 5 minutes, the number of sessions is approximated by taking the number of sessions in the last hour and dividing it by 12.
[FIXES WOR-1187](https://getsentry.atlassian.net/browse/WOR-1187)

fix(docs): Add more details for percent-based alerts

---

src/platforms/python/guides/quart/index.mdx
src/wizard/python/quart.md

This should guide a new user how to integrate Sentry with Quart.
See also https://github.com/getsentry/sentry-python/pull/1248
I've left `???` in as I'm unsure what versions to put in.

Add documentation for Quart based on the sanic documentation

---

src/docs/product/releases/setup/index.mdx

Document on how a project's versioning scheme is determined and what it's based on.
> The behavior of a few features depends on whether a project is using semantic or time-based versioning.
> 
> - Regression detection
> - `release:latest`
> 
> We automatically detect whether a project is using semantic or time-based versioning based on:
> 
> - If ≤ 2 releases total: we look at most recent release.
> - If 3-10 releases total: if any of the most recent 3 releases is semver, project is semver.
> - If 10+ releases: if any of the most recent 3 releases is semver, and 3 out of the most recent 10 releases is semver, then the project is semver.
[FIXES WOR-1285](https://getsentry.atlassian.net/browse/WOR-1285)

feat(releases): Add how versioning scheme is determined

---

src/includes/getting-started-primer/apple.macos.mdx
src/includes/getting-started-primer/apple.mdx

With https://github.com/getsentry/sentry-cocoa/pull/1596
the Cocoa SDK has support for fatalError, assert, and precondition.
This PR mentions this in the features list.
Only merge after sentry-cocoa 7.8.0 is released.

feat(apple): fatalError, assert, and precondition

---

src/platforms/ruby/common/configuration/options.mdx
src/platforms/ruby/common/migration.mdx

- Add missing `context_lines` to Ruby document
- Add `Exception#raven_context` migration guide

Improve Ruby docs

---

src/docs/product/cli/installation.mdx

Windows (mingw bash) complains about sudo missing, manually specifying the installation path helps here.
Also includes another small change, if I'm not mistaken, it's "if necessary", not "if necessarily".

Document INSTALL_DIR for get-cli

---

src/platforms/php/guides/laravel/index.mdx

Laravel's exception handler does not call the report(able) callbacks for exceptions that should not be reported. See https://github.com/laravel/framework/blob/8.x/src/Illuminate/Foundation/Exceptions/Handler.php#L223-L225

Remove redundant check from Laravel code example

---

src/docs/product/issues/index.mdx

When starting to look into Issues the triage links us to the Issue Details section which doesn't mention anything about triaging an issue.

Update triage link to point to triage section

---

src/platforms/react-native/troubleshooting.mdx

Documents auto promise patching added in https://github.com/getsentry/sentry-react-native/pull/1984 and demonstrates how to disable the patching or how to use the patching with other polyfilling libraries.

feat: Update RN troubleshooting docs for promise polyfill fix

---

src/includes/configuration/config-intro/unity.mdx

To at least document our current limitation to have to use the config window to get native support.

Unity: Native support limited to config window

---

src/platforms/common/configuration/options.mdx

Android, Apple, Flutter, and Java support the basic option
maxCacheItems.
Fixes GH-3307

feat: Enable maxCacheItems for Mobile

---

src/platforms/common/enriching-events/identify-user.mdx

We special-case some platform identifiers in Relay when it comes to the
default value of `user.ip_address`. This causes a bunch of confusion for
customers and SDK authors.
This problem came up in an old customer issue involving the native SDK, and it appears that the native SDK does not send `ip_address={{auto}}` when running as part of a desktop application (which it could maybe try to detect)

fix: Document {{auto}} properly [ISSUE-737]

---

src/platforms/apple/common/performance/instrumentation/automatic-instrumentation.mdx

Clarify that the UIViewController Instrumentation only creates
transactions for in-app UIViewControllers.

fix(apple): Clarify ViewController Instrumentation

---

src/platforms/android/migration.mdx

Deprecate `autoUpload` and introduce new `includeProguardMapping` and `autoUploadProguardMapping` options in the SAGP migration guide.

feat: Update migration guide with the new includeProguardMapping flag

---

src/docs/product/integrations/data-visualization/grafana.mdx
src/docs/product/integrations/data-visualization/index.mdx
src/docs/product/integrations/index.mdx

Adds page for Sentry's Grafana integration
Adds link to new page from Integrations index page
Adds link to new page from Data & Visualizations index page

add grafana integration page

---

src/docs/product/integrations/integration-platform/webhooks.mdx

Rather than rewriting this information, I simply added a link to the UI component docs for select options and external issues. Since it doesn't exactly follow the format outlined on the webhook docs page (For example, we claim that all webhooks will contain Sentry-Hook-Resource and Sentry-Hook-Signature headers. I set this up locally and we don't send the same headers) it felt both redundant and incorrect to rewrite what's in the UI component docs. 
See [API-641](https://getsentry.atlassian.net/browse/API-641)

ref(integration platform): Link to additional webhook info

---

src/docs/product/dashboards/custom-dashboards/index.mdx
src/docs/product/issues/index.mdx

Added **Data Set** section to Custom Dashboards page + line in **Table Results** linking to **Data Set**
Added a link from the Issues Page to **Data Set*.
Open to feedback on wording or placement

feat(dashboards): Added Data Set section to Custom Dashboards

---

src/docs/product/cli/dif.mdx

This change was introduced 2 months ago but forgot to add docs here.
Closes https://github.com/getsentry/sentry-cli/issues/1075

docs(cli): Add no-upload option for dif-upload command

---

src/platforms/flutter/common/performance/instrumentation/automatic-instrumentation.mdx

Documentation for auto transactions support added by https://github.com/getsentry/sentry-dart/pull/643.

feat: Document Flutter Auto Transactions

---

src/platforms/common/configuration/options.mdx

Followup for #4579: Clarify that this setting is for resend attempts.
Perhaps there should also be some clarification around which circumstances will lead to resend attempts (something like 5xx errors, connection failures or DNS failures, but I'm just guessing here :)

Clarify send_attempts option

---

src/platforms/android/common/performance/instrumentation/automatic-instrumentation.mdx
src/platforms/android/configuration/integrations/file-io.mdx
src/platforms/java/common/performance/instrumentation/file-io.mdx
src/wizard/android/index.md

Changes "file" in "file I/O" to lower case in most places. 
Since I reviewed previous PRs using this term, I've learned this is a generic term that's generally not capitalized in the places where it's spelled out, so we should avoid setting a precedent that doesn't align with other documentation.

fixe file i/o capitalization

---

src/platforms/apple/common/migration.mdx
src/platforms/apple/common/performance/instrumentation/automatic-instrumentation.mdx

We can move the warning for using minimum 7.5.3 to avoid crashes
with Cocoa to the migration page as we already released 7.9.0.

ref(apple): Move warning for min 7.x to migration

---

src/includes/getting-started-config/apple.mdx

When using SwiftUI the way of initializing the SDK is different.
This adds documentation for that case.

feat(apple): How to init SDK when using SwiftUI

---

src/platforms/flutter/common/performance/instrumentation/automatic-instrumentation.mdx

- Document flutter auto transaction idle time parameter and trimming
Relates to https://github.com/getsentry/sentry-dart/pull/702 and https://github.com/getsentry/sentry-dart/pull/705

Document flutter auto transaction idle time parameter and trimming

---

src/platforms/index.mdx

Hello!
We implemented quite [a basic Sentry.io SDK for the Defold engine](https://github.com/indiesoftby/defold-sentinel), i.e. it can catch errors, capture messages, collect breadcrumbs. 
I would be grateful if you added a link to the SDK to the documentation.

Add "Defold" to the list of Community Supported SDKs

---

src/platforms/react-native/manual-setup/manual-setup.mdx

Since the git submodule to sentry-cocoa was removed in https://github.com/getsentry/sentry-react-native/commit/6c3d4cf8da2b3168b29695417177cb49587cb84f#diff-fe7afb5c9c916e521401d3fcfb4277d5071798c3baf83baf11d6071742823584, manually linking the xcodeproj no longer worked. This PR removes the instructions saying so and instead instructs how to manually link with cocoapods.

fix(RN): Remove broken manual linking install option for React Native

---

src/includes/getting-started-install/apple.ios.mdx
src/includes/getting-started-install/apple.macos.mdx
src/includes/getting-started-install/apple.mdx
src/includes/getting-started-install/apple.tvos.mdx
src/includes/getting-started-install/apple.watchos.mdx
src/wizard/apple/index.md
src/wizard/apple/ios.md
src/wizard/apple/macos.md

The wizard and getting started page mentions that we support
alternate installation methods after explaining how to install the
SDK with CocoaPods. I hypothesize that most people don't read
the hint because they see CocoaPods and then skip the whole
section. This happened to me, and I wondered where we point
out SPM and Carthage. Mentioning the other installation
methods earlier could fix this problem.

ref(apple): Mention other install methods sooner

---

src/platforms/javascript/guides/nextjs/manual-setup.mdx

It's not a class or an interface, so no reason it should be capitalized.

fix(nextjs): Use lower camel case for webpack plugin options object

---

src/platforms/javascript/guides/nextjs/manual-setup.mdx

This documents the option added in https://github.com/getsentry/sentry-javascript/pull/4436, to allow users to use `hidden-source-map` as their webpack `devtool` for client-side builds. (With this option enabled, the same sourcemaps are generated, but the final bundles don't have a `sourceMappingURL` comment, effectively "hiding" the sourcemaps from the browser. Doing this prevents the browser from complaining in situations where the maps are not publicly hosted.)

feat(nextjs): Document `hideSourceMaps` option

---

src/platforms/native/guides/ue4/index.mdx

Changing config file in project directory will NOT result sending data to provided DataRouterUrl (at least on 4.27). 
Way for this to work, its change engine installation CrashReporterClient config.
Forum attached below in document suggests same solution: 
https://forum.sentry.io/t/unreal-engine-crash-reporter-cant-get-it-to-work/7643/2
So I propose to change main documentation to avoid confusion.

fix(ue4): Fix UE4 crash reporting config info

---

src/docs/product/integrations/project-mgmt/shortcut/index.mdx

This PR will fix the broken link for Documentation on the Shortcut sentry app. The redirect to the page was never added after the slug was changed from `clubhouse` to `shortcut`. This should work (even though it's untested) since the code that create's these links is shared for all sentry apps, and is structured the same as Linear and Rookout's links.
This is the `getsentry/sentry` code:
https://github.com/getsentry/sentry/blob/master/static/app/views/organizationIntegrations/sentryAppDetailedView.tsx#L87-L98
This is what redirects look like for other sentry-apps:
https://github.com/getsentry/sentry-docs/blob/leander/shortcut-docs/src/docs/product/integrations/project-mgmt/linear/index.mdx#L5

chore(shortcut): Add redirect from sentry app details page

---

src/includes/configuration/rewrite-frames/javascript.mdx

Adding a reference to our default implementation will help people understand how their custom `iteratee` should look.

docs(js): Add RewriteFrames iteratee reference

---

src/includes/configuration/before-send-fingerprint/php.symfony.mdx
src/includes/configuration/before-send-hint/php.symfony.mdx
src/includes/configuration/before-send/php.symfony.mdx
src/includes/configuration/config-intro/php.laravel.mdx
src/includes/configuration/config-intro/php.mdx
src/includes/configuration/config-intro/php.symfony.mdx
src/includes/configuration/sample-rate/php.symfony.mdx
src/includes/enriching-events/breadcrumbs/before-breadcrumb/php.laravel.mdx
src/includes/enriching-events/breadcrumbs/before-breadcrumb/php.symfony.mdx
src/includes/performance/always-inherit-sampling-decision/php.symfony.mdx
src/includes/performance/configure-sample-rate/php.symfony.mdx
src/includes/performance/traces-sample-rate/php.symfony.mdx
src/includes/performance/traces-sampler-as-filter/php.symfony.mdx
src/includes/set-environment/php.symfony.mdx
src/includes/set-release/php.symfony.mdx
src/platforms/common/data-management/sensitive-data/index.mdx
src/platforms/php/guides/symfony/configuration/symfony-options.mdx
src/platforms/php/index.mdx

I got this done quicker than expected :)
- Added a bunch of Symfony specific snippets (basically everywhere we had them for Laravel)
- Moved the Symfony specific config options page to a more logical place (mirroring Laravel)
- Remove the performance monitoring section from the general getting started page for PHP (because it makes no sense having it there)
- Remove a weird note in the PHP docs mentioning specific config docs but linking to `/product/releases/`
- Simplified some Symfony snippets to be more concise
Fixes #4613.

PHP improvements

---

src/platforms/apple/common/dsym.mdx

This is no longer relevant, as we fixed the issue in https://github.com/getsentry/sentry-cli/pull/1104

docs(ios): Remove force-foreground note

---

src/docs/product/dashboards/custom-dashboards/index.mdx

Removing EA note around Data Set selection due to GA'ing feature

feat(dashboards): Remove EA note for widget dataset selection

---

src/platforms/apple/common/configuration/out-of-memory.mdx

Add a warning to the OOM page for Cocoa about falsely reported
OOMs.
Related to https://github.com/getsentry/sentry-cocoa/issues/1645.

feat(apple): App hangs can lead to false OOMs

---

src/docs/product/dashboards/widget-library/index.mdx

We removed the `assigned_or_suggested:[me, none]` condition in the prebuilt widget. Updating documentation to better reflect this.
https://github.com/getsentry/sentry/pull/31427

fix(dashboards): changed a line to better reflect issue widget condition

---

src/includes/performance/add-spans-example/native.mdx
src/includes/performance/always-inherit-sampling-decision/native.mdx
src/includes/performance/concurrency/native.mdx
src/includes/performance/configure-sample-rate/native.mdx
src/includes/performance/connect-errors-spans/native.mdx
src/includes/performance/uniform-sample-rate/native.mdx
src/platforms/common/configuration/sampling.mdx
src/platforms/common/performance/index.mdx
src/platforms/common/performance/instrumentation/custom-instrumentation.mdx

Some additional content has been added that is important for users of the native SDK. This explains the rationale behind a decision made during its implementation, and what it means for the end user once they start using the SDK. 
Also forgot to add in an early access/experimental flag at the beginning of the docs as a warning that the API may be unstable.
Also fixed a minor copy-paste error.
A bunch of warnings all over the sampling-related document have been added because the native SDK doesn't implement half of the tools described in it.
handy links to pages changed to see how it Really Looks Like to users:
- https://sentry-docs-git-native-perf-ea.sentry.dev/platforms/native/performance/
- https://sentry-docs-git-native-perf-ea.sentry.dev/platforms/native/configuration/sampling/
- …

feat(perfmon): Polish up native performance monitoring 

---

src/platforms/react-native/performance/instrumentation/automatic-instrumentation.mdx

We [support the `maxTransactionDuration` option](https://github.com/getsentry/sentry-react-native/blob/4fd13137fe71984d1166c33198076da9db28f158/src/js/tracing/reactnativetracing.ts#L53) in the React Native SDK, but it's missing from the docs.

fix(react native): Add `maxTransactionDuration` to tracing config options

---

src/includes/configuration/before-send-fingerprint/php.symfony.mdx
src/includes/configuration/before-send-hint/php.symfony.mdx
src/includes/configuration/before-send/php.symfony.mdx
src/includes/enriching-events/breadcrumbs/before-breadcrumb/php.symfony.mdx
src/includes/performance/always-inherit-sampling-decision/php.symfony.mdx
src/includes/performance/configure-sample-rate/php.symfony.mdx
src/includes/performance/traces-sampler-as-filter/php.symfony.mdx
src/platforms/php/guides/symfony/configuration/symfony-options.mdx

Fix Symfony callback syntax

---

src/includes/getting-started-config/javascript.angular.mdx
src/includes/getting-started-config/javascript.mdx
src/includes/getting-started-config/javascript.react.mdx
src/includes/getting-started-config/javascript.vue.mdx
src/includes/performance/beforeNavigate-example/javascript.mdx
src/includes/performance/beforeNavigate-example/javascript.nextjs.mdx
src/includes/performance/configure-sample-rate/javascript.mdx
src/includes/performance/configure-sample-rate/javascript.react.mdx
src/includes/performance/configure-sample-rate/javascript.vue.mdx
src/includes/performance/enable-automatic-instrumentation/javascript.mdx
src/includes/performance/enable-automatic-instrumentation/javascript.react.mdx
src/includes/performance/filter-span-example/javascript.mdx
src/includes/performance/filter-span-example/javascript.nextjs.mdx
src/includes/performance/group-transaction-example/javascript.mdx
src/includes/performance/tracingOrigins-example/javascript.mdx
src/includes/performance/tracingOrigins-example/javascript.nextjs.mdx
src/platforms/javascript/common/configuration/integrations/custom.mdx
src/platforms/javascript/common/install/cdn.mdx
src/platforms/javascript/common/performance/instrumentation/automatic-instrumentation.mdx
src/platforms/javascript/guides/react/configuration/integrations/react-router.mdx
src/platforms/javascript/guides/vue/configuration/integrations/vue-router.mdx
src/platforms/node/common/configuration/integrations/index.mdx
src/wizard/capacitor/index.md
src/wizard/javascript/angular.md
src/wizard/javascript/angularjs.md
src/wizard/javascript/backbone.md
src/wizard/javascript/browser.md
src/wizard/javascript/index.md
src/wizard/javascript/react.md
src/wizard/javascript/vue.md

In https://github.com/getsentry/sentry-javascript/pull/4204 we updated the `BrowserTracing` import in the JS SDK to be exported individually. We want users to use this individual import so that the other integrations are treeshaken. This patch updates our documentation to import `BrowserTracing` directly from `@sentry/tracing` instead of through the `Integrations` object, which hopefully should lead to a bundle size reduction for people.

Update BrowserTracing import for tree shaking

---

src/platforms/unity/troubleshooting.mdx

Added a section to troubleshooting explaining how to deal with `ReflectionTypeLoadException` due to Sentry.Unity.Editor.iOS

Unity: Added troubleshooting for ReflectionTypeLoadException 

---

src/docs/product/integrations/integration-platform/ui-components/index.mdx

Small typo correction with underscores and italics.
Fixes:

chore(docs): UI Component page typos

---

src/docs/clients/javascript/tips.mdx

Update tips.mdx to use updated `ignoreErrors` and `denyUrls`, also update gist link to a version that is compatible. If you try to use the code given here, it will error in typescript, or simply do nothing as far as URLs go in javascript, since the `ignoreUrls` option was renamed to `denyUrls`

Update tips.mdx to use updated ignoreErrors and denyOptions

---

src/docs/product/issues/states-triage/index.mdx

Currently Metric Alerts can trigger ignored Issues so it would be helpful to add it in the docs in order set the right expectations and avoid unnecessary escalations

docs: update Ignore paragraph

---

src/platforms/common/data-management/debug-files/symbol-servers.mdx

For custom symbols servers we have a minimum download speed in order
to protect our own infrastructure.  Document this publicly.

fix: Mention the minimum symbol server download speed

---

src/docs/product/sentry-basics/search/index.mdx

Removes note indicating that advanced search is plan gated.
Fixes styling of another note.

remove advanced search plan note

---

src/platforms/javascript/common/troubleshooting/index.mdx

From time to time we get asked how to capture an error when a static resource fails to load. This moves a solution provided in a GitHub comment into the docs, so that it's easier to find.
Fixes https://github.com/getsentry/sentry-javascript/issues/4499
Fixes https://github.com/getsentry/sentry-javascript/issues/3382

feat(browser): Add section for capturing resource 404s

---

src/platforms/dotnet/guides/aspnetcore/index.mdx
src/platforms/dotnet/guides/aspnetcore/performance/instrumentation/automatic-instrumentation.mdx
src/wizard/dotnet/aspnetcore.md

Adds initialization sample for .NET 6 with Minimal API in C# and F#
About the wizard, should we add another wizard for the Minimal API model or stick with the ASP.NET Core one and mention how to set up the Minimal API?
Close https://github.com/getsentry/sentry-dotnet/issues/1453

.NET 6 Add minimal API description.

---

src/includes/getting-started-verify/unity.mdx
src/platforms/unity/troubleshooting.mdx

Unity logged exceptions are now marked as `unhandled` by default.

Unity: Added troubleshooting for unhandled exceptions 

---

src/includes/getting-started-config/dotnet.aspnet.mdx
src/platforms/dotnet/guides/aspnet/index.mdx
src/platforms/dotnet/guides/aspnet/performance/included-instrumentation.mdx
src/platforms/dotnet/guides/entityframework/index.mdx
src/wizard/dotnet/aspnet.md

This simplifies the error capture for users and also adds the Unhandled tag to the errors.
Closes https://github.com/getsentry/sentry-dotnet/issues/1413

ASP.NET: Replace global error catcher with new extension:

---

src/includes/enriching-events/attachment-upload/dotnet.mdx
src/includes/enriching-events/scopes/with-scope/dotnet.mdx

WithScope will be replaced by the individual Capture methods that have a callback for a local scope.

Update: .NET replacing WithScope with Capture overload

---

src/docs/product/integrations/index.mdx

Corrected the destination for the link for ```spike.sh```.

Correct link to spike.sh page

---

src/platforms/android/common/gradle.mdx
src/platforms/android/configuration/integrations/file-io.mdx
src/platforms/android/configuration/integrations/room-and-sqlite.mdx
src/wizard/android/index.md

* Update to the latest beta
* I removed the deprecated flag a bit too early, as the `3.0.0` is still not GA'd, so had to revert it back

chore(android): Update SAGP versions and re-add deprecated flag

---

src/components/cliChecksumTable.tsx
src/components/jsBundleList.tsx
src/docs/product/cli/installation.mdx
src/gatsby/createSchemaCustomization/appSchema.ts
src/gatsby/createSchemaCustomization/index.ts
src/gatsby/sourceNodes/appRegistryNodes.ts
src/gatsby/sourceNodes/index.ts
src/gatsby/utils/appRegistry.ts

Query our release registry and display checksums for all available sentry-cli builds.

docs(cli): Add build checksums table for CLI executables

---

src/platforms/common/data-management/sensitive-data/index.mdx
src/platforms/common/enriching-events/breadcrumbs.mdx
src/platforms/common/enriching-events/user-feedback.mdx

Replaced remaining text with PlatformIdentifier for before-send, before-breadcrumb
Mostly fixed on [PR 4422](https://github.com/getsentry/sentry-docs/pull/4422)

replace text with PlatformIdentifier 

---

src/platforms/javascript/guides/react/configuration/integrations/react-router.mdx

To encourage users to enable paramaterization functionality with the react router integration, we remove the initial code snippet showing setting up the integration. This is as some users may stop at this point and not continue reading (after copy pasting the initial code snippet into their application). With this change, users now should read into the `Parameterized transaction names` section and select a method appropriately to use.

fix: Encourage paramaterization in react router integration docs

---

src/platforms/node/guides/aws-lambda/index.mdx

this pr was built on top of https://github.com/getsentry/sentry-javascript/pull/4620

ref(serverless): new options for ignoring sentry errors

---

src/platforms/java/common/performance/instrumentation/jdbc.mdx

Related to: https://github.com/getsentry/sentry-java/pull/1915

Java: Document how to disable spy.log file.

---

src/docs/product/dashboards/widget-library/index.mdx

Adds a reference to the new `links` column in Issue Widgets that allows displaying Jira and Github tickets.

feat(dashboards): Issue Widgets Links column

---

src/platforms/javascript/common/configuration/integrations/default.mdx

`s/denyUrl/denyUrls` and `s/allowUrl/allowUrls`.

fix(js): Fix option name typos in `InboundFilters` description

---

src/docs/product/accounts/quotas/manage-event-stream-guide.mdx

This PR clarifies the fact that `ignoreErrors` matches on `"ExceptionType: exceptionValue"` as one string.
Fixes https://github.com/getsentry/sentry-docs/issues/4762

Adjust description of ignoreErrors

---

src/docs/product/cli/dif.mdx

Based on this comment from @marandaneto, the --write-properties syntax is no longer preferred. Instead, use --uuid https://github.com/getsentry/sentry-cli/issues/914#issuecomment-1050023401

Write Properties is not recommended. Use --uuid

---

src/docs/product/cli/dif.mdx

An extension of https://github.com/getsentry/sentry-docs/pull/4764
Closes https://github.com/getsentry/sentry-docs/issues/4431

docs(cli): Explain how to add ProGuard UUID to Android SDK

---

src/templates/apiPage.tsx

If the parameter has a fixed number of choices via the openapi `enum` field, show them along with the description.

feat(apidocs): show schema enums on param fields if they exist

---

src/platforms/javascript/common/install/lazy-load-sentry.mdx

In our current implementation of the feature, a session and a pageload transaction are essentially one and the same, which means that release health doesn't work any better than tracing does when you're using the loader. This clarifies that in the loader's Limitations section.
Fixes https://github.com/getsentry/sentry-docs/issues/4722.

fix(browser): Mention release health in loader limitations section

---

src/platforms/javascript/guides/angular/config.yml

This PR changes the NPM package link in the right nav component in the platform SDK
details panel. Instead of linking to the generic `@sentry/browser` SDK package,
it now links to the Sentry Angular SDK package (`@sentry/angular`).
Additionally, the `description` property is added to the `config.yml` file. 
All changes are based on the `@sentry/react` `config.yml`

fix(angular): change NPM link from `@sentry/browser` to `@sentry/angular`

---

src/docs/product/cli/send-event.mdx

It may seem to some that this edit (adding a link in this page to more info on the .sentryclirc file) is nit-picky or pedantic ("we can't link to EVERYTHING"), but let me share why it seems useful. 
I found this page as it's pointed to from a blog post on the Sentry site (https://blog.sentry.io/2021/11/18/monitoring-our-local-development-environment-with-sentry). The blog post talks about the bash-hook feature, showing editing of a bash script to monitor it for errors, including putting in the needed sentry env vars. It links to this docs page for more on bash hooks, but only the docs page talks about using the .sentryclirc file as an option for a more central place to put the associated env vars. 
And so, since someone may find this doc page that way--and learn of the .sentryclirc file …

Add link to info on .sentryclirc file

---

src/platforms/apple/common/configuration/out-of-memory.mdx

OOM events don't that much context as typical unhandled errors.
We frequently get asked why that is. This PR adds clarification
for that.

feat(apple): Clarify why OOMs don't have much context

---

src/docs/product/accounts/quotas/index.mdx
src/docs/product/data-management-settings/filtering/index.mdx

Add details about which value to set and where to get it from for inbound filtering errors by message.
Unfortunately, there's no clear indication in the docs as to what is the correct value to set for filtering errors by message. It took me 30 minutes to find out why message filtering with the help of this [help center article](https://help.sentry.io/product-features/configuration/why-isn-t-filter-by-error-message-working/). The obvious place for that information would be here IMHO.

docs: clarify message filtering

---

src/platforms/android/configuration/integrations/timber.mdx
src/platforms/android/migration.mdx

Merge after this is shipped https://github.com/getsentry/sentry-java/pull/1898

chore(android): Mention that Timber.tag is not supported

---

src/includes/getting-started-primer/dart.mdx
src/includes/getting-started-primer/flutter.mdx
src/platforms/android/configuration/integrations/timber.mdx
src/platforms/dart/configuration/integrations/logging.mdx

Closes https://github.com/getsentry/sentry-docs/issues/4472

feat: Logging docs for Dart and Flutter

---

src/templates/apiPage.tsx

With our new API tooling, we automatically grab all of the required scopes from the endpoint, of which only one scope is needed, not all of them. On the docs generation side, we should probably list them in direction of least privileged to most privileged (e.g. `project:read` before `project:admin`).

feat(apidocs): update scope required description

---

src/docs/product/integrations/integration-platform/index.mdx
src/docs/product/integrations/integration-platform/webhooks.mdx

Add documentation for the new Sentry app comment webhooks that were added in https://github.com/getsentry/sentry/pull/32245

feat(sentry apps): Add docs for comment webhooks

---

src/docs/product/issues/index.mdx

Issue Widgets has already GA'd which means this EA note is no longer needed.

fix(dashboards): Removes ea note from issue widget text

---

src/includes/configuration/auto-session-tracking/ruby.mdx
src/platforms/common/configuration/releases.mdx

Description about auto session tracking in Ruby. This feature is currently implemented in the Ruby SDK and will be released in about a week.

Add documentation about auto session tracking in Ruby

---

src/platforms/common/enriching-events/event-processors.mdx

Moved the Event Processors page that was under Node.js to the common content for all platforms so it can be shared by JavaScript and React Native.

move event processors to common content

---

src/includes/set-level/javascript.mdx

The current sample is a bit confusing
resulting on an <unknown> error
The refactored sample will describe that an error inside of WithScope will have the event level set by the defined setlevel where events outside of WithScope will have their default values set
Before
After

Fix per event level description

---

src/includes/enriching-events/set-transaction-name/python.mdx

For reasons of backwards compatibility, we still support changing the active transaction's name by assigning to `scope.transaction`, even though `scope.transaction` is actually the `Transaction` object whose name you're changing. Eventually we won't support it, though, and in the meantime it's very confusing. This PR therefore updates the code to do it the right way, which is to first retrieve the transaction and then set its name directly.
Fixes https://github.com/getsentry/sentry-python/issues/1155.

fix(python): Update snippet for setting transaction name

---

src/includes/performance/enable-tracing/native.mdx

One of the requirements to enable perfmon in the native SDK was removed (https://github.com/getsentry/sentry-native/pull/678) which means it's enabled by default. This updates the docs to reflect that change. Apologies that this came in a bit late relative to the actual change itself 😔

chore(perfmon): Remove compile time requirement to use performance monitoring in the native SDK

---

src/includes/getting-started-primer/android.mdx
src/includes/getting-started-primer/flutter.mdx
src/includes/performance/configure-sample-rate/dart.mdx
src/includes/performance/configure-sample-rate/flutter.mdx
src/platforms/android/common/performance/instrumentation/automatic-instrumentation.mdx
src/platforms/apple/common/performance/instrumentation/automatic-instrumentation.mdx
src/platforms/dart/common/performance/instrumentation/automatic-instrumentation.mdx
src/platforms/flutter/common/performance/instrumentation/automatic-instrumentation.mdx
src/platforms/react-native/performance/instrumentation/automatic-instrumentation.mdx

cc @denrase 
* Removed the beta notes since they are GA already.
* Removed the duplicated slow/frozen explanations since they are explained under the Mobile vitals already, single source of truth is better.
https://github.com/getsentry/sentry-dart/pull/784
Merge after: https://github.com/getsentry/publish/issues/927

Mobile Vitals for Flutter

---

src/platforms/javascript/common/configuration/webworkers/index.mdx

According to https://docs.sentry.io/platforms/javascript/usage/ it should be `captureException`.

Correct method name

---

src/includes/getting-started-primer/dart.mdx
src/includes/getting-started-primer/flutter.mdx
src/platforms/dart/common/performance/instrumentation/automatic-instrumentation.mdx
src/platforms/dart/configuration/integrations/dio.mdx
src/platforms/dart/configuration/integrations/http-integration.mdx
src/platforms/flutter/common/performance/instrumentation/automatic-instrumentation.mdx

Closes https://github.com/getsentry/sentry-docs/issues/4602
Merge after: https://github.com/getsentry/sentry-dart/pull/791
and https://github.com/getsentry/sentry-release-registry/pull/67

Feat: Document Dio for Dart/Flutter

---

src/platforms/react-native/touchevents.mdx

https://github.com/getsentry/sentry-react-native/pull/2068
Merge only after https://github.com/getsentry/publish/issues/867 gets published

feat(RN): Touch event boundary now take a sentry-label prop

---

src/platforms/apple/common/configuration/out-of-memory.mdx

Change warning for falsely reported OOMs.
Only merge after https://github.com/getsentry/sentry-cocoa/pull/1695 is released.

fix(apple): Falsely reported OOMs

---

src/platforms/javascript/common/install/cdn.mdx

A number of PRs ([#4674](https://github.com/getsentry/sentry-javascript/pull/4674), [#4699](https://github.com/getsentry/sentry-javascript/pull/4699), [#4718](https://github.com/getsentry/sentry-javascript/pull/4718)) have recently added to the bundles available for use on the CDN. This documents the new options, and does some general wordsmithing on the page.

feat(js): Document new bundle varieties

---

src/platforms/javascript/guides/nextjs/manual-setup.mdx

This documents the option added in https://github.com/getsentry/sentry-javascript/pull/4705, which allows users to choose to cast a wider net when uploading sourcemaps for client-side code.

feat(nextjs): Add `widenClientFileUpload` option

---

src/platforms/common/configuration/options.mdx

This documents the new `normalizeMaxBreadth` option added to JS-based SDKs in https://github.com/getsentry/sentry-javascript/pull/4689, which controls how many properties or entries any given object or array will contain after normalization.
Ref: https://getsentry.atlassian.net/browse/WEB-712

feat(JS): Add `normalizeMaxBreadth` option

---

src/includes/getting-started-config/node.mdx

Reflects: https://github.com/getsentry/sentry-javascript/issues/4731

fix(node): Update node tracing ESM imports.

---

src/docs/product/dashboards/index.mdx

Adds documentation for the Widget Viewer in the Dashboards page

docs(dashboards): Adds docs for Widget Viewer

---

src/platforms/android/configuration/integrations/fragment.mdx
src/platforms/android/configuration/integrations/okhttp.mdx
src/platforms/android/configuration/integrations/timber.mdx

Merge after 3.1.0 of SAGP is shipped

feat(android): Add autoinstallation sections for okhttp, fragment and timber

---

src/docs/product/accounts/pricing.mdx
src/docs/product/accounts/quotas/index.mdx
src/docs/product/accounts/quotas/manage-event-stream-guide.mdx

This pull request updates the current on-demand budget documentation in anticipation of the rollout of the new on-demand budgets feature to all performance plans on the week of April 4, 2022.  This pull request should not be merged until this roll out completes.
Changelog:
- I've renamed "On-Demand Spending Cap" to "On-Demand Budget"
- Added blurbs on shared and per-category on-demand budget strategies.

feat(billing): Update documentation surrounding on-demand budgets

---

package.json
yarn.lock

Linked to https://github.com/getsentry/platformicons/pull/55

chore(platformicons): update to 4.4.0

---

src/platforms/apple/common/performance/instrumentation/automatic-instrumentation.mdx

Improve the wording for UIViewControllers a bit, because the wording
was a bit confusing for some people.

fix(apple): UIViewController wording

---

src/includes/performance/create-transaction-bound-to-scope/apple.mdx
src/platforms/common/performance/instrumentation/custom-instrumentation.mdx

Add Create transaction bound to scope as Java already has it because the Apple SDK
supports the bound to scope feature.

feat(apple): Transaction bound to scope

---

src/platforms/node/guides/serverless-cloud/index.mdx
src/wizard/node/serverlesscloud.md

Adds a Sentry Guide for [Serverless Cloud](https://www.serverless.com/cloud) ([docs](https://www.serverless.com/cloud/docs)).
Serverless Cloud's API functionality is based on ExpressJS, and allows us to use many of the same concepts (with a few small tweaks).
I haven't tested out any of the advanced performance monitoring stuff yet, so I haven't touched that part of the guide yet.

add Serverless Cloud base guide

---

src/includes/sourcemaps/generate/javascript.mdx
src/platforms/javascript/common/sourcemaps/generating.mdx

This page implies that the Sentry plugin generates the sourcemaps and upload them as well
and right now this is not the case.
We need to denote that it is up to the user to generate the sourcemaps and then Sentry will just take care of uploading it.

Denote that the Sentry plugin doesn't generate SM

---

src/docs/product/sentry-basics/dsn-explainer.mdx

I'm new to Sentry and these docs didn't help me find the DSN for my app (`Settings > Projects > Client Keys (DSN)` had nothing for me - see screenshot below).
I'm sure this could be worded better (and/or link to the appropriate spot), but I at least wanted to start the discussion.

Docs change to make it easier for new users to find their DSN

---

src/components/layout.tsx

#4915
My guess is that the `<Sidebar />` subtree is incorrectly reused during reconciliation on client-side (perhaps because JSX composition is same). I don't know exactly why.
[src/components/layout.tsx](https://github.com/getsentry/sentry-docs/blob/ad0cd9a3d12cbcee1faffe83c730bfc030abe9ae/src/components/layout.tsx#L46):
```jsx
<div className="text-white p-3">
{sidebar ? sidebar : <Sidebar />}
</div>
```
Most likely my fix is not optimal. As far as I know it will be lazily evaluated when used as default function parameter value.

Fix sidebar reconciliation issue

---

src/components/layout.tsx

Reverts getsentry/sentry-docs#4918
sidebar is entirely missing here: https://docs.sentry.io/product/issues/

Revert "Fix sidebar reconciliation issue"

---

src/platforms/apple/common/performance/instrumentation/automatic-instrumentation.mdx

Mention that the class name of the UIViewController must contain
ViewController.

fix(apple): Mention class name for APM

---

src/wizard/apple/ios.md

Mention the experimental file I/O and Core data auto instrumentation in
the wizard to get more feedback. Don't mention these for macos on
purpose because most APM features don't work there yet.

feat(apple): Add beta APM features to wizard

---

src/api/ratelimits.mdx

Update the rate limit documentation to include the concurrent rate limiter headers.

ref(rate limits): Add concurrent headers

---

src/docs/product/accounts/pricing.mdx

This pull request prepares the documentation surrounding on-demand budgets for GA roll out.
This entails updating the note introduced in https://github.com/getsentry/sentry-docs/pull/4808
GA for on-demand budgets is expected to begin on Monday, April 18 2022.

chore(billing): Prepare on-demand budget for GA to all performance plans

---

src/platforms/common/configuration/options.mdx

Clarifies that BeforeSend hook (and others in general) are run on the same thread where the event (error) happens. https://github.com/getsentry/sentry-unity/issues/471#issuecomment-1087598702
----

feat(unity): add thread-safety note to Hooks

---

src/platforms/common/configuration/options.mdx

Release is a reserved keyword on
Cocoa and instead, the option
is called releaseName.
----

fix(apple): release option

---

src/platforms/unity/migration.mdx

https://github.com/getsentry/sentry-unity/pull/657 will bring WebGL support to the Unity SDK so we no longer need to refer users to the Sentry Lite SDK on the migration page.

fix(unity): Removed WebGL from migration page

---

src/includes/getting-started-install/java.servlet.mdx
src/includes/getting-started-next-steps/java.servlet.mdx

Document that `sentry-servlet-jakarta` exists as of `6.0.0-alpha.6` (https://github.com/getsentry/sentry-java/pull/1987)

Mention sentry-servlet-jakarta

---

src/platforms/android/migration.mdx
src/platforms/java/migration.mdx

https://github.com/getsentry/sentry-java/releases
TODO:
* Remove notes about min. version Gson and deprecated features from docs once this is GA.

Migration docs for Android and Java v6

---

src/platforms/common/configuration/options.mdx

Since Unity "inherits" from the .NET it has to be specifically excluded here to avoid duplication.

fix(unity): Duplicate Environment

---

.github/ISSUE_TEMPLATE/config.yml

see: https://github.blog/changelog/2022-04-25-git-io-deprecation/
Committed via https://github.com/asottile/all-repos

fix: replace git.io links with redirect targets

---

src/platforms/react-native/troubleshooting.mdx

Relates to https://github.com/getsentry/sentry-react-native/issues/1937

Document mismatched line numbers on react native ram bundles

---

src/platforms/android/migration.mdx
src/platforms/dart/migration.mdx
src/platforms/flutter/migration.mdx
src/platforms/java/migration.mdx

Depends on https://github.com/getsentry/sentry-java/issues/2005

Document migration for sendclientreports

---

src/docs/product/cli/installation.mdx
src/gatsby/config.ts

ref: https://github.com/getsentry/sentry-cli/pull/1225

docs(cli): Add version specifier to get-cli script

---

src/docs/product/relay/index.mdx

Fixes broken platform redirect from Relay docs to platform before-send hooks docs

fix broken redirect link from relay docs

---

src/docs/product/integrations/integration-platform/webhooks.mdx

This example was missing a comma, this missing comma caused the JSON to be invalid

Added missing comma to webhook issue alert example

---

src/includes/getting-started-install/javascript.mdx
src/platforms/javascript/common/troubleshooting/index.mdx

This PR adds two links to the JS SDK repo's `MIGRATION.md` file which contains information on breaking changes and instructions how to update to the latest version of Sentry. 
Currently, the URLs link to the `7.x` version of the migration guide to include v7 migration instructions for early adopters of v7 beta versions. This means we'll have to adjust the URLs as soon as v7 is released.
Currently, there are two links, one in the "Getting Started" (which arguably many people won't look up when updating but IMO it doesn't hurt to have it there either) and one in the "Troubleshooting" section.
ref: https://getsentry.atlassian.net/browse/WEB-807

feat(javascript): Link to Github `MIGRATION.md` file from docs

---

src/docs/product/integrations/debugging/rookout/index.mdx
src/docs/product/integrations/deployment/vercel/index.mdx
src/docs/product/integrations/feature-flag/split/index.mdx
src/docs/product/integrations/issue-tracking/clickup/index.mdx
src/docs/product/integrations/issue-tracking/jira/index.mdx
src/docs/product/integrations/issue-tracking/shortcut/index.mdx
src/docs/product/integrations/notification-incidents/amixr/index.mdx
src/docs/product/integrations/notification-incidents/pagerduty/index.mdx
src/docs/product/integrations/notification-incidents/slack/index.mdx
src/docs/product/integrations/notification-incidents/spikesh/index.mdx
src/docs/product/integrations/source-code-mgmt/azure-devops/index.mdx
src/docs/product/integrations/source-code-mgmt/bitbucket/index.mdx
src/docs/product/integrations/source-code-mgmt/github/index.mdx
src/docs/product/integrations/source-code-mgmt/gitlab/index.mdx

Remove the sentence "This integration needs to set up only once per organization, then it is available for _all_ projects." from our first party integration docs. This is an artifact of differentiating between plugins and first party integrations, but since first party integrations (and partner integrations) are the majority and the path forward, this sentence doesn't need to be here.

ref(integrations): Remove indirect reference to plugin behavior

---

src/docs/product/sentry-basics/search/index.mdx

The docs currently do not mention that wildcards are not allowed when you use
the multi value search. As is, it implies that wildcards do work, which is not
the case.

fix(search): Mention wildcards are not allowed with multi value search

---

src/docs/product/integrations/issue-tracking/index.mdx

Adds link to Height integration page from Issue Tracking index page

add height link from issue tracking page

---

src/includes/getting-started-verify/python.django.mdx
src/includes/getting-started-verify/python.flask.mdx

Fixes wording of logging bullet point in the Verify section of these pages:
- https://docs.sentry.io/platforms/python/guides/django/#verify 
- https://docs.sentry.io/platforms/python/guides/django/#verify

fix wording of logging bullet point

---

src/platforms/unity/migration.mdx

Documentation for dropping the support saving the options as Json in https://github.com/getsentry/sentry-unity/pull/709

feat(unity): Added migration path from 0.3.0

---

src/includes/debug-symbols-apple/_default.mdx

- Change Alert level from Note to info to make the content more apparent. Customers may miss this content when being redirected from the app like so:
- Clarify App Store Connect behaviour for Team subscription plans

clarify team plan behaviour for app-store-connect

---

src/gatsby/onPostBuild.ts
src/wizard/javascript/performance-onboarding/javascript/1.install.md
src/wizard/javascript/performance-onboarding/javascript/2.configure.md
src/wizard/javascript/performance-onboarding/javascript/3.verify.md
src/wizard/javascript/performance-onboarding/react/1.install.md
src/wizard/javascript/performance-onboarding/react/2.configure.md
src/wizard/javascript/performance-onboarding/react/3.verify.md

This pull request extends the wizard onboarding documentation generation such that we generate Performance onboarding documentation content as sub-steps.
We aim to provide Performance onboarding content for JavaScript and React projects. They'll be shown in the product like this:
-----
Related to https://github.com/getsentry/sentry-docs/issues/3226
I intentionally did not provide any meta-documentation for how to write and contribute content to the Performance onboarding checklist at @imatwawana 's wishes; since we're only providing content for JavaScript and React platforms in the short-term to validate this feature.

feat(perf): Update onPostBuild step to generate performance on-boarding docs

---

src/platforms/common/enriching-events/context.mdx

I only have a one character fix to suggest.

SDKs typo fix

---

src/templates/apiPage.tsx

- This changes `array` to also include its subtype
- eg. instead of just `array` it'll now say `array(string)`

feat(apiDocs): Add api type to params too

---

src/components/banner.tsx

updated the banner to our next workshop

updated banner

---

src/docs/product/accounts/pricing.mdx

This PR syncs with https://github.com/getsentry/getsentry/pull/7548
This updates the note on the availability of the split on-demand budget on performance plans.

chore(billing): GA on-demand budget for all performance plans

---

src/platforms/javascript/common/configuration/tree-shaking/index.mdx

Documents usage of additional tree shaking flag added in https://github.com/getsentry/sentry-javascript/pull/5166
Ref: https://getsentry.atlassian.net/browse/WEB-713

[JS v7] **do not merge**: Add instructions to tree shake tracing code in JS SDK

---

src/includes/enriching-events/add-attachment/javascript.mdx

Adds docs for the new attachment API in v7 of the JavaScript SDKs.
Needs adding to https://github.com/getsentry/sentry-docs/milestone/2

[JS v7] **do not merge**: Add docs for new attachments API

---

src/platforms/javascript/guides/react/configuration/integrations/react-router.mdx

Adds a summary and usage example for the new React Router v6 instrumentation.
https://github.com/getsentry/sentry-javascript/pull/5042

[JS v7] **do not merge** Add React Router v6 instrumentation docs.

---

src/platforms/node/guides/aws-lambda/index.mdx

In https://github.com/getsentry/sentry-javascript/pull/5090 we removed the `ignoreSentryErrors` from the AWS Lambda JS SDK. In this PR we're removing references to it.
Ref: https://getsentry.atlassian.net/browse/WEB-918

[JS v7] **do not merge** Remove `ignoreSentryErrors` section in JS docs

---

src/includes/configuration/extra-error-data/javascript.mdx

JavaScript SDK: Updates `ExtraErrorData` `depth` option description to not mention a workaround for the global `normalizeDepth` option.
Relates to https://github.com/getsentry/sentry-javascript/pull/5053 which gets rid of that workaround.
Ref: https://getsentry.atlassian.net/browse/WEB-600

[JS v7] **do not merge**: Update `ExtraErrorData` depth description

---

src/platforms/javascript/common/install/cdn.mdx

This PR documents updates to our CDN bundle naming scheme - making ES6 the new default. Updates were made here: https://github.com/getsentry/sentry-javascript/pull/4958
Ref: https://getsentry.atlassian.net/browse/WEB-862
TODO before merging:
**DO NOT MERGE: Only merge this branch after the Sentry JavaScript SDK version 7 has been published.**

[JS v7] **do not merge** Adjust JS CDN bundle page to reflect ES5/ES6 naming changes

---

src/includes/getting-started-install/javascript.mdx
src/platforms/javascript/common/troubleshooting/index.mdx

This small PR changes the URLs of two links to the JS SDK migration guide which previously linked to the `7.x` branch version of the migration guide. It now links to master since we merged the `7.x` branch

ref(js): change migration guide URLs from v7 branch to master

---

src/includes/enriching-events/breadcrumbs/breadcrumbs-example/javascript.mdx
src/includes/set-level/javascript.mdx
src/platforms/common/enriching-events/breadcrumbs.mdx
src/platforms/javascript/common/troubleshooting/index.mdx

In https://github.com/getsentry/sentry-javascript/pull/4926, we deprecated the `Severity`. This PR replaces all occurrences of that enum with their now recommended string value counterpart.
Ref: https://getsentry.atlassian.net/browse/WEB-849
**DO NOT MERGE: Only merge this branch after the Sentry JavaScript SDK version 7 has been published.**

[JS v7] **do not merge** ref(javascript): Replace deprecated severity enums with string literals

---

src/docs/product/integrations/integration-platform/webhooks/errors.mdx
src/docs/product/integrations/integration-platform/webhooks/issue-alerts.mdx
src/platforms/javascript/common/configuration/integrations/default.mdx

This PR adjusts docs after renaming the `UserAgent` integration in the Sentry JS SDK to `HttpContext`.  
ref: https://getsentry.atlassian.net/browse/WEB-270

[JS v7] **do not merge**: Adust docs after renaming `UserAgent` integration to `HttpContext`

---

src/platforms/node/common/performance/database/auto-instrument.mdx
src/platforms/node/common/performance/database/index.mdx
src/platforms/node/common/performance/database/opt-in.mdx

- Added a simple example about the use of new Prisma integration. (https://github.com/getsentry/sentry-javascript/pull/4931)

[JS v7] Add Prisma ORM Integration Docs.

---

src/includes/capture-error/native.mdx

@Swatinem and @jan-auer: this is my suggested change to the documentation after our conversation on Tuesday. It replaces the low-level calls with all currently available high-level APIs. It also shows how to add a stack trace to the exception instead of only referring to it.
Instead of having two, we can provide only one example with the stack trace (and comment on its optionality).

ref(native): capture-error using high-level API.

---

src/platforms/android/common/performance/instrumentation/automatic-instrumentation.mdx

The Kotlin code sample for user interaction transactions had a typo.
This is fixed now by aligning the code sample with Java.

fix(android): Typo for UI transactions

---

src/platforms/javascript/common/performance/instrumentation/automatic-instrumentation.mdx

This small PR is a follow-up of #5061 which adds the instructions on how to deal with the new `baggage` header in CORS settings. The `baggage` header was introduced in v7 of the JS SDK (see original PR for more info)
ref: https://getsentry.atlassian.net/browse/WEB-941

ref(js): Add baggage information to automatic instrumentation page

---

src/platforms/apple/common/performance/instrumentation/automatic-instrumentation.mdx

Add docs similar to user interaction instrumentation on Android.
As the implementations don't match exactly we can't create reusable docs.

feat(apple): User interaction instrumentation

---

src/includes/performance/retrieve-transaction/dotnet.mdx

Clarify the behaviour of the GetSpan method.
GetSpan will return an ongoing Transaction or Span that is on the Scope. This is not clear from the .NET docs.
Related to ZenDesk ticket #65770

dotnet performance clarify GetSpan

---

src/docs/product/cli/releases.mdx
src/docs/product/issues/states-triage/index.mdx
src/docs/product/releases/setup/manual-setup-releases.mdx
src/docs/product/releases/suspect-commits/index.mdx

Retitles and restructures Enable Suspect Commits page
Removes finalizing releases content from suspect this page
Moves intro text for code snippet to manual setup page

improve enable suspect commits content

---

src/platforms/android/common/performance/instrumentation/automatic-instrumentation.mdx

Reduce the complexity of the code sample for manually adding spans
to user interaction transactions.

ref(android): Simplify UI transaction code sample

---

src/includes/getting-started-primer/unity.mdx
src/platforms/unity/native-support/index.mdx

Because we've got even more supported platforms I split the docs into `Mobile` and `Desktop` to highlight differences/similarities.

feat(unity): Added additional platforms to native support

---

src/includes/getting-started-install/javascript.capacitor.mdx
src/platforms/javascript/guides/capacitor/troubleshooting.mdx
src/wizard/capacitor/index.md
src/wizard/cordova/index.md
src/wizard/ionic/index.md

- Remove initialization for Capacitor 3 on Ionic/Capacitor for Android.
- Fixed warnings from Double Quoted strings.
- Add troubleshooting if users forgot to add the SentryCapacitor Plugin.
This fixes the issue found here https://github.com/getsentry/sentry-capacitor/issues/174 and https://github.com/getsentry/sentry-docs/issues/5084

Refactor Ionic/Capacitor/Cordova Wizards

---

src/docs/product/accounts/quotas/index.mdx

Inbound data filters are applied to all events, including transactions.
See [envelope
filtering](https://github.com/getsentry/relay/blob/7c6b308bbf04e63e8e0b456489da1ddc320e2e6a/relay-server/src/actors/envelopes.rs#L1603)
and the [should_filter
check](https://github.com/getsentry/relay/blob/7c6b308bbf04e63e8e0b456489da1ddc320e2e6a/relay-filter/src/lib.rs#L38-L60) in relay.

fix(quotas): Clarify filters application scope

---

scripts/bump-version.sh

- this is so the script can be run on MacOS where the date function is
slightly different

feat(api): Update the bump script since CI doesn't run it

---

src/platforms/javascript/guides/angular/angular1.mdx

Adjusts AngularJS 1.x SDK documentation because we dropped support for it in version 7 of the JS SDK.
Fixes https://github.com/getsentry/sentry-javascript/issues/5216

Add discontinuation of AngularJS 1.x

---

src/platforms/common/configuration/options.mdx
src/platforms/flutter/native-init.mdx

Add documentation for option `autoInitializeNativeSdk` for flutter/dart sdk.
Merge after `6.6.0-alpha.3` gets released.

feat(docs): Document flutter autoInitializeNativeSdk

---

src/docs/product/accounts/quotas/index.mdx
src/docs/product/accounts/quotas/manage-transaction-quota.mdx

Removes beforeSend from transaction quota content
Adds inbound data filters to transaction quota content
Fixes a reference to inbound filters on Quotas index page

fix transaction quota management content

---

src/components/banner.tsx

hid banner

---

src/includes/enriching-events/add-attachment/java.mdx
src/platforms/common/enriching-events/attachments/index.mdx

Add some examples on how to add attachments via `Hint`

Document how to manipulate attachments via hints

---

src/includes/getting-started-primer/note/apple.mdx

Clarify that signal handlers work for macOS and manual setup
is required for uncaught exceptions.

fix(apple): Signal handlers for macOS

---

src/includes/configuration/auto-session-tracking/ruby.mdx
src/includes/configuration/before-send-fingerprint/ruby.mdx
src/includes/configuration/before-send-hint/ruby.mdx
src/includes/configuration/before-send/ruby.mdx
src/includes/configuration/before-send/ruby.rails.mdx
src/includes/enriching-events/breadcrumbs/before-breadcrumb/ruby.mdx
src/includes/getting-started-config/ruby.mdx
src/includes/getting-started-config/ruby.rack.mdx
src/includes/getting-started-config/ruby.rails.mdx
src/includes/performance/configure-sample-rate/ruby.mdx
src/includes/performance/traces-sample-rate/ruby.mdx
src/includes/performance/traces-sampler-as-filter/ruby.mdx
src/includes/performance/traces-sampler-as-sampler/ruby.mdx
src/includes/set-environment/ruby.mdx
src/includes/set-fingerprint/database-connection/ruby.mdx
src/includes/set-fingerprint/rpc/ruby.mdx
src/includes/set-release/ruby.mdx
src/wizard/ruby/rails.md

Unify the use of Ruby code snippets. Basically just adding the ellipsis to show that other parameters need to be added.

Unify Ruby code snippets.

---

src/includes/configuration/before-send-hint/go.mdx
src/includes/configuration/before-send/go.mdx
src/includes/configuration/sample-rate/go.mdx
src/includes/enriching-events/breadcrumbs/before-breadcrumb/go.mdx
src/includes/getting-started-config/go.mdx
src/includes/performance/always-inherit-sampling-decision/go.mdx
src/includes/performance/configure-sample-rate/go.mdx
src/includes/performance/custom-sampling-context/go.mdx
src/includes/performance/traces-sample-rate/go.mdx
src/includes/set-environment/go.mdx
src/includes/set-release/go.mdx
src/platforms/go/common/configuration/options.mdx
src/platforms/go/common/migration.mdx
src/platforms/go/guides/echo/index.mdx
src/platforms/go/guides/fasthttp/index.mdx
src/platforms/go/guides/gin/index.mdx
src/platforms/go/guides/http/index.mdx
src/platforms/go/guides/iris/index.mdx
src/platforms/go/guides/martini/index.mdx
src/platforms/go/guides/negroni/index.mdx
src/wizard/go/index.md

Added `TracesSampleRate` to Go code snippets to enable performance by default.

Add performance to Go code snippets

---

src/includes/getting-started-install/android.mdx
src/includes/getting-started-install/java.jul.mdx
src/includes/getting-started-install/java.log4j2.mdx
src/includes/getting-started-install/java.logback.mdx
src/includes/getting-started-install/java.mdx
src/includes/getting-started-install/java.servlet.mdx
src/includes/getting-started-install/java.spring-boot.mdx
src/includes/getting-started-install/java.spring.mdx

Gson dependency has been vendored in `6.0.0` so we no longer need the note.

Remove Gson dependency note

---

src/docs/product/alerts/create-alerts/index.mdx

This removes the EA label from duplicate alerts for GA.

feat(alerts): Remove EA label from duplicate alerts

---

src/platforms/dotnet/guides/maui/index.mdx

Add a note about a common error users may get when installing the new .NET MAUI package.

Add installation troubleshooting note for MAUI

---

scripts/bump-api-schema-sha.sh
scripts/bump-version.sh

Overloading the `bump-version.sh` Craft [hook](https://github.com/getsentry/craft#pre-release-command) to also be used from localhost during [more-frequent API doc updates](https://develop.sentry.dev/api/public/#build-process) added some [inter-environment friction](https://github.com/getsentry/sentry-docs/pull/5115) that resulted in [a CalVer release failure](https://github.com/getsentry/self-hosted/issues/1515#issuecomment-1156787127).
Seems great to update the API docs more frequently than once a month, and that means it would be redundant to also do this during monthly CalVer release, so let's move that to a separate script.

Move API SHA bump to its own script

---

src/includes/getting-started-install/react-native.mdx

Remove the period at the end of the heading. Having a period only for one heading looks weird.

fix(rn): Heading on getting started

---

src/docs/product/alerts/create-alerts/issue-alert-config.mdx

Remove the EA mention of issue owner Slack alerts and make it a normal GA thing. This has been out for a while but it was missed when we GA'd the feature 😬

ref(alerts): Mention issue owner alert types

---

src/docs/product/integrations/issue-tracking/height/index.mdx
src/docs/product/integrations/notification-incidents/threads/index.mdx

Add a redirect so that when users click "View Documentation" in the integration overview page, it actually goes to the page ☠️

fix(integrations): Add redirect from product page

---

src/platforms/react-native/manual-setup/hermes.mdx

This PR hopes to clarify the sentence 'You will upload the **original** bundle (output from Step 1) and the **composed** source map (output from Step 3)' from the docs. It took me a while to figure out what was meant here, because Step 1 has _two_ outputs, the bundle and the packager source map. 
So I clarified in step one that there's two outputs, and clarified which of those outputs need to be uploaded. …

docs: clarifying Hermes artifacts

---

src/includes/enriching-events/scopes/scope-synchronization/flutter.mdx
src/platforms/common/configuration/options.mdx
src/platforms/common/enriching-events/scopes.mdx
src/platforms/dart/migration.mdx

Document user and attachments deprecations of `Scope`.

Dart: Document Scope Deprecations

---

src/platforms/apple/common/performance/instrumentation/automatic-instrumentation.mdx

With https://github.com/getsentry/sentry-cocoa/issues/1849,
we stop reporting pre-warm app starts. Add a note to the docs
to avoid confusion.
Only merge after https://github.com/getsentry/sentry-cocoa/issues/1849 is released.

fix(apple): Note on pre warmed app starts

---

src/docs/clients/react-native/sourcemaps.mdx
src/platforms/react-native/sourcemaps.mdx

Remove explicit rewrite flags from sentry cli RN

---

src/platforms/react-native/manual-setup/ram-bundles.mdx

Specify bundle names for RAM bundles react native

---

src/platforms/node/common/performance/database/index.mdx
src/platforms/node/common/performance/database/opt-in.mdx

Ref: https://github.com/getsentry/sentry-javascript/pull/3953

Add Node Apollo and GraphQL Integrations

---

src/platforms/common/configuration/releases.mdx

Removed this version information from the Releases Set Up page in product and moved it here since this is when you need to know about version naming behavior (during the actual SDK configuration)

adding version info

---

src/docs/product/releases/index.mdx

- Moves hero image further up the page
- Rearranges headings below the image
- Adds generic wording for code mapping files
- Adds Learn More heading
- Points to Set Up page instead of SDK pages for setup content
**Merge after [PR 5108](https://github.com/getsentry/sentry-docs/pull/5108)**

restructure releases page

---

src/platforms/node/common/performance/database/opt-in.mdx

That import is unnecessary and is a leftover from the Prisma demo app.

Remove extra import from Prisma example.

---

.github/workflows/bump-api-schema-sha.yml

Could've caught this [the other day](https://github.com/getsentry/develop/pull/607), but had to hear it from Support. ¯\\\_(ツ)\_/¯
> When you use the repository's `GITHUB_TOKEN` to perform tasks, events triggered by the `GITHUB_TOKEN` will not create a new workflow run. This prevents you from accidentally creating recursive workflow runs. For example, if a workflow run pushes code using the repository's `GITHUB_TOKEN`, a new workflow will not run even when the repository contains a workflow configured to run when push events occur.
https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow

Use elevated token to trigger CI from automated PR

---

src/includes/debug-symbols-apple/_default.mdx

Some developers may want errors from `sentry-cli` to break their builds, like if it's part of a CI deployment that shouldn't succeed, lest they encounter sentry issues with unsymbolicated symbols. This gives an example of each as copyable snippets, with a quick explainer on the difference.

docs: add alternative snippet that blocks on sentry-cli errors

---

src/platforms/react-native/migration.mdx

https://github.com/getsentry/sentry-react-native/releases/tag/4.0.0

Migration page for RN v4

---

src/docs/product/integrations/integration-platform/ui-components/formfield.mdx

Adds a bit more description to the 'options' field requirements

chore(docs): More description for options details

---

src/platforms/php/guides/laravel/index.mdx
src/wizard/php/index.md
src/wizard/php/laravel.md
src/wizard/php/symfony.md

The current PHP wizard pages got a little out of sync, this brings them up to speed to have more similar information tot he current getting started guides on docs.sentry.io.

Sync wizard pages with current docs

---

src/platforms/apple/common/performance/instrumentation/automatic-instrumentation.mdx

Clarify when the Cocoa SDK adds the click suffix
to UI interactions transactions and when not.

fix(apple): Clarify UI interaction operations

---

src/platforms/android/configuration/integrations/fragment.mdx
src/platforms/android/configuration/integrations/okhttp.mdx
src/platforms/android/configuration/integrations/timber.mdx

Was an oversight when bumping it on the Gradle docs

chore(android): Switch to SAGP stable version in integrations docs

---

src/platforms/javascript/common/configuration/tree-shaking/index.mdx

The `__SENTRY_TRACING__` tree-shaking flag in the JS SDK is supposed to be used in combination with packages like the Next.js SDK where `@sentry/tracing` usage. It shouldn't be used when directly using methods from the `@sentry/tracing` package, like for example `Sentry.startTransaction()`.
To make this a little bit more explicit and to avoid confusion (like reported in https://github.com/getsentry/sentry-javascript/issues/5320) we're documenting this with this PR.

Document implications of tree shaking `__SENTRY_TRACING__`

---

src/platforms/common/configuration/options.mdx

The send_attempts option was deprecated and default changed to 0 in https://github.com/getsentry/sentry-php/pull/1312

Update send_attempts option

---

src/docs/product/releases/suspect-commits/index.mdx

Updates language around how sentry-CLI associates commits when you don't have a repo-based integration
I've started with edits based on the conversation that happened on PR 5108, but I'm not sure if I've got this at all right.
Original conversation on PR 5108:
https://github.com/getsentry/sentry-docs/pull/5108/files#r893972887 
https://github.com/getsentry/sentry-docs/pull/5108/files#r896895816

clarify how sentry-cli associates commits

---

src/platforms/common/enriching-events/attachments/index.mdx

This clarifies limits for upload-like endpoints that are already in place (20 MB compressed, 100 MB uncompressed), similar to ones already described in:
https://develop.sentry.dev/sdk/envelopes/#size-limits
https://docs.sentry.io/platforms/native/guides/minidumps/#size-limits

Clarify attachments upload limits, taking compression into account

---

src/includes/enriching-events/set-user/dart.mdx
src/includes/enriching-events/unset-user/dart.mdx

Current dart snippet for setting user in Sentry scope is deprecated with the latest version of Sentry. Snippet has been updated to follow the latest version of Sentry

Modify user setup snippet as current snippet represent deprecated method

---

src/docs/product/integrations/integration-platform/ui-components/alert-rule-action.mdx

Fix the example where it says "url" instead of "uri". Double checked this on the [source of truth](https://github.com/getsentry/integration-platform-example/blob/main/integration-schema.json#L79-L82) 😉.

fix(sentry apps): Fix url -> uri typo

---

src/includes/debug-symbols-apple/_default.mdx

Mention everywhere in the dSYMs docs page for Apple
how to get an auth token.
@kevinrenskers, got didn't know where to get an auth token when adding the Cocoa SDK to a project.

fix(apple): Mention where to get an auth token

---

src/includes/getting-started-primer/apple.macos.mdx

See: https://github.com/getsentry/sentry-cocoa/issues/1052#issuecomment-1129736553

apple: remove mention of experimental feature

---

src/platforms/common/enriching-events/attachments/index.mdx

For now the Electron SDK does not support the new JS attachments API. This will change soon

fix(electron): Remove attachment docs

---

src/platforms/common/enriching-events/screenshots.mdx

Enable the screenshot doc for Unity

enable screenshot doc for Unity

---

src/platforms/dotnet/guides/aspnetcore/index.mdx

Add docs on how to use tunneling from the sentry aspnetcore package
related to https://github.com/getsentry/sentry-dotnet/pull/1645
Merge after the sentry-dotnet PR

Dotnet tunnel docs

---

src/platforms/javascript/common/troubleshooting/index.mdx

The docs used the old term for a Chrome DevTools feature: `framework blackboxing` which was changed to `Framework Ignore List`.
The URL to the `blackboxing` docs was broken and led to the main page of the Chrome Developers Docs. I searched for a Docs article about `Framework Ignore List` and only found a stub that seemed to focus more on ignoring Chrome extension scripts. I used this URL as it's the closest to the original `blackboxing` URL. I tried this fix and it worked.
I hope this makes sense. I wish there was a more thorough article about this Chrome feature. If any changes are needed, please let me know!
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order …

Update Chrome docs broken link + feature name

---

src/includes/enriching-events/attach-screenshots/dotnet.xamarin.mdx

This adds the missing configuration Sample for screenshots on Sentry Xamarin.

Add snippet for Xamarin Screenshot

---

src/platforms/common/configuration/options.mdx

ios screenshots for crashes

---

src/platforms/common/configuration/sampling.mdx

The link to the "Connecting Services" page was for the JavaScript docs, not the Python docs.

Fix wrong URL in link for sampling.mdx

---

src/includes/performance/traces-sampler-as-sampler/dotnet.aspnetcore.mdx

Aims to fix the following issue: https://github.com/getsentry/sentry-docs/issues/5124
Sampling context was retrieving the wrong key on the Documentation.
Also, only ASP.NET Core has `TryGetHttpPath` so for other platforms I only fixed the correct key where in ASP.NET Core I used the appropriate extension.

(.NET): Update TracerSampling Key reference

---

src/platforms/go/common/serverless.mdx

Fixing a spelling error in go serverless document.

fix servers spelling error

---

src/platforms/apple/common/configuration/out-of-memory.mdx
src/platforms/apple/common/performance/instrumentation/automatic-instrumentation.mdx
src/platforms/apple/troubleshooting.mdx

Move notes on upgrading to an SDK version to fix critical bugs
to a newly added troubleshooting page.

feat(apple): Add troubleshooting page

---

src/includes/getting-started-install/native.mdx
src/includes/getting-started-install/native.qt.mdx

This fixes https://github.com/getsentry/sentry-docs/issues/5274. It seems the docs got a bit out of sync with the repository documentation. I took the liberty of cleaning up the required build steps as follows:
We can remove the CMAKE_BUILD_TYPE entirely for the purpose of this documentation because it uses our default build type. In addition to that, it would have to be passed as `-DCMAKE_BUILD_TYPE=RelWithDebInfo` and not via `--config` at the build-generator stage. This leads to an error in CMake [starting with version 3.20](https://cmake.org/cmake/help/latest/release/3.20.html#other-changes).
In the actual compile/build stage it could be passed via `--config` for build-generators that provide all build-types under a single hierarchy (like Visual Studio solutions). This is also not …

fix(native): clean up install/build instructions

---

src/includes/capture-error/javascript.remix.mdx
src/includes/getting-started-config/javascript.remix.mdx
src/includes/getting-started-install/javascript.remix.mdx
src/includes/getting-started-primer/javascript.remix.mdx
src/includes/getting-started-verify/javascript.remix.mdx
src/includes/sourcemaps/generate/javascript.remix.mdx
src/includes/sourcemaps/overview/javascript.remix.mdx
src/includes/sourcemaps/upload/primer/javascript.remix.mdx
src/platforms/javascript/common/sourcemaps/best-practices.mdx
src/platforms/javascript/common/sourcemaps/uploading/webpack.mdx
src/platforms/javascript/guides/remix/config.yml

Adds documentation for Remix SDK
https://github.com/getsentry/sentry-javascript/tree/master/packages/remix

Add Remix SDK docs

---

src/docs/product/sentry-basics/tracing/distributed-tracing.mdx
src/platforms/common/data-management/sensitive-data/index.mdx

This PR adds a small warning in the product guide that transaction names can potentially contain sensitive data (i.e. unparameterized URLs). Furthermore, the PR adds a list item for transaction names in the "Scrubbing Sensitive Data" page).

ref(JS): Add warning for potentially sensitive data in transaction names

---

src/includes/performance/traces-sampler-as-sampler/dotnet.aspnetcore.mdx

The using on the ASP.NET Core doc is not used so I just removed it.

(.NET) Remove redundant using

---

package.json
src/gatsby/onPostBuild.ts
src/wizard/javascript/nextjs.md
yarn.lock

This adds a new frontmatter field, `wizard_setup`, that allows the author to specify simplified setup instructions. This will be used on the onboarding view to give simplified setup instructions.

Add sentry wizard setup instructions to sentry docs

---

package.json
src/gatsby/onPostBuild.ts
src/wizard/javascript/nextjs.md
src/wizard/javascript/nextjs_wizard.md
yarn.lock

The old approach didn't work because we'll have to manually add all plugins that we would like to use. We have too many.
Instead we can put this in a separate file and let gatsby treat it as any other file. This separate file in itself wouldn't be a valid wizard docs file, so we'll have to skip it during processing.

Proper markdown support for wizard quicksetup frontmatters

---

src/platforms/common/enriching-events/scopes.mdx

I might not be understanding this part of the docs, but I don't think this section applies to the way the Ruby library works?
(I also might not understand how this documentation format works. Can you nest a "PlatformSection" inside a "PlatformSection"?)

Hide warning for Ruby

---

src/includes/enriching-events/set-transaction-name/android.mdx
src/includes/enriching-events/set-transaction-name/dart.mdx
src/includes/enriching-events/set-transaction-name/dotnet.mdx
src/includes/enriching-events/set-transaction-name/flutter.mdx
src/includes/enriching-events/set-transaction-name/java.mdx
src/includes/enriching-events/set-transaction-name/native.mdx
src/includes/enriching-events/set-transaction-name/react-native.mdx
src/includes/enriching-events/set-transaction-name/unity.mdx
src/platforms/common/enriching-events/transaction-name.mdx

We'll need to add the code snippets for each new platform.
Apple might need to be dropped though

enriching events: set transaction name

---

src/platforms/python/guides/celery/index.mdx

* `worker_process_init` doesn't work because it's called after our [patches need to run](https://github.com/getsentry/sentry-python/issues/1512#issuecomment-1195511889) 
* fixes https://github.com/getsentry/sentry-python/issues/1512

fix(python): Clarify which Celery signals work and explain Celery + Django setup

---

src/platforms/javascript/common/troubleshooting/index.mdx

Update instructions for client constructor in docs.
Fixes https://github.com/getsentry/sentry-javascript/issues/5422
Fixes https://github.com/getsentry/sentry-javascript/issues/5298

feat(js): Update JS troubleshooting for new v7 client

---

package.json
src/platforms/python/guides/fastapi/index.mdx
src/platforms/python/guides/starlette/index.mdx
src/wizard/python/fastapi.md
src/wizard/python/starlette.md
yarn.lock

Starlette and FastAPI are two new Python frameworks we support. They are both heavily depending on each other, so it makes sense to add documentation for both at the same time. 
Refs getsentry/sentry-python#1409

Docs for Starlette and FastAPI integration.

---

src/wizard/unity/index.md

Relies on https://github.com/getsentry/sentry-docs/pull/5337 for the IL2CPP link to work.

feat(unity): Updated wizard

---

src/wizard/unity/index.md

Moved the note about the experimental feature to configuration.

fix(unity): Wizard IL2CPP note

---

src/wizard/javascript/remix.md

ref: https://github.com/getsentry/sentry-javascript/issues/4894

Add onboarding wizard for Remix SDK

---

src/includes/configuration/before-send/native.mdx

After merging https://github.com/getsentry/sentry-native/pull/734 we are ready to release version 0.4.19 of `sentry-native`. The last required step is to add documentation for this new feature.
@Swatinem please review. Thx!

feat(native): Provide documentation for on_crash

---

src/docs/clients/javascript/integrations.mdx

Add legacy warning to integrations page, similar to the one here: https://docs.sentry.io/clients/javascript/

Add legacy warning to integrations page

---

src/includes/troubleshooting/older-browser-support/javascript.mdx
src/includes/troubleshooting/older-browser-support/javascript.nextjs.mdx
src/platforms/javascript/common/troubleshooting/index.mdx
src/platforms/javascript/guides/nextjs/configuration/build/index.mdx
src/platforms/javascript/guides/nextjs/manual-setup.mdx

In https://github.com/getsentry/sentry-javascript/pull/5472, a `transpileClientSDK` option was added to the nextjs SDK to force SDK code to be transpiled along with other app code, primarily for the use of folks wanting to use the SDK in older browsers without support for ES6 or ES6+ features like object spread. This documents that option by:
- Adding a section to the manual setup page (which is where other build-time options live)
- Adding a new 'Build Options' page redirecting people to the relevant section of of the manual setup page, for greater discoverability
- Adding a nextjs-specific include to a new legacy browser support section on the Troubleshooting page. (A generic include has also been added for the non-nextjs JS docs, detailing how to do manually what the added option …

feat(nextjs): Add `transpileClientSDK` option and build config page

---

src/includes/configuration/config-intro/unity.mdx

Updated the parts explaining how the SDKs get initialized and what limitations this imposes on mobile.

fix(unity): Initialization and programmatic configuration

---

src/includes/getting-started-primer/javascript.remix.mdx

Since https://github.com/getsentry/sentry-javascript/issues/4894 has been closed, let's move this into beta.

Update docs for Remix alpha -> beta

---

src/platforms/common/configuration/options.mdx

Fixes #5358. @Swatinem, @imatwawana, @souredoutlook pls have a look.

ref(native): environment default is `production`

---

src/docs/product/alerts/alert-types.mdx
src/docs/product/alerts/create-alerts/metric-alert-config.mdx

Based heavily on the wording from https://github.com/getsentry/sentry-docs/pull/5224
Update metric alert docs to explain how we switch between transaction vs metric based performance alerts.
**Do not merge** until [PR 5224](https://github.com/getsentry/sentry-docs/pull/5224) is merged).

Update docs to explain metric performance alerts

---

src/platforms/dotnet/guides/maui/index.mdx
src/wizard/dotnet/maui.md

Update the .NET MAUI package install to remove the version string and just use the latest pre-release.
We'll go back to using the version string when we are out of preview.

Update .NET MAUI

---

src/platforms/dotnet/guides/entityframework/index.mdx

EFCore is integrated through `Sentry` or `Sentry.DiagnosticSource`, not `Sentry.Extensions.Logging`.

Improve EF Core details

---

src/docs/product/issues/issue-owners/index.mdx

Add a mention of the maximum file size for codeowners with a suggestion on what to do if your file exceeds it. We get this question frequently.

ref(codeowners): Add file limit

---

src/platforms/java/guides/spring-boot/record-user.mdx

Java needs `new` to instantiate object. Small typo in docs.

Fix java typo in record-user

---

src/platforms/common/configuration/options.mdx

Adds documentation for the discussed `tracePropagationTargets` option. More context: [DACI](https://www.notion.so/sentry/DACI-Control-Sending-Trace-Data-63fd04ea885443ee99514c15a1e91499) (internal)
Related to changes in the JavaScript SDK: https://github.com/getsentry/sentry-javascript/pull/5521

Add trace-propagation-targets to unified API options

---

src/docs/product/integrations/integration-platform/ui-components/index.mdx

Update the error handling docs for the integration platform to reflect a change made in https://github.com/getsentry/sentry/pull/37454 and https://github.com/getsentry/sentry/pull/37325 which shows an issue link as disabled rather than not showing it at all.

fix(sentry apps): Update error handling docs

---

src/platforms/common/enriching-events/attachments/index.mdx

Essentially reverts #5261 since the SDK now supports attachments.

fix(electron): Re-enable attachment docs

---

src/platforms/javascript/guides/electron/index.mdx

Related to:
https://github.com/getsentry/sentry-electron/issues/524
https://github.com/getsentry/sentry-wizard/pull/183
Full native stack decoding is now supported by simply enabling the Electron symbol server in Sentry.

fix(electron): Uploading of debug symbols no longer required

---

src/platforms/javascript/guides/nextjs/manual-setup.mdx

This updates the nextjs manual setup docs to use the helper function for `_error.js` introduced in https://github.com/getsentry/sentry-javascript/pull/5259.

feat(nextjs): Use helper function in `_error.js` example

---

src/platforms/javascript/common/performance/instrumentation/automatic-instrumentation.mdx

This adds the new 'experiments' option for `BrowserTracing` with the on-by-default `enableLongTasks` flag.
Refs: https://github.com/getsentry/sentry-javascript/pull/5529

docs(sdk): Add long tasks experiment to docs

---

src/includes/enriching-events/set-transaction-name/android.mdx
src/includes/enriching-events/set-transaction-name/ruby.mdx
src/includes/getting-started-config/javascript.capacitor.mdx
src/platforms/javascript/guides/capacitor/ionic.mdx
src/wizard/unity/index.md

- Fix Kotlin Sample for transaction name.
- Add include to Ruby sample for transaction name.
- Populate the Ionic page so it's not too empty

Minor fixes to Sentry Docs

---

src/docs/product/accounts/quotas/index.mdx
src/docs/product/stats/index.mdx

Fixes references that conflate events and attachments
Replaces #5106 which has several merge conflicts due to significant changes to _Pricing_ and _Quota Management_ docs; replicates already approved changes

fix events and attachments references

---

src/platforms/php/guides/symfony/index.mdx

Just a little missing typo that I find will integrating the SentryTestController myself :)

SF Install : Missing extends AbstractController

---

src/includes/getting-started-verify/javascript.remix.mdx
src/includes/sourcemaps/overview/javascript.remix.mdx
src/includes/sourcemaps/upload/primer/javascript.remix.mdx
src/platforms/javascript/common/install/index.mdx
src/wizard/javascript/remix.md

This PR makes a few small improvements to our Remix SDK documentation and the onboarding wizard. While working on #5413 and #5415 I came across some things that IMO could be slightly improved. Furthermore, during the review of the two PRs a few additional things came up that we should also address in the Remix docs.
Specifically, this PR 
* disables the "Installation Methods" section in the left nav menu. (Doesn't make sense for Remix b/c the only installation method is NPM)
* Fixes a few broken links (which didn't work b/c of some formatting problems)
* repositions and adjusts a sentence regarding the SDK functionality "verification" (i.e. the section to send your first event)
* Adds a basic SDK functionality "verification" step to the onboarding wizard (for consistency with our other …

ref(remix): Improve Remix SDK docs and wizard

---

src/includes/capture-error/javascript.svelte.mdx
src/includes/getting-started-config/javascript.svelte.mdx
src/includes/getting-started-install/javascript.svelte.mdx
src/includes/getting-started-primer/javascript.svelte.mdx
src/includes/getting-started-verify/javascript.svelte.mdx
src/includes/sourcemaps/generate/javascript.svelte.mdx
src/includes/sourcemaps/overview/javascript.svelte.mdx
src/includes/sourcemaps/upload/primer/javascript.svelte.mdx
src/includes/troubleshooting/older-browser-support/javascript.mdx
src/platforms/javascript/common/install/index.mdx
src/platforms/javascript/guides/svelte/config.yml

This PR adds official documentation to the new `@sentry/svelte` JS SDK which is currently in aplha. It includes
* A disclaimer that this SDK is in alpha and subject to breaking changes
* Instructions for installing and using the SDK in Svelte projects
* Instruction for generating and uploading Sourcemaps in Svelte projects
ref: https://github.com/getsentry/sentry-javascript/issues/5573

feat: Add Svelte SDK docs

---

src/docs/product/relay/getting-started.mdx

Apparently the [`:z` option](https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label) is necessary for users of [SELinux](https://en.wikipedia.org/wiki/Security-Enhanced_Linux).
Fixes https://github.com/getsentry/sentry-docs/issues/5422

Add :z to volume mount in Relay example

---

src/docs/product/data-management-settings/scrubbing/server-side-scrubbing.mdx

This PR adds mentions about some limitations which data scrubbing  has in the breadcrumbs. 
Where the scrubbing only works for message and data.

feat: Add limitation about data scrubbing in breadcrumbs

---

src/includes/enriching-events/user-feedback/example-widget/ruby.rails.mdx
src/platforms/common/enriching-events/user-feedback.mdx

Adds information on integrating the JavaScript User Feedback SDK into a Rails app. It's modeled off the existing Python documentation.
It also serves as a way to document the env variable `sentry.error_event_id` which was added in https://github.com/getsentry/sentry-ruby/pull/1849 (CC: @st0012).
This has the unfortunate side-effect of populating the Ruby-only version of this page, when the Ruby SDK doesn't actually support user feedback. But there's no easy way to show this page for Rails and not Ruby. Python also has the same problem, so I don't think this should block merging.
I recently implemented the described behavior in our Rails app, so I thought I'd add a couple words to the documentation. Feedback is welcome.
Look, I get it. The entity doing business as "Sentry" was incorporated …

Add User Feedback section for Rails

---

src/platforms/common/enriching-events/context.mdx

I tried my best at cleaning up the "clearing scope" section. I have absolutely no clue what concept it was trying to convey. The documentation's description was just *so so* far off compared to what the SDK actually does.
Resolves https://github.com/getsentry/sentry-docs/issues/5441

Clarify Global scope for Node SDK

---

src/docs/product/cli/send-event.mdx

There's currently an empty space breaking the link.

Remove space to enable link

---

src/platforms/java/guides/spring-boot/record-user.mdx
src/platforms/java/guides/spring/advanced-usage.mdx

`io.sentry.core.protocol` was a long time ago renamed to `io.sentry.protocol`

Fix imported user on java samples

---

src/platforms/javascript/guides/nextjs/manual-setup.mdx

This expands the explanation of the `hideSourceMaps` option in `next.config.js`, and notes that it will default to `true` starting in version 8 of the SDK.
In conjunction with https://github.com/getsentry/sentry-javascript/pull/5649, https://github.com/getsentry/sentry-wizard/pull/188, and https://github.com/vercel/next.js/pull/40079, this is the first step in addressing the concerns raised in https://github.com/getsentry/sentry-javascript/issues/4489. See [here](https://github.com/getsentry/sentry-javascript/issues/4489#issuecomment-1231137629) for more details.

ref(nextjs): Add note about upcoming default `hideSourceMaps` value

---

package.json
yarn.lock

Includes Svelte logo - linked to https://github.com/getsentry/sentry/pull/38118

chore(platformicons): update to 5.3.1

---

src/platforms/common/performance/instrumentation/performance-metrics.mdx

fixes this typo in the performance metrics doc
https://docs.sentry.io/platforms/python/performance/instrumentation/performance-metrics/#information-units

Fix duplicate petabyte typo in Performance Metrics doc

---

src/platforms/javascript/guides/react/configuration/integrations/react-router.mdx

To make sure we prevent possible mis-configurations with the React Router v4/v5 integration, this PR updates our docs around it. We first move the usage of `withSentryRouting` higher up, and encourage it as the default approach to use for paramaterization. We then move down the route config option below that, and offer it as a way for users to define paths outside of the usage of `withSentryRouting`.

fix(react): Update React Router v4/v5 to make paramaterization more clear

---

src/platforms/javascript/guides/svelte/features/componenttracking.mdx
src/platforms/javascript/guides/svelte/features/index.mdx

This PR adds a page in the Svelte SDK documentation about a new feature in the SDK, component tracking. It includes a brief description of what this feature does and how to use it (two ways). 
I'm not particularly happy with the placement of the documentation but I took what we have in Angular and React as an example. In the future I'd vote to rename the navigation item on the left for Angular and React from "Components" to "[Framwork] Features". This title is IMO more general and better represents what's in there than "Components". In Angular for instance, none of the trace helpers are actual components. If we do this, we should also consider to adapt the Vue documentation which doesn't have such a section but scatters its component tracking documentation in the performance monitorin …

feat(svelte): Add documentation for component tracking

---

src/platform-includes/sourcemaps/upload/webpack/javascript.mdx

Fixes a typo on [Sentry React Webpack](https://docs.sentry.io/platforms/javascript/guides/react/sourcemaps/uploading/webpack/) page.
`of the` -> `of`
---

✏️ Nothing major, fix a typo: of the -> of

---

src/docs/product/profiling/index.mdx

We started getting inbound email originating from docs but not understanding that only iOS and Android are supported currently. This should help with that. See screenshot.

Emphasize the supported platforms on the product page

---

src/docs/product/relay/monitoring/index.mdx

Remove a duplicate line from the relay monitoring docs. This line is a partial sentence and repeats info from the sentence before it.

fix: remove duplicate info in relay metrics

---

src/platforms/node/guides/gcp-functions/index.mdx

https://sentry-docs-git-abhi-version-serverless.sentry.dev/platforms/node/guides/gcp-functions/

Use latest version in serverless GCP docs

---

src/platform-includes/getting-started-primer/javascript.svelte.mdx

This tiny PR bumps our Svelte SDK's status from alpha to beta. 
Only merge this, when we go live with the beta
ref: https://github.com/getsentry/sentry-javascript/issues/5671

ref(svelte): Bump SDK status from alpha to beta

---

src/wizard/javascript/svelte.md

This PR adds the onboarding wizard page for the Svelte SDK.
ref: https://github.com/getsentry/sentry-javascript/issues/5671

feat: Add onboarding wizard instructions for Svelte SDK

---

src/docs/product/data-management-settings/server-side-sampling/current-limitations.mdx
src/docs/product/data-management-settings/server-side-sampling/getting-started.mdx

After DS support for RN is released this needs to be updated and published.
Related pull requests:
- https://github.com/getsentry/sentry-react-native/pull/2454

(docs) Add RN SDK to supported list for DS

---

src/docs/product/dashboards/widget-builder/index.mdx
src/docs/product/dashboards/widget-library/index.mdx

Reverts getsentry/sentry-docs#5280 since we re-enabled Release widgets
and is now in GA

Revert "docs(dashboards): Revert Releases widget docs"

---

src/platform-includes/set-level/ruby.mdx

Added list of log levels for Ruby
Replaces PR #5401 - had to close that one because we changed the structure of our includes since it was opened

add log levels for ruby

---

src/docs/product/user-feedback/index.mdx
src/platforms/common/enriching-events/user-feedback.mdx

- Adds a note at the end of the main [User Feedback](https://docs.sentry.io/product/user-feedback/) indicating which SDKs don't support the feature with a warning that clicking the link may result in a 404
- Adds PlatformSection for Native and React Native indicating the feature is not supported
- Adds PlatformSection for Ruby indicating the feature is only supported for Rails

add guidance for SDKs not supporting user feedback

---

src/docs/product/sentry-basics/search/searchable-properties.mdx

Fixes https://getsentry.atlassian.net/browse/ISSUE-1549
After some conversation we're going to be slowly removing "handled" from docs and product where possible.

Remove `handled` property use `error.handled` instead

---

src/platforms/javascript/guides/react/configuration/integrations/react-router.mdx

Adds a warning about the React Router 6 Instrumentation's expected init order.
Related: 
https://github.com/getsentry/sentry-javascript/issues/5555
https://github.com/getsentry/sentry-javascript/issues/5309

Add a warning about the React Router v6 init order.

---

src/platform-includes/capture-error/apple.mdx

Added documentation for the new custom error description feature.
Relates to https://github.com/getsentry/sentry-cocoa/pull/2120

feat: Custom error description docs for sentry-cocoa

---

src/docs/product/alerts/alert-types.mdx

Some users miss this point and expect issue alerts to be constantly scanning. It is reiterated further down after a screenshot though.

clarify initial premise of issue alerts

---

src/platform-includes/enriching-events/scopes/scope-callback-param/dotnet.mdx

Fixed incorrect variable assignment in CaptureException call back  function.

Fixed incorrect variable assignment

---

src/platforms/node/common/configuration/integrations/default-integrations.mdx
src/platforms/node/common/configuration/integrations/pluggable-integrations.mdx

documents https://github.com/getsentry/sentry-javascript/pull/5706
Moves `Modules` integration from optional -> default
Blocked on new SDK release

feat(node): Add Modules integration docs

---

src/docs/product/accounts/pricing.mdx

Adds the following to the Pricing & Billing page under Taxes:
Canadian Taxes
VAT
B2B/B2C taxes

add canadian, VAT, and b2b/b2c sections to taxes

---

src/platform-includes/enriching-events/breadcrumbs/automatic-breadcrumbs/apple.mdx
src/platform-includes/getting-started-primer/apple.macos.mdx

The auto-generated breadcrumbs page for Apple was missing. This is fixed now.
Came up in https://github.com/getsentry/sentry-docs/issues/5509.

feat(apple): Add auto generated breadcrumbs

---

src/docs/contributing/approach/product-docs/write-index.mdx
src/docs/contributing/approach/sdk-docs/common_content.mdx
src/docs/contributing/approach/sdk-docs/write-configuration.mdx
src/docs/contributing/approach/sdk-docs/write-data-management.mdx
src/docs/contributing/approach/sdk-docs/write-enriching-events.mdx
src/docs/contributing/approach/sdk-docs/write-getting-started.mdx
src/docs/contributing/approach/sdk-docs/write-performance.mdx
src/docs/contributing/approach/sdk-docs/write-usage.mdx

Update include directions for platform docs to indicate new platform-includes folder
Add include directions for product docs

update include directions

---

package.json
yarn.lock

Bumping platformicons to 5.2.3 – adds wasm icons to the docs.

update platformicons to 5.2.3

---

src/docs/clients/node/integrations.mdx
src/platform-includes/getting-started-config/javascript.remix.mdx
src/platform-includes/performance/custom-performance-metrics/python.mdx
src/platforms/javascript/guides/react/configuration/integrations/react-router.mdx
src/wizard/javascript/remix.md

Unsure what the distinction between `___DSN___` and `___PUBLIC_DSN___` is but all `__DSN__` (2 underscores) should all be `___DSN___` (3 underscores).

fix(docs): Typo missing third underscore around DSN

---

src/platform-includes/debug-symbols-apple/_default.mdx

I added this snippet in #5147 but we never added the important flag that prevents the process from executing in the background, defeating the purpose of the snippet. I just noticed this behavior going through a new test app setup.

fix: --force-foreground to break builds if upload fails

---

src/docs/product/cli/configuration.mdx

Documentation was missing login command for manual cli login.

fix manual login command

---

src/platforms/apple/common/configuration/app-hangs.mdx

Explain why the app hangs code runs when disabled but keeping OOM enabled.
Came up in https://github.com/getsentry/sentry-cocoa/issues/2214.

fix(apple): Why app hangs run when disabled

---

src/platform-includes/configuration/before-send/native.mdx
src/platforms/common/configuration/options.mdx

There is no support for the `before_breadcrumb`-hook in `sentry-native`, but there is an `on_crash`-hook which hasn't been mentioned yet in the __Basic Options__.

fix(native): Cut before_breadcrumb + add on_crash

---

src/platform-includes/getting-started-config/native.mdx
src/platform-includes/getting-started-config/native.qt.mdx
src/wizard/native/index.md
src/wizard/native/qt.md

As discussed with @Swatinem and raised in https://github.com/getsentry/sentry-native/issues/754, we should enable the debug option in all introductory examples because many new users are unaware of that option. I left out examples that discuss only one specific option.

fix(native): set debug option in introductory examples

---

src/platforms/common/configuration/options.mdx

The default of `environment` is `production` in the Python SDK.
Fixes https://github.com/getsentry/sentry-python/issues/1625

Fixed wrong default value in documentation

---

src/platform-includes/getting-started-primer/javascript.svelte.mdx

ref: https://github.com/getsentry/sentry-javascript/issues/5492
Svelte is now GA, so we can remove this warning from the docs.

Remove beta warning from Svelte Docs

---

src/platforms/javascript/guides/nextjs/manual-setup.mdx

Ref: https://github.com/getsentry/sentry-javascript/issues/5505
Adds a description for the `autoInstrumentServerFunctions` Next.js SDK option which automatically wraps user's API routes and data fetching methods.

Add docs for Next.js SDK option `autoInstrumentServerFunctions`

---

src/platform-includes/performance/custom-performance-metrics/dart.mdx
src/platform-includes/performance/custom-performance-metrics/javascript.mdx
src/platforms/common/performance/instrumentation/performance-metrics.mdx

Add custom metrics docs for Dart and Flutter

---

src/docs/product/accounts/sso/index.mdx

Noticed this while sending a link to a customer.

fix(saml2): Spelling error in anchor tag

---

src/platform-includes/capture-error/apple.mdx

Specify which min version is needed for customized error descriptions.

fix(apple): Custom error desc min version

---

src/platforms/javascript/common/performance/instrumentation/automatic-instrumentation.mdx

Noticed a few inconsistencies between docs and SDK code while working on #5606: This PR brings the JS SDK `BrowserTracing` integration options up to date with the currently available options:
* add `finalTimeout` option introduced in v7
* remove `maxTransactionDuration` option dropped in v7
* improve `idleTimeout` description

ref: Update `BrowserTracing` options description

---

src/platforms/common/configuration/options.mdx

Fixes https://github.com/getsentry/sentry-docs/issues/4496

clarify that maxBreadcrumbs can be customized

---

src/platforms/javascript/common/troubleshooting/index.mdx

Based on https://github.com/getsentry/sentry-javascript/issues/5894#issuecomment-1270298766
Add troubleshooting note about potential issues with the Vite Bundler.

feat(js): Add vite bundler build issue to troubleshooting

---

.vscode/extensions.json

The mdx VSCode extension we currently recommend [has been deprecated](https://marketplace.visualstudio.com/items?itemName=silvenon.mdx). This updates the recommendation to point to [its replacement](https://marketplace.visualstudio.com/items?itemName=unifiedjs.vscode-mdx).

chore(dev): Update VSCode mdx extension recommendation

---

src/platforms/common/performance/index.mdx

Fix grammar issue regarding sample rate configuration.

Fix grammar issue

---

src/platforms/javascript/common/troubleshooting/index.mdx

Removes git output in code block, that might be confusing at times.

Remove git output from diff view in Vite troubleshooting section

---

src/platform-includes/sourcemaps/overview/javascript.remix.mdx

It's discouraged to upload your source maps to production. Some simple bash commands can be used to remove these after uploading the source maps to Sentry.
Fixes https://github.com/getsentry/sentry-javascript/issues/5740

Update Source Maps docs for Remix

---

src/platforms/javascript/common/performance/instrumentation/automatic-instrumentation.mdx

This PR adds the JS SDK BrowserTracing integration's `heartbeatInterval` option that makes the previously hard-coded heartbeat interval configurable. 
ref: https://github.com/getsentry/sentry-javascript/issues/4925

feat: Add `BrowserTracing` `heartbeatInterval` option description

---

src/platform-includes/performance/automatic-performance-metrics/android.mdx
src/platform-includes/performance/custom-performance-metrics/java.mdx
src/platforms/common/performance/instrumentation/performance-metrics.mdx

Add missing API doc for custom performance metrics, including java and kotlin example code.
See https://github.com/getsentry/sentry-java/pull/2260 for the relevant SDK implementation.
@romtsn who else should be reviewing this PR?

feat(java): Add automatic and custom performance metrics doc

---

src/includes/sampling-supported-sdks.mdx

Remove `beta` as `6.5.0` has been released.

Change min supported DS SDK version for Java

---

src/platform-includes/getting-started-primer/apple.mdx
src/platforms/apple/common/configuration/swizzling.mdx

Remove experimental suffixes for file I/O and core data queries, which are GA already, see https://github.com/getsentry/sentry-docs/pull/5548.

fix(apple): Delete experimental note GA features

---

src/platforms/react-native/troubleshooting.mdx

Inform users of the new arch that we are aware of the issues with the jave stack trace.

Add information about missing java stack trace on rn new arch

---

src/platforms/android/common/gradle.mdx
src/platforms/android/configuration/integrations/file-io.mdx
src/platforms/android/configuration/integrations/okhttp.mdx
src/platforms/android/configuration/integrations/room-and-sqlite.mdx
src/platforms/android/troubleshooting.mdx

It looks like the package for `InstrumentationFeature` changed,  but the docs weren't up to date.
There are some minor whitespace changes as well - those were automatically applied by the pre-commit hook 😉 

fix(android): Use correct imports for InstrumentationFeature

---

src/platform-includes/performance/automatic-performance-metrics/android.mdx
src/platform-includes/performance/automatic-performance-metrics/apple.mdx
src/platform-includes/performance/custom-performance-metrics/apple.mdx
src/platform-includes/performance/custom-performance-metrics/java.mdx
src/platforms/common/performance/instrumentation/performance-metrics.mdx

Only merge after releasing Cocoa 7.28.0. Related Cocoa PR https://github.com/getsentry/sentry-cocoa/pull/2268.
This PR is similar to https://github.com/getsentry/sentry-docs/pull/5604.

feat(apple): Add custom performance metrics

---

src/docs/product/alerts/alert-types.mdx
src/docs/product/alerts/index.mdx
src/docs/product/data-management-settings/event-grouping/fingerprint-rules.mdx
src/docs/product/data-management-settings/event-grouping/grouping-breakdown/index.mdx
src/docs/product/data-management-settings/event-grouping/index.mdx
src/docs/product/data-management-settings/event-grouping/merging-issues/index.mdx
src/docs/product/data-management-settings/event-grouping/stack-trace-rules.mdx
src/docs/product/issues/issue-details/index.mdx
src/docs/product/issues/issue-owners/index.mdx
src/docs/product/issues/performance-issues/index.mdx
src/docs/product/issues/performance-issues/n-one-queries.mdx
src/docs/product/sentry-basics/enrich-data/index.mdx
src/docs/product/sentry-basics/grouping-and-fingerprints/index.mdx
src/docs/product/sentry-basics/key-terms.mdx
src/docs/product/sentry-basics/search/searchable-properties.mdx
src/includes/only-error-issues-note.mdx

Various small changes. Partially addresses PERF-1733. Mostly makes documentation that relates to issues a little more generic by removing references to errors, since issues can now be groups of problematic transactions. In general:
- removes specific references to errors when talking about issues
- add disclaimers above features that only apply to error issues
- add more clarifications about how N+1 Queries work
Using the word "problem" as a substitute for "error", since it's a more generic term seems to work!
Related: #5633

feat(perf-issues): General documentation updates for Performance Issues

---

src/docs/product/integrations/source-code-mgmt/github/index.mdx
src/docs/product/integrations/source-code-mgmt/gitlab/index.mdx

https://github.com/getsentry/sentry/issues/35608
Since Stack Trace Linking is not supported in languages except JS and Python? Adding a reminder so that others won't spent days to find out why it is not working

Add a reminder on the supported languages for Stack Trace Linking

---

src/platforms/apple/common/configuration/app-hangs.mdx

Explain why the Cocoa SDK can't report the exact duration of app hangs.

fix(apple): Explain why no duration for app hangs

---

src/platforms/javascript/guides/electron/index.mdx

Adds details of how to configure the Electron SDK combined with a JavaScript framework specific SDK.

feat(electron): Add details of JavaScript framework specific init

---

src/platforms/javascript/guides/vue/configuration/integrations/vue-router.mdx
src/platforms/javascript/guides/vue/features/component-tracking.mdx

This adds a note on which `vue-router` versions are supported by our vue routing instrumentation. Also did some minor cleanup of the code example as it contained some unnecessary lines. 
ref: https://github.com/getsentry/sentry-javascript/issues/5910

ref(vue): Add vue-router version support information

---

src/components/layout.tsx

Added nav bar to the layout to show in case of mobile view, hide otherwise
Related to this <a href="https://github.com/getsentry/sentry-docs/issues/4593">issue</a>

Top page nav disappears on mobile 

---

src/docs/product/integrations/data-visualization/amazon-sqs/index.mdx
src/docs/product/integrations/data-visualization/segment/index.mdx
src/docs/product/integrations/data-visualization/splunk/index.mdx

Updated data forwarding link. Previously it took you to https://docs.sentry.io/platform-redirect/?next=/data-management/data-forwarding/ which further redirected to “Page Not Found” because the content had been moved to a product page.

updated incorrect links to data forwarding page

---

src/docs/product/integrations/integration-platform/webhooks.mdx

Updating the casing in the Javascript Verifying signature example. 
from `Sentry-Hook-Signature` to `sentry-hook-signature`
The header is received in my test webhook in all lowercase `sentry-hook-signature`, and it is also used like that in the python example. One customer reported getting errors when copying the code due to the wrong case.

fix: Change casing of javascript webhook property

---

src/platform-includes/performance/add-spans-example/native.mdx
src/platform-includes/performance/connect-errors-spans/native.mdx
src/platform-includes/performance/distributed-tracing/native.mdx
src/platform-includes/performance/enable-manual-instrumentation/native.mdx
src/platform-includes/performance/force-sampling-decision/native.mdx

As pointed out in https://github.com/getsentry/sentry-docs/issues/5568, `sentry_transaction_start` takes 2 arguments, but is called in multiple places in the docs with just one argument. The documentation of `sentry_transaction_start` says
```
The second parameter is a custom Sampling Context to be used with a Traces
Sampler to make a more informed sampling decision. The SDK does not currently
support a custom Traces Sampler and this parameter is ignored for the time
being but needs to be provided.
```
Therefore I think we should just add `sentry_value_new_null` as the second argument everywhere.
Fixes https://github.com/getsentry/sentry-docs/issues/5568.

fix: sentry_transaction_start takes 2 arguments

---

src/platforms/android/configuration/integrations/okhttp.mdx

Blocked by https://github.com/getsentry/sentry-java/pull/2287 till it gets released.

Docs for HTTP Client errors OkHttp

---

src/platforms/php/guides/laravel/configuration/laravel-options.mdx
src/platforms/php/guides/laravel/other-versions/index.mdx
src/platforms/php/guides/laravel/other-versions/laravel4.mdx
src/platforms/php/guides/laravel/other-versions/laravel5.mdx
src/platforms/php/guides/laravel/other-versions/laravel6-7.mdx
src/platforms/php/guides/laravel/performance/instrumentation/automatic-instrumentation.mdx

Updates the Laravel docs to be in line with our new major [v3.0.0](https://github.com/getsentry/sentry-laravel/releases/tag/3.0.0).
As Laravel 5.x is now deprecated, I moved it to its own page.

Laravel 3.0.0

---

src/platforms/javascript/guides/svelte/features/component-tracking.mdx

⚠️  Only merge, once next SDK version is released!
This PR updates the Svelte component tracking docs with usage instructions for the new approach we recently [introduced](https://github.com/getsentry/sentry-javascript/pull/5936) to the Svelte SDK. Instead of manually adding a preprocessor to their svelte config, users can now simply wrap their config with a Sentry wrapper function that takes care of adding this preprocessor for them. This new approach allows us to make more changes to the config in the future without asking our users every time to change something in their config.
ref: https://github.com/getsentry/sentry-javascript/issues/5923

ref(svelte): Update component tracking docs with new `withSentryConfig` approach

---

package.json
yarn.lock

- Updated to the proper version of platform icons
- Fixes large Remix icon to make it more readable

fix(icons): updated large remix icon

---

src/platform-includes/capture-error/flutter.mdx
src/platforms/flutter/migration.mdx

Mention usage of `PlatformDispatcher.onError` of SDK.

Document SDK usage of Flutter `PlatformDispatcher.onError` callback

---

src/platforms/ruby/common/configuration/options.mdx

This document is transcluded in the [docs for `sentry-rails`](https://docs.sentry.io/platforms/ruby/guides/rails/configuration/options/) as well as [those for `sentry-ruby`](https://docs.sentry.io/platforms/ruby/configuration/options/). This results in the statement about the default setting for `config.logger` being misleading in the Rails case, because the reader might reasonably assume that it's safe to mutate the default logger.
For example, based on these docs I might reasonably expect to be able to set `config.logger.level = Sentry::Logger::WARN` when initialising Sentry, but if I'm in a Rails app I'd be shooting myself in the foot by unwittingly mutating `Rails.logger` through a shared reference.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of …

Fix misleading description of `config.logger` default.

---

src/platforms/node/guides/express/performance/index.mdx

Update the Node/Express performance docs to show how to setup auto-instrumentation, which was previously missing from the performance section.
I basically copied the content from the Express index page over there, as the index page has a "Performance" section with full instructions.
I kept the manual tracing docs as separate section below.
Closes https://github.com/getsentry/sentry-docs/issues/5680

Update Express performance docs for auto-instrumentation

---

src/platforms/javascript/guides/nextjs/manual-setup.mdx

My smallest contribution ever but it makes a big difference ;)
In the docs for the nextjs manual setup (https://docs.sentry.io/platforms/javascript/guides/nextjs/manual-setup/) there is a tiny error which has a big impact, the extension for the "_error" file in a nextjs project when using typescript should be ".tsx" and not ".ts", so this PR adds the x to the "_error.ts" filename and fixes the compilation error one will get if using the .ts extension instead of the .tsx extension …

fix extension for typescript with jsx file

---

src/platform-includes/performance/automatic-performance-metrics/react-native.mdx
src/platform-includes/performance/custom-performance-metrics/react-native.mdx
src/platforms/common/performance/instrumentation/performance-metrics.mdx

RN example was missing and the RN page showed JS SDK info.
Context: https://github.com/getsentry/team-mobile/issues/51#issuecomment-1292472679

Add dedicated RN example to performance metrics

---

src/platforms/node/common/configuration/integrations/default-integrations.mdx
src/platforms/node/guides/azure-functions/index.mdx
src/platforms/node/guides/koa/index.mdx

This adds documentation for the new `RequestData` integration in the node SDK, which adds request data to events. For frameworks where we don't have wrappers in the SDK, and merely tell people how to use sentry in the docs, this also adds storing the request in scope metadata to our boilerplate.

add `RequestData` integration

---

src/platform-includes/getting-started-config/apple.mdx
src/platform-includes/getting-started-primer/android.mdx
src/platform-includes/getting-started-primer/apple.mdx
src/platforms/apple/common/configuration/http-client-errors.mdx
src/platforms/apple/common/configuration/swizzling.mdx
src/platforms/common/configuration/options.mdx
src/wizard/apple/ios.md

Relates to https://github.com/getsentry/sentry-cocoa/pull/2308
Depends on https://github.com/getsentry/publish/issues/1534

HTTP Client errors docs for iOS

---

src/gatsby/onPostBuild.ts
src/wizard/javascript/replay-onboarding/javascript/1.install.md
src/wizard/javascript/replay-onboarding/javascript/2.configure.md

This is some setup so that we can implement this onboarding experience for Session Replay:
I'm modeling this on the existing code for performance: https://github.com/getsentry/sentry-docs/pull/4888
What we're doing is putting the copy/instructions inside the docs repo, then pulling that into sentry as a checklist so developers can track their progress and get things setup smoothly!
Followup PRs for this will probably include creating more md files, one for each JS framework, so that the instructions are 100% copy+paste ready for any JS project.
See also: https://docs.sentry.io/contributing/onboarding-wizard/

feat(replays):  Update onPostBuild step to generate replay onboarding docs

---

src/platforms/android/common/gradle.mdx
src/platforms/android/configuration/integrations/jetpack-compose.mdx

Add docs for the upcoming Android Jetpack Compose navigation instrumentation feature.
Relevant code changes:
- https://github.com/getsentry/sentry-android-gradle-plugin/pull/392
- https://github.com/getsentry/sentry-java/pull/2320
Todos

feat(android): Add Jetpack Compose navigation instrumentation docs

---

src/platform-includes/performance/connect-services/node.mdx
src/platforms/common/performance/connect-services.mdx

Potentially Resolves: #5647 (Do we need to open another PR on [getsentry/develop](https://github.com/getsentry/develop)?)
Adds basic examples about:
- How to obtain a trace header from a span using `toTraceparent`
- How to use `extractTraceparentData` to continue upstream service traces.
Also removed the part that mentions `continueFromHeaders` function (which is not available in `sentry-javascript`) for JavaScript and Node docs. 
---
As an aside note, Node docs in general seem to need some restructuring, and I just remembered there is unfinished work in https://github.com/getsentry/sentry-docs/issues/3605.
We previously made a few updates in https://github.com/getsentry/sentry-docs/pull/3693, which have already crossed out some sub-tasks there.
I'm up to finish that next, if the team …

Add Distributed Tracing to Node docs

---

src/docs/product/sentry-basics/search/searchable-properties.mdx

Add device screen fields to searchable properties entries

---

src/docs/product/integrations/index.mdx
src/docs/product/integrations/notification-incidents/index.mdx
src/docs/product/integrations/notification-incidents/rootly/index.mdx

Add a new docs page for the Rootly integration published on our integration platform.

feat(integrations): Add Rootly Docs

---

src/platform-includes/enriching-events/attach-screenshots/flutter.mdx
src/platform-includes/getting-started-primer/android.mdx
src/platform-includes/getting-started-primer/apple.mdx
src/platform-includes/getting-started-primer/flutter.mdx
src/platforms/common/configuration/options.mdx
src/platforms/common/enriching-events/screenshots.mdx

Wait new version gets published https://github.com/getsentry/publish/issues/1552

Add screenshots support for Flutter

---

src/wizard/javascript/replay-onboarding/angular/1.install.md
src/wizard/javascript/replay-onboarding/angular/2.configure.md
src/wizard/javascript/replay-onboarding/ember/1.install.md
src/wizard/javascript/replay-onboarding/ember/2.configure.md
src/wizard/javascript/replay-onboarding/gatsby/1.install.md
src/wizard/javascript/replay-onboarding/gatsby/2.configure.md
src/wizard/javascript/replay-onboarding/nextjs/1.install.md
src/wizard/javascript/replay-onboarding/nextjs/2.configure.md
src/wizard/javascript/replay-onboarding/react/1.install.md
src/wizard/javascript/replay-onboarding/react/2.configure.md
src/wizard/javascript/replay-onboarding/remix/1.install.md
src/wizard/javascript/replay-onboarding/remix/2.configure.md
src/wizard/javascript/replay-onboarding/svelte/1.install.md
src/wizard/javascript/replay-onboarding/svelte/2.configure.md
src/wizard/javascript/replay-onboarding/vue/1.install.md
src/wizard/javascript/replay-onboarding/vue/2.configure.md

Following up on https://github.com/getsentry/sentry-docs/pull/5711
Related to https://github.com/getsentry/sentry/issues/40787
Previously when the docs exist for a framework they will appear inside sentry in a slide out (implemented in https://github.com/getsentry/sentry/pull/41141) 
And when there are no docs for a framework the user will get a placeholder message:
This PR fills in all the missing framework types that replay supports so some kind of docs appear in all cases.
- intentionally missing is `angularjs`, because that depends on the old 6.x javascript SDK which is incompatible with Replay.
I checked the code examples against the existing js docs: https://docs.sentry.io/platforms/javascript/ 
After this lands we need to update `sentry` so it knows to lookup docs for these …

feat(replays): Add more example snippets for Replay onboarding

---

src/docs/product/integrations/integration-platform/webhooks.mdx

Update the Python example for the webhook signature comparison to follow best practices.
Using `hmac.compare_digest()` mitigates [timing-based attacks](https://en.wikipedia.org/wiki/Timing_attack) on the signature verification.
I've also updated the line to pull the signature header value to use the `.get()` method in order to avoid a `KeyError` exception.

Update example to follow HMAC best practice

---

src/platform-includes/performance/always-inherit-sampling-decision/dotnet.mdx
src/platform-includes/upload-dif/dotnet.mdx
src/platforms/common/data-management/debug-files/upload/index.mdx

Adding missing snippets listed on #3107
The Debug File Upload page needs to be restructured. It was built for Native, and we're now including it on more platforms.
Unity bundles `sentry-cli` and uploads things automatically as stated in the top note. The instructions that follow are not helpful there.
The .NET SDK support only requires symbol upload for iOS/MacCatalyst/Android at the moment, and the goal is to bundle sentry-cli within the SDK and run it automatically with the build.

fix: missing snippets dotnet

---

src/components/tableOfContents.tsx
src/platforms/python/guides/pymongo/index.mdx

Small update to the Python/PyMongo integrations. Added supported versions.

Python: Added supported PyMongo/Python versions.

---

src/platform-includes/enriching-events/set-user/android.mdx
src/platform-includes/enriching-events/set-user/apple.mdx
src/platform-includes/enriching-events/set-user/flutter.mdx
src/platform-includes/enriching-events/set-user/react-native.mdx
src/platforms/common/enriching-events/identify-user.mdx

Removes notes about fallback behavior from snippets to common content. Clarified language of note by using the name of the option/property vs a descriptor.

move note from snippets into common content

---

src/platform-includes/getting-started-config/apple.mdx
src/platforms/apple/common/performance/instrumentation/automatic-instrumentation.mdx
src/wizard/apple/ios.md

Add docs for the experimental feature enablePreWarmedAppStartTracking, which will be released with
https://github.com/getsentry/sentry-cocoa/pull/1969.
Only merge after releasing https://github.com/getsentry/sentry-cocoa/pull/1969.

feat(apple): Add docs for pre-warmed app starts

---

src/platforms/apple/common/configuration/app-hangs.mdx

Point out that the app hang integration depends on the SentryCrashIntegration.

fix(apple): AppHangs need SentryCrash

---

src/platform-includes/performance/opentelemetry-install/node.mdx
src/platform-includes/performance/opentelemetry-setup/node.mdx
src/platforms/common/performance/instrumentation/opentelemetry.mdx

Mainly based on the README here: https://www.npmjs.com/package/@sentry/opentelemetry-node
Initial Context: https://github.com/getsentry/sentry/discussions/40712
Node SDK work: https://github.com/getsentry/sentry-javascript/issues/6000

Add OpenTelemetry Node SDK docs

---

src/docs/product/accounts/quotas/manage-event-stream-guide.mdx

Sections under new LA section need to be H4s to make clear that they are part of the LA content.

fix LA spike protection sub-sections

---

src/platforms/javascript/guides/electron/index.mdx

Document default Electron offline support

---

src/platforms/javascript/guides/nextjs/manual-setup.mdx

This adds the new `excludeServerRoutes` option in the nextjs SDK (added in https://github.com/getsentry/sentry-javascript/pull/6207) to the docs. It also pulls all of the auto-instrumentation config into its own section in the manual setup page.
(Note: The only part of this which is actually new content is the `Opt Out of Auto-instrumentation on Specific Routes` section. Everything else is just stuff moving around.)

feat(nextjs): Add `excludeServerRoutes` option to manual setup page

---

src/docs/product/data-management-settings/event-grouping/fingerprint-rules.mdx

Adds note about replacing square brackets with asterisks in fingerprinting rules.
Updates a link about syntax to point to search docs.

add note about square brackets for fingerprinting

---

src/platforms/javascript/guides/capacitor/troubleshooting.mdx
src/wizard/capacitor/index.md

The PR explains the importance of using the exact version of the Sibling SDK for Capacitor and a side effect of not doing so.
Wizard was also updated in order to avoid mismatched versions when installing Sentry Capacitor with a sibling SDK.

Capacitor: Add troubleshooting for Sibling SDKs

---

src/platforms/common/configuration/options.mdx

goes with https://github.com/getsentry/sentry-python/pull/1746

feat(python): Add proxy_headers to common/config

---

src/platforms/common/configuration/options.mdx

We should not suggest setting `send_default_pii` as `True` by default without further details on what sensitive information it will send in each platform/framework. It's too risky and can expose credentials, session cookies, etc.

docs(options): adjust send_default_pii recommendation

---

src/platforms/php/common/configuration/transports.mdx

The current code example on the docs has type mismatches when creating the `HttpClientFactory` and missing arguments for `HttpTransport`.

Update async transport to PSR-17 and PSR-18

---

src/platforms/javascript/common/sourcemaps/troubleshooting_js.mdx

This PR checks and adjusts all places in the source maps troubleshooting docs that assume our webpack plugin is the only plugin, which is not the case anymore since we support multiple bundlers now: https://github.com/getsentry/sentry-javascript-bundler-plugins
Also, adjusts some random wrong backticks.
Ref https://github.com/getsentry/sentry-docs/issues/5718

Make source maps troubleshooting page bundler-agnostic

---

src/docs/product/profiling/getting-started.mdx
src/docs/product/profiling/index.mdx
src/platforms/common/profiling/index.mdx

In preparation for the python profiling alpha, this adds the python profiling setup.

docs(profiling): Add python profiling alpha docs

---

src/platform-includes/enriching-events/scopes/configure-scope/native.mdx
src/platforms/common/enriching-events/scopes.mdx

Let's clarify in the explanation of Hub & Scope that the Hub abstraction is not yet implemented in the Native SDK. While the tracing docs mention this shortcoming, changes to the scope from multiple threads are currently not coordinated (besides locking for mutually exclusive access) and affect other use cases too.
Please, @Swatinem and @imatwawana, I welcome your input.

fix(native): hub abstraction not implemented

---

src/platforms/javascript/guides/gatsby/index.mdx

In all of our Getting Started snippets showing people the basic SDK setup, we include `tracesSampleRate: 1.0`, so that people will send transactions by default. In the gatsby docs, though, the option name is wrong - we're turning on error sampling, not transaction sampling. This fixes it to be the right option.

fix(gatsby): Fix performance sample rate option in getting started snippets

---

src/platforms/javascript/guides/nextjs/manual-setup.mdx

Currently, in our nextjs SDK docs about the Sentry webpack plugin, we imply that all it does is upload sourcemaps. In fact, the plugin is also what causes sourcemaps to be generated in the first place, but we don't tell people that. Nor do we tell them that it automatically sets the SDK's release value. As a result, it seems from our docs like disabling the plugin only disables upload, when in fact that's not the case.
This clarifies the full scope of the plugin's function, and adds a note telling people who disable the plugin that they'll have to set the release value themselves.
Fixes https://github.com/getsentry/sentry-javascript/issues/6240.

fix(nextjs): Improve explanation of webpack plugin function

---

src/docs/product/accounts/quotas/index.mdx
src/docs/product/accounts/quotas/manage-transaction-quota.mdx

This removes the SDK Sample Rate section from the guide on transaction quota management, because `sampleRate` doesn't apply to transactions, and `tracesSampleRate` is covered by the next heading, SDK Tracing options.

fix(quota): Remove `sampleRate` section in transaction quota guide

---

src/docs/product/accounts/quotas/index.mdx
src/docs/product/accounts/quotas/manage-event-stream-guide.mdx
src/docs/product/relay/index.mdx
src/platform-includes/configuration/decluttering/javascript.mdx
src/platforms/common/configuration/options.mdx
src/platforms/common/data-management/sensitive-data/index.mdx
src/platforms/common/enriching-events/user-feedback.mdx
src/platforms/javascript/common/configuration/integrations/plugin.mdx
src/platforms/javascript/common/troubleshooting/index.mdx
src/platforms/javascript/guides/gatsby/index.mdx
src/platforms/node/common/configuration/integrations/pluggable-integrations.mdx

This is a bunch of small fixes and tweaks extracted from my work adding `beforeSendTransaction` to the docs - autoformatting, proofreading, and the occasional clarification. 
Note to reviewers: Each commit is atomic and accurately described, so it may be easier to review just going through them that way.

fix(various): Small formatting and language fixes

---

src/docs/product/issues/issue-details/error-issues/index.mdx
src/docs/product/issues/issue-details/index.mdx
src/platforms/common/enriching-events/screenshots.mdx

Add a couple lines of product docs for the screenshot feature.
There is already a Screenshot section in the relevant SDKs.
Fixed "Attachments" formatting:
Before
After

docs: Add product docs for screenshots

---

src/platforms/javascript/guides/react/configuration/integrations/react-router.mdx

Documents: https://github.com/getsentry/sentry-javascript/pull/6172
TODO: Update the version

Add documentation for React Router 6.4 support.

---

src/platform-includes/performance/file-io-instrumentation/java.mdx

Code examples were missing `new` statement on second file open.

Fixing typos in code examples

---

src/platform-includes/performance/opentelemetry-setup/node.mdx

Mapping over the changes from https://github.com/getsentry/sentry-javascript/pull/6262
1. Convert from ES modules to `require`
2. Specify to set the `instrumenter` option to turn off Sentry instrumentation
3. Clean up imports 
4. Add `sdk.start` command to match otel docs: https://opentelemetry.io/docs/instrumentation/js/getting-started/nodejs/#setup

chore(otel): Update otel node installation instructions

---

src/platform-includes/sourcemaps/overview/javascript.vue.mdx
src/platforms/javascript/common/sourcemaps/uploading/systemjs.mdx
src/platforms/javascript/common/sourcemaps/uploading/uglifyjs.mdx

Adds a guide on how to use our Vite bundler plugin directly on the source maps page of the Vue docs. Vite is essentially the default for Vue projects so this should make the barrier of entry a tiny bit smaller.

Add vite plugin documentation to vue source maps page

---

src/docs/product/profiling/getting-started.mdx
src/docs/product/profiling/index.mdx
src/platforms/common/profiling/index.mdx

In preparation for the rust profiling alpha, this adds the rust profiling setup.

docs(profiling): add rust profiling alpha doc

---

src/platform-includes/performance/opentelemetry-install/javascript.nextjs.mdx
src/platform-includes/performance/opentelemetry-setup/javascript.nextjs.mdx
src/platforms/common/performance/instrumentation/opentelemetry.mdx

Basically the same as Node docs (https://github.com/getsentry/sentry-docs/pull/5760), but with some adjustments.

feat(otel): add NextJS OpenTelemetry docs

---

src/platforms/javascript/common/troubleshooting/index.mdx

Changes "here" to "below" to make clear the content is on the current page

clarify wording to indicate location of content

---

src/docs/product/integrations/source-code-mgmt/github/index.mdx
src/docs/product/integrations/source-code-mgmt/gitlab/index.mdx

This is to update the list added in #5642.

Update list of platforms that support stacktrace linking

---

src/docs/product/accounts/quotas/index.mdx
src/docs/product/accounts/quotas/manage-event-stream-guide.mdx
src/docs/product/accounts/quotas/manage-transaction-quota.mdx
src/docs/product/relay/index.mdx
src/platform-includes/configuration/before-send-transaction/javascript.mdx
src/platform-includes/configuration/before-send/javascript.mdx
src/platforms/common/configuration/filtering.mdx
src/platforms/common/configuration/options.mdx
src/platforms/common/data-management/sensitive-data/index.mdx
src/platforms/common/enriching-events/event-processors.mdx
src/platforms/javascript/common/configuration/integrations/plugin.mdx
src/platforms/javascript/guides/gatsby/index.mdx
src/platforms/node/common/configuration/integrations/pluggable-integrations.mdx

This adds the new `beforeSendTransaction` option to the docs, both on the options page and alongside `beforeSend` in many places in the text. Because you can't selectively turn certain phrases on and off for different platforms, I tried to indicate where I could that it's not universally supported. (Right now, I believe JS is in fact the only platform to support it, though I expect that to change in the near future.) It also does a tiny bit of wordsmithing of the text around the additions, courtesy of @lizokm and @imatwawana.
Note that the one spot where updates haven't been done in this PR is the text of the Filtering page, as it's being worked on separately in https://github.com/getsentry/sentry-docs/pull/5804. Once the changes there are done, …

feat(js): Add `beforeSendTransaction` option

---

src/platform-includes/performance/opentelemetry-install/ruby.mdx
src/platform-includes/performance/opentelemetry-setup/ruby.mdx
src/platforms/common/performance/instrumentation/opentelemetry.mdx

Blocked on next release of Ruby SDK so draft PR as a result.

feat(otel): Add docs for Ruby OpenTelemetry

---

src/platform-includes/sourcemaps/upload/primer/javascript.svelte.mdx
src/platforms/javascript/common/sourcemaps/uploading/typescript.mdx

Updates the Svelte source maps docs to refer to the new vite bundler plugin. Also removes tsc as a recommended tool and adds a section that was accidentally removed.

Update Svelte source maps docs to refer to new bundler plugins

---

.github/workflows/issue-routing-helper.yml

This implements a membership check so that the routing logic doesn't happen for issues created by Sentry members

Implement membership check before routing logic

---

src/platforms/javascript/common/configuration/integrations/default.mdx

When the new `RequestData` integration was [added to the node docs](https://github.com/getsentry/sentry-docs/pull/5674), it should also have been added to the nextjs and remix docs, since both frameworks are combo frontend-backend.

fix(nextjs/remix): Add `RequestData` integration to default integrations page

---

src/platform-includes/getting-started-verify/javascript.react.mdx
src/wizard/javascript/react.md
src/wizard/javascript/remix.md

When going through the process of instrumenting Sentry on Javascript (React as an example) I uncovered this small annoyance.
To verify if Sentry is instrumented you’re asked to intentionally create an error with this snippet of code.
`return <button onClick={methodDoesNotExist}>Break the world</button>;`
The Problem here is that, you get a blank white screen by adding this `-> onClick={methodDoesNotExist}` because your in fact not declaring anything. I know a developer would know this, but I don’t think we should rely on people reading the snippet of code to get the intended value.

fix: Code samples for react components

---

src/platform-includes/getting-started-primer/dart.mdx
src/platform-includes/getting-started-primer/flutter.mdx
src/platforms/dart/common/performance/instrumentation/automatic-instrumentation.mdx
src/platforms/dart/configuration/integrations/file.mdx
src/platforms/flutter/common/configuration/integrations/user-interaction-instrumentation.mdx
src/platforms/flutter/common/performance/instrumentation/automatic-instrumentation.mdx

Relates to https://github.com/getsentry/sentry-dart/pull/1160

Add File IO instrumentation docs

---

src/docs/product/accounts/quotas/index.mdx
src/docs/product/issues/index.mdx

Adds more to note about issues/events/quota in Issues page
Adds link to note from Quota Management page

add issues and quota content and link to content

---

src/wizard/javascript/replay-onboarding/angular/2.configure.md
src/wizard/javascript/replay-onboarding/ember/2.configure.md
src/wizard/javascript/replay-onboarding/gatsby/2.configure.md
src/wizard/javascript/replay-onboarding/nextjs/2.configure.md
src/wizard/javascript/replay-onboarding/react/2.configure.md
src/wizard/javascript/replay-onboarding/remix/2.configure.md
src/wizard/javascript/replay-onboarding/svelte/2.configure.md
src/wizard/javascript/replay-onboarding/vue/2.configure.md

The changed text/url appears in the app inside this onboarding slide-out:
Depends on https://github.com/getsentry/sentry-docs/pull/5899

Update Replay Wizard links and examples to link to docs and use correct field names

---

src/platforms/javascript/common/session-replay/custom-instrumentation/general-configuration.mdx

Removing reference to Canvas since it's not supported in Session Replay.

Update general-configuration - remove Canvas

---

src/pages/index.tsx

This might spark a conversation, but I've added links to the (forthcoming) Session Replay product docs from the footer on the homepage:
| --- | --- |
| ![before](https://user-images.githubusercontent.com/187460/206037079-79122da0-ef73-437d-865f-ef6f5d2859c0.png)  | ![after](https://user-images.githubusercontent.com/187460/206037106-1b392431-0c11-4c77-8eb7-9fd9df282d7a.png) |
Changes:
1. `Session Replay` is added to the 1st column,
2. `Sentry-CLI` moved from column 1 into 2
3. `Integrations` moved from column 2 into 3, next to Integration Platform
This is just a suggestion!
We should add a link down here imo, but what position does it take?
Also DONT MERGE this until the product docs actually exist

feat(replays): Add link to session replay product docs from homepage footer

---

src/platforms/unity/configuration/il2cpp.mdx

Came up on Twitter where people were not sure this affected Release Builds
Debug Builds anyway have line numbers

unity il2cpp release builds

---

src/platform-includes/session-replay/install-session-replay/javascript.mdx
src/platform-includes/session-replay/setup-session-replay/javascript.mdx
src/platforms/javascript/common/session-replay/index.mdx

Notes sent in self review
See: https://github.com/getsentry/sentry-docs/issues/5903

replay: ref onboarding snippet

---

src/platform-includes/session-replay/install-session-replay/javascript.mdx

Document unminified bundle until fix is live.
This is likely reverted on Monday morning EST already

replay: cdn non minified

---

src/docs/product/integrations/issue-tracking/jira/index.mdx

There's a note in the troubleshooting section but it is too common for customers to use ad-blockers.

Add note to disable ad-blocker when installing JIRA

---

src/platform-includes/session-replay/install-session-replay/javascript.mdx

⚠️ Only merge after 7.25.0 of the JS SDK is released
This reverts #5943 as we fixed the bug with minified CDN bundles.

Revert "replay: cdn non minified (#5943)"

---

src/platforms/javascript/common/session-replay/index.mdx
src/wizard/javascript/replay-onboarding/angular/2.configure.md
src/wizard/javascript/replay-onboarding/ember/2.configure.md
src/wizard/javascript/replay-onboarding/gatsby/2.configure.md
src/wizard/javascript/replay-onboarding/javascript/2.configure.md
src/wizard/javascript/replay-onboarding/nextjs/2.configure.md
src/wizard/javascript/replay-onboarding/react/2.configure.md
src/wizard/javascript/replay-onboarding/remix/2.configure.md
src/wizard/javascript/replay-onboarding/svelte/2.configure.md
src/wizard/javascript/replay-onboarding/vue/2.configure.md

Addresses review notes from @imatwawana left after the previous PR was merged:
https://github.com/getsentry/sentry-docs/pull/5927#pullrequestreview-1212121599

replay: corrections; latin, ordering

---

package.json
yarn.lock

It was impossible for me to build and run the docs locally, due to an old version node-sass using an old version of node-gyp, which didn't work on my machine.
Fixes #5936

fix: Migrate from node-sass to sass

---

src/platforms/javascript/guides/nextjs/manual-setup.mdx

Adds a description for the `tunnelRoute` option introduced in https://github.com/getsentry/sentry-javascript/pull/6425.

Add description for Next.js SDK `tunnelRoute` option

---

src/platform-includes/performance/opentelemetry-install/python.mdx
src/platform-includes/performance/opentelemetry-setup/python.mdx
src/platforms/common/performance/instrumentation/opentelemetry.mdx

Basically the same as Ruby docs (https://github.com/getsentry/sentry-docs/pull/5856), but for Python.

feat(otel): Add docs for Python OpenTelemetry

---

src/platforms/apple/common/install/swift-package-manager.mdx

Problem: package(name:url:from:) is [deprecated since SPM 5.6](https://github.com/apple/swift-package-manager/blob/dd7e9cc68fccd6aad5db11aca2becfc24746905a/Sources/PackageDescription/PackageDependency.swift#L256).
Solution: switch to the new syntax.

SPM: package(name:url:from:) is deprecated

---

bin/bootstrap

- Yarn wasn't included in the bootstrap, which meant the next step in the contributing docs of running `make` would fail

fix: include yarn in bootstrap

---

src/platform-includes/session-replay/install/javascript.mdx
src/platform-includes/session-replay/setup/javascript.mdx
src/wizard/javascript/replay-onboarding/angular/1.install.md
src/wizard/javascript/replay-onboarding/angular/2.configure.md
src/wizard/javascript/replay-onboarding/ember/1.install.md
src/wizard/javascript/replay-onboarding/ember/2.configure.md
src/wizard/javascript/replay-onboarding/gatsby/1.install.md
src/wizard/javascript/replay-onboarding/gatsby/2.configure.md
src/wizard/javascript/replay-onboarding/javascript/1.install.md
src/wizard/javascript/replay-onboarding/javascript/2.configure.md
src/wizard/javascript/replay-onboarding/nextjs/1.install.md
src/wizard/javascript/replay-onboarding/nextjs/2.configure.md
src/wizard/javascript/replay-onboarding/react/1.install.md
src/wizard/javascript/replay-onboarding/react/2.configure.md
src/wizard/javascript/replay-onboarding/remix/1.install.md
src/wizard/javascript/replay-onboarding/remix/2.configure.md
src/wizard/javascript/replay-onboarding/svelte/1.install.md
src/wizard/javascript/replay-onboarding/svelte/2.configure.md
src/wizard/javascript/replay-onboarding/vue/1.install.md
src/wizard/javascript/replay-onboarding/vue/2.configure.md

This PR updates the Session Replay docs after we released version 7.27.0 of the JS SDKs. With this new version, users don't need to explicitly install `@sentry/replay` anymore, as it is now a dependency of `@sentry/browser` which [exports the Replay integration](https://github.com/getsentry/sentry-javascript/pull/6508). 
* Update the session replay setup page
* Update the session replay onboarding wizard
ref #https://github.com/getsentry/sentry-javascript/issues/6326
Note: I'd like to keep this PR open for a few days (Monday or so) just to make sure 7.27.0 isn't breaking anything

ref(replay): Update Replay installation with SDK-package import

---

src/platform-includes/enriching-events/user-feedback/sdk-api-example/react-native.mdx

Not released yet.
- https://github.com/getsentry/sentry-react-native/pull/2675

Add last event id to the feedback example react-native

---

src/platform-includes/getting-started-install/android.mdx
src/platforms/android/common/gradle.mdx

We got some feedback that it's not clear if the Sentry SDK should be applied on the project root or on the app level. This is an effort to make it more clear that the SDK needs be added on a module level.

ref(android): Clarify initial Android SDK gradle setup step

---

src/docs/clients/cocoa/dsym.mdx
src/platform-includes/debug-symbols-apple/_default.mdx

Xcode 10 was released four years ago, and not one should be using it anymore.

fix(apple): Remove Xcode 10 note for dSYMs

---

src/platform-includes/debug-symbols-apple/_default.mdx

Making the pricing tier limitations clearer for people trying to use multiple App Store Connect sources.

clarifying pricing tier limitations for App Store Connect sources

---

src/platform-includes/configuration/before-send/javascript.mdx

Related to https://github.com/getsentry/sentry-docs/issues/5988, the current docs for `beforeSend` in JS can be more explicit about which return values are allowed. This PR updates this section to explicitly state that only `null` or an event payload are allowed.

fix(javascript): Make `beforeSend` return values more explicit

---

src/platforms/common/profiling/index.mdx
src/wizard/rust/profiling-onboarding/rust/0.alert.md
src/wizard/rust/profiling-onboarding/rust/1.install.md
src/wizard/rust/profiling-onboarding/rust/2.configure-performance.md
src/wizard/rust/profiling-onboarding/rust/3.configure-profiling.md
src/wizard/rust/profiling-onboarding/rust/4.upload.md

This PR adds "wizard" docs for Rust profiling.

feat(profiling): add wizard onboarding docs for rust

---

src/platform-includes/performance/add-spans-example/ruby.mdx

This is much closer to how Python is documented, and is usually what
people want:
1. nests span under currently executing span
2. handles cases where there is no current transaction by discarding the
span (easily hittable in unittests)

fix(ruby): Use global with_child_span in custom spans example

---

src/platform-includes/getting-started-primer/react-native.mdx
src/platforms/react-native/troubleshooting.mdx

Remove the Expo troubleshooting page
And reword the Expo package text to explicitely point to the Expo team
closes: https://github.com/getsentry/sentry-docs/issues/5696

ref(rn): Remove expo troubleshooting and reword the expo package info

---

src/docs/product/issues/issue-owners/index.mdx

Fixes WOR-2497
Add 100K char limitation to Ownership Rules doc, similarly to how it's added for Codeowners

fix: Add Ownership Rules 100K char limitation

---

src/platforms/react-native/manual-setup/hermes.mdx

Add note about the zero sized bundle.
- https://github.com/getsentry/sentry-react-native/issues/2683

chore(rn): Add note about zero bytes size bundle with Hermes on Android

---

src/includes/beta-note-session-replay.mdx

To encourage users to open GitHub issues for their feedback, and to list the supported SDKs on the Session Replay SDK docs.

Update to beta note on Session Replay SDK Docs

---

src/platform-includes/sourcemaps/overview/javascript.mdx
src/platform-includes/sourcemaps/primer/javascript.nextjs.mdx

This PR adds Vercel and Github Actions as a way to set up source maps. Note I did not make separate pages within `/sourcemaps/uploading/` so they won't show up in the sidebar as they exist in other parts of documentation.

feat(source-maps): adds Vercel and Github actions to source map tools

---

src/platforms/javascript/guides/nextjs/manual-setup.mdx

Hey What's up?!
This PR fixes a typo in the manual setup for NextJS application.
[doc page](https://docs.sentry.io/platforms/javascript/guides/nextjs/manual-setup/#opt-out-of-auto-instrumentation-on-specific-routes)

fix(manual-setup-nextjs): fix typo

---

src/platforms/common/configuration/options.mdx

@Angelodaniel made us aware of a sentence that seems to have been duplicated by accident. This PR just cleans this up and slightly rewords the descriptions of `allowUrls` and `denyUrls`.

ref(js): Reword `allowUrls` and `denyUrls` docs

---

src/platforms/apple/common/migration.mdx

Merge after 8.0.0 is released.

feat(apple): Migration guide for sentry-cocoa 7 -> 8

---

src/platforms/go/guides/echo/index.mdx
src/platforms/go/guides/fasthttp/index.mdx
src/platforms/go/guides/gin/index.mdx
src/platforms/go/guides/http/index.mdx
src/platforms/go/guides/iris/index.mdx
src/platforms/go/guides/martini/index.mdx
src/platforms/go/guides/negroni/index.mdx

We're changing the location of the examples directory in sentry-go repository.
Companion PR: https://github.com/getsentry/sentry-go/pull/521 (should be merged first).

fix(go): Fix links to examples in sentry-go repository

---

src/platforms/apple/common/migration.mdx

Add a couple of more breaking changes and modifications to the migration docs. Furthermore, restructure them a bit.
We can already merge this as [Cocoa 8.0.0-rc.1](https://github.com/getsentry/sentry-cocoa/releases/tag/8.0.0-rc.1) is out.

feat(apple): Final pass for migration docs

---

src/platforms/apple/common/configuration/out-of-memory.mdx

The text of the watchdog termination and OOM page are the same, except for the name of the integration. Instead of maintaining both pages, we can redirect users of OOM to the watchdog page.

ref(apple): Remove duplicate text of OOM

---

src/docs/product/sentry-basics/search/searchable-properties.mdx

in tandem with https://github.com/getsentry/sentry/pull/43125, adds levels to our docs, which seemed to be missing before.

fix(search): add level to docs

---

src/platform-includes/debug-symbols-apple/_default.mdx
src/platform-includes/getting-started-config/apple.mdx
src/platform-includes/getting-started-config/javascript.capacitor.mdx
src/platforms/common/data-management/debug-files/index.mdx
src/platforms/unity/native-support/index.mdx
src/wizard/apple/index.md
src/wizard/apple/ios.md
src/wizard/apple/macos.md

This PR restructures the dSYMs page for Apple to make it easier to understand, moves the Bitcode related section down, as Bitcode is now deprecated with Xcode 14, and mentions how to upload source bundles for source context to work.
Fixes GH-5823
As I tried to add the information on how to make source context work, I would have had to add the info in many different places. Instead, I restructured the page quite a bit to simplify it, and now I have to add the info in fewer places.

ref(apple): dSYMs restructuring

---

src/platform-includes/getting-started-config/apple.mdx
src/platforms/apple/common/configuration/metric-kit.mdx
src/wizard/apple/ios.md

Add docs for the experimental MetricKit integration available on Sentry Cocoa 8.0.0 and above.
Merge after releasing Cocoa 8.0.0.

feat(apple): Docs for the MetricKit integration

---

src/platform-includes/configuration/before-send-transaction/go.mdx
src/platforms/common/configuration/filtering.mdx
src/platforms/common/configuration/options.mdx

BeforeSendTransaction is added to sentry-go here: https://github.com/getsentry/sentry-go/pull/517
The change is not released yet, so we'll be merging this together with the release of the next sentry-go version.
Similarly to https://github.com/getsentry/sentry-docs/pull/6039, not touching any other pages for now, given the on-going refactorings of BeforeSendTransaction docs in https://github.com/getsentry/sentry-docs/pull/6038, https://github.com/getsentry/sentry-docs/pull/5804, and https://github.com/getsentry/sentry-docs/pull/5838.

feat(go): Add BeforeSendTransaction example snippet

---

src/platforms/go/common/configuration/options.mdx

BeforeSendTransaction is added to sentry-go here: https://github.com/getsentry/sentry-go/pull/517
The change is not released yet, so we'll be merging this together with the release of the next sentry-go version.
Not touching any other pages for now, given the on-going refactorings of BeforeSendTransaction docs in https://github.com/getsentry/sentry-docs/pull/6038, https://github.com/getsentry/sentry-docs/pull/5804, and https://github.com/getsentry/sentry-docs/pull/5838.

feat(go): Add BeforeSendTransaction to Basic Options page

---

src/docs/product/cli/installation.mdx

The script is updated to imply sh usage here

feat(cli): Replace bash w/ sh for installer

---

src/platform-includes/debug-symbols-apple/_default.mdx

Specify clearly that include sources uploads users' source code to Sentry.

fix(apple): Clarify source context uploads code

---

src/platform-includes/getting-started-config/apple.mdx
src/platform-includes/getting-started-primer/apple.mdx
src/platforms/apple/common/configuration/swizzling.mdx
src/platforms/apple/common/performance/instrumentation/automatic-instrumentation.mdx
src/wizard/apple/ios.md

We renamed a couple of features from tracking to tracing for Cocoa 8.0.0. We missed a couple of renamings, which this PR addresses. Furthermore, we can remove some of the renamed features in the wizard and getting started as they are now enabled by default. Finally, this PR also clarifies that core data spans are enabled by default.
I did a bunch of different changes in one PR, as splitting them up would be complicated.
This is a follow-up on https://github.com/getsentry/sentry-docs/pull/5859.

fix(apple): Renamings from tracking to tracing

---

src/platforms/common/configuration/options.mdx
src/platforms/node/common/configuration/integrations/default-integrations.mdx

Closes #6060
Adds docs for the `LocalVariables` integration.

feat(node): Add `LocalVariables` integration

---

src/platforms/javascript/guides/nextjs/manual-setup.mdx

Update the Next.js Manual Setup to include the following based on the issue https://github.com/getsentry/sentry-javascript/issues/6729
If you want the `sentry` to be available in your server side & not in client side, you can make your `sentry.client.config.js` empty. This will prevent webpack from pulling in the Sentry related files when generating the browser bundle. The same goes the opposite for opting out of server side bundle by emptying `sentry.server.config.js`.
You cannot delete the respective config files because the SDK requires you to have it. …

docs(nextjs): Add info on opting out of client/server bundles

---

src/platforms/react-native/performance/instrumentation/automatic-instrumentation.mdx

This property has been renamed in sentry-javascript and the original name is deprecated and marked for removal in the next major version.
See: https://github.com/getsentry/sentry-javascript/blob/461afdfc3740e19536b0c6fe515aeff40b130bd0/packages/tracing/src/browser/request.ts#L31

tracingOrigins changed to tracePropagationTargets

---

src/platforms/javascript/common/session-replay/index.mdx
src/wizard/javascript/replay-onboarding/angular/1.install.md
src/wizard/javascript/replay-onboarding/ember/1.install.md
src/wizard/javascript/replay-onboarding/ember/2.configure.md
src/wizard/javascript/replay-onboarding/gatsby/1.install.md
src/wizard/javascript/replay-onboarding/javascript/1.install.md
src/wizard/javascript/replay-onboarding/nextjs/1.install.md
src/wizard/javascript/replay-onboarding/nextjs/2.configure.md
src/wizard/javascript/replay-onboarding/react/1.install.md
src/wizard/javascript/replay-onboarding/remix/1.install.md
src/wizard/javascript/replay-onboarding/remix/2.configure.md
src/wizard/javascript/replay-onboarding/svelte/1.install.md
src/wizard/javascript/replay-onboarding/vue/1.install.md
src/wizard/javascript/replay-onboarding/vue/2.configure.md

This updates the docs for Replay to ensure we reference the "new" installation style everywhere.

feat(replay): Update replay setup docs

---

src/platforms/javascript/common/session-replay/configuration.mdx

Remove the advanced recording configuration options as we want greater control over how recording should be done. The SDK API will be changed at a later point so that these options will not be passed. Instead we will provide good defaults that shouldnt need to be configured.

feat(replay): Remove advanced configuration

---

src/platforms/apple/common/migration.mdx

Mention in migration docs that we renamed the master branch to main.

feat(apple): Rename master to main branch

---

src/includes/beta-note-opentelemetry.mdx
src/platforms/common/performance/instrumentation/opentelemetry.mdx

Otel SDKs are in beta - let's update docs to reflect this.

Move from alpha -> beta note for OpenTelemetry

---

src/platform-includes/session-replay/setup/javascript.mdx
src/platforms/javascript/common/session-replay/configuration.mdx

This adds docs for lazy loading Replay and fixes the docs for start/stop recording.

feat(replay): Update docs for starting/resuming recording

---

src/docs/product/issues/issue-details/error-issues/index.mdx
src/docs/product/issues/issue-details/index.mdx
src/platforms/common/enriching-events/screenshots.mdx

Add the information the screenshots are capture not only with errors, but also when the app crashes

feat(apple): More detail to when screenshots are captured

---

src/platform-includes/configuration/before-send-transaction/python.mdx
src/platforms/common/configuration/filtering.mdx
src/platforms/common/configuration/options.mdx

Python is now also able to specify a `before_send_transaction` option.

Enable before_send_transaction for python

---

src/platform-includes/sourcemaps/overview/javascript.svelte.mdx
src/platform-includes/sourcemaps/overview/javascript.vue.mdx
src/platform-includes/sourcemaps/upload/esbuild/javascript.mdx
src/platform-includes/sourcemaps/upload/rollup/javascript.mdx
src/platform-includes/sourcemaps/upload/vite/javascript.mdx

https://github.com/getsentry/sentry-javascript-bundler-plugins/pull/165 changed how the bundler plugins are exported.
This PR updates the sourcemap upload docs accordingly.

Update bundler plugin docs to reflect new export structure

---

src/docs/product/accounts/quotas/manage-event-stream-guide.mdx

fix: replace typo in RateLimits section

---

src/platform-includes/session-replay/install/javascript.mdx
src/platforms/javascript/common/install/cdn.mdx

This updates the CDN usage docs to use the new full replay bundle by default, streamlining this.
While at it, I also reordered the "CDN installation" page generally a bit:
1. I moved the tracing bundle to top, as that is the default experience we want to provide.
2. After that, I added a new tracing + replay section
3. After that, there is the error only bundle
4. Moved the "Updates to naming scheme in SDK version 7" section further down, as it is not really very up to date anymore
Related to https://github.com/getsentry/sentry-docs/pull/6082, and dependent on https://github.com/getsentry/sentry-javascript/pull/6818.
Closes https://github.com/getsentry/sentry-javascript/issues/6573
Closes #5972

feat(replay): Update replay CDN usage docs

---

src/platform-includes/getting-started-primer/apple.mdx
src/platforms/apple/common/configuration/app-hangs.mdx
src/platforms/common/configuration/options.mdx

Replace remaining occurrences of out-of-memory with watchdog termination.

fix(apple): Replace OOM with watchdog termination

---

src/platforms/apple/common/configuration/watchdog-terminations.mdx

Explain that disabling the crash handler on Apple also disables the watchdog termination integration.

fix(apple): Disabling crashes disables watchdog

---

src/docs/product/issues/issue-details/performance-issues/main-thread-io.mdx

Okay maybe using the include is not quite right since there's an SDK note, but the reprocessing thing is definitely wrong, right? Anyway you tell me, feel free to just push to this PR or ignore it or whatever works 🙏🏻

Remove incorrect reprocessing text from IO issue

---

src/platforms/common/configuration/options.mdx
src/platforms/native/configuration/transports.mdx

The option for configuring HTTP proxies in the Native SDK is currently not reflected in the docs. I've added this to the transport page, which is presently a native-specific page because it makes sense due to their interaction. But it probably also makes sense to mention the option in `Basic Options` (where it would require a platform-specific description because it doesn't fit the description of the other platforms) under transport.
@Swatinem: should we place it in both or only one (and which one)? I am not sure the interface is complicated enough to warrant a separate "usage" section, but it doesn't feel wrong on the transport page.

fix(native): add missing description for proxy option

---

src/platforms/javascript/common/configuration/tree-shaking/index.mdx

`@sentry/trace` -> `@sentry/tracing`

fix: Typo in JS treeshaking docs

---

src/platform-includes/sourcemaps/upload/vite/javascript.mdx

Explanation here:
https://main.vitejs.dev/config/#environment-variables
AND I don't know but with Tailwind I add to do that also:
`releaseInjectionTargets: resolve(__dirname, 'src', 'main.js')`

fix: vite configuration for sourcemap

---

src/platforms/dart/migration.mdx
src/platforms/flutter/migration.mdx

https://github.com/getsentry/sentry-dart/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+milestone%3A7.0.0

Migration page for Dart and Flutter v7

---

src/platforms/node/common/configuration/integrations/pluggable-integrations.mdx

Previously, the documentation page for Node.js's "Pluggable Integrations" used the wrong import names and did not explain that the user must install a separate package. This commit fixes both of these issues.
[Vercel preview for the modified docs page.](https://sentry-docs-git-fork-dannynemer-patch-2.sentry.dev/platforms/node/configuration/integrations/pluggable-integrations/) …

docs(node): Add setup instructions for pluggable integrations

---

src/docs/product/issues/issue-details/performance-issues/index.mdx

Since this isn't a limitation, it doesn't make sense to keep it as part of this list. I suggest we move it into a note at the bottom of the page.

Move File IO out of list of limitations

---

src/platforms/common/configuration/options.mdx
src/platforms/node/common/configuration/integrations/default-integrations.mdx

ref https://github.com/getsentry/sentry-javascript/pull/6874
ref https://github.com/getsentry/sentry-javascript/pull/6876
resolves https://github.com/getsentry/sentry-docs/issues/6124
Document `includeLocalVariables` integration.
cc @timfish

feat(node): Update Node LocalVariables integration for new option

---

src/docs/product/profiling/getting-started.mdx

Before, Node.js, Python and Rust were listed in the "Mobile" Category

Added Server category in Profiling Getting Started

---

src/docs/product/issues/issue-details/performance-issues/index.mdx

Resolves PERF-1940
As more performance issues arise, we should have a more clear way to breakdown all the available issue types by category. 
- The categories used match the categories seen when you create a new project in sentry.
- I’m not sure if I completely like the duplicated server and serverless entries, but I think it’s better to stay consistent with the categories we have.
- I omitted Desktop and Other as they currently don't have detectors (correct me if i'm wrong)

feat(perf-issues): Add table to root performance issue docs

---

src/platforms/common/configuration/options.mdx

Document `traceOptionsRequests` option.
Need to wait for https://github.com/getsentry/sentry-java/pull/2453 to land.

Add docs for `traceOptionsRequests`

---

src/docs/product/issues/issue-details/performance-issues/n-one-api-calls.mdx

Lots of people (customers, PMs, SEs, and others) have asked us to clarify this aspect of the detector, so they can have a better idea of when this might affect them.

fix(n1-api-calls): Clarify affected platforms

---

src/components/hooks/usePlatform.tsx

Sorts `.NET` as `NET`
| ----------- | ----------- |
| ![old](https://user-images.githubusercontent.com/6349682/215562693-3b993b24-c8fb-4603-a9e0-ec1ae80e0fde.gif)      | ![new](https://user-images.githubusercontent.com/6349682/215562697-49aed2cb-0246-4ad8-b5ff-37942f5232f1.gif)       |

feat: order platforms by their natural name

---

src/platforms/unity/migration.mdx

I added a section for the breaking changes in the `0.28.0` release.
Additionally, I flipped the entries around to go from newest to oldest.

feat(unity): Updated migration

---

src/platform-includes/enriching-events/attach-screenshots/unity.mdx

The Unity SDK does not simply "capture a screenshot" but instead captures what is currently visible on screen from there game's perspective. This means that overlays from native plugins won't be visible on the screenshot. Which is important for PII reasons.

fix(unity): Screenshot capture mechanim

---

src/docs/product/session-replay/index.mdx
src/includes/beta-note-session-replay.mdx

replay links in notes to get to frameworks specific docs easier

add platform links to beta note

---

src/platforms/javascript/common/session-replay/troubleshooting.mdx

Aligns with Performance that has its own troubleshooting doc at the root

replay: move troubleshooting page

---

src/platforms/apple/common/migration.mdx

We decided to remove the master branch from the GH repo, as users pointing to it won't notice that we migrated to the main branch. Pointing to the master branch is considered a bit experimental cause you always point to the latest changes without relying on official SDK releases.

fix(apple): Remove master branch from migration

---

src/platform-includes/enriching-events/attach-screenshots/unity.mdx

Went into more detail on the difference of which SDK tries to capture a screenshot.

fix(unity): Native screenshots

---

src/platform-includes/enriching-events/attach-viewhierarchy/android.mdx
src/platform-includes/getting-started-primer/android.mdx
src/platforms/common/configuration/options.mdx
src/platforms/common/enriching-events/viewhierarchy.mdx

Add documentation on how to enable the View Hierarchy feature for Android.
Our `sentry-java` needs to be shipped first before merging this, will probably be part of the `6.12.0` release.

feat(Android): Add docs for View Hierarchy

---

src/docs/product/integrations/deployment/heroku/index.mdx

Update the Heroku docs to include a line about copying the webhooks signing secret into your Sentry plugin configuration, as well as some small cleanups that confused me when I read through it.

ref(heroku): Update Heroku docs

---

src/platforms/common/configuration/options.mdx

https://develop.sentry.dev/sdk/features/#local-variables
develop docs say it should be `true` but maybe better that it should say "encouraged to be true". We opted not to for sensitive data concerns. But this is a minor point

Need to set true boolean

---

src/platforms/android/configuration/integrations/timber.mdx

Came up here https://github.com/getsentry/sentry-java/issues/2468, and apparently, we do not have an easy way to disable the timber integration, but keep using other auto-installation features. This is a workaround for now, until we implement the proper solution https://github.com/getsentry/sentry-android-gradle-plugin/issues/426

chore(android): Clarify how to disable Timber integration

---

src/platforms/javascript/guides/nextjs/manual-setup.mdx

Ref: https://github.com/getsentry/sentry-javascript/issues/7061#issuecomment-1418964265

Clarify that Next.js `tunnelRoute` option does not work with self-hosted

---

src/platforms/dotnet/common/configuration/msbuild.mdx

Remove `SentryIncludeIntermediateOutputPath`.  This was available only briefly. The default behavior is now to always use the `obj` folder.

Update dotnet msbuild page

---

src/docs/product/cli/dif.mdx
src/platforms/android/common/proguard.mdx

Hey guys 👋 
I enabled R8 in our Android app and found that the docs around this can be more precise.
So here we are 🙂 
I updated the Android -> Proguard page which includes a rough overview about how deobfuscating works.
I also updated the cli manual by reordering the examples.
It was abit missleading that you first explain "upload with UUID" and **afterwards** set it into the `AndroidManifest`.
Because the `AndroidManifest` needs the UUID **first**, otherwise you can't use the same UUID as the APK doesn't contain that UUID 🙃. And if you then add the UUID and build again *you might* have another mapping file and you have to upload the new mapping file again ♻️ . I hope you get the point 😬 
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in …

Update proguard docs

---

src/platforms/java/guides/spring-boot/webflux.mdx

Closes #6020 by directing users to use OpenTelemetry for WebFlux performance.

Mention OTEL for WebFlux performance

---

src/platform-includes/getting-started-config/ruby.mdx

fix(ruby): Add explicit require in main getting started sample

---

src/platforms/common/performance/instrumentation/opentelemetry.mdx

It can be a little overwhelming to see the wall of text when trying to set up the SDK. In order to make this process as easy as possible, move our description of span transformation to the bottom of the page, so users can still read it after they completed the installation process.

feat(otel): Move otel <-> Sentry transformation description to bottom of page

---

package.json
sentry.config.js
src/gatsby/config.ts
yarn.lock

Update to use https://docs.sentry.io/platforms/javascript/guides/gatsby/#sentry-configuration-file, so we can use the Replay integration.
I'm going to remove the plugin config docs, since folks should not be using this anymore (and add a deprecation message as well).

Add Session Replay to Sentry docs

---

src/docs/product/issues/issue-details/performance-issues/consecutive-db-queries/index.mdx

A new threshold has been added to consec db detector recently, this PR documents the new threshold.

feat(perf-issues): document new threshold for consecutive db detector

---

src/css/_includes/type.scss

I haven't checked all the tables but here is the one I did check
https://sentry-docs-git-ref-table-border.sentry.dev/api/permissions/#organizations
It should apply to all tables
Before:
After:

ref: Add full border to table

---

sentry.config.js

As per https://www.gatsbyjs.com/docs/how-to/local-development/environment-variables/#accessing-environment-variables-in-the-browser
Also removing debug mode, woops!

fix: Use correct gatsby env variables

---

src/wizard/javascript/nextjs.md

Explicitly installing the sentry package is no long necessary with the wizard

fix(nextjs): move installation instructions

---

src/docs/product/accounts/sso/okta-sso/okta-scim.mdx

From Rodolfo:
> From the docs we cannot provision owners via SCIM, but this note is only under Configuring Organization-level Roles, which makes thing confusing as SCIM can (and will) remove owners from organisation if they are deprovisioned in the IdP.
> i managed to remove owners using the SCIM api with no problem:
> Can we can it be clarified in the docs and/or prevent it from happening?

feat(scim): clarify that you can deprovision owners

---

src/platform-includes/getting-started-install/react-native.mdx

The link in our docs doesn't exist anymore.

Remove non existing link to our Expo troubleshooting page

---

src/platforms/python/common/troubleshooting.mdx

* clarify new `AsyncioIntegration`
* Remove channels clarification since it adds to confusion
resolves #6261

fix(python): Remove legacy channels section from Troubleshooting

---

src/platform-includes/session-replay/install/javascript.mdx
src/platform-includes/session-replay/setup/javascript.mdx
src/platforms/javascript/common/install/cdn.mdx
src/platforms/javascript/common/session-replay/configuration.mdx

This updates the replay installation/configuration docs with some of the recent changes/additions to the Replay CDN bundles.
With version 7.37.0:
* We now have an errors+replay CDN bundle, so we mention it in the Replay setup page
* We also list it in the Sentry JS SDK installation page
* We update the namespace of the `Replay` integration so that people always use `Sentry.Replay` instead of `Sentry.Integrations.Replay`. Note: This change is backward-compatible, so people who previously used `Sentry.Integrations.Replay` will not be impacted.  
closes #6263

ref(replay): Update Replay CDN bundle descriptions

---

src/platform-includes/enriching-events/set-user/rust.mdx

The old code snippet wouldn't compile, so this is a fix.

fix(rust): fix rust code for identify-users

---

src/platforms/python/common/configuration/integrations/asyncio.mdx
src/platforms/python/common/configuration/integrations/index.mdx

Added missing documentation for the `asyncio` integration in the Python SDK.
NEW docs:
https://sentry-docs-git-antonpirker-python-asyncio-integration.sentry.dev/platforms/python/configuration/integrations/asyncio/

feat(Python): Added docs for Python `asyncio` integration

---

src/platforms/dotnet/common/configuration/msbuild.mdx

Show both new and old URL formats for the org/project slug example.

Update URL format in MSBuild doc

---

src/css/_includes/content.scss

there is a `.content` class style for padding being applied to parts of highlighted code in example blocks, so making this style specific to divs, as I believe that's the intent of it. I'm also not sure this class is being used in our docs anyway.

making content class more specific
