getsentry/sentry-docs

- src/platforms/javascript/common/session-replay/index.mdx
> feat(replay): Add note about potential Angular performance impact

- src/docs/product/crons/getting-started.mdx
> ref(crons): Update URLs for hybrid cloud

- src/platforms/javascript/common/session-replay/troubleshooting.mdx
This PR adds a note to the Replay Troubleshooting guide that SVGs with cross-origin-link `<use>` tags cannot be shown in the replayer due to a browser limitation.
ref: https://github.com/getsentry/sentry-javascript/issues/7020
> ref(replay): Add note about SVG `<use>` CORS limitations

- src/platform-includes/getting-started-primer/flutter.mdx
- src/platform-includes/getting-started-primer/javascript.cordova.mdx
- src/platform-includes/getting-started-primer/react-native.mdx
Offline caching functionality for iOS and Android behave differently; reports are retried under slightly different conditions. This is already clear in the respective iOS and Android docs:
- [iOS](https://docs.sentry.io/platforms/apple/guides/ios/): "Offline caching when a device is unable to connect; we send a report once we receive another event"
- [Android](https://docs.sentry.io/platforms/android/): "Offline caching when a device is offline; we send a report once the application is restarted"
However, the [Flutter docs](https://docs.sentry.io/platforms/flutter/) are vague about how offline caching works in a way that has confused at least one customer. This change clarifies how offline caching works for Flutter.
> Clarify offline caching behavior of Flutter SDK

- src/platforms/javascript/common/performance/instrumentation/automatic-instrumentation.mdx
This depends on https://github.com/getsentry/sentry-javascript/pull/6837 being released in 7.32.0.
> feat: Update `enableLongTask` docs

- src/platforms/javascript/common/session-replay/configuration.mdx
https://github.com/getsentry/sentry-javascript/pull/6878 altered on version 7.33.0 the default to 0 but the docs still point as if the default was 1.0
> Update Replay README.md wrong default values

- src/platforms/javascript/common/session-replay/index.mdx
Very little testing went into Capacitor and we still have issues such as: https://github.com/getsentry/sentry-capacitor/issues/318
For that reason we'll keep Capacitor-only still in Beta until we get more validation.
To track GA: https://github.com/getsentry/sentry-capacitor/issues/319
> replay: capacitor continue in beta

- src/docs/product/sentry-basics/search/searchable-properties.mdx
We recently made some changes to search to include some additional searchable properties. Updating the docs to reflect those changes.
> doc(search): update searchable properties to include functionality reflected in search

- src/docs/product/issues/issue-details/performance-issues/consecutive-db-queries/index.mdx
Now that we're in GA, i've added the current thresholds to the doc.
> feat(perf-issues): Add consec db thresholds to docs

- src/platform-includes/enriching-events/breadcrumbs/automatic-breadcrumbs/apple.mdx
Added UIControl events to the list of automatic breadcrumbs created by the SDK.
> feat(apple): Automatic breadcrumb for UIControl events

- src/platform-includes/performance/enable-tracing/react-native.mdx
- src/platform-includes/performance/tracePropagationTargets-example/react-native.mdx
> Fix tracingOrigins was renamed to tracePropagationTargets

- src/docs/product/session-replay/protecting-user-privacy.mdx
Modifies the "Protecting User Privacy" page under Session Replay:
* Adds a Privacy & Legal FAQ
* Adds some new intro paragraphs
* Adds a new heading, "How Session Replay Approaches Data Capture", to the previous content
> feat(replays): Add privacy & legal FAQ, plus additional edits

- src/docs/product/session-replay/protecting-user-privacy.mdx
This placeholder was accidentally left in.
> fix(replay): Fix bad unblock classname in privacy docs

- src/platform-includes/configuration/offline/javascript.mdx
- src/platforms/javascript/common/configuration/integrations/plugin.mdx
- src/platforms/javascript/common/configuration/transports.mdx
This PR:
- Removes reference to the `Offline` integration since this will be deprecated
- Add a `Transports` section to the JavaScript configuration
- Excludes this from sub-plartforms which already have their own specialised offline support
- Documents how to use `makeBrowserOfflineTransport` to create an offline transport
Does this need separate platform includes with differing imports for Angular/React/etc/etc?
> feat(browser): Add offline transport docs

- src/platforms/python/common/configuration/integrations/pymongo.mdx
> Fix typo MonogDB to MongoDB

- src/platforms/apple/common/performance/instrumentation/swiftui-instrumentation.mdx
Updated the docs on how to install SentrySwiftUI to include cocoapod.
> feat(Apple): SentrySwiftUI from cocoapod

- src/platforms/node/common/performance/database/opt-in.mdx
Docs PR for https://github.com/getsentry/sentry-javascript/pull/7194
Only merge in once the above has been released.
> feat(node): Add docs for Apollo NestJS flag

- src/platforms/common/data-management/debug-files/symbol-servers.mdx
We recommend using lowercased directories and filenames but not using the lowercased path casing for symbol lookups. When combining this with the default (Mixed-case) we see many issues with missing symbols.
> clarify s3 instructions

- src/components/expandable.tsx
- src/components/markdown.tsx
- src/css/_includes/alert.scss
- src/css/_includes/expandable.scss
- src/css/screen.scss
- src/platform-includes/getting-started-config/android.mdx
- src/platform-includes/getting-started-install/android.mdx
- src/platform-includes/getting-started-primer/android.mdx
- src/platforms/android/manual-configuration.mdx
- src/platforms/android/using-ndk.mdx
- src/platforms/common/index.mdx
- src/wizard/android/index.md
Our Android SDK docs entry point is quite overwhelming. This is an attempt to make the "Getting Started" section more concise and easy to consume. Less text, more value 😉 
- Provide better default SDK configuration
- Split up automatic/manual configuration, choosing between those two is probably hard in the beginning. Let's default to automatic, as we can provide more value here
- Simplify first steps / remove huge text walls
- Added basic expandable widget to highlight recent changes (#5748)
> feat(android): Improve Android SDK docs entry point

- src/platforms/react-native/manual-setup/manual-setup.mdx
The text note that the configuration must be before the `apply` call can be easily overlooked. 
Showing the code with the `apply` ensures the correct order when users copy the code snippets.
Context: https://discord.com/channels/621778831602221064/750735628932612096/1076132995494326322
> Add `sentry.gradle` to all RN manual examples

- src/docs/product/data-management-settings/scrubbing/advanced-datascrubbing.mdx
Add the mention about how and what to escape in the regexes. 
related: https://github.com/getsentry/relay/issues/1836
> chore(regex): Add note about escaping punctuation characters

- src/platform-includes/getting-started-install/apple.ios.mdx
- src/platform-includes/getting-started-install/apple.mdx
- src/platforms/apple/common/install/cocoapods.mdx
- src/wizard/apple/index.md
- src/wizard/apple/ios.md
- src/wizard/apple/macos.md
Since Cocoa 8.0.0 the min iOS version is 11, so we can bump it for the podfiles as well.
Follow up on https://github.com/getsentry/sentry-docs/pull/6334.
> fix(apple): Replace iOS 9 with 11 for pods

- src/platforms/apple/common/performance/instrumentation/swiftui-instrumentation.mdx
SentrySwiftUI instead of SentrySwifUI.
> fix(apple): Typo for SwiftUI for CocoaPods

- src/platforms/node/common/performance/database/opt-in.mdx
Since I'm already working on docs today, this PR adds a quick note around a limitation of our `Apollo` integration.
I don't have a lot of context around this integration, so not sure if we can offer an alternative path what to do to get the integration working.
closes #6346
> ref(node): Mention limitation around Apollo intergation

- src/platforms/javascript/common/session-replay/configuration.mdx
Before stopping recording manually, users should flush one more time to not loose any recording data before the `stop` call.
This came up in https://github.com/getsentry/sentry-javascript/issues/7255
> ref(replay): Flush before manually stopping recording

- src/platforms/common/profiling/index.mdx
- src/wizard/rust/profiling-onboarding/rust/1.install.md
This should make it possible to paste the snippet directly into the config. Config.toml requires that rust version should be a string.
> Add quotes around rust crate version

- src/platform-includes/capture-error/javascript.angular.mdx
- src/platform-includes/enriching-events/import/javascript.angular.mdx
- src/platform-includes/getting-started-config/javascript.angular.mdx
- src/platform-includes/getting-started-install/javascript.angular.mdx
- src/platform-includes/getting-started-verify/javascript.angular.mdx
- src/platform-includes/performance/configure-sample-rate/javascript.mdx
- src/platform-includes/performance/enable-automatic-instrumentation/javascript.mdx
- src/platforms/javascript/guides/angular/features/component-tracking.mdx
- src/wizard/javascript/angular.md
- src/wizard/javascript/replay-onboarding/angular/1.install.md
- src/wizard/javascript/replay-onboarding/angular/2.configure.md
To ensure first-class compatibility with Angular's "new" rendering engine, Ivy, we needed to create a new SDK package that's compiled differently than the original `@sentry/angular` package. This new SDK is compatible with Angular 12 and newer and hence we're going to make it the default SDK in the docs going forward.
This PR 
* Updates the Angular version <-> Sentry SDK compatibility description with a table
* I added entries for Angular 1/AngularJS (this came up recently in a Slack convo) and Angular 2-9 with a message that we do not support these versions anymore in v7 of the SDKs. Happy to make changes here if reviewers think this shouldn't be promoted.
* Updates imports and code snippets with versions for Angular 12+ (ivy) and Angular 10/11
* Updates the SDK onboarding wizard docs (+ …
> ref(angular): Update Angular SDK docs for `@sentry/angular-ivy`

- src/platforms/python/guides/arq/index.mdx
Docs for https://github.com/getsentry/sentry-python/pull/1872
- added guide for ARQ
> Docs for ARQ integration

- src/docs/product/alerts/create-alerts/metric-alert-config.mdx
Adds some documentation to explain which fields are available for metric alert filters, and what happens if you try to use an unavailable filter.
> docs(metric-alerts): Explain available search properties

- src/platforms/apple/common/performance/instrumentation/automatic-instrumentation.mdx
This PR removes a sentence that wrongly suggests that transactions will be created for network spans if there isn’t one on the scope.
> ref(apple): Remove misleading wording wrt network transaction generation

- src/platforms/common/profiling/index.mdx
- src/wizard/python/profiling-onboarding/python/1.install.md
1.16.0 contains some bug fixes that ensure things work out of the box on more configurations.
> chore(docs): Bump min python sdk for profiling to 1.16.0

- src/platforms/node/guides/gcp-functions/index.mdx
- src/wizard/node/gcpfunctions.md
Just noticed that in our onboarding wizard, we had docs that assumed that source code tabs would be available which - unfortunately - they are not. This PR just adds headings instead for the three different kinds of GCP functions. 
Also it slightly renames the tab title in the actual docs page for GCP functions.
> ref(serverless): Improve GCP functions onboarding wizard and docs

- src/components/search.tsx
Send analytics tags so we can distinguish from different sources of traffic in algolia analytics
> feat(algolia): send analytics tags

- src/docs/product/projects/index.mdx
- src/docs/product/releases/health/index.mdx
- src/docs/product/releases/index.mdx
- src/platform-includes/getting-started-install/apple.watchos.mdx
- src/platform-includes/getting-started-primer/apple.mdx
- src/platforms/apple/common/configuration/app-hangs.mdx
- src/platforms/apple/common/configuration/integrations/default.mdx
- src/platforms/apple/common/migration.mdx
- src/platforms/common/configuration/releases.mdx
We have some features that aren't available on watchOS due to hardcoded limitations (see https://github.com/getsentry/sentry-cocoa/issues/406#issuecomment-1171872518), so call out the features that rely on the unavailable API in the docs to make sure customers are aware.
Also related to https://github.com/getsentry/sentry-cocoa/issues/2726
> update some feature lists for lack of watchOS support

- src/platform-includes/getting-started-config/javascript.vue.mdx
- src/wizard/javascript/vue.md
This PR updates the Vue SDK getting started and wizard docs:
Following https://github.com/getsentry/sentry-javascript/pull/7310 where we flipped the default value of `logErrors` from `false` to `true`, this PR updates the docs accordingly and removes the IMO now obsolete warning regarding the SDK supressing error logs by default.
> ref(vue): Update `logErrors` description

- src/platforms/flutter/migration.mdx
Updates the migration page for Dart/Flutter for the dio integration
cc @marandaneto 
> Update Sentry Flutter migration page for dio 

- src/platforms/flutter/migration.mdx
https://github.com/getsentry/sentry-dart/pull/1276/
> The `enableNdkScopeSync` feature is now enabled by default.

- src/platforms/node/common/performance/instrumentation/automatic-instrumentation.mdx
- src/platforms/node/guides/express/performance/automatic-instrumentation.mdx
- src/platforms/node/guides/express/performance/index.mdx
- src/platforms/node/guides/express/performance/instrumentation/automatic-instrumentation.mdx
Currently, the auto instrumentation docs for Node.js are actually manual instrumentation docs, as we don't really have a lot of auto-instrumentation there.
Also, for express we just re-use the auto-instrumentation docs, even though we actually _have_ auto instrumentation there.
Closes https://github.com/getsentry/sentry-docs/issues/6377
> feat: Improve docs for node & express auto instrumentation

- src/platforms/android/common/performance/instrumentation/automatic-instrumentation.mdx
I just renamed reportFullDisplayed to reportFullyDisplayed, as it was updated in code, too.
It's more correct in english
> renamed reportFullDisplayed to reportFullyDisplayed

- src/platforms/react-native/performance/instrumentation/automatic-instrumentation.mdx
- https://github.com/getsentry/sentry-react-native/pull/2855
> Add app start measurements naming note

- src/docs/product/sentry-basics/search/searchable-properties.mdx
The `unreal.crash_type` based on Unreals enum is now searchable.
> chore(unreal): Add `unreal.crash_type` to properties table 

- src/platforms/flutter/troubleshooting.mdx
cc @vaind 
Relates to https://github.com/getsentry/sentry-dart/issues/132
> Dart source context troubleshooting

- src/platforms/javascript/guides/vue/configuration/integrations/vue-router.mdx
Update the docs for the new vue router option from here: https://github.com/getsentry/sentry-javascript/pull/7326
!! Only merge this when the next JS SDK version is released!
Note that I've also removed some boilerplate code, to make this page a bit clearer IMHO.
> feat: Update vue router docs for new option

- src/docs/product/releases/setup/release-automation/netlify/index.mdx
This does some minor wordsmithing to our docs on the Netlify integration, and adds a note about the difference between it and the new Netlify-built sentry plugin.
Ref: WOR-2818
> ref(integrations): Add note about `@netlify/sentry` to Netlify plugin docs

- src/components/pageGrid.tsx
- src/platform-includes/sourcemaps/overview/javascript.angular.mdx
- src/platform-includes/sourcemaps/upload/primer/javascript.angular.mdx
- src/platforms/javascript/common/sourcemaps/uploading/angular-webpack.mdx
This PR adds a new source maps upload guide to our Angular SDK docs: Users can make use of the Angular CLI and the Sentry Webpack plugin to upload source maps. This requires a custom Angular builder. Changes:
* Add a tutorial for Angular CLI + Webpack plugin
* Add Angular-specific source maps overview and source maps uploading index page
* Let the `PageGrid` component accept an `exclude` prop to exclude certain entries from being displayed
* Otherwise we show source maps upload option twice, once in the "recommended" section and once in the "other options" section of the uploading index page. 
closes #6326
> feat(angular): Add Angular CLI + Webpack Plugin sourcemaps upload guide

- src/platforms/react-native/manual-setup/manual-setup.mdx
fixes: https://github.com/getsentry/sentry-react-native/issues/2886
> Fix xcode bundle build phase sentry properties path

- src/platforms/python/common/performance/instrumentation/custom-instrumentation.mdx
- src/wizard/python/tracing.md
Made it easier comprehensible (less special words) 
Also added the new way of adding spans (with the decorator)
Before:
https://docs.sentry.io/platforms/python/performance/instrumentation/custom-instrumentation/
Now:
https://sentry-docs-git-antonpirker-performance-custom-instrumentation.sentry.dev/platforms/python/performance/instrumentation/custom-instrumentation/
> [Python] Improve "custom instrumentation" docs

- src/docs/clients/javascript/sourcemaps.mdx
- src/docs/clients/node/sourcemaps.mdx
Ben P. mentioned these links were broken, so this PR fixes that. However, they're linking to a super old blog post. 
It may be better to link to https://docs.sentry.io/platforms/javascript/sourcemaps and https://docs.sentry.io/platforms/node/sourcemaps (respectively), or a newer blog post instead.
> fix links to sourcemaps blog post

- src/platforms/dotnet/common/compatibility.mdx
- .NET Core 3.1 is no longer supported by Microsoft
- Don't make recommendations beyond using supported versions
- Link to official Microsoft support policies
- Cleanup wording
> Update .NET compatibility details

- src/platforms/common/enriching-events/viewhierarchy.mdx
Updating the platform support note to call out that deobfuscation for Flutter currently isn't supported and we will update if there are any changes in the future.
> feat(view-hierarchy): Update platform support note

- src/platform-includes/performance/opentelemetry-setup/node.mdx
ref https://github.com/getsentry/sentry-javascript/issues/7538
Update these docs based on work in https://github.com/getsentry/sentry-javascript/pull/7548
Passing in a propagator in the otel SDK constructor is more correct than using the `setGlobalPropagator` API.
> Update otel node propagator instructions

- src/platforms/unity/troubleshooting.mdx
I dunno the APIs by heart so would appreciate review.
Should we point out `Debug.LogException` too? Any other API?
> unity: note on concat exceptions

- src/platforms/apple/common/performance/instrumentation/automatic-instrumentation.mdx
Remove the yet for NSURLConnection to clarify that we don't have plans to support it.
> fix(apple): Clarify no support for NSURLConnection

- src/docs/product/sentry-basics/migration/index.mdx
This updates the docs to use the most up to date backup scripts for self-hosted sentry
> Update self-hosted backup instructions

- src/platforms/react-native/manual-setup/manual-setup.mdx
I think there is a mistake in the iOS symbols upload script at https://docs.sentry.io/platforms/react-native/manual-setup/manual-setup/#upload-debug-symbols-to-sentry.
By using it "as is" it will upload nothing and yield "Warning: No paths were provided."
To get it working I needed to add the path to my built .app so it can look for files to upload.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's …
> fix(react-native): add missing argument for ios debug symbols upload

- src/platform-includes/capture-error/apple.mdx
Clarify that using custom error descriptions don't impact grouping.
> fix(apple): Custom error descr no grouping impact

- .github/PULL_REQUEST_TEMPLATE.md
Modify the PR template to add a checklist. The main objective is to remind/encourage internal contributors to get the proper reviews before merging their own PRs.
> Add pr checklist for docs

- src/platforms/common/configuration/options.mdx
- src/platforms/python/common/performance/instrumentation/custom-instrumentation.mdx
This is a new feature in the Python SDK to have a central place to define which functions should be performance instrumented.
See feature implementation: https://github.com/getsentry/sentry-python/pull/1960
> Added docs for "functions_to_trace" option.

- src/platform-includes/performance/configure-sample-rate/node.mdx
- src/platform-includes/performance/enable-tracing/node.mdx
- src/platforms/node/common/performance/database/auto-instrument.mdx
- src/platforms/node/common/performance/database/index.mdx
- src/platforms/node/common/performance/database/opt-in.mdx
- src/platforms/node/common/performance/instrumentation/automatic-instrumentation.mdx
- src/platforms/node/common/profiling/index.mdx
- src/platforms/node/guides/express/index.mdx
- src/platforms/node/guides/express/performance/index.mdx
- src/platforms/node/guides/express/performance/instrumentation/automatic-instrumentation.mdx
- src/platforms/node/guides/koa/index.mdx
- src/platforms/node/guides/serverless-cloud/index.mdx
ref https://github.com/getsentry/sentry-javascript/issues/5815 and #6518
This PR updates our instructions to remove the dependency on using the `@sentry/tracing` package for the node.js SDK and its derivatives. The node.js SDK now enables tracing support by default and the tracing integrations are now available on the `Integrations` namespace.
Before:
```ts
import * as Sentry from '@sentry/node';
import '@sentry/tracing';
Sentry.init({
dsn: '__DSN__',
tracesSampleRate: 1.0,
});
```
```ts
import * as Sentry from '@sentry/node';
import * as Tracing from '@sentry/tracing';
Sentry.init({
dsn: '__DSN__',
tracesSampleRate: 1.0,
integrations: [new Tracing.Integrations.Postgres()],
});
```
After:
```ts
import * as Sentry from '@sentry/node';
Sentry.init({
dsn: '__DSN__',
tracesSampleRate: 1.0, …
```
> Remove references to `@sentry/tracing` for node performance

- src/docs/product/issues/issue-details/performance-issues/large-render-blocking-asset/index.mdx
- src/platform-includes/getting-started-config/node.mdx
- src/platform-includes/getting-started-install/node.mdx
- src/platform-includes/performance/connect-services/node.mdx
- src/platforms/common/performance/index.mdx
- src/platforms/javascript/common/install/lazy-load-sentry.mdx
- src/wizard/javascript/react/with-error-monitoring-and-performance.md
- src/wizard/javascript/react/with-error-monitoring-performance-and-replay.md
- src/wizard/node/express.md
- src/wizard/node/index.md
- src/wizard/node/serverlesscloud.md
While merging in https://github.com/getsentry/sentry-docs/pull/6523 and https://github.com/getsentry/sentry-docs/pull/6508 we missed some instances of `@sentry/tracing`. This comes back and cleans them up.
> Remove last references to `@sentry/tracing`

- src/platforms/node/common/configuration/integrations/default-integrations.mdx
Given https://github.com/getsentry/sentry-javascript/issues/7230 merging in and getting release, let us bump the min node version required here so that users use a version that has no memory leak issues.
> feat(node): Bump LocalVariables min version to 7.46.0

- src/platform-includes/getting-started-config/javascript.react.mdx
- src/wizard/javascript/react/index.md
Closes [#6542](https://github.com/getsentry/sentry-docs/issues/6542)
> feat(react): Update docs to React 18 instructions

- src/platforms/android/common/performance/instrumentation/automatic-instrumentation.mdx
- src/platforms/apple/common/performance/instrumentation/automatic-instrumentation.mdx
Added documentation for TTID and TTFD spans during view controller automatic transactions.
This docs should not be merged before [this PR](https://github.com/getsentry/sentry-cocoa/pull/2724).
> feat(apple): Time to Initial display and Time to Full display measurement

- src/docs/product/user-feedback/index.mdx
1. React Native actually supports it
During the platform selection flow we'll show in case something isn't supported. 99% people getting here will pick a supported platform so not worth having Perl and Native there
> user feedback remove note unsupported

- src/platforms/common/profiling/index.mdx
- src/platforms/javascript/common/install/cdn.mdx
- src/platforms/node/common/profiling/index.mdx
- src/wizard/node/profiling-onboarding/node/1.install.md
- src/wizard/node/profiling-onboarding/node/2.configure-performance.md
- src/wizard/node/profiling-onboarding/node/3.configure-profiling.md
Also runs code through prettier - so formatting has changed slightly.
> Remove @sentry/tracing from profiling node instructions

- src/docs/product/issues/issue-details/suggested-fix/index.mdx
Link was pointing always to `sentry-sdks`. This PR makes it dynamically according to the user org
> fix(ai): Update docs link to redirect to the correct org

- src/platform-includes/performance/configure-sample-rate/javascript.electron.mdx
- src/platform-includes/performance/enable-automatic-instrumentation/javascript.electron.mdx
After updating to the latest JavaScript SDKs, users no longer need to use `@sentry/tracing` with the Electron SDK to support performance.
> feat(electron): Remove references to `@sentry/tracing` for Electron SDK

- src/platforms/elixir/configuration/options.mdx
Updates the documentation to reflect the option `in_app_module_whitelist` was renamed to `in_app_module_allow_list` in https://github.com/getsentry/sentry-elixir/blob/master/CHANGELOG.md#805-2021-02-14.
The elixir sentry sdk warns if you use the old option.
> Update options.mx  - deprecated option fix

- src/platforms/javascript/guides/react/configuration/integrations/react-router.mdx
This adds a comment about how you don't need to wrap *all* the Routes in RRv6, as compared to needing to wrap every Route in RRv5.
Another question I have is whether you need to use SentryRoutes if you're already using `sentryCreateBrowserRouter`, or are those mutually exclusive options? …
> React Router: Add info about wrapping Routes

- src/platform-includes/crons/setup/python.celery.mdx
- src/platform-includes/crons/setup/python.mdx
We have a new feature that allows Celery Beat periodic tasks to be automatically monitored with Sentry Crons.
Only release this, when the feature itself was released.
PR for the feature: https://github.com/getsentry/sentry-python/pull/1967
> Added documentation for Celery Beat auto monitoring

- src/docs/product/crons/getting-started/cli.mdx
Adding the following lines to authenticate cron checkins
```
[defaults]
auth.dsn = MY_DSN
```
results in a warning message in the CLI:
```
WARN    2023-04-04 14:54:48.791431 +02:00 Token auth is deprecated for cron monitor checkins. Please use DSN auth.
```
The correct syntax that removes the warning is:
```
[auth]
dsn = MY_DSN
```
> fixing sentryclirc auth sintax

- src/platform-includes/performance/connect-errors-spans/apple.mdx
- src/platforms/common/performance/instrumentation/custom-instrumentation.mdx
Added information on how to connect errors with spans.
Related to https://github.com/getsentry/sentry-cocoa/issues/1324
> feat(apple): Connect Errors with Spans

- src/platform-includes/enriching-events/user-feedback/sdk-api-example/javascript.mdx
- src/platforms/common/enriching-events/user-feedback.mdx
fixes https://github.com/getsentry/sentry-docs/issues/6602
We released the User Feedback API in https://github.com/getsentry/sentry-javascript/releases/tag/7.47.0, this PR adds docs for it.
Thanks for the reminder @sdzhong!
> Add docs for JS browser user feedback API

- src/docs/product/alerts/create-alerts/metric-alert-config.mdx
It's pretty easy to miss the limitations on filtering for transactions, trying to make it a bit easier to spot.
> Highlight limitations of transaction filters

- src/docs/product/sentry-basics/search/searchable-properties.mdx
Added a note about the limited number of properties one can search for when configuring a filter in a performance metric alert.
> Note for Alerts

- src/docs/product/integrations/issue-tracking/jira/index.mdx
This adds a troubleshooting entry to the Jira integration docs covering a hurdle I ran into when setting up the integration.
Ref: WOR-2928
> fix(jira): Add note about assignable user permissions

- src/platforms/react-native/troubleshooting.mdx
This fixes a minor typo in one of the troubleshooting steps. Xcode Cloud was misspelled as "Xcode Could"
- [Sentry …
> Fix typo in Xcode Cloud troubleshooting

- src/platform-includes/sourcemaps/upload/cli/javascript.mdx
This PR adds the Sentry Javascript SDK version to new sourcemaps docs.
> fix(sourcemaps): Add clarification for javascript SDK version

- src/platforms/javascript/common/troubleshooting/index.mdx
Broken link has been updated
The hyperlink to Chrome's docs on "Ignore Chrome Extensions scripts" was broken and has been updated.
> Fix broken link to Framework Ignore List

- src/docs/product/accounts/quotas/manage-event-stream-guide.mdx
- src/platform-includes/configuration/ignore-errors/javascript.mdx
- src/platform-includes/configuration/ignore-transactions/javascript.mdx
- src/platforms/common/configuration/filtering.mdx
- src/platforms/common/configuration/options.mdx
- src/platforms/javascript/common/configuration/integrations/default.mdx
- src/platforms/node/common/configuration/integrations/default-integrations.mdx
This adds proper docs for `ignoreErrors` & `ignoreTransactions` as ways to filter events.
I've only added them for JavaScript for now, but I believe it also exists for other languages already - we may also add these then?
> feat: Add docs for `ignoreErrors` & `ignoreTransactions`

- src/platforms/node/common/configuration/integrations/pluggable-integrations.mdx
Waiting on a fix + release (https://github.com/getsentry/sentry-javascript/pull/7802) before adding the version number.
> Add node docs for tRPC middleware

- src/platforms/node/common/configuration/async-context.mdx
- src/platforms/node/guides/express/index.mdx
- src/platforms/node/guides/express/performance/index.mdx
- src/platforms/node/guides/express/performance/instrumentation/automatic-instrumentation.mdx
- src/platforms/node/guides/koa/index.mdx
- src/platforms/node/guides/serverless-cloud/index.mdx
- src/wizard/node/express.md
- src/wizard/node/serverlesscloud.md
ref https://github.com/getsentry/sentry-javascript/issues/7691
ref https://github.com/getsentry/sentry-javascript/pull/7817
In the new upcoming version of the Node SDK, we now expose an API allowing users to isolate their requests to prevent breadcrumbs/tags/spans from leaking across requests. This PR documents that.
Before users had to manually use Node's domains API to do this, but now we've abstracted this away from them. To make this easier, we've updated the Koa docs to stop using domains directly, but instead use the new `runWithAsyncContext` API.
Note: only merge when `7.48.0` is released.
> feat(node): Add docs for async context apis

- src/platform-includes/enriching-events/set-transaction-name/go.mdx
- src/platforms/common/enriching-events/transaction-name.mdx
Document how to set transaction names for Go.
Fixes #6627
> feat(go): Add a snippet for setting transaction name

- src/platforms/common/profiling/index.mdx
- src/wizard/python/profiling-onboarding/python/1.install.md
- src/wizard/python/profiling-onboarding/python/3.configure-profiling.md
Update the docs for python profiling for the latest min version 1.18.0 which moves python profiling out of the experiment option.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's …
> docs(profiling): Update python profiling docs for 1.18.0

- src/docs/product/integrations/source-code-mgmt/gitlab/index.mdx
In the [Gitlab docs](https://docs.sentry.io/product/integrations/source-code-mgmt/gitlab/#stack-trace-linking), part of the bullet list that should go under the "Stack Trace Linking" heading is instead under the "Code owners" heading ([showing up as a txt code block](https://docs.sentry.io/product/integrations/source-code-mgmt/gitlab/#code-owners)), and this last heading is also repeating twice.
This PR fixes these two issues without any change in the substance of the text being moved.
Cheers!
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order …
> Fix misplaced content in GitLab docs

- src/docs/product/sentry-basics/search/searchable-properties.mdx
Follow up https://github.com/getsentry/sentry/pull/47446
> Add error.main_thread search fields

- src/platform-includes/sourcemaps/overview/javascript.svelte.mdx
- src/platform-includes/sourcemaps/overview/javascript.vue.mdx
- src/platform-includes/sourcemaps/upload/esbuild/javascript.mdx
- src/platform-includes/sourcemaps/upload/rollup/javascript.mdx
- src/platform-includes/sourcemaps/upload/vite/javascript.mdx
Waiting for the release of https://github.com/getsentry/sentry-javascript-bundler-plugins/pull/204
Resolves https://github.com/getsentry/sentry/issues/47230
> Update bundler plugin snippets to use new Debug ID process by default

- src/docs/product/profiling/getting-started.mdx
- src/docs/product/profiling/index.mdx
- src/platforms/common/profiling/index.mdx
- src/wizard/ruby/profiling-onboarding/ruby/0.alert.md
- src/wizard/ruby/profiling-onboarding/ruby/1.install.md
- src/wizard/ruby/profiling-onboarding/ruby/2.configure-performance.md
- src/wizard/ruby/profiling-onboarding/ruby/3.configure-profiling.md
merge after releasing https://github.com/getsentry/sentry-ruby/pull/2024 in 5.9.0
> feat(ruby): Add Profiling docs

- src/components/hooks/useKeyboardNavigate.tsx
- src/components/search.tsx
- src/css/_includes/search.scss
- src/pages/index.tsx
- Search now supports keyboard navigation
This is lifted from [my own project][0]
- Search now uses gatsby's smart <Link /> and navigate function, so search will now correctly work in dev
- Auto focus on the index page
- General code cleanup
[0]: https://github.com/evanpurkhiser/waitress/blob/main/components/useKeyboardNavigate.tsx
> feat(search): Make it better

- src/platform-includes/getting-started-install/react-native.mdx
- src/wizard/react-native/index.md
Previously we used `npx` and `yarn` interchangeably but since the new one-line command for RN we should use only `npx` to avoid `wizard` not installed errors.
> fix(rn): Use npx for all rn wizard examples

- src/components/apiSidebar.tsx
seems like we accidentally used the wrong variable during the https://github.com/getsentry/sentry-docs/pull/6694 refactor/renaming of variables here. this should fix it. can verify by looking at the vercel deploy preview.
> fix(docs): api sidebar styling

- src/components/codeBlock.tsx
When picking a DSN etc, do not let the scroll chain outside of the
selector box
> fix(ui): Avoid scroll chaining on code block selector

- src/docs/contributing/pages/index.mdx
- src/docs/product/security/ip-ranges.mdx
- src/docs/product/sentry-basics/integrate-frontend/upload-source-maps.mdx
- src/platform-includes/getting-started-install/react-native.mdx
- src/platform-includes/session-replay/install/javascript.capacitor.mdx
- src/platform-includes/session-replay/install/javascript.mdx
- src/platform-includes/sourcemaps/overview/javascript.remix.mdx
- src/platform-includes/sourcemaps/overview/javascript.svelte.mdx
- src/platform-includes/sourcemaps/overview/javascript.vue.mdx
- src/platform-includes/sourcemaps/upload/esbuild/javascript.mdx
- src/platform-includes/sourcemaps/upload/rollup/javascript.mdx
- src/platform-includes/sourcemaps/upload/vite/javascript.mdx
- src/platforms/apple/common/migration.mdx
- src/platforms/common/profiling/index.mdx
- src/platforms/java/common/performance/instrumentation/jdbc.mdx
- src/platforms/javascript/guides/gatsby/index.mdx
- src/platforms/javascript/guides/nextjs/manual-setup.mdx
- src/platforms/php/guides/symfony/index.mdx
- src/platforms/react-native/migration.mdx
- src/wizard/php/symfony.md
Some typos, some just wrong
This fixes a bunch of warnings
> fix: Various invalid codeblock language identifiers

- package.json
- yarn.lock
This fixes a large number of warnings during build time related to the
[warning: Using / for division is deprecated][0] error
[0]: https://github.com/twbs/bootstrap/issues/34051
> chore(js): Bump bootstrap 4.3.1 -> 4.6.1

- src/gatsby/plugins/gatsby-remark-variables/index.js
This warning is produced far to much for it to be of any value
> fix: Silence 'Error executing variable-like construct'

- src/docs/product/integrations/source-code-mgmt/github/index.mdx
Changing the highlight for GitHub enterprise steps as it is" hidden" in the steps for Github.
> Highlighting github enterprise

- .github/labels.yml
- .github/workflows/sync-labels.yml
cf. https://github.com/getsentry/sentry/pull/36833
> Switch to declarative labels

- src/platforms/javascript/common/configuration/micro-frontend-support.mdx
Closes https://github.com/getsentry/sentry-javascript/issues/7622
Adds preliminary docs for using the multiplexed transport introduced with https://github.com/getsentry/sentry-javascript/pull/7926 for the micro-frontends use case.
Adds a warning about async context support meaning that we cannot isolate breadcrumbs/spans.
> feat(js): Add micro-frontend docs

- src/platform-includes/getting-started-verify/apple.mdx
Capture a Swift error in getting-started-verify instead of an NSError.
> fix(apple): Capture Swift Error in verify

- src/platforms/apple/common/performance/instrumentation/automatic-instrumentation.mdx
Clarify to which transaction the Cocoa SDK attaches the app start spans.
> fix(apple): Clarify app start tracing

- src/platforms/common/enriching-events/identify-user.mdx
The `InstallationId` is not auto-generated for pure java apps, because there's no offline cache enabled by default.
> chore(java): InstallationId is not auto-generated

- src/platform-includes/capture-error/apple.mdx
Use a PlatformSection to show the uncaught exceptions paragraph only for macOS.
> fix: Show uncaught exceptions only for macOS

- .github/labels.yml
This isn't actually a product area, I goofed. It's part of the footer.
cf. https://github.com/getsentry/sentry/pull/48482
> Whack service status product area

- .github/labels.yml
This is for docs-related things that don't fit a more specific product area.
> Add "Product Area: Docs" label

- src/gatsby/createSchemaCustomization/index.ts
This is used in the PageGrid query and does appear to be legitimate
> fix(schema): Add missing description to PageContext

- src/platform-includes/getting-started-install/javascript.angular.mdx
This PR adds a note that `@sentry/angular` is no longer compatible with Angular 16 or newer. This is fine though, as our newer package, `@sentry/angular-ivy` supports it just fine. 
Given that the compatibility table already recommends the Ivy package for NG12+ I think just leaving this additional note is fine.
> ref(js): Add Angular 16 compatibility note

- src/wizard/javascript/with-error-monitoring-and-performance.md
- src/wizard/javascript/with-error-monitoring-and-replay.md
- src/wizard/javascript/with-error-monitoring-performance-and-replay.md
- src/wizard/javascript/with-error-monitoring.md
In the onboarding, if users prefer `yarn` and `npm` over the loader, we display the docs with the product selection. Docs for the BRowser JavaScript were missing and this PR fixes it.
> feat(onboarding): Add replay and performance docs for browser javascript

- src/platform-includes/getting-started-config/javascript.remix.mdx
Before ES2017 it was not possible to have trailing commas
> fix(js): Remove bad trailing comma in args list

- src/platform-includes/configuration/before-send-fingerprint/php.symfony.mdx
- src/platform-includes/configuration/before-send-hint/php.symfony.mdx
- src/platform-includes/configuration/before-send-transaction/php.symfony.mdx
- src/platform-includes/configuration/before-send/php.symfony.mdx
- src/platform-includes/configuration/config-intro/php.symfony.mdx
- src/platform-includes/configuration/sample-rate/php.symfony.mdx
- src/platform-includes/enriching-events/breadcrumbs/before-breadcrumb/php.symfony.mdx
- src/platform-includes/performance/always-inherit-sampling-decision/php.symfony.mdx
- src/platform-includes/performance/configure-sample-rate/php.symfony.mdx
- src/platform-includes/performance/traces-sample-rate/php.symfony.mdx
- src/platform-includes/performance/traces-sampler-as-filter/php.symfony.mdx
- src/platform-includes/set-environment/php.symfony.mdx
- src/platform-includes/set-release/php.symfony.mdx
- src/platforms/php/guides/symfony/configuration/symfony-options.mdx
- src/platforms/php/guides/symfony/index.mdx
- src/platforms/php/guides/symfony/profiling/index.mdx
- src/wizard/php/profiling-onboarding/symfony2/2.configure-performance.md
- src/wizard/php/profiling-onboarding/symfony2/3.configure-profiling.md
- src/wizard/php/symfony.md
We don't want to reformat these
> ref(prettier): Ignore symfomy yaml configs

- bin/react-to-product-owners-yml-changes.sh
- minimal protections on sentry-docs, we want review to avoid label disaster
- got an [auth bug](https://github.com/getsentry/sentry-docs/actions/runs/4889060391/jobs/8727273173)
> Drop back from auto-merge; try to fix auth bug

- src/platform-includes/capture-error/apple.mdx
- src/platform-includes/getting-started-verify/apple.mdx
Use do catch for usage in Swift. Pass an NSError from a method to the SentrySDK instead of creating an NSError, which reflects a more accurate use case. Furthermore, remove the reference to captureException, as they are rarely used on Apple. This is related to https://github.com/getsentry/sentry-docs/pull/6768.
> fix(apple): Capturing errors

- src/platforms/python/guides/django/index.mdx
The DjangoIntegration can now record access to Django caches and also include information if it was a cache hit or miss.
Old version: 
https://docs.sentry.io/platforms/python/guides/django/
New version: 
https://sentry-docs-git-antonpirker-python-django-cache-spans.sentry.dev/platforms/python/guides/django/
> Added docs for cache spans in Django

- src/docs/product/security/ssl.mdx
- Update the minimum required version of TLS to 1.2
- Update the list of supported ciphers based on ssllabs: [o1.ingest.sentry.io](https://www.ssllabs.com/ssltest/analyze.html?d=o1.ingest.sentry.io) and [sentry.io](https://www.ssllabs.com/ssltest/analyze.html?d=sentry.io)
- Propose section about root CA certificates pinning
- [Sentry blog: Deprecating TLS 1.0 and 1.1](https://blog.sentry.io/2022/08/22/deprecating-tls-1-0-and-1-1/)
> doc(ssl): update TLS protocols, ciphers, pinning

- src/docs/product/issues/issue-details/performance-issues/db-main-thread-io.mdx
This performance issue (DB on the Main Thread) will not be available on Android for some time, so the team has decided to move forward with GA-ing with only iOS support.
> feat(db-on-main-thread): Update docs for iOS GA

- src/wizard/javascript/nextjs/index.md
- src/wizard/javascript/nextjs/with-error-monitoring-and-performance.md
- src/wizard/javascript/nextjs/with-error-monitoring-and-replay.md
- src/wizard/javascript/nextjs/with-error-monitoring-performance-and-replay.md
- src/wizard/javascript/nextjs/with-error-monitoring.md
- src/wizard/node/profiling-onboarding/javascript-nextjs/0.alert.md
- src/wizard/node/profiling-onboarding/javascript-nextjs/1.install.md
- src/wizard/node/profiling-onboarding/javascript-nextjs/3.configure-profiling.md
This adjusts the wording about "configuring" the SDK with the onboarding wizard in the NextJS wizard docs. 
Extracted from #6867 
Happy to discuss this but I think we should improve this in some way at least :)
> ref(nextjs): Adjust wording and links in onboarding wizard docs

- src/platforms/javascript/common/session-replay/configuration.mdx
This reverts commit f3f3d20ec2e6468ffa34445055f8d8c0ede337d2.
Link didn't render
> Revert "replay: privacy link from config (#6874)"

- src/platform-includes/sourcemaps/upload/cli/javascript.mdx
- works great! https://sentry-docs-git-fork-igorsantos07-patch-1.sentry.dev/platforms/javascript/guides/react/sourcemaps/uploading/cli/#2-generate-source-maps
This simply doesn't make much sense :)
- [Sentry Docs …
> Remove wrong, copied over ini/bash config for Webpack

- src/platform-includes/performance/enable-manual-instrumentation/go.mdx
- src/platform-includes/performance/force-sampling-decision/go.mdx
`TransactionName` will be deprecated in sentry-go version 0.21.0, so changing it to the recommended `WithTransactionName`.
> fix(go): Replace deprecated usage of TransactionName

- src/platforms/javascript/common/sourcemaps/index.mdx
https://github.com/getsentry/sentry-docs/issues/6899
- this blog is out of date, removing the link and updating in contenful to route people to the correct place …
> Remove old blog link for source maps that makes no sense anymore

- src/platform-includes/capture-error/apple.mdx
Sentry Cocoa 8.7.0 contains improvements for Swift error descriptions. This PR adds the docs for this feature. Please only merge this PR after releasing 8.7.0.
> feat(apple): Add docs for Swift Error description

- src/platforms/common/configuration/options.mdx
Add intialScope option for the Apple SDK. Related PR https://github.com/getsentry/sentry-cocoa/pull/2982. Only merge after releasing Cocoa 8.7.0.
> feat(apple): Add initialScope option

- gatsby-ssr.js
- src/gatsby/onCreateWebpackConfig.ts
This uses a new env var `SENTRY_LOADER_URL`, which is expected to be the full loader URL, e.g. `https://js.sentry-cdn.com/xxx.min.js`.
@lforst has added this to the prod. env of our vercel build.
> build: Use new `SENTRY_LOADER_URL` env var

- src/gatsby/createSchemaCustomization/index.ts
These are defined in the frontmatter, but not in the PageContext schema.
Honestly I Don't understand how this was sometimes working?
> fix(schema): More missing schema types?

- src/platforms/common/performance/index.mdx
This is a shared component for documentation. So merging this would impact all SDKs across the docs which reference this page.
This PR proposes 2 changes:
1. around turning on tracing and configuring a sample rate
Is:
> Sampling for transactions must also be configured before tracing
To be (something simpler):
> Enable tracing and configure the sampling rate for transacations with....
2. dynamic sampling has become too loaded
Updating to avoid that this is not conflated with "dynamic sampling" which is something on server side, and instead proposing to call it "selective" sampling, based on contextual data, Which is more accurate to what it actually is
[Example:](https://sentry-docs-git-smeubank-perf-tracing-config.sentry.dev/platforms/javascript/guides/react/performance/#configure-the-sam …
> (Performance) reconsider onboarding wording

- src/platform-includes/getting-started-config/javascript.vue.mdx
- src/platforms/javascript/guides/vue/features/component-tracking.mdx
- src/platforms/javascript/guides/vue/features/multiple-apps.mdx
This PR declutters the "Getting Started" page for the Vue SDK/platform: 
* Move Vue 3 above Vue 2 init
* Remove multiple apps configuration from getting started and move it to its own page
* Minor rewordings
> ref(vue): Declutter Vue Getting Started page

- src/platforms/javascript/common/configuration/micro-frontend-support.mdx
Fixes a glitch in one of the MFE doc examples.
> Fix syntax error in MFE docs

- src/platforms/javascript/common/session-replay/understanding-sessions.mdx
Add an example of when to defer loading of Replay SDK and setting sample rates at a later point in time.
> feat(replay): Add "Custom Sampling" session

- src/platforms/rust/index.mdx
ref: https://github.com/getsentry/sentry-rust/issues/574#issuecomment-1542816871
I decided to keep this on the main page, as `debug-images` is the default, and it should be visible right away.
> docs(rust): Add note about debug-images integration quirk

- src/platforms/common/enriching-events/identify-user.mdx
[Cocoa SDK 6.0.1 ](https://github.com/getsentry/sentry-cocoa/releases/tag/6.0.1)was released 2,5 years ago. We can remove the note.
> fix(apple): UserId remove note on v 6.0.1

- src/platforms/javascript/common/session-replay/configuration.mdx
... from an example placeholder to `window.location.origin`
> ref(replay): Change default value of `networkDetailAllowUrls`

- src/gatsby/config.ts
- src/gatsby/plugins/gatsby-remark-variables/index.js
- src/gatsby/sourceNodes/appRegistryNodes.ts
- src/gatsby/sourceNodes/packageRegistryNodes.ts
- src/gatsby/utils/appRegistry.ts
- src/gatsby/utils/fetchCache.ts
- src/gatsby/utils/genericRegistry.ts
- src/gatsby/utils/packageRegistry.ts
The problem here was the registry data was being loaded lazily **inside of a `eval` expression**. There was some logic to `await` the result of the eval, but it's unclear how well that works in a JavaScript VM and is likely cause of all of the intermittent 'Socket closed' errors we were seeing.
This explicitly updates the gatsby-remark-variables plugin to first load the data in the registries, and THEN handle the replacements using synchronous accessor functions from the registry.
> fix(js): Eager load registry data

- src/platform-includes/getting-started-config/javascript.remix.mdx
I followed the docs to setup Sentry with Remix and kept getting errors, until I realized I was including the BrowserTracing integration in the server side file. (`Uncaught TypeError: Sentry.Integrations.BrowserTracing is not a constructor`). I'm assuming given the name "Browser" this does not belong in the server entry file. Once removed all worked as expected.  …
> fix: remove BrowserTracing integration from Remix server example

- bin/react-to-product-owners-yml-changes.sh
In the automation to react to `product-owner.yml` changes, if there is nothing to commit we can exit cleanly.
> Exit cleanly if there is nothing to commit

- src/wizard/javascript/ember/with-error-monitoring-and-performance.md
- src/wizard/javascript/ember/with-error-monitoring-and-replay.md
- src/wizard/javascript/ember/with-error-monitoring-performance-and-replay.md
- src/wizard/javascript/ember/with-error-monitoring.md
- src/wizard/javascript/gatsby/with-error-monitoring-and-performance.md
- src/wizard/javascript/gatsby/with-error-monitoring-and-replay.md
- src/wizard/javascript/gatsby/with-error-monitoring-performance-and-replay.md
- src/wizard/javascript/gatsby/with-error-monitoring.md
- src/wizard/javascript/nextjs/with-error-monitoring-and-performance.md
- src/wizard/javascript/nextjs/with-error-monitoring-and-replay.md
- src/wizard/javascript/nextjs/with-error-monitoring-performance-and-replay.md
- src/wizard/javascript/nextjs/with-error-monitoring.md
Remove links that do not have a 'feature' page, causing users to be redirected to a similar page as below:
> fix(onboarding-docs): Remove broken 'feature' links

- src/wizard/node/express.md
Fix `Tracing is not defined` when you try to run the example code here.
> docs(express-sdk): Fix Express SDK wizard example code

- src/platforms/common/configuration/options.mdx
- src/platforms/dotnet/common/configuration/http-client-errors.mdx
Issue #6984 Document HTTP Client Errors (enableCaptureFailedRequests).
These are very similar to the Java and Apple iOS docs, with minor variations. 
> Document HTTP Client Errors (enableCaptureFailedRequests) 

- src/platform-includes/crons/setup/python.celery.mdx
- src/platforms/python/guides/celery/index.mdx
Documentation of the new `exclude_beat_tasks` option for the Celery Beat auto-instrumentation of Sentry Crons.
Related to https://github.com/getsentry/sentry-python/pull/2130
> Docs for exclude_beat_tasks

- src/platform-includes/getting-started-config/javascript.angular.mdx
- src/platform-includes/getting-started-config/javascript.mdx
- src/platform-includes/getting-started-config/javascript.react.mdx
- src/platform-includes/getting-started-config/javascript.remix.mdx
- src/platform-includes/getting-started-config/javascript.svelte.mdx
- src/platform-includes/getting-started-config/javascript.vue.mdx
- src/platform-includes/performance/configure-sample-rate/javascript.electron.mdx
- src/platform-includes/performance/configure-sample-rate/javascript.mdx
- src/platform-includes/performance/configure-sample-rate/javascript.react.mdx
- src/platform-includes/performance/configure-sample-rate/javascript.vue.mdx
- src/platform-includes/performance/tracePropagationTargets-example/javascript.mdx
- src/platforms/javascript/common/install/loader.mdx
- src/platforms/javascript/common/performance/instrumentation/automatic-instrumentation.mdx
This PR updates all JS SDK Sentry.init snippets that include `BrowserTracing` to also include the `tracePropagationTargets` options. The purpose of this change is to point out to users that `tracePropagationTargets` is necessary to control to which urls of outgoing requests, our distributed tracing headers should be added. 
This does not yet address the onboarding wizard snippets. Will update them in a separate PR
cc @cleptric
> ref(js): Add `tracePropagationTargets` to SDK init code snippets

- src/platform-includes/sourcemaps/validating/javascript.mdx
- src/platforms/javascript/common/sourcemaps/validating.mdx
- src/platforms/node/common/sourcemaps/validating.mdx
The "Validating Files" section only contains outdated information or information that is already part of the troubleshooting guide:
- https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/#verify-your-source-maps-work-locally
- https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/#verify-your-source-maps-are-built-correctly
> Remove duplicated sourcemaps troubleshooting content

- src/wizard/javascript/angular/index.md
- src/wizard/javascript/angular/with-error-monitoring-and-performance.md
- src/wizard/javascript/angular/with-error-monitoring-performance-and-replay.md
- src/wizard/javascript/ember/with-error-monitoring-and-performance.md
- src/wizard/javascript/ember/with-error-monitoring-performance-and-replay.md
- src/wizard/javascript/gatsby/with-error-monitoring-and-performance.md
- src/wizard/javascript/gatsby/with-error-monitoring-performance-and-replay.md
- src/wizard/javascript/index.md
- src/wizard/javascript/nextjs/with-error-monitoring-and-performance.md
- src/wizard/javascript/nextjs/with-error-monitoring-performance-and-replay.md
- src/wizard/javascript/performance-onboarding/javascript/2.configure.md
- src/wizard/javascript/performance-onboarding/react/2.configure.md
- src/wizard/javascript/react/index.md
- src/wizard/javascript/react/with-error-monitoring-and-performance.md
- src/wizard/javascript/react/with-error-monitoring-performance-and-replay.md
- src/wizard/javascript/remix/index.md
- src/wizard/javascript/remix/with-error-monitoring-and-performance.md
- src/wizard/javascript/remix/with-error-monitoring-performance-and-replay.md
- src/wizard/javascript/svelte/index.md
- src/wizard/javascript/svelte/with-error-monitoring-and-performance.md
- src/wizard/javascript/svelte/with-error-monitoring-performance-and-replay.md
- src/wizard/javascript/vue/index.md
- src/wizard/javascript/vue/with-error-monitoring-and-performance.md
- src/wizard/javascript/vue/with-error-monitoring-performance-and-replay.md
- src/wizard/javascript/with-error-monitoring-and-performance.md
- src/wizard/javascript/with-error-monitoring-performance-and-replay.md
Following #7013, this PR now also adds `tracePropagationTargets` to the onboarding wizard code snippets.
> ref(js): Add `tracePropagationTargets` to onboarding wizard snippets

- src/platforms/javascript/guides/sveltekit/manual-setup.mdx
In the code snippet for the third step of the client-side setup when manually setting up the SvelteKit SDK, the filename is incorrectly set as `hooks.server.ts`. This PR fixes this.
<details>
<summary>Toggle screenshots</summary>
JavaScript:
---
TypeScript:
</details> …
> Fix filename in TypeScript version of code snippet of manual-setup.mdx

- src/platforms/dotnet/guides/azure-functions-worker/config.yml
- src/platforms/dotnet/guides/azure-functions-worker/index.mdx
- src/platforms/dotnet/guides/extensions-logging/index.mdx
- Azure Functions (Isolated Worker/Out-of-Process) support (https://github.com/getsentry/sentry-dotnet/pull/2346)
- Add tag filters to `SentryOptions` (https://github.com/getsentry/sentry-dotnet/pull/2367)
- …
> Azure functions and extensions logger

- src/docs/product/accounts/early-adopter.mdx
- src/docs/product/issues/issue-details/performance-issues/index.mdx
- src/docs/product/issues/issue-details/performance-issues/large-http-payload/index.mdx
Removes EA notes around large http detector and adds the threshold to the detection criteria
> chore(large-http): Update docs for GA

- src/platform-includes/getting-started-primer/node.mdx
I believe we should not immediately confront people landing on the getting started page with asynchronous context, which is a very advanced concept + we're already mentioning errors right below the note anyhow.
I would also like to remove the note about the legacy SDK documentation because the legacy sdk is REALLY old and doesn't deserve a spot on this page. The legacy SDK docs should really only be accessible via external links.
> Remove node primer

- src/platform-includes/sourcemaps/overview/javascript.svelte.mdx
- src/platform-includes/sourcemaps/overview/javascript.vue.mdx
- src/platform-includes/sourcemaps/upload/esbuild/javascript.mdx
- src/platform-includes/sourcemaps/upload/rollup/javascript.mdx
- src/platform-includes/sourcemaps/upload/vite/javascript.mdx
- src/platform-includes/sourcemaps/upload/webpack/javascript.mdx
- src/platforms/javascript/common/sourcemaps/uploading/angular-webpack.mdx
- Add notes that you need SDK version 7.47.0 or higher to use the guide.
- Remove everything except for the absolute necessary options for the bundler plugins.
> Clean up bundler plugin instructions 

- src/docs/product/accounts/getting-started/index.mdx
- src/docs/product/codecov/set-up.mdx
- src/docs/product/issues/ownership-rules/index.mdx
- src/docs/product/issues/suspect-commits/index.mdx
- src/docs/product/releases/setup/release-automation/github-deployment-gates/index.mdx
- src/gatsby/utils/resolveOpenAPI.ts
- src/platform-includes/sourcemaps/overview/javascript.mdx
- src/platforms/android/configuration/integrations/okhttp.mdx
- src/platforms/android/configuration/integrations/room-and-sqlite.mdx
Changes all instances of `Github` to `GitHub` which is the correct case. …
> fix: Github > GitHub

- src/docs/product/alerts/index.mdx
Since https://github.com/getsentry/sentry/pull/49573 is merged, add some clarification to the docs to explain what options are available and what will happen in certain scenarios.
> ref(mute alerts): Add clarification

- src/platforms/python/common/performance/instrumentation/custom-instrumentation.mdx
`functions_to_trace` has to be a list of dictionaries with a certain structure (https://github.com/getsentry/sentry-python/pull/1960#issue-1627368894, https://github.com/getsentry/sentry-python/pull/1960#issuecomment-1553410650), the example in the docs uses a different format.
> Fix `functions_to_trace` example

- src/docs/product/issues/issue-details/ai-suggested-solution/index.mdx
Fixed typo - lower case "we" after "."
> Fixed typo

- src/docs/product/cli/releases.mdx
- src/includes/sentry-cli-sourcemaps.mdx
This is a TODO. I don't quite 'get' what the 'dist' of a sourcemap is supposed to help with.
We have a problem where we are making a separate release of every PR, that gets a custom release number that is `<main_version>.<branch_height_of_main_since_main_version>.0-the-branch-name`. We've made it this way, so that hopefully Sentry can see that these releases isn't that important (due to semver). It's not really working super great.
I'm wondering if `dist` is somewhat meant to help with this? Probably not, but anyway it'd be nice to explain what `dist` is meant to do, rather than being self-referential as it is now ^_^
*Describe your changes here. If your PR relates to …
> sentry-cli-sourcemaps.mdx: Make TODO for explaining `dist`

- src/platform-includes/set-level/ruby.mdx
As per dev docs, critical level is not supported: https://develop.sentry.dev/sdk/event-payloads/#optional-attributes
An event sent with level:critical has the level changed to fatal during server side processing
> Remove critical level

- src/platforms/javascript/common/session-replay/configuration.mdx
Adds some documentation for `mutationLimit` and `mutationBreadcrumbLimit`
> feat(replay): Add docs for `mutationLimit`

- src/platforms/javascript/common/session-replay/understanding-sessions.mdx
This code snippet is incorrct.
Closes https://github.com/getsentry/sentry-docs/issues/6983
> fix(replay): Incorrect code snippet for "Manually Starting Replay"

- src/platform-includes/sourcemaps/overview/javascript.angular.mdx
- src/platform-includes/sourcemaps/upload/primer/javascript.angular.mdx
- src/platforms/javascript/common/sourcemaps/uploading/angular-nx.mdx
Based on our findings from https://github.com/getsentry/sentry-javascript/issues/8267 let's bring this guide to our docs. 
Verified the steps with a simple Nx Angular test app: https://github.com/Lms24/nx-angular-sentry
> feat(angular): Add guide for uploading source maps with `@nx/angular` CLI

- src/platform-includes/getting-started-primer/javascript.sveltekit.mdx
- src/platforms/javascript/guides/sveltekit/manual-setup.mdx
Now that we support more adapters, we should update the compatibility note accordingly
ref https://github.com/getsentry/sentry-javascript/issues/8085
> ref(sveltekit): Update SvelteKit SDK compatibility note

- src/platform-includes/getting-started-config/javascript.capacitor.mdx
- src/platform-includes/getting-started-install/javascript.capacitor.mdx
- src/wizard/capacitor/index.md
- src/wizard/ionic/index.md
This PR updates the usage of `BrowserTracing` in capacitor and ionic docs:
- replace `tracingOrigins` (which is deprecated) with `tracePropagationTargets`
- update `tracePropagationTargets` values as in #7013 
- add notes around `@sentry/angular` vs `@sentry/angular-ivy`
- add `BrowserTracing` and `tracesSampleRate` in Getting Started page 
- add the `TraceService` provider snippets as well as it's required for proper routing instrumentation in Angular. 
I have no context around capacitor/ionic so I'd appreciate a review from the mobile team before this is merged. For instance, I'm not sure if `BrowserTracing` is also exported from the capacitor SDK which is why I used the sibling SDK. Furthermore, I don't know if capacitor depends on any custom logic around `tracingOrigins` that hasn't …
> ref(js): Update BrowserTracing and Angular SDK usage in capacitor and ionic docs

- src/platforms/javascript/common/troubleshooting/index.mdx
As we recently found out, Brave blocks [Sentry requests that are passed through service workers](https://github.com/getsentry/sentry/issues/47912#issuecomment-1573714875), even if users deactivated the domain from being blocked. While this might be a bug in the browser we should nevertheless include this information to avoid confusion. Also it's one more reason to set up a tunnel and using the SDK's `tunnel` option. 
(I'm on vacation for the next two weeks. Please feel free to take this PR over and merge it as you see fit).
> ref(js): Add note about ad-blocking behaviour of Brave browser

- src/components/banner.tsx
- src/platform-includes/enriching-events/attach-viewhierarchy/android.mdx
- src/platforms/android/common/gradle.mdx
- src/platforms/android/common/kotlin-compiler-plugin.mdx
- src/platforms/android/common/performance/instrumentation/automatic-instrumentation.mdx
- src/platforms/android/configuration/integrations/jetpack-compose.mdx
> feat(Android): Add docs for Sentry Kotlin Compiler Plugin

- src/docs/product/relay/options.mdx
Remove no longer supported TLS configuration options
Remove no longer available TLS configuration options that were removed in sentry relay in https://github.com/getsentry/relay/pull/1938.
- [Sentry Docs …
> Update options.mdx to remove information about TLS support in sentry relay

- src/platform-includes/getting-started-config/java.mdx
- src/platform-includes/getting-started-config/java.spring-boot.mdx
- src/platform-includes/performance/configure-sample-rate/java.spring-boot.mdx
- src/platform-includes/performance/configure-sample-rate/java.spring.mdx
Some getting started pages didn't set `tracesSampleRate` yet. Also it was set to < `1.0` in some places.
I presume it's fine to leave https://docs.sentry.io/platforms/java/configuration/sampling/#setting-a-uniform-sample-rate and similar as they are. Please let me know otherwise.
> Mention traces sample rate and set it to 1.0

- src/platforms/common/configuration/options.mdx
`include_source_context` and `include_local_variables` were missing from the Basic Options page.
- https://sentry-docs-f5f6onk55.sentry.dev/platforms/python/configuration/options/#include-source-context
> Add missing options to Basic Options

- src/platforms/android/common/gradle.mdx
> feat(Android): Integrate source context into Android Gradle overview page

- src/docs/product/integrations/source-code-mgmt/azure-devops/index.mdx
Clarify that the organization needs to allow Third-party application access via Oauth in their Azure Org's settings.
> Clarify Azure DevOps installation process

- package.json
I was trying to get rid of 
```sh
warning package.json: License should be a valid SPDX license expression
```
when running the docs locally. While I didn't achieve this, the change still makes sense.
`BSL-1.1` does not exists, the closest match is the [Boost Software License 1.0](https://spdx.org/licenses/BSL-1.0.html).
In our case, this repo is licensed under the [Business Source License 1.1](https://spdx.org/licenses/BUSL-1.1.html), which short identifier is `BUSL-1.1`.
> Use correct license identifer in package.json

- src/docs/product/alerts/alert-types.mdx
Move banner about team plan from sessions to metric alerts for clarity
> Fix: Move team plan banner for metric alerts

- src/docs/clients/react-native/manual-setup.mdx
- src/platforms/react-native/manual-setup/manual-setup.mdx
Fix link to Apple debug symbols page from the RN manual setup docs. This is the only remaining reference to a `/client` page from a non-`/client` page that I could find.
EDIT: since the section was specific to bitcode, and bitcode has been deprecated months ago, we decided to remove the section
> Fix link to Apple debug symbols

- src/wizard/javascript/react/index.md
- src/wizard/javascript/react/with-error-monitoring-and-performance.md
- src/wizard/javascript/react/with-error-monitoring-performance-and-replay.md
Since setting up React Router is key for getting parameterised transaction names, adding this suggestion to the next steps when the Performance product is selected.
> Add React Router Info to Onboarding Wizard

- src/platform-includes/sourcemaps/legacy-uploading-methods/javascript.mdx
Aims to fix https://github.com/getsentry/sentry-docs/issues/7105
This PR re-adds troubleshooting docs that were removed in https://github.com/getsentry/sentry-docs/pull/7049 to streamline docs around sourcemaps for debug IDs.
What I didn't consider back then was that some platforms can't use debug IDs and still need some troubleshooting guide for the legacy process.
> Re-add troubleshooting guide for legacy source map upload

- src/platform-includes/sourcemaps/legacy-troubleshooting/javascript.mdx
- src/platforms/javascript/common/sourcemaps/troubleshooting_js/artifact-bundles.mdx
- src/platforms/javascript/common/sourcemaps/troubleshooting_js/index.mdx
- src/platforms/javascript/common/sourcemaps/troubleshooting_js/legacy-uploading-methods.mdx
This PR restores the old sourcemaps troubleshooting docs for all platforms that don't yet support debug IDs.
Resolves https://github.com/getsentry/sentry-docs/issues/7125
> Restore troubleshooting sourcemaps docs for platforms that support debug IDs yet

- src/platforms/react-native/manual-setup/manual-setup.mdx
Based on https://github.com/getsentry/sentry-docs/pull/7143#discussion_r1228358556
> Add Apple Debug Symbols Sentry CLI link to RN manual setup page

- src/platforms/flutter/troubleshooting.mdx
> Fix min version for sourec code context on Flutter ios

- jest.config.js
- package.json
- setup-test-env.js
- src/gatsby/plugins/gatsby-plugin-code-tabs/__tests__/__snapshots__/index.js.snap
- src/gatsby/plugins/gatsby-plugin-include/__tests__/__snapshots__/index.js.snap
- yarn.lock
- Remove react-testing-library. This package was not used and is not
what you think it is.
- Remove @react-testing-library/react since we aren't even using this
- Upgrade various testing packages to their latest versions
> chore(deps): Upgrade testing dependencies

- src/platforms/apple/common/performance/instrumentation/automatic-instrumentation.mdx
Added an explanation on how to filter out requests that will contain the trace id by using 'tracePropagationTarget' option.
In response to #7110
> feat(apple): Add tracePropagationTarget to automatic instrumentation

- package.json
- yarn.lock
Some still require the old package, but it's okay, we have a number of
versions of it
> chore(deps): Bump dotenv

- src/platforms/node/legacy-sdk/typescript.mdx
- vercel.json
Details on the 404s
1. https://docs.sentry.io/enriching-error-data/scopes/
- Preview link to test redirect fix: https://sentry-docs-q8ottlbhj.sentry.dev/enriching-error-data/scopes/
- How many hits is this getting (last 90 days)
- 191 hits
- 161 unique users
- Where are they coming from?
- Linked from a [popular GitHub issue](https://github.com/getsentry/sentry-javascript/issues/1607)
- and somewhere on our forums
- These links use the old query string method for selecting a platform (https://docs.sentry.io/enriching-error-data/scopes/?platform=browser)
- those platform names to match 1:1 to what we use now
- often the url doesn't have a platform query string on it
- this all makes it hard to navigate users to the right framework page
- we also don't have a non-SDK specific page for this …
> [DRAFT] Add redirects for top 404s

- src/docs/product/profiling/getting-started.mdx
- src/docs/product/profiling/index.mdx
- src/platforms/common/profiling/index.mdx
- src/wizard/go/profiling-onboarding/go/0.alert.md
- src/wizard/go/profiling-onboarding/go/1.install.md
- src/wizard/go/profiling-onboarding/go/2.configure-performance.md
- src/wizard/go/profiling-onboarding/go/3.configure-profiling.md
Adds relevant pages to the new Go Profiling alfa support introduced in https://github.com/getsentry/sentry-go/pull/626
I've also adapted the `profiling-onboarding` wizard but don't know how to check that locally...
> feat: Go profiling

- src/platform-includes/performance/opentelemetry-install/javascript.nextjs.mdx
- src/platform-includes/performance/opentelemetry-setup/javascript.nextjs.mdx
fixes https://github.com/getsentry/sentry-docs/issues/6999
Updates the nextjs otel docs to use https://nextjs.org/docs/app/building-your-application/optimizing/open-telemetry
> feat(nextjs): Add OpenTelemetry instrumentation docs for Next.js

- src/docs/product/sentry-basics/grouping-and-fingerprints/index.mdx
This makes a number of improvements to the Sentry Basics > Grouping Issues page:
- Remove duplicative information about approaches to changing how events are grouped. (They are currently listed in a paragraph, immediately followed by a list with the same information.)
- Rename "Solutions" section to the more descriptive "Changing How Events are Grouped."
- Move info about configuring stacktrace rules to its own section under "Changing How Events are Grouped". Do the same for SDK-side fingerprinting.
- Fix link to server-side fingerprinting rules page (currently points to SDK fingerprinting rules).
- Do a whole bunch of wordsmithing.
TODO: Some of the screenshots on this page [could use some work](https://github.com/getsentry/sentry-docs/issues/7200), but that can be a separate PR at some …
> ref(grouping): Improve Sentry Basics > Grouping Issues page

- src/platforms/javascript/guides/nextjs/manual-setup.mdx
Imported names are wrong. They should be `wrapApiHandlerWithSentry`.
> docs(nextjs): Replace withSentry with wrapApiHandlerWithSentry

- src/platforms/react-native/manual-setup/hermes.mdx
Related to https://github.com/getsentry/sentry-fastlane-plugin/pull/195
Adding the Fastlane example to show that Hermes source map and bundle have to be uploaded in one action together.
That is a difference compared to JSC.
> Add Fastlane Plugin option to RN Hermes sourcemaps page

- src/platforms/javascript/common/session-replay/troubleshooting.mdx
This adds a replay troubleshooting section to explain how to get apollo client responses captured. I think it makes sense to have this as a troubleshooting section?
Closes https://github.com/getsentry/sentry-javascript/issues/8345
> feat(replay): Add troubleshooting doc for Apollo Client response capture

- src/docs/product/security/ip-ranges.mdx
We'll be changing the DNS A records for `sentry.io` and `app.getsentry.com` in August 2023. This PR will update https://docs.sentry.io/product/security/ip-ranges/ to reflect the new addresses for each of those hosts, so that anyone who needs to update a firewall configuration can make the necessary changes. This also removes the effective date from the organizational subdomain text.
> Update IP address for apex domain and app.getsentry.com

- src/platforms/javascript/guides/react/configuration/integrations/react-router.mdx
Just noticing the description of why to setup react router is more halfway down the page. The version specifics are still relevant but generally i think this statement should be at the top and is applicable across
> Update react-router - why tho?

- src/platform-includes/crons/setup/php.mdx
Requires https://github.com/getsentry/sentry-php/pull/1511 to be released prior to merging.
> Add PHP Cron Monitor upserts

- src/platforms/android/using-ndk.mdx
Fixes https://github.com/getsentry/sentry-java/issues/2586 …
> chore(android): Add troubleshooting section to NDK docs

- src/platforms/javascript/guides/sveltekit/manual-setup.mdx
> add a missed colon

- src/platforms/javascript/guides/nextjs/manual-setup.mdx
Fixes https://github.com/getsentry/sentry-docs/issues/7206#issuecomment-1602174581
The SDK will scream at you if you don't provide an auth token so we should add it to the manual setup guide.
>  Add auth token to manual Next.js setup snippet

- src/platforms/javascript/guides/react/configuration/integrations/react-router.mdx
It looks like `createHashRouter` can be wrapped by `wrapCreateBrowserRouter`.
https://github.com/getsentry/sentry-javascript/issues/8317#issuecomment-1591045500
https://github.com/getsentry/sentry-javascript/pull/8362
> Update `createHashRouter` usage.

- src/platform-includes/sourcemaps/legacy-troubleshooting/javascript.mdx
- src/platform-includes/sourcemaps/overview/javascript.svelte.mdx
- src/platform-includes/sourcemaps/overview/javascript.vue.mdx
- src/platform-includes/sourcemaps/troubleshooting/javascript.mdx
- src/platform-includes/sourcemaps/upload/esbuild/javascript.mdx
- src/platform-includes/sourcemaps/upload/vite/javascript.mdx
- src/platform-includes/sourcemaps/upload/webpack/javascript.mdx
- src/platforms/javascript/common/sourcemaps/uploading/angular-nx.mdx
- src/platforms/javascript/common/sourcemaps/uploading/angular-webpack.mdx
Resolves https://github.com/getsentry/sentry-docs/issues/7229
When uploading source maps, it is not recommended to do it with a dev build or in watch mode. This PR adds hints in the bundler plugin sections and troubleshooting guides about this.
> Add hint to run production build when trying to upload source maps locally

- src/platform-includes/debug-symbols-apple/_default.mdx
- src/platform-includes/getting-started-install/javascript.cordova.mdx
- src/platform-includes/getting-started-install/react-native.mdx
- src/platforms/unity/native-support/index.mdx
- src/wizard/react-native/index.md
Apple don't support Bitcode anymore, so we remove the suggestions to use Bitcode to extract symbols.
Related to https://github.com/getsentry/sentry-docs/issues/6756
> chore: Remove suggestion to use Bitcode

- src/docs/product/issues/issue-details/performance-issues/n-one-queries.mdx
A customer brought up that we detect N+1s on SQL queries that make modifications (e.g. INSERT, UPDATE, DELETE) and not just SELECT, even though our docs only reference the SELECT case. Add a note to the intro clarifying that modifications are also detected, and add an example of an INSERT N+1 with fix.
> Clarify that N+1s also apply to modifications

- src/wizard/apple/ios.md
We'd like to improve the Create Project -> Sent First Error conversion for native mobile platforms, therefore refining the wizard docs and aligning them with the best-converting platforms like react/django/nextjs.
I'm focusing on iOS only for now, but let me know if I should do the same changes for macos/apple generic wizard.
Rendered version:
> feat(wizard): Simplify iOS wizard and align with best-converting platforms

- src/platforms/common/configuration/filtering.mdx
- src/platforms/common/configuration/sampling.mdx
Make it explicit, that if the parent sample decision is overridden, then distributed traces break.
> Changing parent sampled flag breaks distributed traces. 

- src/platform-includes/crons/setup/php.laravel.mdx
https://github.com/getsentry/sentry-laravel/pull/677 must be merged and released prior to merging this PR.
> Laravel Cron Upserts

- src/platforms/node/common/performance/instrumentation/automatic-instrumentation.mdx
This PR adds a note about the performance impact of `autoDiscoverNodePerformanceMonitoringIntegrations`. 
closes: https://github.com/getsentry/sentry-docs/issues/7221
> ref(node/serverless): Add note about performance impact of auto discovery of integrations

- src/platform-includes/source-context/java.mdx
- src/wizard/java/index.md
- src/wizard/java/log4j2.md
- src/wizard/java/logback.md
- src/wizard/java/spring-boot.md
- src/wizard/java/spring.md
Fixes https://github.com/getsentry/sentry-docs/issues/7241
Also updating our sample https://github.com/getsentry/sentry-maven-plugin/pull/6 …
> Change Maven plugin to execution phase generate-resources

- src/platform-includes/debug-symbols-apple/_default.mdx
- src/platforms/apple/troubleshooting.mdx
Uploading dSYMs with AppStore Connect is no longer working. Remove the documentation to not confuse users.
> fix(apple): Remove dSYMs with AppStore Connect

- src/includes/sentry-cli-sourcemaps.mdx
- src/includes/sourcemaps-cli-step-one.mdx
- src/includes/sourcemaps-typescript.mdx
- src/includes/sourcemaps-wizard-instructions.mdx
- src/platform-includes/sourcemaps/overview/javascript.mdx
- src/platform-includes/sourcemaps/overview/javascript.svelte.mdx
- src/platform-includes/sourcemaps/upload/cli/javascript.mdx
- src/platform-includes/sourcemaps/upload/esbuild/javascript.mdx
- src/platform-includes/sourcemaps/upload/rollup/javascript.mdx
- src/platform-includes/sourcemaps/upload/vite/javascript.mdx
- src/platform-includes/sourcemaps/upload/webpack/javascript.mdx
This PR adds docs for the new [source maps wizard](https://github.com/getsentry/sentry-wizard/issues/290). The wizard will automatically* configure source maps upload for users when running 
```sh
npx @sentry/wizard@latest -i sourcemaps
```
In this PR, the wizard instructions are added to these pages:
* Source Maps index page
* Affected bundler plugin pages
I'll add them to the getting started pages in a separate PR. 
'* In the first iteration of the wizard, users are still required to copy some code manually but the wizard will point this out very clearly. In future versions, we'll try to automate the entire process.
ref: #7300 
ref: …
> Add sourcemaps wizard instructions to uploading source maps docs

- src/platform-includes/getting-started-sourcemaps/javascript.mdx
- src/platform-includes/getting-started-sourcemaps/node.mdx
- src/platforms/common/index.mdx
This PR is Part 2 of #7304. It adds instructions for the new source maps wizard to the "Getting Started" pages of all JS/Node frameworks that don't come with automatic source maps upload included.
closes #7300
> Add source maps wizard instructions to Getting Started pages

- src/platform-includes/sourcemaps/artifact-bundles/javascript.mdx
- src/platforms/common/data-management/debug-files/index.mdx
This documents the time-to-idle retention policy of debug files. After 90 days of being idle, we will delete them.
> Document Debug File Retention Policy

- src/includes/platforms/configuration/integrations/redux.mdx
- src/platform-includes/enriching-events/user-feedback/sdk-api-example/javascript.mdx
- src/platform-includes/getting-started-config/javascript.remix.mdx
- src/platform-includes/performance/custom-performance-metrics/python.mdx
- src/platform-includes/performance/opentelemetry-setup/go.mdx
- src/platform-includes/performance/opentelemetry-setup/javascript.nextjs.mdx
- src/platform-includes/performance/opentelemetry-setup/node.mdx
- src/platform-includes/performance/opentelemetry-setup/ruby.mdx
- src/platform-includes/performance/opentelemetry-setup/with-java-agent/with-auto-init/java.mdx
- src/platform-includes/performance/opentelemetry-setup/with-java-agent/without-auto-init/java.spring-boot.mdx
- src/platform-includes/performance/opentelemetry-setup/without-java-agent/java.spring-boot.mdx
- src/platforms/common/profiling/index.mdx
- src/platforms/javascript/guides/react/configuration/integrations/react-router.mdx
- src/platforms/php/common/profiling/index.mdx
- src/wizard/javascript/remix/index.md
- src/wizard/javascript/remix/with-error-monitoring-and-performance.md
- src/wizard/javascript/remix/with-error-monitoring-and-replay.md
- src/wizard/javascript/remix/with-error-monitoring-performance-and-replay.md
- src/wizard/javascript/remix/with-error-monitoring.md
- src/wizard/python/pylons.md
Based on a discussion on Slack, we noticed that in a bunch of places we were using `___DSN___`, which includes a private part, instead of `___PUBLIC_DSN___`. I updated places except for legacy SDK places I found.
There were also some places where we've been using `__DSN__` (with two `_`), which is not replaced at all.
For the future, make sure to use the public dsn placeholder.
> fix: Use `___PUBLIC_DSN___` instead of `___DSN___` for all current SDKs

- src/platforms/javascript/common/session-replay/index.mdx
Hi, Team.
There's a little typo as below.
Please kindly reveiw this change :)
Thank you.
- as-is
`rate-imited`  
- to-be
`rate-limited`
> fix: typo (rate-imited -> rate-limited)

- src/components/codeContext.tsx
- src/components/signInNote.tsx
- src/components/signedInCheck.tsx
* Do not show signed in note until the user has loaded (or not).
* Extract the signed in check out (we'll need it for the org auth tokens as well)
* Make sure the sign in link does not open in a new tab, as the redirect back to docs already works 🎉
> feat: Do not show sign in note while loading user

- src/platform-includes/getting-started-config/apple.mdx
- src/platforms/apple/common/performance/instrumentation/automatic-instrumentation.mdx
- src/wizard/apple/ios.md
Renaming `enableTimeToFullDisplay` to `enableTimeToFullDisplayTracing` to reflect latest changes.
> feat(apple): Renaming enableTimeToFullDisplay to enableTimeToFullDisplayTracing

- src/wizard/javascript/react/index.md
- src/wizard/javascript/react/with-error-monitoring-and-performance.md
- src/wizard/javascript/react/with-error-monitoring-and-replay.md
- src/wizard/javascript/react/with-error-monitoring-performance-and-replay.md
- src/wizard/javascript/react/with-error-monitoring.md
Reverts getsentry/sentry-docs#7380
> Revert "ref(getting-started-docs): Remove react wizard"

- src/platform-includes/getting-started-config/javascript.angular.mdx
- src/platform-includes/getting-started-config/javascript.mdx
- src/platform-includes/getting-started-config/javascript.react.mdx
- src/platform-includes/getting-started-config/javascript.remix.mdx
- src/platform-includes/getting-started-config/javascript.svelte.mdx
- src/platform-includes/getting-started-config/javascript.vue.mdx
- src/platform-includes/performance/configure-sample-rate/javascript.mdx
- src/platform-includes/performance/configure-sample-rate/javascript.react.mdx
- src/platform-includes/performance/configure-sample-rate/javascript.vue.mdx
- src/platform-includes/performance/tracePropagationTargets-example/javascript.mdx
- src/platforms/javascript/common/install/loader.mdx
- src/wizard/javascript/angular/index.md
- src/wizard/javascript/angular/with-error-monitoring-performance-and-replay.md
- src/wizard/javascript/gatsby/with-error-monitoring-performance-and-replay.md
- src/wizard/javascript/index.md
- src/wizard/javascript/nextjs/with-error-monitoring-and-performance.md
- src/wizard/javascript/nextjs/with-error-monitoring-performance-and-replay.md
- src/wizard/javascript/performance-onboarding/react/2.configure.md
- src/wizard/javascript/react/with-error-monitoring-and-performance.md
- src/wizard/javascript/remix/index.md
- src/wizard/javascript/remix/with-error-monitoring-and-performance.md
- src/wizard/javascript/remix/with-error-monitoring-performance-and-replay.md
- src/wizard/javascript/svelte/with-error-monitoring-and-performance.md
- src/wizard/javascript/vue/index.md
- src/wizard/javascript/vue/with-error-monitoring-and-performance.md
- src/wizard/javascript/vue/with-error-monitoring-performance-and-replay.md
- src/wizard/javascript/with-error-monitoring-and-performance.md
ref https://github.com/getsentry/sentry-javascript/issues/8352
Can only be merged after https://github.com/getsentry/sentry-docs/pull/7176 is merged in and https://github.com/getsentry/sentry-javascript/pull/8399 is released.
> feat: Update JS docs to use top level `tracePropagationTargets`

- .github/workflows/test.yml
Updating to the latest version of [action-setup-volta](https://github.com/getsentry/action-setup-volta) to address GitHub action deprecation warnings.
> CI: Update setup-volta action to latest version

- src/components/basePage.tsx
- src/components/codeBlock.tsx
- src/components/layout.tsx
- src/components/platformLink.tsx
- src/components/signedInCheck.tsx
This type is more lenient and is typically what we want in these cases.
> ref(ts): Prefer ReactNode over JSX.Element

- src/components/lambdaLayerDetail.tsx
When wrapping a Select with a styled it loses the generics for the
component type, making some values `unknown`
> fix(ts): Do not style Select so the template types inherit correctly

- src/docs/product/security/ssl.mdx
From [DigiCert root and intermediate CA certificate updates 2023][1]:
> On March 8, 2023, at 10:00 MST (17:00 UTC), DigiCert will begin updating the default public issuance of TLS/SSL certificate to our public, second-generation (G2) root, and intermediate CA (ICA) certificate hierarchies.
We are going to have new certificates issued from the new G2 certificate hierarchy soon. Likely beginning of August, but certainly not later than August 20, when our old certificates will start to expire.
[DigiCert root and intermediate CA certificate updates 2023][1]
[1]: https://knowledge.digicert.com/generalinformation/digicert-root-and-intermediate-ca-certificate-updates-2023.html
> SSL: add `DigiCert Global Root G2` to the list of root certificates

- src/platforms/javascript/guides/react/configuration/integrations/react-router.mdx
Was referencing the Javascript docs for configuring Sentry with React and noticed that the DSN client key did not appear in some of the example router configurations. Modified the examples so that each one has a DSN. (https://docs.sentry.io/platforms/javascript/guides/react/configuration/integrations/react-router/)
> Update DSN in react-router.mdx

- src/docs/product/sentry-basics/search/searchable-properties/issues.mdx
changed "for" to "or"
Updated: `none` for no assignee/suggestion, `my_teams` for `#team-name` for teams you belong to.
To: `none` for no assignee/suggestion, `my_teams` or `#team-name` for teams you belong to.
> Tiny language tweak to "assigned" filter description

- src/docs/product/sentry-basics/search/searchable-properties/events.mdx
`spans.ui` is a supported, searchable property, so it should be listed in the docs.
Fixes #7406
> Add spans.ui to searchable properties

- src/docs/product/alerts/index.mdx
this pr removes the note that says muting metric alerts is only available for ea users , now that we have ga'ed the feature
> Remove note for muting metric alerts 

- src/platform-includes/getting-started-config/javascript.remix.mdx
Documents: https://github.com/getsentry/sentry-javascript/pull/8415
> Document Remix v2 support.

- src/docs/product/issues/issue-details/performance-issues/image-decoding-main-thread/index.mdx
- src/docs/product/issues/issue-details/performance-issues/json-decoding-main-thread/index.mdx
- src/docs/product/issues/issue-details/performance-issues/regex-main-thread/index.mdx
Making similar changes to the ones suggested in https://github.com/getsentry/sentry-docs/pull/7303. Some are merely wording improvements, others were necessary to make after some updates to the UI they are discussing.
> docs: update other profiling main thread issue docs

- src/platforms/common/performance/index.mdx
- src/platforms/common/performance/instrumentation/custom-instrumentation.mdx
- removes `experimental` note on Native perf page for custom instrumentation
- adds alerts on Sampling page that `tracesSampler` is not available for Native
> fix(native): Update notes on Native perf support

- src/platforms/react-native/manual-setup/manual-setup.mdx
The Sentry Android Gradle Plugin auto installation can potentially break the RN SDK by installing a newer version of the Android SDK which can be potentially incompatible. RN SDK shipped with a comparable version of sentry-android.
- related rn sample update https://github.com/getsentry/sentry-react-native/pull/3136
> Add RN SAGP app dependency and disable auto install option examples

- src/platforms/common/configuration/options.mdx
- src/platforms/python/common/data-collected.mdx
Rename `request_bodies` to `max_request_body_size` and add deprecation alert.
Add deprecation alert also for `with_locals`.
This PR adds the documentation for the changes made in https://github.com/getsentry/sentry-python/pull/2247 for ticket https://github.com/getsentry/sentry-python/issues/926.
A preview of how it looks like:
- …
> docs: Rename python configuration options and add deprecation alerts

- src/platform-includes/session-replay/setup/javascript.mdx
This PR will fix the missing `getCurrentHub` import in the `src/platform-includes/session-replay/setup/javascript.mdx` docs.
> docs: add missing getCurrentHub import

- src/platforms/common/usage/index.mdx
- src/platforms/php/guides/laravel/usage/index.mdx
We were notified that the description about the SDK's behaviour around `captureMessage` is a big confusing. I agree, so let's reword this sentence.
ref #7443
> ref: Reword `CaptureMessage` behaviour sentence

- src/platforms/javascript/common/install/loader.mdx
As brought up in #7443, the sentence around source maps and the JS loader conveys that users have to host source maps publicly. While this is probably the easiest method of making source maps available for loader users, it is not the only one. So let's change the sentence to reflect this.
closes #7443
> ref(js-loader): Reword source maps sentence

- src/docs/product/session-replay/performance-overhead.mdx
Add a bit more details (and hard numbers) for performance overhead of Replay.
Closes https://github.com/getsentry/sentry-docs/issues/6297
> Add Replay performance overhead numbers and messaging

- src/platform-includes/source-context/java.mdx
Fixes https://github.com/getsentry/sentry-docs/issues/6677
Added NDK references to source context setup
> Add NDK references to source context setup

- src/components/docsBotButton.tsx
- src/components/search.tsx
- src/css/_includes/index.scss
- src/css/_includes/search.scss
> ref(ui): Improve spacing of index search

- src/platform-includes/getting-started-config/javascript.remix.mdx
- src/platform-includes/getting-started-primer/javascript.remix.mdx
- src/platform-includes/getting-started-sourcemaps/javascript.remix.mdx
> Streamline Remix Getting Started Page

- src/docs/product/cli/dif.mdx
Adds docs on how to associate a proguard mapping file to a release
> feat(proguard): release association docs

- src/platforms/python/common/performance/instrumentation/custom-instrumentation.mdx
People do not find the code snippet hidden in a tab in a code block. Now we have two blocks.
> Make decorator code snippet more visible

- src/platforms/node/guides/koa/index.mdx
We had a few unnecessary promises in the Koa docs. This streamlines this a bit.
> feat: update Koa docs

- src/docs/product/issues/ownership-rules/index.mdx
Update the ownership rule evaluation flow docs to state that the first owner in the rule will be assigned
closes https://github.com/getsentry/sentry/issues/53337
> ref: Update ownership rule evaluation flow for multiple owners in rule

- bin/lint-docs.ts
- src/components/__tests__/__snapshots__/configKey.test.js.snap
- src/components/guideGrid.tsx
- src/components/hooks/usePlatform.tsx
- src/components/platformContent.tsx
- src/components/platformIdentifier.tsx
- src/components/platformLinkWithLogo.tsx
- src/components/platformSection.tsx
- src/gatsby/createPages/createPlatformPages.ts
- src/gatsby/onPostBuild.ts
- src/gatsby/sourceNodes/platformNodes.ts
- src/pages/index.tsx
- src/shared/platformRegistry.ts
- src/types/index.tsx
- src/types/platform.tsx
This change simplifies the `PlatformRegistry` in various ways. I will leave inline comments on the PR.
> ref(platforms): Improve implementation of platformRegistry

- src/platform-includes/set-release/javascript.nextjs.mdx
Originally added here: https://github.com/getsentry/sentry-docs/pull/7549
wording change after docs team review.
> Adjust wording for nextjs set release

- src/docs/product/profiling/index.mdx
- src/platforms/javascript/common/profiling/index.mdx
- src/wizard/javascript/profiling-onboarding/javascript/1.install.md
- src/wizard/javascript/profiling-onboarding/javascript/2.configure-document-policy.md
- src/wizard/javascript/profiling-onboarding/javascript/3.configure.md
- src/wizard/javascript/profiling-onboarding/react/1.install.md
- src/wizard/javascript/profiling-onboarding/react/2.configure-document-policy.md
- src/wizard/javascript/profiling-onboarding/react/3.configure.md
Will require the latest release of browser SDK hence why the @TODO for version number. @indragiek lmk if the docs are too conservative, I tried leaving the disclaimer which I think is fair and something folks should be aware of. 
We are also not adding other JS SDK docs yet, I think starting with plain javascript and react is a good step.
> feat(profiling): add browser profiling docs

- src/includes/platforms/configuration/integrations/default.mdx
- src/platforms/apple/common/install/carthage.mdx
- src/platforms/node/common/configuration/integrations/default-integrations.mdx
Documents changes from https://github.com/getsentry/sentry-javascript/pull/8463 where we implemented support for AggregateErrors in the JS SDK.
> Add docs for AggregateErrors in Node.js and Browser

- src/docs/product/crons/getting-started/index.mdx
- src/platform-includes/crons/connect-errors/go.mdx
- src/platform-includes/crons/requirements/go.mdx
- src/platform-includes/crons/setup/go.mdx
- src/platforms/common/crons/index.mdx
Starting from `sentry-go` version 0.23.0, we'll have initial support for Cron check-ins. This change documents the current API. 
Also linked the full E2E example from here: https://github.com/getsentry/sentry-go/blob/dde4d360660838f3c2e0ced8205bc8f7a8d312d9/_examples/crons/main.go
Closes https://github.com/getsentry/sentry-go/issues/671
> feat(sentry-go): Document Crons support

- src/platforms/python/common/configuration/integrations/default-integrations.mdx
- src/platforms/python/common/configuration/integrations/httpx.mdx
- src/platforms/python/guides/aiohttp/index.mdx
We just released a new version of the Python SDK that supports [creating events from GraphQL errors](https://github.com/getsentry/sentry-python/issues/2198). We also added an option to opt out of this to the three affected integrations (aiohttp, httpx, stdlib).
> Add `capture_graphql_errors` option to Python HTTP client integrations

- src/docs/product/data-management-settings/event-grouping/merging-issues/index.mdx
- src/docs/product/issues/states-triage/escalating-issues/index.mdx
- src/docs/product/issues/states-triage/index.mdx
- src/includes/merge-escalating-note.mdx
Escalating issues does not work for merged/unmerged issues due to this [bug](https://github.com/getsentry/snuba/issues/4558).
This PR adds this limitation to the docs so users are aware of this issue.
closes https://github.com/getsentry/sentry/issues/53375
> ref(escalating): Add merge/unmerge limitation

- src/docs/product/issues/ownership-rules/index.mdx
Add that auto assignment of an issue is turned off after manual assignment
closes https://github.com/getsentry/sentry/issues/51612
> ref: Add that auto-assignment is turned off after manual assignment

- src/platform-includes/performance/custom-performance-metrics/python.mdx
This page (and maybe others) ends Python statements with semicolons. The code will still work, but I used to get flamed for doing that on IRC so we should probably tidy it up.
If anyone knows `awk` they could maybe search for other Python blocks that have semicolons in them. …
> fix: remove semicolons from some python statements

- src/components/hooks/usePlatform.tsx
Fixes missing `type` param from @evanpurkhiser 's refactor PR: https://github.com/getsentry/sentry-docs/pull/7505
Fixes messed up formatting on this page which uses the `PlatformLinkWithLogo` component:
> fix(js): Correctly load `type` in usePlatform graphQL query

- src/docs/product/issues/issue-details/performance-issues/slow-db-queries/index.mdx
It looks like the missing information caused confusion to a customer, even though they got the same message in the Sentry Web UI:
For completeness, it would be better to add it in our documentation too.
> Add org role requirement note

- src/platforms/common/enriching-events/scopes.mdx
This streamlines the note about errors happening within the callback `withScope` being ignored by the SDK. We previously used "Error" and "Exception" quite interchangeably in this note which seems to cause confusion. 
closes https://github.com/getsentry/sentry-docs/issues/7557
> ref(node): Streamline note about error-catching behaviour in `withScope`

- src/platforms/common/profiling/index.mdx
- src/wizard/react-native/profiling-onboarding/react-native/1.install.md
fix rn sdk version
https://github.com/getsentry/sentry-react-native/releases/tag/5.8.0
> fix(rn): RN Profiling is available from version 5.8.0

- src/platforms/ruby/common/migration.mdx
* https://github.com/getsentry/sentry-ruby/issues/1522
> Async option removal was delayed til 6.0

- src/docs/product/accounts/membership.mdx
Team contributors cannot add projects to teams, even if `Open Membership` is turned on. I tested and verified this on my test organization, but let me know if there's some other way to do it that I missed.
> docs(api): Clarify team contributor abilities

- src/platform-includes/sourcemaps/legacy-uploading-methods/javascript.mdx
- src/platform-includes/sourcemaps/troubleshooting/javascript.mdx
We had a bug/wrong feature flag in Sentry that caused the new source-map upload to be weird in self-hosted Sentry.
This bug was fixed in https://github.com/getsentry/sentry/pull/52102 which was first part of 23.6.2 so we need to adjust the docs to reflect that version as the minimum version for debug IDs.
Ref: https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/360
> Adjust needed self-hosted version for debug ID sourcemap upload

- src/includes/platforms/configuration/integrations/plugin.mdx
- src/platforms/javascript/guides/react/features/error-boundary.mdx
ref https://github.com/getsentry/sentry-javascript/issues/8689
Add note about interaction between react error boundary and the `CaptureConsole` integration. This is duplicated, once in the react docs and once in the `CaptureConsole` docs so that it can be discovered easily.
> ref(js): Add note about react error boundary and CaptureConsole

- src/platforms/android/troubleshooting.mdx
added a `Kotlin` section to Android Troubleshooting regarding kotlin inline function reported with wrong line numbers
Relates to https://github.com/getsentry/sentry-java/issues/2763
> Add wrong Kotlin inline function number to Android Troubleshooting

- src/platform-includes/enriching-events/event-processors/dotnet.mdx
- src/platforms/common/enriching-events/event-processors.mdx
Resolves https://github.com/getsentry/sentry-dotnet/issues/2534
Previously undocumented feature of the .NET SDK.
> feat(.NET): Added `EventProcessor`

- src/platforms/python/common/configuration/integrations/index.mdx
This is just a small update of the index page for Python integrations, where the list of available integrations is not up-to-date with actually available integrations that you can find in the menu.
- [Sentry Docs …
> Add missing integrations to Python index

- src/includes/platforms/configuration/integrations/plugin.mdx
- src/platform-includes/configuration/contextlines/javascript.mdx
Adds documentation for the new `ContextLines` integration which we're going to ship soon (https://github.com/getsentry/sentry-javascript/pull/8699)
ref https://github.com/getsentry/sentry-javascript/issues/8656
> feat(js): Add documentation for new `ContextLines` integration

- src/includes/sampling-supported-sdks.mdx
https://github.com/getsentry/sentry-electron/pull/710 fixes a bug with baggage propagation that existed for a while, so making `4.9.0` the min version required.
> Add electron as performance at scale supported SDK

- src/wizard/javascript/replay-onboarding/electron/1.install.md
- src/wizard/javascript/replay-onboarding/electron/2.configure.md
Based on https://docs.sentry.io/platforms/javascript/guides/electron/ and https://docs.sentry.io/platforms/javascript/guides/electron/session-replay/
Relates to https://github.com/getsentry/sentry/issues/49595
> feat(docs): add replay onboarding docs for electron

- src/platforms/javascript/guides/electron/configuration/integrations/default.mdx
Documents https://github.com/getsentry/sentry-electron/pull/715
cc @timfish
> Document electron main process integration `sendOnCreate`

- src/docs/product/relay/getting-started.mdx
Relay does not support TLS configuration anymore and rather required reverse proxy to do the SSL offloading. 
Let's remove it from the docs altogether.
> chore(relay): Remove TLS mentions from getting started guide

- src/platform-includes/getting-started-install/java.log4j2.mdx
- src/platform-includes/getting-started-install/java.logback.mdx
- src/platform-includes/getting-started-install/java.mdx
- src/platform-includes/getting-started-install/java.spring-boot.mdx
- src/platform-includes/getting-started-install/java.spring.mdx
- src/platform-includes/getting-started-primer/java.spring-boot.mdx
- src/platforms/java/common/gradle.mdx
Document how our Gradle Plugins Auto Installation feature can be used to install Sentry integrations.
- [Sentry Docs …
> Document SAGP auto install for backend

- src/includes/sourcemaps-create-react-app.mdx
- src/platform-includes/sourcemaps/overview/javascript.mdx
- src/platform-includes/sourcemaps/upload/create-react-app/javascript.mdx
- src/platforms/javascript/common/sourcemaps/uploading/cli.mdx
- src/platforms/javascript/common/sourcemaps/uploading/create-react-app.mdx
- src/platforms/javascript/common/sourcemaps/uploading/esbuild.mdx
- src/platforms/javascript/common/sourcemaps/uploading/hosting-publicly.mdx
- src/platforms/javascript/common/sourcemaps/uploading/rollup.mdx
- src/platforms/javascript/common/sourcemaps/uploading/systemjs.mdx
- src/platforms/javascript/common/sourcemaps/uploading/uglifyjs.mdx
- src/platforms/javascript/common/sourcemaps/uploading/vite.mdx
Resolves https://github.com/getsentry/sentry-docs/issues/7106
Adds instructions on how to get source maps working with Create React App.
> Add source maps upload instructions for CRA

- src/docs/product/integrations/integration-platform/webhooks.mdx
We have been slowly lowering the timeout from 5 seconds to 3 seconds https://github.com/getsentry/sentry/pull/54645  then 3 seconds to 1 seconds: https://github.com/getsentry/sentry/pull/54879 and want to reflect this in docs 
> adding responses section explaining timeout

- src/docs/product/cli/releases.mdx
- src/docs/product/releases/associate-commits/index.mdx
A customer recently ran into trouble because they were trying to associate commits using the form `some-repo@123abc` rather than the form `some-org/some-repo@123abc`. Though we do have a note about this in the docs, in the section on releases, it's easy to miss. We also don't mention it at all in the CLI docs.
This fixes that by pulling it out into a highlighted note in both places.
> fix(releases): Add note about repo name when associating commits

- src/platform-includes/sourcemaps/overview/javascript.angular.mdx
> Add sourcemaps wizard to angular source map guide

- src/docs/product/data-management-settings/filtering/index.mdx
**Before:**
**After:**
Related: https://github.com/getsentry/sentry/issues/54539
> feat(inbound-filters): Add health check explanation

- src/docs/product/issues/issue-details/index.mdx
Adds information about the new event dropdown and the new Recommended event. This feature is currently in EA, but will GA tomorrow on 8/17.
> Document new issue details event dropdown and the recommended event

- src/docs/product/profiling/getting-started.mdx
Noticed this when clicking docs link in https://blog.sentry.io/profiling-to-speed-up-your-apps/ but didn't see browser profiling 😢.
I wonder if we should add custom instructions for Next.js (setting it up for both server and client)
> Add browser profiling to profiling getting started

- src/platforms/common/configuration/options.mdx
- src/platforms/java/common/configuration/index.mdx
Documents changes done in https://github.com/getsentry/sentry-java/pull/2840
> Add Docs for enabled option for Java SDK

- package.json
- yarn.lock
This reverts commit c721c5b3a550f5af9fa9c1d9256d3de7f84aa847.
Noticed we are using the SDK Loader here, so this upgrade does nothing.
The package was imported for types only.
> Revert "feat(sdk): Upgrade `@sentry/gatsby` to v7.64.0-alpha.0 (#7644)"

- src/platforms/android/configuration/integrations/apollo3.mdx
Remove beta label for Apollo 3 GraphQL Client Errors
> Remove beta label for Apollo 3 GraphQL Client Errors

- src/platforms/common/configuration/filtering.mdx
Small tweak to the "Filtering" page to clarify usage of `ignoreErrors` / `ignoreTransactions` based on this comment https://github.com/getsentry/sentry-javascript/issues/1013#issuecomment-1681145227.
> fix: Clarify string vs regex usage of `ignoreErrors`/`ignoreTransactions`

- src/docs/product/issues/suspect-commits/index.mdx
> add arcades to suspect commits doc

- src/platforms/rust/guides/actix-web/index.mdx
This removes the use of `#[actix_web::main]` and correctly initializes Sentry before the async runtime is started.
> fix(actix-web): Manually start runtime in actix-web example

- src/platforms/rust/index.mdx
This warns users not to use macros like `#[tokio::main]` or `#[actix_web::main]` and explains how to manually write an "async" main function.
> fix(rust): Add warning about #[tokio::main]

- src/platform-includes/crons/setup/python.mdx
Updated Python crons monitor setup instructions to reflect that `monitor` can now be used as a context manager, in addition to remaining usable as a decorator. This change to the documentation is necessary due to [PR #2290](https://github.com/getsentry/sentry-python/pull/2290) in the sentry-python repo. 
> Python crons monitor is now also a contextmanager

- src/css/_includes/sidebar.scss
Before and after. Our current sidebar text-to-background contrast ratio is 3.54, while 4.5 is the recommended ratio for text. This should make the sidebar text a bit easier to read https://www.w3.org/TR/WCAG20-TECHS/G18.html
lmk thoughts on if color should be tweaked.
part of replays-accessibility hackweek project
> design: tweak sidebar font color to have higher contrast ratio

- src/platforms/common/crons/index.mdx
Refs https://github.com/getsentry/sentry-docs/issues/7664
> feat(crons): Add note about upsert endpoints

- src/docs/product/cli/dif.mdx
- src/platforms/common/data-management/debug-files/identifiers.mdx
While `difutil` still exists as an alias, `debug-files` seems to be the preferred sub-command name for uploading debug-files. Now, the docs inconsistently present both, which confuses users. This PR replaces all uses with the new preference.
CC @Swatinem, @bitsandfoxes, @markushi
> [sentry-cli] use debug-files instead of difutil

- src/docs/product/accounts/early-adopter-features/discord/index.mdx
Just mimicking the Slack integration docs. We wanted somewhere to put Q & A/troubleshooting info based on our experiences with user issues.
> Add Troubleshooting section to Discord docs

- src/platforms/python/common/configuration/integrations/asyncio.mdx
Updated the code snippet for AsyncioIntegration in Python to make clear where the call to `sentry_sdk.init()` should go.
See the preview here:
https://sentry-docs-git-antonpirker-python-integration-asyncio.sentry.dev/platforms/python/configuration/integrations/asyncio/?original_referrer=https%3A%2F%2Fgithub.com%2Fgetsentry%2Fsentry-docs%2Fpull%2F7662
> Updated asyncio code snippet

- src/css/_includes/sidebar.scss
darker text, higher contrast -- fixes accessibility constrast minimum on sidebar links https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html
before and after.
> fix(a11y): add more contrast to sidebar links

- src/components/codeBlock.tsx
- src/components/orgAuthTokenNote.tsx
- src/includes/sourcemaps-create-react-app.mdx
- src/platform-includes/sourcemaps/upload/webpack/javascript.mdx
When signed in:
When not signed in:
The link for the org token creation should be the correct one, either using a redirect or the actual org in the URL.
> feat(org-tokens): Update link & docs for org token creation

- src/platforms/apple/common/configuration/app-hangs.mdx
fixes/improves wording around app hang detection thread also running when app hang feature is disabled
the [previous change](https://github.com/getsentry/sentry-docs/pull/7681/files) still left some confusion - this removes the old paragraph completely and adds a clear message regarding the thread. the necessary information about watchdog terminations not being reported in case of app hangs is already captured on the [watchdog termination page](https://docs.sentry.io/platforms/apple/guides/ios/configuration/watchdog-terminations/), which is a better place to point this out.
> clarify watchdog thread with apphang disabled

- src/docs/product/alerts/create-alerts/issue-alert-config.mdx
issue alerts using "Suggested Assignee" are now alerting the current assignee
more docs https://www.notion.so/sentry/Suggested-Assignees-Issue-Owners-Issue-alert-fallback-settings-91e6dfdbe8b4494886d360893443b0bf?pvs=4
> fix(alerts): Add current assignee to issue alert suggested assignees

- src/gatsby/config.ts
We weren't setting a lang attribute previously. fixes https://www.w3.org/WAI/WCAG21/Understanding/language-of-page.html on our docs site.
> fix(a11y): add lang attribute to site config

- src/platform-includes/performance/add-active-span/javascript.mdx
- src/platform-includes/performance/add-active-span/node.mdx
- src/platform-includes/performance/add-independent-span/javascript.mdx
- src/platform-includes/performance/add-independent-span/node.mdx
- src/platform-includes/performance/add-spans-example/javascript.mdx
- src/platform-includes/performance/enable-manual-instrumentation/apple.mdx
- src/platform-includes/performance/enable-manual-instrumentation/dart.mdx
- src/platform-includes/performance/enable-manual-instrumentation/dotnet.mdx
- src/platform-includes/performance/enable-manual-instrumentation/go.mdx
- src/platform-includes/performance/enable-manual-instrumentation/java.mdx
- src/platform-includes/performance/enable-manual-instrumentation/java.spring-boot.mdx
- src/platform-includes/performance/enable-manual-instrumentation/java.spring.mdx
- src/platform-includes/performance/enable-manual-instrumentation/javascript.mdx
- src/platform-includes/performance/enable-manual-instrumentation/native.mdx
- src/platform-includes/performance/enable-manual-instrumentation/php.mdx
- src/platform-includes/performance/enable-manual-instrumentation/python.mdx
- src/platform-includes/performance/enable-manual-instrumentation/ruby.mdx
- src/platform-includes/performance/enable-manual-instrumentation/rust.mdx
- src/platform-includes/performance/get-span/javascript.mdx
- src/platform-includes/performance/get-span/node.mdx
- src/platform-includes/performance/span-api-version/javascript.mdx
- src/platform-includes/performance/span-api-version/node.mdx
- src/platform-includes/performance/span-operations/javascript.mdx
- src/platform-includes/performance/span-operations/node.mdx
- src/platforms/common/performance/instrumentation/custom-instrumentation.mdx
resolves https://github.com/getsentry/sentry-javascript/issues/8724
Documents the new performance APIs under the custom instrumentation section.
In the future we'll want to revamp both the automatic and custom instrumentation sections, but for now this is a good starting point.
The APIs are detailed in the RFC about the [new performance API](https://github.com/getsentry/rfcs/blob/main/text/0101-revamping-the-sdk-performance-api.md), and were introduced in https://github.com/getsentry/sentry-javascript/pull/8803
`Sentry.startActiveSpan` automatically wraps a callback with a span and makes that span the active span for the execution context of the callback. The callback can be async or sync, and can return arbitrary values.
`Sentry.startSpan` just creates a span, but does not wrap it in a …
> feat(js): Document new performance APIs

- src/docs/product/issues/states-triage/escalating-issues/index.mdx
Follow up to this [conversation](https://github.com/getsentry/sentry-docs/pull/6980#discussion_r1312180871):
- Currently, only archived issues escalate so we should specify this
> ref: Specify that only archived issues escalate

- src/components/codeBlock.tsx
When you create an org token, make sure the currently selected organization matches the org selected to create the token for.
Ignore the error in the video, this was just to try this locally - normally it only updates the org if creation of the token was successful.
https://github.com/getsentry/sentry-docs/assets/2411343/25e6367e-0e14-41bb-8793-27ede895a1b8
> feat(org-tokens): Auto-select org when creating org token

- src/platforms/javascript/common/configuration/micro-frontend-support.mdx
This PR updates the docs for micro-frontend support since metadata injection is now supported by all bundler plugins.
I also added a description since I noticed one was missing:
> feat(js): Update Micro frontends docs to include new bundler plugins support

- src/docs/product/issues/index.mdx
On https://docs.sentry.io/product/issues/#issue-triage:
- Add Regressed, Escalating (and their search terms)
- Update Ignored to Archived
> ref: Fix issue triage docs for escalating

- src/platform-includes/performance/add-active-span/javascript.mdx
- src/platform-includes/performance/add-active-span/node.mdx
- src/platforms/common/performance/instrumentation/custom-instrumentation.mdx
> new performance API wording fixes

- src/platform-includes/source-context/java.mdx
Improves upon https://github.com/getsentry/sentry-docs/pull/7733 by using the org auth token placeholder and providing snippets that can be pasted using the generated token. …
> Improve org auth token usage for Java source context

- src/platforms/java/guides/spring-boot/webflux.mdx
Came up in https://github.com/getsentry/sentry-java/issues/2907
This is no longer true as of `6.16.0` of the Java SDK. …
> Remove suggestion that OTEL is needed for Spring WebFlux performance

- src/components/codeContext.tsx
This would fail anyway without it so this isn't any better or worse, but
now we're being correct about always passing a value to the header
> fix(tsc): Correct null correctness error in getCsrfToken

- src/platforms/common/performance/instrumentation/custom-instrumentation.mdx
ref https://github.com/getsentry/sentry-javascript/issues/8970
> revert performance API docs while we fix exports

- src/docs/product/crons/legacy-endpoint-migration.mdx
We are deprecating the legacy HTTP endpoints. This document describes how to move away from them
> feat(crons): Add docs on legacy endpoint migration

- src/platforms/common/configuration/sampling.mdx
Adds default behaviour for `sampleRate` and `tracesSampleRate`
closes #7764
> ref(sdks): Add sample rate defaults to Sampling page

- src/docs/product/accounts/pricing.mdx
On [Replays Pricing](https://docs.sentry.io/product/accounts/pricing/#replays-pricing) we were showing the incorrect price for on-demand replays.
The price of `$0.000195` is for errors
Replays are at `$0.003335`
**Incorrect Price**
> fix(replay): Fix quoted replay on-demand price

- src/platform-includes/getting-started-config/android.mdx
- src/platform-includes/getting-started-config/apple.ios.mdx
- src/platform-includes/getting-started-install/android.mdx
- src/platform-includes/getting-started-install/apple.ios.mdx
- src/platform-includes/getting-started-verify/android.mdx
- src/platforms/android/manual-setup.mdx
- src/platforms/apple/guides/ios/manual-setup.mdx
- src/platforms/common/index.mdx
* Switches from manual setup to sentry-wizard for Android and iOS in getting started
* For apple I had to split this for ios and non-ios since the wizard supports only iOS I think? Let me know if I should  change it for all apple targets
* Introduces new "Manual Setup" top-level section to be redirected to the old getting started docs
Part of https://github.com/getsentry/sentry-java/issues/2877 and https://github.com/getsentry/sentry-cocoa/issues/3198
> feat(getting-started): Switch from manual setup to sentry-wizard for Android and iOS in getting started

- src/platforms/index.mdx
While looking for a Sentry SDK for Nuxt 3, I found the link to the `sentry-module` from the `nuxt-community`.
Unfortunately, at first glance, there is no disclaimer there explaining that the module is only for Nuxt 2.
So with these changes I am trying to help others save some* time.
*: by _some_ I really mean a lot.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this PR here. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I …
> docs: specify supported nuxt version

- src/docs/product/sentry-basics/search/searchable-properties/session-replay.mdx
> feat(replay): Include `project_id` in the list of searchable Session Replay fields

- src/platform-includes/performance/add-spans-example/javascript.mdx
- src/platform-includes/performance/retrieve-transaction/javascript.mdx
- src/wizard/react-native/index.md
Fixes https://github.com/getsentry/sentry-docs/issues/7789
`SpanStatus` enum is deprecated, so let's replace with normal strings.
> fix(js): Remove span status enum usage in js docs

- src/platforms/python/common/configuration/integrations/asyncpg.mdx
New Python integration for the `asyncpg` library (asynchronous postgres client)
Preview: https://sentry-docs-git-antonpirker-python-asyncpg.sentry.dev/platforms/python/configuration/integrations/asyncpg/?original_referrer=https%3A%2F%2Fgithub.com%2Fgetsentry%2Fsentry-docs%2Fpull%2F7756
Integration PR is here: https://github.com/getsentry/sentry-python/pull/2314
> Added asyncpg docs

- src/platforms/python/guides/celery/index.mdx
Documents the new fine grained control over distributing traces into Celery tasks. 
Preview: https://sentry-docs-git-antonpirker-python-celery-sentry-propaga-15e012.sentry.dev/platforms/python/guides/celery/?original_referrer=https%3A%2F%2Fgithub.com%2Fgetsentry%2Fsentry-docs%2Fpull%2F7757#distributed-traces
PR is here: https://github.com/getsentry/sentry-python/pull/2331
> Document new fine grained controll over distributed tracing

- src/platforms/python/common/configuration/integrations/clickhouse-driver.mdx
- src/platforms/python/common/configuration/integrations/index.mdx
This adds the documentation for a new python integration for `clickhouse-driver`.
See https://github.com/getsentry/sentry-python/issues/2154.
Companion PR: https://github.com/getsentry/sentry-python/pull/2167
- …
> Add documentation for python clickhouse-driver integration

- src/includes/platforms/configuration/integrations/redux.mdx
Added documentation for an option added in `createReduxEnhancer` which helps to attach redux state to error events sent to sentry. 
> docs(redux): add attachReduxState option documentation

- src/platforms/python/common/configuration/integrations/grpc.mdx
- src/platforms/python/common/configuration/integrations/index.mdx
The list of Python integrations was outdated. Made it a bit easier to read too.
> Python: Updated list of integrations

- src/platform-includes/crons/connect-errors/javascript.mdx
- src/platform-includes/crons/connect-errors/node.mdx
- src/platform-includes/crons/connect-errors/php.mdx
- src/platform-includes/crons/connect-errors/python.mdx
- src/platforms/common/crons/index.mdx
Most SDKs added support for Tracing without Performance, hence we do not need to tell users to set the slug manually.
> Remove crons error context for SDKs supporting TwP

- src/platforms/common/configuration/options.mdx
Fixes https://github.com/getsentry/sentry-docs/issues/7815
We can't make it true or false because that might be wrong for some languages but we can at least not make it seem like on and off are keywords.
> Don't make it seem like `off` and `on` are keywords

- src/platforms/common/crons/index.mdx
Attachments are currently underutilized in the Crons product. As it
stands, the new endpoints (using relay) do not support attachments
easily, so we should avoid documenting this for now.
> ref(crons): Remove documentation on Attachments

- gatsby-browser.tsx
- gatsby-ssr.tsx
- src/components/feedback/feedbackWidget.tsx
- src/components/feedback/feedbackWidgetLoader.tsx
Follow-up to https://github.com/getsentry/sentry-docs/pull/7761 -- fixes hydration warnings/errors due to mismatched component tree.
> fix(feedback): Add `FeedbackWidget` to SSR

- src/components/feedback/feedbackForm.tsx
- src/components/feedback/feedbackModal.tsx
- src/components/feedback/feedbackWidget.tsx
- src/components/feedback/feedbackWidgetLoader.tsx
- src/components/feedback/sendFeedbackRequest.ts
De-couple the feedback button from the modal so that we can show the modal using other components as the actor.
This change does the following:
* Move the form in `<FeedbackModal>` to `<FeedbackForm>`
* Move business logic of the modal/form into `<FeedbackModal>` (from `<FeedbackWidget>`)
* `<FeedbackModal>` requires `children` as a render function
* `<FeedbackWidget>` is refactored to use new `<FeedbackModal>` and remains the same (shows our `<FeedbackButton>` which controls the modal)
> ref(feedback): De-couple button from modal

- src/docs/product/cli/releases.mdx
- src/includes/sentry-cli-sourcemaps.mdx
As part of completing https://github.com/getsentry/team-sdks/issues/2, this PR slightly improves wording around how to deal with releases in the new artifact bundle upload procedure. This is the result of a customer call where the customer explained how they were confused if they had to create a release with the CLI or not. It's just a slight improvement though, nothing too fancy.
ref: https://github.com/getsentry/team-sdks/issues/2
> ref(js): Clarify release creation in Sentry CLI source maps upload guide

- src/platform-includes/sourcemaps/overview/javascript.vue.mdx
As part of completing https://github.com/getsentry/team-sdks/issues/2, this PR adds an improvement to the Vue source maps page. Seems like we forgot to add the source maps wizard snippet to the Vue-specific version of this page. This PR adds the snippet and aligns the structure with the Angular and Svelte-specific pages (i.e. automatic and manual setup sections). 
ref: https://github.com/getsentry/team-sdks/issues/2
> ref(js): Add Source Maps wizard snippet to Vue Source Maps page

- package.json
- src/components/guideGrid.tsx
- src/components/hooks/usePlatform.tsx
- src/components/navbarPlatformDropdown.tsx
- src/components/platformGrid.tsx
- src/components/platformLinkWithLogo.tsx
- src/data/platforms.yml
- src/gatsby/createSchemaCustomization/platformSchema.ts
- src/pages/index.tsx
- src/pages/platform-redirect.tsx
- src/platform-includes/getting-started-config/javascript.bun.mdx
- src/platform-includes/getting-started-install/javascript.bun.mdx
- src/platform-includes/getting-started-primer/javascript.bun.mdx
- src/platform-includes/getting-started-verify/javascript.bun.mdx
- src/platform-includes/performance/automatic-instrumentation-intro/javascript.bun.mdx
- src/platform-includes/performance/configure-sample-rate/javascript.bun.mdx
- src/platform-includes/performance/enable-automatic-instrumentation/javascript.bun.mdx
- src/platform-includes/performance/enable-tracing/javascript.bun.mdx
- src/platforms/common/index.mdx
- src/platforms/javascript/common/install/index.mdx
- src/platforms/javascript/common/profiling/index.mdx
- src/platforms/javascript/guides/bun/config.yml
- src/types/platform.tsx
- yarn.lock
> feat: Add Bun docs

- src/components/feedback/feedbackWidgetLoader.tsx
- src/components/githubCta.tsx
- src/components/smartLink.tsx
Changes the "Report a problem" link to open feedback modal (when Sentry SDK is loaded). Otherwise will preserve previous behavior of opening link to GH issue.
Depends on https://github.com/getsentry/sentry-docs/pull/7876
> feat(feedback): Change "Report a problem" link to open feedback modal

- src/docs/product/alerts/index.mdx
- Add section on disabled alerts
> Add Disabled Alerts section

- src/platforms/python/guides/pyramid/index.mdx
Another small update to the getting started guides.
> Python: Documented that Pyramid is auto enabling

- src/platform-includes/configuration/auto-session-tracking/flutter.mdx
Fixes https://github.com/getsentry/sentry-docs/issues/7877
Removed mention of Rusk SDK and replaced with Flutter. v4.0.0 should be correct according to this page: https://pub.dev/packages/sentry_flutter/changelog#400
> fix(releases-flutter): Replace reference to Rust SDK with correct Flutter version

- src/components/banner.tsx
> Update banner for mobile event.tsx

- src/platform-includes/session-replay/install/javascript.angular.mdx
- src/platform-includes/session-replay/install/javascript.capacitor.mdx
- src/platform-includes/session-replay/install/javascript.electron.mdx
- src/platform-includes/session-replay/install/javascript.ember.mdx
- src/platform-includes/session-replay/install/javascript.gatsby.mdx
- src/platform-includes/session-replay/install/javascript.mdx
- src/platform-includes/session-replay/install/javascript.nextjs.mdx
- src/platform-includes/session-replay/install/javascript.react.mdx
- src/platform-includes/session-replay/install/javascript.remix.mdx
- src/platform-includes/session-replay/install/javascript.svelte.mdx
- src/platform-includes/session-replay/install/javascript.sveltekit.mdx
- src/platform-includes/session-replay/install/javascript.vue.mdx
- src/platform-includes/session-replay/setup/javascript.angular.mdx
- src/platform-includes/session-replay/setup/javascript.electron.mdx
- src/platform-includes/session-replay/setup/javascript.ember.mdx
- src/platform-includes/session-replay/setup/javascript.gatsby.mdx
- src/platform-includes/session-replay/setup/javascript.mdx
- src/platform-includes/session-replay/setup/javascript.nextjs.mdx
- src/platform-includes/session-replay/setup/javascript.react.mdx
- src/platform-includes/session-replay/setup/javascript.remix.mdx
- src/platform-includes/session-replay/setup/javascript.svelte.mdx
- src/platform-includes/session-replay/setup/javascript.sveltekit.mdx
- src/platform-includes/session-replay/setup/javascript.vue.mdx
- src/platforms/javascript/common/session-replay/index.mdx
Resolves: https://github.com/getsentry/sentry-docs/issues/7045
> replay: onboarding specific per sdk

- src/platform-includes/getting-started-primer/javascript.sveltekit.mdx
This PR adds a recommendation to use our SDK with SvelteKit 1.24.0 or newer. The reason is that 1.24.0 contains an important [fix](https://github.com/sveltejs/kit/pull/10576) that lets us [avoid invalidating route data ](https://github.com/getsentry/sentry-javascript/pull/9071 )that previously caused an additional round of data loading. 
To be clear, we're not breaking compatibility with our minimum supported version (1.0.0) but for everything before 1.24.0 the SDK causes a slight performance hit, hence the recommendation.
ref https://github.com/getsentry/sentry-javascript/issues/8818
> ref(sveltekit): Update SvelteKit version compatibility

- src/platforms/react-native/manual-setup/codepush.mdx
- relates to https://github.com/getsentry/sentry-react-native/issues/3279
- related appcenter cli pr https://github.com/microsoft/appcenter-cli/pull/2452
- reflects the current behavior of the appcenter cli https://github.com/microsoft/appcenter-cli/blob/7b637743eec2fd4e960823bfa76fe568c4f5e4ff/src/commands/codepush/release-react.ts#L89-L100
combination of `--sourcemap-output` and `--output-dir` no longer works.
source map path must be explicitly set
Bundle will be generated in ./path/CodePush -> source maps should not be in the same directory. So sentry-cli commands have to include paths to source map dir and bundle dir.
> fix(rn): Update CodePush commands to generate and upload source maps

- src/platform-includes/crons/setup/php.mdx
Use `CheckInStatus::ok()` instead of `CheckInStatus::inProgress()` for PHP …
> Use `CheckInStatus::ok()` instead of `CheckInStatus::inProgress()`

- src/platforms/elixir/index.mdx
The documentation was never updated with the new configuration property and also I don't know if it was ever truly soft deprecated in the code. Easy to miss and I'm glad it's finally been hard deprecated.
> 9.0.0 broke a public API for configuration that was "soft deprecated"

- src/docs/product/issues/issue-details/performance-issues/frame-drop/index.mdx
Local build warned me:
> warn unable to find prism language 'objective-c' for highlighting. applying generic code block
No styling before https://docs.sentry.io/product/issues/issue-details/performance-issues/frame-drop/:
After:
> fix: code formatting Objective-C

- src/platforms/dotnet/guides/aspnetcore/index.mdx
- src/platforms/dotnet/guides/aspnetcore/performance/instrumentation/automatic-instrumentation.mdx
Addresses the documentation change components of https://github.com/getsentry/sentry-dotnet/issues/2275. I'll create a separate pull request for in the sentry-dotnet repository for the code sample changes.
> Aspcore guidance 2275

- gatsby-ssr.tsx
- src/components/codeKeywords.tsx
- src/components/codeTabs.tsx
Resolves: https://github.com/getsentry/sentry-docs/issues/7951
Seems to work locally, lets check vercel:
Masking all code snippets which is more than we wants, but a step forward.
Thanks @billyvg for helping chase down the places to mask
> replay: mask only user data

- src/docs/product/session-replay/performance-overhead.mdx
Updates performance overhead benchmarks + benchmark against rrweb2.
I didn't include rrweb1 benchmarks but here they are for reference:
LCP is not very reliable, but here we can see total blocking time (tbt) has improved with rrweb2.
> feat(replay): Update performance overhead

- bin/react-to-product-owners-yml-changes.py
Product Areas Unknown and Other need to be at the front and bottom of the product areas list respectively. They are now mapped to team-ospo in security-as-code, so let's not repeat those values here and preserve the order with this workaround
> chore(open-source): Fix product owner script

- src/docs/product/crons/getting-started/index.mdx
- src/platform-includes/crons/requirements/java.mdx
- src/platform-includes/crons/setup/java.mdx
- src/platform-includes/crons/setup/java.spring-boot.mdx
- src/platform-includes/crons/troubleshooting/java.mdx
- src/platforms/common/crons/index.mdx
- src/platforms/common/crons/troubleshooting.mdx
- src/platforms/java/common/configuration/integrations/index.mdx
- src/platforms/java/common/configuration/integrations/quartz.mdx
Docs for https://github.com/getsentry/sentry-java/issues/2875
We support
- manual check-ins through `Sentry.captureCheckIn`
- Quartz by registering a `SentryJobListener` (happens automatically for Spring Boot) and having users provide a monitor slug trough the job data map
- Spring `@Scheduled` by having advice config for a new `@SentryCheckIn` annotation which allows users to specify methods to send check-ins for and what monitor slug to use.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. …
> Docs for Java SDK Check-ins

- src/platform-includes/getting-started-config/unity.mdx
> Remove duplicate login note on unity getting started page

- src/platforms/javascript/guides/electron/configuration/integrations/eventtomain.mdx
This integration is no longer used and there is no reason customers should be using it. 
https://github.com/getsentry/sentry-electron/pull/759
> fix(electron): The `EventToMain` integration is no longer used

- src/docs/product/sentry-basics/search/index.mdx
Helps address this feedback we received:
> ref(docs): add example for comparison operator searches

- .vscode/settings.json
We should no longer show the wizard content in the search - so people stop editing these pages
> fix: Exclude wizard pages from VScode search

- src/docs/product/data-management-settings/event-grouping/fingerprint-rules.mdx
Fingerprint rules do not support the full scope of Discover queries. Update docs to make this more clear.
> Link to fingerprinting grammar

- src/components/guideGrid.tsx
- src/components/tableOfContents.tsx
- src/platforms/javascript/guides/gatsby/index.mdx
Currently, the list of guides is only rendered, if the getting started page will render a table of contents. If that is not the case (the page has no further headlines other than the h1), the list of guides will also not render. 
- Render the list of guides when no headlines are present
- Add headlines to the Gatsby site
- Move the headline "Related Guides" into the component, and don't render it when there are no guides listed
> Show guide list also when no ToC is present; add ToC/headlines for Gatsby's "Getting Started" page

- src/platform-includes/sourcemaps/primer/javascript.sveltekit.mdx
- src/platforms/javascript/guides/sveltekit/manual-setup.mdx
We linked to the `latest` version which is incorrect in the context of sveltekit.
> Link to vite plugin options v0.6.1

- src/platforms/python/common/integrations/asgi/index.mdx
[We do not support ASGI Falcon apps](https://github.com/getsentry/sentry-python/blob/b31d498861fbcf33d96808170120ed6ea6935bc8/sentry_sdk/integrations/falcon.py#L213) in our integration, so we should not be mentioning it in our ASGI docs, since the Falcon integration does nothing when it detects it is being used with an ASGI app …
> Remove mention of Falcon from ASGI docs

- src/platforms/python/common/integrations/index.mdx
- src/platforms/python/common/integrations/strawberry/index.mdx
We're adding a Strawberry integration to the SDK in https://github.com/getsentry/sentry-python/pull/2393, this adds the docs for it.
Direct link to the added page: https://sentry-docs-git-ivana-python-strawberry-integration.sentry.dev/platforms/python/integrations/strawberry/ …
> Add Python integration docs for Strawberry

- src/platforms/javascript/common/troubleshooting/index.mdx
The PHP tunnel example is quite outdated. Most people rely on frameworks or libraries to achieve these tasks, hence I opted to remove it.
> Remove PHP tunnel example

- src/platform-includes/getting-started-primer/dotnet.mdx
This PR adds the stack trace linking feature to the .NET page, introduced in getsentry/sentry#57520
Closes getsentry/sentry#53249
> Update dotnet.mdx to add stack trace linking as a feature

- src/docs/product/accounts/getting-started/index.mdx
Make it possible for users to create Sentry account by adding link in docs.
> Add link to Sentry

- src/platforms/python/common/integrations/huey/index.mdx
- src/platforms/python/common/integrations/index.mdx
The `huey` integration was added to the Python SDK [quite some time ago](https://github.com/getsentry/sentry-python/releases/tag/1.15.0) and we don't have any docs for it.
Integration table preview: https://sentry-docs-git-ivana-add-huey.sentry.dev/platforms/python/integrations/
Integration page preview: https://sentry-docs-git-ivana-add-huey.sentry.dev/platforms/python/integrations/huey/
> Add docs for `huey` integration

- src/platform-includes/debug-symbols-apple/_default.mdx
_If you work at Sentry, you're able to merge your own PR without review, but please don't unless there's a good reason._
Using `api_host`` will output the following error:
```
Could not find option 'api_host' in the list...
```
For the anecdote, I wrote pretty much [the same pull request](https://github.com/getsentry/sentry-docs/pull/2704) about 3 years ago. 😉
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, …
> Fix on premise config for debug-symbols-apple

- src/platforms/javascript/common/configuration/tree-shaking/index.mdx
This adds a note to the tree shaking docs, clarifying that optional integrations/utils like replay are _automatically_ tree shaken if not used.
> feat: Add note to tree shaking docs

- src/includes/platforms/configuration/integrations/plugin.mdx
- src/platform-includes/configuration/enable-pluggable-integrations-lazy/javascript.mdx
- src/platform-includes/configuration/enable-pluggable-integrations-lazy/react-native.mdx
- src/platform-includes/session-replay/setup/javascript.angular.mdx
- src/platform-includes/session-replay/setup/javascript.electron.mdx
- src/platform-includes/session-replay/setup/javascript.ember.mdx
- src/platform-includes/session-replay/setup/javascript.gatsby.mdx
- src/platform-includes/session-replay/setup/javascript.mdx
- src/platform-includes/session-replay/setup/javascript.nextjs.mdx
- src/platform-includes/session-replay/setup/javascript.react.mdx
- src/platform-includes/session-replay/setup/javascript.remix.mdx
- src/platform-includes/session-replay/setup/javascript.svelte.mdx
- src/platform-includes/session-replay/setup/javascript.sveltekit.mdx
- src/platform-includes/session-replay/setup/javascript.vue.mdx
- src/platforms/javascript/common/configuration/integrations/index.mdx
- src/platforms/javascript/common/session-replay/understanding-sessions.mdx
- yarn.lock
This updates the docs to use the new `Sentry.addIntegration()` method vs. requiring to pick the current hub & client etc.
> feat: Use new `Sentry.addIntegration()`

- .github/workflows/dependency-review.yml
Adds a dependency review CI workflow to prevent introducing new dependencies that contain known _high_ severity vulnerabilities.
Supersedes #6580
> add dependency review workflow

- src/platforms/apple/common/configuration/metric-kit.mdx
Remove experimental note and add some info on MetricKit events.
Only merge this PR after releasing Cocoa 8.14.0.
> feat(apple): MetricKit GA

- src/platforms/dotnet/guides/azure-functions-worker/index.mdx
See: https://github.com/getsentry/sentry-dotnet/pull/2637
Blocked on:
* A non-beta new version of the .NET SDK has to be published first. cc @bitsandfoxes 
* Redoing this with the right name: https://github.com/getsentry/sentry-release-registry/pull/112
Craft is already configured to publish this package to release registry: https://github.com/getsentry/sentry-dotnet/blob/56797bd7951e72f452d636f0f6f34c1fb672ff04/.craft.yml#L20 cc @jamescrosswell
> fix: azure functions name

- src/platforms/rust/common/performance/instrumentation/automatic-instrumentation.mdx
Update the instrumentation docs to be inline with the sentry-tower crate.
The Hub layer should always be before the Http layer as seen here:
https://docs.rs/sentry-tower/latest/sentry_tower/#usage-with-tower-http
> Fix rust automatic-instrumentation.mdx

- src/docs/product/integrations/issue-tracking/jira/index.mdx
Requires https://github.com/getsentry/sentry/pull/58019
Should be merged after Jira Server alert rule action has been entirely merged
> chore(jira): Remove jira server blurb about not having alert rule action

- src/platforms/javascript/common/install/index.mdx
This was requested every now and then, so I added a section to the browser SDK installation methods overview to explain when to use which installation method.
> feat: Add docs about when to use the loader/npm

- gatsby-ssr.tsx
- src/platform-includes/configuration/capture-console/javascript.mdx
- src/platform-includes/configuration/contextlines/javascript.mdx
- src/platform-includes/configuration/debug/javascript.mdx
- src/platform-includes/configuration/dedupe/javascript.mdx
- src/platform-includes/configuration/enable-pluggable-integrations-lazy/javascript.mdx
- src/platform-includes/configuration/enable-pluggable-integrations/javascript.mdx
- src/platform-includes/configuration/extra-error-data/javascript.mdx
- src/platform-includes/configuration/http-client/javascript.mdx
- src/platform-includes/configuration/module-metadata/javascript.mdx
- src/platform-includes/configuration/reporting-observer/javascript.mdx
- src/platform-includes/configuration/rewrite-frames/javascript.mdx
- src/platform-includes/session-replay/install/javascript.mdx
- src/platforms/javascript/common/install/loader.mdx
It is possible that the loader script fails to load (e.g. if it is adblocked or something like this), so to be safe we should recommend to guard against `Sentry` not existing before calling `Sentry.onLoad()`.
> feat: Update loader docs to guard against unexisting `Sentry.onLoad()`

- src/components/basePage.tsx
- src/components/seo.tsx
- src/pages/404.tsx
- src/pages/index.tsx
- src/templates/apiDoc.tsx
- src/templates/apiPage.tsx
- src/templates/doc.tsx
- src/templates/platform.tsx
- src/templates/wizardDebugIndex.tsx
Add canonical tag (`<link rel="canonical" href="https://docs.sentry.io/<slug>" data-react-helmet="true">`) to each page of docs to help with SEO. This prevents Google from indexing the same page twice when there are URL params, so these 2 URLs aren't indexed twice:
- https://docs.sentry.io/platforms/javascript/
- https://docs.sentry.io/platforms/javascript/?original_referrer=https%3A%2F%2Fwww.google.com%2F
> Add canonical tags for SEO

- src/platforms/common/configuration/filtering.mdx
`before_send` has two purposes: it allows folks to define their own function for modifying an event before it leaves the SDK and/or for dropping specific events altogether. The current wording makes it sound like it's primarily for modifying the event.
> Make it clearer that `before_send` can drop events

- src/components/orgAuthTokenNote.tsx
- src/platform-includes/capture-error/javascript.astro.mdx
- src/platform-includes/distributed-tracing/how-to-use/javascript.astro.mdx
- src/platform-includes/enriching-events/import/javascript.astro.mdx
- src/platform-includes/getting-started-config/javascript.astro.mdx
- src/platform-includes/getting-started-install/javascript.astro.mdx
- src/platform-includes/getting-started-primer/javascript.astro.mdx
- src/platform-includes/getting-started-sourcemaps/javascript.astro.mdx
- src/platform-includes/getting-started-verify/javascript.astro.mdx
- src/platform-includes/performance/automatic-instrumentation-intro/javascript.astro.mdx
- src/platform-includes/performance/configure-sample-rate/javascript.astro.mdx
- src/platform-includes/performance/enable-automatic-instrumentation/javascript.astro.mdx
- src/platform-includes/performance/enable-tracing/javascript.astro.mdx
- src/platform-includes/session-replay/install/javascript.astro.mdx
- src/platform-includes/session-replay/setup/javascript.astro.mdx
- src/platform-includes/sourcemaps/overview/javascript.astro.mdx
- src/platform-includes/sourcemaps/primer/javascript.astro.mdx
- src/platforms/common/index.mdx
- src/platforms/javascript/common/install/index.mdx
- src/platforms/javascript/common/sourcemaps/uploading/index.mdx
- src/platforms/javascript/guides/astro/config.yml
- src/platforms/javascript/guides/astro/manual-setup.mdx
This PR adds SDK docs for the new Sentry Astro SDK. It's still in Alpha which we clearly point out in the new docs.
This PR includes adjustments for Astro in the following pages:
* Getting Started shows the semi-automatic setup via the `astro` CLI
* Added "Manual Setup" page similarly, to SvelteKit, Remix and NextJS with all possible configuration options
* Adjusted source map docs to not display the full range of source maps upload material. The Astro SDK ships with the Vite plugin, so there shouldn't be too much need for other resources than troubleshooting. 
* Added Astro specific setup for Replay (This is the first SDK that actually enables Replay by default. …
> feat(js): Add Documentation for Sentry Astro SDK

- src/platform-includes/distributed-tracing/how-to-use/apple.mdx
- src/platform-includes/distributed-tracing/how-to-use/javascript.mdx
- src/platform-includes/distributed-tracing/how-to-use/javascript.nextjs.mdx
- src/platform-includes/distributed-tracing/how-to-use/javascript.remix.mdx
- src/platform-includes/distributed-tracing/how-to-use/javascript.sveltekit.mdx
- src/platform-includes/distributed-tracing/how-to-use/react-native.mdx
- src/platform-includes/distributed-tracing/limiting-traces/javascript.mdx
- src/platform-includes/distributed-tracing/limiting-traces/node.mdx
As discovered by @lforst in https://github.com/getsentry/sentry-docs/pull/8267#discussion_r1368295746, we showed an incorrect example for `tracePropagationTargets` values in the "Usage->Distributed Tracing" page ([example](https://docs.sentry.io/platforms/javascript/guides/sveltekit/usage/distributed-tracing/#how-to-use-distributed-tracing)). TPT values can only be String.contains matches or regex matches but glob patterns in strings like `"https://.*.otherservice.org/.*"` are not supported. 
This PR removes the glob pattern and adds a regex example to show both types of TPT values. 
(Adjusted the one for Astro in #8267)
Note: The same value is used in Flutter and iOS docs but I'm not yet sure if these SDKs support globs or not. Asked in Slack for clarification.
> fix: Remove glob syntax from `tracePropagationTargets` example

- src/platforms/javascript/common/configuration/tree-shaking/index.mdx
- src/platforms/javascript/common/session-replay/troubleshooting.mdx
This adds the new tree shaking flags for Replay, as well as the new bundler plugin configs for bundle size optimizations.
I also excluded the webpack/rollup examples for sveltekit and remix as well (??) - not sure if we should show something (?) else for these platforms?
> feat: Add docs for replay tree shaking flags

- src/components/platformSdkDetail.tsx
- src/gatsby/createSchemaCustomization/packageSchema.ts
- src/gatsby/sourceNodes/appRegistryNodes.ts
- src/gatsby/sourceNodes/packageRegistryNodes.ts
- src/gatsby/utils/genericRegistry.ts
- src/types/platform.tsx
Please have a look at the package details box in the right sidebar
> fetch API docs URL and display in package details box

- src/platforms/common/configuration/options.mdx
ref https://github.com/getsentry/sentry-javascript/discussions/9377
> Make it clear that dsn needs to be set when using tunnel

- src/platform-includes/configuration/error-sampler/python.mdx
- src/platforms/common/configuration/options.mdx
- src/platforms/common/configuration/sampling.mdx
Document the Python `error-sampler` option we introduced in getsentry/sentry-python#2456. Closes #8305.
> Dynamic error sampling Python

- src/platforms/elixir/configuration/options.mdx
I was doing the Sentry onboarding today and it didn't work. I noticed the instructions were wrong because the configuration expects `root_source_code_paths` (plural) and not `root_source_code_path`. Plus, it expects a list instead of a string.
This PR updates the docs to cover that. …
> fix(docs): Fix root_source_code_paths option

- src/platform-includes/sourcemaps/overview/javascript.remix.mdx
We streamlined this some while ago, but forgot a place, where we still had `yarn` before `npm`.
> fix: Fix order of npm vs yarn

- src/includes/javascript-crons-checkins.mdx
- src/includes/javascript-crons-job-monitoring.mdx
- src/platform-includes/crons/setup/javascript.astro.mdx
- src/platform-includes/crons/setup/javascript.bun.mdx
- src/platform-includes/crons/setup/javascript.mdx
- src/platform-includes/crons/setup/javascript.nextjs.mdx
- src/platform-includes/crons/setup/javascript.remix.mdx
- src/platform-includes/crons/setup/javascript.sveltekit.mdx
- src/platforms/common/crons/index.mdx
Documents https://github.com/getsentry/sentry-javascript/pull/9395 released as part of https://github.com/getsentry/sentry-javascript/releases/tag/7.76.0
> feat(crons): Document withMonitor API for JS SDK

- src/platforms/go/common/troubleshooting.mdx
Add a section on avoiding temporary file leaks when using Go SDK middleware with file upload handlers.
See this issue: https://github.com/getsentry/sentry-go/issues/673
> feat(go): add temp file leak section to troubleshooting

- src/platform-includes/source-context/java.mdx
- src/platforms/java/common/maven/index.mdx
Adds documentation for the Java Maven Plugin that allow auto-install of Sentry Dependencies and Source-Bundle upload. …
> Add docs for Java Maven plugin

- src/docs/product/profiling/getting-started.mdx
- src/docs/product/profiling/index.mdx
- src/platform-includes/performance/configure-sample-rate/flutter.mdx
- src/platform-includes/performance/traces-sample-rate/flutter.mdx
- src/platforms/common/profiling/index.mdx
- src/platforms/common/profiling/troubleshooting.mdx
Adds relevant docs for the [Flutter profiling alpha](https://github.com/getsentry/sentry-dart/pull/1611).
> feat: flutter profiling docs

- src/docs/product/integrations/issue-tracking/jira/index.mdx
There's been an existing bug for a long time when you try to manually or automatically create a Jira/Jira Server issue. The priority dropdown will show all priorities from all projects, not the one you've currently selected.
The alert rule action can be created, but will fail silently when triggered and fail to create Jira issues. Creating it manually is fine b/c it shows the error, but we don't validate for alert rule actions b/c we're not sending the webhook to actually create the issue (b/c there is no issue obv)
We're limited by Jira/Jira server APIs to fetch priorities per project, b/c this requires elevated global/project admin permissions that our integration does not have.
See https://github.com/getsentry/sentry/pull/58749 and https://github.com/getsentry/sentry/pull/59197 for …
> chore(jira): Document issue with fetching priorities

- src/platform-includes/performance/configure-sample-rate/javascript.remix.mdx
- src/platform-includes/performance/enable-tracing/javascript.remix.mdx
- src/platforms/common/performance/index.mdx
Currently, we only showed the generic `@sentry/browser` code snippet to set up performance monitoring for the Remix SDK. This PR adds Remix-specific code snippets that show both, client and server code for Remix projects.  
Side note: I think we can probably go the same route with Remix as with Next/Sveltekit/Astro and always add BrowserTracing under the hood. This however is a larger task for which I currently don't have time. So let's go with correct docs for now and adjust later when/if we get to simplify things in the Remix SDK.
> fix(remix): Add Remix-specific Performance monitoring setup code snippets

- src/platforms/javascript/common/troubleshooting/index.mdx
Since this is just example, its' fine to keep but lets call out this is built int
> tunnel example, mention built in

- src/docs/product/integrations/source-code-mgmt/github/index.mdx
Copied from Jira/Azure, will look like below (except github instead of jira)
> chore(github): Mention github action restricted to business plan

- src/docs/product/releases/health/index.mdx
Turned note about crash events not matching crash rates into an alert for more visibility.
> Crash free user/session clarification

- src/docs/product/data-management-settings/scrubbing/server-side-scrubbing/index.mdx
Relay recently added additional functionality for the `Safe Fields` option in Sentry Data Scrubbing. This adds an example with some documentation as well as a link to the full syntax description.
> feat(data-scrubbing): Add sction about advanced safe field usage

- src/docs/product/integrations/notification-incidents/pagerduty/index.mdx
call out edge case for warning thresholds
> Clarify sentry pagerduty alert config

- src/platforms/ruby/common/configuration/options.mdx
This PR adds a little blob on configuring proxy in `sentry-ruby`. 
I worked on https://github.com/getsentry/sentry-ruby/pull/2161 and realized that proxy configuration is not documented yet — so here we go. 
@shanamatthews, in `sentry-ruby` 5.1.2, we don't yet support reading proxy from env variables, but we just pushed up a PR with it. Is it a good idea to document the env var behavior in this PR, or wait until it's merged and released? …
> Ruby: add proxy config docs

- src/platforms/android/enhance-errors/kotlin-compiler-plugin.mdx
Since the compiler plugin has been out for more than half-a-year, I think it's fine to replace the experimental note altogether.
Came up in https://github.com/getsentry/sentry-android-gradle-plugin/issues/591
> chore(android): Add note on min. required Kotlin version

- src/platforms/elixir/usage/index.mdx
The current Elixir library doesn't have functionality for submitting arbitrary breadcrumbs without the user coercing the format. If the format is a random dictionary, the library silently fails. This updates the documentation to reflect the behavior. …
> Update elixir documentation to reflect library behavior

- src/docs/product/relay/getting-started.mdx
I assume that this additional `.` is wrong, at least I get a `Hostname mismatch` error when starting Relay with default configuration.
> Removed superfluous dot from upstream URL.

- src/platforms/apple/common/performance/instrumentation/automatic-instrumentation.mdx
Move the opt-out section of APM to the bottom of the page.
|--------|--------|
| ![CleanShot 2023-11-07 at 11 40 46@2x](https://github.com/getsentry/sentry-docs/assets/2443292/f83670be-cbb3-4f07-83ad-c66b7e9d9df0)| ![CleanShot 2023-11-07 at 11 41 21@2x](https://github.com/getsentry/sentry-docs/assets/2443292/7483ae7e-d769-4317-be76-03ec787806cd) |
> ref(apple): Move opt out to bottom

- src/platforms/javascript/common/configuration/tree-shaking/index.mdx
This is now excluded by default, no need to manually configure anything.
> fix(replay): update treeshaking docs to remove canvas flag

- src/platforms/javascript/common/session-replay/troubleshooting.mdx
This clarifies in replay troubleshooting docs that only static videos can be captured.
Closes https://github.com/getsentry/sentry-javascript/issues/9447#issuecomment-1801639171
> fix(replay): Clarify streaming video capture

- src/platforms/php/common/integrations/index.mdx
In https://github.com/getsentry/sentry-php/pull/1633 we are changing how the PHP `ErrorHandler` works to correctly handle out of memory errors. These docs changes reflect those changes.
/cc @cleptric
> Update PHP docs regarding changes to the `ErrorHandler`

- src/platforms/android/integrations/jetpack-compose/index.mdx
- src/platforms/android/performance/instrumentation/automatic-instrumentation.mdx
On the automatic performance page for Android, we don't need to prefix Activity and Fragment Instrumentation with Android; for Android users, it's clear what the docs refer to.
> ref(android-perf): Remove redundant Android prefix

- src/platforms/javascript/common/session-replay/configuration.mdx
- src/platforms/javascript/common/session-replay/understanding-sessions.mdx
This adds docs for the new replay config method.
> feat(replay): Add docs for `beforeErrorSampling()`

- src/platforms/javascript/common/configuration/sentry-testkit/index.mdx
Sentry Testkit is a [community-maintained library](https://github.com/zivl/sentry-testkit), meaning we don't offer official support for it. However, we quite prominently feature them in our docs. This PR adds a note that this library is not maintained by us and that support requests should be made in the maintainer's repository.
> ref(js): Add note that Sentry Testkit is community-maintained

- src/platforms/common/enriching-events/identify-user.mdx
This shouldn't be used as the feature in the product was never implemented.
> Remove `user.segment`

- src/docs/product/alerts/notifications/index.mdx
Update the participant docs (and say the word "participants" in them) to reflect the new ways you can subscribe and unsubscribe from an issue. 
Don't merge until these changes are GA'd.
Closes https://github.com/getsentry/sentry/issues/57722
> ref(workflow): Update participants docs

- src/platforms/react-native/manual-setup/manual-setup.mdx
- src/platforms/react-native/troubleshooting/index.mdx
Adds docs for new Xcode Build Phase scripts shipped in https://github.com/getsentry/sentry-react-native/releases/tag/5.11.0
> feat(rn): Add new Xcode scripts to RN Manual Setup

- src/platforms/react-native/manual-setup/hermes.mdx
- src/platforms/react-native/sourcemaps/index.mdx
Update Source Maps upload guides to reflect changes released in https://github.com/getsentry/sentry-react-native/releases/tag/5.11.0
> feat(reactnative): Add source maps upload guide with Debug IDs

- src/platform-includes/configuration/config-intro/kotlin-multiplatform.mdx
- src/platform-includes/enriching-events/attach-screenshots/kotlin-multiplatform.mdx
- src/platform-includes/enriching-events/attach-viewhierarchy/kotlin-multiplatform.mdx
- src/platform-includes/enriching-events/attachment-max-size/kotlin-multiplatform.mdx
- src/platform-includes/enriching-events/breadcrumbs/before-breadcrumb/kotlin-multiplatform.mdx
- src/platform-includes/getting-started-config/kotlin-multiplatform.mdx
- src/platform-includes/set-environment/kotlin-multiplatform.mdx
- src/platform-includes/set-release/kotlin-multiplatform.mdx
- src/platforms/kotlin-multiplatform/initialization-strategies.mdx
Android `context` is not needed anymore since KMP `0.3.0`. 
Related PR: https://github.com/getsentry/sentry-kotlin-multiplatform/pull/117
> feat: Remove context from Sentry.init in KMP

- src/platform-includes/distributed-tracing/custom-instrumentation/javascript.mdx
- src/platform-includes/distributed-tracing/custom-instrumentation/node.mdx
- src/platform-includes/distributed-tracing/how-to-use/javascript.mdx
- src/platform-includes/distributed-tracing/how-to-use/node.mdx
- src/platforms/common/usage/distributed-tracing/custom-instrumentation.mdx
This adds docs for custom distributed tracing for Node & Browser JavaScript, including the new `continueTrace` method, which was added here: https://github.com/getsentry/sentry-javascript/pull/9164.
We do not show this for Next, Remix, Sveltekit and Astro - not 100% sure if this is correct, or if there are other guides where we should/should not show this.
> feat: Add custom distributed tracing docs for JS/Node

- src/docs/product/issues/issue-details/performance-issues/db-main-thread-io.mdx
Remove note that DB on main thread perf issues is not available on Android - it's generally available now, see e.g. https://demo.sentry.io/issues/4327317740/?project=1801383
Note: This PR aligns the DB on main thread page with the other pages. We generally do not document compatibility of Mobile perf issues on the docs, but availability is intuitively subject to SDK version, frameworks, and configuration used (i.e. the File/DB APIs/frameworks used need to be instrumented by the SDK for the backend detector to be able to detect perf issues).
> fix(issues): remove note about DB on main thread for Android

- src/platforms/python/integrations/gcp-functions/index.mdx
Add a possible workaround for using the GCP integration on newer Python runtimes that are currently not supported directly.
Direct link to page: https://sentry-docs-git-ivana-gcf-with-newer-runtimes.sentry.dev/platforms/python/integrations/gcp-functions
Related: https://github.com/getsentry/sentry-python/issues/1666
> feat(python): Add a workaround to GCP docs

- package.json
Noticed that the `yarn format` command doesn't really work properly, so I removed it and instead added a new `yarn lint:fix` command that will run all autofixing locally.
> build: Remove `format` command and add `lint:fix` command

- src/platforms/apple/common/install/carthage.mdx
- src/platforms/apple/common/install/swift-package-manager.mdx
Clarify that visionOS is not supported for installation via Carthage and Swift package manager.
> fix(apple): VisionOS Install Methods

- src/api/guides/teams-tutorial.mdx
> Get rid of "our" in tutorial

- src/docs/product/index.mdx
- src/docs/product/sentry-basics/index.mdx
- move "what is sentry" and "what can sentry help with" sections up to the product index page
- add more details to how to get the most value out of sentry based on feedback from PMs
> split up get started with sentry page

- src/platforms/javascript/common/troubleshooting/index.mdx
We noticed these docs were actually incorrect, because you basically _have to_ call `new Hub(client)` - if you don't do this, integrations will not run, which will/may lead to unintended side effects. So updating this to just document this as "the" way to do this.
While at this, I also updated this to specifically call out browser extensions, as that is a common thing we get requests for every now and then, and also point out that in addition you should not setup any global integrations in such a scenario.
> fix: Update docs for manual client creation

- gatsby-ssr.tsx
- src/platform-includes/configuration/capture-console/javascript.mdx
- src/platform-includes/configuration/contextlines/javascript.mdx
- src/platform-includes/configuration/debug/javascript.mdx
- src/platform-includes/configuration/dedupe/javascript.mdx
- src/platform-includes/configuration/enable-pluggable-integrations-lazy/javascript.mdx
- src/platform-includes/configuration/enable-pluggable-integrations/javascript.mdx
- src/platform-includes/configuration/extra-error-data/javascript.mdx
- src/platform-includes/configuration/http-client/javascript.mdx
- src/platform-includes/configuration/module-metadata/javascript.mdx
- src/platform-includes/configuration/reporting-observer/javascript.mdx
- src/platform-includes/configuration/rewrite-frames/javascript.mdx
- src/platform-includes/session-replay/install/javascript.mdx
- src/platforms/javascript/common/install/index.mdx
- src/platforms/javascript/common/install/loader.mdx
Updates the docs for the loader to use the newly added `window.sentryOnLoad` config, which is better than `onLoad()` as it has better timing guarantees and also we do not need to check for existence of `Sentry`.
> feat(loader): update loader docs for new config

- src/platforms/javascript/common/troubleshooting/index.mdx
- src/platforms/javascript/guides/nextjs/manual-setup.mdx
Adds a quick note to the tunnel option docs to say that there is a quicker setup route in Next.js.
> Reference tunnelRoute in Next.js tunnel docs

- src/platform-includes/replay/privacy-configuration/javascript.mdx
Before giving a huge table for the user to parse, lets cover a common use case with a code snippet.
The snippet also benefits in a way to show how the user can place the options listed in the table below in code. (they go under `Replay({ ... })`
This include is used in the following pages:
* https://docs.sentry.io/platforms/javascript/session-replay/configuration
* https://docs.sentry.io/platforms/javascript/session-replay/privacy/
> replay(options): point out how to opt-in for text if safe

- src/platforms/javascript/guides/vue/features/component-tracking.mdx
Adds documentation for Vue 3 compatible performance tracing hooks added in https://github.com/getsentry/sentry-javascript/pull/9578. Screenshot of changed section:
I chose to update the examples to be vue 3 first because vue 2 is [reaching EOL](https://v2.vuejs.org/lts/) at the end of the year - so it made sense to update the docs here to be Vue 3 first as that is already the default for most people right now (or at least, I would expect so). …
> update docs for vue 3 component tracking update

- src/platform-includes/getting-started-config/ruby.rack.mdx
This pull request adds a note on using Sentry in Rack apps that are run directly with Ruby, without Rackup. Closes #8519. Related to [this Sentry-Ruby issue](https://github.com/getsentry/sentry-ruby/issues/2167).
/cc @sl0thentr0py …
> fix(sentry-ruby): A note on Rack apps without Rackup

- src/platforms/python/integrations/django/index.mdx
With the next release of the Python SDK [we'll support Django 5.0](https://github.com/getsentry/sentry-python/issues/2489). Updating the integration docs to reflect this.
Direct link to the affected page: https://sentry-docs-git-ivana-django-50.sentry.dev/platforms/python/integrations/django
(Will only merge this once we've released the SDK, so in a couple of weeks.)
> feat(python): Prepare for Django 5.0 support

- src/platform-includes/getting-started-sourcemaps/javascript.astro.mdx
- src/platform-includes/sourcemaps/overview/javascript.astro.mdx
Also fixed remaining wrong imports
If the file is just `.env` and not `.env.sentry-build-plugin` the Vite Plugin doesn't pick it up correctly
> fix: Env file name for Astro source map uploads

- src/platforms/javascript/guides/remix/manual-setup.mdx
Documents the case in https://github.com/getsentry/sentry-javascript/issues/9500
> feat(remix): Add Vite custom server usage instructions.

- src/platform-includes/enriching-events/user-feedback/example-widget-onclose/_default.mdx
- src/platform-includes/enriching-events/user-feedback/example-widget-onclose/javascript.electron.mdx
- src/platform-includes/enriching-events/user-feedback/example-widget-onclose/javascript.mdx
- src/platform-includes/enriching-events/user-feedback/example-widget-onclose/python.django.mdx
- src/platform-includes/enriching-events/user-feedback/example-widget-onclose/python.flask.mdx
- src/platform-includes/enriching-events/user-feedback/example-widget-onload/_default.mdx
- src/platform-includes/enriching-events/user-feedback/example-widget-onload/javascript.electron.mdx
- src/platform-includes/enriching-events/user-feedback/example-widget-onload/javascript.mdx
- src/platform-includes/enriching-events/user-feedback/example-widget-onload/python.django.mdx
- src/platform-includes/enriching-events/user-feedback/example-widget-onload/python.flask.mdx
- src/platforms/common/enriching-events/user-feedback.mdx
Fixes https://github.com/getsentry/sentry-javascript/issues/9433
Adds `onClose` to the user-feedback section and a short description for both `onClose` and `onLoad`.
Please see the accompanying PRs:
* for the sdk: https://github.com/getsentry/sentry-javascript/pull/9550
* for the backend: https://github.com/getsentry/sentry/pull/59885 …
> feat(feedback): Add onClose description to user-feedback

- src/platforms/dotnet/guides/winui/config.yml
- src/platforms/dotnet/guides/winui/index.mdx
Added a guide for using Sentry with WinUI 3 applications. In particular, the guide contains a section for users who would like to publish their applications using Ahead-of-Time compilation or Trimming enabled, as there are some additional steps that we can't automate using our integration once AOT is enabled. 
See:
- https://github.com/getsentry/sentry-dotnet/issues/2778
> Added a guide for using Sentry with WinUI 3

- src/platforms/javascript/guides/astro/manual-setup.mdx
This PR adds documentation on how to use and customize the Sentry Astro middleware. 
Only merge once 7.82.0 is released
closes https://github.com/getsentry/sentry-javascript/issues/9444
> feat(astro): Document middleware and server instrumentation usage

- src/platform-includes/profiling/automatic-instrumentation-setup/javascript.nextjs.mdx
- src/platform-includes/profiling/automatic-instrumentation-setup/javascript.sveltekit.mdx
Both, the NextJS and SvelteKit SDKs, already add `BrowserTracing` by default. There's no harm in adding them as a user but on the other hand, it's not necessary either. So this PR removes the intgration from the respective snippets.
The same thing applies to Astro but I don't think we have Astro specific Browser profiling docs yet. @JonasBa are you currently adding more platforms or should I quickly add a snippet for Astro?
ref: https://github.com/syntaxfm/website/pull/1346#discussion_r1381817262
> fix(browser-profiling): Remove `BrowserTracing` from Nextjs and Sveltekit snippets

- src/platforms/python/integrations/index.mdx
- src/platforms/python/integrations/starlite/index.mdx
I've noticed we're missing integration docs for Starlite. The actual integration was added to the Python SDK in January of this year.
> fix(python): Add docs for Starlite

- src/docs/product/issues/issue-details/performance-issues/endpoint-regressions/index.mdx
Since not all transactions qualify for the endpoint regression feature, explicitly list all the transaction ops that qualify.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice …
> feat(stats-detectors): List transaction ops for endpoint regression

- src/platform-includes/sourcemaps/overview/javascript.astro.mdx
This small PR adds documentation for the new `assets` option soon to be released in the Astro 
SDK. Functionality it's 1:1 on par with the Vite plugin assets option but we don't expose the 
full Vite Plugin API in the Astro SDK; hence the dedicated documentation.
Only merge after https://github.com/getsentry/sentry-javascript/pull/9668 is relased but otherwise ready to review
> feat(astro): Document `assets` sourcemaps upload option

- src/platforms/android/configuration/using-ndk.mdx
- src/platforms/android/migration.mdx
SDK v7 requires Android API level 19+.
This info has been added to the migration guide. Also, previous workaround for NDK on API 14 has been removed.
> Add Android v7 requirement API 19

- src/platforms/java/common/performance/instrumentation/apollo3.mdx
- src/platforms/java/common/performance/instrumentation/okhttp.mdx
- src/platforms/java/migration/6.x-to-7.0.mdx
* Migration doc from 6.x.x to 7.0.0
* Added new okhttp integration doc as we can use it in non-android modules now
* Added graphql client errors section to apollo3 as it was missing
> feat(java): Migration from 6.x.x to 7.0.0

- src/platform-includes/troubleshooting/dotnet.mdx
> fix: implicit using typo

- src/platforms/common/configuration/options.mdx
Adding a missing config option.
Direct link: https://sentry-docs-git-ivana-add-auto-enabling-integrations.sentry.dev/platforms/python/configuration/options/
> fix(python): Add missing `auto_enabling_integrations` config option

- src/docs/product/cli/releases.mdx
- src/docs/product/reference/search/searchable-properties/events.mdx
- src/docs/product/reference/search/searchable-properties/index.mdx
- src/docs/product/reference/search/searchable-properties/issues.mdx
- src/docs/product/reference/search/searchable-properties/releases.mdx
- src/docs/product/reference/search/searchable-properties/session-replay.mdx
- src/docs/product/reference/search/searchable-properties/user-feedback.mdx
- src/includes/searchable-properties/intro-for-user-feedback.mdx
Adds a section under `Searchable Properties` in the docs for User Feedback.
Closes https://github.com/getsentry/sentry-docs/issues/8585
> feat(docs): add feedback searchable properties

- src/docs/product/integrations/notification-incidents/discord/index.mdx
Users can create an issue alert with a Discord notification with the channel URL or channel id, instead of just the id.
> feat(discord): Update docs for issue alerts to allow for url

- src/platform-includes/getting-started-primer/javascript.astro.mdx
Replaces the Alpha warning with a Beta Note.
> chore(astro): Promote Astro SDK to Beta

- src/platforms/javascript/guides/nextjs/manual-setup.mdx
Instructs on how to capture errors in Next.js error.js pages.
> Add note about Next.js `error.js` pages

- src/docs/product/user-feedback/setup.mdx
Fix: not modal specific but SDK/API for 'crash report' as in, takes event_id
> user-feedback: API for crash reports

- src/platforms/common/user-feedback/configuration.mdx
Fixes extra escaping here:
Also removes a misplaced sentence, this was the context:
> feedback: Remove extra escape chars and misplaced sentence

- src/platforms/common/configuration/options.mdx
We have a new feature in Python to add the source location of database queries. See [this PR](https://github.com/getsentry/sentry-python/pull/2521).
This documents the two new options we introduced for this feature.
> Python: Added new options for query source

- src/platform-includes/getting-started-primer/python.mdx
- src/platforms/common/index.mdx
Bring back the note about frameworks in Python. Because Python has no guides anymore, we link to the integrations list instead.
> [Python] On main page link to integrations list

- src/docs/product/user-feedback/index.mdx
Add reference to https://docs.sentry.io/product/reference/search/searchable-properties/user-feedback/
> feedback: product docs mention search

- src/platform-includes/getting-started-config/elixir.mdx
> Remove deprecated Elixir option

- src/platforms/flutter/troubleshooting.mdx
- src/platforms/react-native/manual-setup/expo.mdx
- related to https://github.com/getsentry/sentry-react-native/issues/3262
Sentry RN SDK will support Expo projects out of the box.
> Add Expo manual setup steps

- src/platforms/node/guides/aws-lambda/container-image/index.mdx
- src/platforms/python/integrations/aws-lambda/container-image/index.mdx
These images are unmaintained (last updated 2y ago) and seem to cause confusion. Let's deprecate them and remove when we do new majors.
Ref: https://github.com/getsentry/sentry-javascript/issues/9762
> Deprecate AWS Lambda Images

- src/platforms/javascript/common/troubleshooting/index.mdx
examples repo has been archived.
> remove examples repo in tunneling docs.

- src/platform-includes/performance/opentelemetry-setup/node.mdx
- src/platforms/javascript/common/install/loader.mdx
- src/platforms/javascript/common/session-replay/understanding-sessions.mdx
- src/platforms/javascript/common/troubleshooting/index.mdx
One step towards removing `getCurrentHub()` from the docs!
> feat: Use `getClient()` instead of `getCurrentHub().getClient()`

- src/docs/product/releases/setup/release-automation/jenkins/index.mdx
The previous command was ambiguous and inconsistent with the other commands in other places. The new command specifies the path to the sourcemaps as /path/to/sourcemaps, which is easier to understand and modify.
changed the path
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's …
> docs(release-automation): make the upload-sourcemaps command clearer

- src/platforms/react-native/manual-setup/manual-setup.mdx
> Fix paht typo in manual-setup.mdx

- src/platforms/android/configuration/options.mdx
- src/platforms/apple/common/configuration/options.mdx
- src/platforms/dart/configuration/options.mdx
- src/platforms/dotnet/common/configuration/options.mdx
- src/platforms/elixir/configuration/options.mdx
- src/platforms/flutter/configuration/options.mdx
- src/platforms/java/common/configuration/options.mdx
- src/platforms/javascript/common/configuration/options.mdx
- src/platforms/kotlin-multiplatform/configuration/options.mdx
- src/platforms/native/common/configuration/options.mdx
- src/platforms/node/common/configuration/options.mdx
- src/platforms/php/common/configuration/options.mdx
- src/platforms/python/configuration/options.mdx
- src/platforms/react-native/configuration/options.mdx
- src/platforms/rust/common/configuration/options.mdx
- src/platforms/unity/configuration/options.mdx
- src/platforms/unreal/configuration/options.mdx
Supersedes https://github.com/getsentry/sentry-docs/pull/8679
the SDK does not read the value of window.SENTRY_RELEASE it releases the value of window.SENTRY_RELEASE.id
[getsentry/sentry-javascript@b3f8d9b/packages/browser/src/sdk.ts#L111](https://github.com/getsentry/sentry-javascript/blob/b3f8d9bcb067b391c1d0eba4f537ff09be56c1e9/packages/browser/src/sdk.ts#L111)
> Clarify window.SENTRY_RELEASE

- src/docs/product/crons/getting-started/cli.mdx
https://github.com/getsentry/sentry-cli/pull/1847 added validation for the `sentry-cli monitors run` command's `--timezone` argument. We should therefore delete the "Known Limitation" notice, which informs users that the `--timezone` argument is not validated, from the docs.
> Remove known CLI monitor limitation

- src/components/githubCta.tsx
We're currently mixing "from x to y" and "whether x or y" in our "edit this page" footer. I went with the latter option, because I think it makes more sense in context.
> fix(site): Fix typo in "edit this page" footer

- src/docs/product/cli/releases.mdx
Document `--strict` argument of the `sentry-cli sourcemaps upload` command, which we added in https://github.com/getsentry/sentry-cli/pull/1829. This PR also updates references to the old `sentry-cli releases files "$VERSION" upload-sourcemaps` command to refer to `sentry-cli sourcemaps upload` instead because `sentry-cli releases files "$VERSION" upload-sourcemaps` only exists for backwards-compatibility with Sentry CLI versions below 2.0.0. …
> Document `sentry-cli sourcemaps upload`'s `--strict` argument

- src/platform-includes/capture-error/apple.mdx
Defining the function in the property would create a new function every time the `errorUserInfo` property is accessed. …
> improve code for CustomNSError example

- src/docs/product/accounts/quotas/spike-protection.mdx
New orgs on a trial will not be spike protected because they have unlimited quotas for the duration of the trial.
> fix(spike protection): add note about SP during trials

- src/platforms/javascript/guides/remix/manual-setup.mdx
Ref: https://github.com/getsentry/sentry-javascript/pull/9725
Updated `handleError` instructions to reflect the new feature.
Also updated external links from Remix v1 documentation to v2.
> Add `wrapRemixHandleError` instructions

- src/platforms/android/enriching-events/tags/index.mdx
- src/platforms/apple/common/enriching-events/tags/index.mdx
- src/platforms/dart/enriching-events/tags/index.mdx
- src/platforms/dotnet/common/enriching-events/tags/index.mdx
- src/platforms/elixir/enriching-events/tags/index.mdx
- src/platforms/flutter/enriching-events/tags/index.mdx
- src/platforms/go/common/enriching-events/tags/index.mdx
- src/platforms/java/common/enriching-events/tags/index.mdx
- src/platforms/javascript/common/enriching-events/tags/index.mdx
- src/platforms/kotlin-multiplatform/enriching-events/tags/index.mdx
- src/platforms/native/common/enriching-events/tags/index.mdx
- src/platforms/node/common/enriching-events/tags/index.mdx
- src/platforms/php/common/enriching-events/tags/index.mdx
- src/platforms/python/enriching-events/tags/index.mdx
- src/platforms/react-native/enriching-events/tags/index.mdx
- src/platforms/ruby/common/enriching-events/tags/index.mdx
- src/platforms/rust/common/enriching-events/tags/index.mdx
- src/platforms/unity/enriching-events/tags/index.mdx
- src/platforms/unreal/enriching-events/tags/index.mdx
Add link to explicit tag syntax from tag pages
related to https://github.com/getsentry/sentry/issues/61595
> ref: Add link to explicit tag syntax from tag pages

- src/platforms/react-native/manual-setup/metro.mdx
Adds docs about the Sentry Metro Serializer released in https://github.com/getsentry/sentry-react-native/releases/tag/5.11.0 and https://github.com/getsentry/sentry-react-native/releases/tag/5.16.0-alpha.1
> feat(rn): Add React Native Metro Bundler page

- src/docs/product/session-replay/index.mdx
Fixing links as mentioned here: https://github.com/getsentry/sentry-javascript/issues/9871
> fix(replay): Fix links to replay start/stop

- src/platform-includes/getting-started-install/javascript.astro.mdx
- src/platform-includes/getting-started-primer/javascript.astro.mdx
- src/platforms/javascript/common/index.mdx
This PR refactors the  Astro "Getting Started" intro section. I tried the suggested "ramp" approach for docs. Figured as Astro is new and relatively small it's ideal to experiment with. Feel free to close this PR if you wanna tackle this more generally. Appreciate feedback either way. 
Motivation for this change: Other than the meeting last week, we had users writing in ([example](https://github.com/getsentry/sentry-javascript/issues/9777)) about Cloudflare and Edge support and it seemed like our previous compatibility note didn't state clearly enough that these runtimes are currently not supported. 
Note: I also wanted to add numbering to the steps but this requires more fundamental changes to the common "getting started" template and I want to avoid this for now. IMO we should get rid …
> ref(astro): Improve Getting Started introduction

- src/platform-includes/crons/setup/javascript.deno.mdx
[`DenoCron`](https://github.com/getsentry/sentry-deno/blob/2bd56ebf652a3f6131cf9ec853cbbd87ca2b12cf/index.mjs#L9895) is exported as part of the [`INTEGRATIONS`](https://github.com/getsentry/sentry-deno/blob/2bd56ebf652a3f6131cf9ec853cbbd87ca2b12cf/index.mjs#L10087) object (not a top-level class). This PR updates the docs to reflect this :) …
> docs(deno): Fix DenoCron reference in docs for Deno.cron

- src/platforms/javascript/guides/nextjs/manual-setup.mdx
- Fix type error in Nextjs manual setup guide `global-error.tsx` example. Importing the Error component as `import Error from "next/error"`  interferes and overrides the global `Error ` type used in the props
- …
> Update nextjs guide `global-error.tsx` example types

- src/platforms/android/enriching-events/tags/index.mdx
- src/platforms/apple/common/enriching-events/tags/index.mdx
- src/platforms/dart/enriching-events/tags/index.mdx
- src/platforms/dotnet/common/enriching-events/tags/index.mdx
- src/platforms/elixir/enriching-events/tags/index.mdx
- src/platforms/flutter/enriching-events/tags/index.mdx
- src/platforms/go/common/enriching-events/tags/index.mdx
- src/platforms/java/common/enriching-events/tags/index.mdx
- src/platforms/javascript/common/enriching-events/tags/index.mdx
- src/platforms/kotlin-multiplatform/enriching-events/tags/index.mdx
- src/platforms/native/common/enriching-events/tags/index.mdx
- src/platforms/node/common/enriching-events/tags/index.mdx
- src/platforms/php/common/enriching-events/tags/index.mdx
- src/platforms/python/enriching-events/tags/index.mdx
- src/platforms/react-native/enriching-events/tags/index.mdx
- src/platforms/ruby/common/enriching-events/tags/index.mdx
- src/platforms/rust/common/enriching-events/tags/index.mdx
- src/platforms/unity/enriching-events/tags/index.mdx
- src/platforms/unreal/enriching-events/tags/index.mdx
Add link to automatically set Sentry tags (searchable properties) from the tag pages
related to https://github.com/getsentry/sentry/issues/61595
> ref: Add link to searchable tags

- src/platforms/apple/common/enriching-events/breadcrumbs/index.mdx
Updated the docs because `null` isn't a thing in Swift or Objective-c. `nil` is a thing and `NULL` is a thing, but `null` is not.
> Update Apple breadcrumbs docs because swift/obj-c don't have a `null` keyword.

- src/platform-includes/getting-started-install/kotlin-multiplatform.mdx
- src/platform-includes/getting-started-primer/kotlin-multiplatform.mdx
- src/platform-includes/getting-started-verify/kotlin-multiplatform.mdx
- src/platforms/kotlin-multiplatform/debug-symbols.mdx
- src/platforms/kotlin-multiplatform/initialization-strategies.mdx
- src/platforms/kotlin-multiplatform/install/cocoapods.mdx
- src/platforms/kotlin-multiplatform/install/index.mdx
- src/platforms/kotlin-multiplatform/install/swift-package-manager.mdx
- src/platforms/kotlin-multiplatform/native-access-sdk.mdx
With more and more KMP SDK releases coming, we need to be able to track which KMP SDK version is compatible with which Cocoa SDK version. 
Ideally we can automate this in the future but now it's the best alternative we can do.
Closes https://github.com/getsentry/sentry-kotlin-multiplatform/issues/159
> kmp: add version compatibility table

- src/platforms/javascript/guides/sveltekit/manual-setup.mdx
Adds documentation for the two new options available with v7.91.0 in the SvelteKit SDK's `sentryHandle` request handler:
ref: https://github.com/getsentry/sentry-javascript/pull/9969
> feat(sveltekit): Document new `sentryHandle` options

- src/includes/platforms/configuration/integrations/redux.mdx
- src/platform-includes/configuration/redux-init/javascript.mdx
- src/platform-includes/configuration/redux-init/react-native.mdx
- src/platforms/javascript/guides/react/features/redux.mdx
Resolves https://github.com/getsentry/sentry-javascript/issues/9986
Seems to still work:
https://sentry-sdks.sentry.io/issues/4770144138/events/5793f545909b4e1fbcd4aa783fc70211/
> Update redux integration docs for newer Redux `configureStore` API

- src/platform-includes/performance/create-transaction-bound-to-scope/apple.mdx
> Note on bindToScope in Apple/Cocoa custom instr.

- src/platforms/react-native/sourcemaps/index.mdx
Fixed multi-line terminator for bash command.
> fix: Missing multi-line terminator for bash command

- src/docs/product/security-policy-reporting.mdx
Updated the documentation to include a note about the deprecation of report-uri and the recommendation to use both report-uri and report-to in the Content-Security-Policy for broader browser compatibility. This change reflects the current state of browser support for CSP directives as noted by Mozilla. …
> Add CSP compatibility note for report-uri and report-to usage

- src/platforms/ruby/common/migration.mdx
closes https://github.com/getsentry/sentry-ruby/issues/2152
> feat(ruby): Add community fork link to migration guide

- src/platforms/ruby/common/configuration/options.mdx
> fix(ruby): Add clarification for setting logger levels

- src/platforms/python/integrations/celery/crons.mdx
Tell people that non standard Celery beat schedulers are not supported yet
> Python Crons - Note on supported schedulers.

- src/platform-includes/getting-started-config/basic-config/apple.mdx
- src/platforms/apple/common/performance/instrumentation/automatic-instrumentation.mdx
Since Cocoa 8.18.0 enablePreWarmedAppStartTracking is stable. This PR also removes code samples on enabling the feature before 8.0.0, which we released over a year ago. As we only removed the experimental note in the code docs of the SDK and didn't make any other changes, we don't need to specify a minimum SDK version.
We need to wait until we release Cocoa 8.18.0 to merge this.
> feat(apple): Prewarmed app start tracing is stable

- src/platforms/react-native/performance/instrumentation/automatic-instrumentation.mdx
I noticed that `enableAutoPerformanceTracking` doesn't exist and it is named `enableAutoPerformanceTracing` so I went ahead and updated the docs
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, …
> docs: Update automatic-instrumentation.mdx

- src/includes/javascript-crons-automatic-crons-instrumentation.mdx
- src/platform-includes/crons/setup/javascript.astro.mdx
- src/platform-includes/crons/setup/javascript.bun.mdx
- src/platform-includes/crons/setup/javascript.nextjs.mdx
- src/platform-includes/crons/setup/javascript.remix.mdx
- src/platform-includes/crons/setup/javascript.sveltekit.mdx
- src/platform-includes/crons/setup/node.mdx
Documents https://github.com/getsentry/sentry-javascript/pull/9999 and https://github.com/getsentry/sentry-javascript/pull/9904
> feat(cron): Add node cron library instrumentation docs

- src/platform-includes/performance/opentelemetry-setup/ruby.mdx
closes https://github.com/getsentry/sentry-ruby/issues/2171
> feat(ruby): Add clarification about middleware ordering in otel

- src/platforms/react-native/manual-setup/manual-setup.mdx
I believe the getPackages Kotlin example is not valid Kotlin (it may have been ported from the react-native example comment - which now has a ticket to update the application of adding packages https://github.com/facebook/react-native/pull/41856)
Update Kotlin example to valid Kotlin for MainApplication.kt …
> Update RN Kotlin example for MainApplication.kt in manual-setup.mdx 

- src/platforms/python/performance/instrumentation/custom-instrumentation.mdx
This PR updates the Sentry Python SDK tracing docs to inform users that when tracing a static or class method using the `@sentry_sdk.trace` decorator, the decorator must be placed **after** the `@staticmethod` or `@classmethod` decorator. 
Failing to adhere to this ordering will break the function (specifically when it is called on an instance rather than on the class), due to how static and class methods work in the Python language (see https://github.com/getsentry/sentry-python/issues/2525). Unfortunately, because of how static and class methods work in Python it is probably impossible to change the `@sentry_sdk.trace` decorator to allow a flipped ordering, so …
> docs: `@sentry_sdk.trace` and static/class method decorator ordering

- src/docs/product/relay/operating-guidelines.mdx
Relay [no longer supports SSL/TLS](https://github.com/getsentry/relay/blob/d17608ca5d0cb9b897d7c96e99b5a7cddb09ae82/relay-server/src/actors/server.rs#L25-L27) and the recommendation is to offload this responsibility to a proxy. The [Getting Started page no longer references TLS options](https://github.com/getsentry/sentry-docs/pull/7621), but there are currently no docs on setting it up. This PR adds such docs.
> Add SSL/TLS support as a benefit of a proxy in front of Relay

- src/docs/product/data-management-settings/scrubbing/advanced-datascrubbing.mdx
[Advanced data scrubbing](https://docs.sentry.io/product/data-management-settings/scrubbing/advanced-datascrubbing/) does [not scrub file names](https://github.com/getsentry/relay/blob/d17608ca5d0cb9b897d7c96e99b5a7cddb09ae82/relay-pii/src/processor.rs#L125-L126):
> In NativeImagePath we must not strip the file's basename because that would break processing.
Not sure if it's exactly the same, but minidumps also follow the [same approach](https://docs.sentry.io/product/data-management-settings/scrubbing/attachment-scrubbing/#minidump-selectors:~:text=Any%20modification%20will%20exclude%20the%20basename%20of%20the%20pathnames%20to%20ensure%20the%20event%20processing%20pipeline%20can%20still%20operate%20correctly%20on%20the%20minidump.):
> Any modification will exclude the basename of the …
> Document no data scrubbing in filenames

- src/platform-includes/performance/opentelemetry-setup/python.mdx
The Python OpenTelemetry example doesn't work out of the box. Additional OpenTelemetry setup is needed to make it work, which we don't describe in the docs, [leaving folks confused](https://github.com/getsentry/sentry-python/issues/1976). This PR:
* changes the OpenTelemetry setup example so that it works without requiring any background OTel setup
* adds an example to verify that the setup is working
Preview: https://sentry-docs-git-ivana-fix-opentelemetry-python-setup.sentry.dev/platforms/python/performance/instrumentation/opentelemetry/
Fixes https://github.com/getsentry/sentry-python/issues/1976
> fix(python): Fix OpenTelemetry example

- src/platform-includes/source-context/java.mdx
- src/platforms/java/common/gradle/index.mdx
- Disable sourceContext option to make build work: This option was set to true in example config but this option cannot be enabled without setting `org`, `project`, and `authToken` so in result the config you copy from the docs fail. I think adding the comment to enable it after reading the docs would communicate that some additional steps are needed for this feature.
- Add section for specifying dependencies of sentry task: When running the plugin in a build where there is a code generation task, the plugin fails. This section provides guidance for running sentry plugin step after the code generation tasks.
Fix: https://github.com/getsentry/sentry-android-gradle-plugin/issues/546
*If you work at Sentry, you're able to merge your own PR without review, but please don't unless there's a …
> Disable sourceContext option to make build work.

- src/platforms/java/common/integrations/quartz.mdx
We've just changed the order of `SentrySchedulerFactoryBeanCustomizer` so users own `SchedulerFactoryBeanCustomizer` will run after it and override whatever the Sentry customizer does. While this means we no longer break the users config, it also means our Quartz integration breaks if they set a global job listener. Unless `SentryJobListener` is manually added by the user in their own `SchedulerFactoryBeanCustomizer`.
[Java PR](https://github.com/getsentry/sentry-java/pull/3095) …
> Spring Boot Quartz `SchedulerFactoryBeanCustomizer` add note

- src/platforms/apple/common/enriching-events/attachments/index.mdx
Small updates to wording of intro and placement/wording of note about crash attachments
related: https://github.com/getsentry/sentry-cocoa/issues/1247
> ref(apple): attachments intro and note about crash attachments

- src/platforms/node/guides/express/index.mdx
It appears this is not necessary (at least with the latest & greatest - express, @types/express and @sentry/*) anymore. …
> Remove note on the necessity of type assertion when using TypeScript

- src/platform-includes/configuration/capture-console/javascript.mdx
- src/platform-includes/configuration/contextlines/javascript.mdx
- src/platform-includes/configuration/debug/javascript.mdx
- src/platform-includes/configuration/dedupe/javascript.mdx
- src/platform-includes/configuration/enable-pluggable-integrations-lazy/javascript.mdx
- src/platform-includes/configuration/enable-pluggable-integrations/javascript.mdx
- src/platform-includes/configuration/extra-error-data/javascript.mdx
- src/platform-includes/configuration/http-client/javascript.mdx
- src/platform-includes/configuration/module-metadata/javascript.mdx
- src/platform-includes/configuration/reporting-observer/javascript.mdx
- src/platform-includes/configuration/rewrite-frames/javascript.mdx
- src/platform-includes/getting-started-config/javascript.bun.mdx
- src/platform-includes/getting-started-config/javascript.mdx
Fixes https://github.com/getsentry/sentry-docs/issues/8880
It was brought up in that issue, that while we point to the Loader setup first, we show the non-loader config below on the "Getting Started" page for Browser JS. This is a bit confusing...  I updated this to specifically call out that config differs for the loader, adding tabs for npm/loader/cdn for clarity.
While at it, I also renamed the tabs from "ESM" to `npm` in the integration pages, which is IMHO clearer for there.
> feat: Update browser getting started docs to explain loader vs npm config

- src/docs/product/profiling/getting-started.mdx
- src/docs/product/profiling/index.mdx
- src/platforms/dotnet/profiling/index.mdx
- src/platforms/dotnet/profiling/troubleshooting/index.mdx
- src/wizard/dotnet/profiling-onboarding/dotnet/0.alert.md
- src/wizard/dotnet/profiling-onboarding/dotnet/1.install.md
- src/wizard/dotnet/profiling-onboarding/dotnet/2.configure-performance.md
- src/wizard/dotnet/profiling-onboarding/dotnet/3.configure-profiling.md
This adds .NET profiling docs for the upcoming .NET 4.0 release.
> feat: dotnet profiling docs

- src/platforms/javascript/guides/astro/manual-setup.mdx
Found a typo in Astro's "Manual Setup" code blocks.
**Also:** I noticed we're using `process.env` to access environment variables in the `astro.config.mjs` file. If we define our variables in `.env` file(s), it won't work because [Astro evaluates the config file before `.env`](https://docs.astro.build/en/guides/configuring-astro/#environment-variables) so the values are always going to be `undefined`. A suggested solution is to use the `loadEnv` method from the `vite` package (which if you use `pnpm` you explicitly need to install it):
```javascript
import { loadEnv } from "vite";
const { SENTRY_DSN, SENTRY_AUTH_TOKEN } = loadEnv(
process.env.NODE_ENV,
process.cwd(), …
```
> fix(typo): import capitalization typo

- src/platform-includes/performance/retrieve-transaction/ruby.mdx
This fixes the null object representation in a ruby dedicated example in Performance's « retrieve a transaction » paragraph.
> Update type in null object for ruby performance transaction

- src/platforms/dotnet/profiling/index.mdx
Follow up for #8862 - for now, before the final 4.0 release is out, we need to instruct users to instruct the latest prerelease version instead 3.*.*
> chore: update dotnet profiling package version

- gatsby-ssr.tsx
- vercel.json
We are moving away from Google Tag Manager and hosting the script we needed directly on our site, as a follow up to our cookie blog.
> Move plausible off Google Tag manager

- src/platforms/javascript/common/performance/instrumentation/custom-instrumentation.mdx
`startTransaction` will be removed in v8 of the JS SDK in favour of the startSpan functions. We already 
deprecated the function in out changelog, migration guide and code documentation. This PR also adds a 
deprecation note to the docs, given this is a quite prominent API.
closes https://github.com/getsentry/sentry-docs/issues/8946
> ref(js): Add deprecation note to `startTransaction` documentation

- src/platform-includes/performance/traces-sampler-as-sampler/android.mdx
- src/platforms/android/configuration/options.mdx
- src/platforms/android/manual-setup/index.mdx
- src/platforms/android/profiling/index.mdx
added enable-app-start manifest option
added small description of App Start Profiling
mention TransactionContext.isForNextAppStart in sampler functions
added profiling options in Basic Options
> Add Android App Start Profiling

- src/docs/product/accounts/early-adopter-features/index.mdx
- src/platform-includes/session-replay/setup/javascript.mdx
- src/platforms/javascript/common/session-replay/troubleshooting.mdx
Adds documention on how to setup `<canvas>` recording support in Replay. Also updates the Troubleshooting section accordingly.
Closes https://github.com/getsentry/team-replay/issues/335
Closes https://github.com/getsentry/team-replay/issues/337
Related to https://github.com/getsentry/team-replay/issues/347
> feat(replay): Add docs for canvas support in Replay

- src/docs/product/accounts/early-adopter-features/index.mdx
- src/platform-includes/session-replay/setup/javascript.mdx
This should actually be open beta rather than limited to EA.
> feat(canvas): Remove EA requirement for replay-canvas

- src/docs/product/performance/web-vitals.mdx
Add some more content around required browser support for performance score calculations. Also update firefox to include lcp support in the browser support table. (Firefox supports lcp as of version 122 released on Jan 23, 2024)
> feat(webvitals): More browser support performance score details, and Firefox LCP support

- src/platform-includes/metrics/configure/javascript.astro.mdx
- src/platform-includes/metrics/configure/javascript.bun.mdx
- src/platform-includes/metrics/configure/javascript.deno.mdx
- src/platform-includes/metrics/configure/javascript.electron.mdx
- src/platform-includes/metrics/configure/javascript.mdx
- src/platform-includes/metrics/configure/javascript.nextjs.mdx
- src/platform-includes/metrics/configure/javascript.remix.mdx
- src/platform-includes/metrics/configure/javascript.sveltekit.mdx
- src/platform-includes/metrics/configure/node.mdx
- src/platform-includes/metrics/counter-snippet/javascript.mdx
- src/platform-includes/metrics/distribution-snippet/javascript.mdx
- src/platform-includes/metrics/gauge-snippet/javascript.mdx
- src/platform-includes/metrics/set-snippet/javascript.mdx
- src/platform-includes/metrics/version-support-note/javascript.electron.mdx
- src/platform-includes/metrics/version-support-note/javascript.mdx
- src/platforms/javascript/common/metrics/index.mdx
- src/platforms/node/common/metrics/index.mdx
Documents metrics for browser JS (all the frameworks), Node, Deno, Bun, and Electron.
Reference:
- Electron: https://github.com/getsentry/sentry-javascript/discussions/10110
- Browser: https://github.com/getsentry/sentry-javascript/discussions/9938
- Node/Deno/Bun: https://github.com/getsentry/sentry-javascript/discussions/9973
> feat(js): Add JS metrics docs

- src/platform-includes/sourcemaps/legacy-uploading-methods/javascript.mdx
Sentry no longer supports finding the sourcemap file using the Sourcemap header added to files. Removing the line that explains how to use it.
> Removing sourcemap header reference

- docs/platforms/python/data-management/data-collected.mdx
Was caused by a `<br/>` at the end of the headline
> Fix headline link icon

- app/platform-redirect/page.tsx
- src/components/docPage.tsx
- src/components/serverSidebar.tsx
This endpoint is given a path (via the `next` query string param) and, optionally, a `platform` param. If a valid platform is given, a redirect happens immediately. Otherwise, a list of platform-specific links to the given path is rendered.
See [the Gatsby version](https://github.com/getsentry/sentry-docs/blob/405170000995bd8d98bd155f4e8d38ce4c19275a/src/pages/platform-redirect.tsx).
> Bring back /platform-redirect endpoint

- docs/platforms/javascript/common/performance/troubleshooting/index.mdx
- docs/platforms/node/common/performance/troubleshooting/index.mdx
- platform-includes/performance/add-spans-example/javascript.mdx
- platform-includes/performance/control-data-truncation/javascript.mdx
- platform-includes/performance/start-span/javascript.mdx
- platform-includes/performance/start-span/node.mdx
`data` is deprecated, instead users should use `attributes` for spans.
Remaining is a replacement for `span.setTag()`, I'll update this once we published https://github.com/getsentry/sentry-javascript/pull/10475 (next week).
> feat: Replace span data with attributes in JS docs

- docs/platforms/javascript/common/troubleshooting/index.mdx
- docs/platforms/node/common/troubleshooting/index.mdx
- includes/diagnostics-channel-build-error-troubleshooting.mdx
Adds troubleshooting docs for when diagnostics_channel is not available when building/bundling.
Also adds troubleshooting docs to the node.js platform.
Ref: https://github.com/getsentry/sentry-javascript/pull/10388
> Add troubleshooting docs for diagnostics_channel in JS and node

- platform-includes/performance/custom-performance-metrics/javascript.mdx
Replacement for https://github.com/getsentry/sentry-docs/pull/9015 that actually updates the code snippet.
> feat: Avoid using deprecated `getTransaction()` in JS

- docs/platforms/python/performance/instrumentation/custom-instrumentation.mdx
adds a space in on the performance instrumentation page for Python.
> Fix spacing on custom performance instrumentation

- docs/platforms/javascript/common/index.mdx
- docs/platforms/node/common/index.mdx
This adds an explicit callout to the getting started page of all JS SDKs pointing them to the migration docs. They are maybe not super intuitive to find right now, if you go search for them on the docs... We can eventually remove them again.
Note that they shouldn't actually look like errors, this is due to https://github.com/getsentry/sentry-docs/issues/9049.
> feat: Add deprecation info to JS docs

- src/build/resolveOpenAPI.ts
- src/mdx.ts
Debugged the load times using commit c8d5391d, which more than tripled local build times and more than doubled Vercel build times compared to the previous commit (baf391b1).
Initially, c8d5391d took 9:35 locally.
After caching the `apiCategories` function, the time dropped to 6:34. This method makes a `fetch` call to retrieve our OpenAPI specs - I'm suspicious that Next's fetch cache isn't working properly on this call. We only need this to run once per build anyway.
Further, caching the `getDocsFrontMatter` function dropped the build time to 5:19. This function defensively copies a large array, but the result only needs to be calculated once per build.
There's still work to be done to get all the way back down to baf391b1's build time (2:47 locally), but it's a start.
See #9020.
> Improve build times

- platform-includes/user-feedback/install/javascript.astro.mdx
The Astro code snippet header said `npx` but every other guide says `Bash`:
ex.
> fix(feedback docs): make Astro setup docs consistent

- src/docTree.ts
Caching `getDocsRootNode` improves local build times from 5:19 to 4:39, and also gets rid of a bunch of waiting (the CPU utilization during build according to `time` goes from 74% to 531%).
In Vercel this translated to an improvement from ~26 minutes to ~21 minutes - not huge, but seems worthwhile given the small size of the change.
See #9020.
> Speed up the build a little more

- docs/platforms/javascript/common/session-replay/privacy.mdx
Adds an example for scrubbing URLS from the replay event using `addEventProcessor`
Closes https://github.com/getsentry/sentry-javascript/issues/9871
> feat(replay): Add docs for scrubbing URLs on the replay event

- src/mdx.ts
The previous logic for whether `common` guide pages were applicable based on `supported` and `notSupported` tags was not the same as the old site. It was a little too strict, expecting `supported` to act as an allowlist and `notSupported` as a separate blocklist. Instead, the logic combined the two.
Copied the logic from the old Gatsby site exactly (just renaming the method): https://github.com/getsentry/sentry-docs/blob/405170000995bd8d98bd155f4e8d38ce4c19275a/src/gatsby/createPages/createPlatformPages.ts#L138-L161
Fixes a reported issue where some JavaScript guides were missing Automatic Instrumentation pages.
---
⚠️ Please note that #9056 created Automatic Instrumentation pages for many of the platforms that were missing as a result of this bug. However, the new pages are missing a lot …
> Fix `supported`/`notSupported` frontmatter logic

- .github/workflows/bump-api-schema-sha.yml
It looks like resolveOpenAPI.ts got moved when we switched from gastby to nextjs. This is the new path to the file.
https://github.com/getsentry/sentry-docs/blob/36ad36ada4d889a0975a4d3186aae6705fe05df5/src/build/resolveOpenAPI.ts#L13
---
I'm not sure how to test this directly, but the build is currently failing with errors like:
```
Run git config user.email "bot@getsentry.com"
sed: can't read src/gatsby/utils/resolveOpenAPI.ts: No such file or directory
Error: Process completed with exit code 2.
```
OR
```
0s
Run git config user.email "bot@getsentry.com"
sed: -e expression #[1](https://github.com/getsentry/sentry-docs/actions/runs/7723375200/job/21053336128#step:3:1), char 107: unterminated `s' command
Error: Process completed with exit code 1.
```
which i think are the same problem: …
> build: Update the filepath of resolveOpenAPI.ts

- platform-includes/getting-started-install/native.mdx
- platform-includes/getting-started-install/native.qt.mdx
The Native SDK doesn't support Android directly but acts as a support library for downstream SDKs. The formulation in the documentation needs to be clarified so users can understand the level at which we can support their use cases, which often deviate severely from anything we currently implement, build, or test.
In particular, Qt for Android as a combined supported scenario can easily misinterpreted even though it is not explicitly mentioned. It is better to remove "Android" from the "Getting Started" layer for Qt altogether.
cc: @kahest
> fix(native): clarify android support

- .github/workflows/bump-api-schema-sha.yml
Reverts getsentry/sentry-docs#9086
Seems like builds are not happy with this:
> Revert "build: Trim the sha list we get back from github"

- .github/workflows/bump-api-schema-sha.yml
This is following up on: https://github.com/getsentry/sentry-docs/pull/9086 (reverted in https://github.com/getsentry/sentry-docs/pull/9102)
The reason that initial attempt didn't work isn't clear to me, i think it's because the api response included funky data (sometimes) that would cause two sha's to be returned instead of the one that we expected. I'm not 100% sure exactly, but the logs for failing runs clearly show unexpected things happened like `Switched to a new branch 'bot/bump-api-schema-to-'` where no sha is suffixed to the branch name.
So this takes a different approach: ask for the sha only, and skip all the rest of the parsing business.
> build: Use Accept:application/vnd.github.VERSION.sha to get the latest sha of sentry-api-schema repo

- docs/platforms/apple/common/enriching-events/screenshots/index.mdx
- docs/platforms/apple/common/enriching-events/viewhierarchy/index.mdx
Updated screenshot and view hierarchy docs to reflect changes in the app hang not having those informations.
> fix(apple):No screenshot and view hierarchy for app hangs

- docs/platforms/javascript/guides/react/features/component-tracking.mdx
- docs/product/reference/search/searchable-properties/session-replay.mdx
Adds documentation for the new added functionality for tracking React component names in Sentry. Also includes docs for Replays, for searching for replays by components that were clicked on.
> Add content related to React component name tracking

- platform-includes/profiling/automatic-instrumentation-setup/_default.mdx
- platform-includes/profiling/automatic-instrumentation-setup/javascript.astro.mdx
- platform-includes/profiling/automatic-instrumentation-setup/javascript.react.mdx
- platform-includes/profiling/automatic-instrumentation-setup/javascript.sveltekit.mdx
Just noticed via https://github.com/getsentry/sentry-javascript/issues/10599 that some of the browser profiling docs still mentioned the deprecated integration classes
> ref(js): Update and fix browser profiling integration code snippets

- docs/platforms/apple/common/usage/distributed-tracing/index.mdx
- platform-includes/distributed-tracing/how-to-use/apple.mdx
The trace propagation target code sample was in the section of distributed tracing without an explanation, making the distributed tracing docs for Apple confusing. This is fixed now by adding an explanation and moving the trace propagation target below the distributed tracing section.
> fix(apple): Clarify trace propagation targets

- docs/platforms/apple/common/performance/instrumentation/automatic-instrumentation.mdx
Add documentation for the performanceV2 option.
> feat(apple): Add docs for performanceV2

- src/build/resolveOpenAPI.ts
Vercel build was error because we make a request for every page we generate, this add a simple cache.
> feat: Cache api schema for build

- docs/product/accounts/membership.mdx
Update docs to reflect how org members can create a new project
replaces https://github.com/getsentry/sentry-docs/pull/8725 due to migration and removes mention or org settings which haven't been implemented yet.
> update project permissions

- app/changelog/%5Fadmin/loading.tsx
- app/changelog/%5Fadmin/page.tsx
- app/changelog/[slug]/loading.tsx
- app/changelog/globals.css
- app/changelog/header.tsx
- app/changelog/loading.tsx
- app/changelog/page.tsx
- tailwind.config.js
Added a few loading states to make it feel more snappy
> feat: Add Changelog loading states

- platform-includes/getting-started-primer/javascript.astro.mdx
We were notified that the Astro SDK cause runtime errors when an Astro app is deployed to Netlify using the  Netlify adapter <5.0.0. There seems to be a bug in the adapter that causes `@sentry/cli` to be bundled and required at runtime which shouldn't happen.  
The issues are resolved after upgrading to version 5.x of the adapter, so let's set this as a minimum version.
> ref(astro): Add Netlify adapter compatibility note

- app/changelog/layout.tsx
- package.json
- yarn.lock
https://github.com/getsentry/sentry-docs/assets/363802/288afcf6-bf29-4c45-9e99-90330ea4f519
> feat: Add top loader to indicate action

- platform-includes/getting-started-config/javascript.deno.mdx
- platform-includes/getting-started-sourcemaps/javascript.deno.mdx
When testing this Deno CLI complained about the order of arguments in the script. This is how i tried it from the docs
```
me@me deno-edge-hello-world % deno run index.ts --allow-net=xxxxx.ingest.sentry.io
Permission flags have likely been incorrectly set after the script argument.
To grant permissions, set them before the script argument. For example:
deno run --allow-read=. main.js
error: Module not found "file:///Users/steveneubank/Desktop/deno-edge-hello-world/index.ts".
```
Flipping the order as instructed works
> Deno arguments are not in the correct order

- vercel.json
This feature will allow us to early detect any missing pages. Missing pages (404s) and other network errors will be reported to [nel-docs](https://sentry.sentry.io/issues/?project=4506750822580224) project.
Example of 404 error: https://sentry.sentry.io/issues/4980212157/?project=4506750822580224
For now, sampling reports at 5% and policy duration of 1 hour.
> Enable Network Error Logging

- docs/product/issues/suspect-commits/index.mdx
Add a trailing slash to the example value given for the source code root, making it consistent with the screenshot and the other surrounding references. 
An alternative might be to instead remove the trailing slash from `src/` earlier in the sentence, but it seemed more confusing to then have the slashes in the values used later on. …
> Make trailing slashes consistent in code mapping example

- docs/platforms/kotlin-multiplatform/swift-package-manager.mdx
https://github.com/getsentry/sentry-kotlin-multiplatform/issues/176
> KMP: Add test section for SPM usage in KMP

- platform-includes/getting-started-primer/native.mdx
related: https://github.com/getsentry/sentry-native/pull/952
cc @supervacuus
> chore(native): add note that standalone native sdk is experimental

- app/platform-redirect/page.tsx
Fixes the site, if URL param `next` hasn't been provided
> Fix platform redirect

- platform-includes/enriching-events/breadcrumbs/breadcrumbs-example/native.mdx
In the same vein as this: https://github.com/getsentry/sentry-native/pull/951
There is currently no example in the docs that clarifies the necessity of a wrapping object for the `data` property in breadcrumbs. Users tried to assign JSON as a string for instance.
The example is straight out of the develop docs: https://develop.sentry.dev/sdk/event-payloads/breadcrumbs/#breadcrumb-types. Not sure if we should mention this, because the surroundings docs already do.
cc: @kahest
> fix(native): provide an example for the breadcrumb data property

- docs/platforms/javascript/common/install/loader.mdx
Splitting out and bolding the instruction to include the Sentry.init code _before_ the loader script for Browser JavaScript.
Note: I missed this instruction MULTIPLE times so hopefully this helps other people with my limited reading and comprehension skills. 😅
> Bold and separate instructions for adding init code before loader script

- docs/platforms/python/integrations/bottle/index.mdx
- docs/platforms/python/integrations/django/index.mdx
- docs/platforms/python/integrations/falcon/index.mdx
- docs/platforms/python/integrations/flask/index.mdx
- docs/platforms/python/integrations/pyramid/index.mdx
- docs/platforms/python/integrations/wsgi/index.mdx
- includes/python-uwsgi-warning.mdx
We've had bug reports from folks in the Python SDK that were due to incorrect uWSGI server setup. Since the impact of such misconfiguration can be severe (uWSGI workers crashing), we should call this out in the docs of all integrations that can be used with uWSGI.
See https://github.com/getsentry/sentry-python/pull/2738
Note to the docs team: If there's a way to reuse the same warning on multiple pages, please let me know!
> ref(python): Add a warning about uWSGI to all WSGI frameworks

- next.config.js
This is to fix preview builds and asset loading - we only want to load assets with absolute URL in production
> fix: Reverse logic to explicitly just check for IS_PRODUCTION

- app/changelog/header.tsx
- src/components/changelog/article.tsx
For our rewrite from sentry.io/changelog the Next.js Image component doesn't seem to work
> ref: Don't use Image for rewrite

- src/components/banner.tsx
Added banner for Sentry Launch Week
> Launch Week Banner

- platform-includes/session-replay/pre-requisites/javascript.capacitor.mdx
- platform-includes/session-replay/setup/javascript.capacitor.mdx
Just a nit here the minimum version that supports Replay on Capacitor is 0.11.0
It can be validated here: https://github.com/getsentry/sentry-capacitor/blob/main/CHANGELOG.md#0110 
> fix(capacitor): correct min version  for Sentry Capacitor

- platform-includes/performance/start-span/javascript.mdx
Add extra note about `startSpanManual`, and clarify start span behaviour around returning callbacks.
> add extra clarity to start span snippet

- src/docTree.ts
- src/mdx.ts
- src/platformsData.ts
React's `cache` function does not work the way I expected, and actually wasn't caching properly. Replace usages of it with memoization, which is more verbose but definitely works.
Locally, this sped up `yarn build` to 201 seconds, which is much faster than the previous local build time.
> Fix caching during build

- docs/platforms/android/configuration/options.mdx
- docs/platforms/apple/common/configuration/options.mdx
- docs/platforms/flutter/configuration/options.mdx
- docs/platforms/react-native/configuration/options.mdx
fixes https://github.com/getsentry/sentry-docs/issues/8794
for all applicable platforms
> fix: Config option typo in `attachViewhierarchy`

- app/changelog/%5Fadmin/[id]/edit/page.tsx
- app/changelog/%5Fadmin/confirm.tsx
- app/changelog/%5Fadmin/create/page.tsx
- app/changelog/%5Fadmin/layout.tsx
- app/changelog/%5Fadmin/loading.tsx
- app/changelog/%5Fadmin/page.tsx
- app/changelog/%5Fadmin/upload/route.tsx
- app/changelog/[slug]/loading.tsx
- app/changelog/[slug]/page.tsx
- app/changelog/api/auth/[...nextauth]/route.ts
- app/changelog/error.tsx
- app/changelog/not-found.tsx
- app/changelog/page.tsx
- src/actions/changelog.ts
- src/components/changelog/article.tsx
- src/prisma.ts
Setting `&connection_limit=1` in the postgres url in the environment.
See: https://www.prisma.io/docs/orm/prisma-client/setup-and-configuration/databases-connections#the-serverless-challenge
At least locally when there was an error the page constantly refreshed - adding the error page fixed this. Also added proper not found page while at it.
So I am still not certain this will prevent it from exploding again, I hope the connection limits are properly set now (there are only two functions running the changelog).
> Revert "Add Changelog Maintence (#9236)"

- includes/react-native-expo-plugin-code-snippet.mdx
- related to https://github.com/getsentry/sentry-react-native/pull/3630
This PR removed the `authToken` option example as using it is not safe to use (the token can be easily exposed).
> fix(rn): Remove unsafe `authToken` option from the Expo setup page

- docs/platforms/node/common/metrics/index.mdx
I spent time implementing this and being confused by nothing showing up in my dashboards. I didn't realize Sentry Metrics was _another product_, with a waitlist and all that.
> Include a warning about alpha on node metrics integration docs

- docs/platforms/dotnet/metrics/index.mdx
- docs/platforms/javascript/common/metrics/index.mdx
- docs/platforms/php/common/metrics/index.mdx
- docs/platforms/php/guides/laravel/metrics/index.mdx
- docs/platforms/python/common/metrics/index.mdx
- docs/platforms/react-native/metrics/index.mdx
A user pointed out that he was confused when he tried to add metrics and was taken to a waiting list. It's definitely a good call to add the note about this being an alpha release to the SDK set up docs! :)
PS - I didn't edit the node docs because the user who pointed this out already created his own PR for this.
> add alpha note

- docs/platforms/python/integrations/django/index.mdx
Correct the issue in the docs which state that `cache_spans` is enabled by defaults. This is not the case, it's actually disabled by default. …
> fix: cache_spans are False by default

- docs/platforms/javascript/common/profiling/index.mdx
- src/components/platformOrGuideName.tsx
- src/components/platformSdkPackageName.tsx
- src/mdxComponents.ts
This PR adds two components that return the name and SDK package name of the currently selected platform.
- `PlatformSdkPackageName` returns the package name, e.g. `@sentry/nextjs`
- `PlatformOrGuideName` returns the name of the currently selected platform or guide, e.g. `Next.JS`
Motivation: We have a lot of pages where we statically write a package name (e.g. `@sentry/browser`) which doesn't change when users select a guide (e.g. NextJS). This leads to confusion. Reportedly from SEs, thought they'd need to install _and initialize_ the browser SDK in addition to the NextJS SDK. 
Alternatives: Sure, we could also copy the guide per platform (IIRC we did this for Replay a while back) but it's arguably more work if the changes between these files are literally the name of a package or …
> feat: Add `PlatformOrGuideName` and `PlatformSdkPackageName` components

- docs/product/session-replay/performance-overhead.mdx
The `sub` seemed to not wrap text properly.
The issue comes from the way MDX interpreted the the markdown to HTML conversion with a weird `p` and `ul` tags inside the `sub`
Escaping the `*` and keeping the opening and closing `sub`s inline with the text fixes it.
This PR closes #9028  …
> fix: overlapping sub when text is too long

- app/layout.tsx
- src/components/expandable.tsx
the hydration errors are coming from the generated HTML by MDX, which we can't really control in any simple way
I just suppressed using [`suppressHydrationWarning`](https://nextjs.org/docs/messages/react-hydration-error#solution-3-using-suppresshydrationwarning)
I also took the liberty to fix a warning on a Styled Component of an unrecognized prop on a DOM node
Overall we have less noise on the dev console :)
This PR closes: #9055  …
> Hydration errors and other noise

- src/components/codeKeywords.tsx
The DSN selector didn't work due to a race condition. Removing the memoization of the `getPortal()` function fixes it.
The performance impact is probably negligible as `getElementById()` is pretty fast and `getPortal()` is not in a hot path.
This PR closes #9092 
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute …
> fix: DSN selector not working sometimes

- src/components/tableOfContents.tsx
fixes: #9115  #9012 #9068 
For every link in …
> FIx: Right Sidebar(Table of contents) anchor url fixed

- docs/product/performance/mobile-vitals/app-starts.mdx
Missed a `/` so the link would just append to the URL instead of going to the right place
> fix(app-start): Fix broken link to iOS performanceV2 flag

- src/components/home.tsx
Bring back the alphabetical platform sorting from the Gatsby docs.
This PR closes #9219
> fix: sort platforms dropdown in alphabetical order

- src/components/alert.tsx
- src/styles/_includes/bootstrap-overrides.scss
Brand pink on `info` level `Alert`s looks like an error.
I gave it the traditional Bootstrap colors (using the our theme) and added some types for better autocomplete.
This PR closes #9049 
- [Sentry Docs …
> fix: Alert level colors

- src/components/codeBlock.tsx
Hide the copy button on code blocks until it is interactive
This PR closes #8139
> fix: hide non functioning copy button on slow connections

- docs/product/session-replay/getting-started.mdx
> fix brand name for platform

- docs/platforms/python/migration/1.x-to-2.x.mdx
- package.json
- src/mdx.ts
- src/styles/_includes/code-blocks.scss
- yarn.lock
This PR adds:
1. styles for specific line callouts on code blocks using the `{lineNuber}` syntax or `{from-to}` thanks to [`rehype-prism-plus`](https://github.com/timlrx/rehype-prism-plus)
2. Inline diffs support by prepending `+` or `-` to the lines and adding `diff` to the code block metatdata using [`rehype-prism-diff`](https://github.com/enpitsuLin/rehype-prism-diff/tree/master?tab=readme-ov-file#rehypre-prism-diff) (new dependency)
The inline diffs keep the foreign symbols upon selection and copying although it shouldn't in theory (as per the package docs), we can investigate this further if necessary.
Example, this snippet:
<pre>
```javascript {tabTitle:ESM} {3-4} …
```
> Codeblock highlight callouts and diffs

- src/components/search.tsx
> fix: show results from other Sentry sites when user clicks corresponding button

- platform-includes/performance/configure-sample-rate/python.mdx
See https://github.com/getsentry/sentry-docs/issues/8771
We say that performance monitoring is available since version 0.11.2, but then use an option that was only added in version 1.16 in the setup example.
Adding a note to clarify.
**Direct link to preview:** https://sentry-docs-git-ivana-enable-tracing-not-available-in-old-sdk.sentry.dev/platforms/python/performance/#configure
Fixes https://github.com/getsentry/sentry-docs/issues/8771 …
> fix(python): Clarify how to set up tracing in older SDK

- docs/platforms/javascript/guides/nextjs/manual-setup.mdx
Adds a note to Next.js docs about tunnelRoute being incompatible with Next.js middleware and how to resolve.
> Add note to Next.js docs about `tunnelRoute` clashing with middleware

- src/components/serverSidebar.tsx
- src/files.js
- src/mdx.ts
This brings back the legacy guides (with `draft: true` in the front matter) without showing them on the sidebar navigation
Closes #9224 
> No legacy links on sidebar

- docs/product/metrics/metrics-set-up.mdx
- RN metrics added in https://github.com/getsentry/sentry-docs/pull/9119
- This PR adds only the link
>  Add React Native to metrics SDKs list

- docs/platforms/javascript/common/configuration/integrations/breadcrumbs.mdx
- docs/platforms/javascript/guides/deno/configuration/integrations/breadcrumbs.mdx
In this PR https://github.com/getsentry/sentry-javascript/pull/10867, the options `xhr`, `history` and `dom` were removed from the breadcrumbs Integration for Deno. The base for the breadcrumbs docs file is located in `commons`.
> feat(js/deno): Remove options `xhr`, `history` and `dom` from deno breadcrumbs

- docs/platforms/javascript/common/configuration/integrations/breadcrumbs.mdx
- docs/platforms/javascript/common/configuration/integrations/dedupe.mdx
- docs/platforms/javascript/common/configuration/integrations/functiontostring.mdx
- docs/platforms/javascript/common/configuration/integrations/globalhandlers.mdx
- docs/platforms/javascript/common/configuration/integrations/httpcontext.mdx
- docs/platforms/javascript/common/configuration/integrations/inboundfilters.mdx
- docs/platforms/javascript/common/configuration/integrations/linkederrors.mdx
- docs/platforms/javascript/common/configuration/integrations/trycatch.mdx
This PR changes the wording of the first line in default integrations. The link is now called "modify default integrations" to make it more clear where the link navigates to.
ref https://github.com/getsentry/sentry-docs/pull/9295
> ref(JS/integrations): Slightly change info about default integration

- docs/platforms/native/configuration/backends/crashpad.mdx
This an outcome of a recent support discussion with one of our users: https://github.com/getsentry/sentry-native/discussions/881#discussioncomment-8640854
cc: @kahest
> fix(native): clarify use of crashpad in macOS sandbox

- docs/platforms/python/configuration/options.mdx
Adding docs for https://github.com/getsentry/sentry-python/pull/2786
Direct link to preview: https://sentry-docs-git-ivana-python-socket-options.sentry.dev/platforms/python/configuration/options/
- [Sentry Docs …
> feat(python): Add new config option

- docs/product/alerts/alert-types.mdx
- docs/product/alerts/create-alerts/metric-alert-config.mdx
Adds a note about filtering archived issues from metric alerts. See changelog https://changelog.getsentry.com/announcements/removing-archived-issues-from-metric-alerts
> feat(alers): Update note about filtering out archived issues

- docs/product/performance/mobile-vitals/screen-loads.mdx
This link was missed when the new page was created. The section that it intends to link to is up a level in the Mobile Vitals docs.
> fix(mobile-vitals): Link to TTFD from screens module page

- docs/product/performance/web-vitals/index.mdx
- docs/product/performance/web-vitals/web-vitals-concepts.mdx
- Split up web vitals page into 2 pages, creating separate pages for the product walkthrough and the concepts. 
- Make the concepts a child of the web vitals product page. 
- Update links. 
- Add intro text. 
This PR is just to split up the page (no content changes for INP yet). If this structure looks good, we can merge this first and then focus on updating the pages with INP info in another PR.
> split up web vitals page into 2

- src/components/pageGrid.tsx
Don't render nodes with not front matter on `PageGrid`
Closes #9324 
> fix: empty bullet item on PageGrid

- app/[[...path]]/page.tsx
- src/utils.ts
Append ` | Sentry for "Platform"` on page titles
Closes #9311 
> feat: append platform or guide name to page title

- src/components/codeBlock.tsx
- src/styles/_includes/code-blocks.scss
This was due to the nuance how browsers handle `.textContent` vs `.innerText` and `display: block;` on individual lines that was necessary for the diff/line highlighting.
I can't believe I overlooked it earlier 🙈 
Closes #9384, #9380 …
> Fix: extra line breaks upon copying code snippets

- docs/product/alerts/index.mdx
Remove a line about proactively disabling alerts that refers to a project we ended up not going through with. We do not do this.
> ref(alerts): Remove line about proactively disabling alerts

- docs/product/relay/projects.mdx
Document the fact that Relay can enable individual feature flags in static mode.
ref: https://github.com/getsentry/relay/issues/3175
> List features in relay docs

- docs/platforms/go/common/profiling/index.mdx
Combine snippets, no stand alone for enabling performance
Cleaned up some repetive info on the page and snippets
there are 2 notes for go being in alpha, should also be combined IMO, feeling lazy atm
> [go] Condense Profiling Setup Docs

- docs/platforms/javascript/guides/remix/manual-setup.mdx
- platform-includes/getting-started-install/javascript.remix.mdx
- platform-includes/getting-started-sourcemaps/javascript.remix.mdx
- platform-includes/performance/configure-sample-rate/javascript.remix.mdx
- platform-includes/session-replay/install/javascript.remix.mdx
- platform-includes/sourcemaps/overview/javascript.remix.mdx
- platform-includes/user-feedback/install/javascript.remix.mdx
- Adds instructions for how to configure sourcemaps upload with Vite plugin. (Resolves: #9411)
- Separates `server` and `client` init examples for better visibility. (Related: #6171)
- Mentions example page generation feature of Remix wizard. (Ref: https://github.com/getsentry/sentry-wizard/pull/542)
- Also updates usage for Vite-dev mode workaround for SDK versions < 7.106.0 (Ref: https://github.com/getsentry/sentry-javascript/pull/10784)
> feat(remix): Update Remix documentation.

- platform-includes/replay/privacy-configuration/javascript.mdx
ref https://github.com/getsentry/sentry-javascript/pull/11049
> feat(js/replay): Opt-in options for unmask and unblock 

- app/[[...path]]/page.tsx
- app/sitemap.ts
- src/mdx.ts
@lizokm reported that only some of the pages in the sitemap.xml were being indexed properly. This was caused by an extra trailing `/index` in many of the paths. This is something that the main Page component already handles, but it was missed in the sitemap. Moved this fix up a level (into `getDocsFrontMatter()`) so that it didn't have to be duplicated into both the page and the sitemap, and so that future callers don't run into this same oversight.
> Fix sitemap paths

- docs/platforms/react-native/sourcemaps/uploading/expo.mdx
- context https://github.com/getsentry/sentry-react-native/issues/3659
> misc(expo): EAS Update source maps has no release associated note

- docs/product/data-management-settings/scrubbing/advanced-datascrubbing.mdx
Link to the default scrubbed filters from the `**` selector in the data scrubbing sources docs.
Resolves https://github.com/getsentry/sentry/issues/66932.
> fix(scrubbing): Mention default data scrubbing settings

- platform-includes/enriching-events/attach-screenshots/flutter.mdx
Adds Screenshot Filtering code snippet
Closes https://github.com/getsentry/sentry-docs/issues/9408
> Add filtering to Flutter screenshots

- docs/product/security-policy-reporting.mdx
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-to)
>The Content-Security-Policy Report-To HTTP response header field instructs the user agent to store reporting endpoints for an origin.
the `report-to` directive seems need to be configured as following 
```
Content-Security-Policy: …; report-to groupname
```
and then  `Report-To` header contains the definition of the group with the above defined name
fix: https://github.com/getsentry/sentry-docs/issues/9199
fix: https://github.com/getsentry/sentry/issues/52794
related to: https://github.com/getsentry/sentry/issues/38940 and https://github.com/getsentry/relay/issues/2645
@oioki  just to double check if that makes sense. 
We also use the `report-to` configuration with similar …
> Use report-to with group which configured in the separate header

- docs/platforms/javascript/common/configuration/options.mdx
Adds a note to the JS Basic Options docs calling out a potential "gotcha" when working in frameworks that require an environmental variable prefix to expose their value to the client.
This PR resolves issue #9441  …
> Add a "good to know" note to JS Basic Options docs

- docs/product/performance/web-vitals/index.mdx
Moves up the explainer for the overall performance score and adds note about minimum latency for INP candidates which links out to the google webvitals library
> feat(webvitals): Moves overall perf score explainer up and add min latency for inp

- src/remark-variables.js
This prevents showing empty code blocks when `@inject` variables interpolation fails.
An error is logged to the console in development mode, and the build fails in prod.
Closes #3004 
> feat: fail production build process upon @Inject variable interpolation failure

- src/components/codeContext.tsx
- src/components/codeTabs.tsx
This comes at the expense of some inevitable hydration errors
This is useful for platforms like Java/Kotlin where it makes more sense to have the selection survive a page reload
**Caveat**: this introduces a jump after hydration if the stored selection is different from the default (first one)
Ideally this info should be stored in a cookie, but we can't do it since the pages are statically generated.
Closes #3051 …
> Feat: Persist code block tab selection to locaStorage

- docs/platforms/python/configuration/environments.mdx
- platform-includes/set-environment/python.mdx
Updated the "environments" page of the Python docs. I included the default value and the possibility to set it via env var. I also improved the code snippet by not setting the environment to the default value, which would not make sense at all. 
Preview:
https://sentry-docs-git-antonpirker-python-configuration-environment.sentry.dev/platforms/python/configuration/environments/
> [Python] Updated the environment configuration

- docs/platforms/python/integrations/django/http_errors.mdx
- docs/platforms/python/usage/set-level/index.mdx
I updated the docs to include links to the autogenerated APIdocs that list the possible values for `level`.
Fixes: #5432
There is also a PR in the Python Repo where I updated the APIdocs, that will be released soon: https://github.com/getsentry/sentry-python/pull/2828
> Added links to APIdocs where the levels are listed

- docs/platforms/python/configuration/draining.mdx
- docs/platforms/python/configuration/filtering/index.mdx
- docs/platforms/python/configuration/releases.mdx
- docs/platforms/python/configuration/sampling.mdx
- docs/platforms/python/configuration/sessions.mdx
I updated the "Releases" page in the Python docs to include information how the SDK guesses the `release` if none was specified and also included information that one can set the `SENTRY_RELEASE` environment variable. 
I also removed some stuff where we explain how semantic versioning works and just linked to the official website.
I also renamed the page from "Releases & Health" to just "Releases" (because "Health" is nowhere used in the sentry.io UI) and added a page for "Sessions". In both ("Releases" and "Sessions") I describe how releases and sessions are used to track the health of the system.
Preview:
https://sentry-docs-git-antonpirker-python-releases-sessions.sentry.dev/platforms/python/configuration/releases/
https://sentry-docs-git-antonpirker-python-releases-sessions.sentry.dev/ …
> [Python] Updated releases and sessions documentation

- docs/platforms/python/configuration/environments.mdx
- docs/platforms/python/configuration/releases.mdx
Make it clear how the configuration of `release` and `environment` can be set and in what order the SDK tries the different ways to set those options.
> [Python] Describe precedence of `release` and `environment` configuration

- docs/platforms/python/integrations/arq/index.mdx
Corrected the file extensions `run.py`
> Update index.mdx for arq integration

- docs/platforms/android/integrations/okhttp/index.mdx
[Android OkHttp integration docs still refer](https://docs.sentry.io/platforms/android/integrations/okhttp/) to the deprecated `sentry-android-okhttp` package. The [Java page](https://docs.sentry.io/platforms/java/performance/instrumentation/okhttp/) has already been updated.
> chore(okhttp): Update Android OkHttp integration docs to sentry.okhttp

- docs/platforms/python/integrations/celery/crons.mdx
With https://github.com/getsentry/sentry-python/issues/2616 and https://github.com/getsentry/sentry-python/pull/2643 we'll be adding support for a new Celery Beat scheduler (Redbeat).
> feat(crons): Add Redbeat as supported scheduler

- docs/platforms/java/common/performance/instrumentation/apollo.mdx
- docs/platforms/java/common/performance/instrumentation/apollo3.mdx
- docs/platforms/java/common/performance/instrumentation/jdbc.mdx
- docs/platforms/java/common/performance/instrumentation/okhttp.mdx
- docs/platforms/java/common/performance/instrumentation/open-feign.mdx
- docs/platforms/java/common/performance/instrumentation/opentelemetry.mdx
now that the package sidebar shows correct info for integrations, it's worthwhile to set the correct SDK names for integrations in the docs. as a followup, we may want to add more specific info (e.g. repo or api docs links) to the relevant [release registry](https://github.com/getsentry/sentry-release-registry) items.
> chore(java): Add SDK names for Java integrations

- docs/platforms/node/common/configuration/integrations/default-integrations.mdx
Explicitly state "outgoing" connections. Mainly because I confused myself regarding the next version's [instrumentation of incoming requests](https://github.com/getsentry/sentry-javascript/blob/develop/docs/v8-node.md#plain-node--unsupported-frameworks) versus the current integration's instrumentation of outgoing requests. …
> Explicitly state "outgoing" connections

- docs/product/integrations/source-code-mgmt/github/index.mdx
- docs/product/issues/suspect-commits/index.mdx
**Adds PHP to the list of platforms which have automatic stack trace linking enabled in the Github integration page and the suspect commit page.**  
**Before:**
**After:**
**Before:**
**After:**
> feat(code-mappings): Add PHP to supported platforms for automatic code amppings

- docs/product/data-management-settings/scrubbing/advanced-datascrubbing.mdx
The backticks make it seem like the actual selector that relay applies.
> ref(data-scrubbing): Remove ambiguity in specific selectors

- vercel.json
Migrating away from deprecated `report-uri` to the new `report-to` keyword (ingestion implemented in https://github.com/getsentry/relay/pull/3277). …
> fix(csp): migrate to new `report-to` directive

- docs/platforms/android/performance/index.mdx
- docs/platforms/apple/common/performance/index.mdx
- docs/platforms/dart/performance/index.mdx
- docs/platforms/dotnet/common/performance/index.mdx
- docs/platforms/flutter/performance/index.mdx
- docs/platforms/go/common/performance/index.mdx
- docs/platforms/java/common/performance/index.mdx
- docs/platforms/javascript/common/performance/index.mdx
- docs/platforms/native/common/performance/index.mdx
- docs/platforms/node/common/performance/index.mdx
- docs/platforms/php/common/performance/index.mdx
- docs/platforms/powershell/performance/index.mdx
- docs/platforms/python/performance/index.mdx
- docs/platforms/react-native/performance/index.mdx
- docs/platforms/ruby/common/performance/index.mdx
- docs/platforms/rust/common/performance/index.mdx
- docs/platforms/unity/performance/index.mdx
The `tracesSampler` function is mentioned in the performance docs, but no example is provided. Added a link to an respective example.
> feat(tracing): Add link to `tracesSampler` example

- docs/platforms/javascript/common/configuration/micro-frontend-support.mdx
- current doc is structured around components of the solution, this restructures it around use-cases: Automatic and Manual
- remove the other sample `beforeSend` code that didn't get [the `slice(-1)` fix](https://github.com/getsentry/sentry-docs/pull/8515).
- [Automatic] changes to the "_Once metadata has been injected into modules..._" paragraph
- [Manual] Add a note about importance of using local scope …
> Simplify/reorganize Micro Frontend Suport

- app/layout.tsx
We need to ensure that the docs site has the following meta tag:
<meta name='zd-site-verification' content='ocu6mswx6pke3c6qvozr2e' />
This will allow Zendesk's Help Center to crawl the site and index docs content for search.
More info here: https://support.zendesk.com/hc/en-us/articles/4593564000410-Setting-up-the-search-crawler
> add zd-site-verification meta tag

- docs/product/data-management-settings/filtering/index.mdx
People sometimes ask where they can find the list of errors being filtered out. It would be hard to keep this updated in both places so we were thinking a link to the source code would work.
> docs(issues): Add link to browser extension filters list

- docs/platforms/javascript/common/session-replay/troubleshooting.mdx
Adds troubleshooting section for canvas being tainted
Fixes https://github.com/getsentry/sentry-docs/issues/9515
> feat(replay): Replay canvas troubleshooting docs

- platform-includes/sourcemaps/legacy-uploading-methods/javascript.mdx
This change adds the required scopes to authenticate the sentry-cli in order to run sourcemaps explain and upload the files to sentry. 
Which is not supported by org tokens with scope `org:cli`
> adding scopes to sentry-cli explain command

- docs/platforms/flutter/migration.mdx
> fix(flutter): Flutter migration docs missing _flutter

- docs/product/crons/troubleshooting.mdx
Adding a section here to describe the new broken monitor UX
https://github.com/getsentry/team-crons/issues/157
> feat(crons): Document new broken monitors UX

- docs/product/profiling/performance-overhead.mdx
Since we have 2 sections called "performance overhead" we want to make it clear that this is profiling
> Clarify performance overhead for profiling

- docs/product/session-replay/getting-started.mdx
The prev diff https://github.com/getsentry/sentry-docs/pull/9594 changed from 1.20 to 1.25. There's no functional difference between 1.20 and 1.25, so the update doesn't help users. The real benefit to users comes from v1.26 where tracing without performance was released.
See the release notes here: https://github.com/getsentry/sentry-python/releases/tag/1.26.0
fixes https://github.com/getsentry/sentry/issues/67973
> Python SDK 1.26 is the release where tracing without performance was released

- docs/platforms/python/crons/troubleshooting.mdx
- platform-includes/crons/setup/python.mdx
We'll be adding support for monitoring async functions in https://github.com/getsentry/sentry-python/pull/2912:
* added a note about the minimal version to the main Python crons page
* simplified the examples on the crons page into more digestible code snippets
* added a note to the crons troubleshooting page as well since we had customers asking about this
Direct link to preview:
* https://sentry-docs-git-ivana-python-async-crons.sentry.dev/platforms/python/crons/
* https://sentry-docs-git-ivana-python-async-crons.sentry.dev/platforms/python/crons/troubleshooting/
> ref(crons): Simplify example, add async note

- docs/platforms/python/common/metrics/index.mdx
- docs/platforms/python/performance/instrumentation/performance-metrics.mdx
- platform-includes/metrics/metrics-units/python.mdx
This PR adds the available options for configuring metrics in Python and also added the units available in Python.
Preview: https://sentry-docs-git-antonpirker-python-metrics-options-and-units.sentry.dev/platforms/python/metrics/
Related to: https://github.com/getsentry/sentry-docs/issues/9509
> [Python] Added available options and units to metrics documentation

- docs/platforms/javascript/common/troubleshooting/index.mdx
`Hub` is deprecated and users can already use `Scope` in v7
> fix(troubleshooting): Update deprecated Hub code

- docs/platforms/javascript/guides/react/features/error-boundary.mdx
Based on a slack convo: https://sentry.slack.com/archives/C28MX5WAJ/p1712172008252529
Q from slack: This is interesting.. so in a non-prod environment, should 2 issues appear in the issue stream then? Because the expected eventID (__EVENT_ID__) did not reach their Org even though there's a sampleRate of 1.
A: It doesn't because of how react dev mode works. This docs change should make that more clear.
> Clarify error boundary react behaviour

- docs/platforms/apple/common/install/cocoapods.mdx
- platform-includes/getting-started-install/apple.macos.mdx
- platform-includes/getting-started-install/apple.mdx
- platform-includes/getting-started-install/apple.tvos.mdx
- platform-includes/getting-started-install/apple.watchos.mdx
We already recommend installing the Cocoa SDK via SPM [in the wizard](https://github.com/getsentry/sentry/blob/master/static/app/gettingStartedDocs/apple/apple-macos.tsx#L79). Let's also change it in the docs to align.
> feat(apple): Recommend installing via SPM

- docs/platforms/apple/common/profiling/index.mdx
- platform-includes/getting-started-config/basic-config/apple.mdx
Updates `enableAppLaunchProfiling` option name in code snippets and adds a mention the option in the relevant docs section
> chore(ios): Updates `enableAppLaunchProfiling` option name

- docs/platforms/javascript/common/best-practices/browser-extensions.mdx
Some default integrations which use the global state should not be included when using Sentry in a browser extension.
> fix(browser-extensions): Exclude global state integrations in browser extensions

- docs/platforms/java/guides/spring-boot/performance/instrumentation/automatic-instrumentation.mdx
We should wait until https://github.com/getsentry/sentry-java/pull/3199 has been released before merging this PR.
- …
> Document RestClient and WebClient for Spring Boot

- platform-includes/session-replay/setup/javascript.mdx
Add a note about privacy to session replay set up docs.
closes: https://github.com/getsentry/sentry-docs/issues/8878
> add privacy section to session replays

- docs/platforms/python/crons/index.mdx
With https://github.com/getsentry/sentry-python/pull/2929 we'll be adding cron upserts to the Python SDK.
Also documenting manual check-ins which were missing.
Direct link to preview: https://sentry-docs-git-ivana-python-cron-upsert.sentry.dev/platforms/python/crons/
> feat(python): Improve crons docs, add upserts

- docs/platforms/python/integrations/django/index.mdx
We'll be adding a new option to the Django integration in https://github.com/getsentry/sentry-python/pull/2758 -- documenting it here.
> feat(django): Add `signals_denylist` as new option
