getsentry/sentry-docs

- src/platform-includes/getting-started-install/react-native.mdx
- src/platforms/react-native/troubleshooting.mdx
> fix skd typo

- src/platform-includes/getting-started-config/apple.mdx
- src/wizard/apple/ios.md
Added explanation for Swift concurrency support
> feat(apple): Swift concurrency support

- src/platform-includes/getting-started-primer/react-native.mdx
Some APM features were not listed on the getting started page.
> Add missing APM features to the RN getting started page

- src/docs/product/cli/configuration.mdx
Cause currently [this page](https://docs.sentry.io/product/cli/configuration/) looks like this:
- [Sentry Docs …
> Update configuration.mdx: formatting

- src/platforms/javascript/common/session-replay/troubleshooting.mdx
> Fixed typo

- src/docs/product/integrations/issue-tracking/jira/index.mdx
Update the help link for jira server errors
> Fix broken help link

- src/docs/product/alerts/create-alerts/metric-alert-config.mdx
Reverts getsentry/sentry-docs#7088
> Revert "feat(alerts): Add new common tags"

- src/platforms/common/enriching-events/context.mdx
> Clarify structured context nesting

- vercel.json
Adding Plausible analytics to CSP as part of Plausible trial.
> add plausible to csp

- src/docs/contributing/environment.mdx
> add node version note

- src/platforms/common/configuration/options.mdx
> feat(apple): Update Apple Tracing Options

- package.json
- yarn.lock
Fixes performance on MacOS M2 development machines
> ref: Upgrade link checker

- src/platforms/react-native/manual-setup/manual-setup.mdx
> Add Sentry AGP to RN docs

- vercel.json
Add redirects for URLs like this: /platforms/node/guides/gcp-functions/sourcemaps/best-practices/
> add redirects for sourcemaps best practices

- src/platforms/react-native/upload-debug.mdx
related to https://github.com/getsentry/sentry-react-native/issues/2748
> Add iOS source context info to RN debug symbols page

- src/platforms/flutter/troubleshooting.mdx
Fixed https://github.com/flutter/flutter/issues/73652 for Flutter 3.3.0 and above.
> Fix Flutter version on Windows

- src/platforms/android/common/gradle.mdx
`includeNativeSources` only works with `uploadNativeSymbols` enabled.
related to https://github.com/getsentry/sentry-docs/pull/7144#discussion_r1229173062 and https://github.com/getsentry/sentry-android-gradle-plugin/pull/509
> Update SAGP `includeNativeSources` doc

- src/platform-includes/getting-started-config/javascript.react.mdx
- src/platform-includes/performance/configure-sample-rate/javascript.react.mdx
- src/platforms/common/index.mdx
https://github.com/getsentry/sentry-docs/issues/7132
> Update javascript.react router snippets

- src/platform-includes/sourcemaps/overview/javascript.vue.mdx
- src/platform-includes/sourcemaps/upload/esbuild/javascript.mdx
- src/platform-includes/sourcemaps/upload/rollup/javascript.mdx
- src/platform-includes/sourcemaps/upload/vite/javascript.mdx
Fixes https://github.com/getsentry/sentry-docs/issues/7158
The amount of times I added this error by now is embarrassing.
> Fix faulty env vars in bundler plugin code snippets

- src/platforms/javascript/common/session-replay/configuration.mdx
helps clarify: https://github.com/getsentry/sentry/issues/50919
> replay: network regex example

- src/components/codeBlock.tsx
- src/utils.ts
It was not opening because the clicked element was the referenceEl
> fix(ui): keyword dropdown selector

- src/platforms/java/common/performance/instrumentation/apollo3.mdx
Making the same changes across both pages so they match.
> Update Apollo3.mdx for Java to match the one for Android

- .github/workflows/test.yml
> ref(ci): Remove node version from cache key

- package.json
- yarn.lock
This clears up a dependency on react types
> chore(deps): Bump react-bootstrap

- src/platforms/android/configuration/integrations/apollo3.mdx
> Set GraphQL Client errors as beta

- src/platform-includes/configuration/decluttering/javascript.mdx
- src/platforms/javascript/legacy-sdk/tips.mdx
Seen in https://sentry.sentry.io/issues/4254898193/events/2e263902fff94b749709f4727ad33f23/
> Add `chrome-extension://` to denyUrls recommendations

- src/platforms/javascript/common/session-replay/troubleshooting.mdx
Resolves: https://github.com/getsentry/sentry-docs/issues/6887
> replay: troubleshooting performance

- __mocks__/@reach/router.js
- __mocks__/gatsby.js
- src/components/hooks/__tests__/usePlatform.test.js
- src/components/hooks/usePlatform.tsx
- src/pages/platform-redirect.tsx
useNavigate seems to no longer be a thing in some newish version of gatsby
Fixes DOCS-5YW
> fix: useNavigate -> gatsby/navigate

- src/platform-includes/sourcemaps/troubleshooting/javascript.mdx
> Fix duplicate heading in source maps troubleshooting

- src/platforms/javascript/common/sourcemaps/index.mdx
- src/platforms/javascript/common/sourcemaps/troubleshooting_js/index.mdx
- src/platforms/javascript/common/sourcemaps/uploading/hosting-publicly.mdx
- src/platforms/javascript/common/sourcemaps/uploading/webpack.mdx
- src/platforms/react-native/sourcemaps.mdx
- vercel.json
> [DRAFT] test first redirect

- src/platforms/javascript/common/session-replay/configuration.mdx
- src/platforms/javascript/common/session-replay/privacy.mdx
Closes https://github.com/getsentry/sentry-docs/issues/7055
> feat(replays): Add documentation for `beforeAddRecordingEvent`

- src/docs/product/accounts/pricing.mdx
- [  ] Checked Vercel preview for correctness, including links
Add Arizona and Tennessee as taxable states.
> Arizona/Tennessee taxes pricing.mdx

- src/docs/product/alerts/create-alerts/metric-alert-config.mdx
Add references to the new fields available in metric transactions
> Mention the new transaction tags available.

- src/platforms/python/guides/quart/index.mdx
Just added the minimum SDK version.
> Fixed quart version

- src/platforms/android/common/performance/instrumentation/automatic-instrumentation.mdx
Fixes https://github.com/getsentry/sentry-docs/issues/7110 …
> feat(android): Add missing docs for trace propagation targets

- vercel.json
> breakpad 404s

- src/docs/product/alerts/index.mdx
Add the fact that muting Metric alerts is now in EA.
> Add info about muting Metric alerts.mdx

- src/platform-includes/enriching-events/attach-screenshots/android.mdx
- src/platform-includes/enriching-events/attach-viewhierarchy/android.mdx
> feat(android): Add docs for screenshots/vh BeforeCaptureCallback

- src/platforms/apple/common/configuration/watchdog-terminations.mdx
Fixed a link to a cocoa sdk file
> fix(apple): Link to watchdog termination code.

- src/docs/product/alerts/create-alerts/index.mdx
Explain what the issue alert rule limit is. Related sentry PR: https://github.com/getsentry/sentry/pull/51539
> ref(alerts): Add mention of limits

- src/docs/product/accounts/membership.mdx
Made changes to page to reflect newly added roles.
> updating team membership page

- .github/labels.yml
See [commits list](https://github.com/getsentry/sentry-docs/pull/7288/commits) for details.
I'd like to get this in before https://github.com/getsentry/sentry-docs/pull/7289.
> Make some label changes

- src/platforms/common/performance/index.mdx
The sentence reads a bit clunky, suggesting something that sounds a bit more straightforward.
> Fix wording on Set Up Performance page

- src/platforms/apple/troubleshooting.mdx
Troubleshooting for app not symbolicated
> feat(Apple): Troubleshooting for app not symbolicated

- src/platform-includes/getting-started-config/apple.mdx
Added `enableTracing` in the "Getting Started" section for cocoa so the user could see more transactions out of the box.
More details at #5730
> feat(apple): Point out enableTracing in Getting Started 

- src/platform-includes/getting-started-config/apple.mdx
Clarify we recommend starting the SDK on the main thread.
> fix(apple): Clarify starting SDK on main thread

- src/platform-includes/distributed-tracing/custom-instrumentation/php.mdx
- src/platform-includes/distributed-tracing/how-to-use/php.mdx
- src/platforms/common/usage/distributed-tracing/custom-instrumentation.mdx
Follow up of https://github.com/getsentry/sentry-php/pull/1516
> [PHP] Tracing without performance

- src/platforms/node/common/profiling/index.mdx
Fixes https://github.com/getsentry/sentry-docs/issues/7293
> fix(profiling): update profiler mode docs

- src/docs/product/accounts/quotas/index.mdx
- vercel.json
> Fix more docs 404s

- src/wizard/dotnet/uwp.md
- src/wizard/dotnet/winforms.md
- src/wizard/dotnet/wpf.md
- src/wizard/dotnet/xamarin.md
closes https://github.com/getsentry/sentry/issues/52422
> ref(getting-started-docs): Replace type 'languages' with 'framework'

- src/wizard/javascript/react/index.md
- src/wizard/javascript/react/with-error-monitoring-and-performance.md
- src/wizard/javascript/react/with-error-monitoring-and-replay.md
- src/wizard/javascript/react/with-error-monitoring-performance-and-replay.md
- src/wizard/javascript/react/with-error-monitoring.md
Reverts getsentry/sentry-docs#7333
> Revert "ref(getting-started-docs): Migrate react to sentry"

- src/wizard/react-native/index.md
removes superfluous backticks from RN wizard
> fix RN wizard backticks

- src/components/lambdaLayerDetail.tsx
- src/gatsby/sourceNodes/awsLambdLayerRegistryNodes.ts
This is a much more descriptive name for these graphql nodes
> ref(ts): Rename AWS Labmda layer nodes Layer -> AwsLambdaLayer

- src/platform-includes/getting-started-sourcemaps/react-native.mdx
- src/platforms/common/index.mdx
The wizard source maps command doesn't support react native at the moment.
> Add RN specific source maps getting started

- src/components/codeContext.tsx
The loading/loaded states where swapped, oops...
> fix: Fix signed in check

- src/components/breadcrumbs.tsx
- src/components/layout.tsx
- src/components/platformSidebar.tsx
- src/components/seo.tsx
- src/components/signInNote.tsx
StaticQuery will be removed in gatsby 6
> ref(gatsby): Switch to useStaticQuery

- src/components/banner.tsx
> remove backend webinar banner since it already happened

- vercel.json
> Fix data-management

- src/css/_includes/search.scss
> fix: Search popup position

- src/css/_includes/index.scss
> fix: Make index search smaller

- src/platform-includes/configuration/before-send-transaction/php.symfony.mdx
> Fix symfony code sample for before_send_transaction

- .github/labels.yml
Remove all status labels, they are unused
> (chore): Remove status labels

- src/platforms/javascript/common/sourcemaps/uploading/hosting-publicly.mdx
> Fix typo in source maps doc

- src/platforms/dotnet/common/configuration/msbuild.mdx
Added the new property available on the MSBuild target to the sample snippet.
> Added 'SentryUploadAndroidProguardMapping' to MSBuild properties

- src/platform-includes/configuration/config-intro/dotnet.mdx
- src/platform-includes/enriching-events/breadcrumbs/before-breadcrumb/dotnet.mdx
- src/platform-includes/getting-started-config/dotnet.aspnet.mdx
- src/platform-includes/getting-started-config/dotnet.mdx
- src/platform-includes/getting-started-confignote/dotnet.mdx
- src/platform-includes/set-fingerprint/basic/dotnet.mdx
- src/platform-includes/set-fingerprint/database-connection/dotnet.mdx
- src/platform-includes/set-fingerprint/rpc/dotnet.mdx
- src/platform-includes/set-fingerprint/rpc/dotnet.xamarin.mdx
- src/platform-includes/set-fingerprint/static/dotnet.mdx
- src/platforms/dotnet/guides/aspnet/index.mdx
- src/platforms/dotnet/guides/aspnet/performance/included-instrumentation.mdx
- src/platforms/dotnet/guides/aspnetcore/index.mdx
- src/platforms/dotnet/guides/aws-lambda/index.mdx
- src/platforms/dotnet/guides/google-cloud-functions/index.mdx
- src/platforms/dotnet/guides/maui/index.mdx
- src/platforms/dotnet/guides/uwp/index.mdx
- src/platforms/dotnet/guides/winforms/index.mdx
- src/platforms/dotnet/guides/wpf/index.mdx
- src/platforms/dotnet/guides/xamarin/index.mdx
- src/platforms/dotnet/migration.mdx
Updated snippets and obsolete API.
> .NET housekeeping

- src/platforms/android/configuration/gradle.mdx
> chore(android): Mention autoUploadNativeSymbols option

- src/docs/product/security/ip-ranges.mdx
Just updating the doc to align with our plan of IP addresses switchover:
https://status.sentry.io/incidents/tk9cv26z8xcl
> IP addresses: final switch postponed to September 1

- src/platforms/apple/common/install/carthage.mdx
Add more information regarding all different `frameworks` generated by carthage.
> feat(apple): Update carthage install process

- src/api/index.mdx
Add link to Postman collection and reword APIs index page
> Add postman link and edit intro text

- src/docs/product/accounts/early-adopter-features/index.mdx
Fix https://github.com/getsentry/sentry/issues/53662
> fix early adopter redirect

- src/platform-includes/set-release/javascript.nextjs.mdx
Resolves https://github.com/getsentry/sentry-docs/issues/5805
> Add custom set-release for nextjs sdk

- src/platform-includes/distributed-tracing/custom-instrumentation/python.mdx
- src/platform-includes/distributed-tracing/how-to-use/python.mdx
- src/platforms/common/usage/distributed-tracing/dealing-with-cors-issues.mdx
- src/platforms/common/usage/distributed-tracing/index.mdx
- src/platforms/common/usage/distributed-tracing/limiting-trace-propagation.mdx
> copyedit tracing docs

- src/docs/product/issues/issue-details/performance-issues/regex-main-thread/index.mdx
Added Android sample for Regex on main thread, just as iOS
> Add Android sample for Regex on main thread

- vercel.json
> CSP: allow iframes of `demo.arcade.software`

- src/platform-includes/sourcemaps/overview/javascript.remix.mdx
Fix typo that causes a warning in the docs build
> Fix code block language

- src/platform-includes/crons/setup/php.mdx
Document the newly added `Sentry::captureCheckIn()` function.
> Update PHP Cron snippets to use `Sentry::captureCheckIn()`

- src/platform-includes/enriching-events/add-attachment/go.mdx
- src/platforms/common/enriching-events/attachments/index.mdx
Starting from `sentry-go` version 0.23.0, we'll have the initial support for attachments 🎉
> feat(sentry-go): Document Attachments support

- src/docs/product/issues/issue-details/performance-issues/consecutive-http/index.mdx
- src/docs/product/issues/issue-details/performance-issues/n-one-queries.mdx
- src/docs/product/issues/issue-details/performance-issues/slow-db-queries/index.mdx
- For project: [link](https://www.notion.so/sentry/Detector-Threshold-Configuration-f8cb07e7cceb42388cedb09ea05fc116?pvs=4)
- Updated threshold values to match those in prod.
> docs(perf-detector-thresholds): Updated thresholds.

- src/docs/product/accounts/early-adopter-features/issue-archiving.mdx
> Add archive forever description

- src/platforms/unity/native-support/index.mdx
Add note for Nintendo about Switch builds
Link to review: https://sentry-docs-git-shana-add-unity-note.sentry.dev/platforms/unity/native-support/
> Add note for Nintendo Switch builds

- src/pages/index.tsx
Add a one liner to describe what Sentry is.
> Update home page to describe what Sentry is

- src/docs/product/data-management-settings/filtering/index.mdx
Moved plan requirement to custom filters only, since the rest are available on all plans.
> Plan Alert was misplaced

- src/docs/product/sentry-basics/integrate-frontend/index.mdx
Remove replay & perf monitoring from list
Remove replay & perf monitoring from list
> Update frontend tutorial learning objectives

- src/includes/sourcemaps-systemjs.mdx
- src/includes/sourcemaps-uglifyjs.mdx
- src/platform-includes/sourcemaps/upload/rollup/javascript.mdx
> fix heading levels

- gatsby-ssr.tsx
- package.json
- yarn.lock
You have been selected for a FREE upgrade to alpha test our new Replay SDK ft. rrweb2. Also update config to capture some network bodies.
> feat(sdk): Upgrade `@sentry/gatsby` to v7.64.0-alpha.0

- src/components/banner.tsx
Update banner for crons webinar.
> Add Banner for Upcoming Crons Webinar

- src/docs/product/releases/associate-commits/index.mdx
This adds a small note to the Resolve Issues by Commit section on the Associate Commits page to explain that resolving issues can also be done through PRs in the same way.
Page updated: /product/releases/associate-commits/#resolve-issues-by-commit
> Add resolve by PR on Associate Commits page

- .github/labels.yml
This label already exists. Just adding it to labels.yml so it will be persisted
> Add stale label

- src/platforms/common/profiling/index.mdx
fixes https://github.com/getsentry/sentry-docs/issues/7670
> fix: Clarify which layers are profiled in RN

- src/docs/product/crons/job-monitoring.mdx
> add cron arcade

- src/platforms/node/common/performance/instrumentation/automatic-instrumentation.mdx
Fix small spelling error in code example.
> Fix-spelling-error.mdx

- src/docs/product/issues/ownership-rules/index.mdx
- src/docs/product/sentry-basics/grouping-and-fingerprints/index.mdx
- src/platform-includes/capture-error/javascript.angular.mdx
- src/platform-includes/capture-error/javascript.cordova.mdx
- src/platform-includes/capture-error/javascript.ember.mdx
- src/platform-includes/capture-error/javascript.gatsby.mdx
- src/platform-includes/capture-error/javascript.mdx
- src/platform-includes/capture-error/javascript.nextjs.mdx
- src/platform-includes/capture-error/javascript.react.mdx
- src/platform-includes/capture-error/javascript.vue.mdx
- src/platform-includes/debug-symbols-apple/_default.mdx
- src/platform-includes/getting-started-config/apple.mdx
- src/platform-includes/getting-started-primer/javascript.nextjs.mdx
- src/platform-includes/source-context/apple.mdx
- src/platform-includes/sourcemaps/artifact-bundles/javascript.mdx
- src/platform-includes/sourcemaps/primer/javascript.mdx
- src/platform-includes/sourcemaps/primer/javascript.nextjs.mdx
- src/platforms/android/configuration/app-not-respond.mdx
- src/platforms/android/enhance-errors/proguard.mdx
- src/platforms/android/troubleshooting.mdx
- src/platforms/apple/common/migration.mdx
- src/platforms/common/configuration/options.mdx
- src/platforms/common/data-management/sensitive-data/index.mdx
- src/platforms/go/common/configuration/options.mdx
- src/platforms/java/migration/1.x-to-4.x.mdx
- src/platforms/javascript/guides/nextjs/manual-setup.mdx
- src/platforms/kotlin-multiplatform/debug-symbols.mdx
- src/platforms/react-native/troubleshooting.mdx
- src/platforms/unity/troubleshooting.mdx
Fix instances of "stacktrace" to "stack trace".
> stacktrace -> stack trace

- src/docs/clients/react-native/codepush.mdx
- src/docs/clients/react-native/config.mdx
- src/docs/clients/react-native/index.mdx
- src/docs/clients/react-native/manual-setup.mdx
- src/docs/product/accounts/sso/index.mdx
- src/docs/product/cli/configuration.mdx
- src/docs/product/cli/send-event.mdx
- src/docs/product/security-policy-reporting.mdx
- src/platform-includes/getting-started-config/dotnet.aspnet.mdx
- src/platforms/android/configuration/gradle.mdx
- src/platforms/android/troubleshooting.mdx
- src/platforms/common/data-management/debug-files/symbol-servers.mdx
- src/platforms/common/profiling/index.mdx
- src/platforms/dotnet/guides/nlog/index.mdx
- src/platforms/elixir/configuration/options.mdx
- src/platforms/flutter/upload-debug.mdx
- src/platforms/go/common/configuration/options.mdx
- src/platforms/javascript/common/install/loader.mdx
- src/platforms/javascript/legacy-sdk/config.mdx
- src/platforms/python/guides/beam/index.mdx
- src/platforms/python/guides/pyspark/index.mdx
- src/platforms/python/legacy-sdk/breadcrumbs.mdx
- src/platforms/python/legacy-sdk/integrations.mdx
- src/platforms/react-native/manual-setup/hermes.mdx
> Fix Sentry capitalization

- src/platform-includes/performance/configure-sample-rate/go.mdx
See https://github.com/getsentry/sentry-go/issues/706
> Update Gin traces sampler example

- src/components/banner.tsx
Remove Crons Monitoring Webinar banner
> remove crons monitoring banner

- src/docs/product/issues/states-triage/index.mdx
> Fix redirect link

- src/components/banner.tsx
Updated banner for new Livestram on ANR detection and prevention.
> update marketing banner

- src/components/codeBlock.tsx
- src/components/codeTabs.tsx
- src/css/_includes/code-blocks.scss
This component had a number of React anti patterns
> ref(ts): Improve implementation of CodeTabs

- src/platforms/react-native/manual-setup/manual-setup.mdx
- src/platforms/react-native/troubleshooting.mdx
skimmed through the page and found a few things that seem good to update
Note: I didn't update [notion to Volta](https://blog.volta.sh/2019/05/13/hello-volta/) on the docs for the legacy SDK
> fix(rn): improve/update a few sections on RN troubleshooting

- src/platforms/common/crons/index.mdx
Related: https://github.com/getsentry/relay/pull/2448
Also relates to https://github.com/getsentry/team-crons/issues/88
> feat(crons): Update upsert to use Relay APIs

- src/platform-includes/distributed-tracing/how-to-use/apple.mdx
More detail about distributed tracing that happens now without transaction.
> Feat(apple): Distributed tracing docs

- src/docs/product/accounts/quotas/index.mdx
- src/docs/product/accounts/quotas/spend-allocation.mdx
- src/docs/product/alerts/alert-types.mdx
- src/docs/product/alerts/best-practices.mdx
- src/docs/product/alerts/create-alerts/issue-alert-config.mdx
- src/docs/product/alerts/create-alerts/routing-alerts.mdx
- src/docs/product/alerts/index.mdx
- src/docs/product/integrations/integration-platform/webhooks/issues.mdx
- src/docs/product/integrations/notification-incidents/msteams/index.mdx
- src/docs/product/integrations/notification-incidents/slack/index.mdx
- src/docs/product/integrations/notification-incidents/threads/index.mdx
- src/docs/product/issues/reprocessing/index.mdx
- src/docs/product/sentry-basics/search/searchable-properties/issues.mdx
- src/docs/product/stats/index.mdx
Update docs to change "ignored" to "archived" to align with escalating issues release. 
Also copyedits to remove extra commas in quota docs. …
> update ignored to archived

- src/docs/product/accounts/early-adopter-features/discord/index.mdx
> add discord alert gif

- src/docs/product/session-replay/index.mdx
- src/platforms/javascript/common/session-replay/index.mdx
Fixes https://github.com/getsentry/team-replay/issues/109
> feat(replay): Update docs to be more explicit about Replays across multile pageloads

- src/components/banner.tsx
Update to be about perf monitoring workshop.
> update marketing banner perf monitoring

- src/platforms/javascript/common/configuration/micro-frontend-support.mdx
Added square brackets for correct syntax.
fixes #7793 
> Wrapped Key with square brackets

- src/docs/product/accounts/pricing.mdx
Remove pricing note now that the change is old news
> Remove pricing note

- src/platforms/javascript/guides/electron/configuration/integrations/browserwindowsession.mdx
- src/platforms/javascript/guides/electron/configuration/integrations/mainprocesssession.mdx
Add docs for the new `BrowserWindowSession` integration
> feat(electron): Add `BrowserWindowSession` integration

- src/platforms/python/common/configuration/integrations/wsgi.mdx
Making sure the getting started page for wsgi is correct.
> Python: getting started wsgi

- src/platforms/python/common/configuration/integrations/grpc.mdx
Making sure the getting started page of grpc is correct.
> Python: Getting Started grpc

- src/platforms/python/common/configuration/integrations/httpx.mdx
Making sure getting started for HTTPX is correct
> Python: Getting started httpx

- src/platforms/python/common/configuration/integrations/sqlalchemy.mdx
Making sure the getting started for sqlalchemy is correct.
> Python: Getting Started sqlalchemy

- src/platforms/python/common/configuration/integrations/loguru.mdx
Making sure getting started for loguru is correct.
> Python: Getting Started loguru

- src/platforms/python/common/configuration/integrations/asyncio.mdx
Making sure all getting started information of the `asyncio` integration in Python are correct.
> Python: Getting Started asyncio

- src/platforms/python/common/configuration/integrations/cloudresourcecontext.mdx
Making sure the information on the getting started page of cloud_resource_context integration is correct.
> Python: Getting Started cloud resource context

- src/platforms/python/common/configuration/integrations/asgi.mdx
Made sure all information in getting started page are correct.
> Python: Getting Started ASGI

- src/platforms/python/common/configuration/integrations/asyncpg.mdx
Make sure information on getting started page for asyncpg is correct
> Python: Getting Started asyncpg

- src/platforms/python/common/configuration/integrations/redis.mdx
Making sure the getting started of redis is correct.
> Python: Getting Started redis

- src/platforms/python/common/configuration/integrations/clickhouse-driver.mdx
Making sure getting started page for clickhouse is correct.
> Python: Getting Started Clickhouse

- src/platforms/python/common/configuration/integrations/pymongo.mdx
Making sure the getting started page for pymongo is correct.
> Python: Getting Started pymongo

- src/platforms/python/common/configuration/integrations/aiohttp.mdx
Making sure getting started page of aiohttp is correct.
> Python: Getting Started aiohttp

- src/platforms/javascript/common/configuration/micro-frontend-support.mdx
Fixes https://github.com/getsentry/sentry-docs/issues/7809
> Change microfrontend min required version

- src/docs/product/cli/releases.mdx
> Update release doc to clarify associating commits without integration

- src/platforms/common/profiling/index.mdx
- src/wizard/apple/profiling-onboarding/ios/1.install.md
> fix: update min cocoa sdk versions for profiling

- src/platform-includes/configuration/before-send-transaction/go.mdx
- src/platform-includes/configuration/ignore-errors/go.mdx
- src/platform-includes/configuration/ignore-transactions/go.mdx
- src/platform-includes/performance/traces-sampler-as-filter/go.mdx
- src/platforms/common/configuration/filtering.mdx
- src/platforms/go/common/configuration/options.mdx
Documents https://github.com/getsentry/sentry-go/pull/717 and improves some other things.
> Add new Go config options

- src/platform-includes/performance/add-spans-example/go.mdx
- src/platform-includes/performance/enable-manual-instrumentation/go.mdx
> Improve Go manual instrumentation examples

- src/platforms/index.mdx
> Add serverless framework to community SDK list

- src/platforms/python/guides/rq/index.mdx
- src/platforms/python/guides/tornado/index.mdx
Just mention that tornado is auto enabling.
> Python: Documented that Tornado is auto enabling

- src/platforms/common/enriching-events/context.mdx
Fixes https://github.com/getsentry/sentry-docs/issues/5904
> Clarify setContext signature

- src/platform-includes/session-replay/pre-requisites/javascript.capacitor.mdx
Resolves: https://github.com/getsentry/sentry-capacitor/issues/467
> fix: capacitor instead of electron

- vercel.json
> Add more redirects that need to go in vercel.json

- src/platforms/common/configuration/options.mdx
- related to feature request https://github.com/getsentry/sentry-react-native/issues/3258
> Remove tunnel option from RN

- src/platforms/python/common/configuration/integrations/boto3.mdx
Small update to Boto3 getting started
> Python: Getting Started Boto3

- src/platform-includes/crons/setup/javascript.nextjs.mdx
Based on feedback from https://sentry.sentry.io/feedback/docs:b9670e14579a490b8caae54d327037c4/?project=-1&referrer=feedback_list_page&statsPeriod=90d
> Expand on Next.js crons note

- src/platforms/node/common/configuration/application-not-responding.mdx
Quick fix to make sure options are shown for Node ANR
> Show options for Node ANR

- gatsby-ssr.tsx
Partially addresses https://github.com/getsentry/sentry-docs/issues/7951
> replay: sample 100% of sessions

- src/components/sidebarLink.tsx
* Allow collapsing the sub-tree of an active sidebar item so it is easier to navigate to its siblings
> feat(sidebar): Allow toggling sub links

- src/platforms/python/common/configuration/integrations/gql.mdx
> Added gql integration docs

- src/components/feedback/feedbackForm.tsx
This disables the submit button until there is text in the description field
> fix(replay): Make "description" a required field

- src/docs/product/sentry-basics/search/searchable-properties/session-replay.mdx
Closes https://github.com/getsentry/team-replay/issues/206
> docs(replays): add rage/dead selector as searchable property

- .github/ISSUE_TEMPLATE/issue.yml
> Suggest opening a PR in the issue template

- src/components/githubCta.tsx
- src/components/smartLink.tsx
This reverts commit c7fd4c66b42190ebaab785d048618e47869e02bd.
> Revert "feat(feedback): Change "Report a problem" link to open feedback modal (#7878)"

- src/platforms/go/common/usage/concurrency.mdx
- src/platforms/go/common/usage/panics.mdx
- src/platforms/go/common/usage/serverless.mdx
> Go SDK improvements

- src/docs/product/cli/configuration.mdx
Users shouldn't need to search in sentry-cli source code to figure out what they can set as a log-level.
> feat: list possible log-level values for CLI

- src/docs/product/profiling/index.mdx
This was renamed in product. Just renaming here for consistency.
> chore(profiling): Rename suspect functions to slowest functions

- src/platforms/python/common/integrations/gql/index.mdx
- src/platforms/python/common/integrations/index.mdx
Moved it to the new location, so it shows up in the sidebar.
> Python: Added GQL integration into new place

- src/platform-includes/getting-started-config/javascript.bun.mdx
- src/platform-includes/getting-started-primer/javascript.bun.mdx
- src/platform-includes/performance/enable-tracing/javascript.bun.mdx
> Bun SDK copyedits

- src/includes/feature-stage-beta.mdx
- src/platforms/common/profiling/index.mdx
- src/platforms/javascript/common/profiling/index.mdx
- src/platforms/node/common/configuration/application-not-responding.mdx
> ANR copyedits

- src/platform-includes/session-replay/install/javascript.capacitor.mdx
> replay: capacitor install

- package.json
Bump `sentry-global-search` package
> bump sentry-global-search

- src/platforms/python/common/integrations/sanic/index.mdx
Fixed typo where we confused the Bottle integration and the Sanic integration.
> Fix Python SanicIntegration type

- src/platform-includes/performance/opentelemetry-install/javascript.nextjs.mdx
- src/platform-includes/performance/opentelemetry-install/node.mdx
- src/platform-includes/performance/opentelemetry-setup/javascript.nextjs.mdx
Fixes https://github.com/getsentry/sentry-docs/issues/7957
> Add minimum version to otel node docs and fix snippets

- src/docs/product/issues/issue-details/error-issues/index.mdx
adds React Native to list of platforms supporting screenshots
> add React Native to platforms with screenshots

- .github/ISSUE_TEMPLATE/issue-build.yml
- .github/ISSUE_TEMPLATE/issue.yml
> Specify issue types better

- src/platforms/javascript/guides/electron/configuration/application-not-responding.mdx
Documents https://github.com/getsentry/sentry-electron/pull/753
cc @timfish
> feat: Add docs for Electron main thread ANR

- src/pages/index.tsx
> add unreal to landing pagage

- src/platform-includes/distributed-tracing/how-to-use/flutter.mdx
Add Flutter example code for tracePropagationTargets option.
Closes https://github.com/getsentry/sentry-dart/issues/1652
> Add Flutter example code for tracePropagationTargets option

- src/platform-includes/sourcemaps/troubleshooting/javascript.mdx
> Fix heading structure in sourcemaps troubleshooting

- src/platforms/common/crons/index.mdx
> ref(crons): Remove outdated connect errors section

- src/docs/product/issues/issue-details/performance-issues/frame-drop/index.mdx
Added Android example code in Frame Drop Issue
> Add Android example code in Frame Drop Issue

- vercel.json
> Update vercel.json - elixir

- src/docs/product/profiling/index.mdx
> Fix typo in profiling main page

- src/platforms/javascript/common/configuration/micro-frontend-support.mdx
> fix: micro-frontend code examples

- src/platforms/python/common/integrations/sanic/index.mdx
Added documentation of the `unsampled_statuses` option, which we have added in [sentry-python #2491](https://github.com/getsentry/sentry-python/pull/2419).
> Sanic performance options documentation

- package.json
- src/platforms/python/common/integrations/index.mdx
- yarn.lock
Updated to newest version of Platformicons. Everything looks better now in dark mode. Also fixed some links in Python docs to new icons.
> Updated icons (and fixed links to new icons in python docs

- vercel.json
> Update vercel.json -jav

- vercel.json
> Update vercel.json - /platforms page

- vercel.json
> Update vercel.json - platf

- vercel.json
> Update vercel.json - and

- vercel.json
> Update vercel.json - xam

- vercel.json
> Update vercel.json - int

- vercel.json
> Update vercel.json -scr

- src/platforms/python/integrations/django/index.mdx
> Correct default value for transaction_style for DjangoIntegration

- src/platform-includes/enriching-events/user-feedback/sdk-api-example/javascript.mdx
With a `;`, this was an invalid object.
> Fix `userFeedback` example

- src/platforms/native/configuration/backends/index.mdx
> feat: Expand docs on native backends

- src/docs/product/data-management-settings/filtering/index.mdx
This updates the patterns used by the health-check inbound filter.
See https://github.com/getsentry/sentry/pull/58223
Resolves https://github.com/getsentry/sentry-docs/issues/8260
> Update health-check inbound filter documentation to the new glob patterns

- src/docs/product/cli/releases.mdx
Demo combining multiple repositories for a release …
> multiple repositories

- vercel.json
> Update vercel.json - go

- vercel.json
> Update vercel.json - win

- vercel.json
> Update vercel.json - clo

- vercel.json
> Update vercel.json -conf

- src/platforms/php/common/profiling/troubleshooting.mdx
- src/platforms/php/guides/laravel/profiling/troubleshooting.mdx
- src/platforms/php/guides/symfony/profiling/troubleshooting.mdx
Replaces https://github.com/getsentry/sentry-docs/pull/7676
> Update PHP Profiling troubleshooting

- src/platforms/javascript/guides/electron/configuration/application-not-responding.mdx
documenting https://github.com/getsentry/sentry-electron/pull/770
> Add docs for renderer ANR tracking in Electron

- vercel.json
> Update vercel.json -eng

- src/docs/product/relay/options.mdx
See https://github.com/getsentry/relay/pull/2636.
> docs(relay): Update directory creation when enabling spooling

- src/platforms/javascript/common/session-replay/understanding-sessions.mdx
Give more specific example scenarios for custom sampling.
Closes https://github.com/getsentry/sentry-docs/issues/7839
Closes https://github.com/getsentry/sentry-javascript/issues/9178
> feat(replay): Add examples for custom sampling

- vercel.json
> Update vercel.json - 1026

- vercel.json
> Update vercel.json - 10261

- vercel.json
> Update vercel.json - 1025

- src/platforms/javascript/guides/remix/manual-setup.mdx
Remove unused imports for entry.server.ts code …
> Update manual-setup.mdx to remove unused imports in example code

- vercel.json
> Update vercel.json - 10262

- src/docs/product/sentry-basics/integrate-frontend/index.mdx
The link we currently have is throwing an error. Updating it.
> Update link to Node

- vercel.json
> Update vercel.json - fri3

- vercel.json
> More redirects

- vercel.json
Reverts getsentry/sentry-docs#8349
> Revert "More redirects"

- src/wizard/node/profiling-onboarding/javascript-sveltekit/3.configure-profiling.md
> fix(sveltekit): profiling onboarding typo

- src/platforms/common/performance/index.mdx
Fix Verify header on Set Up Performance page
> Fix Verify header on Set Up Performance page

- src/docs/product/sentry-basics/integrate-backend/index.mdx
Add link to backend tutorial app and move text out of note
> Add link to backend tutorial app

- src/platform-includes/profiling/automatic-instrumentation-intro/_default.mdx
- src/platform-includes/profiling/automatic-instrumentation-intro/javascript.angular.mdx
- src/platform-includes/profiling/automatic-instrumentation-intro/javascript.nextjs.mdx
- src/platform-includes/profiling/automatic-instrumentation-intro/javascript.react.mdx
- src/platform-includes/profiling/automatic-instrumentation-intro/javascript.svelte.mdx
- src/platform-includes/profiling/automatic-instrumentation-intro/javascript.sveltekit.mdx
- src/platform-includes/profiling/automatic-instrumentation-intro/javascript.vue.mdx
- src/platform-includes/profiling/automatic-instrumentation-setup/_default.mdx
- src/platform-includes/profiling/automatic-instrumentation-setup/javascript.angular.mdx
- src/platform-includes/profiling/automatic-instrumentation-setup/javascript.nextjs.mdx
- src/platform-includes/profiling/automatic-instrumentation-setup/javascript.react.mdx
- src/platform-includes/profiling/automatic-instrumentation-setup/javascript.svelte.mdx
- src/platform-includes/profiling/automatic-instrumentation-setup/javascript.sveltekit.mdx
- src/platform-includes/profiling/automatic-instrumentation-setup/javascript.vue.mdx
- src/platforms/javascript/common/profiling/index.mdx
Adds platform specific docs for browser profiling
> feat(profiling): add platform specific docs

- src/platforms/common/configuration/options.mdx
Adding explanation of `before_send` limitations
> Putting SDK team knowledge into docs

- package.json
- yarn.lock
This concludes updating the platform icons. Now all the icons have been reworked and look better and work on dark mode.
> Update to the newest platformicons

- src/platforms/python/integrations/sanic/index.mdx
Document https://github.com/getsentry/sentry-python/issues/1690#issuecomment-1787605696
> Sanic instructions initialize in before_server_start

- src/platforms/apple/common/performance/instrumentation/automatic-instrumentation.mdx
Change them from H3 to H2 to not appear under opt-out on the side bar.
|--------|--------|
| ![CleanShot 2023-11-07 at 11 35 45@2x](https://github.com/getsentry/sentry-docs/assets/2443292/c6059e4e-9dce-4ed0-9f39-6728df5ddffa) | ![CleanShot 2023-11-07 at 11 37 35@2x](https://github.com/getsentry/sentry-docs/assets/2443292/962b7493-f3da-4019-8279-25274d55cb95) |
> ref(apple): Fix TTFD/TTID headers

- src/wizard/flutter/profiling-onboarding/flutter/0.alert.md
- src/wizard/flutter/profiling-onboarding/flutter/1.install.md
- src/wizard/flutter/profiling-onboarding/flutter/2.configure-performance.md
- src/wizard/flutter/profiling-onboarding/flutter/3.configure-profiling.md
Adds wizard for Flutter profiling.
Part of https://github.com/getsentry/sentry/issues/59198
> feat: add Flutter profiling wizard

- src/platform-includes/performance/connect-errors-spans/apple.mdx
The sample code was referencing the wrong var
> Update transaction errors sample code

- src/platforms/node/common/configuration/application-not-responding.mdx
> Fix: fix function name in ANR detection

- src/platforms/javascript/common/profiling/index.mdx
> browser profiling aspnet example snippet

- src/platforms/native/configuration/backends/crashpad.mdx
Add note about multi-process support with crashpad using separate or shared database paths
> ref(native): Add note about multi-process support

- src/docs/product/issues/issue-details/performance-issues/consecutive-http/index.mdx
- Updated description for consecutive http issue to reflect new detector thresholds.
> feat(performance-issue-desc): Updated description for consecutive http issue

- src/platforms/python/integrations/grpc/index.mdx
Documenting changes that will be released with this PR: https://github.com/getsentry/sentry-python/pull/2369
Preview Link: 
https://sentry-docs-git-antonpirker-python-grpc-integrations.sentry.dev/platforms/python/integrations/grpc/
> Python SDK gRPC integration update

- src/platforms/android/configuration/gradle.mdx
> Change 'project' to 'projectName' in the gradle config

- src/platforms/common/configuration/options.mdx
https://github.com/getsentry/relay/blob/592091f7080f9a36a701f254c51dc833f587be57/relay-event-schema/src/processor/attrs.rs#L136
Documenting because of ask on discord.
> Add max length for dist

- src/components/codeContext.tsx
Because we won't have all the DSNs in a single region anymore, we need to fanout across each region that a user has membership in. The results from each region are joined together to make the final DSN/project context.
Refs HC-984
> feat(hybridcloud) Fetch DSNs from each region

- src/platforms/javascript/guides/nextjs/manual-setup.mdx
Adds documentation for instrumenting Next.js server actions.
> Add Next.js server action instrumentation functionality

- src/platforms/javascript/common/session-replay/index.mdx
Resolved: https://github.com/getsentry/sentry-capacitor/issues/319
> replay: capacitor no longer beta

- src/docs/product/integrations/source-code-mgmt/github/index.mdx
> Add redirect

- vercel.json
> Delete less-useful redirects to make room for more-useful redirects

- src/platforms/flutter/integrations/drift-instrumentation.mdx
- src/platforms/flutter/integrations/hive-instrumentation.mdx
Add drift & hive integration docs for Flutter/Dart
if approved don't merge yet pls
> feat(flutter): drift & hive integrations

- src/platforms/react-native/touchevents/index.mdx
- fixes: https://github.com/getsentry/sentry-react-native/issues/3410
> fix(rn): Add mission labelName option to touchevents

- src/platform-includes/configuration/ignore-exceptions/php.laravel.mdx
- src/platform-includes/configuration/ignore-exceptions/php.mdx
- src/platform-includes/configuration/ignore-transactions/php.laravel.mdx
- src/platform-includes/configuration/ignore-transactions/php.mdx
- src/platform-includes/configuration/logger/php.laravel.mdx
- src/platform-includes/configuration/logger/php.mdx
- src/platforms/common/configuration/filtering.mdx
- src/platforms/common/configuration/options.mdx
Catching up on some PHP SDK 4.0 additions.
> Add new PHP config options

- src/docs/product/integrations/compliance/index.mdx
- src/docs/product/integrations/compliance/truto/index.mdx
- src/docs/product/integrations/index.mdx
> Masinette truto integration

- src/platforms/apple/common/performance/instrumentation/swiftui-instrumentation.mdx
Updated documents about SwiftUI tracking feature to remove the beta disclaimer.
> chore(Apple): Remove "Beta" disclaimer for SwiftUI support

- src/platforms/javascript/guides/astro/manual-setup.mdx
Fixes the import - has the wrong name
> fix: Import for Astro Plugin

- src/platform-includes/getting-started-primer/javascript.cordova.mdx
- src/platform-includes/performance/configure-sample-rate/javascript.cordova.mdx
- src/platforms/common/performance/index.mdx
- src/platforms/common/performance/instrumentation/index.mdx
- src/platforms/javascript/common/performance/instrumentation/automatic-instrumentation.mdx
- src/platforms/javascript/common/profiling/index.mdx
mark Cordova not supported by browser profiling
fix Performance support (hide auto-instrumentation, custom init snippet,...)
> fix(cordova): fix docs around Cordova Perf and Profiling support

- src/platform-includes/sourcemaps/overview/javascript.remix.mdx
Resolves https://github.com/getsentry/sentry-docs/issues/8568
> Clarify remix source map deletion

- src/platforms/javascript/guides/remix/manual-setup.mdx
Resolves: https://github.com/getsentry/sentry-docs/issues/8400
> feat(remix): Mention the need for `withSentry` on Remix v2.

- src/platform-includes/crons/setup/java.mdx
> Java CRONS wrapper docs

- src/platforms/javascript/guides/nextjs/manual-setup.mdx
Adds docs on how to capture react render errors for Nex.tjs app router.
> Add instructions on how to capture react render errors in Next.js App Router

- src/platform-includes/crons/setup/javascript.nextjs.mdx
- src/platforms/javascript/guides/nextjs/manual-setup.mdx
Ref https://github.com/getsentry/sentry-javascript/issues/8701
> Update Vercel cron jobs docs

- src/platforms/android/configuration/gradle.mdx
- src/platforms/android/migration.mdx
* Migration docs for the sentry gradle plugin 4.0.0. Merge after it's shipped
> feat(android): Gradle plugin migration from 3.x.x to 4.0.0

- src/platform-includes/distributed-tracing/how-to-use/android.mdx
Mention the Android SDK version for distributed tracing working out of the box
> Android SDK version for automatic distributed tracing

- src/includes/sourcemaps-wizard-instructions.mdx
- src/platform-includes/sourcemaps/overview/javascript.mdx
fixes https://github.com/getsentry/sentry-docs/issues/8560
> ref(sourcemaps): adds RN note to browser JS source maps page

- src/platform-includes/configuration/before-send/kotlin-multiplatform.mdx
- src/platforms/common/configuration/filtering.mdx
Adds `beforeSend` for KMP
Closes #8611
> feat(kmp): add beforeSend

- src/platforms/python/integrations/logging/index.mdx
The note about how the configured log level affects the SDK (not) capturing log records as events was easy to miss -- making that a bit better.
Direct link: https://sentry-docs-git-ivana-better-logging-integration-note.sentry.dev/platforms/python/integrations/logging/
> fix(python): Better clarification regarding log levels

- src/platforms/common/configuration/options.mdx
Some clarifying on how `traces_sample_rate` behaves in Python.
Fixes https://github.com/getsentry/sentry-python/issues/2486
> Clarified the traces_sample_rate behavior in Python.

- src/docs/product/user-feedback/index.mdx
> fix(feedback) typo

- src/wizard/javascript/replay-onboarding/astro/2.configure.md
- src/wizard/javascript/replay-onboarding/capacitor/2.configure.md
- src/wizard/javascript/replay-onboarding/electron/2.configure.md
- src/wizard/javascript/replay-onboarding/sveltekit/2.configure.md
Fixing some incorrect links to the configuration docs
> ref(replay onboarding docs): fix some incorrect links

- src/platform-includes/set-fingerprint/basic/elixir.mdx
- src/platform-includes/set-fingerprint/database-connection/elixir.mdx
- src/platform-includes/set-fingerprint/rpc/elixir.mdx
- src/platform-includes/set-level/elixir.mdx
- src/platforms/common/usage/sdk-fingerprinting.mdx
- src/platforms/common/usage/set-level.mdx
A bunch of easy-peasy Elixir info was missing, so I added it.
> Add more Elixir usage docs

- src/docs/product/integrations/notification-incidents/opsgenie/index.mdx
It took me a while to figure out where I could create a sentry linked key. Hopefully this helps the next person who sets this integration up.
> fix(integrations) Improve opsgenie setup instructions

- src/platform-includes/enriching-events/set-user/native.mdx
fixes https://github.com/getsentry/sentry-native/issues/911
> fix(native): add note about setting user for native release health user stats

- src/platforms/common/crons/index.mdx
Add thresholds to `MonitorConfig`
> docs(crons): Add thresholds to MonitorConfig

- src/docs/product/accounts/early-adopter-features/index.mdx
- src/docs/product/issues/issue-details/performance-issues/endpoint-regressions/index.mdx
- src/docs/product/issues/issue-details/performance-issues/function-regressions.mdx
> docs(stats-detectors): Move regression issues to GA

- src/wizard/javascript/profiling-onboarding/angular/1.install.md
- src/wizard/javascript/profiling-onboarding/angular/2.configure-document-policy.md
- src/wizard/javascript/profiling-onboarding/angular/3.configure.md
- src/wizard/javascript/profiling-onboarding/vue/1.install.md
- src/wizard/javascript/profiling-onboarding/vue/2.configure-document-policy.md
- src/wizard/javascript/profiling-onboarding/vue/3.configure.md
Add angular and angular-ivy docs
> docs: add angular and vue

- src/includes/javascript-crons-upsert.mdx
- src/platform-includes/crons/setup/javascript.astro.mdx
- src/platform-includes/crons/setup/javascript.bun.mdx
- src/platform-includes/crons/setup/javascript.nextjs.mdx
- src/platform-includes/crons/setup/javascript.remix.mdx
- src/platform-includes/crons/setup/javascript.sveltekit.mdx
- src/platform-includes/crons/setup/node.mdx
Adds Crons upsert documentation to all javascript projects.
> Add javascript documentation for Crons upsert

- package.json
- src/platforms/javascript/guides/solid/config.yml
- yarn.lock
Get in https://github.com/getsentry/platformicons/pull/139
cc @atilafassina
> bump platformicons to 5.9.2

- src/platform-includes/crons/setup/javascript.deno.mdx
- src/platforms/javascript/common/crons/index.mdx
ref https://github.com/getsentry/sentry-javascript/issues/9700
> feat(deno): Add docs for `Deno.cron`

- src/platforms/dotnet/guides/azure-functions-worker/index.mdx
> Just added important using

- src/platforms/python/integrations/aws-lambda/manual-instrumentation/index.mdx
- src/platforms/python/integrations/aws-lambda/manual-layer/index.mdx
> fix(typo): you -> your

- src/platforms/react-native/troubleshooting/index.mdx
Add to troubleshooting how to fix sending sensitive transaction data.
> feat(RN): Troubleshoot sensitive transaction data

- src/platforms/node/common/configuration/application-not-responding.mdx
This PR updates the Node ANR docs to reflect the new API.
cc @lforst because I can't select you as a reviewer...
> node: Updated ANR docs

- src/platform-includes/capture-error/apple.mdx
Add a code sample of how to add custom information or how to change the info of an existing Swift error.
> feat(apple): Adding custom info to Swift Errors

- src/platform-includes/capture-error/apple.mdx
> fix(apple): Add link to CustomNSError

- src/platform-includes/performance/create-transaction-bound-to-scope/java.mdx
> Note on bindToScope in Java custom instr.

- src/platforms/ruby/common/configuration/options.mdx
for https://github.com/getsentry/sentry-ruby/issues/2200
> feat(ruby): Add trace_propagation_targets docs

- src/platform-includes/getting-started-primer/kotlin-multiplatform.mdx
- src/platforms/kotlin-multiplatform/swift-package-manager.mdx
The static prerequisite is in the wrong page
> fix(kmp): move static prerequisite to SPM

- src/includes/javascript-crons-automatic-crons-instrumentation.mdx
Documents https://github.com/getsentry/sentry-javascript/issues/9893
> feat(crons): Document Node Schedule support

- src/platforms/javascript/common/session-replay/index.mdx
Resolved by https://github.com/getsentry/sentry-javascript/issues/6946
> replay: remover perf warning

- .github/CODEOWNERS
- src/components/markdown.tsx
- src/components/video.tsx
- vercel.json
Remove the items that was not in used or approved
Added the security team as codeowners to prevent un-approved changes to CSP
Removed youtube 
(removing kamilogorek from codeowner since he is no longer with us)
> Update Content Security Policy

- vercel.json
Fixes https://github.com/getsentry/sentry/issues/60966
> Add redirect for product link

- src/platforms/flutter/integrations/routing-instrumentation.mdx
https://github.com/getsentry/sentry-dart/issues/1813
> flutter: add gorouter code snippet to routing instrumentation

- src/platforms/apple/common/integrations/default.mdx
> add note about testing crashes from Xcode

- src/platform-includes/performance/custom-sampling-context/java.mdx
- src/platform-includes/performance/force-sampling-decision/java.mdx
> fix(java): Update sampling decision docs to the latest version

- src/platforms/javascript/common/index.mdx
- src/platforms/node/common/index.mdx
- src/platforms/python/index.mdx
- src/platforms/react-native/index.mdx
- src/platforms/ruby/common/index.mdx
Add links to devrel setup videos on SDK pages
> Add links to setup videos

- src/docs/product/user-feedback/setup.mdx
Add PHP to supported SDKs for the Crash-Report API
> Add PHP to supported SDKs for the Crash-Report API

- src/platform-includes/user-feedback/example-widget/javascript.electron.mdx
- src/platform-includes/user-feedback/example-widget/javascript.mdx
Fixes https://github.com/getsentry/sentry-javascript/issues/10277
It would cause a typing issue.
> Fix guarding for event id in showReportDialog docs

- src/docs/product/accounts/quotas/spike-protection.mdx
> wip(spike protection): time decay explanation

- src/platforms/javascript/common/session-replay/understanding-sessions.mdx
> Correct typo in getIntegrationById fn

- src/platform-includes/getting-started-verify/apple.mdx
Mention to run app without debugger for verifying crashes.
> feat(apple): No debugger for crashes

- src/includes/performance/browser-custom-routing-instrumentation.mdx
- src/platform-includes/performance/browser-routing-instrumentation/custom-router.mdx
- src/platform-includes/performance/browser-routing-instrumentation/javascript.angular.mdx
- src/platform-includes/performance/browser-routing-instrumentation/javascript.electron.mdx
- src/platform-includes/performance/browser-routing-instrumentation/javascript.ember.mdx
- src/platform-includes/performance/browser-routing-instrumentation/javascript.mdx
- src/platform-includes/performance/browser-routing-instrumentation/javascript.nextjs.mdx
- src/platform-includes/performance/browser-routing-instrumentation/javascript.react.mdx
- src/platform-includes/performance/browser-routing-instrumentation/javascript.remix.mdx
- src/platform-includes/performance/browser-routing-instrumentation/javascript.sveltekit.mdx
- src/platform-includes/performance/browser-routing-instrumentation/javascript.vue.mdx
- src/platforms/javascript/common/performance/instrumentation/automatic-instrumentation.mdx
Add docs for adding custom routing instrumentation.
> feat(js): Add custom routing instrumentation docs

- src/docs/product/performance/index.mdx
> Small edits to perf monitoring page

- src/platforms/apple/common/performance/instrumentation/automatic-instrumentation.mdx
> fix: add experimental feature note to TTFD docs

- src/platforms/javascript/common/session-replay/understanding-sessions.mdx
ref https://github.com/getsentry/sentry-javascript/issues/7384#issuecomment-1910863680
> Use getIntegrationByName API for Replay docs

- src/platforms/javascript/common/user-feedback/configuration/index.mdx
Unfortunately, this code never worked -- we have instead, exported the `sendFeedback` function from the browser SDK packages.
> fix(feedback): Fix `sendFeedback` docs

- src/docs/product/accounts/choose-your-data-center/index.mdx
> update data residency

- src/docs/product/crons/getting-started/http/index.mdx
- src/platforms/javascript/common/crons/index.mdx
Follow up to https://github.com/getsentry/sentry-docs/pull/8965
> fix(crons): Followup suggestions to multi-environment docs

- src/docs/contributing/approach/product-docs/write-index.mdx
- src/docs/contributing/approach/sdk-docs/common_content.mdx
- src/docs/contributing/approach/sdk-docs/index.mdx
- src/docs/contributing/approach/sdk-docs/write-configuration.mdx
- src/docs/contributing/approach/sdk-docs/write-data-management.mdx
- src/docs/contributing/approach/sdk-docs/write-enriching-events.mdx
- src/docs/contributing/approach/sdk-docs/write-getting-started.mdx
- src/docs/contributing/approach/sdk-docs/write-performance.mdx
- src/docs/contributing/approach/sdk-docs/write-usage.mdx
- src/docs/contributing/environment.mdx
- src/docs/contributing/index.mdx
- src/docs/contributing/linking.mdx
- src/docs/contributing/pages/components.mdx
- src/docs/contributing/pages/index.mdx
- src/docs/contributing/pages/search.mdx
- src/docs/contributing/platforms/index.mdx
Update contributing docs for the next.js migration
> Update contributing docs

- src/components/banner.tsx
> update metrics marketing banner

- docs/platforms/php/common/metrics/index.mdx
Symfony does not yet support Metrics.
> Hide Metrics docs for Symfony

- platform-includes/metrics/set-snippet/javascript.mdx
> fix(js): use correct set func for set metric

- platform-includes/metrics/configure/javascript.nextjs.mdx
Copy of PR https://github.com/getsentry/sentry-docs/pull/9011 by @moonrailgun to debug issues with linting CI.
> Fix metrics configure typo in javascript next.js

- docs/product/issues/ownership-rules/index.mdx
> Remove ownership rules limitation

- docs/platforms/apple/common/install/carthage.mdx
Related Cocoa PR getsentry/sentry-cocoa#3565.
Superseeds https://github.com/getsentry/sentry-docs/pull/8917.
> feat(apple): Carthage visionOS support

- docs/platforms/android/troubleshooting/index.mdx
Closes https://github.com/getsentry/sentry-java/issues/2887
> chore(android): Excluding unwanted resources troubleshooting

- docs/platforms/javascript/common/troubleshooting/supported-browsers.mdx
> Fix link to example polyfills

- docs/platforms/javascript/common/troubleshooting/index.mdx
Additional configuration for javascript servers.
A simple POST endpoint parsing Sentry browser events and redirect them to Sentry.
> Add javascript example for tunnel endpoint

- .github/workflows/bump-api-schema-sha.yml
follows https://github.com/getsentry/sentry-docs/pull/9085
> build: Trim the sha list we get back from github

- .github/dependabot.yml
- .github/workflows/codeql-analysis.yml
- Trigger CodeQL scans on PRs to the `master` branch when there are changes to JavaScript/TypeScript files
- Change Dependabot's configuration to check for updates to GHA's daily
> configure security ci workflows

- docs/product/data-management-settings/filtering/index.mdx
this pr adds in information about the updated legacy browser filters and the old ones that we are deprecating.
> Add info about new legacy browser filters

- platform-includes/user-feedback/sdk-api-example/node.mdx
Fixes: https://github.com/getsentry/sentry-docs/issues/8781
> fix: node user feedback snippet

- docs/product/session-replay/index.mdx
> SEO updates for Session Replay page

- docs/platforms/react-native/performance/instrumentation/user-interaction-instrumentation.mdx
Fixes the text line breaks in note https://docs.sentry.io/platforms/react-native/performance/instrumentation/user-interaction-instrumentation
> fix: (react-native): Note line breaks in user interaction

- app/changelog/%5Fadmin/[id]/edit/page.tsx
- app/changelog/%5Fadmin/create/page.tsx
> fix: Order Categories in dropdown

- app/changelog/%5Fadmin/upload/route.tsx
Sentry issue: [DOCS-6YV](https://sentry.sentry.io/issues/4972560197/?referrer=github_integration)
> fix: Encoding of private key of env variables

- vercel.json
> fix: Add CSP for google storage upload

- docs/platforms/react-native/metrics/index.mdx
- platform-includes/metrics/version-support-note/react-native.mdx
- Docs for https://github.com/getsentry/sentry-react-native/pull/3590
No new content, only copied from JS docs.
> Add Sentry.metrics for React Native SDK

- docs/platforms/dotnet/common/legacy-sdk.mdx
> add legacy .net docs

- vercel.json
Follow up of https://github.com/getsentry/sentry-docs/pull/9151 but increasing sampling rate to 100%
> chore: report 100% of network errors

- .github/workflows/test.yml
see title
We build on Vercel anyway and we don't do anything with the build on GH
> Save the Planet! (Remove build from GH)

- docs/product/sentry-basics/integrate-frontend/initialize-sentry-sdk.mdx
- platform-includes/performance/automatic-instrumentation-custom-routing/javascript.mdx
Small things that got noticed that weren't fully correct...
> fix: Small fixes to JS browser tracing docs

- docs/platforms/javascript/common/session-replay/understanding-sessions.mdx
This has been added recently and makes this easier (and type safe!).
> feat: Use new `Sentry.getReplay()` util

- src/components/platformIdentifier.tsx
> PlatformIdentifier should fall back to guides' platform case style

- docs/product/accounts/pricing.mdx
Add the following states to us taxes list:
Illinois
Hawaii
Michigan
New Jersey
> Add states to taxes list

- platform-includes/session-replay/setup/javascript.angular.mdx
- platform-includes/session-replay/setup/javascript.astro.mdx
- platform-includes/session-replay/setup/javascript.electron.mdx
- platform-includes/session-replay/setup/javascript.ember.mdx
- platform-includes/session-replay/setup/javascript.gatsby.mdx
- platform-includes/session-replay/setup/javascript.mdx
- platform-includes/session-replay/setup/javascript.nextjs.mdx
- platform-includes/session-replay/setup/javascript.react.mdx
- platform-includes/session-replay/setup/javascript.remix.mdx
- platform-includes/session-replay/setup/javascript.svelte.mdx
- platform-includes/session-replay/setup/javascript.sveltekit.mdx
- platform-includes/session-replay/setup/javascript.vue.mdx
raised here https://github.com/getsentry/sentry-javascript/issues/10793
> fix(replay): Use correct lazy load snippet

- docs/platforms/android/enriching-events/screenshots/index.mdx
- docs/platforms/apple/common/enriching-events/screenshots/index.mdx
- docs/platforms/dotnet/guides/maui/enriching-events/screenshots/index.mdx
- docs/platforms/dotnet/guides/xamarin/enriching-events/screenshots/index.mdx
- docs/platforms/flutter/enriching-events/screenshots/index.mdx
- docs/platforms/javascript/guides/electron/enriching-events/screenshots/index.mdx
- docs/platforms/kotlin-multiplatform/enriching-events/screenshots/index.mdx
- docs/platforms/react-native/enriching-events/screenshots/index.mdx
- docs/platforms/unity/enriching-events/screenshots/index.mdx
Update language in SDK screenshot docs.
> update screenshots docs

- package.json
- yarn.lock
https://github.com/codecov/codecov-javascript-bundler-plugins/releases/tag/%40codecov%2Fbundler-plugin-core%400.0.1-beta.2
> build: Upgrade codecov plugin to 0.0.1-beta.2

- docs/platforms/apple/common/usage/in-app-frames/index.mdx
> Update Apple in-app frames page

- docs/platforms/apple/common/usage/in-app-frames/index.mdx
fixes https://github.com/getsentry/sentry-docs/issues/8656
> fix(Apple): link to in-app stack trace rules

- app/changelog/page.tsx
> typo: reduceMoths

- docs/product/integrations/issue-tracking/incidentio/index.mdx
Our company's name is lowercase :)
> Update Incident.io to incident.io

- src/actions/changelog.ts
- src/components/changelog/pagination.tsx
Fix mobile version horizontal scroll.
And revalidate list
> Revalidate + Mobile paging

- docs/platforms/javascript/guides/remix/manual-setup.mdx
> fix(remix): Re-add missing line in code snippet

- docs/platforms/javascript/guides/nextjs/manual-setup.mdx
Fixes https://github.com/getsentry/sentry-docs/issues/8884
> Add docs for disable logger option

- docs/platforms/javascript/common/session-replay/index.mdx
This page was missing a few backticks, which was causing formatting issues. …
> fix: close markdown code block

- next.config.js
Image Optimization API is not used.
> Remove `images` next.js option

- package.json
- sentry.client.config.ts
- yarn.lock
Update the spotlight and turn on the Clear …
> update spotlight to latest version and turned on clear events button in it.

- platform-includes/metrics/version-support-note/javascript.mdx
ref https://github.com/getsentry/sentry/pull/65928
> feat(metrics): Update min JS version

- docs/contributing/pages/images.mdx
add recommendations for image sizes and compression
> add image best practices

- docs/platforms/kotlin-multiplatform/native-access-sdk.mdx
- docs/platforms/kotlin-multiplatform/swift-package-manager.mdx
- platform-includes/getting-started-install/kotlin-multiplatform.mdx
- platform-includes/getting-started-primer/kotlin-multiplatform.mdx
Updates regarding release `0.5.0`
> feat: update KMP docs

- package.json
Add updated `license` key and other pieces of metadata to `package.json`
Closes #9008 
> Package.json metadata

- platform-includes/user-feedback/sdk-api-example/javascript.mdx
fixed syntax of userFeedback javascript example
> fix: syntax of userFeedback javascript example

- docs/platforms/node/common/profiling/index.mdx
Released as part of https://github.com/getsentry/sentry-javascript/releases/tag/7.104.0
> fix(node): Use functional integration for node profiling

- docs/platforms/python/enriching-events/scopes/index.mdx
Closes: https://github.com/getsentry/sentry-docs/issues/8888
> replace "with-scope" with "push-scope"

- src/mdx.ts
- src/mdxOptions.js
- src/styles/_includes/type.scss
make markdown heading links styles more specific 
Closes #9330 
> fix: heading colors

- platform-includes/user-feedback/setup/javascript.angular.mdx
- platform-includes/user-feedback/setup/javascript.astro.mdx
- platform-includes/user-feedback/setup/javascript.ember.mdx
- platform-includes/user-feedback/setup/javascript.gatsby.mdx
- platform-includes/user-feedback/setup/javascript.mdx
- platform-includes/user-feedback/setup/javascript.nextjs.mdx
- platform-includes/user-feedback/setup/javascript.react.mdx
- platform-includes/user-feedback/setup/javascript.remix.mdx
- platform-includes/user-feedback/setup/javascript.svelte.mdx
- platform-includes/user-feedback/setup/javascript.sveltekit.mdx
- platform-includes/user-feedback/setup/javascript.vue.mdx
use the default value which is `system`, since many tend to copy the snippet as-is
> feedback: default snippet system theme

- docs/product/crons/legacy-endpoint-migration.mdx
Some customers have reported issues with our CLI when sending check-ins. This can happen if they are authorizing the CLI via auth tokens. This PR clarifies this case and instructs the developer to update their configuration.
P.S.: we already mention this in our [getting started](https://docs.sentry.io/product/crons/getting-started/cli/) docs.
> add clarifying message for Crons legacy endpoint migration with CLI using token auth 

- docs/platforms/native/configuration/backends/index.mdx
- docs/platforms/native/configuration/transports.mdx
- docs/platforms/react-native/performance/instrumentation/user-interaction-instrumentation.mdx
fixes some small remaining layouting issues, all other reported problems in these GH issues are already resolved:
- https://github.com/getsentry/sentry-docs/issues/8931#issuecomment-1979155013
- https://github.com/getsentry/sentry-docs/issues/8948#issuecomment-1908716650
fixes https://github.com/getsentry/sentry-docs/issues/8931
fixes https://github.com/getsentry/sentry-docs/issues/8948
> fix(sdk): Fixes small layout issues on SDK next-docs

- platform-includes/getting-started-config/javascript.deno.mdx
Until this is resolved https://github.com/getsentry/sentry-javascript/issues/10770
> Remove NPM download

- docs/platforms/python/integrations/index.mdx
- docs/platforms/python/integrations/openai/index.mdx
- https://github.com/getsentry/sentry-python/pull/2791
- https://github.com/getsentry/develop/pull/1183
> Add OpenAI docs

- docs/platforms/python/profiling/index.mdx
- docs/platforms/python/profiling/troubleshooting/index.mdx
Combine snippets and move the upgrade to trouble shooting
> [python] Condense Profiling Setup Docs

- docs/platforms/ruby/common/profiling/index.mdx
Combine snippets, no stand alone for enabling performance
> [ruby] Condense Profiling Setup Docs

- docs/product/accounts/early-adopter-features/index.mdx
- docs/product/integrations/source-code-mgmt/github/index.mdx
* Added note for PHP EA support
* Mentioned on EA Features  page.
> chore(open-pr-comments): Add PHP to EA

- docs/product/performance/web-vitals/index.mdx
- docs/product/performance/web-vitals/web-vitals-concepts.mdx
- Add note about INP on web vitals page & concepts page
- Add INP description to concept page
- Move FID down
- Update thresholds chart
- Update browser compatibility chart (according to google documentation, so also removed IE since it wasn't listed on their site)
> Update docs for INP

- platform-includes/performance/opentelemetry-setup/node.mdx
> Fix link syntax

- docs/platforms/php/guides/laravel/configuration/laravel-options.mdx
- docs/platforms/php/guides/laravel/other-versions/laravel4.mdx
- docs/platforms/php/guides/laravel/other-versions/laravel5.mdx
- docs/platforms/php/guides/laravel/other-versions/laravel6-7.mdx
- docs/platforms/php/guides/laravel/other-versions/laravel8-10.mdx
- docs/platforms/php/guides/laravel/usage/index.mdx
Not to be merged before March 12th.
> Adapt Laravel docs for version 11.0

- docs/platforms/ruby/common/metrics/index.mdx
> feat(ruby): Add metrics docs

- src/components/docPage.tsx
- src/components/focus-active-link.tsx
> fix: scroll active sidebar link into view if not visible

- docs/platforms/php/common/enriching-events/tags/index.mdx
- docs/platforms/php/guides/symfony/enriching-events/index.mdx
I added a short note incl. link to the Symfony configuration options. For my point of view this makes it easier to find how to add a tag in a Symfony environment.
> add hint to Symfony configuration

- docs/platforms/javascript/common/performance/instrumentation/automatic-instrumentation.mdx
> feat(webvitals): Adds callout for enableInp about replays and profiles

- platform-includes/enriching-events/set-context/ruby.rails.mdx
> feat(ruby): Add clarification on setting context in rails

- platform-includes/getting-started-config/ruby.mdx
- platform-includes/getting-started-config/ruby.rack.mdx
- platform-includes/getting-started-config/ruby.rails.mdx
> fix(ruby): Simplify getting started configs for performance

- docs/platforms/python/integrations/django/index.mdx
- src/components/platformSdkDetail.tsx
> fix: respect integrations sdk front matter when available

- docs/platforms/javascript/common/session-replay/configuration.mdx
- platform-includes/session-replay/setup-canvas/javascript.angular.mdx
- platform-includes/session-replay/setup-canvas/javascript.astro.mdx
- platform-includes/session-replay/setup-canvas/javascript.ember.mdx
- platform-includes/session-replay/setup-canvas/javascript.gatsby.mdx
- platform-includes/session-replay/setup-canvas/javascript.mdx
- platform-includes/session-replay/setup-canvas/javascript.nextjs.mdx
- platform-includes/session-replay/setup-canvas/javascript.react.mdx
- platform-includes/session-replay/setup-canvas/javascript.remix.mdx
- platform-includes/session-replay/setup-canvas/javascript.svelte.mdx
- platform-includes/session-replay/setup-canvas/javascript.sveltekit.mdx
- platform-includes/session-replay/setup-canvas/javascript.vue.mdx
- platform-includes/session-replay/setup/javascript.angular.mdx
- platform-includes/session-replay/setup/javascript.astro.mdx
- platform-includes/session-replay/setup/javascript.capacitor.mdx
- platform-includes/session-replay/setup/javascript.electron.mdx
- platform-includes/session-replay/setup/javascript.ember.mdx
- platform-includes/session-replay/setup/javascript.gatsby.mdx
- platform-includes/session-replay/setup/javascript.mdx
- platform-includes/session-replay/setup/javascript.nextjs.mdx
- platform-includes/session-replay/setup/javascript.react.mdx
- platform-includes/session-replay/setup/javascript.remix.mdx
- platform-includes/session-replay/setup/javascript.svelte.mdx
- platform-includes/session-replay/setup/javascript.sveltekit.mdx
- platform-includes/session-replay/setup/javascript.vue.mdx
> Highlight replay snippets

- docs/contributing/pages/components.mdx
- docs/contributing/pages/variables.mdx
- src/components/alert.tsx
I updated/cleaned up some parts of the contributing docs that went out of date during Gatsby -> Next.js migration
> chore: Update contributing docs

- app/changelog/feed.xml/route.ts
- app/changelog/page.tsx
- app/changelog/utils.ts
- package.json
- yarn.lock
Exposes `/changelog/feed.xml` as an url for all Changelogs as an RSS feed.
> feat: Add RSS feed for changelog

- docs/platforms/android/common/metrics/index.mdx
- docs/platforms/dotnet/common/metrics/index.mdx
- docs/platforms/java/common/metrics/index.mdx
- docs/platforms/javascript/common/metrics/index.mdx
- docs/platforms/node/common/metrics/index.mdx
- docs/platforms/php/common/metrics/index.mdx
- docs/platforms/php/guides/laravel/metrics/index.mdx
- docs/platforms/python/common/metrics/index.mdx
- docs/platforms/react-native/metrics/index.mdx
- docs/platforms/ruby/common/metrics/index.mdx
- docs/platforms/unity/metrics/index.mdx
- docs/product/metrics/index.mdx
- docs/product/metrics/metrics-explorer-page.mdx
- docs/product/metrics/metrics-set-up.mdx
- includes/feature-stage-beta-metrics.mdx
- Create feature-stage-beta-metrics.mdx
- Update metrics index to include new disclaimer
> Docs updates for Metrics Beta

- app/layout.tsx
- docs/platforms/react-native/performance/instrumentation/time-to-display.mdx
- docs/product/performance/mobile-vitals/screen-loads.mdx
- includes/react-native-react-navigation-setup.mdx
Docs for
- https://github.com/getsentry/sentry-react-native/pull/3588
- https://github.com/getsentry/sentry-react-native/pull/3654
> feat(rn): Add Time To Display docs

- docs/platforms/python/integrations/celery/crons.mdx
Depending on how celery beat is run, Sentry has to be initialized in different ways. Updating the docs to mention this.
Direct link to preview: https://sentry-docs-git-ivana-fix-beat-setup.sentry.dev/platforms/python/integrations/celery/crons/
Closes https://github.com/getsentry/sentry-docs/issues/9457
> fix(crons): Fix instructions for using celery beat

- package.json
- yarn.lock
New version of platformicons with fixed OpenAI logos
> Bumped platformicons

- docs/platforms/python/migration/1.x-to-2.x.mdx
> feat(python): Update prerelease version

- src/components/docPage.tsx
> feat(docs platform): Remember platform/guide path when switching plaforms

- src/components/changelog/list.tsx
Fixes https://github.com/getsentry/sentry-docs/issues/9414
> fix: Category filter

- docs/product/accounts/early-adopter-features/index.mdx
- docs/product/integrations/source-code-mgmt/github/index.mdx
> chore(open-pr-comments): Move PHP to GA

- platform-includes/performance/automatic-instrumentation-custom-routing/javascript.mdx
> Add a missing comma!

- docs/product/crons/getting-started/http/index.mdx
This was missing from the HTTP docs
> feat(crons): Add missing thresholds to http docs

- docs/platforms/python/migration/1.x-to-2.x.mdx
> feat(python): Update release candidate version

- docs/platforms/python/configuration/options.mdx
- docs/platforms/python/crons/troubleshooting.mdx
- docs/platforms/python/troubleshooting.mdx
> feat(python): Add keep-alive option

- docs/platforms/react-native/profiling/index.mdx
Remove note that mixed profiling on RN is not available yet
> chore(react-native): Remove note about mixed profiling on RN

- docs/platforms/node/common/profiling/index.mdx
ref https://github.com/getsentry/sentry-javascript/tree/develop/packages/profiling-node
> Add note about profiling-node architectures

- docs/platforms/javascript/common/user-feedback/index.mdx
This adds some information about how User Feedback integrations with Replay.
Closes https://github.com/getsentry/sentry-docs/issues/9478
> feat(feedback): Add replay integration information inside of Feedback setup

- docs/contributing/pages/images.mdx
Change recommended way to add images when contributing to docs.
> Update image upload instructions

- docs/product/security-policy-reporting.mdx
Per recommendations of our SEO team.
> Optimize-security-policy-reporting-for-SEO

- docs/product/issues/index.mdx
Per recommendations from our SEO team
> Updating issue page to optimize for SEO

- docs/platforms/python/index.mdx
If someone tries the initial Getting Started example from a Python shell instead of from a file, [it won't work](https://github.com/getsentry/sentry-python/issues/2719). Adding a clarification.
Not sure if this is the best place/wording for this -- but it should be prominent enough so that folks who run into this when first trying to set up the SDK can see it right away.
Direct link to preview: https://sentry-docs-git-ivana-python-shell-not-working.sentry.dev/platforms/python/
> ref(python): Include a hint about Python shell

- docs/platforms/elixir/integrations/index.mdx
- docs/platforms/elixir/integrations/oban/index.mdx
- docs/platforms/elixir/integrations/plug_and_phoenix/index.mdx
- docs/platforms/elixir/integrations/quantum/index.mdx
> Add integrations docs for Elixir

- docs/contributing/pages/images.mdx
Update contributing images doc
> update contributing images

- docs/platforms/javascript/guides/react/features/component-tracking.mdx
This documentation so far isn't explaining why would I want to "track components". What does that mean, etc
So I aim to add a "before an after" to help clarify that
> mention value to track react component

- docs/platforms/native/user-feedback/index.mdx
- platform-includes/user-feedback/sdk-api-example/native.mdx
This PR adds a user feedback feature description for `sentry-native` which was introduced in https://github.com/getsentry/sentry-native/pull/966
> feat(native): add user feedback feature description

- docs/product/accounts/quotas/index.mdx
Update links to ensure they go to the right section of docs
> Update links in quota table

- docs/product/session-replay/performance-overhead.mdx
Add the word "replays" to performance overhead
> Clarify performance overhead for replays

- docs/product/alerts/create-alerts/issue-alert-config.mdx
- docs/product/alerts/create-alerts/metric-alert-config.mdx
- docs/product/alerts/create-alerts/routing-alerts.mdx
- docs/product/integrations/integration-platform/index.mdx
- docs/product/integrations/integration-platform/webhooks/issue-alerts.mdx
- docs/product/integrations/integration-platform/webhooks/metric-alerts.mdx
- Add arcade for creating integration and alert rule notifying that integration
- Add links to issue & metric alert creation & alert routing docs
> Update webhook alerts

- docs/product/user-feedback/index.mdx
> add information about user feedback notifications

- docs/platforms/python/migration/1.x-to-2.x.mdx
> ref(python): Update RC version

- docs/platforms/apple/common/troubleshooting/index.mdx
Document a workaround for a crash in the SubClassFinder (https://github.com/getsentry/sentry-cocoa/issues/3798) in Troubleshooting for Apple.
> feat(apple): SubClassFinder Crash Troubleshooting

- src/components/banner.tsx
> [STAT-650] Update Docs Banner for GDC After Party Event

- docs/platforms/apple/common/metrics/index.mdx
- docs/product/metrics/metrics-set-up.mdx
Add metrics docs for the Cocoa/Apple SDK. We have to wait until we release Cocoa 8.23.0 to merge this.
This PR is based on https://github.com/getsentry/sentry-docs/pull/9374.
> feat(apple): Add metrics docs

- docs/product/accounts/early-adopter-features/index.mdx
- docs/product/integrations/source-code-mgmt/github/index.mdx
> chore(open-pr-comments): Ruby to EA

- docs/platforms/javascript/common/best-practices/micro-frontends.mdx
* Just a tiny curly brace misalignment. 
> docs: mfe dsn example braces misalignment

- docs/product/accounts/pricing.mdx
> Clarify replay pricing.mdx

- next.config.js
Adds react component annotations for the Replay SDK.
> feat(sdk): Add react component annotations

- prisma/schema.prisma
- src/instrumentation.ts
Will emit otel spans for prisma.
> feat(sdk): Enable prisma tracing

- docs/product/metrics/index.mdx
- docs/product/metrics/metrics-explorer-page.mdx
- Copyedits to Metrics & Metrics Explorer product pages
- Update Metrics product page to mention observability & add timer as a metric type
- Update Metrics Explorer to replace images with arcades
Preview pages:
- https://sentry-docs-git-update-metrics.sentry.dev/product/metrics/
- https://sentry-docs-git-update-metrics.sentry.dev/product/metrics/metrics-explorer-page/
> update metrics docs

- docs/platforms/python/integrations/aws-lambda/manual-layer/index.mdx
> Removed the colon because it could lead to copy-pasting a string that breaks your Lambda function.

- docs/platforms/python/migration/1.x-to-2.x.mdx
> chore(python): Update RC version

- docs/platforms/python/metrics/index.mdx
* We added two more arguments to `before_emit_metric`: https://github.com/getsentry/sentry-python/issues/2956
* We removed two experimental metrics options: https://github.com/getsentry/sentry-python/issues/2955
Direct link to preview: https://sentry-docs-git-ivana-python-metrics-option-changes.sentry.dev/platforms/python/metrics/
> chore(python): Update metrics options

- src/components/banner.tsx
> [STAT-659] pull down banner

- docs/platforms/apple/common/metrics/index.mdx
Add docs for the timing API. We need to wait until Cocoa 8.24.0 is released to merge this PR.
> feat(apple): Add docs for timing API

- package.json
- yarn.lock
> chore(spotlight): Update spotlight to v2.0.0-alpha.1 to support @sentry/nextjs v8

- docs/product/performance/web-vitals/index.mdx
Updates some table headers and text to make score rating thresholds more clear.
> feat(webvitals): Clarify performance score rating thresholds tables

- docs/platforms/react-native/manual-setup/expo.mdx
- docs/platforms/react-native/migration/sentry-expo.mdx
> chore(rn): Remove note about Expo experimental support, the support is GA

- docs/product/security/ip-ranges.mdx
Add the outbound IP addresses in use by the EU region.
> feat(hybridcloud) Add EU region IPs

- platform-includes/session-replay/setup/javascript.angular.mdx
- platform-includes/session-replay/setup/javascript.astro.mdx
- platform-includes/session-replay/setup/javascript.capacitor.mdx
- platform-includes/session-replay/setup/javascript.electron.mdx
- platform-includes/session-replay/setup/javascript.ember.mdx
- platform-includes/session-replay/setup/javascript.gatsby.mdx
- platform-includes/session-replay/setup/javascript.nextjs.mdx
- platform-includes/session-replay/setup/javascript.react.mdx
- platform-includes/session-replay/setup/javascript.remix.mdx
- platform-includes/session-replay/setup/javascript.svelte.mdx
- platform-includes/session-replay/setup/javascript.sveltekit.mdx
- platform-includes/session-replay/setup/javascript.vue.mdx
Adding PII info section to the Session Replay Set up docs for the rest of the JS platforms.
> update PII on Session Replay

- docs/platforms/javascript/common/best-practices/offline-caching.mdx
- docs/platforms/javascript/common/configuration/transports.mdx
- src/middleware.ts
This page only contains info about setting up offline support, which IMHO can just be a best practice instead.
> feat(browser): Move transports config to best practices

- docs/platforms/dotnet/guides/aspnetcore/index.mdx
Added documentation for Blocking Detection in ASP.NET Core. For details, see:
- https://github.com/getsentry/sentry-dotnet/pull/2709
> Added documentation for Blocking Detection in ASP.NET Core

- docs/product/cli/configuration.mdx
> feat(crons): Add note to CLI auth that DSN is sometimes required

- docs/platforms/javascript/guides/angular/features/component-tracking.mdx
Update the code examples in "Track Angular Bootstrapping" section of the Angular component-tracking guide.
> Update "Track Angular Bootstrapping" example in Angular component-tracking

- docs/product/accounts/choose-your-data-center/index.mdx
- docs/product/accounts/migration/index.mdx
Add link to the workshop until it goes live on April 30th. Will update link to webinar recording once it's over.
> Add link to migrating to SaaS workshop

- docs/product/data-management-settings/filtering/index.mdx
This PR updates the docs with new health checks globs.
Related to: https://github.com/getsentry/sentry/pull/68880
> feat(dynamic-sampling): Update health checks

- docs/product/accounts/choose-your-data-center/index.mdx
> fix: Broken link in data storage docs

- docs/product/integrations/index.mdx
- docs/product/integrations/issue-tracking/index.mdx
- docs/product/integrations/issue-tracking/kitemaker/index.mdx
- docs/product/integrations/notification-incidents/index.mdx
- docs/product/integrations/notification-incidents/pagertree/index.mdx
Add Kitemaker and PagerTree to docs
> Update index.mdx to include kitemaker and pagertree integrations

- docs/platforms/php/guides/laravel/performance/instrumentation/automatic-instrumentation.mdx
Can be merged after getsentry/sentry-laravel#852 is released.
> Add documentation about new Laravel spans

- docs/product/performance/requests.mdx
> feat(perf): Remove EA banner from "Requests" docs

- docs/product/sentry-basics/index.mdx
Update to flow more smoothly with the new design.
> update get started product section name and description

- docs/platforms/elixir/migration.mdx
> feat(elixir): Link hexdocs migration guides

- docs/product/performance/requests.mdx
- Add widget note
- Add manual instrumentation notes
> feat(perf): Add more Requests module documentation

- docs/platforms/javascript/guides/gcp-functions/index.mdx
ref https://github.com/getsentry/sentry-javascript/issues/3269#issuecomment-2072251935
> fix: Add note about firebase to js gcp serverless docs

- vercel.json
> fix data scrubbing redirects

- docs/product/performance/metrics.mdx
Have a way to distinguish performance metrics from custom metrics.
> Renamed to Performance Metrics

- docs/platforms/javascript/common/migration/v7-to-v8/index.mdx
> fix(js): Move migration note under upgrade

- docs/platforms/apple/common/configuration/app-hangs.mdx
Recommend disabling app hangs for widgets and live activities as the might report false positives.
> fix(apple): Recommend disabling app hangs

- src/components/platformIcon.tsx
Make OpenAI Icon available in docs.
> Fix OpenAI icon

- docs/product/reference/search/searchable-properties/events.mdx
- docs/product/reference/search/searchable-properties/issues.mdx
> fix(issues): Fix missing space after .

- docs/platforms/apple/common/data-management/apple-privacy-manifest.mdx
just a wording NIT, I noticed there was a typo on the react native documentation.
> nit(apple): corectly -> correctly

- docs/platforms/flutter/data-management/apple-privacy-manifest.mdx
just a wording NIT, I noticed there was a typo on the react native documentation.
> nit(flutter): corectly -> correctly

- docs/platforms/react-native/data-management/apple-privacy-manifest.mdx
just a wording NIT, I noticed there was a typo on the react native documentation.
> nit(react-native): corectly -> correctly

- docs/product/data-management-settings/index.mdx
Moving data scrubbing and restricting data display to under "security, legal, and pii", so removing from this description.
> Update meta description

- platform-includes/enriching-events/set-user/dotnet.mdx
- platform-includes/enriching-events/unset-user/dotnet.mdx
See:
- https://github.com/getsentry/sentry-dotnet/issues/3331#issuecomment-2083108354
The class was also renamed from `User` to `SentryUser` in the version 4.0 release
> Updated examples for setting and clearing the scope.User in .NET

- platform-includes/sensitive-data/set-tag/dotnet.mdx
- platform-includes/sensitive-data/set-user/dotnet.mdx
I noticed while working on the Xamarin PR that some code samples were missing so I replaced them with proper C# code.
With this PR, all .NET projects will have the correct sample on the `Scrubbing Sensitive Data` field.
Before:
After:
> fix(.NET): Add code sample for scrubbing sensitive data on .NET

- docs/platforms/flutter/integrations/routing-instrumentation.mdx
- docs/platforms/kotlin-multiplatform/data-management/apple-privacy-manifest.mdx
- docs/platforms/kotlin-multiplatform/troubleshooting.mdx
- platform-includes/getting-started-primer/kotlin-multiplatform.mdx
Add apple privacy instructions for kmp as well
> kmp: add apple privacy manifest instructions

- docs/platforms/apple/common/metrics/index.mdx
Fix wrong metric names and values.
> fix(metrics): Apple examples

- docs/platforms/ruby/common/metrics/index.mdx
Remove unit from counter example
> fix(metrics): Ruby counter example

- src/components/platformIcon.tsx
> Made anthropic logo available in the compontents

- src/components/banner.tsx
Update promo banner to promote upcoming Supabase webinar.
> update promo banner

- docs/product/issues/issue-details/performance-issues/consecutive-db-queries/index.mdx
- docs/product/issues/issue-details/performance-issues/consecutive-http/index.mdx
- docs/product/issues/issue-details/performance-issues/db-main-thread-io.mdx
- docs/product/issues/issue-details/performance-issues/file-main-thread-io.mdx
- docs/product/issues/issue-details/performance-issues/frame-drop/index.mdx
- docs/product/issues/issue-details/performance-issues/index.mdx
- docs/product/issues/issue-details/performance-issues/large-http-payload/index.mdx
- docs/product/issues/issue-details/performance-issues/large-render-blocking-asset/index.mdx
- docs/product/issues/issue-details/performance-issues/n-one-api-calls.mdx
- docs/product/issues/issue-details/performance-issues/n-one-queries.mdx
- docs/product/issues/issue-details/performance-issues/regex-main-thread/index.mdx
- docs/product/issues/issue-details/performance-issues/slow-db-queries/index.mdx
- docs/product/issues/issue-details/performance-issues/uncompressed-asset/index.mdx
- docs/product/performance/index.mdx
- docs/product/performance/queries.mdx
- docs/product/performance/requests.mdx
- docs/product/performance/resources.mdx
- docs/product/performance/web-vitals/web-vitals-concepts.mdx
- docs/product/sentry-basics/concepts/tracing/event-detail.mdx
also make capitalization of perf issues consistent
> Update performance descriptions

- docs/organization/integrations/cloud-monitoring/aws-lambda/how-it-works.mdx
- docs/organization/integrations/cloud-monitoring/cloudflare-workers/index.mdx
- docs/organization/integrations/cloud-monitoring/gcp-cloud-run/index.mdx
- docs/organization/integrations/cloud-monitoring/index.mdx
- docs/organization/integrations/index.mdx
- docs/organization/integrations/troubleshooting.mdx
- docs/organization/membership/index.mdx
for org membership, org troubleshooting, and cloud monitoring
> update meta descriptions

- docs/platforms/python/integrations/anthropic/index.mdx
- docs/platforms/python/integrations/langchain/index.mdx
- docs/platforms/python/integrations/openai/index.mdx
Because those integrations (and the matching features on the backend) are not yet ready to go fully prime time!
Preview:
- https://sentry-docs-git-antonpirker-python-ai-beta-message.sentry.dev/platforms/python/integrations/anthropic/
- https://sentry-docs-git-antonpirker-python-ai-beta-message.sentry.dev/platforms/python/integrations/langchain/
- https://sentry-docs-git-antonpirker-python-ai-beta-message.sentry.dev/platforms/python/integrations/openai/
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional …
> Added a beta message to the Python AI integrations

- package.json
- src/components/platformIcon.tsx
- yarn.lock
> Added more AI related icons

- docs/platforms/javascript/common/enriching-events/scopes/index.mdx
I split this out of https://github.com/getsentry/sentry-docs/pull/9906 because I think we can merge this independently, and this is much more content heavy than the other PR.
> feat(js): Update scope docs for v8

- docs/product/metrics/index.mdx
Added units to the list of supported characters. Custom units must consist of ASCII alphanumeric characters, underscores, and digits.
> Update restrictions for units

- docs/platforms/react-native/manual-setup/manual-setup.mdx
- https://github.com/getsentry/sentry-react-native/issues/3798
> fix(rn): Add Xcode Debug Files upload using Sentry shell script

- src/build/resolveOpenAPI.ts
This reverts commit c9b0171e4ee8172ee0bd982a6baeab1ecae59663.
> Fix `/account` 404

- docs/platforms/python/integrations/huggingface_hub/index.mdx
- docs/platforms/python/integrations/index.mdx
plus: added beta message on top of page. 
> Added Hugggingface integration to list of integrations 

- docs/platforms/android/enriching-events/tags/index.mdx
- docs/platforms/apple/common/enriching-events/tags/index.mdx
- docs/platforms/dart/enriching-events/tags/index.mdx
- docs/platforms/dotnet/common/enriching-events/tags/index.mdx
- docs/platforms/flutter/enriching-events/tags/index.mdx
- docs/platforms/go/common/enriching-events/tags/index.mdx
- docs/platforms/java/common/enriching-events/tags/index.mdx
- docs/platforms/javascript/common/enriching-events/tags/index.mdx
- docs/platforms/kotlin-multiplatform/enriching-events/tags/index.mdx
- docs/platforms/powershell/enriching-events/tags/index.mdx
- docs/platforms/python/enriching-events/tags/index.mdx
- docs/platforms/react-native/enriching-events/tags/index.mdx
- docs/platforms/ruby/common/enriching-events/tags/index.mdx
- docs/platforms/rust/common/enriching-events/tags/index.mdx
- docs/platforms/unity/enriching-events/tags/index.mdx
- platform-includes/configuration/tags/defining-is-easy/native.mdx
> Tags are bound to the isolation scope

- platform-includes/performance/add-spans-example/unity.mdx
- platform-includes/performance/enable-manual-instrumentation/unity.mdx
Having those forwarding files actually broke the forwarding?
> fix(Unity): Custom Performance

- app/not-found.tsx
> feat: one click 404 report

- src/components/search/index.tsx
- src/components/search/search.module.scss
> feat: Cmd+k/esc keyboard interaction on Search

- docs/platforms/react-native/manual-setup/hermes.mdx
> spelling correction

- docs/product/metrics/metrics-examples.mdx
Added examples as a list of collapsable items to improve the looks
> Metrics examples with collapsable list

- docs/product/performance/retention-priorities/index.mdx
Re-shuffling content to make the behaviour more obvious.
> Update description for Investigation Mode

- docs/platforms/apple/common/troubleshooting/index.mdx
Added the solution to:
`error: invalid version number in '-target arm64-apple-ios9999'`
> chore(apple): Update Troubleshooting page to include `invalid version` solution.

- platform-includes/getting-started-config/javascript.deno.mdx
> Add import from NPM back

- app/platform-redirect/page.tsx
- docs/product/performance/requests.mdx
- src/middleware.ts
Closes #10007
Closes #9980
Closes #9794
> Fix some 404s

- docs/platforms/javascript/common/performance/instrumentation/automatic-instrumentation.mdx
Adds docs for `interactionsSampleRate` option in performance.
> feat(performance): Add interactionsSampleRate option docs

- src/components/externalLink.tsx
> fix externalLink icon layout

- platform-includes/migration/javascript-v8/important-changes/javascript.astro.mdx
#10034 was just merged. @vivianyentran's feedback missed one of the files I edited in that PR. This PR updates the missed file so all the files are consistent.
> Make all OpenTelemetry sentences consistent

- docs/concepts/migration/index.mdx
Adding an explicit listing of most things that are excluded during relocation.
> docs(relocation): List most excluded items

- docs/organization/integrations/index.mdx
- docs/organization/integrations/issue-tracking/goast/index.mdx
- docs/organization/integrations/issue-tracking/index.mdx
> Masinette goast integration docs

- docs/platforms/javascript/common/configuration/filtering.mdx
- docs/platforms/javascript/common/configuration/options.mdx
- platform-includes/configuration/before-send-span/javascript.mdx
Please don't merge before `v8.2.0`
> feat(core): Add `beforeSendSpan` documentation for javascript

- docs/platforms/apple/common/troubleshooting/index.mdx
Update the troubleshooting guide with more information on how to solve the invalid error Xcode compiler error.
> fix(apple): Troubleshooting invalid version

- docs/organization/integrations/compliance/index.mdx
- docs/organization/integrations/data-visualization/amazon-sqs/index.mdx
- docs/organization/integrations/data-visualization/grafana.mdx
- docs/organization/integrations/data-visualization/index.mdx
- docs/organization/integrations/data-visualization/segment/index.mdx
- docs/organization/integrations/data-visualization/splunk/index.mdx
- docs/organization/integrations/debugging/index.mdx
- docs/organization/integrations/debugging/rookout/index.mdx
- docs/organization/integrations/deployment/heroku/index.mdx
- docs/organization/integrations/deployment/index.mdx
- docs/organization/integrations/deployment/vercel/index.mdx
- docs/organization/integrations/feature-flag/index.mdx
- docs/organization/integrations/feature-flag/launchdarkly/index.mdx
- docs/organization/integrations/feature-flag/split/index.mdx
- docs/organization/integrations/issue-tracking/asana/index.mdx
- docs/organization/integrations/issue-tracking/clickup/index.mdx
- docs/organization/integrations/issue-tracking/index.mdx
- docs/organization/integrations/issue-tracking/jira/index.mdx
- docs/organization/integrations/issue-tracking/linear/index.mdx
- docs/organization/integrations/issue-tracking/shortcut/index.mdx
- docs/organization/integrations/issue-tracking/teamwork/index.mdx
- docs/organization/integrations/notification-incidents/discord/index.mdx
- docs/organization/integrations/notification-incidents/opsgenie/index.mdx
- docs/organization/integrations/session-replay/index.mdx
- docs/organization/integrations/source-code-mgmt/azure-devops/index.mdx
- docs/organization/integrations/source-code-mgmt/bitbucket/index.mdx
- docs/organization/integrations/source-code-mgmt/github/index.mdx
- docs/organization/integrations/source-code-mgmt/gitlab/index.mdx
- docs/organization/integrations/source-code-mgmt/index.mdx
- Update meta descriptions for Sentry integrations …
> update descriptions for org > integrations

- docs/platforms/javascript/common/user-feedback/configuration/index.mdx
Quick typo fixes.
Related to https://github.com/getsentry/sentry-javascript/issues/12015
> fix(feedback): Fix typos in the feedback config docs

- docs/platforms/javascript/guides/electron/configuration/integrations/additionalcontext.mdx
- docs/platforms/javascript/guides/electron/configuration/integrations/browserwindowsession.mdx
- docs/platforms/javascript/guides/electron/configuration/integrations/childprocess.mdx
- docs/platforms/javascript/guides/electron/configuration/integrations/electronbreadcrumbs.mdx
- docs/platforms/javascript/guides/electron/configuration/integrations/electronminidump.mdx
- docs/platforms/javascript/guides/electron/configuration/integrations/mainprocesssession.mdx
- docs/platforms/javascript/guides/electron/configuration/integrations/net.mdx
- docs/platforms/javascript/guides/electron/configuration/integrations/preloadinjection.mdx
- docs/platforms/javascript/guides/electron/index.mdx
- platform-includes/enriching-events/attach-screenshots/javascript.electron.mdx
- platform-includes/enriching-events/import/javascript.electron.mdx
- platform-includes/getting-started-config/javascript.electron.mdx
- platform-includes/performance/configure-sample-rate/javascript.electron.mdx
- platform-includes/performance/enable-automatic-instrumentation/javascript.electron.mdx
- platform-includes/profiling/automatic-instrumentation-setup/javascript.electron.mdx
- platform-includes/set-environment/javascript.electron.mdx
This is a draft until v5 stable is released!
> feat(electron): Update docs for v5

- docs/platforms/javascript/common/install/esm.mdx
This was still missing from our docs.
> feat(node): Add docs for `NODE_OPTIONS` esm config

- docs/platforms/javascript/guides/aws-lambda/container-image/index.mdx
Ref https://github.com/getsentry/sentry-javascript/issues/12012
Depends on https://github.com/getsentry/sentry-javascript/pull/12021
> Update aws serverless require flag

- docs/product/metrics/metrics-examples.mdx
> Fixed minor formatting issues

- docs/organization/early-adopter-features/index.mdx
> Remove priority sort from EA list

- docs/platforms/python/integrations/index.mdx
- docs/platforms/python/integrations/redis/index.mdx
- docs/platforms/python/performance/instrumentation/custom-instrumentation/cache-module.mdx
- Marked anthropic integrations auto enabled
- Cleaned up redis integration to align it with other integration docs …
> [Python] Smaller changes

- docs/platforms/javascript/common/performance/instrumentation/custom-instrumentation.mdx
- platform-includes/performance/start-inactive-span/javascript.mdx
- platform-includes/performance/start-span-manual/javascript.mdx
- platform-includes/performance/start-span/javascript.mdx
This rewrites the JS (node & browser) custom performance instrumentation docs to have much more detail than before.
> feat(js): Improve JS custom instrumentation docs

- docs/platforms/python/performance/instrumentation/custom-instrumentation/caches-module.mdx
This is a small, but important change.  …
> Fixed wrong ops names

- docs/platforms/javascript/common/configuration/integrations/custom.mdx
Updates the docs for custom integrations with the JS sdk to the v8 way of doing things.
> Update JS SDK custom integration docs to the v8 interface

- src/middleware.ts
Add redirects from ai to llm monitoring …
> add llm redirects

- docs/platforms/dotnet/common/crons/index.mdx
- docs/platforms/elixir/crons/index.mdx
- docs/platforms/go/common/crons/index.mdx
- docs/platforms/java/common/crons/index.mdx
- docs/platforms/javascript/common/crons/index.mdx
- docs/platforms/php/common/crons/index.mdx
- docs/platforms/python/crons/index.mdx
- docs/platforms/ruby/common/crons/index.mdx
- docs/product/crons/getting-started/http/index.mdx
- includes/crons-rate-limits.mdx
Adds a new section "Rate Limits" to all platform pages and HTTP to inform our current check-in rate limits to help us prevent abuse. …
> Add Crons rate limit information to all platform pages

- docs/api/auth.mdx
- docs/api/pagination.mdx
- docs/api/requests.mdx
Update URLs used in API usage examples to be compatible with all regions. The un-prefixed URLs only work in the US region or self-hosted/single-tenant environments.
> chore: Update API usage examples

- docs/platforms/python/performance/instrumentation/custom-instrumentation/requests-module.mdx
and it is eventually distracting.  …
> Removed init step, because it is documented elsewhere 

- platform-includes/set-release/dotnet.mdx
Updated how the SDK will look up and create a release.
> fix(.NET): Release creation

- docs/platforms/javascript/common/best-practices/browser-extensions.mdx
Fixes a typo in browser-extensions docs. …
> Fix typo in browser-extensions.mdx

- app/platform-redirect/page.tsx
> Platform redirect with hash

- src/remark-format-code.js
> fix: limit code block line formatting to 80 chars

- docs/platforms/php/common/metrics/index.mdx
Make it easier to copy/paste examples out of the docs like muppet.
> fix(php): Make the PHP metrics examples easier to copy/paste

- platform-includes/getting-started-add-top-level-import/javascript.express.mdx
- platform-includes/getting-started-use/javascript.express.mdx
- platform-includes/migration/javascript-v8/important-changes/javascript.express.mdx
Fixes https://github.com/getsentry/sentry-javascript/issues/12113
> fix(express): Ensure we document error handler positioning

- docs/platforms/elixir/integrations/plug_and_phoenix/index.mdx
See https://github.com/getsentry/sentry-elixir/issues/730. …
> Fix a deprecated function in Elixir docs

- platform-includes/getting-started-config/javascript.node.mdx
We were missing including the `nodeProfilingIntegration` import
> Add nodeProfilingIntegration import

- docs/platforms/dotnet/common/usage/async-void/index.mdx
See:
- https://github.com/getsentry/sentry-dotnet/pull/3379#issuecomment-2133709071
This documents a helper method that was added to the .NET SDK. 
cc: @bitsandfoxes and/or @bruno-garcia 
> Added docs for the RunAsyncVoid helper

- docs/product/metrics/metrics-examples.mdx
Update short description for Metrics Examples to something less dry 😄 
"Get some inspiration, by browsing through example use cases for custom metrics."
> Update short description for Metrics Examples

- platform-includes/migration/javascript-v8/important-changes/javascript.remix.mdx
Fix a typo on the migration guide page for the Remix SDK
https://docs.sentry.io/platforms/javascript/guides/remix/migration/v7-to-v8/ …
> fix(typo): migration guide for remix sdk

- docs/platforms/apple/common/configuration/options.mdx
Remove new in version mentions for basic options for v 7.x that was released over 1.5 years ago
> fix(apple): Remove new in version mentions

- docs/platforms/ruby/common/index.mdx
- platform-includes/getting-started-config/ruby.mdx
- platform-includes/getting-started-config/ruby.rack.mdx
- platform-includes/getting-started-config/ruby.rails.mdx
- platform-includes/getting-started-install/ruby.delayed_job.mdx
- platform-includes/getting-started-install/ruby.mdx
- platform-includes/getting-started-install/ruby.rails.mdx
- platform-includes/getting-started-install/ruby.resque.mdx
- platform-includes/getting-started-install/ruby.sidekiq.mdx
closes https://github.com/getsentry/sentry-docs/issues/10221
> feat(ruby): Add new onboarding component

- src/components/banner/index.tsx
Removing banner from Supabase workshop event since it's passed. …
> rm banner for supabase workshop

- docs/product/issues/issue-priority/index.mdx
We're not using "severity" anywhere else externally so this just rewords the 2 mentions of it in priority docs. …
> fix(issues): severity -> actionability

- docs/concepts/key-terms/tracing/trace-view.mdx
Update this docs page to reflect the new name.
- [x ] Urgent deadline June 5th launch …
> Update trace view to trace details to reflect UI changes

- platform-includes/getting-started-config/javascript.node.mdx
Docs example are missing an import when using ESM. …
> fix(node): Add missing ESM import

- platform-includes/getting-started-config/javascript.node.mdx
Fixes https://github.com/getsentry/sentry-docs/pull/10214, I forgot to check the hiding properly...
> fix(node): Fix onboarding import hiding options

- docs/product/performance/caches/index.mdx
- src/middleware.ts
> Cache instrumentation links

- docs/product/index.mdx
Add metrics section and update starfish modules description …
> Update what is sentry

- platform-includes/session-replay/install/javascript.angular.mdx
- platform-includes/user-feedback/install/javascript.angular.mdx
IMHO this is a bit redundant, I think it's enough to have this on the getting started page...?
> feat(angular): Remove compatibility note in replay/feedback install

- docs/platforms/javascript/common/performance/instrumentation/custom-instrumentation/queues-module.mdx
Fixes https://github.com/getsentry/sentry-javascript/issues/12334
> fix(node): Fix continue trace usage in queue docs

- docs/platforms/kotlin-multiplatform/initialization-strategies.mdx
- docs/platforms/kotlin-multiplatform/native-access-sdk.mdx
- platform-includes/getting-started-install/kotlin-multiplatform.mdx
- platform-includes/getting-started-primer/kotlin-multiplatform.mdx
Adds new init strategy & update versions after new release `0.7.1`
> feat(kmp): add new init strategy & update versions

- docs/platforms/java/common/performance/instrumentation/custom-instrumentation/queues-module.mdx
Some suggestions to improve Java code samples in queue docs (https://github.com/getsentry/sentry-docs/pull/10242) …
> Follow up to improve Java Queue docs code samples

- docs/platforms/php/index.mdx
Add a heading and an additional line of explanation to PHP configuration page.
Proposing changes to the new onboarding experience. 
- [ X ] Urgent deadline (GA date, etc.):  …
> Update PHP configuration

- docs/product/insights/index.mdx
> Add insights page

- docs/platforms/python/configuration/options.mdx
- docs/platforms/python/integrations/aws-lambda/manual-layer/index.mdx
- Edited the section describing what environment variables can be used with AWS Lambda layer for Python:
https://sentry-docs-git-antonpirker-python-aws-lambda-configuration.sentry.dev/platforms/python/integrations/aws-lambda/manual-layer/#configuration-options
- Updated the "common options" to make it easier to see which ones can be set via environment variables:
https://sentry-docs-git-antonpirker-python-aws-lambda-configuration.sentry.dev/platforms/python/configuration/options/#common-options
- Please give the docs …
> Make clear what environment variables can be used with AWS Lambda layer

- docs/platforms/javascript/common/configuration/integrations/browserprofiling.mdx
> fix: BrowserProfiling document has wrong title as BrowserTracing

- docs/pricing/quotas/index.mdx
- docs/pricing/quotas/manage-attachments-quota.mdx
- docs/pricing/quotas/manage-cron-monitors.mdx
- docs/pricing/quotas/manage-event-stream-guide.mdx
- docs/pricing/quotas/manage-replay-quota.mdx
- docs/pricing/quotas/manage-transaction-quota.mdx
- docs/pricing/quotas/spike-protection.mdx
Change performance units to span units and on-demand to pay-as-you-go. …
> Update billing quota pages for AM3

- docs/product/insights/assets.mdx
- docs/product/insights/caches/cache-page.mdx
- docs/product/insights/caches/index.mdx
- docs/product/insights/llm-monitoring/index.mdx
- docs/product/insights/mobile-vitals/app-starts.mdx
- docs/product/insights/mobile-vitals/index.mdx
- docs/product/insights/mobile-vitals/screen-loads.mdx
- docs/product/insights/queries.mdx
- docs/product/insights/queue-monitoring/index.mdx
- docs/product/insights/queue-monitoring/queues-page.mdx
- docs/product/insights/requests.mdx
- docs/product/insights/web-vitals/index.mdx
consolidate arcades for starfish modules to one each …
> update arcades for insights

- docs/platforms/android/metrics/index.mdx
- docs/platforms/apple/common/metrics/index.mdx
- docs/platforms/dart/metrics/index.mdx
- docs/platforms/dotnet/common/metrics/index.mdx
- docs/platforms/flutter/metrics/index.mdx
- docs/platforms/java/common/metrics/index.mdx
- docs/platforms/javascript/common/metrics/index.mdx
- docs/platforms/php/common/metrics/index.mdx
- docs/platforms/php/guides/laravel/metrics/index.mdx
- docs/platforms/php/guides/symfony/metrics/index.mdx
- docs/platforms/python/metrics/index.mdx
- docs/platforms/react-native/metrics/index.mdx
- docs/platforms/ruby/common/metrics/index.mdx
- docs/platforms/unity/metrics/index.mdx
- docs/product/metrics/metrics-explorer-page.mdx
- docs/product/metrics/metrics-set-up.mdx
- [ x ] Need to get this updated ASAP …
> Add alert about upcoming Metrics change to all Metrics pages that have a "beta" note.

- src/components/changelog/ui/Button/index.tsx
> Fix: Outline button variant style fixes in changelog.

- includes/metrics-api-change.mdx
Fixed typo in metrics disclaimer
> Fixed typo in metrics disclaimer

- next.config.js
- package.json
- sentry.client.config.ts
- yarn.lock
Adds a new SDK feature to tag/filter third party errors. This is to validate the feature.
> feat(sentry): Apply tag to errors that contain third-party frames

- docs/platforms/javascript/common/configuration/integrations/browserprofiling.mdx
> fix link to browser tracing 404

- docs/product/explore/traces/index.mdx
- vercel.json
move trace explorer up in nav order …
> update trace explorer nav order

- docs/platforms/index.mdx
Adding hono to our community-supported SDKs. 
closes https://github.com/getsentry/sentry-javascript/issues/12424
> docs(hono): Add hono to community supported SDKs

- docs/platforms/javascript/common/performance/instrumentation/opentelemetry.mdx
Make it more clear that Sentry JS SDK gives OTEL support out of the box, and that custom OTEL config is a power user thing. …
> Make it more clear that Sentry SDK gives OTEL support out of the box

- docs/platforms/javascript/common/configuration/integrations/extraerrordata.mdx
https://github.com/getsentry/sentry-javascript/blob/c8e9f84d9dbe8b81b04a3eb849a43112eee48af6/packages/core/src/integrations/extraerrordata.ts#L27
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me …
> indicate default for captureErrorCause

- docs/product/insights/llm-monitoring/index.mdx
> chore(llm-monitoring): Move LLM monitoring to beta

- docs/platforms/apple/common/features/experimental-features.mdx
- docs/platforms/apple/common/features/index.mdx
- moves features that are not experimental anymore from `Experimental features` page to `Features`
- updates `Experimental features` content
- refactors links on `Features` page to use `<PlatformLink>` and `<Link>`
> chore(Apple): Updates Features/Experimental Features pages

- docs/platforms/javascript/common/best-practices/web-workers.mdx
> note webworker replay support

- includes/feature-stage-beta-metrics.mdx
> Update Discord Link

- src/middleware.ts
- vercel.json
> fix pricing redirects

- docs/organization/integrations/cloud-monitoring/cloudflare-workers/index.mdx
Fixes https://github.com/getsentry/sentry-docs/issues/10341
> chore(cloudflare): Update support contact

- docs/product/insights/web-vitals/index.mdx
- docs/product/insights/web-vitals/web-vitals-concepts.mdx
Adds a Prerequisites and Limitations section to webvitals for more clarity around browser support
> feat(performance): Adds a Prerequisites and Limitations section to webvitals

- docs/platforms/flutter/features/index.mdx
Refer to the integrations page for flutter features
> feat(flutter): on features page add link to integrations list 

- docs/product/explore/traces/index.mdx
> remove  mouse  code

- docs/platforms/javascript/common/tracing/instrumentation/opentelemetry.mdx
Use the `addOpenTelemetryInstrumentation` helper from the SDK for adding custom OTEL instrumentation. …
> Use addOpenTelemetryInstrumentation method

- docs/concepts/key-terms/key-terms.mdx
- docs/platforms/android/tracing/index.mdx
- docs/platforms/android/tracing/instrumentation/custom-instrumentation.mdx
- docs/platforms/dart/tracing/index.mdx
- docs/pricing/quotas/index.mdx
- docs/pricing/quotas/manage-transaction-quota.mdx
- docs/pricing/quotas/spend-allocation.mdx
- docs/product/dashboards/index.mdx
- update references to transactions in pricing docs
- update span quota docs
- incorporate edits from recent feedback …
> edits on span/tracing docs

- docs/platforms/javascript/common/best-practices/micro-frontends.mdx
We stabilized the option in https://github.com/getsentry/sentry-javascript-bundler-plugins/releases/tag/2.18.0
> Stabilize module metadata in MFE docs

- docs/cli/dif.mdx
Fixes a typo in the CLI docs: "been upload" -> "been uploaded"
@andreiborza  …
> fix(cli): typo in Uploading Files

- docs/platforms/javascript/common/best-practices/micro-frontends.mdx
> Add note about getEvent in micro-frontends docs

- docs/platforms/dotnet/common/configuration/options.mdx
Suggested in:
- https://github.com/getsentry/sentry-dotnet/issues/3417#issuecomment-2165440005
cc: @bitsandfoxes 
> Added information about IsGlobalMode to BasicOptions

- src/middleware.ts
> add redirects

- docs/platforms/javascript/common/configuration/filtering.mdx
Adds docs for recently added `thirdPartyErrorFilterIntegration`: https://github.com/getsentry/sentry-javascript/pull/12267
Should wait until upcoming js release containing https://github.com/getsentry/sentry-javascript/pull/12512
> Add docs for `thirdPartyErrorFilterIntegration`

- docs/product/insights/llm-monitoring/getting-started/index.mdx
> Small fix in code snippet

- docs/platforms/javascript/common/install/commonjs.mdx
- docs/platforms/javascript/common/install/esm-without-import.mdx
- docs/platforms/javascript/common/install/esm.mdx
- docs/platforms/javascript/common/install/index.mdx
- docs/platforms/javascript/common/install/late-initializtion.mdx
- platform-includes/getting-started-use/javascript.nestjs.mdx
Fixing a few issues with the nextjs sdk getting started page.
> Fix nestjs getting started

- docs/platforms/android/profiling/index.mdx
Adds note about minimum Android API level required for Android Profiling.
Related:
https://github.com/getsentry/sentry-java/issues/3392
https://github.com/getsentry/sentry-java/pull/3478
> chore(Android): Add note about min api level for android profiler

- docs/organization/integrations/notification-incidents/opsgenie/index.mdx
> add plan information

- docs/platforms/react-native/migration/sentry-expo.mdx
> fix snippet

- docs/platforms/javascript/common/configuration/integrations/localvariables.mdx
As raised in https://github.com/getsentry/sentry-javascript/issues/12588, we don't make it clear how node local variables works with in app frames. This PR updates the integration docs to add a note about this.
> Add note to local variables about in app frames

- docs/platforms/javascript/guides/remix/manual-setup.mdx
Updates Remix docs to make it Remix v2 oriented.
> feat(remix): Make Remix docs v2 oriented.

- docs/platforms/javascript/guides/nextjs/manual-setup.mdx
- platform-includes/getting-started-verify/javascript.nextjs.mdx
We currently cannot capture one class of errors from within the SDK so we need to inform users about it.
Ref: https://github.com/getsentry/sentry-javascript/issues/12525
> Explain that we cannot capture nested RSC errors as of now

- docs/platforms/android/integrations/okhttp/index.mdx
add okhttp client error java examples
Fixes https://github.com/getsentry/sentry-docs/issues/8535
> add okhttp client error java examples
