docs/product/integrations/source-code-mgmt/github/index.mdx
docs/product/issues/suspect-commits/index.mdx

Automatic Code Mapping support for Go has just been GA'd today! This PR updates the docs to reflect that

fix(code-mappings): Add Go to list of languages that have support for Automatic Code mappings

---

platform-includes/user-feedback/example-widget/_default.mdx
platform-includes/user-feedback/example-widget/dotnet.mdx

Missing whitespaces:
- https://docs.sentry.io/platforms/python/user-feedback/#integration
- https://docs.sentry.io/platforms/dotnet/user-feedback/#integration

fix(user-feedback): missing whitespace

---

docs/platforms/javascript/common/user-feedback/configuration/index.mdx

This is documenting a new configuration option I proposed here: getsentry/sentry-javascript#11153
The PR in the js SDK repository is currently reviewed by @billyvg. Therefore, I'm leaving this note here so we don't forget to update the docs as soon as the feature is merged and released with the next SDK version.
HINT: The documentation is also featuring this image: https://docs.sentry.io/platforms/javascript/common/user-feedback/configuration/user-feedback-widget-customization.png
Maybe we should get a sentry graphics designer involved to update the image, indicating that now also the "(required)" text is configurable.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me …

Document new configuration option

---

docs/product/releases/health/index.mdx

I was reading this page https://docs.sentry.io/product/releases/health/ and noticed the links to the crashes and sessions sections were broken because they used the singular (crash and session) but the anchor tags are plural (crashes and sessions).

fix(releases): Fix broken links

---

platform-includes/getting-started-primer/dotnet.mdx

Came up today from Gene if we supported native crash reporting for .NET on Android and iOS (outside MAUI).
I noticed we don't mention AOT, Portable PDB/server-side symbolication nor native crash reporting on desktop 
@jamescrosswell

dotnet: mention key features

---

docs/platforms/python/enriching-events/tags/index.mdx

Add documentation for the [new `set_tags` function](https://github.com/getsentry/sentry-python/pull/2978) in the Python SDK.
Closes GH-9703

docs(python): Document `set_tags` function

---

platform-includes/debug-symbols-apple/_default.mdx
platform-includes/source-context/apple.mdx

Add snippet for new Fastlane plugin DIF upload action, keeping the old (pre v1.20.0) snippet as second tab
related: 
- https://github.com/getsentry/sentry-fastlane-plugin/pull/234
- https://github.com/getsentry/sentry-fastlane-plugin/issues/245
cc: @denrase

docs(apple): Add snippet for new Fastlane plugin DIF upload action

---

src/components/breadcrumbs.tsx
src/components/navbarClient.tsx
src/components/pageGrid.tsx

In Sentry->Session Replay we're seeing some diffs using the hydration error tool, i'm trying to fix them and see if we can improve, but this won't address all sources of hydration errors.
The diffs are:
I was looking at this replay: https://sentry.sentry.io/replays/3585f82981d74dc5a2bc464525272d6d/?project=1267915&query=&referrer=%2Freplays%2F&statsPeriod=24h&yAxis=count%28%29
initial url was https://docs.sentry.io/product/issues/

fix: Format some inline styles as strings to try and avoid hydration errors

---

docs/platforms/javascript/common/configuration/tree-shaking/index.mdx

This moves the sections around a bit, leading with the bundler plugins instructions now, as they are the easiest to do.
Side note: Currently we do not show the bundler plugin docs for next, sveltekit, remix and astro. For next we have dedicated docs, which seems OK. But, can/should we show bundler plugin docs for these platforms as well? Or is this not possible? cc @Lms24 & @lforst

feat(js): Restructure tree shaking docs

---

docs/platforms/python/migration/1.x-to-2.x.mdx

Change the wording to be more positive

Improve Python migration guide wording

---

docs/product/performance/metrics.mdx

direct users to the new Sentry metric, where the signup page is
there's also [Performance Metrics](https://docs.sentry.io/platforms/javascript/performance/instrumentation/performance-metrics/) on a number of platforms with no note

Sentry Metrics Note

---

docs/product/issues/reprocessing/index.mdx

We have decided to enable this feature for all customers, so lets remove the early adopter note.
Turning the feature on fully happens in https://github.com/getsentry/sentry/pull/68412.

Remove EA note from Reprocessing docs

---

docs/platforms/javascript/common/session-replay/understanding-sessions.mdx

The documentation in this case was not correct and was saying that `replaysSessionSampleRate` should be above 1 which shouldn't be the case for a sample-rate. It probably should mean that `replaysSessionSampleRate` should be above 0. Otherwise it makes no sense for me.

Fix replaysSessionSampleRate in custom sampling example

---

src/middleware.ts

I decided to take this on, as it is kind of breaking right now and/or makes adding redirects super hard.
This adds support for `/guides/:guide/` specifically in the middleware redirects. I decided to literally support this case only, which should cover most stuff but allows us to remain relatively straightforward in the implementation.
Fixes https://github.com/getsentry/sentry-docs/issues/9658

fix: Handle `/guides/:guide` in middleware redirects

---

docs/platforms/javascript/common/sourcemaps/uploading/angular-nx.mdx

Adds instructions for using other Nx Executors (Angular builders), especially for the esbuild-browser executor. Also rewords the guide a bit that the purpose of step one is to enable registering a plugin. 
closes https://github.com/getsentry/sentry-docs/issues/9101

ref(angular): Update Nx CLI source maps upload guide for esbuild

---

docs/platforms/php/guides/laravel/configuration/laravel-options.mdx
docs/product/performance/queries.mdx

Can be merged after https://github.com/getsentry/sentry-laravel/pull/881 is merged and released.

Document the new Laravel SQL origin threshold option

---

docs/platforms/php/guides/laravel/integrations/eloquent.mdx

Documents the model violation reporters in the Laravel SDK.
Can be merged after getsentry/sentry-laravel#824 is released.

Document Laravel Eloquent model violation reporters

---

platform-includes/configuration/before-breadcrumb-hint/dart.mdx
platform-includes/configuration/before-send-fingerprint/dart.mdx
platform-includes/configuration/before-send-hint/dart.mdx
platform-includes/configuration/before-send/dart.mdx
platform-includes/enriching-events/breadcrumbs/before-breadcrumb/dart.mdx
platform-includes/set-fingerprint/basic/dart.mdx
platform-includes/set-fingerprint/database-connection/dart.mdx
platform-includes/set-fingerprint/rpc/dart.mdx

Adjust documentation to reflect a breaking change to a `beforeSend` signature introduced in v8.0.0:
- Pull Request introducing the change: https://github.com/getsentry/sentry-dart/pull/1574
- Issue with context: https://github.com/getsentry/sentry-dart/issues/1478 

Fix beforeSend signature in code snippets for dart platforms

---

docs/product/issues/suspect-commits/index.mdx

super small nit clarifying that we're talking about the reader's Sentry org and not _the_ Sentry org

chore(grammar): change "the" to "your" in suspect commits page

---

docs/product/profiling/mobile-app-profiling/metrics.mdx

To distinguish [profiling metrics](https://docs.sentry.io/product/profiling/mobile-app-profiling/metrics/) from [performance metrics](https://docs.sentry.io/product/performance/metrics/) and [custom metrics](https://docs.sentry.io/product/metrics/)

Rename Metrics to Profiling Metrics

---

docs/platforms/apple/common/data-management/apple-privacy-manifest.mdx
docs/platforms/apple/common/troubleshooting/index.mdx

Adds a new page to explain what APIs need to be listed in the Apple Privacy Manifest for apps with Sentry SDK to be published in the App Store. https://github.com/getsentry/sentry-docs/pull/9752 for Apple
related: https://github.com/getsentry/team-mobile/issues/183

chore(apple): Add Apple Privacy Manifest guide

---

docs/platforms/python/migration/1.x-to-2.x.mdx

Messed up the last [migration guide merge](https://github.com/getsentry/sentry-docs/pull/9182/commits/e672fca4613684cd59f6669b7c8dc3606ece7b0c). Fixing. …

fix(python): Fix migration guide

---

docs/platforms/javascript/common/migration/index.mdx
docs/platforms/javascript/common/migration/v4-to-v5_v6.mdx
docs/platforms/javascript/common/migration/v6-to-v7.mdx
docs/platforms/javascript/common/migration/v7-to-v8.mdx
docs/platforms/javascript/common/migration/v7-to-v8/index.mdx
docs/platforms/javascript/common/migration/v7-to-v8/v8-new-performance-api.mdx
docs/platforms/javascript/common/migration/v7-to-v8/v8-opentelemetry.mdx
includes/migration/javascript-v8/browser-other-changes.mdx
includes/migration/javascript-v8/node-other-changes.mdx
includes/migration/javascript-v8/server-other-changes.mdx
platform-includes/migration/javascript-v8/important-changes/javascript.nextjs.mdx
platform-includes/migration/javascript-v8/integrations-package-removal/javascript.nextjs.mdx
platform-includes/migration/javascript-v8/intro/javascript.nextjs.mdx
platform-includes/migration/javascript-v8/other-changes/javascript.nextjs.mdx
platform-includes/migration/javascript-v8/summary/javascript.mdx
platform-includes/migration/javascript-v8/troubleshooting/javascript.nextjs.mdx

This is a start to revamped migration docs for our Sentry JavaScript SDK.
These still link to the repo readme, but contain more accessible migration guides for our users. As an example, I've added a relatively fleshed out set of instructions for migrating a `Next.js` app.
If this general approach is agree'd upon, I'm going to work toward porting the rest of the migration docs into fitting this format, and then adding docs for Node, Browser, React, and Express. With those changed (and Next.js being finished), we then incrementally tackle the other more detailed migration guides whenever we want! (we could even merge them in after v8 releases).
Top level migration docs:
Troubleshooting (maybe should be named FAQ?) at the bottom:
OpenTelemetry docs!

feat: Add JavaScript SDK migration docs to Sentry docs site

---

docs/platforms/python/integrations/index.mdx
docs/platforms/python/integrations/langchain/index.mdx

feat(ai-monitoring): Langchain integration docs

---

docs/product/reference/search/searchable-properties/events.mdx

Remove Replay references under Event Properties to reduce confusion since event properties are defined as specifically errors and transactions in this document.

Remove replay references under Event Properties.mdx

---

docs/platforms/javascript/common/migration/index.mdx
docs/platforms/javascript/common/migration/v4-to-v5_v6.mdx
docs/platforms/javascript/common/migration/v6-to-v7.mdx
docs/platforms/javascript/common/migration/v7-to-v8/index.mdx
docs/platforms/javascript/common/migration/v7-to-v8/v7-deprecations.mdx
docs/platforms/javascript/common/migration/v7-to-v8/v8-new-performance-api.mdx
docs/platforms/javascript/common/migration/v7-to-v8/v8-opentelemetry.mdx
includes/migration/javascript-v8/browser-other-changes.mdx
includes/migration/javascript-v8/general-other-changes.mdx
includes/migration/javascript-v8/node-other-changes.mdx
includes/migration/javascript-v8/server-other-changes.mdx
includes/migration/javascript-v8/v7-deprecation/browser-tracing.mdx
includes/migration/javascript-v8/v7-deprecation/class-based-integrations.mdx
includes/migration/javascript-v8/v7-deprecation/general.mdx
platform-includes/migration/javascript-v8/other-changes/javascript.nextjs.mdx
platform-includes/migration/javascript-v8/v7-deprecation/javascript.angular.mdx
platform-includes/migration/javascript-v8/v7-deprecation/javascript.astro.mdx
platform-includes/migration/javascript-v8/v7-deprecation/javascript.bun.mdx
platform-includes/migration/javascript-v8/v7-deprecation/javascript.deno.mdx
platform-includes/migration/javascript-v8/v7-deprecation/javascript.gatsby.mdx
platform-includes/migration/javascript-v8/v7-deprecation/javascript.mdx
platform-includes/migration/javascript-v8/v7-deprecation/javascript.nextjs.mdx
platform-includes/migration/javascript-v8/v7-deprecation/javascript.node.mdx
platform-includes/migration/javascript-v8/v7-deprecation/javascript.react.mdx
platform-includes/migration/javascript-v8/v7-deprecation/javascript.remix.mdx
platform-includes/migration/javascript-v8/v7-deprecation/javascript.svelte.mdx
platform-includes/migration/javascript-v8/v7-deprecation/javascript.sveltekit.mdx
platform-includes/migration/javascript-v8/v7-deprecation/javascript.vue.mdx

This builds upon https://github.com/getsentry/sentry-docs/pull/9796, porting the `7.x` deprecations to the docs, and adding the rest of the behaviour changes to the docs as well.
Next up - Node frameworks!

feat(js): Add all relevant deprecations and expand breaking changes for next.js

---

docs/platforms/javascript/common/configuration/integrations/breadcrumbs.mdx
docs/platforms/javascript/common/configuration/integrations/browsertracing.mdx
docs/platforms/javascript/common/configuration/integrations/console.mdx
docs/platforms/javascript/common/configuration/integrations/globalhandlers.mdx
docs/platforms/javascript/common/configuration/integrations/http.mdx
docs/platforms/javascript/common/configuration/integrations/httpclient.mdx
docs/platforms/javascript/common/configuration/integrations/httpcontext.mdx
docs/platforms/javascript/common/configuration/integrations/localvariables.mdx
docs/platforms/javascript/common/configuration/integrations/modulemetadata.mdx
docs/platforms/javascript/common/configuration/integrations/modules.mdx
docs/platforms/javascript/common/configuration/integrations/nodecontext.mdx
docs/platforms/javascript/common/configuration/integrations/nodefetch.mdx
docs/platforms/javascript/common/configuration/integrations/onuncaughtexception.mdx
docs/platforms/javascript/common/configuration/integrations/replay.mdx
docs/platforms/javascript/common/configuration/integrations/reportingobserver.mdx
docs/platforms/javascript/common/configuration/integrations/requestdata.mdx
docs/platforms/javascript/common/configuration/integrations/trycatch.mdx
docs/platforms/javascript/common/configuration/integrations/unhandledrejection.mdx

To also show Node.js integrations in meta-frameworks like Next.js or SvelteKit.

docs(integrations): Add environment information to integrations

---

includes/migration/javascript-v8/node-other-changes.mdx
includes/migration/javascript-v8/server-other-changes.mdx
platform-includes/migration/javascript-v8/important-changes/javascript.astro.mdx
platform-includes/migration/javascript-v8/important-changes/javascript.aws-lambda.mdx
platform-includes/migration/javascript-v8/important-changes/javascript.azure-functions.mdx
platform-includes/migration/javascript-v8/important-changes/javascript.connect.mdx
platform-includes/migration/javascript-v8/important-changes/javascript.express.mdx
platform-includes/migration/javascript-v8/important-changes/javascript.gcp-functions.mdx
platform-includes/migration/javascript-v8/important-changes/javascript.koa.mdx
platform-includes/migration/javascript-v8/important-changes/javascript.nextjs.mdx
platform-includes/migration/javascript-v8/important-changes/javascript.node.mdx
platform-includes/migration/javascript-v8/important-changes/javascript.remix.mdx
platform-includes/migration/javascript-v8/important-changes/javascript.sveltekit.mdx
platform-includes/migration/javascript-v8/other-changes/javascript.bun.mdx
platform-includes/migration/javascript-v8/other-changes/javascript.deno.mdx
platform-includes/migration/javascript-v8/other-changes/javascript.sveltekit.mdx

fix(js): Remove redundant otel note from migration

---

docs/platforms/dart/user-feedback/index.mdx
docs/platforms/flutter/user-feedback/index.mdx
platform-includes/user-feedback/sdk-api-example/dart.mdx

Closes https://github.com/getsentry/sentry-dart/issues/1902
Adds `lastEventId` reference to user feedback page

flutter(user-feedback): document `lastEventId`

---

docs/contributing/pages/redirects.mdx

- Remove redirect instructions for `next.config.js` 
- Add redirect instructions for `middleware.ts`
- Add redirect instructions for `vercel.json`

update contributing redirects instructions

---

docs/platforms/index.mdx

We now have a 1st party fastify sdk - we should recommend that!

fix: Remove community fastify sdk

---

platform-includes/sensitive-data/set-tag/native.mdx
platform-includes/sensitive-data/set-user/native.mdx

Adds snippets to strip sensitive data with set_tag and set_user. Tried to keep the examples in line with the other platforms (e.g. `checksum_or_hash`)
cc @supervacuus

chore(native): Add snippets to strip sensitive data with set_tag and set_user

---

docs/platforms/apple/common/configuration/http-client-errors.mdx
platform-includes/configuration/before-send/apple.mdx

Change code comment to return nil instead of NULL.

fix(apple): Return nil in beforeSend

---

platform-includes/configuration/capture-console/javascript.mdx
platform-includes/configuration/capture-console/javascript.node.mdx
platform-includes/configuration/contextlines/javascript.mdx
platform-includes/configuration/debug/javascript.mdx
platform-includes/configuration/debug/javascript.node.mdx
platform-includes/configuration/dedupe/javascript.mdx
platform-includes/configuration/dedupe/javascript.node.mdx
platform-includes/configuration/enable-pluggable-integrations-lazy/javascript.mdx
platform-includes/configuration/enable-pluggable-integrations-lazy/javascript.node.mdx
platform-includes/configuration/enable-pluggable-integrations/javascript.mdx
platform-includes/configuration/enable-pluggable-integrations/javascript.node.mdx
platform-includes/configuration/extra-error-data/javascript.mdx
platform-includes/configuration/extra-error-data/javascript.node.mdx
platform-includes/configuration/http-client/javascript.mdx
platform-includes/configuration/reporting-observer/javascript.mdx
platform-includes/configuration/rewrite-frames/javascript.mdx
platform-includes/configuration/rewrite-frames/javascript.node.mdx
platform-includes/configuration/sessiontiming/javascript.mdx
platform-includes/configuration/sessiontiming/javascript.node.mdx

This is not needed anymore since 7.112.0, and will be removed in v8. By updating this docs work both for v7 and v8.

feat(js): Remove `@sentry/integrations` recommendation

---

docs/platforms/javascript/common/configuration/async-context.mdx
docs/platforms/javascript/common/configuration/options.mdx
docs/platforms/javascript/guides/fastify/configuration/async-context.mdx

Mainly, updates the Async Context docs for fastify (v8 beta), and removes the `caCerts` option (it does not exist in JS).

feat: Some adjustments of docs

---

docs/platforms/apple/common/configuration/app-hangs.mdx

Explain how to filter app hang events in beforeSend.

feat(apple): Filter app hang events

---

docs/product/performance/mobile-vitals/index.mdx

Fixed a typo in the docs to update "for you application" to "for your application"

fix:  Fixed a typo in the docs to update "for you application" to "for your application"

---

docs/platforms/python/migration/1.x-to-2.x.mdx

Fixes the link to the python migration documentation, the current link 404s.

Fix link to migration docs in github in Update 1.x-to-2.x.mdx 

---

docs/platforms/react-native/configuration/options.mdx

- Implemented https://github.com/getsentry/sentry-react-native/blob/4d3618dd04096827f76057238a9f96f44abf04db/src/js/options.ts#L111
The desc is copied form the native SDKs.
- https://github.com/getsentry/sentry-docs/edit/master/docs/platforms/android/configuration/options.mdx

Add `maxCacheItems` to RN Options

---

docs/platforms/native/advanced-usage/index.mdx
docs/platforms/native/advanced-usage/signal-handling/index.mdx

This PR introduces a new section, "Advanced usage," which allows us to go into much more detail when describing how operating systems behave and how this affects users of the Native SDK.
This section should house topics that our users repeatedly encounter, which we cannot hide behind a nice facade and which runtime developers do not abstract away from our responsibility (as is the case for most other SDKs).
While this section will soon see additions like
- [WER module usage ](https://github.com/getsentry/sentry-native/issues/875#issuecomment-1689564967)
- Debugging & resolving `UnhandledExceptionFilter` overwrites
- [Stackoverflow handling on Windows](https://github.com/getsentry/sentry-native/issues/977)
- [Trade-offs in determining which backend to …

feat(native): advanced usage section to explain OS error handling

---

docs/platforms/apple/common/data-management/apple-privacy-manifest.mdx
docs/platforms/flutter/data-management/apple-privacy-manifest.mdx
docs/platforms/react-native/data-management/apple-privacy-manifest.mdx

updates min versions listed in apple privacy manifest docs for cocoa, RN and flutter

chore: Update min versions in apple privacy docs

---

docs/platforms/elixir/crons/troubleshooting.mdx
docs/platforms/java/common/crons/troubleshooting.mdx
docs/platforms/javascript/common/crons/troubleshooting.mdx
docs/platforms/php/common/crons/troubleshooting.mdx
docs/platforms/python/crons/troubleshooting.mdx
docs/platforms/ruby/common/crons/troubleshooting.mdx
docs/product/crons/troubleshooting.mdx
platform-includes/crons/troubleshooting/elixir.mdx
platform-includes/crons/troubleshooting/java.mdx
platform-includes/crons/troubleshooting/javascript.mdx
platform-includes/crons/troubleshooting/php.mdx
platform-includes/crons/troubleshooting/python.mdx
platform-includes/crons/troubleshooting/ruby.mdx

Removes mentions of attachments in troubleshooting docs for crons.

ref(crons): Remove mentions of attachments (deprecated)

---

docs/product/data-management-settings/event-grouping/fingerprint-rules.mdx

Problem
--------
- It was not clear from the documentation that variables in fingerprints would be interpreted for fingerprints set on the client side, outside of fingerprint rules.
- The documentation hinted that fingerprints disable default grouping.
Solution
--------
- Add context to the statement about overriding default grouping that makes it clear that you can still opt in to default grouping when using fingerprinting.
- Make it clear that fingerprint variables are not only evaluated on the right hand side of server-side rules, but also when included in fingerprints set via Sentry SDKs.
*Describe your changes here. If your PR relates to or resolves an issue, add a …

Adds more information about how to use fingerprint variables

---

docs/contributing/approach/sdk-docs/common_content.mdx
docs/contributing/platforms/index.mdx
docs/contributing/platforms/platform-icons/index.mdx

Because there are several steps that one must do to make a new platform icon to work in docs. 
- [Sentry Docs …

Added a guide for how to add a new platform icon to the docs

---

docs/platforms/dotnet/guides/xamarin/data-management/apple-privacy-manifest.mdx
docs/platforms/dotnet/guides/xamarin/data-management/index.mdx

Apple now requires the user projects to include a Privacy manifest file on their project, this PR aids the user on how to add this information on an Xamarin project and also informs the required fields when using Sentry.

doc(Xamarin): Add privacy info page for Xamarin

---

docs/platforms/dotnet/common/profiling/index.mdx

Relates to:
* https://github.com/getsentry/sentry-dotnet/issues/3336

dotnet profiling doesnt need prerelease

---

src/components/changelog/list.tsx

#9410 
Added params for both date and …

fix: added params for filters on changelog listing page

---

docs/organization/integrations/integration-platform/webhooks/issues.mdx

We're launching a new status: `unresolved` and I also think we need to explain what `substatus` is for that to make sense.
https://sentry-docs-git-athena-webhook-docs.sentry.dev/product/integrations/integration-platform/webhooks/issues/

Update webhook docs for issues

---

app/changelog/header.tsx
src/components/changelog/article.tsx

next/image doesn't work with the redirects we do and static images we serve from Google

fix: Changelog Images

---

docs/platforms/kotlin-multiplatform/native-access-sdk.mdx
platform-includes/getting-started-install/kotlin-multiplatform.mdx
platform-includes/getting-started-primer/kotlin-multiplatform.mdx

Update versions for 0.6.0 release

kmp: update versions for 0.6.0 release

---

src/components/platformSelector/index.tsx

platform selector didn't filter out integrations shown as guides properly

fix: narrow down integrations properly on platformSelector

---

docs/platforms/dotnet/common/index.mdx
docs/platforms/go/common/index.mdx
docs/platforms/javascript/common/index.mdx
docs/platforms/php/index.mdx
docs/platforms/python/index.mdx
docs/platforms/rust/index.mdx
platform-includes/alert-using-a-framework/_default.mdx
platform-includes/framework-list/javascript.mdx
platform-includes/framework-list/python.mdx

Update this alert message since we've moved frameworks out of the right hand nav.

update using framework alert

---

docs/platforms/php/guides/symfony/index.mdx

Add fill_extra_context option to the symfony documentation. https://github.com/getsentry/sentry-php/blob/master/src/Monolog/Handler.php
See also comment from @nuryagdym https://github.com/getsentry/sentry-php/issues/870#issuecomment-1833319890
Thx @cviniciussdias for the hint. …

Add fill_extra_context option to the symfony documentation

---

src/components/codeBlock/code-blocks.module.scss

fix codeBlock overflow on short lines

---

src/components/search/index.tsx

Fix the `relativizeUrl` function's permissive regex. The original pattern could match any domain name that contains "docs.sentry.io" in it. For example, it would match `http://docs.sentry.io.malicious-site.com`.
Resolves CodeQL scanning alert: https://github.com/getsentry/sentry-docs/security/code-scanning/2

fix: permissive regex

---

docs/product/performance/resources.mdx

minor cleanup, there was some random backticks on the page

fix(resources): stray backticks

---

docs/platforms/javascript/common/performance/instrumentation/requests-module.mdx
docs/platforms/python/performance/instrumentation/requests-module.mdx
docs/product/performance/requests.mdx

I'm following the template set up for the Caches documentation! Adding manual instrumentation docs for JavaScript and Python, and linking to the snippets from the module documentation. Very similar to https://github.com/getsentry/sentry-docs/pull/9926/

feat(perf): Requests module SDK instrumentation documentation

---

docs/platforms/react-native/configuration/options.mdx

Update options for performance tracing and watchdog termination to reflect their new names in the v5 versions of React Native.
attachStacktrace is also On by default in React Native, whereas the docs currently listed it as Off.

Update deprecated option names and attachStacktrace value

---

docs/platforms/javascript/common/session-replay/understanding-sessions.mdx

Adds a hypothetical example of how you can send a replay when a user opens a support widget.
Closes https://github.com/getsentry/sentry-docs/issues/9037

feat(replay): Document how to connect Replay with support software

---

docs/platforms/javascript/common/user-feedback/index.mdx
docs/product/user-feedback/index.mdx
docs/product/user-feedback/setup.mdx
includes/feature-stage-beta-user-feedback.mdx

As of this week User Feedback has been GA'd and is the primary way of submitting feedback!
The old method, user reports, required an associated error event but this method does not. So when describing the widget/overall product, the mentions of associating events are incorrect. 
--- …

doc(feedback): remove beta banners and 'associated error event' mentions

---

docs/platforms/javascript/common/configuration/transports.mdx
includes/migration/javascript-v8/browser-other-changes.mdx

There was a typo in the link, oops.

fix(js): Fix dead link

---

src/remark-format-code.js

Don't log for failed code block formatting

---

docs/platforms/javascript/common/session-replay/index.mdx

Canvas has been in GA for a few weeks now, time to remove the beta notice.

feat(replay): Remove "canvas is in beta" notice

---

docs/platforms/javascript/guides/nextjs/manual-setup.mdx

This PR to fix a wrong filename in the "[Create Initialization Config Files](https://docs.sentry.io/platforms/javascript/guides/nextjs/manual-setup/#create-initialization-config-files)" section's code sample, which describes how to import the configuration for the server and edge runtime from a [Next.js instrumentation file](https://nextjs.org/docs/app/building-your-application/optimizing/instrumentation). …

fix(nextjs): change instrumentation filename

---

docs/platforms/javascript/common/migration/v7-to-v8/index.mdx

I have seen people confused about that migr8 does not change Next.js configuration for example.

Suggest to still read the js v8 changelog despite having `@sentry/migr8`

---

docs/platforms/javascript/guides/angular/features/component-tracking.mdx
platform-includes/capture-error/javascript.angular.mdx
platform-includes/enriching-events/import/javascript.angular.mdx
platform-includes/getting-started-config/javascript.angular.mdx
platform-includes/getting-started-config/javascript.capacitor.mdx
platform-includes/getting-started-install/javascript.angular.mdx
platform-includes/getting-started-install/javascript.capacitor.mdx
platform-includes/migration/javascript-v8/important-changes/javascript.angular.mdx
platform-includes/profiling/automatic-instrumentation-setup/javascript.angular.mdx
platform-includes/session-replay/install/javascript.angular.mdx
platform-includes/session-replay/install/javascript.capacitor.mdx
platform-includes/session-replay/setup-canvas/javascript.angular.mdx
platform-includes/session-replay/setup/javascript.angular.mdx
platform-includes/user-feedback/install/javascript.angular.mdx
platform-includes/user-feedback/setup/javascript.angular.mdx

(draft until v8 is stable)
This PR updates our Angular SDK docs for the v8 major bump. Changes:
- Removed `@sentry/angular-ivy` imports and related duplicated snippets. No longer necessary as in v8, there's only one Angular package (for the moment at least)
- Renamed the `TraceClass` and `TraceMethod` decorators and slightly reworked the component tracking docs
- Re-worked the Getting Started docs to finally have _one_ code snippet that shows all providers that are necessary to set up. Previously, we had 3 different snippets which made the setup utterly complicated to follow. Technically, this is a bit out of scope but since I was looking at Angular docs, I figured I might as well improve things.
- Added highlighting to most snippets

feat(js/angualar): Update Angular docs for v8

---

docs/platforms/javascript/common/install/commonjs.mdx
docs/platforms/javascript/common/install/esm-without-import.mdx
docs/platforms/javascript/common/install/esm.mdx
docs/platforms/javascript/guides/fastify/index.mdx

This updates the docs to add another installation method.
While at it, I also improved the two existing ones, streamlining this a bit.

feat(js): Add docs to use SDK with ESM without `--import`

---

docs/platforms/javascript/common/migration/v7-to-v8/v8-opentelemetry.mdx
platform-includes/migration/javascript-v8/important-changes/javascript.astro.mdx
platform-includes/migration/javascript-v8/important-changes/javascript.aws-lambda.mdx
platform-includes/migration/javascript-v8/important-changes/javascript.azure-functions.mdx
platform-includes/migration/javascript-v8/important-changes/javascript.bun.mdx
platform-includes/migration/javascript-v8/important-changes/javascript.connect.mdx
platform-includes/migration/javascript-v8/important-changes/javascript.deno.mdx
platform-includes/migration/javascript-v8/important-changes/javascript.express.mdx
platform-includes/migration/javascript-v8/important-changes/javascript.fastify.mdx
platform-includes/migration/javascript-v8/important-changes/javascript.gcp-functions.mdx
platform-includes/migration/javascript-v8/important-changes/javascript.koa.mdx
platform-includes/migration/javascript-v8/important-changes/javascript.nextjs.mdx
platform-includes/migration/javascript-v8/important-changes/javascript.node.mdx
platform-includes/migration/javascript-v8/important-changes/javascript.remix.mdx
platform-includes/migration/javascript-v8/important-changes/javascript.sveltekit.mdx

- Fix weird sentence construction when mentioning OpenTelemetry
- Before: "though if you use OpenTelemetry-native APIs to start spans, and Sentry will pick up everything automatically."
- After: "though if you use OpenTelemetry-native APIs to start spans, Sentry will pick up everything automatically."
- Remove duplicate text about not needing to know what OpenTelemetry is
- Before: "You do not need to know or understand what OpenTelemetry is in order to use Sentry. We set up OpenTelemetry under the hood, no knowledge of it is required in order to get started."
- After: "You do not need to know or understand what OpenTelemetry is in order to use Sentry. We set up OpenTelemetry under the hood."
- Teamwork …

Fix grammar of sentences mentioning OpenTelemetry

---

docs/platforms/react-native/manual-setup/metro.mdx
docs/platforms/react-native/sourcemaps/uploading/hermes.mdx
docs/platforms/react-native/sourcemaps/uploading/jsc.mdx

- This PR updates the RN Metro docs to use the latest functions from the SDK 
- https://github.com/getsentry/sentry-react-native/releases/tag/5.17.0

feat(rn): Update `metro.config.js` samples to use the latest withSentryConfig fucntion

---

docs/platforms/dotnet/guides/aspnetcore/index.mdx

The documentation on the ASP.NET Core page (https://docs.sentry.io/platforms/dotnet/guides/aspnetcore/#capturing-the-affected-user) references `IUserFactory`, but per [#2719](https://github.com/getsentry/sentry-dotnet/pull/2719) it should be `ISentryUserFactory`
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from …

Fix: Rename IUserFactory to ISentryUserFactory

---

docs/platforms/javascript/guides/aws-lambda/layer/index.mdx

Ideally we would want to have another dropdown for v7 that automatically spits out the latest ARN for v7, but this is a change that needs to be carefully evaluated in `craft` and `sentry-release-registry`. For now we'll have to live with a hard-coded ARN for v7.
ref: https://github.com/getsentry/sentry-javascript/issues/12098

docs(lambda): Add AWS Lambda layer for v7 node sdk

---

docs/concepts/search/searchable-properties/session-replay.mdx

Update after https://github.com/getsentry/sentry/pull/70967

Change viewed_by_id->viewed_by_me in replay search props

---

platform-includes/metrics/configure/javascript.astro.mdx
platform-includes/metrics/configure/javascript.mdx
platform-includes/metrics/configure/javascript.nextjs.mdx
platform-includes/metrics/configure/javascript.remix.mdx
platform-includes/metrics/configure/javascript.sveltekit.mdx

The integration in v8 is no longer needed, removing it from code snippets.

ref: Remove metrics integration

---

docs/platforms/javascript/common/troubleshooting/supported-browsers.mdx

Copying over https://docs.sentry.io/platforms/javascript/migration/v7-to-v8/#supported-versions

feat(js): Update supported browsers based on v8

---

docs/platforms/javascript/guides/sveltekit/manual-setup.mdx
platform-includes/getting-started-verify/javascript.sveltekit.mdx
platform-includes/sourcemaps/primer/javascript.sveltekit.mdx

Updates SvelteKit docs to reflect Vite plugin 2.x bump. Also added a bunch of code block highlights - great stuff @a-hariti!

ref(v8/sveltekit): Adjust manual setup for Vite plugin 2.x bump

---

docs/platforms/javascript/guides/sveltekit/manual-setup.mdx

Missed documenting more example options in #9343, so this PR adds a couple of them. Also it fixes a link that pointed to the wrong version of Vite plugin options.

fix(sveltekit): Show more `sentrySvelteKit` plugin options

---

docs/product/metrics/index.mdx

This PR updates our develop docs with the updated limits for metric name and unit lengths.
Related to: https://github.com/getsentry/relay/pull/3628

feat(metrics): Add maximum length for metric components

---

platform-includes/getting-started-add-top-level-import/javascript.fastify.mdx
platform-includes/getting-started-use/javascript.fastify.mdx
platform-includes/migration/javascript-v8/important-changes/javascript.fastify.mdx

Reference: https://github.com/getsentry/sentry-javascript/issues/12119#issuecomment-2122228817
Also, this now lines up with the code snippet in sentry ui.

ref(fastify): Recommend the default export of fastify over named export

---

docs/platforms/python/performance/instrumentation/custom-instrumentation/caches-module.mdx
docs/platforms/python/performance/instrumentation/custom-instrumentation/queues-module.mdx

A guide on how to manually instrument spans so they are eligible for the Queues Insighs Module. 
Preview: https://sentry-docs-git-antonpirker-python-queues-module-manual-533d53.sentry.dev/platforms/python/performance/instrumentation/custom-instrumentation/queues-module/
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some …

[Python] Guide for Manual Queues Insights Module Instrumenation

---

docs/product/metrics/metrics-explorer-page.mdx

Remove references to Percentiles, since we removed them from distributions in the product already.

Remove references to Percentiles

---

docs/platforms/javascript/common/performance/instrumentation/custom-instrumentation/requests-module.mdx

- Remove SDK init section as it's covered extensively in higher-level guides
- Some wording and code adjustments

ref(javascript): Streamline custom http request instrumenation guide

---

includes/migration/javascript-v8/general-other-changes.mdx
includes/migration/javascript-v8/v7-deprecation/general.mdx

Looks like we missed this in https://github.com/getsentry/sentry-javascript/issues/11951
This PR removes the deprecation and removal message in the migration guide of our `lastEventId` API (which we decided to bring back in version 8.1.0).

ref(javascript): Revert `lastEventId` removal (v8) and deprecation (v7) in migration docs

---

docs/platforms/dotnet/guides/azure-functions-worker/index.mdx

Fixes https://github.com/getsentry/sentry-docs/issues/10041
If you (as a user) are using the ASP.NET integration use the `ConfigureFunctionsWebApplication` call instead of `ConfigureFunctionsWorkerDefaults`. It's an either/or situation, but not both.

fix(.NET): Update Azure Functions

---

docs/platforms/elixir/crons/troubleshooting.mdx
docs/platforms/java/common/crons/troubleshooting.mdx
docs/platforms/javascript/common/crons/troubleshooting.mdx
docs/platforms/php/common/crons/troubleshooting.mdx
docs/platforms/python/crons/troubleshooting.mdx
docs/platforms/ruby/common/crons/troubleshooting.mdx
docs/product/crons/troubleshooting.mdx
includes/feature-stage-beta-crons.mdx

Since Crons is not in beta any longer, I'm removing the crons-feedback email from our docs.

Remove crons-feedback email

---

docs/platforms/python/performance/instrumentation/custom-instrumentation/caches-module.mdx

Complements https://github.com/getsentry/sentry-docs/pull/10121/
Removes the section about initializing sentry as it's documented throughly throughout our docs

ref(python): remove initialize sentry section in python

---

docs/platforms/javascript/common/configuration/integrations/browserprofiling.mdx
docs/platforms/javascript/common/configuration/integrations/nodeprofiling.mdx

This adds the browser & node profiling integrations to the list of integrations, streamlining this a bit.
it mostly links out to the relevant page, but should still make it easier to find this.

feat(js): Add profiling integrations

---

docs/platforms/javascript/common/performance/instrumentation/custom-instrumentation/queues-module.mdx

- Only show page on server-side guides
- remove imports from `@sentry/core` - we should never tell people to import from it
as it's only a transitive dependency from their SDK. Here, we can make use of the 
`Sentry.` namespace import that people are familiar with from other docs. This also
saves us the hassle of having to customize the imported package for each guide :)
- just minor formatting (prettier) and code snippet fixes

ref(javascript): Streamline queue instrumentation page

---

docs/product/performance/caches/index.mdx
docs/product/performance/queue-monitoring/index.mdx

While working on #10121 and #10123 I missed that we link to these pages in our product walkthrough docs. This PR adjusts the links.

fix(js): Fix broken cache and queue monitoring product walkthrough links

---

docs/platforms/react-native/manual-setup/manual-setup.mdx

Tiny fix for the Debug Files upload, adding full path to the Sentry RN SDK module.

fix: Path to RN Module for Debug Files upload

---

docs/platforms/javascript/common/configuration/integrations/custom.mdx

This updates the JS custom integration docs to show which APIs we support.

feat(js): Update docs for custom integrations

---

platform-includes/metrics/configure/javascript.astro.mdx
platform-includes/metrics/configure/javascript.bun.mdx
platform-includes/metrics/configure/javascript.deno.mdx
platform-includes/metrics/configure/javascript.electron.mdx
platform-includes/metrics/configure/javascript.mdx
platform-includes/metrics/configure/javascript.nextjs.mdx
platform-includes/metrics/configure/javascript.node.mdx
platform-includes/metrics/configure/javascript.remix.mdx
platform-includes/metrics/configure/javascript.sveltekit.mdx

Display v7 configuration instructions for metrics as comment.
Relates to https://github.com/getsentry/sentry/issues/71510

feat(metrics): Add comments for v7 configuration

---

docs/platforms/javascript/guides/node/profiling/index.mdx

https://github.com/getsentry/sentry-javascript/issues/11455 was released, so we can update the profiling docs!

Add Node 22 to profiling docs

---

docs/platforms/dotnet/common/performance/instrumentation/automatic-instrumentation.mdx

Added docs explaining that transactions/spans don't get created for outbound HTTP requests when there is an active transaction on the scope, when using the .NET SDK.
Resolves https://github.com/getsentry/sentry-dotnet/issues/3370
CC: @bitsandfoxes for review

Documented request tracing requirement for an active transaction on the scope to the .NET docs

---

docs/platforms/javascript/guides/aws-lambda/profiling/index.mdx
docs/platforms/javascript/guides/azure-functions/profiling/index.mdx
docs/platforms/javascript/guides/connect/performance/index.mdx
docs/platforms/javascript/guides/connect/profiling/index.mdx
docs/platforms/javascript/guides/express/performance/index.mdx
docs/platforms/javascript/guides/express/profiling/index.mdx
docs/platforms/javascript/guides/fastify/performance/index.mdx
docs/platforms/javascript/guides/fastify/profiling/index.mdx
docs/platforms/javascript/guides/gcp-functions/profiling/index.mdx
docs/platforms/javascript/guides/hapi/performance/index.mdx
docs/platforms/javascript/guides/hapi/profiling/index.mdx
docs/platforms/javascript/guides/koa/performance/index.mdx
docs/platforms/javascript/guides/koa/profiling/index.mdx
docs/platforms/javascript/guides/nestjs/performance/index.mdx
docs/platforms/javascript/guides/nestjs/profiling/index.mdx
docs/platforms/javascript/guides/node/performance/index.mdx

This kind of got messed up along the way and was not really consistent anymore.
Now we use the same label & order for all the js variants again.

fix(node): Fix performance & profiling page name & order

---

docs/platforms/javascript/common/performance/instrumentation/opentelemetry.mdx

Docs to match https://github.com/getsentry/sentry-javascript/pull/12214
This updates the docs for when a user has an existing OTEL setup to actually work.
Only merge this once https://github.com/getsentry/sentry-javascript/pull/12214 is published!

feat(node): Update docs for manual OTEL setup

---

docs/product/performance/caches/cache-page.mdx
docs/product/performance/caches/index.mdx
docs/product/performance/queue-monitoring/index.mdx

Adds cache module arcade to caches documentation and queue module arcade.
I added it in a location consistent to the other modules, for examples requests shows the arcade just after the quick blurb on how to use the module
https://docs.sentry.io/product/performance/requests/

add caches walkthrough arcade

---

docs/platforms/javascript/common/user-feedback/v7/index.mdx

Add a link in the docs pages so people can find the migration steps as they're reading about feedback in the v7 sdk.
Fixes https://github.com/getsentry/sentry-javascript/issues/12015

docs(feedback): Link to migration guide for feedback from SDK v7 to v8

---

docs/platforms/android/features/index.mdx
docs/platforms/android/index.mdx

We removed this a while ago from the landing page to streamline the getting started experience. Re-adding this now as separate Features page.
The list is a good reference for new and existing users.

feat(Android): Re-add features list as separate page

---

src/components/tableOfContents/index.tsx

scrolling fast up and down a page leads to many calls to the history API to update the url `#`,
getting rid of this functionality for now

fix: don't update the url # on scroll

---

src/remark-format-code.js

We do not want "our" (as in, the docs developers) prettier config to be what dictates the content of code blocks, but rather we want to stick to the default prettier config as much as possible because that is what people are used to.

ref: Use default prettier config for formatting code blocks instead of repository config

---

docs/platforms/javascript/common/user-feedback/configuration/index.mdx

This adds documentation for a new feature/behavior within the User Feedback SDK -> different strategies for bundling the SDK code within your app.
I tried to be verbose about what's available, and what the defaults are. I hope it makes sense. 
Relates to https://github.com/getsentry/sentry/issues/70862

docs(feedback): Add notes about async loading the Feedback integration

---

includes/javascript-crons-upsert.mdx

Note: Only merge after `8.6.0` gets merged in!
Documents https://github.com/getsentry/sentry-javascript/pull/12248

Add `failureIssueThreshold` and `recoveryThreshold` to js cron docs

---

docs/platforms/javascript/guides/react/features/tanstack-router.mdx

Adds docs for the newly added TanStack router integration: https://github.com/getsentry/sentry-javascript/pull/12095 …

Add TanStack Router docs

---

docs/platforms/python/integrations/celery/index.mdx

Small update to distributed tracing in Celery

---

platform-includes/getting-started-config/javascript.react.mdx

~Do not merge until `8.6.0` releases.~ Released!
ref https://github.com/getsentry/sentry-javascript/issues/11798
documents https://github.com/getsentry/sentry-javascript/pull/12147

feat(react): Document `Sentry.reactErrorHandler`

---

docs/platforms/javascript/common/index.mdx
platform-includes/getting-started-primer/javascript.bun.mdx
platform-includes/getting-started-primer/javascript.svelte.mdx

We can remove these beta warnings for bun & deno I believe, and also I updated the primer about the migration warnings.

feat(js) Update primers & headers for JS

---

platform-includes/migration/javascript-v8/v7-deprecation/javascript.react.mdx

Very minor, but I encountered this issue when upgrading to `@sentry/react@8`. The import incorrectly refers to the `/svelte` package when in the React docs context …

docs(react): correct import in React v8 migration docs

---

src/components/onboarding/index.tsx

Fix onboarding options jumping

---

docs/product/user-feedback/index.mdx

Includes:
- Manual marking as spam
- Auto-spam detection

Add Spam Detection to docs.mdx

---

docs/product/performance/web-vitals/index.mdx

Adds a note to clarify web vitals samples list in page overview:

feat(performance): adds note about webvitals samples

---

docs/platforms/android/configuration/options.mdx
docs/platforms/apple/common/configuration/options.mdx
docs/platforms/dart/configuration/options.mdx
docs/platforms/dotnet/common/configuration/options.mdx
docs/platforms/elixir/configuration/options.mdx
docs/platforms/flutter/configuration/options.mdx
docs/platforms/java/common/configuration/options.mdx
docs/platforms/javascript/common/configuration/options.mdx
docs/platforms/kotlin-multiplatform/configuration/options.mdx
docs/platforms/native/common/configuration/options.mdx
docs/platforms/php/common/configuration/options.mdx
docs/platforms/powershell/configuration/options.mdx
docs/platforms/python/configuration/options.mdx
docs/platforms/react-native/configuration/options.mdx
docs/platforms/rust/common/configuration/options.mdx
docs/platforms/unity/configuration/options.mdx
docs/platforms/unreal/configuration/options.mdx

I was doing some copy+paste and got some copywriting feedback here: https://github.com/getsentry/sentry/pull/71924#discussion_r1624912295
So I thought I could also update the source.

docs: Tweak `sample_rate` copy

---

platform-includes/getting-started-config/java.mdx
platform-includes/getting-started-config/java.spring-boot.mdx
platform-includes/getting-started-install/java.mdx
platform-includes/getting-started-install/java.spring-boot.mdx

Didn't allow me to toggle locally, now trying to deploy here and check this way. …

Toggle performance for Java SDK

---

docs/platforms/android/integrations/jetpack-compose/index.mdx
docs/platforms/android/performance/instrumentation/automatic-instrumentation.mdx

Changed the docs from mentioning `Modifier.testTag` to `Modifier.sentryTag`.
I'm not sure why the `testTag` thing is there, if this was changed to your own tag or what.. 
I just found out that you actually use a custom `sentryTag` and not the `testTag`.
See https://github.com/getsentry/sentry-android-gradle-plugin/blob/1c15d184114b41058f3c0803c8675b79073f0d0a/sentry-kotlin-compiler-plugin/src/main/kotlin/io/sentry/compose/JetpackComposeTracingIrExtension.kt#L92
*Make sure you've checked the …

Adding `sentryTag` in compose docs

---

docs/platforms/javascript/common/index.mdx
docs/platforms/javascript/common/performance/index.mdx
docs/platforms/javascript/guides/aws-lambda/index.mdx
docs/platforms/javascript/guides/azure-functions/index.mdx
docs/platforms/javascript/guides/bun/config.yml
docs/platforms/javascript/guides/electron/index.mdx
docs/platforms/javascript/guides/gatsby/index.mdx
docs/platforms/javascript/guides/gcp-functions/index.mdx
platform-includes/getting-started-config/javascript.angular.mdx
platform-includes/getting-started-config/javascript.aws-lambda.mdx
platform-includes/getting-started-config/javascript.azure-functions.mdx
platform-includes/getting-started-config/javascript.bun.mdx
platform-includes/getting-started-config/javascript.capacitor.mdx
platform-includes/getting-started-config/javascript.deno.mdx
platform-includes/getting-started-config/javascript.electron.mdx
platform-includes/getting-started-config/javascript.ember.mdx
platform-includes/getting-started-config/javascript.gcp-functions.mdx
platform-includes/getting-started-config/javascript.react.mdx
platform-includes/getting-started-config/javascript.solid.mdx
platform-includes/getting-started-config/javascript.svelte.mdx
platform-includes/getting-started-config/javascript.vue.mdx
platform-includes/getting-started-install/javascript.aws-lambda.mdx
platform-includes/getting-started-install/javascript.gcp-functions.mdx
platform-includes/getting-started-install/javascript.solid.mdx
platform-includes/getting-started-node/javascript.mdx
src/components/platformCategorySection.tsx

Except for base browser JS, which still uses the loader-based onboarding for now.
This changes quite a few things, but hopefully for the better!
I did not touch cordova, but this should be fine for now...
Meta SDKs are also not touched by this because they use the wizard.
Two other changes that were necessary to make this work:
1. I added `notSupported` to `<PlatformCategorySection>`, in order to properly be able to skip meta frameworks
2. I updated bun to count as "server" SDK, not both server + browser

feat(js): Add new onboarding for all JavaScript guides

---

docs/platforms/javascript/common/distributed-tracing/index.mdx
platform-includes/distributed-tracing/how-to-use/javascript.astro.mdx
platform-includes/distributed-tracing/how-to-use/javascript.mdx
platform-includes/distributed-tracing/how-to-use/javascript.nextjs.mdx
platform-includes/distributed-tracing/how-to-use/javascript.node.mdx
platform-includes/distributed-tracing/how-to-use/javascript.remix.mdx
platform-includes/distributed-tracing/how-to-use/javascript.sveltekit.mdx

This adds a new section in JS distributed tracing docs on how to disable distributed tracing.
This came up a few times now, esp. in relation to people using OTEL on the backend, where they may not want to propagate traces from a frontend (for whatever reason).

feat(js): Add docs on how to disable distributed tracing

---

docs/product/session-replay/replay-details.mdx

Add docs describing replays support for inbound-filters.
Ref: https://github.com/getsentry/sentry/issues/44700

Add inbound-filter docs for replay

---

docs/platforms/apple/common/configuration/options.mdx

Add docs for the new enableSigterm options available on Sentry Cocoa 8.27.0 and above.

feat(apple): Add docs for enableSigterm

---

docs/product/issues/issue-priority/index.mdx

Issue priority will be GA soon, so we no longer need this banner.

feat(issue-priority): Remove EA banner from page on issue priority

---

docs/platforms/javascript/common/install/late-initializtion.mdx

Just stumpled across this typo

fix: Fix typo in Node SDK late init

---

docs/api/guides/index.mdx

This PR Removed "API Guides" from the sidebar. Currently the section lives between other endpoint documentation, which is out of place.
The docs are already linked under the main API Reference page:
so it is safe to remove them from the sidebar.
How it looks now:

feat(api): Remove "API Guides" from Sidebar

---

docs/platforms/javascript/common/configuration/tree-shaking.mdx

This adds docs on tree-shaking in Node.
You can also bundle your node app (if you want), so the debug & tracing flags can be documented the same way.
Additionally, I also added docs for node specifically on how to initialize without default integrations, for bundle size optimization. This will also tree-shake all the OTEL stuff away, for folks who don't want this.

feat(node): Add docs for tree shaking in Node

---

docs/platforms/javascript/common/performance/instrumentation/custom-instrumentation/caches-module.mdx

Reviewing JS Cache Instrumentation docs and adding code snippet for Redis.
closes https://github.com/getsentry/sentry-javascript/issues/12365

feat(js-caches): Add Instrumentation with Redis Clients

---

docs/platforms/python/integrations/celery/crons.mdx

Related to: https://github.com/getsentry/sentry-python/issues/3131
We currently don't support all celery schedules, so add a note here that schedules defined in celery config have to be parseable via traditional crontab syntax

fix(crons): Add note that certain celery schedules are not supported

---

docs/platforms/python/integrations/fastapi/index.mdx
docs/platforms/python/integrations/starlette/index.mdx

Adding a new option to the Starlette and FastAPI integrations to configure the status code to create events on in https://github.com/getsentry/sentry-python/pull/3008.
Direct links to preview:
- FastAPI: https://sentry-docs-git-ivana-python-failed-request-status-codes.sentry.dev/platforms/python/integrations/fastapi/
- Starlette: https://sentry-docs-git-ivana-python-failed-request-status-codes.sentry.dev/platforms/python/integrations/starlette/
*Make sure you've checked the following before merging …

feat(python): Add failed_request_status_codes to integrations

---

docs/concepts/key-terms/tracing/distributed-tracing.mdx

This PR adds a warning in the docs of traces to clarify how rate limiting and traces work together.
Closes: https://github.com/getsentry/team-ingest/issues/315

feat(docs): Add clarification of trace completeness with rate limiting

---

docs/platforms/javascript/common/index.mdx

Link to the docs-based migration guides, because they are more customized per SDK.

Link to migration docs instead of GitHub

---

docs/cli/releases.mdx
docs/product/releases/setup/release-automation/circleci/index.mdx
docs/product/releases/setup/release-automation/jenkins/index.mdx
docs/product/releases/setup/release-automation/travis-ci/index.mdx

Replace all mentions of the legacy `sentry-cli releases deploys ...` commands with the `sentry-cli deploys ...` commands introduced in Sentry CLI v2.0.0.
Resolves #10268

docs: Use `sentry-cli deploys` instead of legacy command

---

docs/product/metrics/index.mdx
includes/metrics-api-change.mdx

Metrics beta change disclaimer

Metrics beta change disclaimer

---

platform-includes/session-replay/setup/javascript.angular.mdx
platform-includes/session-replay/setup/javascript.astro.mdx
platform-includes/session-replay/setup/javascript.electron.mdx
platform-includes/session-replay/setup/javascript.ember.mdx
platform-includes/session-replay/setup/javascript.gatsby.mdx
platform-includes/session-replay/setup/javascript.mdx
platform-includes/session-replay/setup/javascript.nextjs.mdx
platform-includes/session-replay/setup/javascript.react.mdx
platform-includes/session-replay/setup/javascript.remix.mdx
platform-includes/session-replay/setup/javascript.svelte.mdx
platform-includes/session-replay/setup/javascript.sveltekit.mdx
platform-includes/session-replay/setup/javascript.vue.mdx

Adding snippets for setups without top level await support. Also added filename arguments to the Next.js replayIntegration docs.
ref https://github.com/getsentry/sentry-javascript/issues/12364 

docs(replayIntegration): Add snippets without top level await

---

docs/platforms/javascript/common/distributed-tracing/index.mdx
platform-includes/distributed-tracing/custom-instrumentation/javascript.mdx

See https://github.com/getsentry/sentry-javascript/pull/12138 for details.

feat(javascript): Document new `startNewTrace` API

---

docs/platforms/android/configuration/options.mdx
docs/platforms/apple/common/configuration/options.mdx
docs/platforms/dart/configuration/options.mdx
docs/platforms/flutter/configuration/options.mdx
docs/platforms/kotlin-multiplatform/configuration/options.mdx
docs/platforms/react-native/configuration/options.mdx

- Fixes options casing for all Mobile platforms
fixes https://github.com/getsentry/sentry-docs/issues/10237
- Removes outdated `tracing-origins` options (Android, KMP)
- Adds missing `trace-propagation-targets` option (RN)
- Adds whole section for Dart/Flutter

chore(Mobile): Fixes tracing options casing, updates options

---

docs/concepts/key-terms/tracing/distributed-tracing.mdx

- Updating spans section in the tracing page for some changes coming up
- Given this is user facing documentation, removing the `(optional)` text since that doesn't make sense given the public api for spans is through `sentry_sdk.start_span()`
- Linking to searchable properties (that doesn't exist yet so this PR will need to wait for that) from here if that's what the user is looking for

feat(tracing): Update spans section

---

platform-includes/performance/add-spans-example/apple.mdx
platform-includes/performance/custom-sampling-context/apple.mdx
platform-includes/performance/enable-manual-instrumentation/apple.mdx
platform-includes/performance/force-sampling-decision/apple.mdx
platform-includes/performance/retrieve-transaction/apple.mdx

I've noticed our Apple docs mention Span protocol, but that didn't work for me. Should it be `SentrySpan`?

fix(apple): Use id<SentrySpan> in performance obj-c code snippets

---

docs/product/insights/queue-monitoring/index.mdx

Updates `Queue Monitoring` text to `Queues` to match actual module name.

feat(performance): Updates module name to Queues

---

docs/concepts/search/searchable-properties/events.mdx
docs/concepts/search/searchable-properties/index.mdx
docs/concepts/search/searchable-properties/spans.mdx

Added searchable span properties to the search concepts section of the docs. Required by https://github.com/getsentry/sentry-docs/pull/10246

feat(tracing): Add searchable span properties

---

scripts/algolia.ts

adds support for skipping some files on error
set by the env var:
```
ALOGOLIA_SKIP_ON_ERROR="true"
```

add skip on error option to Algolia script

---

src/mdxOptions.js

Fixes a bug where formatting a header with `#` was causing the RSC to break. We don't need a header enumeration in the Changelog.

fix: Changlog Detail page header formatting

---

docs/platforms/javascript/common/best-practices/multiple-sentry-instances.mdx

Copy over integrations snippet from https://docs.sentry.io/platforms/javascript/best-practices/browser-extensions/ to https://docs.sentry.io/platforms/javascript/best-practices/multiple-sentry-instances/ page.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. …

Add note about integrations to multiple clients js doc

---

docs/platforms/javascript/guides/aws-lambda/index.mdx

The page for "installing Sentry as a Container Image" specifies it is now deprecated.
```
Deprecation Notice
The Node.js AWS Lambda Container Image is deprecated. Instead, please either use the Sentry AWS Lambda Layer or use the Sentry AWS Lambda SDK directly.
```
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from …

Remove reference to deprecated "Sentry as a Container Image"

---

docs/product/explore/traces/index.mdx

Trace Explorer is no longer at `/performance/traces/` and it's now `/traces/`. …

fix(docs): Broken trace explorer redirect link

---

docs/platforms/javascript/common/enriching-events/scopes/index.mdx

Added some clarifications on the current and isolation scope.

docs(scope): Add small clarifications on current scope

---

docs/platforms/javascript/common/session-replay/troubleshooting.mdx

Closes https://github.com/getsentry/sentry/issues/70028

feat(replay): Add notes about `captureConsoleIntegration` causing replays to record

---

docs/product/alerts/notifications/index.mdx
docs/product/alerts/notifications/notification-settings.mdx

Prepare and update documentation in anticipation of the spend notifications feature rollout.

feat(billing): Update spend notifications documentation

---

platform-includes/metrics/configure/javascript.remix.mdx

**Before:**
**After:**
**Disclaimer:**
I'm updating this because I found it confusing while looking at the tabs. After noticing a helpful comment in the code, I've decided to improve the visibility of the tab names.

ref(remix-metric): Update tabs naming

---

docs/pricing/quotas/index.mdx
docs/pricing/quotas/spend-allocation.mdx
docs/pricing/quotas/spike-protection.mdx
src/components/dynamicNav.tsx
src/components/sidebar/index.tsx
src/types/frontmatter.ts
src/utils.ts

Adds the `sidebar_hidden` attribute to the frontmatter for hiding pages from the sidebar + remove references to spend allocations
Closes https://getsentry.atlassian.net/browse/RV-1723 …

feat: enable hiding pages in sidebar + pricing docs updates

---

docs/platforms/javascript/common/configuration/integrations/trpc.mdx
platform-includes/configuration/integrations/javascript.astro.mdx
platform-includes/configuration/integrations/javascript.aws-lambda.mdx
platform-includes/configuration/integrations/javascript.bun.mdx
platform-includes/configuration/integrations/javascript.deno.mdx
platform-includes/configuration/integrations/javascript.gcp-functions.mdx
platform-includes/configuration/integrations/javascript.nextjs.mdx
platform-includes/configuration/integrations/javascript.node.mdx
platform-includes/configuration/integrations/javascript.remix.mdx
platform-includes/configuration/integrations/javascript.sveltekit.mdx

Adds back docs for the tRPC integration that got lost somewhere during v8.
Fixes https://github.com/getsentry/sentry-docs/issues/10372#issuecomment-2172501157

Add back tRPC middleware/integration

---

docs/platforms/react-native/manual-setup/metro.mdx

This PR adds `metro.config.js` file name to the code snippets. This helps users to identify where should they modify their Metro configuration.

fix(metro): add missing config file names

---

docs/product/issues/issue-details/index.mdx

Original copy retrieved from [here](https://github.com/getsentry/sentry-docs/pull/10042/files#diff-051c4d59160f658294ad60b91e188f36142e24b8f9b1dc77436b547cb47a67a2L49-L55).

feat(trace_navigator): Update documentation

---

docs/platforms/javascript/guides/nextjs/manual-setup.mdx

Updates the Next.js snippet to not use type casting anymore
related to https://github.com/getsentry/sentry-wizard/pull/592

docs(nextjs): Update Next.js GlobalError prop type

---

app/globals.css
src/components/docPage/type.scss

- Adds a background to inline code blocks in headings
- Adds style guide colors
- Prevent line wrapping of inline code blocks in headings
- Reduce font weight to be in line with style guide
Fixes https://github.com/getsentry/sentry-docs/issues/10426
Before:
After:

Add background to inline code blocks in headings

---

docs/product/insights/web-vitals/index.mdx
docs/product/insights/web-vitals/web-vitals-concepts.mdx

- Removes the FID deprecation note, since it's been over 90 days and no longer needed
- Updates the web vitals intro to clarify that webvitals data come from real user traffic

feat(performance): removes fid note and update webvitals intro to clarify field data

---

docs/platforms/javascript/guides/remix/manual-setup.mdx

Documents the changes in https://github.com/getsentry/sentry-javascript/pull/12110

feat(remix): Add OTEL auto-instrumentation instructions.

---

platform-includes/migration/javascript-v8/important-changes/javascript.gatsby.mdx
platform-includes/migration/javascript-v8/important-changes/javascript.react.mdx

Add errorboundary changes to v8 migration guide for react and gatsby docs, based on feedback from https://github.com/getsentry/sentry-javascript/discussions/12571 …

feat: Add errorboundary changes to v8 migration guide

---

docs/platforms/javascript/common/configuration/integrations/rewriteframes.mdx

This PR fixes the old ClassName integration in the examples table.

fix(js): Use rewriteframes integration function name in the examples

---

docs/platforms/apple/common/configuration/filtering.mdx
docs/platforms/javascript/common/configuration/filtering.mdx
platform-includes/configuration/before-send-span/apple.mdx

Add docs for beforeSendSpan similar to JS.
Cocoa PR https://github.com/getsentry/sentry-cocoa/pull/4095. We have to wait until we release Cocoa 8.30.0 to merge this.

feat(apple): Add docs for beforeSendSpan

---

platform-includes/distributed-tracing/custom-instrumentation/ruby.mdx

merge after https://github.com/getsentry/sentry-ruby/pull/2314 is released

fix(ruby): Use new meta helper in rails view

---

docs/platforms/apple/common/configuration/app-hangs.mdx

Add docs for resuming and pausing app hangs.
We can only merge this after releasing Cocoa 8.30.0. Related Cocoa PR https://github.com/getsentry/sentry-cocoa/pull/4077.

feat(apple): Docs for resume and pause AppHangs

---

docs/platforms/flutter/configuration/draining.mdx
docs/platforms/flutter/configuration/rewriteframes.mdx

Add flutter documentation on how to rewrite stack frames using `beforeSend` hook. This is needed if users need to set `url_prefix` for Flutter web applications.
Relates to https://github.com/getsentry/sentry-dart/issues/2111

docs(flutter): Add  `Rewrite Frames` documentation

---

docs/platforms/javascript/common/tracing/instrumentation/automatic-instrumentation.mdx

Make it clear that `enableInp` is set to true on `8.x` of the JS SDKs  …

fix: Add note about `enableInp` behaviour in v8/v7

---

platform-includes/performance/automatic-instrumentation-custom-routing/javascript.mdx
platform-includes/performance/opentelemetry-setup/javascript.node.mdx

Simplify code snippets for client generation in js.
[#12495](https://github.com/getsentry/sentry-javascript/issues/12495)
Note: we need to wait until https://github.com/getsentry/sentry-javascript/pull/12585 is released until we merge this. …

docs(js): use client from init method in js snippets

---

package.json
src/mdx.ts
vercel.json
yarn.lock

Reverts getsentry/sentry-docs#10497
Platform redirects were broken https://docs.sentry.io/platform-redirect/?next=%2Ftracing%2F. We instant rollbacked on vercel.

Revert "deps: Bump next and related dependencies"

---

docs/organization/integrations/integration-platform/webhooks/errors.mdx
docs/organization/integrations/integration-platform/webhooks/issue-alerts.mdx
docs/platforms/javascript/common/best-practices/multiple-sentry-instances.mdx
docs/platforms/javascript/common/best-practices/shared-environments.mdx

I found the old integration name in the code example. This integration name have been renamed from (https://github.com/getsentry/sentry-javascript/pull/10755).
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some …

Remove deprecated integration name in example code

---

docs/product/insights/caches/index.mdx
docs/product/insights/queue-monitoring/index.mdx

fixes  #10463
There were some links still pointing to `platforms/x/performance` instead of tracing,
and links not pointing deep enough to queue monitoring

fix queue monitoring 404s

---

docs/platforms/javascript/common/tracing/instrumentation/opentelemetry.mdx

Make sure we only have a single provider
Make the experience for https://twitter.com/tim_nolet/status/1806051221112832459 better
reflects https://github.com/getsentry/opentelemetry-js/pull/1
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: …

fix: Update OTEL js custom instructions snippet

---

docs/platforms/javascript/common/configuration/filtering.mdx
docs/platforms/javascript/common/configuration/integrations/inboundfilters.mdx
includes/platforms/configuration/options/allow-urls.mdx
includes/platforms/configuration/options/deny-urls.mdx

This PR makes the docs around `allowUrls` and `denyUrls` more precise. There is a subtle but very important difference between where an error was *created*, where it has been *thrown*, and where it has been *captured*. These option concern themselves with where an error has been *created*.

Make `allowUrls` and `denyUrls` more precise

---

docs/product/relay/options.mdx

Clarify that the default config path for Relay is relative to the current working directory.
Fixes https://github.com/getsentry/relay/issues/3763.

.relay/config.yml is a relative path

---

docs/platforms/javascript/common/best-practices/multiple-sentry-instances.mdx
docs/platforms/javascript/common/best-practices/shared-environments.mdx

One part of the docs should be in "Shared Environments" (not "Multiple Sentry Instances"). The relevant docs part is moved.

fix(javascript): Move best practices docs to shared environments

---

vercel.json

The redirect was wrong causing the sidebar item "What are Artifact Bundles" to redirect to the parent page "Troubleshooting Source Maps"

Remove wrong redirect for artifact bundles

---

docs/platforms/javascript/common/configuration/tree-shaking.mdx

This was brought up by a customer, they configured both the bundler plugins _and_ the manual tree shaking, and were confused that there was no difference.

fix(js): Clarify tree shaking docs

---

docs/product/insights/web-vitals/index.mdx

Add note to clarify difference in webvital thresholds between google and sentry
https://github.com/getsentry/sentry-docs/issues/9754

feat(insights): add note to clarify difference in webvital thresholds between google and sentry

---

docs/product/insights/mobile-vitals/screen-loads.mdx

Adds links for Android and iOS instructions for instrumenting TTFD. Flutter and RN do a good job at linking out to their pages, but snippets for iOS and Android are harder to discover.

docs(screen-loads): Link out to TTID/TTFD for native SDKs

---

docs/platforms/javascript/guides/remix/manual-setup.mdx

Updates the code snippet for setting up the server error handler in Remix
related issue: https://github.com/getsentry/sentry-javascript/issues/12785

fix(remix): Code example for `handleError`

---

docs/organization/data-storage-location/index.mdx
docs/platforms/javascript/common/user-feedback/index.mdx
docs/platforms/php/guides/laravel/other-versions/laravel8-10.mdx
docs/platforms/react-native/index.mdx
docs/pricing/quotas/index.mdx
src/middleware.ts
vercel.json

Fixes several redirects and broken links:
- https://docs.sentry.io/platforms/javascript/user-feedback/
- broken link "attachments quota" (https://docs.sentry.io/account/quotas/manage-attachments-quota/)
- https://docs.sentry.io/platforms/react-native/
- "touch event tracking" (https://docs.sentry.io/platforms/react-native/touchevents/)
- https://docs.sentry.io/platforms/php/guides/laravel/other-versions/laravel8-10/
- "Laravel Log Channel" (https://docs.sentry.io/platforms/php/guides/laravel/other-versions/laravel8-10/usage/#log-channels)
- https://docs.sentry.io/platforms/php/guides/laravel/other-versions/laravel8-10/
- "Using Sampling to Filter Transaction Events" (https://docs.sentry.io/platforms/php/guides/laravel/other-versions/laravel8-10/configuration/filtering/#using-sampling-to-fi …

fix: Update several outdated links and redirects

---

docs/platforms/python/migration/1.x-to-2.x.mdx

The before and after are not entirely equivalent in our example under "Hub cloning" in our migration guide; this PR fixes the discrepancy …

docs(python): Fix migration guide Hub cloning

---

docs/platforms/javascript/guides/nestjs/features/index.mdx
docs/platforms/javascript/guides/nestjs/features/sentry-traced-decorator.mdx

Adds a page for the recently `@SentryTraced` decorator to the nest documentation.

feat(nestjs): Add SentryTraced feature

---

docs/platforms/react-native/manual-setup/ram-bundles.mdx
docs/platforms/react-native/sourcemaps/troubleshooting/legacy-uploading-methods.mdx
docs/product/releases/setup/release-automation/circleci/index.mdx
docs/product/releases/setup/release-automation/jenkins/index.mdx
docs/product/releases/setup/release-automation/travis-ci/index.mdx
platform-includes/getting-started-config/javascript.capacitor.mdx
platform-includes/sourcemaps/legacy-troubleshooting/javascript.mdx
platform-includes/sourcemaps/legacy-uploading-methods/javascript.mdx

This change removes all references to the legacy `sentry-cli releases files upload-sourcemaps` command, and replaces then with references to `sentry-cli sourcemaps upload`, the new command.
Resolves #10270

Use `sentry-cli sourcemaps upload` instead of legacy command

---

docs/platforms/javascript/guides/nestjs/features/sentry-cron-decorator.mdx

Add documentation for the new nest `@SentryCron` decorator.
Prepared this now so it can already be reviewed but should be merged after the next SDK release.

feat(nestjs): Add SentryCron feature

---

platform-includes/migration/javascript-v8/important-changes/javascript.remix.mdx
platform-includes/migration/javascript-v8/v7-deprecation/javascript.angular.mdx
platform-includes/migration/javascript-v8/v7-deprecation/javascript.vue.mdx

Fixes https://github.com/getsentry/sentry-docs/issues/10615
This PR fixes some incorrect migration guide examples (mostly referencing a router variable that does not exist in some places). In addition, it also adds a note to the remix docs about the new remix setup, linking there at least, to indicate that something changed there.

fix(remix): Fix remix migration docs

---

docs/platforms/python/integrations/django/index.mdx

Changed 'endpoint' to 'function_name' within documentation. Found under 'how to name transactions showing in Sentry Tracing'.
Resolves a ValueError when configuring Sentry for Django: 
`ValueError: Invalid value for transaction_style: endpoint (must be in ('function_name', 'url'))` …

Update index.mdx to resolve ValueError

---

docs/contributing/pages/components.mdx
docs/platforms/javascript/common/session-replay/troubleshooting.mdx
src/components/expandable.tsx

add a `permalink` option to the `<Expandable />` component to render headers as links and show them up on the TOC.

feat: add <Expandable /> permalinks

---

platform-includes/distributed-tracing/custom-instrumentation/javascript.mdx
platform-includes/distributed-tracing/how-to-use/javascript.mdx

I noticed that the docs for trace propagation in browser where partially incorrect, and partially missing in details.
This PR:
1. Adds docs on how to continue a trace manually when using `browserTracingIntegration`
2. Adds docs about automatic trace propagation through meta tags
3. Fixes the docs for custom trace propagation without `browserTracingIntegration`

feat(js): Improve trace propagation docs for browser JS

---

package.json

fix `package.json` build scripts for sdk docs vs dev docs
should be merged before launching #10345

proper build scripts for dev docs and sdk docs

---

docs/organization/early-adopter-features/index.mdx
docs/product/issues/reprocessing/index.mdx

The "Reprocess Event" action is now available for everyone.

Remove "early adopter" mention from Reprocessing

---

includes/migration/javascript-v8/v7-deprecation/general.mdx

ref https://github.com/getsentry/sentry-docs/issues/10563
We undeprecated `setTransactionName` in https://github.com/getsentry/sentry-javascript/pull/10966 - these migration docs are wrong.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: …

feat(js): Remove setTransactionName migration from js sdk docs

---

docs/platforms/dotnet/common/tracing/index.mdx

In the specific use case decribed [here](<https://github.com/getsentry/sentry-dotnet/issues/3423#issuecomment-2202576482>) when people are using `WebApplicationBuilder` but need/want to control when the `EndpointRoutingMiddleware` is added, they need to manually call `UseSentryTracing`. 
cc: @bitsandfoxes 

Documented specific case when UseSentryTracing must be called manually

---

platform-includes/configuration/capture-console/javascript.mdx
platform-includes/configuration/contextlines/javascript.mdx
platform-includes/configuration/debug/javascript.mdx
platform-includes/configuration/dedupe/javascript.mdx
platform-includes/configuration/enable-pluggable-integrations-lazy/javascript.mdx
platform-includes/configuration/enable-pluggable-integrations/javascript.mdx
platform-includes/configuration/extra-error-data/javascript.mdx
platform-includes/configuration/http-client/javascript.mdx
platform-includes/configuration/reporting-observer/javascript.mdx
platform-includes/configuration/rewrite-frames/javascript.mdx
platform-includes/configuration/sessiontiming/javascript.mdx

Fixes https://github.com/getsentry/sentry-javascript/issues/12758
I updated the docs for using pluggable integrations with the loader to the v8 syntax, however the loader is not yet even fully out with v8 support, which leads to confusion and problems.
This PR ensures we have docs for both v7 and v8 of the loader, so this should work both ways.

fix: Add docs for v7 loader integrations

---

docs/platforms/python/migration/1.x-to-2.x.mdx

Document that Hub clones should be replaced with isolation scope forks. Depends on #10521.
Resolves #10524 …

docs(python): Document how to migrate Hub clones

---

.github/CODEOWNERS

Docs Team gets a bunch of PRs such as https://github.com/getsentry/sentry-docs/pull/10657. 
We should always approve, but for a sanity check lets make sure owners-api approve these prs.

chore(codeowners): Add owners-api to `resolveOpenAPI.ts`

---

docs/product/insights/caches/index.mdx
docs/product/insights/queue-monitoring/index.mdx

The links to the manual instrumentation on https://docs.sentry.io/product/insights/caches/#instrumentation are wrong.

Fix links to manual cache instrumentation

---

docs/platforms/javascript/common/tracing/instrumentation/custom-instrumentation/index.mdx

This adds docs for the `parentSpan` option we added somewhat recently to the SDK, which should make it easier to understand. It also adds a dedicated section to custom instrumentation docs to explain this, as it is a rather common scenario.
Ref https://github.com/getsentry/sentry-javascript/pull/12928

feat(js): Add docs for creating a child span

---

docs/pricing/quotas/spend-allocation.mdx

Spans does not have spend allocations support yet so removed this from the docs + corrected on-demand to PAYG.

fix: remove spans and on-demand from spend allocation docs

---

docs/platforms/javascript/common/migration/v7-to-v8/v8-opentelemetry.mdx

Resolves https://github.com/getsentry/sentry-docs/issues/10750 …

fix: Only show otel migration docs for node based sdks

---

docs/platforms/apple/common/profiling/index.mdx

On Apple platforms, we only [officially support Profiling for iOS and macOS](https://docs.sentry.io/product/explore/profiling/). This PR hides the Profiling page on the guides for the other platforms (tvOS, watchOS, visionOS).
Also created an issue to follow up with details on platform support, especially for hybrid (mobile) SDKs: https://github.com/getsentry/team-mobile/issues/191 …

fix(Apple): Show Apple profiling pages only on supported platforms

---

docs/platforms/apple/common/index.mdx

Manual setup link in the iOS docs is the wrong platform, should be iOS and not React Native …

fix(apple): change link from react native manual setup to ios manual setup

---

docs/concepts/migration/index.mdx
docs/organization/integrations/source-code-mgmt/azure-devops/index.mdx
docs/pricing/quotas/spike-protection.mdx
docs/product/explore/profiling/profile-details.mdx
docs/product/issues/issue-details/replay-issues/index.mdx
docs/security-legal-pii/security/ai-ml-policy.mdx

Test plan:
1. Login to an org that is not sentry.sentry.io
Example: demo.sentry.io
3. Visit the links, you should be redirected to `demo.sentry.io/**`

fix: Use /orgredirect/ instead of linking to sentry org

---

docs/platforms/python/configuration/options.mdx
docs/platforms/python/integrations/index.mdx

Bringing the Python integrations page a bit closer to [Node's](https://docs.sentry.io/platforms/javascript/guides/node/configuration/integrations/) with more examples, config options, etc.
* add examples for different integrations-related config options to the integrations page
* fix `false` -> `False` capitalization
* fix some generic wording ("In some SDKs..." -> Python specific behavior)
Follow up in another PR: expand the integrations table with what functionality each integration offers (tracing, errors, etc.)
Thanks in advance …

feat(python): Improve integrations page

---

docs/platforms/python/migration/1.x-to-2.x.mdx

Add documentation to inform users that custom `Hub` usage (i.e. `with my_hub` statements) should be replaced with the `sentry_sdk.use_isolation_scope` context manager. Depends on #10506.
Resolves #10499 …

docs(python): Document how to migrate custom `Hub` usage

---

docs/platforms/apple/guides/macos/features/index.mdx
platform-includes/capture-error/apple.mdx

Add info on how to use `NSApplicationCrashOnExceptions` flag to enable handling of uncaught exceptions.
fixes https://github.com/getsentry/sentry-docs/issues/9313

feat(macos): Add NSApplicationCrashOnExceptions to usage

---

platform-includes/getting-started-primer/java.spring-boot.mdx

Fix URL to Spring Boot git integration

---

docs/platforms/javascript/common/migration/v7-to-v8/v8-new-performance-api.mdx

Our migration guide didn't mention the removal of `sampled: boolean` at all previously. This PR adds an entry how to migrate forcing a sampling decision. 
Since we already mention `tracesSampler` in the docs and how to return a definitely positive sampling decision from it, I think we don't need an extra "Forcing Sampling Decision" guide in the regular docs.

fix(javascript): Add entry to migration guide about forcing a sampling decision

---

develop-docs/sdk/event-payloads/contexts.mdx

Fix a link in the os-context documentation that points to the Native SDK repo. The old link pointed to the `master`, but the respective [feature-branch](https://github.com/getsentry/sentry-native/pull/963) wasn't merged due to a change in plans :-)
Let's link to the branch until the feature is adapted across all repos (given that the contents linked to will not change).
cc: @stephanie-anderson, @kahest

fix: 404 links in develop-docs

---

docs/platforms/javascript/common/configuration/integrations/http.mdx

This PR adds documentation for the new `request` parameter passed as a second argument to the `ignoreOutgoingRequests` and `ignoreIncomingRequests` callbacks.
ref https://github.com/getsentry/sentry-javascript/issues/12913

feat(node): Add documentation for `request` param in `httpIntegration` callbacks

---

docs/platforms/javascript/common/sourcemaps/uploading/angular-nx.mdx

docs: improve Nx CLI docs

---

docs/platforms/javascript/common/install/esm.mdx

Fixes https://github.com/getsentry/sentry-docs/issues/10802
For now I only added `exclude` docs there, I guess that is the most important one!
Need to also add this to late initialization, once the next release is out.

feat(node): Add docs for skipping instrumentation

---

.github/workflows/cleanup-preview-deployments.yml
scripts/preview-deployment-cleanup.ts

- Adds a script to cleanup stale preview deployments (mainly ported from #6592)
- Adds a gh workflow that calls this script every day for user docs and developer docs
closes #10695

feat: Automatic preview cleanups

---

develop-docs/self-hosted/index.mdx

This PR is a duplicate of https://github.com/getsentry/develop/pull/1336. We did not realize develop docs moved to sentry-docs

Docs for errors only self hosted

---

docs/platforms/python/configuration/options.mdx
docs/platforms/python/integrations/index.mdx

With https://github.com/getsentry/sentry-python/issues/3166 we're adding a new config option to the Python SDK. Most of our integrations are now auto-enabled, making it harder to opt out of single integrations. `disabled_integrations` solves this issue.
Preview:
- basic options page https://sentry-docs-git-ivana-pythondisabled-integrations.sentry.dev/platforms/python/configuration/options/#integration-configuration
- integrations page https://sentry-docs-git-ivana-pythondisabled-integrations.sentry.dev/platforms/python/integrations/#disabling-integrations

feat(python): Add disabled_integrations config option

---

src/remark-format-code.js

Skip codesnippets that use a `@inject` value from formatting as they lead to unintended linebreaks
fixes [#10765](https://github.com/getsentry/sentry-docs/issues/10765)

fix: Exclude code snippets with injects from formatting

---

platform-includes/enriching-events/import/javascript.node.mdx

We use this snippet in a bunch of places where we once tell users how they import their SDK on top of the page and all other snippets on the page are import-less. It came up in internal feedback about users being confused why this only shows import (ESM) syntax when most of our highler level guides have both options and default to CJS. So this PR adds a CJS version and defaults to it instead of ESM.

ref(node): Show CJS and ESM import versions in dedicated SDK import code snippet

---

docs/platforms/javascript/common/tracing/instrumentation/opentelemetry.mdx

Adds a section on how to implement a custom otel sampler.
relates to [#12494](https://github.com/getsentry/sentry-javascript/issues/12494)

docs: add section for custom otel sampler

---

docs/platforms/javascript/guides/nextjs/manual-setup.mdx

This PR proposes a small typo fix in the Next.js documentation. 

docs(nextjs): fix typo in manual-setup.mdx

---

docs/platforms/javascript/guides/react/features/react-router.mdx

While creating a small react router test app, I tried to apply our RR6 routing instrumentation and ran into every possible pitfall along the way. First, I imported the hooks from the wrong packages, then I missed that I need to apply `wrapCreateBrowserRouter` and ultimately (not my proudest moment lol) missed calling `sentryCreateBrowserRouter`.
Because IMO it's really easy to fall into at least one of these problems, I thought, our code snippet highlighting feature would work well here because the setup is (compared to other routing instrumentations) quite involved. So this PR adds some highlighting to the various RR version code snippets and slightly streamlines wording.
Example:
Note: All snippet highlights assume that `Sentry.init` was already set up beforehand which I think is a fair …

ref(react): Improve React Router instrumentation docs

---

docs/platforms/dotnet/guides/aspnet/tracing/included-instrumentation.mdx
docs/platforms/dotnet/guides/blazor-webassembly/index.mdx
platform-includes/configuration/config-intro/dotnet.mdx
platform-includes/getting-started-config/dotnet.aspnet.mdx
platform-includes/getting-started-config/dotnet.mdx

The .NET SDK has deprecated `EnableTracing` from the options in favor of relying on `TracesSampleRate` [here](https://github.com/getsentry/sentry-dotnet/pull/3381).

fix(.NET): Removed deprecated `EnableTracing`

---

docs/platforms/dotnet/common/configuration/options.mdx

Since it was missing. And it's common.

fix(.NET): Added `BeforeSendTransaction` to common options

---

docs/platforms/javascript/common/tracing/instrumentation/automatic-instrumentation.mdx

Adds the `enableLongAnimationFrame` option to the js docs.

feat(js): add enableLongAnimationFrame to javascript docs

---

develop-docs/application/feature-flags/flagpole.mdx

Because all flags are Flagpole only features and we don't have to add them to `flagpole.flagpole_only_features`, we should delete this from the docs.

chore(flagpole): Remove Instructions to add flag to `flagpole.flagpole_only_features`

---

docs/platforms/flutter/features/index.mdx
docs/platforms/flutter/profiling/index.mdx

Resolves https://github.com/getsentry/sentry-dart/issues/2197

Clarify Profiling support on Flutter

---

package.json

We're doing this so that we can gradually migrate away from calling `rm -r app/changelog` in vercel.

build: Add build command for dev docs on vercel

---

apps/changelog/next.config.mjs
apps/changelog/package.json
apps/changelog/sentry.client.config.ts
apps/changelog/sentry.edge.config.ts
apps/changelog/sentry.server.config.ts
yarn.lock

Adds back spotlight to the changelog.

feat(changelog): Add back spotlight

---

package.json
src/mdx.ts
src/rehype-slug.js

Fix section headings with PlatformIdentifier 

---

docs/platforms/javascript/common/configuration/integrations/prisma.mdx

Looking at
the snippet should be highlighting `previewFeatures = ["tracing"]` instead of `provider`. …

fix: Change highlighted section in prisma snippet

---

docs/organization/integrations/notification-incidents/slack/index.mdx

While going through the sentry slack docs, noticed that `@<USER_ID>` should actually be `<@USER_ID>`.

fix: Update Slack Sentry Docs

---

develop-docs/application/feedback-architecture.mdx

Update after verifying https://github.com/getsentry/self-hosted/pull/3193 works. Even after that's merged, this helps people who are on outdated branches

chore(feedback): Update info on self hosted flags and support

---

includes/sentry-cli-sourcemaps.mdx

I found a user on discord who was setting `dist` and `release` which was not good for them and is not a good idea in 95% of the cases so I wanted to move it down a bit so that user's are less likely to do so. Also add a note to only do this when being really sure about it.

Make sourcemaps upload less misleading with regards to dist and release

---

docs/product/stats/index.mdx

We're updating how rate limit reasons are shown in the UI. Please check the [PR](https://github.com/getsentry/sentry/pull/75414) for details. This PR also updates the documentation to match the new changes.

ref(stats): Update rate limited reasons

---

docs/pricing/quotas/legacy-manage-transaction-quota.mdx

For customers still on pre-AM3 plans, we still link to legacy documentation from the Sentry SaaS web app, and we want these pages to not bork leaving these customers hanging.
Here, I am reviving the legacy docs on managing performance units quota. But this page will be hidden and not linked from anywhere else in the docs website.
Associated pull request to link to this page is in https://github.com/getsentry/sentry/pull/75477

chore(billing): Revive legacy docs on managing performance units quota

---

develop-docs/development/testing.mdx

Added a section about temporary models which can be used when developer needs to test a behaviour of a feature that is not tied to a specific model (e.g. custom lookup, or custom field).
I have struggled with this, and I wish I had a docs where I could have looked this up, when I needed it.

docs(development/testing) Docs about temporary test models

---

docs/platforms/dotnet/common/configuration/msbuild.mdx

Resolves https://github.com/getsentry/sentry-dotnet/issues/3500
CC: @bitsandfoxes 

Added docs on SentryCreateRelease and SentrySetCommits

---

docs/platforms/dotnet/guides/wpf/index.mdx
docs/platforms/dotnet/index.mdx
platform-includes/getting-started-primer/dotnet.mdx

This got bumped to from `4.6.1` to `4.6.2`

fix(.NET): Updated supported framework version

---

develop-docs/sdk/hub_and_scope_refactoring.mdx
docs/platforms/python/migration/1.x-to-2.x.mdx
platform-includes/enriching-events/scopes/configure-scope/python.mdx

In https://github.com/getsentry/sentry-python/pull/3357, we'll be adding new top-level API to interact with scopes, so that:
- `sentry_sdk.Scope.get_current_scope()` becomes `sentry_sdk.get_current_scope()`
- `sentry_sdk.Scope.get_isolation_scope()` becomes `sentry_sdk.get_isolation_scope()`
- `sentry_sdk.Scope.get_global_scope()` becomes `sentry_sdk.get_global_scope()`

feat(python): Use new scope API

---

.gitignore
package.json
scripts/algolia.ts
src/components/docPage/index.tsx
yarn.lock

- Applies custom search settings from `sentry-global-search`
- Tags algolia records with their respective sdk and framework names for improving path bias (when searching from react guide, results will prioritise records within the guide)
- Updates search settings for algolia client to include framework name for improving search results
relates to [#10592](https://github.com/getsentry/sentry-docs/issues/10592)

feat: Improve algolia search results

---

docs/platforms/python/tracing/instrumentation/custom-instrumentation/caches-module.mdx

Small documentation fix for the python instrumentation of the custom cache solution, the if else statement had a typo …

typo: correct the if else in the get example

---

src/components/codeBlock/code-blocks.module.scss

fixes [#10510](https://github.com/getsentry/sentry-docs/issues/10510)

fix: Add padding to diff code blocks

---

docs/platforms/apple/common/integrations/default.mdx

Change SentryOutOfMemoryTrackingIntegration to
SentryWatchdogTerminationTrackingIntegration as it was renamed over one year ago.

fix(apple): Fix default integration name

---

.github/workflows/algolia-index.yml
.github/workflows/lint-404s.yml
.github/workflows/sync-labels.yml
.github/workflows/test.yml

setup-volta is now deprecated as setup-node supports what it can do with 1 less layer of indirection + it is an upstream action

ci: replace setup-volta

---

includes/only-error-issues-note.mdx

Change that reprocessed issues feature is only available for issues with debug information files, excluding source maps

chore(reprocessed-events): Change wording to clarify applicability

---

docs/platforms/javascript/common/best-practices/index.mdx
docs/platforms/javascript/common/configuration/index.mdx
docs/platforms/javascript/common/data-management/index.mdx
docs/platforms/javascript/common/enriching-events/index.mdx
docs/platforms/javascript/common/sourcemaps/index.mdx
docs/platforms/javascript/common/usage/index.mdx

Updating the order of the sidenav and changing the name of some of the folders, per our conversations with DevRel team :)

Update sidenav order for JS

---

docs/cli/send-event.mdx

Link to the [Event Payloads](https://develop.sentry.dev/sdk/event-payloads/) page from the `send-event` command page, so that users know what format their event should follow.
Closes https://github.com/getsentry/sentry-docs/issues/9538
Not urgent
- Skipping, because this is a very simple change

docs(cli): Document `send-event` format

---

docs/platforms/javascript/common/session-replay/understanding-sessions.mdx

relates to [#12810](https://github.com/getsentry/sentry-javascript/issues/12810)

docs(replay): Update docs on public replay api methods

---

apps/changelog/package.json
yarn.lock

`yarn migrate:dev` fails because `dotenv` is not available, `dotenv-cli` as a dev dependency makes it work.

fix(changelog): Add dotenv-cli as dev dependency

---

docs/platforms/apple/common/troubleshooting/index.mdx

Add a troubleshooting entry for missing mach info that was fixed in 8.33.0

feat: Apple troubleshooting for missing mach info

---

docs/platforms/apple/guides/ios/session-replay/index.mdx

Renamed Apple `errorSampleRate` option to `onErrorSampleRate` in order to keep consistency with other SDKs.
This should wait for https://github.com/getsentry/sentry-cocoa/pull/4218

Renamed Apple errorSampleRate option to onErrorSampleRate

---

docs/platforms/javascript/guides/sveltekit/manual-setup.mdx

This PR adds documentation for the new `wrapServerRouteWithSentry` function we added in https://github.com/getsentry/sentry-javascript/pull/13247. While adding this, I slightly restructured the Manual Setup page of the SvelteKit guide to now have "Automatic Instrumentation" and "Manual Instrumentation" headings on the same level. 

feat(sveltekit): Document new `wrapServerRouteWithSentry` wrapper

---

docs/platforms/javascript/guides/sveltekit/manual-setup.mdx
platform-includes/sourcemaps/primer/javascript.sveltekit.mdx

builds on top of #10990
This PR adds a couple of improvements to the manual setup page of our SvelteKit guide:
- streamlined code snippets so that there's only one snippet per file users need to change. Since we can now highlight parts in snippets, I think it's easier for users to identify what they need to change in a file on one glance instead of piecing together two or three snippets.
- Removed TS and JS tabs in the snippets because there's no TS-specific syntax in them.
- Restructured H2 document structure so that not all optional configuration sections are part of "Configuration". This should help users identify what they have to do vs. what's optional and probably not necessary to read.
*Make sure …

ref(sveltekit): Improve manual setup code snippets and structure

---

apps/changelog/src/app/changelog/[slug]/loading.tsx
apps/changelog/src/app/changelog/[slug]/page.tsx
apps/changelog/src/app/changelog/loading.tsx
apps/changelog/src/app/changelog/page.tsx
apps/changelog/src/client/components/article.tsx
apps/changelog/src/client/components/list.tsx

We had nested a tags in the previews. This PR strips them out and thus fixes the resulting hydration error.

fix(changelog): Fix hydration errors because of nested `<a>` tags

---

next.config.js
package.json

I have the theory that the .git folder is sometimes included in our lambdas, causing the vercel build to fail because the lambdas are too large.

fix: Fix too large build output

---

docs/platforms/javascript/common/configuration/integrations/vue.mdx
platform-includes/getting-started-config/javascript.vue.mdx

closes https://github.com/getsentry/sentry-docs/issues/10415

docs(vue): Manually set up `vueIntegration`

---

platform-includes/performance/connect-errors-spans/apple.mdx
platform-includes/performance/custom-sampling-context/apple.mdx
platform-includes/performance/traces-sample-rate/apple.mdx
platform-includes/performance/traces-sampler-as-sampler/apple.mdx

As we move away from Objective-C and create more features in Swift, these new features will only be available for use in other Objective-C projects if the developer imports the Sentry module instead of the umbrella header.
So I changed the Objective-c code snippets to reflect this.

chore(Apple): Update docs to use @import Sentry;

---

platform-includes/getting-started-config/javascript.nuxt.mdx

Better explanation for script setup and import variable.
ref: https://github.com/getsentry/sentry-javascript/issues/13304

docs(nuxt): Describe run script more precisely

---

docs/platforms/javascript/common/configuration/filtering.mdx

Adds a note to the `thirdPartyErrorFilterIntegration` docs that explains why it is not supported in conjunction with the loader and CDN bundles.
Resolves https://github.com/getsentry/sentry-javascript/issues/13297

Note that `thirdPartyErrorFilterIntegration` is not supported with Loader or CDN bundles

---

docs/platforms/python/configuration/options.mdx

goes with https://github.com/getsentry/sentry-python/pull/3438
to be merged when that feature is released

feat(python): Add custom_repr docs

---

docs/platforms/apple/common/configuration/swizzling.mdx
docs/platforms/apple/common/tracing/instrumentation/automatic-instrumentation.mdx

Add docs for the existing option swizzleClassNameExcludes.

feat(apple): Add docs for swizzleClassNameExcludes

---

docs/platforms/flutter/integrations/routing-instrumentation.mdx

Add ignoreRoutes for SentryNavigatorObserver in sentry-dart
[2218](https://github.com/getsentry/sentry-dart/pull/2218)

add ignoreRoutes for SentryNavigatorObserver in sentry-dart

---

platform-includes/distributed-tracing/custom-instrumentation/javascript.mdx

To be merged after https://github.com/getsentry/sentry-javascript/pull/13201 is released.
This PR adds documentation for 
- `getTraceData` introduced in https://github.com/getsentry/sentry-javascript/pull/13134
- `getTraceMetaTags` introduced in https://github.com/getsentry/sentry-javascript/pull/13201
which both give users the ability to propagate backend -> frontend traces via `<meta>` Html tags.
closes https://github.com/getsentry/sentry-docs/issues/7671

feat(javascript): Add documentation for injecting Html `<meta>` tags

---

src/components/codeContext.tsx
src/components/codeTabs.tsx
src/components/docImage.tsx
src/utils.ts

fixes [#11070](https://github.com/getsentry/sentry-docs/issues/11070)

fix: Get rid of remaining hydration errors

---

docs/platforms/javascript/common/best-practices/multiple-sentry-instances.mdx

There is no hub anymore in JS, only clients.

fix(js): Delete hub occurrences

---

docs/product/alerts/uptime-monitoring/troubleshooting.mdx

Updates uptime's user-agent to match our system:
https://github.com/getsentry/sentry/blob/74cc8f6a555922c491534ebc8f11cc82be726780/src/sentry/uptime/detectors/tasks.py#L37

Fix incorrect user-agent value for uptime

---

src/components/header.tsx

Added the additional "Get Started" button from the [welcome page](https://sentry.io/welcome/ page). The color looks correct on hover, however I could not find a way for the transition styles to take effect. Please let me know if there is anything to touch up.

Added get started button to docs header with initial styling

---

develop-docs/application/feature-flags/flagpole.mdx
develop-docs/application/feature-flags/index.mdx
develop-docs/development/analytics.mdx
develop-docs/development/database-migrations/index.mdx
develop-docs/development/workflow.mdx
develop-docs/sdk/envelopes.mdx
develop-docs/sdk/event-payloads/contexts.mdx
develop-docs/sdk/event-payloads/replay-recording.mdx
develop-docs/sdk/replays.mdx
develop-docs/sdk/telemetry/traces/modules/requests.mdx
develop-docs/self-hosted/index.mdx
develop-docs/self-hosted/releases.mdx

Port the latest commits to the develop docs repo
Cutoff point:
```
Author: joshuarli <joshuarli98@gmail.com>
Date:   Wed Aug 14 10:46:08 2024 -0700
self-hosted: update upgrade path (#1345)
```

Sync dev docs

---

src/components/header.tsx
tailwind.config.js

Essentially extended a custom screen size in the tailwind.config.js, then added style to the new header link.

Added custom screen size to account for header links

---

app/[[...path]]/page.tsx
src/utils.ts

Fixes confusing search result titles for all apple platforms. e.g. "iOS" was displayed as "Ios" etc.

fix: Format apple platform names in metadata

---

develop-docs/self-hosted/releases.mdx

- add `24.8.0` as a pre-squash hard stop (for commits similar to: https://github.com/getsentry/sentry/pull/76507 )
- change hard stops to a list so they don't need a scroll back
- add an example upgrade

adjust self-hosted hard stop documentation

---

docs/platforms/javascript/common/configuration/filtering.mdx

It seems like these docs didn't read well enough because @nikolovlazar had issues with them: https://github.com/getsentry/sentry-javascript/issues/13326
This attempts to make the transition between paragraphs a bit smooter.

Make transition smoother for thirdPartyErrorFilterIntegration paragraph

---

docs/platforms/python/integrations/aws-lambda/manual-instrumentation/index.mdx
docs/platforms/python/integrations/gcp-functions/index.mdx

The repository with the sample are has been archived because those samples are outdated (last touched 4 years ago)
Removing the links to those sample apps, because they probably lead to more confusion than they help users.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware …

[Python] Remove links to defunct sample apps

---

docs/security-legal-pii/security/ip-ranges.mdx

The highlighting defaults to _Bash_ when not defined. This causes IP addresses to have some odd coloring.
Before:
Instead, I'm explicitly setting them to `plaintext` to disable the highlighting.
After:

set highlight to plaintext

---

docs/platforms/javascript/guides/electron/config.yml
docs/platforms/javascript/guides/gatsby/config.yml

Closes #11120
Noticed Electron was wrong and then checked all the JavaScript frameworks and found Gatsby!

fix: Incorrect titles

---

develop-docs/development/environment/index.mdx

I hit a wall twice in a row here where I ran `devenv sync`, but the `sentry` command wasn't on my path until I restarted my terminal and `cd` into my Sentry project install.
After which it ran this:
```
❯ cd Projects/getsentry
direnv: loading ~/Projects/getsentry/.envrc
SUCCESS!
direnv: export +NODE_OPTIONS +PIP_DISABLE_PIP_VERSION_CHECK +PYTHONUNBUFFERED +SENTRY_DEVENV_HOME +SENTRY_DEVSERVICES_DSN +SENTRY_INSTRUMENTATION +SENTRY_UI_HOT_RELOAD +VIRTUAL_ENV +XDG_CACHE_HOME +XDG_CONFIG_DIRS +XDG_CONFIG_HOME +XDG_DATA_DIRS +XDG_DATA_HOME +XDG_RUNTIME_DIR +XDG_STATE_HOME ~PATH
```
... and everything went fine from there.

Add note about restarting terminal after devenv sync

---

docs/platforms/javascript/common/tracing/instrumentation/custom-instrumentation/index.mdx

- Reference to anchor link for `withActiveSpan` was broken

Fix broken anchor link `withActiveSpan`

---

includes/sentry-cli-sourcemaps.mdx

While reading the docs on source maps [Associating dist with Artifact Bundle](https://docs.sentry.io/platforms/javascript/sourcemaps/uploading/typescript/#associating-dist-with-artifact-bundle), I found a typo in one of the examples where the `release` property exist twice but the second time it should be `dist`.
Not urgent, can wait up to 1 week+

Fix a property name typo from `release` to `dist`

---

docs/platforms/android/configuration/shared-environments.mdx
docs/platforms/android/troubleshooting/shared-environments/index.mdx

Fixes https://github.com/getsentry/sentry-docs/issues/10910 …

chore(android): Add docs for using the Android SDK within a shared environment

---

docs/platforms/javascript/common/configuration/integrations/fs.mdx
platform-includes/configuration/integrations/javascript.astro.mdx
platform-includes/configuration/integrations/javascript.aws-lambda.mdx
platform-includes/configuration/integrations/javascript.bun.mdx
platform-includes/configuration/integrations/javascript.fastify.mdx
platform-includes/configuration/integrations/javascript.gcp-functions.mdx
platform-includes/configuration/integrations/javascript.nestjs.mdx
platform-includes/configuration/integrations/javascript.nextjs.mdx
platform-includes/configuration/integrations/javascript.node.mdx
platform-includes/configuration/integrations/javascript.nuxt.mdx
platform-includes/configuration/integrations/javascript.remix.mdx
platform-includes/configuration/integrations/javascript.sveltekit.mdx

Adds docs for the newly added `fsIntegration`

[JS SDK] Add docs for `fsIntegration`

---

docs/platforms/dart/integrations/http-integration.mdx

Based on the issue in the sentry-dart repo [1192](https://github.com/getsentry/sentry-dart/issues/1192), I added an example for using the [runWithClient](https://pub.dev/documentation/http/latest/http/runWithClient.html) function.

add 'runWithClient' example to http-integration.mdx

---

docs/platforms/python/integrations/dramatiq/index.mdx

The Dramatiq integration docs page states that the Dramatiq integration supports tracing, but it only supports errors.
This change corrects the page accordingly.
Fixes #11143
Would be good to merge sooner rather than later since this PR corrects incorrect information in our docs. There is no specific deadline, though.

docs: Remove incorrect mention of tracing on Dramatiq docs

---

docs/platforms/dotnet/common/configuration/disable-integrations.mdx

The `DisableTaskUnobservedTaskExceptionCapture` method was deprecated a few years ago[^1] in favor of `DisableUnobservedTaskExceptionCapture`, which was removed around 9 months ago[^2] for v4.
[^1]: https://github.com/getsentry/sentry-dotnet/pull/2034
[^2]: https://github.com/getsentry/sentry-dotnet/pull/2841
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional …

Fix DisableUnobservedTaskExceptionCapture method name

---

public/_platforms/python/performance-onboarding-1-install.json

Fix incorrect install snippet in python performance onboarding.
`pip install "@sentry/browser" sentry-sdk ` -> `pip install sentry-sdk`
closes https://github.com/getsentry/sentry/issues/76517

fix(python): Performance onboarding install snippet

---

develop-docs/self-hosted/index.mdx

current stuff is outdated, felt it would be best to just link to our readme since that's more updated in tandem with `install/_min-requirements.sh    `

self-hosted: minimum system requirements

---

develop-docs/self-hosted/index.mdx

In the self-hosted docs we mention the date of the workshop as if it will happen in the future, but since it has already happened, we should remove the date details.

docs(self-hosted) Remove mention of the date of the live workshop

---

docs/platforms/android/troubleshooting/index.mdx

Add troubleshooting entry warning that Sentry.init should not be used on Android, but rather SentryAndroid.init

chore(Android): Add troubleshooting entry about Sentry.init

---

docs/platforms/javascript/guides/nextjs/manual-setup.mdx

Adding more information about enabling `instrumentationHook` first. Based on this comment: https://github.com/getsentry/sentry-javascript/issues/12044#issuecomment-2301540086

feat(nextjs): Add information about enable next instrumentation

---

develop-docs/sdk/features.mdx

See https://github.com/getsentry/team-sdks/issues/100

Add `http` breadcrumb level based on response code

---

src/middleware.ts

I think this is most suitable redirect for this error
Closes [#10968](https://github.com/getsentry/sentry-docs/issues/10968)

fix python http errors 404

---

docs/platforms/javascript/common/troubleshooting/index.mdx
src/components/expandable.tsx

- use native `<details />` element
- <kbd>Ctrl</kbd><kbd>F</kbd> expands corresponding matches
- add missing `permalink` flags
Closes #11183

Improve <Expandable />

---

app/[[...path]]/page.tsx
src/utils.ts

Updates some of the platform page titles.
Closes [#11219](https://github.com/getsentry/sentry-docs/issues/11219)

fix: Use correct platform page titles

---

platform-includes/getting-started-config/javascript.solidstart.mdx
platform-includes/getting-started-sourcemaps/javascript.solidstart.mdx

Waiting on: https://github.com/getsentry/sentry-javascript/pull/13493 …

ref(solidstart): Overhaul solidstart options and sourcemap uploading

---

docs/platforms/javascript/common/session-replay/privacy.mdx

Closes https://github.com/getsentry/sentry-docs/issues/11090
Our old snippet had some typos in it. Now, the JS example should be fine.
Because the example does not work well in TS, for this case I opted to also add a TS example too.

fix: Fix replay privacy code example

---

platform-includes/enriching-events/add-attachment/python.mdx

Update attachment docs to reflect new API added in Python SDK 2.0.0, and introduce other general improvements to the page.
Depends on https://github.com/getsentry/sentry-python/pull/3342, which adds parameter documentation to the API Docs.
Fixes: #10844
Related: getsentry/sentry-python#3340

docs(python): Update attachment docs for 2.x

---

develop-docs/sdk/envelopes.mdx
develop-docs/sdk/telemetry/profiles/sample-format-v2.mdx

Add documentation for the `profile_chunk` item type referred by the _Profile Sample Format V2_ documented in this previous [PR](viglia/ref/add-profile_chunk-item-type-doc).

ref(profiling): add doc for the profile_chunk item type

---

docs/platforms/python/migration/1.x-to-2.x.mdx

[Python] Update docs for `last_event_id` in migration guide

---

platform-includes/sourcemaps/primer/javascript.cloudflare.mdx
platform-includes/sourcemaps/primer/javascript.mdx
src/components/video.tsx

Closes: #10342
Replaces the sourcemaps upload image with a video explaining how to generate and upload sourcemaps using the wizard. …

feat(docs): Add sourcemaps upload video to javascript docs

---

platform-includes/getting-started-primer/javascript.solidstart.mdx

Waiting on: https://github.com/getsentry/sentry-javascript/pull/13599
Removes the alpha warning for the SolidStart SDK as it will be in Beta with the `8.29.0` release of the SDK. …

chore(solidstart): Remove alpha warning

---

docs/platforms/javascript/guides/node/profiling/index.mdx
platform-includes/profiling/automatic-instrumentation-setup/_default.mdx
platform-includes/profiling/automatic-instrumentation-setup/javascript.angular.mdx
platform-includes/profiling/automatic-instrumentation-setup/javascript.astro.mdx
platform-includes/profiling/automatic-instrumentation-setup/javascript.electron.mdx
platform-includes/profiling/automatic-instrumentation-setup/javascript.nextjs.mdx
platform-includes/profiling/automatic-instrumentation-setup/javascript.react.mdx
platform-includes/profiling/automatic-instrumentation-setup/javascript.remix.mdx
platform-includes/profiling/automatic-instrumentation-setup/javascript.svelte.mdx
platform-includes/profiling/automatic-instrumentation-setup/javascript.sveltekit.mdx
platform-includes/profiling/automatic-instrumentation-setup/javascript.vue.mdx

This adds docs for `profilesSampler` in browser JS & Node.
Closes https://github.com/getsentry/sentry-docs/issues/10010

feat: Add docs for `profilesSampler` function in JS

---

docs/platforms/javascript/common/best-practices/multiple-sentry-instances.mdx

This PR adds a section about how to fork scopes when working with multiple clients.
Closes https://github.com/getsentry/sentry-docs/issues/11180

feat: Add docs about scope forking with multiple clients

---

docs/platforms/ruby/common/configuration/options.mdx
docs/platforms/ruby/common/integrations/index.mdx
platform-includes/enriching-events/breadcrumbs/breadcrumbs-example/ruby.mdx

feat(ruby): Document integrations - gems and patches

---

docs/platforms/python/integrations/index.mdx
docs/platforms/python/integrations/sys_exit/index.mdx

**Converted to draft pending release of the [integration](https://github.com/getsentry/sentry-python/pull/3401).** Add the version number that the integration was released in prior to merge.
Add documentation for the sys.exit integration, introduced in https://github.com/getsentry/sentry-python/pull/3401.
Closes #11043

docs(python): Document sys.exit integration

---

platform-includes/configuration/integrations/lazy-loading-replay/javascript.angular.mdx
platform-includes/session-replay/setup/javascript.angular.mdx

This PR updates the documentation how to correctly lazy-load the replay intergration in Angular apps with minimal bundle size implications. Unfortunately, Angular/Webpack don't play in our favour here so we can't use the same dynamic import snippet without initial bundle size hit penalties. More details here: https://github.com/getsentry/sentry-docs/issues/6477#issuecomment-2337877761
finally closes https://github.com/getsentry/sentry-docs/issues/6477

ref(angular): Update Replay lazy load instructions

---

docs/platforms/javascript/common/tracing/instrumentation/custom-instrumentation/index.mdx
platform-includes/performance/enable-automatic-instrumentation/javascript.angular.mdx
platform-includes/performance/enable-automatic-instrumentation/javascript.electron.mdx
platform-includes/performance/enable-automatic-instrumentation/javascript.mdx
platform-includes/performance/enable-automatic-instrumentation/javascript.react.mdx
platform-includes/performance/enable-automatic-instrumentation/javascript.remix.mdx
platform-includes/performance/enable-automatic-instrumentation/javascript.vue.mdx

This adds docs for `span.setAttribute()` and `span.updateName()` APIs in JS.

feat: Document span methods for JS

---

develop-docs/sdk/client-reports.mdx
develop-docs/sdk/rate-limiting.mdx

Part of https://github.com/getsentry/team-sdks/issues/88

Document span client reports

---

apps/changelog/next.config.mjs
apps/changelog/package.json
next.config.js
package.json
yarn.lock

Bundle analysis for codecov has hit 1.0.0, so upgrading the plugins in the docs repo so we can test.
To accommodate this change, we switch from using the regular webpack plugin, to the nextjs specific codecov webpack plugin: https://github.com/codecov/codecov-javascript-bundler-plugins/tree/main/packages/nextjs-webpack-plugin
While I'm here I also bumped the sentry nextjs sdk version.
Look, I get it. The entity doing business as …

build: Upgrade codecov bundle analysis plugins to 1.0.0

---

docs/platforms/python/integrations/default-integrations.mdx

The `propagate_scope` option of the `ThreadingIntegration` in Python is on by default, but the docs say otherwise.
- Fix ^
- Clarify behavior a bit more
- Fix heading (there is no "Example A")
Fixes https://github.com/getsentry/sentry-docs/issues/10148 …

fix(python): `propagate_scope` is `True` by default

---

docs/platforms/javascript/guides/nextjs/manual-setup.mdx

Document `unstable_sentryWebpackPluginOptions` within `withSentryConfig`
fixes [#11213](https://github.com/getsentry/sentry-docs/issues/11213) …

docs(nextjs): Document unstable_sentryWebpackPluginOptions

---

docs/platforms/native/configuration/backends/index.mdx

The default for Linux used to be breakpad but was changed to crashpad in https://github.com/getsentry/sentry-native/commit/164da7919172b0df9c7b75efbc36e6e897124415 …

Update docs to match native sdk backend defaults

---

platform-includes/performance/add-spans-example/native.mdx
platform-includes/performance/connect-errors-spans/native.mdx
platform-includes/performance/enable-manual-instrumentation/native.mdx

Fixes erroneous syntax on page https://docs.sentry.io/platforms/native/tracing/instrumentation/custom-instrumentation/  (trailing commas, missing semicolons, non-commented ellipsis) …

fix: correct syntax for native-sdk custom trace instrumentation

---

docs/platforms/javascript/common/tracing/instrumentation/automatic-instrumentation.mdx

The ways the function is implemented it can't be used for dropping transactions.
https://github.com/getsentry/sentry-javascript/blob/d265d927ee87d5c50fdebc62da926ddea3c95912/packages/browser/src/tracing/browserTracingIntegration.ts#L241

beforeStartSpan in JS has to always return options

---

docs/platforms/android/session-replay/index.mdx

Assuming this gets merged:
* https://github.com/getsentry/sentry-java/pull/3680
We need to adjust this FAQ once we add support for masking Jetpack Compose views.

android: replay faq

---

docs/concepts/data-management/event-grouping/stack-trace-rules.mdx

These two actions are being removed in https://github.com/getsentry/sentry/pull/76994 since they were never shipped to GA.

Remove mention of sentinel and prefix actions

---

platform-includes/replay/privacy-configuration/javascript.mdx

Resolves: https://github.com/getsentry/sentry-docs/issues/11116

replay: avoid copy paste mistake without reading docs

---

docs/product/releases/health/index.mdx

Users find confusing the terminology Session used here, and seeing their quote of 50 "Session Replays" and how they relate
@lizokm Could you help me phrase this better please?

Release Health: Note on session and session replay

---

src/components/smartLink.tsx

Copy the heading link to the clipboard on click.
We got the feedback from multiple people that they expected this behaviour.
closes https://github.com/getsentry/sentry/issues/77226

feat(headings): Copy link to clipboard on click

---

platform-includes/session-replay/setup/javascript.angular.mdx
platform-includes/session-replay/setup/javascript.astro.mdx
platform-includes/session-replay/setup/javascript.capacitor.mdx
platform-includes/session-replay/setup/javascript.electron.mdx
platform-includes/session-replay/setup/javascript.ember.mdx
platform-includes/session-replay/setup/javascript.gatsby.mdx
platform-includes/session-replay/setup/javascript.mdx
platform-includes/session-replay/setup/javascript.nextjs.mdx
platform-includes/session-replay/setup/javascript.react.mdx
platform-includes/session-replay/setup/javascript.remix.mdx
platform-includes/session-replay/setup/javascript.svelte.mdx
platform-includes/session-replay/setup/javascript.sveltekit.mdx
platform-includes/session-replay/setup/javascript.vue.mdx

Streamline the verify instructions for configuring replay using a JS SDK so they match the in-product docs.
closes https://github.com/getsentry/sentry/issues/77136

feat(replay-javascript): Streamline verify instructions

---

docs/platforms/python/troubleshooting.mdx

For the case when people google "Sentry Connection reset by peer", they maybe land on our docs page. 
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this …

Added possible error messages to network issues page

---

docs/platforms/apple/guides/ios/session-replay/index.mdx
docs/platforms/react-native/session-replay/index.mdx

redaction is enabled (`true`) by default. to disable it we should set it to `false`

fix(docs): fix mobile redaction

---

platform-includes/sourcemaps/overview/javascript.angular.mdx

Just noticed that if you make a link bold, the text color changes, making the link no longer appear purple. Might be a one-off though because we rarely make lists like this afaict
EDIT: Looks like any bold link is no longer coloured purple. Should we fix this? I guess there's rarely a reason to make a link bold so maybe it's also just fine if we leave it as-is

fix(angular): Ensure sourcemaps links have correct text color

---

docs/platforms/javascript/common/configuration/integrations/genericpool.mdx
platform-includes/configuration/integrations/javascript.astro.mdx
platform-includes/configuration/integrations/javascript.aws-lambda.mdx
platform-includes/configuration/integrations/javascript.bun.mdx
platform-includes/configuration/integrations/javascript.fastify.mdx
platform-includes/configuration/integrations/javascript.gcp-functions.mdx
platform-includes/configuration/integrations/javascript.nestjs.mdx
platform-includes/configuration/integrations/javascript.nextjs.mdx
platform-includes/configuration/integrations/javascript.node.mdx
platform-includes/configuration/integrations/javascript.nuxt.mdx
platform-includes/configuration/integrations/javascript.remix.mdx
platform-includes/configuration/integrations/javascript.solidstart.mdx
platform-includes/configuration/integrations/javascript.sveltekit.mdx

Documents https://github.com/getsentry/sentry-javascript/pull/13465 …

feat(js): Add docs for generic pool integration

---

platform-includes/crons/setup/javascript.nextjs.mdx

closes https://github.com/getsentry/sentry-docs/issues/8131
Not sure if the change is actually needed since the documentation for me is good as is.
@lforst feel free to just close this one if you deem it unnecessary 😄

docs(nextjs): update cron docs

---

develop-docs/sdk/javascript/debug-ids.mdx

Adds a page to the develop docs on how files need to be modified for debug IDs to work.
We can later expand on the "why?".

Add instructions of how debug ids need to be injected

---

docs/platforms/php/guides/symfony/configuration/symfony-options.mdx
platform-includes/crons/setup/php.mdx

Php updates

---

docs/platforms/javascript/common/index.mdx

Removes duplicated and somewhat confusing entry that the "Latest JavaScript SDK" was a prerequesite in the getting started guides (second red square in screenshot). For now we have the alert that people should upgrade to v8 SDK. We probably can remove that too, once we have versioned docs or after a couple of months.

fix(js): Remove duplicated "latest SDK" prerequisite

---

docs/platforms/javascript/guides/angular/features/component-tracking.mdx
platform-includes/getting-started-config/javascript.angular.mdx

Following https://github.com/getsentry/sentry/issues/77134 in the product, this PR now also adds code snippets for AppConfig-bsaed Angular apps to our Docs.
I opted for displaying the snippets in tabs next to each other (1 tab for `app.config.ts` vs `app.module.ts`). 
closes https://github.com/getsentry/sentry-docs/issues/8342

ref(angular): Add code snippets for `app.config.ts`-based Angular apps

---

docs/platforms/javascript/guides/angular/features/error-handler.mdx
platform-includes/getting-started-config/javascript.angular.mdx

builds on top of #11356 
This PR adds a new "Angular Features" sub page for the Angular SDK's `ErrorHandler`. Previously, the config options and some edge cases around the handler were undocumented and users had to ask for clarifications in GitHub and Discord. 
The new page now explains 
- what the error handler does / why it's necessary
- a couple of options (omitted the old `reportDialog` options in favour of User Feedback)
- how to handle multiple error handlers
ref https://github.com/getsentry/sentry-javascript/issues/13636

feat(angular): Add documentation for Sentry's `ErrorHandler` 

---

docs/platforms/javascript/common/session-replay/troubleshooting.mdx

Adds some common cases where a replay does not look correct
Closes https://github.com/getsentry/sentry-docs/issues/10886

feat(replay): Add troubleshooting section for "Replay does not look correct"

---

docs/platforms/dart/integrations/http-integration.mdx

Add additional informations what will be sent to sentry in the dart http integration.
closes https://github.com/getsentry/sentry-dart/issues/2130

Specify data collected in HTTP client errors

---

docs/product/sentry-basics/integrate-backend/capturing-errors.mdx

The code snippet no longer uses `push_scope`. This block is incorrect as a result.
Rather than fix the block, I think it makes more sense simply to delete it. I think the page already provides enough context around what we are doing.

docs: Delete inaccurate, confusing block

---

platform-includes/performance/group-transaction-example/javascript.mdx

Since the import above uses `import * as Sentry...`, let's ensure `browserTracingIntegration` is used from `Sentry. browserTracingIntegration`.

docs: fix integration usage to prevent error

---

docs/platforms/javascript/common/sourcemaps/uploading/angular-nx.mdx
docs/platforms/javascript/common/sourcemaps/uploading/angular-webpack.mdx
docs/platforms/javascript/common/sourcemaps/uploading/esbuild.mdx
docs/platforms/javascript/common/sourcemaps/uploading/rollup.mdx
docs/platforms/javascript/common/sourcemaps/uploading/vite.mdx
docs/platforms/javascript/common/sourcemaps/uploading/webpack.mdx
platform-includes/sourcemaps/overview/javascript.svelte.mdx
platform-includes/sourcemaps/overview/javascript.vue.mdx

We do link to org auth tokens further down, but it does not hurt to be explicit there.
Closes https://github.com/getsentry/sentry-docs/issues/9524

feat: Clarify that org auth tokens should be used for bundler plugins

---

.github/workflows/prepare-release.yml

This removes the scheduled release job, since docs is not required to run a self-hosted release …

feat(self-hosted): Remove scheduled release job

---

platform-includes/performance/traces-sampler-as-sampler/ruby.mdx

see 
https://github.com/getsentry/sentry-ruby/issues/2399#issuecomment-2360157202

fix(ruby): Make traces_sampler example safe

---

docs/platforms/javascript/guides/react/features/react-router.mdx

Add docs for error boundaries in react router.
closes [#9337](https://github.com/getsentry/sentry-docs/issues/9337)

docs(react): Add error boundary docs for react-router

---

docs/concepts/search/index.mdx
docs/concepts/search/searchable-properties/issues.mdx
docs/product/explore/traces/index.mdx

Add notes and make updates to relative sections to get ready for new search bar experience GA.

Make updates to search concepts section

---

docs/platforms/javascript/guides/aws-lambda/profiling/index.mdx
docs/platforms/javascript/guides/azure-functions/profiling/index.mdx
docs/platforms/javascript/guides/connect/profiling/index.mdx
docs/platforms/javascript/guides/express/profiling/index.mdx
docs/platforms/javascript/guides/fastify/profiling/index.mdx
docs/platforms/javascript/guides/gcp-functions/profiling/index.mdx
docs/platforms/javascript/guides/hapi/profiling/index.mdx
docs/platforms/javascript/guides/koa/profiling/index.mdx
docs/platforms/javascript/guides/nestjs/profiling/index.mdx
docs/platforms/javascript/guides/node/profiling/index.mdx
includes/profiling-node-runtime-flags.mdx

Documents profiler runtime flags, fixes https://github.com/getsentry/sentry-docs/issues/11128

ref: document all profiler runtime flags

---

docs/platforms/javascript/common/session-replay/issue-types.mdx
docs/product/issues/issue-details/replay-issues/hydration-error.mdx

feat(replay): Remove Beta label from Hydration Error product & setup pages

---

develop-docs/frontend/using-styled-components.mdx

Change styled component definition to come after main component body

develop: update styled order

---

platform-includes/performance/group-transaction-example/javascript.mdx

While reviewing https://github.com/getsentry/sentry-docs/pull/11133, I noticed another inconsistency between v7 and v8 code on this page. This PR changes `BrowserTracing`->`browserTracingIntegration` and slightly adjusts the import in the code snippet above to better fit the browser docs.

ref(js): Adjust and update JS transaction grouping example code

---

docs/platforms/javascript/guides/cloudflare/frameworks/astro.mdx
docs/platforms/javascript/guides/cloudflare/frameworks/index.mdx
docs/platforms/javascript/guides/cloudflare/frameworks/remix.mdx
docs/platforms/javascript/guides/cloudflare/frameworks/sveltekit.mdx

Resolves https://github.com/getsentry/sentry-javascript/issues/13363
Adds framework specific guides or Remix, SvelteKit and Astro, the most asked for frameworks with cloudflare workers.
These guides will become unnecessary when we have support in the individual sdks to automatically add the cloudflare sdk, but for now we need to have these documented.
Look, I get it. The entity doing business as "Sentry" was incorporated in the …

feat(cloudflare): Add framework specific guides

---

platform-includes/getting-started-config/python.mdx

In our SDK docs, for most of the platforms we were missing init SDK code snippet for python in **Configure** section (e.g. [AIOHTTP](https://docs.sentry.io/platforms/python/integrations/aiohttp/)).
This is because we were missing `python.mdx` as a platfrom in our `platform-includes/getting-started-config/` directory.
The code snippet here is the same as for the default Python SDK configuration.

fix(docs): Fix missing python configure SDK code snippet

---

docs/platforms/javascript/common/configuration/integrations/reportingobserver.mdx

closes https://github.com/getsentry/sentry-docs/issues/11392

fix(js): Change ReportingObserver description

---

docs/product/explore/profiling/transaction-vs-continuous-profiling.mdx

docs(profiling): add new cont profiling page docs

---

docs/organization/membership/index.mdx

Add that Org Members can edit project ownership rules

fix: Update org members can edit project ownership rules

---

apps/changelog/src/app/changelog/%5Fadmin/[id]/edit/page.tsx
apps/changelog/src/app/changelog/%5Fadmin/confirm.tsx
apps/changelog/src/app/changelog/%5Fadmin/create/page.tsx
apps/changelog/src/client/components/forms/createChangelogForm.tsx
apps/changelog/src/client/components/forms/editChangelogForm.tsx
apps/changelog/src/server/actions/changelog.ts
apps/changelog/src/server/actions/serverActionPayload.interface.ts

This pr adds [useActionState](https://react.dev/reference/react/useActionState) for all changelog server actions.
Although the payloads are currently not used (they were not used before either), this fixes the type errors we got from passing these actions directly to the forms.

fix(changelog): Use useActionState for server actions

---

docs/concepts/search/searchable-properties/spans.mdx

Adds several missing properties for span searching to the documentation. Check out https://github.com/getsentry/sentry/pull/74787 to see the PR that adds descriptions for these search properties …

docs(tracing): Add missing searchable span properties

---

docs/platforms/javascript/common/sourcemaps/uploading/angular-nx.mdx
docs/platforms/javascript/common/sourcemaps/uploading/angular-webpack.mdx
docs/platforms/javascript/common/sourcemaps/uploading/esbuild.mdx
docs/platforms/javascript/common/sourcemaps/uploading/rollup.mdx
docs/platforms/javascript/common/sourcemaps/uploading/vite.mdx
docs/platforms/javascript/common/sourcemaps/uploading/webpack.mdx

Closes https://github.com/getsentry/sentry/issues/77903

Callout to add .env to .gitignore

---

develop-docs/development/environment/index.mdx

I had a few pain points while running getsentry locally, so I have updated the docs to save someone else (and my future self) the trouble next time getsentry is going to be run locally

Update docs on running getsentry locally

---

docs/platforms/dotnet/common/index.mdx
docs/platforms/elixir/index.mdx
docs/platforms/go/common/index.mdx
docs/platforms/java/common/index.mdx
docs/platforms/javascript/common/index.mdx
docs/platforms/kotlin-multiplatform/index.mdx
docs/platforms/native/common/index.mdx
docs/platforms/powershell/index.mdx
docs/platforms/python/index.mdx
docs/platforms/ruby/common/index.mdx
docs/platforms/unity/index.mdx
docs/platforms/unreal/index.mdx
platform-includes/getting-started-node/javascript.mdx

Users in a new organization who are going through the onboarding process should select a project (if multiple are available) on the issue stream page (the default page when opening sentry.io), rather than clicking on the 'Projects' sidebar item, as suggested in the docs.
Noticed this when dogfooding Sentry using Next.js

ref(onboarding): Update word

---

docs/platforms/javascript/common/configuration/integrations/dataloader.mdx

Documents https://github.com/getsentry/sentry-javascript/pull/13664, released with https://github.com/getsentry/sentry-javascript/releases/tag/8.31.0
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest …

feat(js): Document dataloaderIntegration released with 8.31.0

---

docs/concepts/search/searchable-properties/events.mdx
docs/concepts/search/searchable-properties/issues.mdx
docs/concepts/search/searchable-properties/releases.mdx
docs/concepts/search/searchable-properties/session-replay.mdx
docs/concepts/search/searchable-properties/spans.mdx
docs/product/releases/usage/sorting-filtering.mdx

The Dashboards team got some feedback that the `"release:latest"` filter didn't work as people expected. It was not clear what exactly the filter does. This PR adds a bit of documentation to explain what's going on, and links to it in the appropriate places.

fix(releases): Document `release:latest` filter behaviour

---

docs/product/alerts/alert-types.mdx

Closes https://github.com/getsentry/sentry-docs/issues/11445

Add User Feedback alerts to main Alerts docs page

---

includes/javascript-crons-upsert.mdx

relates to https://github.com/getsentry/sentry-javascript/issues/13820

docs(cron): Add note about luxon timezones

---

docs/platforms/javascript/guides/remix/manual-setup.mdx

The verify step was missing in the manual guide for remix 
**Before**
**After**
closes https://github.com/getsentry/sentry/issues/78337

fix(remix): Add verify step to manual guide

---

develop-docs/sdk/event-payloads/breadcrumbs.mdx

Closes https://github.com/getsentry/sentry-cocoa/issues/4043
Is blocked by the implementation of https://github.com/getsentry/sentry-java/issues/3470
This PR adds the documentation for the new optional `breadcrumb`field `origin` used to identify source of the breadcrumb. …

Adds breadcrumb origin field

---

docs/platforms/python/integrations/django/index.mdx
docs/platforms/python/integrations/flask/index.mdx

This is part of this PR:
https://github.com/getsentry/sentry-python/issues/3528
This should not be merged until the feature has been released. 
Preview:
- https://sentry-docs-git-antonpirker-pythonhttpmethodstocapture.sentry.dev/platforms/python/integrations/flask/#options
- https://sentry-docs-git-antonpirker-pythonhttpmethodstocapture.sentry.dev/platforms/python/integrations/django/#options
Look, I get it. The entity doing …

[Python] Added new option `http_methods_to_capture` to Flask and Django docs.

---

develop-docs/self-hosted/index.mdx

Closes https://github.com/getsentry/self-hosted/issues/3314 …

docs(self-hosted): differences between SaaS and self-hosted

---

docs/platforms/python/tracing/instrumentation/custom-instrumentation/index.mdx

- Add documentation for manual span creation (without context manager)
- Clean up code snippets
- Made all callout boxes the same color, to make page more calm. 
Preview Link: 
https://sentry-docs-git-antonpirker-pythoncustom-tracing-information.sentry.dev/platforms/python/tracing/instrumentation/custom-instrumentation …

[Python] Overhaul "Setup tracing" > "Custom instrumentation"

---

develop-docs/application/dynamic-sampling/outcomes.mdx

Link to rendered page: https://develop-docs-git-feat-ds-outcomes.sentry.dev/application/dynamic-sampling/outcomes/
Document why & how some data types report outcomes in two different categories.

feat(develop): Document indexed outcome categories

---

develop-docs/development/database-migrations/index.mdx

We have been referencing 2.2 version of Django docs which has been outdated for some time now. This is now fixed by referencing the newest version of the docs

fix(migrations): Update the URL of the migrations Django docs

---

docs/platforms/apple/common/configuration/watchdog-terminations.mdx

Explain that some crashes might lead to watchdog termination events.

fix(apple): Add reasons for watchdog terminations

---

docs/platforms/native/guides/minidumps/index.mdx

The docs currently do not describe how the minidump endpoint can be used when sending compressed payloads. This is often necessary when customers produce minidumps bigger than our upload limits.
Fixes #7575.

feat(native): add a compressed minidump endpoint example

---

docs/platforms/python/integrations/aiohttp/index.mdx

Document the Python SDK `aiohttp` integration's new `failed_request_status_codes` option.
Closes [#11417](https://github.com/getsentry/sentry-docs/issues/11417)

docs: Document `aiohttp` `failed_request_status_codes`

---

docs/platforms/python/integrations/fastapi/index.mdx
docs/platforms/python/integrations/starlette/index.mdx

We have slightly changed the `failed_request_status_codes` API for FastAPI and Starlette in https://github.com/getsentry/sentry-python/pull/3563. The old API is still supported, but it is deprecated, so the docs should only document the new API.
Closes [#11434](https://github.com/getsentry/sentry-docs/issues/11434)

docs: Update FastAPI/Starlette `failed_request_status_codes` docs

---

develop-docs/development/environment/index.mdx

tl;dr we had a bespoke form of https devserver support a long time ago https://github.com/getsentry/sentry/pull/60734 but @evanpurkhiser  tried to replace it but then wasn't able to get it to work so was reverted (but evan forgot to update the docs): https://github.com/getsentry/sentry/pull/60673#issuecomment-1832745402

develop: https devserver not supported

---

docs/platforms/javascript/common/best-practices/shared-environments.mdx

closes https://github.com/getsentry/sentry-docs/issues/11479
The section around Inbound Filters was already there but this PR makes the text easier to find by adding a header and giving more explaination.

ref(browser-extension): Rephrase text around Inbound Filters

---

docs/platforms/dotnet/common/enriching-events/scopes/index.mdx
docs/platforms/powershell/enriching-events/scopes/index.mdx
docs/platforms/unity/enriching-events/scopes/index.mdx

Resolves https://github.com/getsentry/sentry-dotnet/issues/3589
**_Note:_** that I had to make the change in 3 separate places as this content appears to be duplicated for dotnet, powershell and unity... all of which seem to be separate "platforms" in the context of the documentation. It wasn't immediately obvious to me how best to refactor this so that it can be maintained once, centrally. Perhaps someone from the docs team can suggest a better approach? 

Added details on IsGlobalModeEnabled to Hubs and Scopes docs

---

docs/platforms/php/guides/laravel/tracing/instrumentation/automatic-instrumentation.mdx

Some automatic tracing features are only available when using a certain version of Laravel, that is now documented better. Also updated some links to packages that were outdated.

Add Laravel version requirements if needed

---

docs/platforms/php/common/configuration/options.mdx

The option works a little different from other SDKs so the wording was updated to be correct.
Fixes getsentry/sentry-php#1782

Fix wording of `trace_propagation_targets` to be correct

---

docs/platforms/php/common/integrations/monolog.mdx
docs/platforms/php/guides/symfony/integrations/monolog.mdx

Documents the Monolog (breadcrumb) handlers and how to configure them in plain PHP and with the Symfony PHP framework.
Fixes #5487 and #7444.

Document how to use the PHP Monolog integration

---

docs/platforms/dotnet/index.mdx

onboarding is incorrectly dictating only `Sentry.Profiling` when the profiling checkbox is chcked. It should add it to the existing `Sentry` package.

onboarding: dotnet list package

---

docs/platforms/react-native/sourcemaps/index.mdx
docs/platforms/react-native/sourcemaps/uploading/expo.mdx

Fixes https://github.com/getsentry/sentry-react-native/issues/3743
This PR adds a note highlighting that source maps are not uploaded for debug mode in Expo. Note that there is a [similar note in the React Native section](https://github.com/getsentry/sentry-docs/blob/master/docs/platforms/react-native/manual-setup/manual-setup.mdx?plain=1#L90). 
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of …

Adds a note that source maps are not uploaded for debug mode in React Native / Expo

---

docs/platforms/apple/common/configuration/app-hangs.mdx

Add docs for the experimental feature app hangs V2 for the Cocoa SDK.

feat(apple): Add docs for app hangs v2

---

docs/contributing/pages/components.mdx
src/components/pageGrid.tsx

This PR re-adds the functionality of the `exclude` prop in the `PageGrid` component. I introduced this option in https://github.com/getsentry/sentry-docs/pull/6404 because I wanted to "feature" certain source maps upload guides for Angular but still display all other guides via `PageGrid`. Looks like this funcitonality got lost in one of the major refactorings of our docs repo. So this PR re-adds the filter functionality.
(Noticed while reviewing #11494)

fix(components): Re-add `exclude` functionality in `PageGrid`

---

develop-docs/development/environment/index.mdx

This brings back the self-signed cert notes from https://github.com/getsentry/sentry-docs/pull/11491 that @evanpurkhiser originally wrote. It wasn't working on it's own, but with a reverse proxy in front it is solving a problem I had.
Depends on https://github.com/getsentry/sentry/pull/78774

docs: Bring back self-signed cert docs and expand with reverse-proxy note

---

src/components/search/index.tsx

Relativizing cross-search results leads to 404 urls on dev-docs.
fixes https://github.com/getsentry/sentry-docs/issues/11411
fixes https://github.com/getsentry/sentry-docs/issues/11391
fixes https://github.com/getsentry/sentry-docs/issues/11381
fixes https://github.com/getsentry/sentry-docs/issues/11317

fix(search): Use correct urls for cross-search results

---

docs/platforms/php/guides/laravel/index.mdx
docs/platforms/php/guides/symfony/index.mdx
docs/platforms/php/guides/symfony/integrations/monolog.mdx

Noticed the Monolog docs are now a bit duplicated and also right there in the getting started guide even though it's not strictly needed. Move everything to the monolog integration and leave a note about it in the installation guide (similar to how we handle this for Laravel).
Also a little tweak to the wording about log channels in Laravel, was a bit verbose.

Merge and move Symfony Monolog docs

---

src/components/codeKeywords/keywordSelector.tsx

fix: Improve dark theme detection on codeKeywords (Dsn selector)

---

docs/platforms/dotnet/common/troubleshooting.mdx

See: 
* https://github.com/getsentry/sentry-dotnet/issues/3648

dotnet: ios changelog xcode 16

---

docs/platforms/apple/common/tracing/instrumentation/automatic-instrumentation.mdx

Add note that TTID/TTFD only work with UIViewControllers and not SwiftUI.

impr(apple): TTID/TTFD only for UIViewControllers

---

docs/platforms/javascript/common/enriching-events/process-isolation/index.mdx
docs/platforms/javascript/common/enriching-events/request-isolation/index.mdx
docs/platforms/javascript/common/enriching-events/scopes/index.mdx
platform-includes/enriching-events/scopes/with-isolation-scope/javascript.mdx

This adds docs for how to use `withIsolationScope`.
Additionally, it also adds a new section (for server SDKs) under "enriching events" describing how process isolation works. We lack docs for this as of now, and this is something users may def. fall into.
It would be ideal if we could somehow auto-fork this for middlewares, but in the meanwhile...
See https://github.com/getsentry/sentry-javascript/discussions/12191#discussioncomment-10667098 for how this affects users.

feat: Add docs about request isolation in Node SDK

---

docs/organization/integrations/issue-tracking/jira/index.mdx
docs/organization/integrations/source-code-mgmt/bitbucket/index.mdx
docs/organization/integrations/source-code-mgmt/github/index.mdx
docs/product/issues/issue-details/performance-issues/index.mdx
docs/security-legal-pii/security/ai-ml-policy.mdx

Incorrectly nested `<tr>` elements as direct children of `<table>` cause hydration errors as `<tbody>` elements get injected by the browser.

fix(platform): table hydration errors

---

docs/concepts/key-terms/tracing/distributed-tracing.mdx

Make a few more tweaks to make this page easier to digest.

Update Distributed Tracing Page

---

develop-docs/development/docs/index.mdx

Developer docs have been moved inside the getsentry/sentry-docs repo. Our docs pages should reflect this.
Somewhat urgent (no specific deadline) – this change corrects incorrect information.

docs: Correct repository information

---

src/components/pageGrid.tsx
src/docTree.ts

Reuse the sidebar sorter on pageGrid

---

docs/platforms/python/integrations/bottle/index.mdx

Specifically, convert the bulleted list to subheadings, and make the wording more specific and clearer.

docs(python): Improve `BottleIntegration` options docs

---

docs/platforms/react-native/profiling/index.mdx

This options was added in https://github.com/getsentry/sentry-react-native/releases/tag/5.33.0 …

feat(react-native): Add `platformProfilers` option

---

docs/platforms/python/integrations/bottle/index.mdx

Document Bottle integration's `failed_request_status_codes` option, added in #3618.

docs(bottle): Document `failed_request_status_codes`

---

docs/platforms/javascript/common/configuration/integrations/amqplib.mdx
platform-includes/configuration/integrations/javascript.astro.mdx
platform-includes/configuration/integrations/javascript.aws-lambda.mdx
platform-includes/configuration/integrations/javascript.bun.mdx
platform-includes/configuration/integrations/javascript.deno.mdx
platform-includes/configuration/integrations/javascript.fastify.mdx
platform-includes/configuration/integrations/javascript.gcp-functions.mdx
platform-includes/configuration/integrations/javascript.nestjs.mdx
platform-includes/configuration/integrations/javascript.nextjs.mdx
platform-includes/configuration/integrations/javascript.node.mdx
platform-includes/configuration/integrations/javascript.nuxt.mdx
platform-includes/configuration/integrations/javascript.remix.mdx
platform-includes/configuration/integrations/javascript.solidstart.mdx
platform-includes/configuration/integrations/javascript.sveltekit.mdx

Documents https://github.com/getsentry/sentry-javascript/issues/13312

docs(js): Add docs for amqplib

---

docs/platforms/android/index.mdx
docs/platforms/javascript/common/index.mdx
docs/platforms/python/index.mdx
docs/platforms/ruby/common/index.mdx
platform-includes/getting-started-primer/javascript.astro.mdx
platform-includes/getting-started-primer/ruby.mdx

Fix some of the onboarding issues in SDK docs

---

docs/platforms/java/common/integrations/quartz.mdx

fix a typo

---

docs/concepts/key-terms/tracing/distributed-tracing.mdx

I found a broken link to the profiling docs and fixed it. …

Fix broken link to profile page

---

src/components/platformFilter/index.tsx
src/components/platformSelector/index.tsx

Based on feedback that the `node` guide is not immediately visible for filtering SDKs for `node`.

fix: Update sorting order for guides on platform filter

---

docs/platforms/javascript/common/crons/index.mdx
docs/platforms/javascript/common/crons/troubleshooting.mdx
platform-includes/profiling/automatic-instrumentation-headers/javascript.nuxt.mdx
platform-includes/profiling/automatic-instrumentation-intro/javascript.nuxt.mdx
platform-includes/profiling/automatic-instrumentation-setup/javascript.nuxt.mdx
platform-includes/session-replay/install/javascript.nuxt.mdx
platform-includes/session-replay/setup-canvas/javascript.nuxt.mdx
platform-includes/session-replay/setup/javascript.nuxt.mdx
platform-includes/user-feedback/example-widget/javascript.nuxt.mdx
platform-includes/user-feedback/install/javascript.nuxt.mdx
platform-includes/user-feedback/sdk-api-example/javascript.nuxt.mdx
platform-includes/user-feedback/setup/javascript.nuxt.mdx

Adds missing code snippets for Nuxt. And excludes Nuxt from "Crons" docs, as we currently have no instrumentation for Nitro Tasks (experimental feature in Nitro).

docs(nuxt): Add missing code snippets

---

docs/platforms/javascript/guides/cloudflare/frameworks/sveltekit.mdx

This PR improves the SvelteKit Cloudflare guide code block a bit by
- fixing formatting of the diff block (TIL, the code block language needs to be set to `<language> diff`)
- re-adding the `handleError` hook just to point out that this remains unchanged from the default setup. (@AbhiPrasad Just to sanity-check: It _does_ remain unchanged, right?)

fix(cloudflare): Improve SvelteKit framework guide code block

---

docs/platforms/apple/common/configuration/options.mdx

Explain that the idleTimeout only applies to user interaction transactions. …

fix(apple): IdleTimeout for iOS

---

docs/platforms/javascript/common/configuration/options.mdx

It's clear elsewhere in the docs (Reference: https://docs.sentry.io/platforms/javascript/configuration/releases/#sessions) that `autoSessionTracking` defaults to `true`. Hopefully saving someone from needing to look around in the future by mentioning this here.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in …

Add note that autoSessionTracking defaults to true

---

redirects.js

The `/organization/integrations/launchdarkly/` path no longer works and should be redirected to `/organization/integrations/feature-flag/launchdarkly/`

fix(integration): Adds a redirect from old launchdarkly doc link to new path

---

docs/platforms/javascript/common/best-practices/multiple-sentry-instances.mdx
docs/platforms/javascript/common/best-practices/shared-environments.mdx

Reverts getsentry/sentry-docs#11577
This was a mistake, integrations can be added directly to a client, just not on the init call.

Revert "docs(js): Fix default integration examples"

---

platform-includes/getting-started-config/javascript.nuxt.mdx
platform-includes/getting-started-primer/javascript.nuxt.mdx
platform-includes/getting-started-sourcemaps/javascript.nuxt.mdx

Updates the docs for the `@sentry/nuxt` beta release

docs(nuxt): Manual setup for beta

---

docs/platforms/javascript/guides/vue/features/pinia.mdx
platform-includes/getting-started-config/javascript.vue.mdx

Documents: https://github.com/getsentry/sentry-javascript/pull/13841

feat(vue): Add Pinia Plugin Docs

---

docs/platforms/unity/configuration/il2cpp/index.mdx

Uploading symbols is critical, we should mention that earlier and make it more prominent
Disabling is the least relevant thing (also why would someone disable, should we say it on the docs?)

unity: il2cpp line number update

---

platform-includes/performance/opentelemetry-setup/ruby.mdx

The Ruby otel gem uses Rack Events rather than a middleware since v0.24.0, so the instructions for ordering middlewares no longer work. …

Update for Ruby otel-rack post v0.24.0

---

develop-docs/application/api/public.mdx

https://develop.sentry.dev/application/api/public/#faqs

fix(docs): Fix markdown bold formatting

---

platform-includes/getting-started-config/javascript.nuxt.mdx

This is already described in the readme of the package, but since the resolution/override is important to know, it's added to the setup page as well.

docs(nuxt): Add "Troubleshoot Server-Side"

---

docs/platforms/javascript/guides/nestjs/features/index.mdx
docs/platforms/javascript/guides/nestjs/index.mdx
docs/platforms/javascript/guides/solid/features/index.mdx
docs/platforms/javascript/guides/solidstart/features/index.mdx
platform-includes/getting-started-primer/javascript.nuxt.mdx

The SDKs are in beta state and this notice can be updated.

docs(solid/nestjs): Update notice about beta state

---

docs/platforms/javascript/common/session-replay/index.mdx

Add a warning message for Angular as it can break customer sites (or lead to performance problems) when using the default change detection strategy due to their monkeypatching of globals (Zone.js)

feat(replay): Add warning message for Angular default Change Detection Strategy

---

develop-docs/sdk/philosophy.mdx

There is some overlap of this in degrade gracefully but we generally feel "stability" by itself deserves a dedicated callout

feat: Add Trust is _1

---

docs/platforms/android/session-replay/index.mdx
docs/platforms/apple/guides/ios/session-replay/index.mdx
docs/platforms/flutter/session-replay/index.mdx
docs/product/explore/session-replay/mobile/index.mdx

Resolves #11555
additionally a minor fix to all other mobile replay docs (copy-pasta)

feat: add flutter replay docs

---

docs/platforms/apple/guides/ios/session-replay/index.mdx

Adding an extra FAQ item for cocoa session replay.

feat(apple): Update cocoa session replay FAQ

---

docs/platforms/javascript/common/install/npm.mdx

Currently the install docs for js browser include the loader script for npm installation. This is potentially misleading.
Before:
After:

docs(js): Update package install page

---

docs/platforms/python/integrations/celery/crons.mdx
docs/platforms/python/integrations/celery/index.mdx

Better description on how and where to setup the Python SDK when you use Celery. 
Preview Link: 
https://sentry-docs-git-antonpirker-pythoncelery-instrumentation.sentry.dev/platforms/python/integrations/celery/
Fixes #9955
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in …

[Python] Updated celery instrumentation documentation

---

docs/platforms/python/integrations/fastapi/index.mdx
docs/platforms/python/integrations/starlette/index.mdx

Better describe `failed_request_status_codes` option.
Preview:
- https://sentry-docs-git-antonpirker-pythonfailedrequeststatuscodes.sentry.dev/platforms/python/integrations/starlette/#options
- https://sentry-docs-git-antonpirker-pythonfailedrequeststatuscodes.sentry.dev/platforms/python/integrations/fastapi/#options
Fixes #11488
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 …

[Python] Document `failed_request_status_codes` option better

---

docs/platforms/javascript/common/user-feedback/configuration/index.mdx
docs/platforms/javascript/common/user-feedback/v7/index.mdx
platform-includes/user-feedback/manual-injection/javascript.mdx
platform-includes/user-feedback/manual-injection/javascript.nextjs.mdx
platform-includes/user-feedback/manual-injection/javascript.react.mdx
platform-includes/user-feedback/manual-injection/javascript.remix.mdx

Create separate feedback code snippets for JS and React.

docs(user-feedback): Add snippet for manual injection

---

docs/platforms/javascript/guides/nuxt/features/pinia.mdx

Documents enabling `trackPinia` in Nuxt. PR: https://github.com/getsentry/sentry-javascript/pull/14047
Vue docs for Pinia: https://github.com/getsentry/sentry-docs/pull/11516

docs(nuxt): Add docs for Pinia plugin

---

docs/product/sentry-basics/distributed-tracing/create-new-project.mdx
docs/product/sentry-basics/distributed-tracing/generate-first-error.mdx
docs/product/sentry-basics/distributed-tracing/index.mdx
docs/product/sentry-basics/distributed-tracing/initialize-sentry-sdk-backend.mdx

All suggested edits have been made.
I have one last bit of feedback for the very end of the tutorial.
When I clicked into traces, there was one trace that had both icons, as described in the tutorial.
I got the error on the front end:
And in the log:
However, the _error_ was not present in the trace in my trace list.
Going to the issues screen, clicking into the generated issue, and clicking on the full trace ID, however, got me to the correct trace:
It's weird because I checked the sample rates and they were all set to 100%.
I just wonder if it's a better happy path if we direct users to the issue screen, and then ask them to click the full trace ID, so we can guarantee the error will be shown in the trace.

Suggested edits for tracing tutorial

---

develop-docs/application/feedback-architecture.mdx

Currently shows like this ^
We should go with `JavaScript` or if pseudo code maybe don't specify it at all (this PR attempts the latter)

develop: UF remove language from snippet

---

app/platform-redirect/page.tsx

closes https://github.com/getsentry/sentry-docs/issues/10517
With this change we display the title and description of the requested page (if it exists).
The risk here is that different platforms might have different titles and descriptions for the same page, and in this PR we just take the first one we find (which is usually .NET I think). I tested out some pages and it seemed to work fine every time.

feat(platform): Display requested title in platform redirect

---

app/[[...path]]/page.tsx
docs/platforms/javascript/common/configuration/options.mdx
docs/platforms/javascript/common/enriching-events/level/index.mdx
docs/platforms/javascript/common/session-replay/privacy.mdx
docs/platforms/javascript/common/sourcemaps/uploading/vite.mdx
docs/platforms/javascript/common/sourcemaps/uploading/webpack.mdx
src/types/frontmatter.ts

We've been asked to update some canonical tags, the request is documented here: 
https://docs.google.com/spreadsheets/d/1jaP6A53p09vxoCLMhaX2RcynERN3PE0AsIAOJYNwq44/edit?usp=sharing 
The codebase didn't have the capability to add custom canonical tags, so I added it through Frontmatter data, and updated the canonicals of the urls in the document above.
To verify:
Go to https://sentry-docs-git-custom-canonical-tags.sentry.dev/platforms/javascript/guides/react/configuration/options/
and inspect, you'll see a canonical tag as follows:
`<link rel="canonical" href="https://docs.sentry.io/platforms/javascript/configuration/options/">`
Go to https://sentry-docs-git-custom-canonical-tags.sentry.dev/platforms/javascript/guides/react/session-replay/privacy/ and inspect and you'll see a canonical …

feat: Custom canonical tags

---

platform-includes/capture-error/apple.mdx

Mention that users don't need to manually call captureException for uncaught NSExceptions on macOS when configured correctly.

impr(apple): Uncaught NSExceptions on macOS

---

docs/product/insights/mobile-vitals/app-starts.mdx

Fix minimum required app versions for the App Starts Module for Mobile Vitals.

fix(apple): Min SDK versions for App Starts

---

develop-docs/relay/transaction-span-ratelimits.mdx

Description of how span and transaction outcomes are (to be) handled within Relay.

feat(relay): Add document describing span and transaction quotas

---

develop-docs/application/feedback-architecture.mdx

Ref
- https://github.com/getsentry/sentry/pull/79790

ref(feedback): add versioning note on feedback issue platform flags

---

app/[[...path]]/page.tsx
develop-docs/application/index.mdx
develop-docs/development/environment/index.mdx
develop-docs/integrations/index.mdx
develop-docs/relay/index.mdx
develop-docs/sdk/index.mdx
develop-docs/self-hosted/index.mdx
develop-docs/self-hosted/releases.mdx
develop-docs/services/index.mdx
docs/account/index.mdx
docs/api/index.mdx
docs/cli/index.mdx
docs/concepts/index.mdx
docs/contributing/pages/frontmatter.mdx
docs/organization/index.mdx
docs/pricing/index.mdx
docs/product/index.mdx
docs/security-legal-pii/index.mdx
src/components/docPage/index.tsx
src/components/githubCTA/styles.module.css
src/components/paginationNav.tsx
src/components/sidebar/sidebarLinks.tsx
src/docTree.spec.ts
src/docTree.ts
src/types/frontmatter.ts
src/types/paginationNavNode.ts

closes https://github.com/getsentry/sentry-docs/issues/11572

feat(platform): Navigation buttons

---

docs/pricing/index.mdx
docs/pricing/quotas/manage-cron-monitors.mdx

This pull request updates the documentation related to cron monitors in the pricing section to provide clearer guidance on quota management and billing practices. The documentation now explains how activating and deactivating monitors affects billing within and across billing periods, including the concept of quota reuse (i.e. billing seat re-allocation) within the same billing period.

chore(billing): Update crons billing documentation

---

docs/platforms/javascript/guides/remix/manual-setup.mdx

Small update to the manual setup docs: As pointed out in https://github.com/getsentry/sentry-javascript/issues/14129, it's easy to miss the source maps upload configuration step since it came after the "Verify" section. This PR moves it to the "Configuration" section, since source map upload is part of SDK setup/configuration. …

ref(remix): Re-order manual setup configuration steps

---

docs/platforms/javascript/common/troubleshooting/index.mdx
includes/terser-plugin-build-error-troubleshooting.mdx

Adds a troubleshooting section for build-errors when using a minifier like terser.
documents https://github.com/getsentry/sentry-javascript/issues/14091

docs(js): Add troubleshooting section on terser

---

platform-includes/capture-error/apple.mdx

Add docs for `UncaughtNSExceptionReporting`, available on Cocoa SDK 8.40.0 and above.

feat(apple): Add UncaughtNSExceptionReporting

---

develop-docs/sdk/expected-features/index.mdx

fix: Typo in expected features for SDKs

---

docs/platforms/javascript/common/configuration/integrations/localvariables.mdx
docs/platforms/javascript/common/configuration/options.mdx

resolves https://github.com/getsentry/sentry-javascript/issues/13394
Makes esm issue with local variables more clear, and updates relevant documentation accordingly.

feat(js): Update esm warning for local variables

---

platform-includes/debug-symbols-apple/_default.mdx
platform-includes/source-context/apple.mdx

Xcode may not detect homebrew installs in a Apple Silicon device.
This problem was raised in [this issue](https://github.com/getsentry/sentry-docs/issues/7597).

feat(Apple): Extra instructions to Upload debug Symbols

---

docs/api/index.mdx
docs/organization/data-storage-location/index.mdx

Give more context on how/when to use our API base domains.
Refs #11058

feat: Add more context on data storage locations and API endpoints

---

docs/platforms/javascript/common/install/esm.mdx
docs/platforms/javascript/common/troubleshooting/index.mdx

feat(js): Document `onlyIncludeInstrumentedModules` option

---

docs/platforms/javascript/guides/astro/manual-setup.mdx

The current wording might be a bit confusing, so the wording was changed slightly to make sure it's not needed to add the file paths in a default setup.

docs(astro): Elaborate on custom config paths

---

docs/platforms/javascript/common/opentelemetry/custom-setup.mdx

This PR updates the Custom Node Otel setup page by:
- showing how users can now add their own HttpInstrumentation (possible since we added `httpIntegration({spans: false})` in 8.35.0
- adding a section discussing ESM loaders and that only one loader hook (either their own or Sentry's) should be registered (we learned about this in https://github.com/getsentry/sentry-javascript/issues/14065)
Look, I get it. The entity doing business …

ref(js): Update custom Node Otel setup docs

---

platform-includes/getting-started-config/javascript.capacitor.mdx

This PR will give the correct snippet for the latest angular and the old version, but also adds the React and Vui snippet that were missing and with that, removed the `others framework`  snippet since we are covering all the frameworks with it.
Close #11085 …

Fix(Capacitor): Expand configure setup to other frameworks

---

platform-includes/user-feedback/setup/javascript.electron.mdx

- Ref: https://github.com/getsentry/sentry-electron/issues/1001
By default Electron denies access to `navigator.mediaDevices.getDisplayMedia()` which is required to capture screenshots used in the feedback widget.
This PR adds some extra docs that detail how to allow these permissions.

feat(electron): Add screenshot permissions config detail

---

docs/product/insights/web-vitals/web-vitals-concepts.mdx

Fixes https://github.com/getsentry/sentry-docs/issues/11601 …

Fix small typo on web-vitals-concepts

---

src/components/docPage/type.scss

Fix for https://github.com/getsentry/sentry-docs/issues/11313
To verify:
Go to https://sentry-docs-git-bold-link-color.sentry.dev/product/performance/filters-display/widgets/#most-time-consuming-queries
You will see that the bolded links are now the same color as the non-bolded links (rgb(106, 95, 193)). The styles do not leak into any other text.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State …

Add CSS rule to fix color of bold links

---

develop-docs/application/architecture.mdx
develop-docs/application/control-silo.mdx
develop-docs/application/dynamic-sampling/outcomes.mdx
develop-docs/application/feedback-architecture.mdx
package.json
src/components/docPage/index.tsx
src/components/mermaid.tsx
yarn.lock

Converts `mermaid` code blocks to svg using `mermaid.js` using a minimal diff
this library comes with the limitation of working client side only (the same way it's handled on Github Readmes for example),
some solutions for node.js come with a whole browser environment to take a screenshot (clunky solution)
on the flip side, client side conversion causes some flickering on the pages with mermaid diagrams,
but this seems to be the most pragmatic way to do this
**Note:** to preview this, go to the developer docs preview under `/application/architecture/`
TODO:
closes #11561

feat: convert mermaid code blocks to SVGs client side

---

package.json
src/components/apiExamples/apiExamples.module.scss
src/components/apiExamples/apiExamples.tsx
src/components/apiPage/styles.scss
src/components/codeBlock/code-blocks.module.scss
src/components/codeTabs.tsx
src/components/docPage/type.scss
yarn.lock

The intent was to unify the syntax highlighting logic for API examples and other docs,
but API examples have specific requirements that prevent us from reusing existing logic
code blocks are usually handled though `CodeTabs`, which adds tabs and manages the corresponding code blocks, but we need more tabs (api responses for example)
The curl bash snippet was possible to handle using a simple `CodeBlock`
I tried to use the same syntax highlighting libraries (using refractor) server side, and gave the API examples code blocks the same look and behavior as elsewhere
verify [here](https://sentry-docs-git-api-syntax-highlighting.sentry.dev/api/alerts/retrieve-a-metric-alert-rule-for-an-organization/)
closes #11093

API examples syntax highlighting

---

.github/labels.yml
apps/changelog/src/client/components/navbar.tsx
src/components/header.tsx
src/components/mobileMenu/index.tsx

This PR addresses https://github.com/getsentry/sentry-docs/issues/11557.
I think I changed all relevant instances of "Sign in" to "Go to Sentry" with my limited contextual knowledge!

Update "Sign in" wording to "Go to Sentry"

---

develop-docs/application/architecture.mdx
develop-docs/application/control-silo.mdx
develop-docs/application/cross-region-replication.mdx
develop-docs/application/dynamic-sampling/outcomes.mdx
develop-docs/application/feedback-architecture.mdx
docs/contributing/pages/charts-diagrams.mdx
docs/contributing/pages/components.mdx
docs/contributing/pages/frontmatter.mdx
docs/contributing/pages/images.mdx
docs/contributing/pages/redirects.mdx
docs/contributing/pages/search.mdx
docs/contributing/pages/variables.mdx
src/components/mermaid.tsx

- Some cleaning up of the white space in the mermaid code snippets.
- Set the `neutral` mermaid theme, that is somewhat readable in light and dark mode. 
New graph theme:
https://develop-docs-git-antonpirker-mermaid-cleanup.sentry.dev/application/architecture/
Documentation on how to use it:
https://sentry-docs-git-antonpirker-mermaid-cleanup.sentry.dev/contributing/pages/charts-diagrams/
Look, I get it. The entity doing business …

Cleaning up mermaid code and made it a bit more readable in dark mode

---

docs/platforms/javascript/common/index.mdx
docs/platforms/javascript/guides/nuxt/features/pinia.mdx
platform-includes/getting-started-next-steps/javascript.nuxt.mdx

Documenting https://github.com/getsentry/sentry-javascript/pull/14138
The docs were already added [here](https://github.com/getsentry/sentry-docs/pull/11638) but reverted because the API was changed.

docs(nuxt): `piniaIntegration` in Nuxt

---

docs/product/insights/queries.mdx

MongoDB support in the Queries module has GA'd, so we can remove the early adopters note.

docs(insights): Remove EA note from Queries re: MongoDB

---

docs/api/auth.mdx

the link https://docs.sentry.io/api/organizations/list-your-organization/ does not exist

fix(docs): fix 404 lint error

---

docs/platforms/javascript/guides/electron/index.mdx

Add a link to electron docs about macos sandboxing. This makes it more clear the issue is on electron, not on us. …

feat(electron): Add link to macos sandboxing restriction

---

docs/platforms/go/common/tracing/instrumentation/caches-module.mdx

Add documentation for instrumenting cache with Go

---

docs/platforms/go/common/integrations/index.mdx

Add Integrations page for Go

---

develop-docs/sdk/telemetry/traces/tracing-without-performance.mdx

This PR adds a develop docs page to our SDK->Telemetry->Tracing section for "Tracing without Performance" (TwP). TWP has been around for some time and most (all?) SDKs support it today. However, we didn't specify the behaviour in develop docs yet. This page specifies the expected high-level behaviour on continuing and propagating traces in TwP as well as attaching trace data to events and envelopes. 
This specification is based on the previously existing internal [Notion doc](https://www.notion.so/sentry/Tracing-without-performance-efab307eb7f64e71a04f09dc72722530) as well as some discussions we recently had around TwP and its implications. 
[Page Preview](https://develop-docs-git-lms-feat-twp.sentry.dev/sdk/telemetry/traces/tracing-without-performance/)

feat(develop): Add Tracing without Performance documentation

---

docs/platforms/javascript/guides/remix/frameworks/hydrogen.mdx
docs/platforms/javascript/guides/remix/frameworks/index.mdx

feat: Add docs for Shopify Hydrogen

---

docs/product/explore/profiling/transaction-vs-continuous-profiling.mdx

Add a section about the tradeoffs between continuous profiling and transaction based profiling.
@lizokm I think this section could inspire the managing profiling spend we talked about. We also have inbound filter rules that we should document

profiling: add managing usage section to profiling mode

---

src/middleware.ts

https://docs.sentry.io/api/organizations/list-your-organizations/ is a broken link.
it's moved to https://docs.sentry.io/api/users/list-your-organizations/ i believe

fix(docs): add redirect for list your organizations api

---

docs/product/sentry-basics/distributed-tracing/initialize-sentry-sdk-backend.mdx
docs/product/sentry-basics/distributed-tracing/initialize-sentry-sdk-frontend.mdx

Adds links to the tracing product page from our tracing tutorial. …

Add links to tracing product page in tracing tutorial

---

docs/platforms/javascript/common/configuration/integrations/console.mdx
docs/platforms/javascript/common/configuration/integrations/nodefetch.mdx
docs/platforms/javascript/common/data-management/sensitive-data/index.mdx
docs/platforms/javascript/common/sourcemaps/uploading/rollup.mdx
docs/platforms/kotlin-multiplatform/data-management/sensitive-data/index.mdx
docs/platforms/native/common/tracing/trace-propagation/dealing-with-cors-issues/index.mdx

See the unchecked rows of https://docs.google.com/spreadsheets/d/1_V8fwvomASiJgXSD4LusD9JrOLZjIG_iCUnvXK3eF2o/edit?usp=sharing for the request.
To verify:
visit: https://sentry-docs-git-more-canonicals.sentry.dev/platforms/javascript/guides/cordova/data-management/sensitive-data/
Inspect and you will see that the canonical tag points to: https://docs.sentry.io/platforms/javascript/guides/koa/data-management/sensitive-data/  as referenced in the spreadsheet.
All five of these link will follow the same behavior.
Thanks in advance for …

Add 5 custom canonical tags based on SEO agency recs

---

src/components/mermaid.tsx

fix mermaid charts in dark mode

---

docs/platforms/javascript/common/best-practices/shared-environments.mdx

This PR adds documentation for a new SDK option introduced in https://github.com/getsentry/sentry-javascript/pull/14147
(to be merged once this option is released)
Further small changes:
- slightly adjusted wording in some paragraphs
- added more headings for better doc structure (table of contents looked bit weird before)
- Changed `<Note>` to `<Alert level="danger">` to highlight the implications of using `Sentry.init` in shared environments
*Make sure you've checked the following before merging …

feat(js): Add `skipBrowserExtensionCheck` documentation

---

develop-docs/application/architecture.mdx

Changed /store to /envelope in one chart (because /store does not exist anymore)

---

develop-docs/development/environment/index.mdx

When switching `devenv` to Colima, need to remove Docker Desktop config. …

Docker Desktop to Colima fix

---

docs/contributing/pages/banners.mdx
src/components/banner/banner.module.scss
src/components/banner/index.tsx
src/components/docPage/index.tsx
src/components/home.tsx

Adds support for multiple banners along with Regex pathname matching and expiration dates 
closes  #11532
**TODO**

feat: Banner pathname regex

---

next.config.js
src/build/resolveOpenAPI.ts

chore: silence fetch cache error due to size limit

---

develop-docs/backend/api/public.mdx

i added a new type of error that i have ran into and some instructions on fix

:wrench: chore(api): add additional troubleshooting instructions to publish api docs

---

docs/platforms/native/advanced-usage/backend-tradeoffs/index.mdx
docs/platforms/native/configuration/backends/index.mdx

I try to cover _some_ of the surface area of the tradeoffs involved when choosing a backend in the Native SDK. This was requested by downstream SDK maintainers (ref: issues below).
Fixes: https://github.com/getsentry/sentry-native/issues/908
Fixes: https://github.com/getsentry/sentry-native/issues/1070 …

feat(native): add backend trade-offs to Advanced Usage

---

platform-includes/getting-started-use/javascript.koa.mdx

`@koa/router` is never used, not needed in this snippet. …

ref(koa): Remove unused koa router import

---

docs/platforms/dart/configuration/releases.mdx
docs/platforms/dart/index.mdx
docs/platforms/flutter/configuration/options.mdx
docs/platforms/flutter/configuration/releases.mdx
docs/platforms/flutter/enriching-events/screenshots/index.mdx
docs/platforms/flutter/integrations/routing-instrumentation.mdx
platform-includes/configuration/auto-session-tracking/flutter.mdx
platform-includes/enriching-events/attach-screenshots/flutter.mdx

flutter: improve session and screenshots docs

---

src/build/open-api/types.ts
src/build/resolveOpenAPI.ts

some Sentry endpoints don't have any parameters, neither `path` nor `query`. An example would be [`DocIntegrationsEndpoint`](https://github.com/getsentry/sentry/blob/5d91f6af15832688bd18839866e07bd2afbb0ed4/src/sentry/integrations/api/endpoints/doc_integrations_index.py#L23)
currently our Open API Resolver makes the assumption that there will always be parameters, so when trying to document parameter-less endpoints, we see the following error:
```
Error: Cannot read properties of undefined (reading 'filter')
summary: apiData.summary,
130 |           descriptionMarkdown: apiData.description,
> 131 |           pathParameters: apiData.parameters.filter(
|                                              ^
132 |             p => p.in === 'path'
133 |           ) as APIParameter[],
134 | …
```

:bug: fix(open api resolver): Add Support for No Parameter API Documentation

---

docs/platforms/javascript/common/configuration/integrations/processThreadsBreadcrumb.mdx

feat(node): Document `processThreadBreadcrumbIntegration`

---

docs/platforms/flutter/session-replay/index.mdx

fix: flutter replay variable names

---

platform-includes/sourcemaps/legacy-troubleshooting/javascript.mdx
platform-includes/sourcemaps/legacy-uploading-methods/javascript.mdx
platform-includes/sourcemaps/troubleshooting/javascript.mdx

There was one too many times where I had to tell people to do this and it resolved their issue.

Recommend to check `symbolicator` if source maps are not working on Self-Hosted

---

includes/react-native-react-navigation-setup.mdx

Correct function misspelling of `reactNavigationIntegration`
This corrects a very minor misspelling that would affect the copy-paste functionality of the docs
- [Sentry Docs …

Update react-native-react-navigation-setup.mdx (reactNavigationintegration  to reactNavigationIntegration) 

---

docs/product/dashboards/widget-builder/index.mdx
docs/product/dashboards/widget-library/index.mdx

We're moving away from the "overlay" terminology and going with "data series".

fix(dashboards): Update overlay to data series

---

docs/platforms/python/configuration/filtering/index.mdx

Refine the Python filtering configuration example to explicitly indicate the return type as `Event | None`, clarifying that the function can return either `Event` or `None`. 
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is …

fix(python-filtering): update filtering example with optional return type in Python

---

includes/react-native-react-navigation-setup.mdx

Fixes incorrect capitalisation of `Sentry.reactNavigationIntegration`

Fix capitalisation

---

develop-docs/sdk/data-model/event-payloads/contexts.mdx
develop-docs/sdk/expected-features/index.mdx

Addw develop docs for feature flags. …

Add develop docs for feature flags

---

docs/platforms/react-native/manual-setup/metro.mdx

Fix spelling

---

docs/platforms/javascript/common/configuration/integrations/launchdarkly.mdx

Documents the integration added in https://github.com/getsentry/sentry-javascript/pull/14207. Equivalent for server-side Python is https://github.com/getsentry/sentry-docs/pull/11675

feat(flags): add browser JS integration docs for Launchdarkly

---

src/components/platformFilter/index.tsx
src/components/platformFilter/style.module.scss

fix: Consistent cursors on guide cards on the home page

---

docs/platforms/apple/common/tracing/instrumentation/automatic-instrumentation.mdx

Explain how the SDK decides on the parent-child relationship for UIViewController transactions and which UIViewController transactions to put on the scope.

feat(apple): Explain UIViewController scope logic

---

docs/product/index.mdx
docs/product/sentry-basics/index.mdx
src/components/home.tsx

Small tweaks to intro navigation for a more intuitive flow

---

docs/platforms/javascript/guides/nestjs/features/index.mdx
docs/platforms/javascript/guides/nestjs/index.mdx

The SDK is stable now.
Ref: https://github.com/getsentry/sentry-javascript/issues/14242

Remove NestJS SDK beta status

---

src/components/card.tsx
src/components/home.tsx

Adds a reuseable card component:

feat(platform): Card component

---

app/platform-redirect/page.tsx

- exclude from search engine index
- add title and descritpion
closes #11740

fix  platform-redirect SEO

---

docs/platforms/javascript/common/configuration/integrations/browsertracing.mdx

This PR fixes one JS snippet from the chapter on the browser tracing integration. `Sentry.browserTracingIntegration()` is a function, not a constructor. like [here](https://docs.sentry.io/platforms/javascript/tracing/).

Fix the snippet from the example on how to set up the browser tracing integration

---

platform-includes/getting-started-primer/javascript.nextjs.mdx

Makes the turbopack wording more clear and accurate.

Reword turbopack section

---

platform-includes/debug-symbols-apple/_default.mdx
src/components/onboarding/index.tsx

Added source-coxtext as onboarding component option in order to manipulate the code snippet related to upload debug symbols.
closes #11810

feat(apple): Add onboarding source context Option

---

docs/platforms/javascript/common/configuration/integrations/debug.mdx
docs/platforms/javascript/common/configuration/integrations/sessiontiming.mdx

These integrations are going to get removed soon.
https://github.com/getsentry/sentry-javascript/issues/14272

Deprecate `SessionTiming` and `Debug` integrations

---

develop-docs/api-server/application-domains/database-migrations/index.mdx

Changing docs for adding columns with defaults.

Update database migration docs

---

platform-includes/getting-started-use/javascript.nestjs.mdx

`@WithSentry` is deprecated.
Ref: https://github.com/getsentry/sentry-javascript/issues/14293

Suggest using `SentryExceptionCaptured` instead of `WithSentry`

---

docs/platforms/javascript/common/configuration/integrations/childProcess.mdx
platform-includes/configuration/integrations/javascript.astro.mdx
platform-includes/configuration/integrations/javascript.aws-lambda.mdx
platform-includes/configuration/integrations/javascript.connect.mdx
platform-includes/configuration/integrations/javascript.fastify.mdx
platform-includes/configuration/integrations/javascript.gcp-functions.mdx
platform-includes/configuration/integrations/javascript.hapi.mdx
platform-includes/configuration/integrations/javascript.nestjs.mdx
platform-includes/configuration/integrations/javascript.nextjs.mdx
platform-includes/configuration/integrations/javascript.node.mdx
platform-includes/configuration/integrations/javascript.nuxt.mdx
platform-includes/configuration/integrations/javascript.remix.mdx
platform-includes/configuration/integrations/javascript.solidstart.mdx
platform-includes/configuration/integrations/javascript.sveltekit.mdx

Ref https://github.com/getsentry/sentry-javascript/issues/14276

Deprecate `processThreadBreadcrumbIntegration`

---

platform-includes/getting-started-use/javascript.nestjs.mdx

Ref: https://github.com/getsentry/sentry-javascript/issues/14292
We don't want to suggest using this class because it is problematic. Also `SentryGlobalGenericFilter` is deprecated but necessary for now.

Suggest not to use `SentryGlobalGraphQLFilter` in newer SDK versions

---

docs/organization/integrations/source-code-mgmt/bitbucket/index.mdx

Update instructions for bitbucket server integration

---

docs/platforms/react-native/enriching-events/identify-user/index.mdx
src/middleware.ts

Patching some borked redirects, to verify ensure these all redirect to working urls:
https://sentry-docs-git-outdated-links.sentry.dev/platforms/java/performance/instrumentation/opentelemetry/
https://sentry-docs-git-outdated-links.sentry.dev/platforms/go/performance/instrumentation/opentelemetry/
https://sentry-docs-git-outdated-links.sentry.dev/platforms/javascript/guides/node/performance/instrumentation/opentelemetry/
https://sentry-docs-git-outdated-links.sentry.dev/platforms/python/performance/instrumentation/opentelemetry/
https://sentry-docs-git-outdated-links.sentry.dev/platforms/ruby/performance/instrumentation/opentelemetry/
Once we fix our Vercel redirects this extra code can be reverted.
- …

Fix bad link and update broken redirects

---

docs/platforms/android/configuration/options.mdx
docs/platforms/java/common/configuration/index.mdx
docs/platforms/java/common/configuration/options.mdx
platform-includes/configuration/auto-session-tracking/android.mdx
platform-includes/configuration/drain-example/java.mdx

We've removed some APIs in Java SDK v8. This PR replaces / removes docs for those.
Here's the changelog: https://github.com/getsentry/sentry-java/blob/8.x.x/CHANGELOG.md
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna …

Update Java SDK v8 deprecation removals

---

platform-includes/crons/setup/java.mdx

Adding documentation on how to check-in to an environment with `CheckInUtils` on Java platforms. Follows a change in the following PR: https://github.com/getsentry/sentry-java/pull/3889 …

Add documentation on how to check-in to an environment with CheckInUtils

---

develop-docs/sdk/telemetry/profiles/sample-format-v1.mdx

We had this odd sampling frequency value in our docs which looks like a typo but it is not. This PR adds a note box to reassure the readers with some explanation and a reference link to why.

feat(profiling): Add explanation for lockstep sampling

---

docs/platforms/dotnet/common/enriching-events/scopes/index.mdx
docs/platforms/powershell/enriching-events/scopes/index.mdx
docs/platforms/unity/enriching-events/scopes/index.mdx
includes/platforms/configuration/options/thread-locality.mdx

Turn a piece of content that's repeated 3 times into an include that can be managed in one place. …

Turn repeated thread locality content into an include

---

docs/product/explore/session-replay/mobile/index.mdx

Fix replay notes about how often we capture replay screenshots. The original was pretty confusing IMO and also not exactly correct (with higher refresh rates) - we don't capture 16ms per second …

fix: replay product docs

---

next.config.js
src/components/header.tsx
tailwind.config.mjs

fix issues behind some noise in the dev console like 
1. 
```
ReferenceError: module is not defined
at file:///Users/abdellah/code/sentry-docs/tailwind.config.js:14:1
at ModuleJobSync.runSync (node:internal/modules/esm/module_job:367:35)
at ModuleLoader.importSyncForRequire (node:internal/modules/esm/loader:325:47)
at loadESMFromCJS (node:internal/modules/cjs/loader:1396:24)
at Module._compile (node:internal/modules/cjs/loader:1529:5)
at Object..js (node:internal/modules/cjs/loader:1709:10)
at Module.load (node:internal/modules/cjs/loader:1315:32)
at Function._load (node:internal/modules/cjs/loader:1125:12)
```
2. `<a>` usage instead of `next/link`
3. the annoying `punnycode` deprecation warning

Clean up dev console warnings

---

docs/platforms/javascript/common/configuration/options.mdx
includes/platforms/configuration/options/warn-before-send-span.mdx
platform-includes/configuration/before-send-span/javascript.mdx

documents https://github.com/getsentry/sentry-javascript/issues/14335

docs(js): Add warning for usage of beforeSendSpan

---

.github/workflows/algolia-index.yml

Indexing stopped working due to https://github.com/oven-sh/bun/issues/15314

fix(ci): Pin bun version for algolia indexing

---

develop-docs/api-server/application-domains/database-migrations/index.mdx

This uses the new operations from
https://github.com/getsentry/sentry/pull/81063
https://github.com/getsentry/sentry/pull/81098

Update docs on how to delete tables and columns

---

docs/platforms/dotnet/index.mdx

To simplify things (referring to .NET Framework 3.5 at the top of the docs isn't helpful)

dotnet: remove note on legacy sdk

---

docs/platforms/javascript/guides/nuxt/features/component-tracking.mdx
docs/platforms/javascript/guides/vue/features/component-tracking.mdx
platform-includes/getting-started-config/javascript.vue.mdx

Based on https://github.com/getsentry/sentry-javascript/issues/14265 and https://github.com/getsentry/sentry-javascript/pull/14385 we are updating how users should enable component tracking for Vue and Nuxt.

Instruct to use the recommended way of using Vue component tracking

---

docs/platforms/native/configuration/transports.mdx

Updated the section on proxy support to match the [upcoming socks5 proxy support feature](https://github.com/getsentry/sentry-native/pull/1063) in sentry-native. …

feat (native): update transport proxy docs

---

docs/platforms/apple/common/configuration/options.mdx

Add docs for the new option enableTracingWhenCrashing.

feat(apple): Add enableTracingWhenCrashing

---

includes/only-error-issues-note.mdx

On `/product/releases/associate-commits/` we mention:
>This feature is only applicable for [error issues](https://docs.sentry.io/product/issues/issue-details/error-issues/) with debug information files, excluding source maps. Other categories of issues (such as [performance issues](https://docs.sentry.io/product/issues/issue-details/performance-issues/)) do not support this feature.
This change adds `Replay Issues` to the list in parens.
**Before**
**After**

feat: Link to Replay Issues when we mention Perf Issues as well

---

develop-docs/development-infrastructure/environment/index.mdx
develop-docs/development-infrastructure/python-dependencies.mdx

adds a link to internal troubleshooting doc + updates the obsoleted `make install-py-dev` with `devenv sync`

devenv: internal troubleshooting

---

develop-docs/ingestion/relay-best-practices.mdx

Closes: https://github.com/getsentry/team-ingest/issues/90
Some best practices for development on Relay.

feat(realy): Add Relay best practices guide

---

docs/product/dashboards/custom-dashboards/index.mdx

Add section for Dashboard Edit Access selector under the custom dashboards section [here](https://docs.sentry.io/product/dashboards/custom-dashboards/#manage-dashboards). …

feat(dashboards): Add docs for Dashboard Edit Access Selector

---

docs/platforms/react-native/session-replay/index.mdx
docs/platforms/react-native/session-replay/privacy/index.mdx

- Need when https://github.com/getsentry/sentry-react-native/pull/4224 is released. (This week/next week as beta.)

Add RN Replay Privacy page

---

src/components/search/index.tsx

use native crypto to generate uuid

---

docs/platforms/android/index.mdx
docs/platforms/android/profiling/index.mdx
docs/platforms/android/profiling/troubleshooting/index.mdx

- Add callouts to [Android](https://docs.sentry.io/platforms/android/) and [Android Profiling](https://docs.sentry.io/platforms/android/profiling) landing pages about current issues with Android Runtime `tracer`
- Make `Profiling` option **off by default** on [Android](https://docs.sentry.io/platforms/android/) landing page
- Add entry to [Android Profiling Troubleshooting](https://docs.sentry.io/platforms/android/profiling/troubleshooting/) page and link to that from the callouts
*Make sure you've …

chore(Profiling): Add callouts and links to Android Profiling troubleshooting info

---

docs/platforms/android/session-replay/index.mdx
docs/platforms/android/session-replay/privacy/index.mdx

Document that it's possible to enable/disable masking via AndroidManifest 

chore(android): Add masking options to AndroidManifest

---

src/components/banner/index.tsx

Add banner to promote launch week on demand content. …

update banner for post-launch week promotion

---

platform-includes/getting-started-config/javascript.angular.mdx
platform-includes/getting-started-install/javascript.angular.mdx

This PR updates the Angular provider setup in the Angular "Getting Started" docs page. In Angular 19, the `APP_INITIALIZER` DI token was deprecated and the new recommended way to provide a dependency (our `TraceService`) at app start is to use `provideAppInitializer` and the `inject` API. 
To be clear, this is not a breaking change. But it makes sense for us to document the most up to date way as well. 
Also made a minor wording change in the compatibility note
Our SDK is comaptible with Angular 19 since v8.40.0, so this PR can be merged whenever it's approved.
- Please give the docs team up to 1 week to review your PR unless you've …

feat(angular): Update SDK provider setup docs for Angular 19

---

docs/organization/integrations/debugging/apigene/index.mdx
docs/organization/integrations/debugging/index.mdx
docs/organization/integrations/debugging/revisedev/index.mdx
docs/organization/integrations/index.mdx

Masinette apigene revisedev

---

docs/platforms/javascript/common/install/esm.mdx
docs/platforms/javascript/common/opentelemetry/custom-setup.mdx
docs/platforms/javascript/common/opentelemetry/using-opentelemetry-apis.mdx

Ref: https://github.com/getsentry/sentry-javascript/issues/14483
- We want to recommend people to register their own loader hooks with a custom otel setup.
- we want to discourage using `addOpenTelemetryInstrumentation()`.

Guide towards v9 for ESM OTEL setups

---

docs/platforms/javascript/common/troubleshooting/index.mdx
docs/platforms/javascript/guides/nuxt/manual-setup.mdx

Adding the manual setup as an extra page (right now, it is the index page - which will be the setup soon).
I also added the troubleshooting items to the troubleshooting page to make it easier to read. As there was already a similar item regarding `pnpm` ([PR here](https://github.com/getsentry/sentry-docs/pull/11931)), I excluded this for Nuxt and added one specifically for Nuxt.
Part of https://github.com/getsentry/sentry-docs/issues/11978
*Make sure you've checked the following before merging your …

docs(nuxt): Add manual setup and troubleshooting

---

docs/platforms/javascript/common/best-practices/micro-frontends.mdx
docs/platforms/javascript/common/session-replay/privacy.mdx
includes/javascript-crons-upsert.mdx

Ref: https://github.com/getsentry/sentry-javascript/issues/14271
Removes all references to `@sentry/types`.
- We will remove `@sentry/types` in the next major so using it is discouraged.
- Having to use it is an anti-pattern in our world.

Free docs from `@sentry/types`

---

docs/security-legal-pii/scrubbing/server-side-scrubbing/index.mdx

After investigating a data scrubbing issue I found out, that the list in the docs differs from the list defined in the relay code.
[list in the current docs](https://github.com/getsentry/sentry-docs/blob/d92a2eba3798e43c824456d1ef55ddc802d607aa/docs/security-legal-pii/scrubbing/server-side-scrubbing/index.mdx?plain=1#L18-L31):
```
- password
- secret
- passwd
- api_key
- apikey
- access_token
- auth
- credentials
- mysql_pwd
- stripetoken
- card[number]
- github_token
- privatekey
- private_key
```
[list in the current relay code](https://github.com/getsentry/relay/blob/a2f9e1100100c93b3a680a45a46379655e4d7f15/relay-pii/src/regexes.rs#L289):
``` rs
password|secret|passwd|api_key|apikey|auth|credentials|mysql_pwd|privatekey|private_key|token|bearer
```
comparing these two lists I updated …

docs(relay): update the data scrubbing default values

---

docs/platforms/javascript/common/opentelemetry/custom-setup.mdx

This PR updates the node docs for custom otel setups to show in more detail how to handle an errors-only setup.

feat(node): Improve docs for errors-only OTEL setup

---

.pre-commit-config.yaml
develop-docs/api-server/config.mdx
src/middleware.ts

The "Configuration" page did not make sense in Application Architecture, because it documentas the configuration options one can set for the API server.  …

Moved configuration pages to where it belongs

---

docs/product/stats/index.mdx

Related to https://github.com/getsentry/sentry/pull/81488

ref(stats): Rename cors to disallowed domain

---

docs/platforms/native/common/configuration/options.mdx

This options is not present in the SDK

Remove attach_stacktrace

---

docs/platforms/javascript/guides/nuxt/features/component-tracking.mdx
docs/platforms/javascript/guides/vue/features/component-tracking.mdx

Ref https://github.com/getsentry/sentry-javascript/issues/14265
Should only be merged once https://github.com/getsentry/sentry-javascript/pull/14526 is released.
Aligns the nuxt component tracking docs with vue.

Streamline nuxt component tracking

---

platform-includes/sourcemaps/primer/javascript.nuxt.mdx

fixes https://github.com/getsentry/sentry-docs/issues/11996

fix(nuxt): Link to correct source maps section

---

platform-includes/performance/configure-sample-rate/javascript.vue.mdx

Follows https://github.com/getsentry/sentry-javascript/pull/14385 and https://github.com/getsentry/sentry-docs/pull/11917. This code block was missed when updating the recommended way of using Vue component tracking. …

Update Vue component tracking docs

---

develop-docs/frontend/using-styled-components.mdx

fix(frontend): missing import

---

docs/product/explore/feature-flags/index.mdx

ref(flags): clarify 'integration documentation' links on product index page

---

docs/concepts/key-terms/sample-rates.mdx

Create a platform-agnostic page to explain the various sample rate options available with Sentry.
See preview on: https://sentry-docs-git-sample-rate-concept.sentry.dev/concepts/key-terms/sample-rates/ …

Add platform-agnostic sample rate page

---

develop-docs/engineering-practices/rust.mdx

Async traits exist for a year now. We should use them.

ref(develop): Update Rust async trait section

---

docs/platforms/native/common/tracing/instrumentation/custom-instrumentation.mdx

Related to the changes in sentry-native https://github.com/getsentry/sentry-native/pull/1093
Updating the docs to reflect the additional explicit timing API for transactions/spans. …

feat(native): docs on extending performance API with explicit timings

---

docs/concepts/search/searchable-properties/events.mdx
docs/concepts/search/searchable-properties/issues.mdx

Prompted by changes in Sentry (https://github.com/getsentry/sentry/pull/81656) where we added `os.distribution_name` and `os.distribution_version` to the searchable properties. …

feat(docs): add Linux distribution name and version to searchable properties

---

develop-docs/sdk/data-model/event-payloads/contexts.mdx

In reference to https://github.com/getsentry/sentry-native/pull/963 ; we need to flatten the payload so the values are properly searchable.
ToDo: …

feat(native): update contexts interface to flatten distribution keys

---

develop-docs/api-server/application-domains/database-migrations/index.mdx

When removing a model that has a hybrid cloud foreign key you can't set `db_constraint` to False, but instead you need to make the column nullable.

ref(migrations): Add instructions for hybrid cloud foreign key

---

docs/organization/integrations/feature-flag/launchdarkly/index.mdx

fix(flags): Update change tracking docs to highlight new settings page

---

develop-docs/self-hosted/troubleshooting.mdx

Refer to https://github.com/getsentry/self-hosted/issues/3388#issuecomment-2453568273
cc @hubertdeng123 @joshuarli  …

docs(self-hosted): manually clean sentry-data

---

develop-docs/sdk/data-model/event-payloads/contexts.mdx

As discussed `span_id` is always required. Update docs to clarify a random span_id can be provided if none is available. …

docs(tracing) clarify span_id attribute

---

docs/platforms/javascript/guides/node/profiling/index.mdx

`Sentry.profiler.startProfiling` is not a function:
TypeError: Sentry.profiler.startProfiling is not a function
at file:///root/workspace/meteogram/instrument.mjs:46:17
at ModuleJob.run (node:internal/modules/esm/module_job:234:25)
at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:118:9)

fix(js): Correct function names for `startProfiler`

---

app/platform-redirect/page.tsx
app/platform-redirect/utils.spec.ts
app/platform-redirect/utils.ts

Closes an open redirect for platform-redirects by adding better sanitising on the passed next param

fix(platform): Sanitise next in platform-redirect

---

docs/platforms/javascript/common/troubleshooting/index.mdx
docs/platforms/javascript/guides/nuxt/install/dynamic-import.mdx
docs/platforms/javascript/guides/nuxt/manual-setup.mdx
platform-includes/getting-started-install/javascript.nuxt.mdx

Improves some sections of the docs based on feedback from @whitep4nth3r 

feat(nuxt): Improve docs based on feedback

---

docs/platforms/unreal/index.mdx
platform-includes/getting-started-config/javascript.svelte.mdx
platform-includes/getting-started-config/unity.mdx
platform-includes/getting-started-config/unreal.mdx

Just a minor upgrade, stumbled upon this while using the guide.

docs(svelte): Update getting started snippet

---

src/components/platformSelector/index.tsx
src/components/sidebar/index.tsx

fixes #11973
`router.push()` works on mobile Next 15

Keep platform selector in sync with pathname

---

docs/platforms/apple/common/data-management/sensitive-data/index.mdx

Add the correct code samples for scrubbing data on Apple and clarify that transactions go through beforeSend.

fix(apple): Scrubbing Data Code Samples

---

platform-includes/getting-started-use/javascript.nestjs.mdx

Hopefully makes it a bit more clear how specific error filters need to be transformed so that they will capture errors.
closes https://github.com/getsentry/sentry-javascript/issues/14580

Clarify NestJS error filters

---

docs/platforms/unreal/configuration/environments.mdx

Reodered things a bit and added the values mentioned by @tustanivsky on the linked ticket
Resolves:
* https://github.com/getsentry/sentry-docs/issues/11056

unreal: clarify environment defaults

---

docs/platforms/python/configuration/options.mdx

Documentation of two new options that where introduced here: https://github.com/getsentry/sentry-python/pull/3673 …

Added new options to control what frames to add to the stack trace

---

docs/platforms/javascript/common/configuration/integrations/launchdarkly.mdx
docs/platforms/javascript/common/configuration/integrations/openfeature.mdx

Clarify for open beta users they have to use this specific version of @sentry/browser, before 8.43 comes out
Example (banner is same for OpenFeature + every platform):

ref(flags): temporarily mention beta release version in JS integration docs

---

docs/concepts/data-management/event-grouping/stack-trace-rules.mdx

Add note to the stack trace rules to explain that a subset of those rules will now be applied to profiles as well.
----------

ref(profiling): add note for profiles stack trace rules

---

docs/platforms/php/common/profiling/troubleshooting.mdx

I have been trying to get tracing and profiling to work. I followed the guide, including the troubleshooting guide, but I still didn't see any traces in the performance tab. I ended up [asking on Discord](https://discord.com/channels/621778831602221064/1245295898594902077/1313882179121446954) where I got a quick reply to try to enable logger. From there, I could quickly see that the transactions were being dropped due to an exceeded quota. From there, it was easy to see that some other projects under our organization have used up the quota.
- Please give the docs team up to 1 week to review your PR unless you've added an urgent due …

docs(profiling): add SDK logger as a step to troubleshooting

---

docs/platforms/javascript/common/install/esm-without-import.mdx
docs/platforms/javascript/guides/nuxt/install/cli-import.mdx
docs/platforms/javascript/guides/nuxt/install/dynamic-import.mdx
docs/platforms/javascript/guides/nuxt/install/top-level-import.mdx
docs/platforms/javascript/guides/nuxt/manual-setup.mdx

Documenting based on this PR: https://github.com/getsentry/sentry-javascript/pull/14553
Dynamic `import()` is not the default anymore. Docs are changed accordingly 

feat(nuxt): Use --import as the default installation method

---

platform-includes/configuration/before-send/ruby.rails.mdx

fixes https://github.com/getsentry/sentry-docs/issues/12082

fix(ruby): Fix missing require for ParameterFilter

---

docs/platforms/javascript/common/troubleshooting/index.mdx

closes https://github.com/getsentry/sentry-javascript/issues/8982

docs(nextjs): Add troubleshooting section for nx

---

docs/platforms/javascript/common/configuration/integrations/custom.mdx
docs/platforms/react-native/integrations/custom.mdx

fix custom integration type 404

---

develop-docs/self-hosted/index.mdx
develop-docs/self-hosted/releases.mdx

Closes https://github.com/getsentry/self-hosted/issues/3393
cc @hubertdeng123 @joshuarli  …

docs(self-hosted): explicitly specify how to handle .env.custom file

---

docs/platforms/javascript/common/configuration/integrations/launchdarkly.mdx
docs/platforms/javascript/common/configuration/integrations/openfeature.mdx

Reverts getsentry/sentry-docs#12073 now that release 8.43 is live and linked in the sidebar. Also removes the npm links to @sentry/browser - these pages are for specific platforms, so users should refer to the side bar "Package Details"

ref(flags): Revert "temporarily mention beta release version in JS integration docs"

---

docs/product/explore/profiling/transaction-vs-continuous-profiling.mdx
includes/profiling-node-runtime-flags.mdx

Method name was wrong as identified [here](https://github.com/getsentry/sentry-javascript/issues/14561#issuecomment-2522295906), the correct naming is startProfiler and stopProfiler

ref(profiling) fix method name

---

docs/platforms/javascript/common/troubleshooting/index.mdx

ref https://github.com/getsentry/sentry-javascript/issues/10468
Adds a troubleshooting section to nextjs for the OOM issue while building.

docs(nextjs): Add troubleshooting for OOM

---

docs/platforms/android/data-management/sensitive-data/index.mdx
docs/platforms/apple/common/data-management/sensitive-data/index.mdx
docs/platforms/dart/data-management/sensitive-data/index.mdx
docs/platforms/dotnet/common/data-management/sensitive-data/index.mdx
docs/platforms/elixir/data-management/sensitive-data/index.mdx
docs/platforms/flutter/data-management/sensitive-data/index.mdx
docs/platforms/go/common/data-management/sensitive-data/index.mdx
docs/platforms/java/common/data-management/sensitive-data/index.mdx
docs/platforms/javascript/common/data-management/sensitive-data/index.mdx
docs/platforms/php/common/data-management/sensitive-data/index.mdx
docs/platforms/powershell/data-management/sensitive-data/index.mdx
docs/platforms/python/data-management/sensitive-data/index.mdx
docs/platforms/react-native/data-management/sensitive-data/index.mdx
docs/platforms/ruby/common/data-management/sensitive-data/index.mdx
docs/platforms/rust/common/data-management/sensitive-data/index.mdx
platform-includes/sensitive-data/scrubbing-data/native.mdx

Explain that most SDKs will add the HTTP query string and fragment as a data attribute to spans, as pointed out in the [develop docs](https://develop.sentry.dev/sdk/expected-features/data-handling/#spans).
Related to https://github.com/getsentry/sentry-docs/pull/12025.

feat: Scrubbing HTTP Data from HTTP Spans

---

docs/platforms/rust/index.mdx

https://github.com/getsentry/sentry-rust/issues/574

Solves sentry-rust 574

---

docs/platforms/javascript/common/configuration/integrations/vercelai.mdx
docs/platforms/javascript/common/configuration/vercelai.mdx

Documents Vercel AI integration added with https://github.com/getsentry/sentry-javascript/pull/13892 …

feat: Document Vercel AI integration

---

docs/platforms/dotnet/common/tracing/instrumentation/custom-instrumentation/caches-module.mdx
docs/platforms/go/common/tracing/instrumentation/caches-module.mdx
docs/platforms/java/common/tracing/instrumentation/custom-instrumentation/caches-module.mdx
docs/platforms/javascript/common/tracing/instrumentation/custom-instrumentation/caches-module.mdx
docs/platforms/php/common/tracing/instrumentation/caches-module.mdx
docs/platforms/php/common/tracing/instrumentation/queues-module.mdx
docs/platforms/php/common/tracing/instrumentation/requests-module.mdx
docs/platforms/python/tracing/instrumentation/custom-instrumentation/caches-module.mdx
docs/platforms/python/tracing/instrumentation/custom-instrumentation/queues-module.mdx
docs/platforms/python/tracing/instrumentation/custom-instrumentation/requests-module.mdx
docs/platforms/ruby/common/tracing/instrumentation/custom-instrumentation/caches-module.mdx
docs/product/insights/index.mdx
src/components/pageGrid.tsx

We missed migrating some links with the new Insights menu.

fix(insights): links were pointing to old dashboards

---

platform-includes/user-feedback/pre-requisites/javascript.mdx

This adds a note that User Feedback requires browsers that support the [Dialog element](https://caniuse.com/mdn-html_elements_dialog) as we use the element + its APIs to show the feedback modal.

feat(feedback): Add requirement note for Dialog element

---

docs/product/performance/index.mdx

Update documentation for performance issues to call out impact on quota. Fixes https://github.com/getsentry/sentry-docs/issues/9136

docs(performance): Add note about performance issue quota

---

docs/product/releases/index.mdx

Clarify the behavior for "resolved in next release", addressing feedback from [#78325](https://github.com/getsentry/sentry/issues/78325)

docs(releases): Clarify behavior for "Resolved in next release"

---

apps/changelog/package.json
apps/changelog/src/server/actions/changelog.ts
yarn.lock

Bumps @auth/prisma-adapter, previous version included a vulnerable version of `cookie`.
ref https://github.com/getsentry/sentry-docs/security/dependabot/146

deps(changelog): Bump `@auth/prisma-adapter`

---

docs/platforms/javascript/common/best-practices/micro-frontends.mdx

Adds a section about the importance of having SDKs aligned to the same version in MFE setups plus an optional workaround for when this is not feasible. I opted to only link to the workaround posted in GH for the moment because we're still awaiting confirmation that this works and it requires some deep SDK behaviour intervention from users. We might revisit this and provide a better abstraction for it on demand.
- [Sentry Docs …

ref(js): Add section about version alignment to Micro Frontends documentation

---

docs/platforms/android/tracing/instrumentation/automatic-instrumentation.mdx
docs/platforms/android/troubleshooting/index.mdx

added gradle plugin auto-instrumentation issue with minified libraries to troubleshooting page
changed Android TTFD timeout from 30 to 25 seconds
Closes https://github.com/getsentry/sentry-android-gradle-plugin/issues/768
Relates to https://github.com/getsentry/sentry-java/issues/3831

Troubleshoot android minified libraries autoinstrumentation

---

.github/workflows/bump-api-schema-sha.yml
.github/workflows/prepare-release.yml

The `getsentry-release` is a GitHub bot account that is used in various automation, and the `${{ secrets.GH_RELEASE_PAT }}` is a personal access token from that bot account. We are using a regular GitHub account as a bot while it should be a non-human account since there are no humans behind it. Hence, we are replacing it with a GitHub App. 
the `bump-api-schema-sha.yml` was also using the `GH_RELEASE_PAT` token, but since it's not related to release, I replaced it with the `getSantry` app
Functionality wise, there will be no difference. 
More details: https://www.notion.so/sentry/DACI-Replace-GitHub-bot-accounts-with-GitHub-Apps-getsentry-release-15109965d1204a91b9be71c49e8b66e0?pvs=4
#skip-changelog

feat(release): Replace release bot with GH app

---

develop-docs/sdk/data-model/event-payloads/exception.mdx

This PR clarifies/expands on the impact and applicability of the `synthetic` flag in the exception `mechanism`:
- adds impact on issue grouping
- adds another concrete use case when to set the flag …

ref(develop): Clarify `synthetic` flag in exception mechanism

---

docs/product/dev-toolbar/setup.mdx

toolbar: Fix link to MockFeatureFlagAdapter and nits

---

docs/platforms/python/tracing/instrumentation/custom-instrumentation/index.mdx

- closes: https://github.com/getsentry/sentry/issues/79811

fix(python): tracing wording improvements

---

redirects.js

[After we reverted the name change from api-server to backend](https://github.com/getsentry/sentry-docs/pull/12141), links on google, etc. don't work for the time being. This PR adds a redirect from api-server to backend to restore functionality.

chore: add redirect from api-server to backend

---

platform-includes/user-feedback/install/javascript.mdx

Closes https://github.com/getsentry/sentry-docs/issues/12138
We did not really document well how to use user feedback with the loader. So I expanded this section in the docs to properly explain how it can be used.

fix(js): Fix docs for using feedback with the Loader

---

CONTRIBUTING.md

It took me quite a while to figure out how to run the developer docs locally. I would expect that info also in the Contributing.md.
Explain how to start the dev server for the developer docs in the Contributing.md and not just the environment.mdx.

chore: Mention developer docs in Contributing

---

docs/product/insights/frontend/web-vitals/index.mdx

Performance Scores no longer require a minimum set of webvitals to calculate. Removes this text to accurately reflect this.

chore(webvitals): Updates text around required Webvitals for Performance Score

---

src/build/open-api/types.ts
src/build/resolveOpenAPI.ts
src/components/apiExamples/apiExamples.tsx

Some of our endpoints require customers to use region domains in order to have APIs work correctly across DE and US regions. I've already updated those endpoints in getsentry/sentry#82159.
Refs getsentry/sentry#81232

feat(api) Add ability for endpoint specific domains

---

develop-docs/backend/application-domains/feature-flags/flagpole.mdx

Adds a new section to Flagpole's documentation describing the flag removal process.

chore(flagpole): Adds docs for flagpole feature removal

---

develop-docs/backend/application-domains/database-migrations/index.mdx

Updates develop docs Database Migrations page to clarify the caveats for adding any type of constraint (as opposed to just not null).

feat(develop): Clarify adding constraints

---

docs/product/dev-toolbar/setup.mdx

Separating the Dev/Staging recommendations from the Production recommendations on conditionally including the Dev Toolbar.
The code for conditionally including in the Production environment is so dependent on the application, we should have them be separate.

Update devl-toolbar setup.mdx

---

docs/platforms/javascript/common/tracing/instrumentation/custom-instrumentation/index.mdx

To be merged only once https://github.com/getsentry/sentry-javascript/pull/14291 was released
This PR:
- adds documentation for `Sentry.updateSpanName`, a helper function we (unfortunately) had to add to the JS SDK
- rewords the previous `span.updateName` documentation, leaving the shortcomings of the previous way to update a span name in Node in place
- does not touch the React Native docs because I think it's fine for RN users (given it's based on `@sentry/react`) to continue using `span.updateName`. Happy to change this if reviewers have different opinions
- Please give the docs team up to 1 week to review your PR unless you've …

feat(js): Add docs for `updateSpanName`

---

docs/platforms/javascript/common/enriching-events/transaction-name/index.mdx
platform-includes/enriching-events/set-transaction-name/javascript.mdx
platform-includes/performance/beforeNavigate-example/javascript.mdx

⚠️ to be merged after #11824 (which this PR is based on)
This PR rewrites the "Enriching Events"->"Transaction Name" page which is was fairly outdated and misleading for JavaScript. 
Most importantly, it now mentions that `scope.setTransactionName` only applies to error events and has nothing to do with spans and root span names. The page now disambiguates the two concepts and lists ways how to update both names individually. 
As an experiment, I added a "Further Information" section at the bottom of the page which tries to explain the historic context of why these two names are convoluted and appear ambiguous. I'm happy to remove this but this question and the confusion around the two names is coming up repeatedly on GitHub, in Discord as well as internally. While reviewing, feel free to …

ref(js): Rewrite outdated "Transaction Name" documentation

---

platform-includes/enriching-events/breadcrumbs/automatic-breadcrumbs/dart.mdx

Dart: link to Dio integration for breadcrumbs

---

docs/platforms/android/enriching-events/attachments/index.mdx
docs/platforms/apple/common/enriching-events/attachments/index.mdx
docs/platforms/dart/enriching-events/attachments/index.mdx
docs/platforms/dotnet/common/enriching-events/attachments/index.mdx
docs/platforms/flutter/enriching-events/attachments/index.mdx
docs/platforms/java/common/enriching-events/attachments/index.mdx
docs/platforms/kotlin-multiplatform/enriching-events/attachments/index.mdx
docs/platforms/powershell/enriching-events/attachments/index.mdx
docs/platforms/unity/enriching-events/attachments/index.mdx
docs/platforms/unreal/enriching-events/attachments/index.mdx
platform-includes/enriching-events/add-attachment/javascript.mdx

add specific info in the docs about which MIME types are supported / renderable for event attachments.
based on `previewAttachmentTypes.tsx`:
https://github.com/getsentry/sentry/blob/bf167f9145882b76bc1f38eb4b7f62bedf6d9b71/static/app/components/events/attachmentViewers/previewAttachmentTypes.tsx#L7-L32
closes https://github.com/getsentry/sentry-docs/issues/8471

ref(docs): add info about mimetype in docs

---

docs/platforms/android/index.mdx
docs/platforms/apple/common/index.mdx

Ensures that Profiling (feature description, feature selector, config snippet) is only shown on supported platforms (iOS, macOS). Also fixes a small glitch with incorrect line highlights in snippets.
This PR is based on the changes in https://github.com/getsentry/sentry-docs/pull/12191, so we should get the other one merged first.
fixes https://github.com/getsentry/sentry-docs/issues/12089 …

chore(Apple): Show Profiling only on supported platforms' landing pages

---

app/layout.tsx
src/components/search/index.tsx
vercel.json

closes https://github.com/getsentry/sentry-docs/issues/11934

feat(platform): Kapa.ai integration

---

src/components/mobileMenu/index.tsx
src/components/search/index.tsx

follow up to https://github.com/getsentry/sentry-docs/issues/11934

fix(platform): Update mobile menu to display AI

---

docs/platforms/javascript/guides/react/features/react-router/v6.mdx
docs/platforms/javascript/guides/react/features/react-router/v7.mdx

- Updates the warning on order of calling react router related functions.
- Updates a reference to a legacy function

docs(react): Update warning on react router library docs

---

develop-docs/sdk/telemetry/traces/index.mdx

For the invariant mentioned on the page to hold true, the `sample_rand` cannot be `1.0` but instead has to be less. …

Exclude 1.0 from allows values for `sample_rand`

---

docs/platforms/android/session-replay/index.mdx
docs/platforms/apple/guides/ios/session-replay/index.mdx
docs/platforms/flutter/session-replay/index.mdx
docs/platforms/react-native/session-replay/index.mdx
src/components/banner/index.tsx

We'd like to let beta users know ASAP that the beta is ending soon so that we can get more people to get started NOW. On January 6th we will have additional updates in a separate PR for the GA.

Mobile replay beta almost over banner

---

platform-includes/getting-started-config/javascript.react-router.mdx

This PR just quickly fixes the session replay sample rate option keys in the React Router guide.  …

fix(react-router): Fix replay sample rate option names

---

platform-includes/getting-started-config/javascript.react-router.mdx

One more quick PR to use consistent file names for the server instrumentation file. No particular strong opinions if we should 
go with `instrument.server.mjs` or `instrument.mjs`, just that we should be consistent. 
Feel free to change the name around as you see fit :) …

fix(react-router): Use consistent file names for `instrument.server.mjs`

---

docs/platforms/python/feature-flags/index.mdx

This links to the wrong platform. We shouldn't mention this integration at all until it's live, https://github.com/getsentry/sentry-docs/pull/12152 is on standby for this

fix(flags): rm link to custom integration for python

---

develop-docs/self-hosted/index.mdx

Fixes getsentry/self-hosted#3441.

fix(self-hosted): Add difference btw SaaS for iOS symbolication

---

docs/platforms/javascript/common/configuration/integrations/featureflags.mdx
docs/platforms/javascript/common/configuration/integrations/launchdarkly.mdx
docs/platforms/javascript/common/configuration/integrations/openfeature.mdx
docs/platforms/javascript/common/feature-flags/index.mdx
docs/platforms/python/feature-flags/index.mdx
docs/platforms/python/integrations/launchdarkly/index.mdx
docs/platforms/python/integrations/openfeature/index.mdx

As we add and release more integrations, the versioning will be different for each one, so we should not specify it in the list of integrations.

ref(flags): move min version requirements from index to integration docs

---

develop-docs/self-hosted/troubleshooting.mdx

Add `DAY` in the `INTERVAL` keyword used to manually purge the nodestore_node table to prevent accidentally purging (almost) the entire table, since the days would be used as seconds.
When manually purging events from the nodestore_node table, the example request in the documentation makes use of the `INTERVAL`  keyword, referencing the `$SENTRY_RETENTION_DAYS` variable, but without specifying the `DAY` keyword to `INTERVAL`, which can lead people to input days that will be interpreted as seconds by PostgreSQL.
Thanks in advance for …

Update troubleshooting.mdx - Add `DAY` when using `INTERVAL` while referencing the `SENTRY_RETENTION_DAYS` variable

---

docs/platforms/javascript/common/tracing/instrumentation/automatic-instrumentation.mdx

This PR updates the browser JS "Automatic Instrumentation" docs:
1. The `heartbeatTimeout` option does not exist anymore, I replaced it with the new `childSpanTimeout`. This has been replaced in v8.
2. We used "transaction" everywhere still, I rewrote this to use the term span instead.
Closes https://github.com/getsentry/sentry-javascript/issues/14805

feat(js): Update automatic instrumentation docs

---

docs/platforms/python/integrations/index.mdx

Fixes a discrepancy with other integration headings. There's no platform icon for FF provider so let's just use Python for now
Before:
After:

ref(flags): reduce heading size and fix platform icons on python/integrations/

---

docs/platforms/javascript/common/configuration/integrations/graphql.mdx

docs for https://github.com/getsentry/sentry-javascript/pull/13248
closes https://github.com/getsentry/sentry-docs/issues/12080

feat(graphql): Document `useOperationNameForRootSpan`

---

app/layout.tsx

closes https://github.com/getsentry/sentry-docs/issues/12225

feat(platform): Add privacy policy and example questions to ai widget

---

docs/platforms/javascript/common/user-feedback/configuration/index.mdx

Adds a note that shorthand margin values can be passed to feedback css customization
ref https://github.com/getsentry/sentry-javascript/issues/14539

docs(js): Add note for shorthand margin

---

docs/product/dev-toolbar/faq.mdx

docs: Add FAQ page for the Dev Toolbar

---

develop-docs/self-hosted/releases.mdx

From the convo in https://github.com/getsentry/self-hosted/issues/3475#issuecomment-2562170668
cc: @hubertdeng123 @bc-sentry  …

docs(self-hosted): state versions with known issues

---

docs/organization/integrations/feature-flag/launchdarkly/index.mdx

some clarifications/updates to the webhook setup docs

ref(flags): clarify launchdarkly webhook setup docs

---

develop-docs/application-architecture/feedback-architecture.mdx
develop-docs/sdk/data-model/envelope-items.mdx
develop-docs/sdk/expected-features/index.mdx

Closes https://github.com/getsentry/sentry/issues/64700

feat(feedback): document new feedback envelope format and rename old format

---

docs/platforms/apple/guides/ios/session-replay/customredact.mdx

Part of:
* https://github.com/getsentry/sentry-docs/pull/12202

replay mobile iOS not experimental

---

develop-docs/application-architecture/feedback-architecture.mdx
develop-docs/sdk/data-model/envelope-items.mdx
develop-docs/sdk/expected-features/index.mdx

Reverts getsentry/sentry-docs#12188
Wanted to loop in SDK folks before merging, sorry to rush it

Revert "feat(feedback): document new feedback envelope format and rename old format"
